### ISSUE TITLE
fork执行顺序bug

### ISSUE THREAD

**Issue by kueiwoodwolf** [cloudwu/skynet#1000]
skynet.fork的执行顺序可能跟调用fork的顺序不一致，因为next返回的顺序是不确定的， 应该用table.remove(fork_queue, 1)

![image](https://user-images.githubusercontent.com/8786265/56847849-c0b6a080-6913-11e9-92af-0d27b7948fb3.png)

**Comment by cloudwu** [comment]
fork 并未做次序承若。

**Comment by cloudwu** [comment]
我明天改成有序的。

另外，麻烦学习一下 markdown 以及 github 用法，此处完全不应该贴图片。

**Comment by kueiwoodwolf** [comment]
ok， 谢谢~
