### ISSUE TITLE
可否给skynet.socket增加查询发送缓冲区未发送字节数的函数

### ISSUE THREAD

**Issue by jxlczjp77** [cloudwu/skynet#1004]
我尝试用skynet做消息推送业务，有个问题是消费者阻塞或者读取速度变慢，推送服务的业务代码没有办法得到反馈，继续推送会造成大量消息积压在发送缓冲区。
当然目前也有解决方法，就是在业务层增加一个ack确认协议，不过如果底层能增加这个查询功能的话可以更好的调整推送速率。

**Comment by jxlczjp77** [comment]
socket.warning设置的回调函数可以得到缓冲区告警通知，在这里我尝试降速发送，后续再慢慢递增发送速度，但还是没有很好的方法来评估降速后是否缓冲区没有继续变大。

**Comment by cloudwu** [comment]
过载 warning 信号后，一旦缓冲区发完会还推送一个 0 的 warning 信号，你可以靠这个测速。

**Comment by jxlczjp77** [comment]
实际测试确实发现 size 为 0 的 warning 信号，原来是这个原理，非常感谢。
