### ISSUE TITLE
关于kqueue的eof导致socket.lua读取报错的问题

### ISSUE THREAD

**Issue by keventan** [cloudwu/skynet#1014]
【问题场景】
	使用skynet模拟客户端进行压测。
	skynet版本：v1.2.0 (2018-11-6)
	服务器系统版本：CentOS release 6.2。
	模拟客户端系统版本：macOS 10.14.4。
【过程】
	服务器使用了lua-socket+httpd实现http的请求处理服务。
	客户端使用httpc.request接口连接服务器进行账号登录。
【问题】
	服务器收到http消息处理完并使用httpd.write_response回写数据到socket后，立刻调用socket.close关闭连接。客户端socket收到了回写的消息，但是读取数据时候报错了。【该报错非常大概率会发生，偶尔没问题】
	## http服务消息处理代码 ##
		dispatch(_, _, id)
		socket.close(id)
	dispatch是消息处理，并调用httpd.write_response返回处理结果消息的接口，然后就直接close掉socket
【报错堆栈】
	Error:	[Socket Error]	stack traceback:
	./lualib/functions.lua:1162: in function 'error'
	./lualib/http/sockethelper.lua:54: in local 'readbytes'
	./lualib/http/internal.lua:49: in function 'http.internal.recvheader'
	./lualib/http/httpc.lua:38: in function <./lualib/http/httpc.lua:13>
	[C]: in function 'pcall'
	./lualib/http/httpc.lua:125: in function 'http.httpc.request'
	(...tail calls...)
	[C]: in function 'xpcall'
	./logic/test/client.lua:46: in function 'test.client.login'
	./logic/test/client_mgr.lua:19: in function 'test.client_mgr.createClient'
	./logic/test/client_mgr.lua:60: in upvalue 'f'
	./lualib/skynet.lua:138: in function <./lualib/skynet.lua:110>
【分析】
	经过查看代码+wireshark抓包追踪发现，服务器回写的消息分成了几个TCP包发送，模拟客户端已经收到所有的消息包，到了发起http请求的socket读到第1条消息发现是分成了几个包，于时继续调用read接口读取，此时读取的lua协程被挂起。底层socket_server_poll读取数据时检测到eof标记位生效，直接调用了force_close关闭连接，向服务器发送了RST消息。并向lua层发送关闭socket消息，把挂起的协程唤醒后就报错了。
wireshark抓包：
![1](https://user-images.githubusercontent.com/7480310/57902522-1be90c80-789c-11e9-89d8-fa916d6f0b4e.png)

【疑问】
	因为怀疑是服务器过早关闭socket导致的，于是决定试下http服务响应完消息后，延迟0.1秒再关闭
socket。经常过千次测试，没有再出现上面的报错。
	代码如下：
		dispatch(_, _, id)
		skynet.sleep(10)
		socket.close(id)
	我查看了#858里有提到，kqueue当socket关闭时，无论socket的缓冲区是否有数据，都会标记EV_EOF。然后skynet的socket_server_poll检测到eof标记生效了就把socket关掉了。
		If the read direction of the socket has shutdown,
		then the filter also sets EV_EOF in flags,	and
		returns the socket	error (if any) in fflags.  It
		is possible for EOF to be returned	(indicating
		the connection is gone) while there is still data
		pending in the socket buffer.

	在这里想请教下大佬们，这个是不是我使用的方式有问题？还是kqueue这种机制需要我自己做好容错？如果是的话，我上面延迟0.1秒关闭socket的解决方式合理吗？

**Comment by cloudwu** [comment]
试试新建的 kqueue 分支，看是否能修好这个问题。我没有测试环境，麻烦了。

另外 @lvzixun 这个 eof 消息处理应该是你加的，也看一下。

**Comment by lvzixun** [comment]
能否提供下测试用例？ 之前好像是因为会有`EVFILT_WRITE`和`EV_EOF`两个标记一起发过来， 触发了read函数之后会导致返回`RST`错误码，所以优先处理了`EV_EOF`。

可以尝试把  https://github.com/cloudwu/skynet/blob/master/skynet-src/socket_kqueue.h#L78 
代码改为`e[i].read = (filter == EVFILT_READ);`试试？

**Comment by keventan** [comment]
> 试试新建的 kqueue 分支，看是否能修好这个问题。我没有测试环境，麻烦了。
> 
> 另外 @lvzixun 这个 eof 消息处理应该是你加的，也看一下。

好的，我试下

**Comment by keventan** [comment]
> 能否提供下测试用例？ 之前好像是因为会有`EVFILT_READ`和`EV_EOF`两个标记一起发过来， 触发了read函数之后会导致返回`RST`错误码，所以优先处理了`EV_EOF`。
> 
> 可以尝试把 https://github.com/cloudwu/skynet/blob/master/skynet-src/socket_kqueue.h#L78
> 代码改为`e[i].read = (filter == EVFILT_READ);`试试？

整个测试代码比较复杂，不好提供，涉及到项目代码。我看能不能简化下吧。

**Comment by lvzixun** [comment]
@keventan 你可以看下这个提交。https://github.com/lvzixun/skynet/commit/18829aa1b0449af51392cb6bc33ebc462d0ddb7b 我在我本地测试了下，没问题。

**Comment by keventan** [comment]
> @keventan 你可以看下这个提交。[lvzixun@18829aa](https://github.com/lvzixun/skynet/commit/18829aa1b0449af51392cb6bc33ebc462d0ddb7b) 我在我本地测试了下，没问题。

抽空测了下，你和云大的两个方案经过大量测试都没问题，没报错了。感谢！
