### ISSUE TITLE
tlshelper read 卡住

### ISSUE THREAD

**Issue by findix** [cloudwu/skynet#1016]
Hi, 我之前一直在跟进 https client 的新特性，但是尝试失败，访问任何https站点都一定会卡住无法返回。
目前发现是卡在
https://github.com/cloudwu/skynet/blob/6addb504e4c956dbbb22fb9e3ed1ed1e87972986/lualib/http/tlshelper.lua#L60
这里，如果改为
```lua
        local ds = readfunc(1)
```
就是可以的。

**Comment by lvzixun** [comment]
https://github.com/cloudwu/skynet/pull/1017  你看下这个PR， 判断`SSL_read`读完的实现有问题， 应该判断错误码是否是`SSL_ERROR_WANT_READ`和`SSL_ERROR_WANT_WRITE`。

之前测试的时候没有测试很大的https请求，所以不会触发这个问题。我测试了下拉取`https://github.com`没问题。

**Comment by findix** [comment]
测试可以了，感谢~~

**Comment by findix** [comment]
Hi，@lvzixun 
还有一个问题，我在 loginserver 中使用 httpc 访问平台账号认证，但是固定在第二次有人登陆访问的时候，会抛出 `SSL_CTX_new client faild` 异常，请问一下可能是怎样的原因呢？
谢谢，麻烦了~

**Comment by lvzixun** [comment]
第一次https请求是能够正常返回吗？ 还是说第一次能成功，但是第二次才会出现报错？ 
把`lnew_ctx`函数里面的 https://github.com/cloudwu/skynet/blob/6addb504e4c956dbbb22fb9e3ed1ed1e87972986/lualib-src/ltls.c#L315-L317  这段改成
~~~.lua
    if(!ctx_p->ctx) {
        unsigned int err = ERR_get_error();
        char buff[128];
        ERR_error_string_n(err, buff, sizeof(buff));
        luaL_error(L, "SSL_CTX_new client faild. error:%s\n", buff);
    }
~~~
看一下打印出来的错误是什么。

**Comment by findix** [comment]
对的，第一次可以正常返回，第二次失败
错误是
`SSL_CTX_new client faild. error:error:140A90F1:SSL routines:SSL_CTX_new:unable to load ssl2 md5 routines`

**Comment by lvzixun** [comment]
你还有用其他加载了openssl的第三方库吗？  像`libcurl`这样的。 看报错应该是在错误的时机被调用了`EVP_cleanup()` 这个函数。

**Comment by findix** [comment]
对的……我们自己调用了openssl库用于加密……
正好在登陆成功以后分配服务器的时候会调用，结束的时候会调用`EVP_cleanup()`，所以导致第二次登陆的时候已经被清理了。

**Comment by lvzixun** [comment]
你看下把tls和你的那个加密lib的init和destroy阶段给合并下，只用一个。因为EVP_cleanup这个接口是全局，一旦有人调用了会影响整个进程openssl的状态。

Sean <notifications@github.com>于2019年6月27日 周四下午12:22写道：

**Comment by findix** [comment]
我尝试去掉自己这边的`EVP_cleanup()`调用后确实可以了，就是不知道lstl.c的destructor是什么情况下会被调用，担心引起泄露问题。

**Comment by lvzixun** [comment]
`destructor`这个应该是在`ltls.so`被人卸载的时候才会调用的。os提供的`dlopen`这个接口本身是有引用计数的，只有调用`dlclose`跟`dlopen`一样次数后才会被释放的。 我觉得最好的做法是，你在一个跟`skynet`进程同样生命周期的一个`service`中`require "ltls.c"`保证`ltls.so`不被释放就好了。

**Comment by findix** [comment]
了解了，非常感谢帮助！
