### ISSUE TITLE
小菜鸟遇到HTTP问题， 弄了一晚上实在无法解决，求助！

### ISSUE THREAD

**Issue by luosixiang** [cloudwu/skynet#1023]
使用httpc 访问苹果的支付验证， 搞了一晚上还是返回302，求助............
在本地虚拟机和云服liunx上都是一样。

请求内容如下：
        ```
local respheader = {}
        local head = {
            ["content-type"] = "application/json",
        }
        local data = {
            ["receipt-data"] = "(客户端支付，苹果返回的一大堆字符串)"
        }
        local status, body = httpc.request("POST", "sandbox.itunes.apple.com", "/verifyReceipt", respheader, head, data)
```

返回的数据：
state 302
["connection"]="close",
["pragma"]="no-cache",
["cache-control"]="no-cache",
["location"]="https://sandbox.itunes.apple.com/verifyReceipt",

**Comment by cloudwu** [comment]
我认为任何支付接口都不可能用 http 的。

**Comment by cloudfreexiao** [comment]
最新 skynet 已经 支持 https
看看 location 的含义吧
 https://zh.wikipedia.org/wiki/HTTP_302

**Comment by luosixiang** [comment]
谢谢， 那就是请求问题了，  skynet 发起https有demo吗？   @cloudfreexiao

**Comment by cloudfreexiao** [comment]
https://github.com/cloudwu/skynet/blob/master/test/testhttp.lua#L36

**Comment by luosixiang** [comment]
非常感谢
