### ISSUE TITLE
lua调用go编写的so失败

### ISSUE THREAD

**Issue by judithzzh** [cloudwu/skynet#1031]
有一个go写的so库，我用系统上装的lua5.3调用能正确执行，但是在skynet里就提示找不到函数
![image](https://user-images.githubusercontent.com/19266616/59321656-78a5de80-8d05-11e9-93c4-95ae8e026563.png)
上面是我打印出的这个lib
![image](https://user-images.githubusercontent.com/19266616/59321684-8ce9db80-8d05-11e9-94c7-abed15b4c989.png)
type时却是nil

**Comment by judithzzh** [comment]
云大能指点下吗

**Comment by cloudwu** [comment]
1. 改掉截图的坏毛病吧，明明都是文本，学学 markdown 。
2. 多半是 lua 库的链接问题。

**Comment by judithzzh** [comment]
好的  我再查查。markdown不太熟，还在持续学习中，多谢~~
