### ISSUE TITLE
SSM特性

### ISSUE THREAD

**Issue by sheldonzeng** [cloudwu/skynet#1039]
SSM特性能否加个编译开关关闭这个特性避免不必要的性能开销，因为我的应用环境不需要用到ssm，今天更新了最新版本简单测试了下，加载玩家数据这里性能下降严重，用的自带的mysql库，原来查询一个玩家是在几十ms级别，现在要秒级别

**Comment by sheldonzeng** [comment]
不知道是ssm还是jemalloc5.2的原因，今天更新到最新版本后myslq查询这里性能下降特别严重

**Comment by cloudwu** [comment]
我正在做另一个版本，将会去掉 ssm ，预计今天能提交到分支上。

但我想确定你的问题原因。

jemalloc 你可以自己取上一个版本测试一下。

ssm 本身的设计不应该造成这么大的区别，可能是触发了什么 bug? 你可以用 debug console 的 info 指令查一下 garbagecollect 服务，输出 ssm 的细节，或直接调用 ssm.info() 也能查询。

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/tree/stringid  你可以看看今天新的分支，已经去掉了 ssm 。但是加了跨 vm 的短字符串比较机制。随便帮忙测试一下？

**Comment by sheldonzeng** [comment]
> 我正在做另一个版本，将会去掉 ssm ，预计今天能提交到分支上。
> 
> 但我想确定你的问题原因。
> 
> jemalloc 你可以自己取上一个版本测试一下。
> 
> ssm 本身的设计不应该造成这么大的区别，可能是触发了什么 bug? 你可以用 debug console 的 info 指令查一下 garbagecollect 服务，输出 ssm 的细节，或直接调用 ssm.info() 也能查询。
这是info的信息，帮忙看下有没异常
info 00000004
garbage	3910
garbage_size	174868
longest	11
n	119584
size	4772391
slots	111593
variance	0.12207555135306

**Comment by sheldonzeng** [comment]
> https://github.com/cloudwu/skynet/tree/stringid 你可以看看今天新的分支，已经去掉了 ssm 。但是加了跨 vm 的短字符串比较机制。随便帮忙测试一下？

我试下

**Comment by cloudwu** [comment]
你的 ssm 中 hash 冲突很小啊，最长才 11 ，n/slots 也非常小，几乎没有冲突。

我想你需要定位别的地方，最好做一下 profile ，找到具体什么函数运行消耗的 cpu 过高。

**Comment by sheldonzeng** [comment]
> 你的 ssm 中 hash 冲突很小啊，最长才 11 ，n/slots 也非常小，几乎没有冲突。
> 
> 我想你需要定位别的地方，最好做一下 profile ，找到具体什么函数运行消耗的 cpu 过高。

是mysql.query这里耗时

**Comment by cloudwu** [comment]
这个就很难从表面找到问题了，需要你有环境去 profile 。因为我们自己的项目，和 @hongling0 的项目都没有发现性能大幅度下降的问题。

另外，今天的新版本还有问题吗？

**Comment by cloudwu** [comment]
btw, 没有 ssm 的版本应该就是 May 22 的版本，从 commits 历史可以查到。你在那个版本就没有问题了吗？

**Comment by sheldonzeng** [comment]
> 这个就很难从表面找到问题了，需要你有环境去 profile 。因为我们自己的项目，和 @hongling0 的项目都没有发现性能大幅度下降的问题。
> 
> 另外，今天的新版本还有问题吗？

暂时还未测试

**Comment by sheldonzeng** [comment]
> btw, 没有 ssm 的版本应该就是 May 22 的版本 https://github.com/cloudwu/skynet/tree/2d6d2c75a400eecfe193996815ed7890f9753d3d ，从 commits 历史可以查到。你在那个版本就没有问题了吗？

那可能不是ssm问题，我上次更新版本是6.5号，这段期间正常，今天早上再次更新版本出现的问题，我再排查看看

**Comment by cloudwu** [comment]
不，ssm 分支是最近才合并的。5 号尚未合并。如果你想退回去，需要退到 May 22 的版本。

**Comment by sheldonzeng** [comment]
> 不，ssm 分支是最近才合并的。5 号尚未合并。如果你想退回去，需要退到 May 22 的版本。

定位出来了，跟ssm和jemalloc都没关系，是我们一位员工今天新加的一个系统查询玩家数据语句写错把整个表查出来了，耽误你时间，抱歉了
