### ISSUE TITLE
启动bootstrap的时候失败

### ISSUE THREAD

**Issue by PorscheCH** [cloudwu/skynet#1043]
root@BF-CHENHONGYU01:/data/majong-shanghai/game-server/skynet_pbc# $(pwd)/skynet/skynet ../xyconfig/serversconfig
Wed Jun 19 11:24:32 2019 ERROR  [:00000001]Unknown request (0): LAUNCH snlua bootstrap
Wed Jun 19 11:24:32 2019 ERROR  [:00000001]lua call [2 to :1 : 0 msgsz = 22] error : ./skynet/lualib/skynet.lua:616: ./skynet/lualib/skynet.lua:502: Unknown session : 0 from 2
stack traceback:
	[C]: in function 'assert'
	./skynet/lualib/skynet.lua:616: in function 'skynet.manager.dispatch_message'
Wed Jun 19 11:24:32 2019 ERROR  [:00000001]Unknown request (0): LAUNCH snlua launcher
Wed Jun 19 11:24:32 2019 ERROR  [:00000001]lua call [3 to :1 : 0 msgsz = 21] error : ./skynet/lualib/skynet.lua:616: ./skynet/lualib/skynet.lua:502: Unknown session : 0 from 3
stack traceback:
	[C]: in function 'assert'
	./skynet/lualib/skynet.lua:616: in function 'skynet.manager.dispatch_message'
Wed Jun 19 11:24:32 2019 ERROR  [garbagecollect:][:00000004]LAUNCH snlua garbagecollect
Wed Jun 19 11:24:32 2019 ERROR  [cdummy:][:00000005]LAUNCH snlua cdummy
Wed Jun 19 11:24:32 2019 ERROR  [:00000006]LAUNCH harbor 0 5
Wed Jun 19 11:24:32 2019 ERROR  [datacenterd:][:00000007]LAUNCH snlua datacenterd
Wed Jun 19 11:24:32 2019 ERROR  [service_mgr:][:00000008]LAUNCH snlua service_mgr
Wed Jun 19 11:24:32 2019 ERROR  [main:][:00000009]LAUNCH snlua main
Wed Jun 19 11:24:32 2019 ERROR  [clusterd:][:0000000a]LAUNCH snlua clusterd
Wed Jun 19 11:24:32 2019 ERROR  [main:]ClusterCenterSvr start
Wed Jun 19 11:24:32 2019 ERROR  [console:][:0000000b]LAUNCH snlua console
Wed Jun 19 11:24:32 2019 ERROR  [debug_console 8101:][:0000000c]LAUNCH snlua debug_console 8101
Wed Jun 19 11:24:32 2019 ERROR  [debug_console 8101:]Start debug console at 127.0.0.1:8101
Wed Jun 19 11:24:32 2019 ERROR  [clustercentersvr:][:0000000d]LAUNCH snlua clustercentersvr

**Comment by cloudwu** [comment]
clone 一份全新的代码试试。没问题再自己排查自定义的部分的问题。

你这里缺少 [:00000002] [:00000003] 的启动日志。
