### ISSUE TITLE
求方向: 关于 maybe in an endless loop

### ISSUE THREAD

**Issue by zhushaojun65** [cloudwu/skynet#1045]
[:00000000] A message from [ :00000000 ] to [ :00000004 ] maybe in an endless loop (version = 3945767)

这类问题不知道怎么下手, 希望各位skyneter指引一个方向, debug_console的mem和stat指令都没有响应了

**Comment by aasdpiao** [comment]
signal adress 可以试试  你试试看 signal 4

**Comment by zhushaojun65** [comment]
:00000004  这个服务是 snlua garbagecollect
但是我从skynet启动过程中并没有找到这个服务的启动位置, 以及这个服务的代码位置, 有人能指点我一下吗?谢谢了

**Comment by xzhovo** [comment]
因为ssm被删了...去看提交记录就知道了

**Comment by zhushaojun65** [comment]
@xzhovo garbagecollect 这个服务是属于ssm的吗? 意思是我更新最新版的skynet就不会有该服务了吗?

**Comment by xzhovo** [comment]
是的

**Comment by zhushaojun65** [comment]
@xzhovo 不对呀, 我更新到最新的master版本, 还是有garbagecollect 这个服务

**Comment by xzhovo** [comment]
也许你应该kill并重启skynet..

**Comment by zhushaojun65** [comment]
@xzhovo 生产环境怎么可能让你随便重启

**Comment by zhushaojun65** [comment]
另外起了一个iss, 所以关闭本条
