### ISSUE TITLE
关于garbagecollect服务maybe in an endless loop

### ISSUE THREAD

**Issue by zhushaojun65** [cloudwu/skynet#1048]
关于这个问题, 是在是没找到突破口, 我现在能做到就是把debug_console服务中stat指令对每个服务调用debug.STAT由原来的skynet.call 改成了0.5s超时的timeout_call(Wiki文档中有), 问题重现后, 进入debug_console, 发现除了garbagecollect(:00000004)其他服务都能正常响应
    希望有经验的skyneter能帮忙分析一下, 不甚感激

**Comment by cloudwu** [comment]
此服务已从主干移除。
