### ISSUE TITLE
cluster.send偶现name is too long (null)的问题

### ISSUE THREAD

**Issue by shyhc** [cloudwu/skynet#1050]
线上生产环境会时不时出现这个问题
跟踪代码，定位是lua-cluster.c内的packreq_string函数发出的错误
大概是什么样的情况会造成这个问题的出现，云大能指点一下吗

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/blob/master/lualib-src/lua-cluster.c#L168

你在调用 packrequest 时，第一个参数如果不是数字就必须是字符串，这里出错信息显示 (null) 说明不是字符串（导致 `lua_tolstring` 返回 null）。你可以看看到底传了什么类型。

**Comment by cloudwu** [comment]
我增强了错误提示，你可以再看看。

**Comment by shyhc** [comment]
好的，谢谢云大，我再继续观察一下
