### ISSUE TITLE
sharedata共享配置的疑问

### ISSUE THREAD

**Issue by zlibrary** [cloudwu/skynet#1052]
在我们的项目中， 使用“sharedata”来在多个“agent”间共享配置数据， 现在发现的问题是，某些配置数据我们仅仅在创建角色或者每日重置的时候才会使用一次（整个配置表遍历），因为"sharedata"会在本地缓存配置，而且无法释放，导致这些配置其实空占了大量的内存。不知道有没有比较合理的解决方案呢。

**Comment by cloudwu** [comment]
目前推荐用 sharetable 替代，已经是 0 额外内存开销了。

**Comment by zlibrary** [comment]
谢谢， 这就去试试

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/wiki/ShareData
