### ISSUE TITLE
需要 web socket 支持

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/skynet#1053]
网上已有很多第三方为 skynet 扩展 web socket 的方案，现在需要一个 skynet 官方版本。

不知道有没有同学愿意长期维护？

ps. 我个人希望用纯 lua 实现。

**Comment by h87070628** [comment]
找了好几个第三方版本,各种问题, 要不就是早就没维护的.. 尴尬的是小游戏环境还只支持wss连接.

**Comment by korialuo** [comment]
https://github.com/korialuo/skynet/blob/master/lualib/websocket.lua
自己结合其他开源代码修改过后的实现，未详细测试。

**Comment by korialuo** [comment]
https://github.com/korialuo/skynet/blob/master/test/testwebsocket.lua
这是例子。

**Comment by srdgame** [comment]
https://raw.githubusercontent.com/Skycrab/skynet_websocket/master/websocket.lua

**Comment by h87070628** [comment]
> https://github.com/Skycrab/skynet_websocket

没人维护而且有bug

**Comment by luosixiang** [comment]
顶一波， 现在做游戏WS用的比socket多

**Comment by srdgame** [comment]
> > https://github.com/Skycrab/skynet_websocket
> 
> 没人维护而且有bug

只是放出来有个参考。 我们产品（不是游戏）里面轻微用到了websocket，没遇到什么问题。

**Comment by luosixiang** [comment]
> > > https://github.com/Skycrab/skynet_websocket
> > 
> > 
> > 没人维护而且有bug
> 
> 只是放出来有个参考。 我们产品（不是游戏）里面轻微用到了websocket，没遇到什么问题。 https://github.com/freeioe/freeioe

用是能用， 只是处理不够严谨， 有报错被pcall拦截了 ，而且没有打印捕获的错误。

**Comment by sue602** [comment]
还是挺需要的。

**Comment by rangercyh** [comment]
> 找了好几个第三方版本,各种问题, 要不就是早就没维护的.. 尴尬的是小游戏环境还只支持wss连接.

我的解决方案是客户端wss连接到nginx，nginx配置ssl的ws认证，然后转发到后端服务器做处理，转发后端的连接方式就看你的需求了，你可以直接用socket跟skynet连，在skynet里拆ws的包，也可以自己弄个单独的有人维护的第三方ws库进行拆包再转发给skynet的gate，总之就是很麻烦

**Comment by CandyMi** [comment]
我在[这里](https://github.com/CandyMi/skynet-lua-websocket)实现了一个`Websocket`的库. 它基于resty-websocket改造而来的纯Lua实现.

拥有完整的`Websocket`抽象与`test.lua`代码示例可以帮助你快速建立`ws`对象原型, 对象建立仅依赖`class`对象并仅需主动创建几个回调方法即可.

`wss`支持仅需`Nginx`等反向代理工具`proxy`即可, 目前已有一些小伙伴已经用于生产环境且并未出现任何异常. 

参考`README`之后即可快速上手.

**Comment by hanxi** [comment]
> 我在[这里](https://github.com/CandyMi/skynet-lua-websocket)实现了一个`Websocket`的库. 它基于resty-websocket改造而来的纯Lua实现.
> 
> 拥有完整的`Websocket`抽象与`test.lua`代码示例可以帮助你快速建立`ws`对象原型, 对象建立仅依赖`class`对象并仅需主动创建几个回调方法即可.
> 
> `wss`支持仅需`Nginx`等反向代理工具`proxy`即可, 目前已有一些小伙伴已经用于生产环境且并未出现任何异常.
> 
> 参考`README`之后即可快速上手.

代码挺清晰的，几个建议：
1. 代码中的中文换成英文
2. 不要依赖class，用lua的元表
3. wss 可以试试新的 http.tlshelper

**Comment by ZhouWeikuan** [comment]
微信小游戏用的是wss接口，也就是https版的web socket，应该需要用到http.tlshelper库的

**Comment by hsz8250** [comment]
支持普通的http 的 ws已经足够了，然后在nginx上做https代理即可

**Comment by ZhouWeikuan** [comment]
根据 https://github.com/Skycrab/skynet_websocket
和 skynet里的 examples/simpleweb.lua

撸了一个支持ws, wss的websocket, 
https://github.com/ZhouWeikuan/Crypt.js/blob/master/websocket.lua

没有仔细测过

**Comment by lvzixun** [comment]
我用之前写的`tlshelper`简单的实现了个支持ws/wss协议，同时具有server和client功能的websocket模块， 目前我在我自己测试环境下能简单测试通过。 https://github.com/cloudwu/skynet/pull/1056，有兴趣的童鞋可以先review下 ;D

**Comment by cloudwu** [comment]
各位同学有需求的可以先看看 #1056 不出意外我会合并这个。

**Comment by stlnkm** [comment]
急需官方版本，请问啥时候合并呢

**Comment by cloudwu** [comment]
> 急需官方版本，请问啥时候合并呢

有这个需求就先用用，给个试用报告。

**Comment by stlnkm** [comment]
OK，我试试

**Comment by sabearcher** [comment]
@lvzixun 
请问，我在启用最新版 `Latest commit cd27343 Jul 31, 2019` 的websocket分支时，使用 simplewebsocket.lua 启动了newservice， 在客户端用wss连接时，产生了报错：
```
[:00000012] lua call [0 to :12 : 0 msgsz = 29] error : ../../build/../../skynet/lualib/skynet.lua:616: ../../build/../../skynet/lualib/skynet.lua:183: ../../build/../../skynet/lualib/http/tlshelper.lua:2: module 'ltls.c' not found:
        no field package.preload['ltls.c']
        no file '../../build/../../skynet/lualib/ltls/c.lua'
        no file '../../build/../../skynet/lualib/ltls/c/init.lua'
        no file '../../build/luaservices/common/ltls/c.lua'
        no file '../../build/luaservices/common/config/ltls/c.lua'
        no file '../luaservices/lgc_frame/ltls/c.lua'
        no file '../luaservices/lgc_player/common/ltls/c.lua'
        no file '../luaservices/lgc_player/ltls/c.lua'
        no file '../../build/../../skynet/luaclib/ltls/c.so'
        no file '../../build/extern/ltls/c.so'
        no file '../../build/../../skynet/luaclib/ltls.so'
        no file '../../build/extern/ltls.so'
stack traceback:
        [C]: in function 'require'
        ../../build/../../skynet/lualib/http/tlshelper.lua:2: in main chunk
        [C]: in function 'require'
        ../../build/../../skynet/lualib/http/websocket.lua:348: in upvalue '_new_server_ws'
        ../../build/../../skynet/lualib/http/websocket.lua:387: in function 'http.websocket.accept'
        ../luaservices/lgc_frame/player/testws.lua:47: in upvalue 'f'
        ../../build/../../skynet/lualib/skynet.lua:140: in function <../../build/../../skynet/lualib/skynet.lua:112>
stack traceback:
        [C]: in function 'assert'
        ../../build/../../skynet/lualib/skynet.lua:616: in function 'skynet.dispatch_message'
```
请问问题出在哪里？我已经 yum install -y openssl-devel 安装过后再编译了

**Comment by lvzixun** [comment]
https://github.com/cloudwu/skynet/blob/master/Makefile#L22-L24 @sabearcher  看下你有没有编译`ltls`.

**Comment by sabearcher** [comment]
@lvzixun 
的确没有设置TLS_LIB与TLS_INC，在luaclib/ 下未发现 `ltls.so`，
此处我不懂，还请教我， 我通过 `yum install -y openssl-devel` 安装的，是否可以使用tls，lib与inc在哪里呢？我使用whereis没有查到

**Comment by cloudfreexiao** [comment]
不出意外在 /usr/local/openssl/  里
这里有个 外部指定 tls 的例子
https://github.com/cloudfreexiao/AntServer/blob/master/Makefile#L31

**Comment by sabearcher** [comment]
@cloudfreexiao  我没有这个目录，莫非是必须用源码安装openssl才可以？

**Comment by cloudfreexiao** [comment]
我是 源码 安装的

**Comment by sabearcher** [comment]
> @lvzixun
> 的确没有设置TLS_LIB与TLS_INC，在luaclib/ 下未发现 `ltls.so`，

@lvzixun  此处我说错了，之前 `TLS_MODULE=ltls` 未打开，打开后不填 `TLS_LIB=` 等，生成的 ltls.so 无法使用，
```
[:00000012] lua call [0 to :12 : 0 msgsz = 29] error : ../../build/../../skynet/lualib/skynet.lua:616: ../../build/../../skynet/lualib/skynet.lua:183: ../../build/../../skynet/lualib/http/websocket.lua:355: SSL_CTX_use_certificate_file error:0
stack traceback:
	[C]: in method 'set_cert'
	../../build/../../skynet/lualib/http/websocket.lua:355: in upvalue '_new_server_ws'
	../../build/../../skynet/lualib/http/websocket.lua:387: in function 'http.websocket.accept'
	../luaservices/lgc_frame/player/testws.lua:47: in upvalue 'f'
	../../build/../../skynet/lualib/skynet.lua:140: in function <../../build/../../skynet/lualib/skynet.lua:112>
stack traceback:
	[C]: in function 'assert'
	../../build/../../skynet/lualib/skynet.lua:616: in function 'skynet.dispatch_message'
```
是需要用openssl的源码安装一次吗？版本有要求吗？

**Comment by lvzixun** [comment]
如果装了openssl-devel 一般都是有头文件和lib的。你要不在跟目录下面find下看看。

**Comment by bingo235** [comment]
@cloudwu  
websocket需要获取客户端真实IP接口

目前其实可以在socke open回调时建立一个fd->obj的map来保存addr，但我觉得ws应该在handle.handshake成功之后再建立比较符合逻辑。
https://github.com/cloudwu/skynet/blob/cd27343083e882f46cbc167ae8f715a7678675e9/examples/simplewebsocket.lua#L79



我想的方法是在websocket.accept时传入socke open回调返回的addr，存储在ws_obj中
https://github.com/cloudwu/skynet/blob/cd27343083e882f46cbc167ae8f715a7678675e9/lualib/http/websocket.lua#L384
```
//此处要传入addr
function M.accept(socket_id, handle, protocol, addr) 
```

如果ws有前置代理(nginx etc.)，需要自己在handle.handshake中获取X-Real-IP或者X-Forwarded-For，因为各自代理环境不同，需要自己在header中设置。
https://github.com/cloudwu/skynet/blob/cd27343083e882f46cbc167ae8f715a7678675e9/examples/simplewebsocket.lua#L14

**Comment by cloudwu** [comment]
@lvzixun

**Comment by bingo235** [comment]
还有个需求，最好在 handle.handshake回调中带上请求url，形如:
```
--/ws?uid=111&&token=1ae6ae259e200983888f9a974fc83cdd
function handle.handshake(id, header, url) 
    local path, query = urllib.parse(url)
end

```

**Comment by lvzixun** [comment]
那我这边就加一个新的接口`websocket.getaddr(ws_id)` 返回addr吧。 `handshake`那边也加上`url`参数。

**Comment by lvzixun** [comment]
@bingo235  你看下这个PR: https://github.com/cloudwu/skynet/pull/1070

**Comment by Fanrncho** [comment]
这个文件的第53行要改一下（https://github.com/cloudwu/skynet/blob/websocket/lualib/http/websocket.lua），
if not recvheader["connection"] or recvheader["connection"]:lower() ~= "upgrade" then
        error("websocket handshake connection must upgrade")
    end
改为：
if not header["connection"] or not header["connection"]:lower():find("upgrade", 1,true) then
        return 400, "\"Connection\" must be \"Upgrade\"."
    end
因为Connection字段里不是一定等于upgrade,比如我这边测试的结果Connection: keep-alive, Upgrade
@lvzixun

**Comment by cloudwu** [comment]
如果需要 find ，我建议不用 lower() 而直接匹配 [uU]pgrade

**Comment by bingo235** [comment]
@lvzixun 看过没发现问题 我继续测试

**Comment by Fanrncho** [comment]
抱歉，笔误，应该改为：
if not header["connection"] or not header["connection"]:lower():find("upgrade", 1,true) then
        return 400, "Connection must Upgrade"
    end
少了个not @lvzixun

**Comment by Fanrncho** [comment]
@cloudwu 风哥的建议好

**Comment by Fanrncho** [comment]
@lvzixun ws模块测试出现问题：我从客户端发数据到服务器，服务器可以read到数据，但从服务器通过write接口回复客户端时，客户端就直接异常断开连接了，然后服务器这边read接口也出错了。我这边测试是必现的问题，我不是用的官方提供的ws例子测试的，而是用cocos creator项目做ws客户端，连接skynet服务器测试的。
现在服务器这边ws模块可以正常接收到客户端的数据，但数据往回写就不行，会导致客户端直接异常断开。
我这边服务器的握手相关信息如下：
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: vxemfbkYgL/S3r5v73fzitjG8JI=

["accept"] = "*/*",
	["upgrade"] = "websocket",
	["connection"] = "keep-alive, Upgrade",
	["cache-control"] = "no-cache",
	["user-agent"] = "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0",
	["pragma"] = "no-cache",
	["origin"] = "http://localhost:7456",
	["host"] = "39.105.47.25:2001",
	["accept-encoding"] = "gzip, deflate",
	["sec-websocket-extensions"] = "permessage-deflate",
	["sec-websocket-version"] = "13",
	["accept-language"] = "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2",
	["sec-websocket-key"] = "Su9FOQtOY4emQFp86IUbJw==",

**Comment by Fanrncho** [comment]
刚又测试了下昨天提的问题，发现是ws模块接口使用问题才导致客户端连接异常问题出现的。
因为我这边从服务器回传到客户端的数据都是通过pbc编码过得二进制文本，然后这样调用写入接口的：websocket.write(id, login_resp(404))。
刚细看了下websocket.write接口实现，才发现该接口如果只传两个参数的话默认以"text"格式传送，所以我在调用该接口的地方指定第三个参数为"binary"后就没有问题了：websocket.write(id, protobuff.encode("xxx"), "binary")
@lvzixun

**Comment by Fanrncho** [comment]
希望websocket模块能添加类似于skynet.socket模块的socket.abandon接口（清除 socket id 在本服务内的数据结构，但并不关闭这个 socket 。这可以用于你把 id 发送给其它服务，以转交 socket 的控制权。）。
问题示例：
1. 在一个agent服务里fd由websocket.accept接口，在接收到消息的时候直接调用socket.abandon接口。
2. 然后把该fd通过skynet.call传送到另一个agent服务里由websocket.accept接口监听。
测试的过程中发现程序执行到步骤2（也就是调用websocket.accept接口监听这行代码）就卡住了。
@cloudwu @lvzixun

**Comment by lvzixun** [comment]
对于`ws`协议来说在握手之后，是可以加一个`abandon`接口。 但是因为要支持`wss`，使用了`tls`做加密传输，很难做到`abandon`。 所以推荐的方式是将单个或者多个`ws_id`放到一个service中做accept和write。 与客户端的通信全部通过这个service。

**Comment by Fanrncho** [comment]
客户端和服务器建立websocket连接后，客户端把程序关了，然后服务器这边往websocket模块注册的error回调方法会被触发，从websocket模块代码来看触发"error"事件后是会把socket关闭了，这时我觉得应该要触发一下注册的close回调方法，或者说，这都不应该触发"error"事件，这是应该判定为客户端主动断开连接，触发close事件就可以了，不应该触发"error"事件 @cloudwu @lvzixun 
还有一个问题就是希望websocket模块对外提供一个判断ws_pool[socket_id]是否有效的方法，我在外部调用websocket模块的write接口前如果这时ws_pool[socket_id]为nil，那么我就不触发write了。

**Comment by lvzixun** [comment]
@Fanrncho  那只需要把socket直接关闭的行为去触发`close`事件就可以了吧？

**Comment by Fanrncho** [comment]
@lvzixun 我认为这种情况不应该归为error，这时客户端断开连接了，触发close就行了。
另外，这两天还出现一个问题：
```
[:0000000c] lua call [0 to :c : 460 msgsz = 0] error : ./skynet/lualib/skynet.lua:616: ./skynet/lualib/skynet.lua:183: {
}
stack traceback:
	[C]: in function 'error'
	./skynet/lualib/http/sockethelper.lua:65: in field 'write'
	./skynet/lualib/http/websocket.lua:185: in upvalue 'write_frame'
	./skynet/lualib/http/websocket.lua:466: in function 'http.websocket.write'
	./business/client/clientd.lua:15: in field 'sendtosvr'
	./business/client/module/svrmsghandler.lua:29: in upvalue 'f'
	./skynet/lualib/skynet.lua:140: in function <./skynet/lualib/skynet.lua:112>
stack traceback:
	[C]: in function 'assert'
	./skynet/lualib/skynet.lua:616: in function 'skynet.dispatch_message'
```

**Comment by Fanrncho** [comment]
@lvzixun 这个问题经常出现，希望能尽快解决：
```
[:0000000c] lua call [0 to :c : 460 msgsz = 0] error : ./skynet/lualib/skynet.lua:616: ./skynet/lualib/skynet.lua:183: {
}
stack traceback:
	[C]: in function 'error'
	./skynet/lualib/http/sockethelper.lua:65: in field 'write'
	./skynet/lualib/http/websocket.lua:185: in upvalue 'write_frame'
	./skynet/lualib/http/websocket.lua:466: in function 'http.websocket.write'
	./business/client/clientd.lua:15: in field 'sendtosvr'
	./business/client/module/svrmsghandler.lua:29: in upvalue 'f'
	./skynet/lualib/skynet.lua:140: in function <./skynet/lualib/skynet.lua:112>
stack traceback:
	[C]: in function 'assert'
	./skynet/lualib/skynet.lua:616: in function 'skynet.dispatch_message'
```

**Comment by lvzixun** [comment]
> @lvzixun 这个问题经常出现，希望能尽快解决：
> 
> ```
> [:0000000c] lua call [0 to :c : 460 msgsz = 0] error : ./skynet/lualib/skynet.lua:616: ./skynet/lualib/skynet.lua:183: {
> }
> stack traceback:
> 	[C]: in function 'error'
> 	./skynet/lualib/http/sockethelper.lua:65: in field 'write'
> 	./skynet/lualib/http/websocket.lua:185: in upvalue 'write_frame'
> 	./skynet/lualib/http/websocket.lua:466: in function 'http.websocket.write'
> 	./business/client/clientd.lua:15: in field 'sendtosvr'
> 	./business/client/module/svrmsghandler.lua:29: in upvalue 'f'
> 	./skynet/lualib/skynet.lua:140: in function <./skynet/lualib/skynet.lua:112>
> stack traceback:
> 	[C]: in function 'assert'
> 	./skynet/lualib/skynet.lua:616: in function 'skynet.dispatch_message'
> ```
这个报错很奇怪， 你是有在 handle注册的事件函数里面有用`skyent.call`或者其他的挂起行为吗？

**Comment by Fanrncho** [comment]
@lvzixun 出现问题的服务节点是我写的向服务器发消息的模拟客户端节点，该节点上都没有注册handle事件，仅用了websocket.connect、websocket.read、websocket.write、websocket.close几个接口，从错误上来看是在websocket模块调用sockethelper.writefunc的闭包函数触发socket.write操作失败抛出的错误，另外刚刚又测到了另一个问题（websocket.read时也报错了）：
```
[:0000000c] lua call [0 to :c : 34 msgsz = 0] error : ./skynet/lualib/skynet.lua:616: ./skynet/lualib/skynet.lua:183: {
}
stack traceback:
	[C]: in function 'error'
	./skynet/lualib/http/sockethelper.lua:54: in field 'read'
	./skynet/lualib/http/websocket.lua:212: in upvalue 'read_frame'
	./skynet/lualib/http/websocket.lua:439: in function 'http.websocket.read'
	./business/client/clientd.lua:34: in upvalue 'f'
	./skynet/lualib/skynet.lua:140: in function <./skynet/lualib/skynet.lua:112>
stack traceback:
	[C]: in function 'assert'
	./skynet/lualib/skynet.lua:616: in function 'skynet.dispatch_message'
```
我讲下我这边错误出现的场景：我用skynet创建了两个节点，一个作为服务器节点，一个作为客户端节点，首先客户端节点通过websocket.connect接口去连接服务器节点，服务器节点的socket监听到连接后通过websocket.accept接口监听该fd的事件，客户端节点持续间隔1秒钟通过websocket.write给该服务器节点发送一个消息，服务器节点收到消息后也会客户端节点回一个消息，而客户端节点这边用一个while循环间隔1秒钟调用一次websocket.read接口来接收服务器节点回的消息。
1. 如果我在他们通讯的过程中把服务器节点杀掉，那么客户端节点就会出现上面这个websocket.write异常问题，并且偶尔会出现websocket.read异常问题。
2.如果我在他们通讯的过程中把客户端节点杀掉，那么服务器节点就会触发handle注册的事件函数error，但不会触发注册的事件函数close，正常来说应该触发close，不用触发error的，因为这是客户端连接断开问题。
你可以测试下，我这边是必现的问题。

**Comment by lvzixun** [comment]
> 1. 如果我在他们通讯的过程中把服务器节点杀掉，那么客户端节点就会出现上面这个websocket.write异常问题，并且偶尔会出现websocket.read异常问题。 

假如服务器异常断开的连接， 客户端当前还是`write`/`read` 那你是期望要怎么返回？ 

> 2. 如果我在他们通讯的过程中把客户端节点杀掉，那么服务器节点就会触发handle注册的事件函数error，但不会触发注册的事件函数close，正常来说应该触发close，不用触发error的，因为这是客户端连接断开问题。

从wesocket 协议角度来说，断开连接是要像服务器发送`close`协议的，如果没发`close`协议的话， 我觉得是应该触发`error`。 还有，由于现在用的是`socket.lua`来实现网络连接， 从接口层面没法知道网络错误码。 https://github.com/cloudwu/skynet/blob/websocket/lualib/skynet/socket.lua#L112 
出现`[Socket Error]`的异常的时候你是无法区分是因为socket error导致还是网络断开连接导致。

**Comment by Fanrncho** [comment]
@lvzixun 

> 假如服务器异常断开的连接， 客户端当前还是write/read 时会直接抛出[Socket Error]，这个逻辑在socketchannel.lua中也是一样的实现。那你是期望要怎么返回？ 是返回一个false/true来表示是否write/read成功？
websocket.write接口的实现定义如下：
```
function M.write(id, data, fmt, masking_key)
    local ws_obj = assert(ws_pool[id])
    fmt = fmt or "text"
    assert(fmt == "text" or fmt == "binary")
    write_frame(ws_obj, fmt, data, masking_key)
end
```
如果服务器异常断开了连接，那就说明socket关闭了，ws_pool里也就应该即时清理掉对应的id，这样的话，即使这时客户端调用write/read，那么也应该在assert(ws_pool[id])这一行代码抛出错误，那为什么异常问题会在write_frame方法里抛出？

**Comment by lvzixun** [comment]
>如果服务器异常断开了连接，那就说明socket关闭了，ws_pool里也就应该即时清理掉对应的id，这样的话，即使这时客户端调用write/read，那么也应该在assert(ws_pool[id])这一行代码抛出错误，那为什么异常问题会在write_frame方法里抛出？

如果你是服务器，`accept`是做了`pcall`，客户端主动断开抛出`[socket error]`会被外面捕获，之后会立即触发`error`handle的，这时你再`write`和`read`都会在`assert(ws_pool[id])`中触发错误。除非你在handle的回调函数中有用`call`，`sleep`这种挂起操作，导致accept被resume的时机错乱。

如果你是客户端模式，服务器强制断开连接，`socket.lua`那边会接收到close 消息， 只是wakeup一下当前操作socket的coroutine。网络连接断开的消息只能通过`socket.lua`的read和write的返回值是不是false来判断，`websocket.lua`的read/write 是`sockethelper.lua`中封装的，网络断开直接抛出`[socket error]`异常的。对于websocket这种有明确的close协议来说， 没有发送close协议而直接断开网络连接本身是违反协议定义的。 正确的关闭是应该调用`websocket.close`发送close协议来通知对方关闭，`websocket.read`也会返回false来表示是否收到对方发送close协议。

**Comment by Fanrncho** [comment]
@lvzixun 好吧，目前没有遇到其他问题了，希望官方针对这些注意点能出个说明文档。

**Comment by lyonscott** [comment]
我在macosx上
```
git clone openssl->configure gcc->make->make install
set
TLS_MODULE=ltls
TLS_LIB=/usr/local/lib
TLS_INC=/usr/local/include
cd skynet->make macosx
```
客户端请求wss后
```
dlopen(~/server/slib/skynet/luaclib/ltls.so, 6): Symbol not found: _ASN1_OCTET_STRING_it
```
请教一下，不知道怎么解决

**Comment by cloudwu** [comment]
请问有没有生产环境尝试用 websocket 分支的？有没有遇到什么问题？我打算合并到主干了。

**Comment by bingo235** [comment]
> 请问有没有生产环境尝试用 websocket 分支的？有没有遇到什么问题？我打算合并到主干了。

生成环境小规模使用没有遇到问题。
建议https://github.com/cloudwu/skynet/blob/918e85b7128606146075073cf34675b33e5429ac/examples/simplewebsocket.lua#L46
加上pcall，不然客户端发送异常数据会有很多报错提示。

**Comment by sabearcher** [comment]
目前在生产环境，刚发现用websocket开服务后，进程会在开服时自杀退出，而且没有报错，还在调试中

**Comment by cloudwu** [comment]
> > 请问有没有生产环境尝试用 websocket 分支的？有没有遇到什么问题？我打算合并到主干了。
> 
> 生成环境小规模使用没有遇到问题。
> 建议
> 
> https://github.com/cloudwu/skynet/blob/918e85b7128606146075073cf34675b33e5429ac/examples/simplewebsocket.lua#L46
> 
> 
> 加上pcall，不然客户端发送异常数据会有很多报错提示。

我觉得有道理，建立连接不成功，可以忽略掉出错提示，或者是写一行简单的提示。

**Comment by lvzixun** [comment]
> > 请问有没有生产环境尝试用 websocket 分支的？有没有遇到什么问题？我打算合并到主干了。
> 
> 生成环境小规模使用没有遇到问题。
> 建议
> 
> https://github.com/cloudwu/skynet/blob/918e85b7128606146075073cf34675b33e5429ac/examples/simplewebsocket.lua#L46
> 
> 
> 加上pcall，不然客户端发送异常数据会有很多报错提示。

https://github.com/cloudwu/skynet/blob/websocket/lualib/http/websocket.lua#L397 

这段是有pcall的， 你说的报错是在握手阶段，或者是解析包失败吗？

**Comment by cloudwu** [comment]
我觉得需要改进的 1. 是 example ，2. 作为库，这里返回 false 是否比 error 更合理？

**Comment by lvzixun** [comment]
> 我觉得需要改进的 1. 是 example ，2. 作为库，这里返回 false 是否比 error 更合理？

https://github.com/cloudwu/skynet/blob/websocket/lualib/http/websocket.lua#L410

那是只需要打印下error信息，同时返回下false就好了？ 主要是不用xpcall的话，在read和调用handle的阶段都有可能出现错误， 为了出现错误能够正常close socket。所以才加的pcall，如果把error给去掉的话， 会导致handle那边的报错，可能会被忽略掉。不过加一个log，貌似也可以吧

**Comment by Fanrncho** [comment]
错误码302的原因是url被重定向了，检查检查是不是后台访问机制的问题 @sabearcher

**Comment by sabearcher** [comment]
@Fanrncho  我可不是一次都没握手成功，是使用没有问题，大概2~3小时后，会突然出现302，然后就不行了

**Comment by ZhouWeikuan** [comment]
android上的微信小游戏wss连接需要验证中间证书，但ltls.c加载时，只加载了服务器证书，客户端连接报错： error <Error: exception onOpen fail code:8, msg: TLS handshake failed>

需要修改lualibb-sr/ltls.c中的函数_lctx_cert，修改下面几行:
    int ret = SSL_CTX_use_certificate_file(ctx_p->ctx, certfile, SSL_FILETYPE_PEM);
    if(ret != 1) {
        luaL_error(L, "SSL_CTX_use_certificate_file error:%d", ret);
    }   

为
    int ret = SSL_CTX_use_certificate_chain_file(ctx_p->ctx, certfile);
    if(ret != 1) {
        luaL_error(L, "SSL_CTX_use_certificate_chain_file error:%d", ret);
    }   

并确保证书文件内即包含服务器证书，也包含中间证书

**Comment by ZhouWeikuan** [comment]
中间证书加载过一次就可以，好像有缓存。因此测试时，可以用
https://www.myssl.cn/tools/check-server-cert.html
来检测中间证书成功与否

**Comment by cloudwu** [comment]
fix #1137
