### ISSUE TITLE
skynet 集成的 OpenSSL 能验证RSA签名吗？ 请指点一二，多谢！

### ISSUE THREAD

**Issue by luosixiang** [cloudwu/skynet#1055]
在做谷歌支付验证， 发行方不肯提供API refresh_token， 我一再说明安全性的情况下还是要求只做 RSA验证， 但是skynet对这方面的支持好像有点少。

**Comment by cloudwu** [comment]
@lvzixun

**Comment by lvzixun** [comment]
不支持， 目前用的`OpenSSL`的地方只有`ltls`这个动态库，而且是对`tls`和`bio`接口的高层封装，专门为tls做的。

**Comment by cloudfreexiao** [comment]
用这个
https://github.com/mkottman/luacrypto

**Comment by luosixiang** [comment]
多谢， 我研究下。
回复真快啊 ！

**Comment by cloudfreexiao** [comment]
或者 这个 
https://github.com/cloudfreexiao/AntServer/blob/master/lualib-src/luacrypto/lua-codec.c

**Comment by luosixiang** [comment]
> 或者 这个
> https://github.com/cloudfreexiao/AntServer/blob/master/lualib-src/luacrypto/lua-codec.c

多谢！ 我都看下， 顺便请教一下，  苹果gamecenter登录的证书验证是否支持？

**Comment by cloudfreexiao** [comment]
没搞过 不清楚 理论上肯定没问题 毕竟 skynet 已经支持 https 了
