### ISSUE TITLE
http 回应内容为空处理相关

### ISSUE THREAD

**Issue by cloudfreexiao** [cloudwu/skynet#1057]
`http 回应 没有内容时(例子如下) 如果使用 readall 会导致一直阻塞 我把这行去掉可行 现在这么处理有其他意义？`

HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: 12917dbe-b1b1-11e9-803d-00163e0cdd40
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.7.7
X-Request-Id: 12917dbe-b1b1-11e9-803d-00163e0cdd40
Date: Mon, 29 Jul 2019 03:29:29 GMT

https://github.com/cloudwu/skynet/blob/master/lualib/http/httpc.lua#L77

**Comment by cloudwu** [comment]
http 0.9 中没有 Content-Length ，http 1.0 也可以选择没有 Content-Length 而读到服务器关闭。

https://stackoverflow.com/questions/15991173/is-the-content-length-header-required-for-a-http-1-0-response

这里没有处理 204 ，应该加上。
