### ISSUE TITLE
watchdog 使用了agent池后,发现回收之后再使用的agent不能垃圾回收内存

### ISSUE THREAD

**Issue by aasdpiao** [cloudwu/skynet#1059]
应用场景如下

![image](https://user-images.githubusercontent.com/10129066/62313063-5be68580-b4c2-11e9-99c0-74ac176c1922.png)

在第5步newservice agent的时候是用的一个服务池来循环使用agent, 每次得到agent后需要重新初始化数据.但是发现agent的内存每次增大一倍. 所以猜测可能是没有垃圾回收掉.我也通过内存快照来看是否有地方没有解引用.

我的agent的大致内容如下

 ```lua
local class = require "class"

local RoleObject = class()

function RoleObject:ctor()
	self.__account_id = 1
	self.__role_name = "role_name"
	self.__level = 1
	self.__gold = 1
	self.__cash = 1
end
-- 逻辑部分全部在RoleObject中处理
local role_object = RoleObject.new()

```

在回收的时候直接对role_object = nil 处理

进入的时候重新生成了一个新的RoleObject对象

我也尝试用https://github.com/cloudwu/lua-snapshot.git 来打印内存快照,但是因为RoleObject内容很多,找不出来.

**Comment by cloudwu** [comment]
把 agent 独立到一个 vm 中最重要的一个原因就是可以把连接相关的数据独立出来可以增加生命期管理的健壮性。我看不到复用它的任何好处。

这个问题似乎和 skynet 完全没有关系，纯粹是你的 lua 代码为什么没有正确的对你认为应该不在引用的对象解引用。任何一处对原有  role_object 的引用留在 vm 中都会阻止回收它。

**Comment by aasdpiao** [comment]
好的,多谢云大

**Comment by cloudwu** [comment]
btw, 如果你希望加快新建 agent 的速度，我建议你可以做一个 agent 分配服务。它不去复用老的 agent ，而是在空闲的时候初始化新的 agent 备用，控制一下总量就好了。

**Comment by aasdpiao** [comment]
好的.多谢建议.我这就改
