### ISSUE TITLE
sproto相关

### ISSUE THREAD

**Issue by cloudfreexiao** [cloudwu/skynet#1060]
目前 sproto tcp 使用 rpc dispatch 的情况是 使用 userdata 
但是在 使用  udp时 数据是 string 请问 能使用 rpc 吗?
或者 udp 中 使用 rpc 是个错误的想法?

**Comment by cloudwu** [comment]
https://github.com/cloudwu/sproto/blob/master/lsproto.c#L472-L487

sproto 在处理输入 buffer 时，应该是同时兼容 string 和 userdata/sz 格式的。

**Comment by cloudfreexiao** [comment]
好的 我试试
