### ISSUE TITLE
service_snlua 模块 init_cb 函数初始化 Lua 疑问

### ISSUE THREAD

**Issue by ylme** [cloudwu/skynet#1064]
https://blog.codingnow.com/2015/05/lua_c_api.html

> 完善的做法是，你应该把你的业务逻辑写到一个 lua_CFunction 中，然后用 lua_pcall 去调用它。而这个代码块的参数则应该用 void * 通过 lua_pushlightuserdata 来传递。

根据这里的描述 init_cb 函数 https://github.com/cloudwu/skynet/blob/master/service-src/service_snlua.c#L76 对于 Lua 虚拟机的初始化，放在 `lua_CFunction` 中会更严谨，是吧。

**Comment by cloudwu** [comment]
这里考虑了所有 oom 之外的 error . 而 skynet 所有地方都不考虑 oom .
