### ISSUE TITLE
lua-clientsocket.c中exit(1)

### ISSUE THREAD

**Issue by iamjokerjun** [cloudwu/skynet#1069]
我们在使用clientsocket作为压测机器人的客户端socket时，发现一个问题，当控制终端关闭时，会出现整个机器人进程退出的情况，经过排查发现问题在stdin关闭了。
if (fgets(tmp,sizeof(tmp),stdin) == NULL) {
    // read stdin failed
    exit(1);
}
这里建议把进程退出改成线程退出pthread_exit。这样不会终端关闭时，整个进程退出的情况了。

**Comment by cloudfreexiao** [comment]
别用它 用 lsocket 或者 luasocket

**Comment by cloudwu** [comment]
不要使用 clientsocket 。

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/blob/master/lualib-src/lua-clientsocket.c#L1-L3
