### ISSUE TITLE
由于缺少autogen.sh导致编译错误

### ISSUE THREAD

**Issue by weiwuzhimeng** [cloudwu/skynet#1071]
3rd/jemalloc下面缺少autogen.sh文件，导致make linux时编译报错：
Makefile:35: recipe for target '3rd/jemalloc/autogen.sh' failed
make[1]: *** [3rd/jemalloc/autogen.sh] Error 128

完整错误：
make all PLAT=linux SKYNET_LIBS="-lpthread -lm -ldl -lrt" SHARED="-fPIC --shared" EXPORT="-Wl,-E" MALLOC_STATICLIB="3rd/jemalloc/lib/libjemalloc_pic.a" SKYNET_DEFINES=""
make[1]: Entering directory '/home/weiwu/workspace/skynet-1.1.0'
git submodule update --init
fatal: Not a git repository (or any of the parent directories): .git
Makefile:35: recipe for target '3rd/jemalloc/autogen.sh' failed
make[1]: *** [3rd/jemalloc/autogen.sh] Error 128
make[1]: Leaving directory '/home/weiwu/workspace/skynet-1.1.0'
platform.mk:40: recipe for target 'linux' failed
make: *** [linux] Error 2

**Comment by cloudfreexiao** [comment]
https://github.com/cloudwu/skynet/wiki/FAQ

**Comment by Javcurry** [comment]
make linux
make[1]: Entering directory '/Users/jake/openProject/skynet'
make all PLAT=linux SKYNET_LIBS="-lpthread -lm -ldl -lrt" SHARED="-fPIC --shared" EXPORT="-Wl,-E" MALLOC_STATICLIB="3rd/jemalloc/lib/libjemalloc_pic.a" SKYNET_DEFINES=""
make[2]: Entering directory '/Users/jake/openProject/skynet'
cd 3rd/jemalloc && ./autogen.sh --with-jemalloc-prefix=je_ --enable-prof
autoconf
./autogen.sh: 5: ./autogen.sh: autoconf: not found
Error 0 in autoconf
Makefile:44: recipe for target '3rd/jemalloc/Makefile' failed
make[2]: *** [3rd/jemalloc/Makefile] Error 1
make[2]: Leaving directory '/Users/jake/openProject/skynet'
platform.mk:40: recipe for target 'linux' failed
make[1]: *** [linux] Error 2
make[1]: Leaving directory '/Users/jake/openProject/skynet'
platform.mk:13: recipe for target 'default' failed
make: *** [default] Error 2

**Comment by Javcurry** [comment]
autoconf 脚本里面的autoconf not found, 导致编译出错

**Comment by hanxi** [comment]
安装 autoconf

https://github.com/cloudwu/skynet/wiki/Build

**Comment by weiwuzhimeng** [comment]
谢谢大家，问题已经解决了，我原来是把tar.gz复制到linux下才报的这个错误，后来我直接在linux下在线下载项目，就不会报这个错误了。
