### ISSUE TITLE
debug_console 退出没有释放socket

### ISSUE THREAD

**Issue by NovoXiaolei** [cloudwu/skynet#1074]
[2019-08-21 12:10:48.35] [SKYNET] [0x0000000b] LAUNCH snlua debug_console 21061
    10 [2019-08-21 12:10:48.36] [SKYNET] [0x0000000b] init service failed: ./skynet/lualib/skynet/socket.lua:360: Listen error
     9 stack traceback:
     8     [C]: in function 'skynet.socketdriver.listen'
     7     ./skynet/lualib/skynet/socket.lua:360: in function 'skynet.socket.listen'
     6     ./skynet/service/debug_console.lua:120: in local 'start'
     5     ./skynet/lualib/skynet.lua:720: in function <./skynet/lualib/skynet.lua:717>
     4     [C]: in function 'xpcall'
     3     ./skynet/lualib/skynet.lua:724: in function 'skynet.pcall'
     2     ./skynet/lualib/skynet.lua:728: in function 'skynet.init_service'
     1     ./skynet/lualib/skynet.lua:741: in upvalue 'f'
247309     ./skynet/lualib/skynet.lua:113: in function <./skynet/lualib/skynet.lua:112>
     1 [2019-08-21 12:10:48.36] [SKYNET] [0x0000000b] KILL self
     2 [2019-08-21 12:10:48.36] [SKYNET] [0x00000008] init service failed: ./skynet/lualib/skynet.lua:358: call failed
     3 stack traceback:
     4     [C]: in function 'error'
     5     ./skynet/lualib/skynet.lua:358: in upvalue 'yield_call'
     6     ./skynet/lualib/skynet.lua:375: in function 'skynet.call'
     7     (...tail calls...)
     8     ./dock/main.lua:166: in local 'start'
     9     ./skynet/lualib/skynet.lua:720: in function <./skynet/lualib/skynet.lua:717>
    10     [C]: in function 'xpcall'
    11     ./skynet/lualib/skynet.lua:724: in function 'skynet.pcall'
    12     ./skynet/lualib/skynet.lua:728: in function 'skynet.init_service'
    13     ./skynet/lualib/skynet.lua:741: in upvalue 'f'
    14     ./skynet/lualib/skynet.lua:113: in function <./skynet/lualib/skynet.lua:112>
    15 [2019-08-21 12:10:48.36] [SKYNET] [0x00000008] KILL self

**Comment by cloudwu** [comment]
不明白

**Comment by NovoXiaolei** [comment]
抱歉我应该换个问法，我应该如何去关闭debug_console中的fd呢

**Comment by NovoXiaolei** [comment]
是我搞错了，我内部用了os.execute导致有个子进程共享了fd，所以没有关闭成功
