### ISSUE TITLE
在mac上编译时出现的错误

### ISSUE THREAD

**Issue by pickline** [cloudwu/skynet#1075]
错误出现在编译master分支commit#65eb351a3b7979代码时
以下是完整错误的输出：
/Applications/Xcode.app/Contents/Developer/usr/bin/make all PLAT=macosx SKYNET_LIBS="-lpthread -lm -ldl" SHARED="-fPIC -dynamiclib -Wl,-undefined,dynamic_lookup" EXPORT="" MALLOC_STATICLIB="" SKYNET_DEFINES="-DNOUSE_JEMALLOC"
cc -g -O2 -Wall -I3rd/lua  -o skynet skynet-src/skynet_main.c skynet-src/skynet_handle.c skynet-src/skynet_module.c skynet-src/skynet_mq.c skynet-src/skynet_server.c skynet-src/skynet_start.c skynet-src/skynet_timer.c skynet-src/skynet_error.c skynet-src/skynet_harbor.c skynet-src/skynet_env.c skynet-src/skynet_monitor.c skynet-src/skynet_socket.c skynet-src/socket_server.c skynet-src/malloc_hook.c skynet-src/skynet_daemon.c skynet-src/skynet_log.c 3rd/lua/liblua.a -Iskynet-src -I3rd/jemalloc/include/jemalloc   -lpthread -lm -ldl -DNOUSE_JEMALLOC
Undefined symbols for architecture x86_64:
  "_luaL_initcodecache", referenced from:
      _main in skynet_main-43f4b4.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [skynet] Error 1
make: *** [macosx] Error 2

**Comment by semgilo** [comment]
都没留下解决方法就关了？

**Comment by Tangkysin** [comment]
遇到了同样的问题，不提新issue了，可以分享下怎么解决吗？

**Comment by pickline** [comment]
你看看是不是有些submodule没拉下来
