### ISSUE TITLE
skynet.cluster 缓存 sender 造成节点地址改变后无法连接

### ISSUE THREAD

**Issue by findix** [cloudwu/skynet#1080]
Hi 云风~

https://github.com/cloudwu/skynet/blob/5025e6887f9ff3c611e38908197a603d438c3320/lualib/skynet/cluster.lua#L41-L57

`cluster.call()` 获取 `clustersender` 时，如果存在，会直接取 table `sender` 缓存，当节点地址变化的时候（比如在Kubernetes容器中），即使调用 `cluster.reload()`，也不会 changenode

我查阅了一下 git log，缓存操作是在 https://github.com/cloudwu/skynet/issues/988 里加入的，去掉缓存，即删除
https://github.com/cloudwu/skynet/blob/5025e6887f9ff3c611e38908197a603d438c3320/lualib/skynet/cluster.lua#L29
可以解决问题。
请问是否有更适合的解决方法呢？ 谢谢~~~

**Comment by cloudwu** [comment]
缓存操作是从一开始就有的， #988 只是保证了次序而已。

改缓存是必须做的，否则所有的消息都需要请求 clusterd ，也就失去了拆分 sender 的意义。

按设计，reload 并不应该生成新的 sender 服务，而是通知已有的 sender 更换 ip 重连。

https://github.com/cloudwu/skynet/blob/master/service/clusterd.lua#L48

如果还是有问题，你找找为什么 reload 没有正确触发 changenode 。

简单说，你错误定位了问题。

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/blob/master/service/clusterd.lua#L89

我猜想，问题出在 loadconfig 后，应该主动把重置的 sender 主动调用一遍 open channel 。

**Comment by cloudwu** [comment]
@findix 看看修好没有？

**Comment by findix** [comment]
试了没问题，感谢！
