### ISSUE TITLE
调用socket.close方法时偶尔会阻塞很久，最长会阻塞半小时，有人遇到过吗，能帮我想想原因吗.

### ISSUE THREAD

**Issue by samoyedsun** [cloudwu/skynet#1083]

**Comment by ylme** [comment]
https://github.com/cloudwu/skynet/blob/master/lualib/skynet/socket.lua#L231-L245
感觉是是不是卡在 https://github.com/cloudwu/skynet/blob/master/lualib/skynet/socket.lua#L240 这一行了？
可以用 debug_console 看看堆栈。

**Comment by samoyedsun** [comment]
> https://github.com/cloudwu/skynet/blob/master/lualib/skynet/socket.lua#L231-L245
> 感觉是是不是卡在 https://github.com/cloudwu/skynet/blob/master/lualib/skynet/socket.lua#L240 这一行了？
> 可以用 debug_console 看看堆栈。

是的，就是这一行，我打日志看出来了。

**Comment by ylme** [comment]
https://github.com/cloudwu/skynet/blob/master/lualib/skynet/socket.lua#L22  wakeup 函数
https://github.com/cloudwu/skynet/blob/master/lualib/skynet/socket.lua#L30 suspend 函数

* 看一下 `wakeup`  函数被调用的地方，看是不是 cotouine 被挂起后没有被 wakeup 。
* 看一下 `suspend` 函数被调用地方。还是被你手动挂起了。

**Comment by turtleLin** [comment]
我也有遇到这种情况
