### ISSUE TITLE
疑问：socket发送数据是否有内存泄漏？

### ISSUE THREAD

**Issue by zjcmtsx** [cloudwu/skynet#1092]
lua-socket.c中lsend函数
`

static int
lsend(lua_State *L) {
	struct skynet_context * ctx = lua_touserdata(L, lua_upvalueindex(1));
	int id = luaL_checkinteger(L, 1);
	int sz = 0;
	void *buffer = get_buffer(L, 2, &sz);  // 分配出内存
	int err = skynet_socket_send(ctx, id, buffer, sz); // 发送完之后好像没看到释放
	lua_pushboolean(L, !err);
	return 1;
}

`

**Comment by zjcmtsx** [comment]
> lua-socket.c中lsend函数
> `
> 
> static int
> lsend(lua_State *L) {
> struct skynet_context * ctx = lua_touserdata(L, lua_upvalueindex(1));
> int id = luaL_checkinteger(L, 1);
> int sz = 0;
> void *buffer = get_buffer(L, 2, &sz); // 分配出内存
> int err = skynet_socket_send(ctx, id, buffer, sz); // 发送完之后好像没看到释放
> lua_pushboolean(L, !err);
> return 1;
> }
> 
> `

工程用的是老版的skynet，我看最新版的skynet已经修复了

**Comment by cloudwu** [comment]
` skynet_socket_send` 的数据，在 socket 线程真正发送后删除。

**Comment by zjcmtsx** [comment]
> ` skynet_socket_send` 的数据，在 socket 线程真正发送后删除。

我们的项目用的很老的版本，应该是2015年 skynet-1.0.0-rc这个版本， sockect发送数据确实是有内存泄漏的。我昨天更新了最新的skynet，泄漏已经没有了。谢谢云风大哥！
