### ISSUE TITLE
sharetable热更不了尚未调用的闭包里的upvalue。

### ISSUE THREAD

**Issue by yxhtx** [cloudwu/skynet#1096]
配置表文件内容：
return {
	[1] = {a = 1}
}

在testsharetable服务的代码：
skynet.start(function()
	sharetable.loadfile(filename)
	local t = sharetable.query(filename)
	local t1 = t[1]

	skynet.timeout(10 * 100, function()
		print("10s later")
		sharetable.loadfile(filename)
		sharetable.update(filename)
	end)

	skynet.timeout(15 * 100, function()
		print("15s later")
		dump(t)
		dump(t1)
	end)
end)

具体操作：
启动服务器后，在第一个定时器执行前手动修改配置表的a的值，发现第二个定时器执行时，dump的两个表t、t1，无论地址和内容都和最初query的表一样。

**Comment by cloudwu** [comment]
@lvzixun

**Comment by yxhtx** [comment]
另外用配置表做table的key时，也不能更新。

**Comment by yxhtx** [comment]
还有一个问题是，不支持第二次热更。
是不是因为sharetable.update里的RECORD[name] = nil放在了sharetable.query(name)后面，导致清空了RECORD的值，下次调用update前如果不调用sharetable.query(name)，RECORD就没有对应的值，从而不能更新。

**Comment by lvzixun** [comment]
@yxhtx  你看下这个PR  #1097 。从未resume的coroutine，table的key，以及多次update的问题，给修复了。

**Comment by yxhtx** [comment]
> @yxhtx 你看下这个PR #1097 。从未resume的coroutine，table的key，以及多次update的问题，给修复了。

好，谢谢大佬。

**Comment by cloudwu** [comment]
@yxhtx 今天我合并了 https://github.com/cloudwu/skynet/pull/1097 ，我已经简单 review 了代码，不过还是麻烦测试一下。

**Comment by yxhtx** [comment]
> @yxhtx 今天我合并了 #1097 （今天比昨天还做了一些修改），我已经简单 review 了代码，不过还是麻烦测试一下。

好，如果有问题我再open。
