### ISSUE TITLE
clusterd.reload不能切换到新的地址

### ISSUE THREAD

**Issue by wanliyun** [cloudwu/skynet#1101]
hi,
    项目里要支持运行时切换cluster中某个node的地址。调用cluster.reload新地址却没有生效。
    初步分析了下：
    services/clusterd.lua文件中clusterd.reload把node_channel[name]置为nil（93行），把node_address[name]切换到新地址（96行）。猜测是为了等下次访问到node_channel[name]时触发loadconfig()完成切换。
     然而，等下次访问node_channel[name]没有等来。cluster.lua文件中之前已经访问过clusterd.sender（这个函数里访问了node_channel[name]）然后缓存起来，之后再也不会调用clusterd.sender了。

   目前我们临时解决了下：
   在clusterd.lua的96行后塞了一行代码，访问node_channel[name]

	                        -- address changed
				if rawget(node_channel, name) then
					node_channel[name] = nil	-- reset connection
					table.insert(reload, name)
				end
line：96 			node_address[name] = address    
                                local XTmp = node_channel[name]  --【HACK】 trigger address change

  不优雅，勉强能用。期待诸神的修复~

**Comment by cloudwu** [comment]
为什么后面的 https://github.com/cloudwu/skynet/blob/master/service/clusterd.lua#L113-L117 没有生效？

没有在这里加是因为连接是个阻塞过程，所以加到了 reload 数组里，后面统一处理。

**Comment by wanliyun** [comment]
额~定睛看了下，我们用的skynet版本比较老~~没有那几行代码！多谢云大！
