### ISSUE TITLE
云风大佬别再一句看wiki打发初学者了，GettingStarted扯一堆架构，请让我能跑起来吧，谢谢

### ISSUE THREAD

**Issue by yrong** [cloudwu/skynet#1104]
➜  skynet git:(master) ✗ lua5.3 ./examples/main.lua
lua5.3: error loading module 'skynet.core' from file 'luaclib/skynet.so':
	luaclib/skynet.so: undefined symbol: dump_mem_lua
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	lualib/skynet.lua:2: in main chunk
	[C]: in function 'require'
	./examples/main.lua:8: in main chunk
	[C]: in ?

**Comment by findix** [comment]
https://github.com/cloudwu/skynet/wiki/Build

**Comment by sishui** [comment]
wiki 看了还跑不起来，多半浮躁没认真看，如果开始就这样，建议早日弃坑

**Comment by yrong** [comment]
＠findix 谢谢
@sishui 不是build不过，试图加载service的问题，自己加载build生成的链接库通过lua直接启服务报的错误．已经解决了,说实话个人觉得这个GettingStarted很不友好，实际是Architectural Design. Any way,如果语气让你觉得不爽,sorry.

**Comment by tangyiyang** [comment]
先说你的问题，你的启动命令（lua5.3 ./examples/main.lua）不对。 skynet并不是用 Lua解释器 来启动是，而是用你build出来的 skynet 可执行文件来启动的，并且启动程序的参数是skynet配置文件，并不是main.lua。所综上，启动命令应该是类似这样的命令： ./bin/skynet ./examples/config.lua。

skynet不是开箱即用的引擎，在这之前，最好先去看一下  PIL (Programming in Lua)，至少要先了解一下Lua作为脚本语言，是如何和宿主程序协作的。

skynet的上手已经足够友好了，这些文档都做了一个基本的假设，skynet的用户有一定的Lua的基础。没有手把手的把每一个步骤都写出来，留一些东西自己探索何尝不是乐趣。 :)

**Comment by sishui** [comment]
> 
> 
> @findix 谢谢
> @sishui 不是build不过，试图加载service的问题，自己加载build生成的链接库通过lua直接启服务报的错误,已经解决了.说实话个人觉得这个[GettingStarted](https://github.com/cloudwu/skynet/wiki/GettingStarted)很不友好，实际是Architectural Design. Any way,如果语气让你觉得不爽,sorry.

你想错了，我只是说 仔细阅读 所有的wiki，大多数基本问题都是能得到答案的

**Comment by cloudwu** [comment]
怎样跑起来见项目首页的 Readme 。

**Comment by yrong** [comment]
@tangyiyang @cloudwu 谢谢

Btw: 毕竟是个8K+的项目了，文档应该可以更友好一些．还是觉得这个项目文档安排不太合理，知识点有点散乱，入门介绍的东西也偏少，所以自己上手的时候有点恼火，当然可能也是自己耐心不够吧．后来花了点时间做了点整理工作(https://yrong.github.io/blog/2018/04/09/intro-to-skynet)
