### ISSUE TITLE
使用websocket 接收WSS连接遇到一些问题。

### ISSUE THREAD

**Issue by luosixiang** [cloudwu/skynet#1109]
Demo：https://github.com/cloudwu/skynet/tree/websocket
证书：使用 openssl req -x509 -newkey rsa:2048 -days 3650 -nodes -keyout server-key.pem -out server-cert.pem 创建
测试环境：本地局域网，服务器为centos虚拟机。
报错日志：
![image](https://user-images.githubusercontent.com/10294716/68653830-8a670880-0567-11ea-80da-a20a7ba95f45.png)

客户端只有WSS连接请求。

对WSS的概念还比较模糊， 客户端必须使用HTTPS 访问才能只能WSS吗？
感谢。

**Comment by lvzixun** [comment]
error 为1 。 那应该是`SSL_ERROR_SSL` 这个错误了。 查看了下 对应openssl的文档： https://www.openssl.org/docs/man1.1.0/man3/SSL_get_error.html 


> SSL_ERROR_SSL
A non-recoverable, fatal error in the SSL library occurred, usually a protocol error. The OpenSSL error queue contains more information on the error. If this error occurs then no further I/O operations should be performed on the connection and SSL_shutdown() must not be called.

**Comment by luosixiang** [comment]
> error 为1 。 那应该是`SSL_ERROR_SSL` 这个错误了。 查看了下 对应openssl的文档： https://www.openssl.org/docs/man1.1.0/man3/SSL_get_error.html
> 
> > SSL_ERROR_SSL
> > A non-recoverable, fatal error in the SSL library occurred, usually a protocol error. The OpenSSL error queue contains more information on the error. If this error occurs then no further I/O operations should be performed on the connection and SSL_shutdown() must not be called.
> 
> 看下是不是协议错误了？ 比如用ws的客户端去请求wss的服务器。

感谢回复。  客户端确认是发的WSS。 代码如下：
![image](https://user-images.githubusercontent.com/10294716/68662678-47616100-0578-11ea-9b71-98cb55976408.png)
cocoscreatoer 的 websocket

**Comment by xiaoqunSun** [comment]
请问下你是怎么解决的  我这边也碰到了这个问题

**Comment by luosixiang** [comment]
我去申请了一个正式证书， 然后IP换成域名就行了。

**Comment by wuwenyi19890101** [comment]
我是gate服务监听端口 检测到连接后new一个agent服务去管理连接 然后在检测到连接断开的时候去关闭当前服务
代码如下
closeSocket = function()
	stopCheckFreeConnectSchedule()
	websocket.close(fd)
	skynet.send(gate, "lua", "disconnect", fd)
	timer.schedule(function()
		skynet.exit()
	end, 50000, "") --500秒后
end

tcp和ws一直都没问题 加入wss后 就会高概率进程崩溃 如果不调用skynet.exit()就没事 后面做了延时在skynet.exit() 也会崩溃 只是概率降低了 不知道具体什么原因导致的 ai的解释如下

这里会走到 tlshelper.lua 里去做 TLS 握手。TLS 握手后，Skynet 会封装底层 fd 的读写（websocket.write()、websocket.close()），并在连接关闭后还可能有一些未释放资源，比如：
SSL socket 的残余回调还没清理
fd 关闭后再调用某些 handler
skynet.exit() 提前导致服务销毁，但 C 侧 TLS 实例还在访问 Lua handler
在 wss 模式下，TLS 卸载需要一个更“完整”的资源回收流程，如果你用 skynet.exit() 提前强制杀服务，可能还没清理完 socket TLS 状态，导致访问已销毁的协程或 handler。

以上是ai的解释 具体不知道怎么解决这个问题

**Comment by hanxi** [comment]
@wuwenyi19890101 用转发模式还是forward? 可以看看这个 https://github.com/hanxi/skynet-demo?tab=readme-ov-file#websocket-watchdog-gate-agent

**Comment by cloudwu** [comment]
skynet.exit() 不会做任何清理工作，你应该在 exit  前尽可能的清理需要清理的东西。

如果你依赖 skynet.exit() ，我觉得更好的方法是直接 kill 进程，差不太多。

**Comment by wuwenyi19890101** [comment]
> [@wuwenyi19890101](https://github.com/wuwenyi19890101) 用转发模式还是forward? 可以看看这个 https://github.com/hanxi/skynet-demo?tab=readme-ov-file#websocket-watchdog-gate-agent

不是nginx转发模式 直接用的skyent提供的wss协议 就是配置了证书后直接把ws改为wss  这里就是一个网关节点 之前做的tcp网关 ws网关都没问题 设计逻辑都是一样的 只是设计wss网关之后出的问题

**Comment by wuwenyi19890101** [comment]
> skynet.exit() 不会做任何清理工作，你应该在 exit 前尽可能的清理需要清理的东西。
> 
> 如果你依赖 skynet.exit() ，我觉得更好的方法是直接 kill 进程，差不太多。而有并发状态的程序，不应该依赖延迟来解决问题，你延迟 500s 也不行。应该确定所有的任务都妥善处理了，才可以调用 skynet.exit() 。
> 
> ps. tls 库并没有任何 callback ，所以不存在 **C 侧 TLS 实例还在访问 Lua handler** ，这点看代码很容易确认：https://github.com/cloudwu/skynet/blob/master/lualib-src/ltls.c

就一个网关节点 之前做的tcp网关 ws网关都没问题 设计逻辑都是一样的 只是设计wss网关之后出现这个问题 我需要在连接断开后退出agent服务 agent服务是绑定连接的 一个连接一个agent 我改成kill试试

**Comment by wuwenyi19890101** [comment]
> [@wuwenyi19890101](https://github.com/wuwenyi19890101) 你的agent是怎么发消息给客户端的？直接调用websocket.write还是把消息发给gate后由gate调用websocket.write？如果是agent直接调用websocket.write的话应该是有多线程问题的。有没有一个最小测试用例？

我是自己写的gate和agent 文件命名为mygate和myagent  对对我就是在gate负责监听 agent负责连接维护包括消息发送接收 确实就是在agent里做了read write 那这样设计是不是有问题

**Comment by wuwenyi19890101** [comment]
> > [@wuwenyi19890101](https://github.com/wuwenyi19890101) 你的agent是怎么发消息给客户端的？直接调用websocket.write还是把消息发给gate后由gate调用websocket.write？如果是agent直接调用websocket.write的话应该是有多线程问题的。有没有一个最小测试用例？
> 
> 具体怎么个多线程问题我不太记得了，很久以前复现过，tls.writefunc 里面好像会有影响。

那可能就是你说的这个原因了 关键是tcp ws都没触发过这个问题(进程崩溃)  我也是前几天添加wss网关的时候 用之前写的ws网关来改的  那就是说不能在agent里面去write了 那接收的没问题吧

**Comment by wuwenyi19890101** [comment]
> [@wuwenyi19890101](https://github.com/wuwenyi19890101) 你的agent是怎么发消息给客户端的？直接调用websocket.write还是把消息发给gate后由gate调用websocket.write？如果是agent直接调用websocket.write的话应该是有多线程问题的。有没有一个最小测试用例？

我在这里随便粘贴主要代码 mygate代码如下
local skynet = require "skynet"
local socket = require "skynet.socket"
local timer = require "timer"
local common = require "common"
local tools = require "tools"


local MAX_CONNECT = 5000
local REPORT_TIME = 1000	--上报连接量定时时间

local service = nil
local connectCount = 0	--连接数量统计

local CMD = {}


function CMD.start(info)
	service = info.service
	local lId = socket.listen("0.0.0.0", common.GATEWAY_PORT)
	assert(lId)
	socket.start(lId, function(cId, cAddr)
		tools.log("new client:", cId, cAddr)
		if(connectCount >= MAX_CONNECT) then
			socket.close(cId)
			return
		end
		local agent = skynet.newservice("myagent")
		skynet.send(agent, "lua", "start", {
			fd = cId,
			addr = cAddr,
			service = info.service,
			gate = skynet.self(),
		})
		connectCount = connectCount + 1
	end)
end

function CMD.disconnect(fd)
	tools.log("on socket disconnect: fd = ", fd)
	connectCount = connectCount - 1
end

function CMD.exit()
	skynet.exit()
end

skynet.start(function()
	skynet.dispatch("lua", function(session, source, cmd, ...)
		local f = assert(CMD[cmd])
		f(...)
	end)

	local function scheduleReportGatewayInfo()
		local info = 
		{
			connectCount = connectCount,
			ip = common.GATEWAY_IP,
			port = common.GATEWAY_PORT,
		}
		skynet.send(service, "lua", "reportGatewayInfo", info)
	end
	timer.schedule(scheduleReportGatewayInfo, REPORT_TIME)
end)


myagent文件如下 去掉了一些协议字段了 还有心跳检测 空连接检测断开等等
local skynet = require "skynet"
local websocket = require "http.websocket"
local timer = require "timer"
local protoid = require "protoid"
local common = require "common"
local tools = require "tools"
local struct= require "struct"

local CMD = {}
local handler = {}
local closeSocket = nil


local function write(data)
	websocket.write(fd, data, "binary")
end

closeSocket = function()
	stopCheckFreeConnectSchedule()
	stopHeartbeatSchedule()
	websocket.close(fd)
	skynet.send(gate, "lua", "disconnect", fd)
	skynet.exit() --就是这里 tcp ws都没问题 wss出问题
end

function handler.connect(cId)
end

function handler.handshake(cId, header, url)
	--握手完毕后，开始验证客户端
	sendCheckClientMsg()
	startHeartbeatSchedule()
end

function handler.message(cId, msg, msg_type)
	assert(msg_type == "binary" or msg_type == "text")
	noRecvTime = 0 --只要收收到消息就置0
	bReceived = true
	onRead(msg)
end

function handler.ping(cId)
end

function handler.pong(cId)
end

function handler.close(cId, code, reason)
	if(not server_close) then --不是服务器主动关闭的话，通知tcp断开消息
		skynet.send(service, "lua", "onClientSocketDisconnect", fd)
		-- tools.log("客户端tcp断开 fd = ", fd)
		closeSocket()
	end
end

function handler.error(cId)
	if(not server_close) then --不是服务器主动关闭的话，通知tcp断开消息
		skynet.send(service, "lua", "onClientSocketDisconnect", fd)
		-- tools.log("客户端tcp断开 fd = ", fd)
		closeSocket()
	end
end

function CMD.start(info)
	gate = info.gate
	service = info.service
	fd = info.fd
	local addr = info.addr
	local size = info.addr:len()
	local pos = info.addr:find(":")
	ip = info.addr:sub(1, pos-1)
	port = info.addr:sub(pos+1, size)
	startCheckFreeConnectSchedule()
	local ok, err = websocket.accept(fd, handler, "wss", addr)
	if not ok then
		tools.log(err)
	end
end

function CMD.send(data)
	write(data)
end

function CMD.close()
	server_close = true
	skynet.send(service, "lua", "onClientSocketDisconnect", fd) --服务器踢，也要通知断开
	-- tools.log("服务器踢 fd = ", fd)
	closeSocket()
end

skynet.start(function()
	skynet.dispatch("lua", function(session, source, cmd, ...)
		local f = assert(CMD[cmd])
		f(...)
	end)
end)

**Comment by cloudwu** [comment]
代码请用 markdown 贴。
