### ISSUE TITLE
使用websocket发送返回消息：The client frame was not masked but all client frames must be masked

### ISSUE THREAD

**Issue by hujunlong** [cloudwu/skynet#1110]
function thrid_websocket_api.sms(data)
  filelog.sys_info("thrid_websocket_api.sms", data)
  thrid_websocket_api.ws_id = websocket.connect(thrid_websocket_api.thirdip)
  websocket.write(thrid_websocket_api.ws_id, data)
  local resp, close_reason = websocket.read(thrid_websocket_api.ws_id)
 
  --websocket.close(thrid_websocket_api.ws_id)
  filelog.sys_info("resp:", resp, "close_reason:", close_reason)
end

--返回close_reason内容，The client frame was not masked but all client frames must be masked ，我使用go语言就没有这个问题，请问是什么情况呢

**Comment by lvzixun** [comment]
The client frame was not masked but all client frames must be masked. `function M.write(id, data, fmt, masking_key)`  确认下 `fmt` 和`masking_key`是什么。

**Comment by hujunlong** [comment]
> The client frame was not masked but all client frames must be masked.
> 
> websocket 的write 函数： `function M.write(id, data, fmt, masking_key)` 确认下 `fmt` 和`masking_key`是什么。

我直接采用默认，没有填写这两个值，我现在添加了 两个参数"text", 0x80 可以了 ，非常感谢！

**Comment by luosixiang** [comment]
> The client frame was not masked but all client frames must be masked.
> 
> websocket 的write 函数： `function M.write(id, data, fmt, masking_key)` 确认下 `fmt` 和`masking_key`是什么。

大佬， 我客户端使用的是binary， 报错 Could not decode a text frame as UTF-8. 
我看了下代码好像text和binary处理方法好像都是同一个， 是这个问题吗？  
之前网上找的ws没问题。
还是我得自己设置一下ws的模式？
