### ISSUE TITLE
websocket 使用wss协议连接 报错

### ISSUE THREAD

**Issue by xiaoqunSun** [cloudwu/skynet#1111]
环境:
Ubuntu 14.04.6 LTS
OpenSSL 1.1.0h  27 Mar 2018 (Library: OpenSSL 1.1.1b  26 Feb 2019)

服务器:
openssl req -x509 -newkey rsa:2048 -days 3650 -nodes -keyout server-key.pem -out server-cert.pem
监听wss
![image](https://user-images.githubusercontent.com/4404089/68750311-a12a5f80-063a-11ea-9689-c8be9363aa40.png)

客户端:
chrmoe console下执行
ws = new WebSocket("wss://xxxx:9948")

服务器报错
![image](https://user-images.githubusercontent.com/4404089/68750120-590b3d00-063a-11ea-9536-38c1cb539a40.png)

**Comment by lvzixun** [comment]
因为你的证书没有被认证。 你可以用`wsdump.py` 用忽略证书来测试。 
` wsdump.py   wss://127.0.0.1:9948/test_websocket -n  -v`

**Comment by xiaoqunSun** [comment]
的确是这个问题 换个证书好了
