### ISSUE TITLE
内存统计问题

### ISSUE THREAD

**Issue by lcy03406** [cloudwu/skynet#1115]
“cmem”命令会把codecache的内存统计到统计到首先加载代码的服务中，特别是会因此报一些已经关闭的服务有内存占用，不利于定位内存泄漏。

看到这个现象一开始我以为是有skynet.pack之后丢给其它服务的内存没有释放（不是担心框架有问题，而是我们项目有一些模块用了skynet.pack），实际是共享代码占用的内存。

#1112 处理了这个问题，但有很多无关代码。

**Comment by cloudwu** [comment]
如非特别必要，我建议用 skynet.packstring 而不是用 skynet.pack 。否则较容易引起泄露。

共享代码的问题，我个人建议你在进程启动的时候，用一个独立服务，扫描目录下所有 .lua 文件，全部预加载一遍。这样运行过程中，就基本不会有临时加载。
