### ISSUE TITLE
请问 websocket binary的正确使用方法。

### ISSUE THREAD

**Issue by luosixiang** [cloudwu/skynet#1116]
以前正常的，换掉ws底层后 客户端报错 Could not decode a text frame as UTF-8.

我用HTML写了一个测试 text连接和收发都是正常的。

**Comment by lvzixun** [comment]
根据websocket标准，binary 只是frame里面的一个类型字段。并不会影响数据的。报错` Could not decode a text frame as UTF-8.`  那估计是客户端那边默认就只接受text类型的frame了。 看下有接口可以修改吗

**Comment by luosixiang** [comment]
感谢回复， 问题已经找到了，  是客户端 sproto 处理的问题。
