### ISSUE TITLE
skynet cluster open_channel maybe trigger repetitive connection

### ISSUE THREAD

**Issue by ylme** [cloudwu/skynet#1118]
https://github.com/cloudwu/skynet/commit/0b83b089b26c8b07730fa205f9d8a7ad3b8bbcac 这次修改会造成 `open_channel` 函数如下调用：

`open_channel` --- wakeup --- maybe `open_channel`
`loadconfig` > node_address change --- reload `open_channel`

其中 --- 表示存在异步。

maybe open_channel 表示 

```
if node_address[key] ~= address then
    return open_channel(t,key)
end
```

reload open_channel 表示

```
for _, name in ipairs(reload) do
    -- open_channel would block
    skynet.fork(open_channel, node_channel, name)
end
```

由于异步环境，所以似乎可能出现如下情况：

maybe `open_channel` 触发并且连接成功，然后 reload `open_channel` 又重新发起了连接请求。也就是说问题是目标节点重新连接成功了，又触发了对目标节点的连接请求。实际使用应该很难出现这种情况，但临界情况下好像会出现，不知道我有没有看错，请指点一下。

**Comment by cloudwu** [comment]
但是 `open_channel` 本身就是设计成可以同时多次调用的，且没有完成的连接过程，会合并成一个。这个函数返回的是一个  clustersender 服务，由它负责建立真正的 socket 连接。而这个服务也被设计成可以多次连接的。

如果发生了以上情况有什么恶果呢？会死循环吗？

**Comment by ylme** [comment]
恶果倒没有，也不会陷入死循环，只是觉得想执行一下 reload ，然后 https://github.com/cloudwu/skynet/blob/master/service/clusterd.lua#L92-L96 这里更新了地址，可能极低概率在临界情况下，`open_channel` 会执行两次，如果第一次 `open_channel` 连接成功返回了，第二次的 `open_channel` 还是会执行会有点怪。
当前这些只是忽略实际环境的分析，现实中很难这样。
