### ISSUE TITLE
c层共享数据问题

### ISSUE THREAD

**Issue by rdcentermrzhi** [cloudwu/skynet#1127]
我用sharedata 做游戏配置， 我在其他服务的c层会用到相关的配置数据，配置数据较大，但是将配置数据传入c层 会不会影响效率， 大家有没有什么好的办法

**Comment by cloudwu** [comment]
1. 目前比较推荐使用 sharetable
2. 所谓的 C 层都是服务中的一个库，配置数据应该作为参数传入，而不建议从 C 中再读外部的表。
3. 考察所谓 C 层存在的必要性，看能否用 lua 重写。

**Comment by rdcentermrzhi** [comment]
了解
