### ISSUE TITLE
初步观察是一个内存复写的问题

### ISSUE THREAD

**Issue by rdcentermrzhi** [cloudwu/skynet#1135]
print(netpack4.tostring(msg, sz) .. "\n")
  local pb = assert(io.open("./proto/pb/gamedata.pb"))
  local buffer = pb:read "*a"
  pb:close()
  **--protobuf.register(buffer)**
  print(msg, sz)
  print(netpack4.tostring(msg, sz) .. "\n")

1.netpack4 是我参考 netpack.c 自己定义的分包模块
2.msg 是lightuserdata 
3.  protobuf 用的是pbc
问题：当我用 调用protobuf.register(buffer) 后  userdata 的内存被改写了

**Comment by cloudwu** [comment]
我不太明白你想表达什么。但我不建议自己写任何 c 模块直接操作 lightuserdata.

服务收到的指针应在第一时间一律转化为 lua string 后再进行进一步操作，不应再使用该指针。

**Comment by rdcentermrzhi** [comment]
1.整个服务就是一个类似https://github.com/YKPublicGame/chess_server/blob/9a1024c06661174a803beefed9e9eae4370a47a5/service/pbc.lua#L25
pbc 解析服务 
2. msg 是在c 分配的内存， 当我调用protobuf.register(buffer) 之后， 我发现msg指向内存被修改了 这是第一个问题
3. msg 是socket读取的数据 转换到lua string会不会影响效率

**Comment by rdcentermrzhi** [comment]
> 我不太明白你想表达什么。但我不建议自己写任何 c 模块直接操作 lightuserdata.
> 
> 服务收到的指针应在第一时间一律转化为 lua string 后再进行进一步操作，不应再使用该指针。

1.整个服务是类似 https://github.com/YKPublicGame/chess_server/blob/9a1024c06661174a803beefed9e9eae4370a47a5/service/pbc.lua#L25 的一个pbc 解析服务
2.上边的msg是 c 中分配的内存，但是当我在调用 protobuf.register(buffer) 之后，发现 msg 指向的内存被修改了
3.lightuserdata -> msg 是从socket中的读取的数据，每次都转化成lua string 会不会影响效率， 我看到你之前写的example/agent.lua  采用lightuserdata + sz 的方式 给sproto 去解析的

**Comment by cloudwu** [comment]
所有 skynet 传递给服务的消息 (lightuserdata) 都是临时的，在没有搞清楚前，不要承诺任何关于数据的生命期。

这就是为什么 skynet 的 lua 框架为什么在消息处理阶段要分 unpack 和 dispatch 两个 callback 。消息必须在 unpack 阶段处理完，并保证在 unpack 结束后，没有任何地方持有这个指针及指向的内容，且 unpack 函数中不应该调用任何阻塞 api ，甚至不要调用任何 skynet api 。仅仅把数据读出来转换成需要的，由 lua 管理的对象。

然后 dispatch 才去处理这个消息代表的对象。dispatch 并不直接处理指针。

**Comment by rdcentermrzhi** [comment]
目前我怀疑是我的protobuf文件太大了， 注册的时候出现了问题， 把文件分解开来就没问题了，  我先关闭这个issue， 留待以后仔细研究
