### ISSUE TITLE
一个服务中调用pbc解析的问题

### ISSUE THREAD

**Issue by rdcentermrzhi** [cloudwu/skynet#1136]
```
local skynet = require "skynet"
local protobuf = require "protobuf"
require "print_r"
require "skynet.manager"

local function register_proto()
      protobuf.register_file("game.pb")
end

local function read_pb()
  local pb = assert(io.open("game.data"))
  local buffer = pb:read "*a"
  pb:close()
  print_r(protobuf.decode("Game", buffer))
end

local CMD = {}

function CMD.encode(name, msg)
  return protobuf.encode(name, msg)
end

function CMD.decode(name, msg, sz)
  read_pb()
end



skynet.start(function()
  register_proto()
  read_pb()

  print("pbcd start")
  skynet.dispatch("lua", function (_, address, cmd, ...)
    local f = CMD[cmd]
    if not f then
      skynet.ret(skynet.pack(nil, "Invaild command" .. cmd))
      return 
    end
    skynet.ret(skynet.pack(f(...)))
  end)

  skynet.register("pbcd")
end)
```
问题：当我在服务初始化的过程中调用 read_pb 它所解析出的 数据是正确， 当我发送消息调用 CMD.decode 的时候  read_pb 此时解析出来的数据是错误的 ， 解析出来的数据不是完全错误， 是有部分数据没有解析出来， 主要是一个map ，帮剖析一下是什么问题，是什么地方影响了解析？。
1 . 解析protobuf 用的是pbc

**Comment by cloudwu** [comment]
不建议在消息传递指针，你的代码你完全看不到指针指向的内存是如何在管理的。

**Comment by rdcentermrzhi** [comment]
> 不建议在消息传递指针，你的代码你完全看不到指针指向的内存是如何在管理的。

我还是不太理解
1、 “game.data” 是二进制数据，  我每次打开的用pbc 解析，他的结果不应该是一样的吗？
为什么俩次的解析结果会不同那
2. 你所说的指针是指 msg， 还是指？
刚开始接触skynet， 有什么说的不对的地方， 还希望不吝指正

**Comment by cloudwu** [comment]
我看错了，你的  `CMD.decode(name, msg, sz)` 里并没有使用 msg 这个参数。

那么，你的整段程序就和 skynet 完全没有关系了。你应该在 skynet 外的 lua 环境做好测试。

btw,  严格来说， io.open 应该加上 "b" 确保是 binary 模式打开。

**Comment by rdcentermrzhi** [comment]
> 我看错了，你的 `CMD.decode(name, msg, sz)` 里并没有使用 msg 这个参数。
> 
> 那么，你的整段程序就和 skynet 完全没有关系了。你应该在 skynet 外的 lua 环境做好测试。
> 
> btw, 严格来说， io.open 应该加上 "b" 确保是 binary 模式打开。


参考 我之前的 https://github.com/cloudwu/skynet/issues/1135#issuecomment-566877198
```
function CMD.decode(name, msg, sz)
  netpack4.see(msg, sz);
  local ret, err = protobuf.decode(name, msg, sz)
  netpack4.see(msg, sz)
end
```
我大概理清楚了问题：
1. 我在c 层自己分配了内存，  然后lightuserdata传到 pbc 服务处理， c 层分配的内存由我自己管理
2. 当我在 上边pbc 服务中调用 protobuf.decode(name, msg, sz) 发现 lightuserdata 指向的数据被修改了
3. 在此之前我并没有释放lightuserdata 指针的内存

现象1：当前服务 pbc 解码的时候如果传入msg， sz  他会修改msg 指向的内存？
现象2 ：我在下边其他服务中 调用 protobuf.decode(name, msg, sz)  并没有此发现这种问题
```
skynet.register_protocol {
        name = "client",
        id = skynet.PTYPE_CLIENT,
        unpack = function (msg, sz)
               return netpack4.unpack(msg, sz)
        end,
        dispatch = function (fd, _, msgid, ...)
                assert(fd == client_fd) -- You can use fd to reply message
                skynet.ignoreret()      -- session is fd, don't call skynet.ret
                skynet.trace()
              print(msgid)
             local msg, sz = ...
              netpack4.see(msg, sz)
 --           local data = protobuf.decode("GlobalSetting", msg, sz)
          local b = protopack.unpack(msgid, msg, sz) -- 将msg转至pbc 服务处理
               netpack4.see(msg, sz)
    end
}

```
能看出什么问题吗？  给个思路也可以， 多谢

**Comment by cloudwu** [comment]
1. 如果你传入 dispatch 的内存指针是你自己分配的，那么你应该检查内存管理是否正确，比如是否有 double free 。https://github.com/cloudwu/skynet/wiki/MemoryHook 而且，我也没看见你何时释放该指针。个人认为，很难在 lua 代码中正确做此管理。
2. 如果此内存指针依赖服务传入的消息内存，那么你违背了 unpack 和 disptach 分离的原则。该指针应该只在 unpack 中使用。
3. 我建议你不要在 lua 中玩 lightuserdata , 全部改成 string , 然后在必要的时候再小心考虑优化。

**Comment by rdcentermrzhi** [comment]
> 1. 如果你传入 dispatch 的内存指针是你自己分配的，那么你应该检查内存管理是否正确，比如是否有 double free 。https://github.com/cloudwu/skynet/wiki/MemoryHook 而且，我也没看见你何时释放该指针。个人认为，很难在 lua 代码中正确做此管理。
> 2. 如果此内存指针依赖服务传入的消息内存，那么你违背了 unpack 和 disptach 分离的原则。该指针应该只在 unpack 中使用。
> 3. 我建议你不要在 lua 中玩 lightuserdata , 全部改成 string , 然后在必要的时候再小心考虑优化。


查了一整天， 还是没有头绪， 大概定位到 https://github.com/cloudwu/pbc/blob/54cb548fdab16f94f48a054e33cc17e889460820/src/decode.c#L125
我注意到内存在 执行完decode_cb 后就被修改了， 但是我仔细看了代码，并没有发现函数中有修改 用户内存的代码， 令我很费解
我打开了double free 的检查， 但目前和内存释放的关系并不大，此时我并没有释放， 主要是内存被修改了
总之很费解
如果实现找不到问题的话， 只能直接转lua string 处理了

**Comment by cloudwu** [comment]
如果和 pbc 的实现有关联，那么你应该在 skynet 外就能测试出来。不必在 skynet 内部去调试。

pbc 虽然已经没有在维护了，但是我确定它的 decode 是线程安全的。在 skynet 环境下和外部独立环境有什么不同。

**Comment by rdcentermrzhi** [comment]
> 如果和 pbc 的实现有关联，那么你应该在 skynet 外就能测试出来。不必在 skynet 内部去调试。
> 
> pbc 虽然已经没有在维护了，但是我确定它的 decode 是线程安全的。在 skynet 环境下和外部独立环境有什么不同。

我仔细阅读skynet wiki 的时候发现这么一段话：
**skynet 服务间传递的消息在底层是用 C 指针/lightuserdata 加一个数字长度来表示的。当一条消息进入 skynet 服务时，该消息会根据消息类别分发到对应的类别处理流程，（由 skynet.register_protocol ) 。这个消息数据指针是由发送消息方生成的，通常是由 skynet_malloc 分配的内存块。默认情况下，框架会在之后调用 skynet_free 释放这个指针**
我开启double free 检查之后， 自己手动释放内存就会 触发 double free ，
也就说我用skynet_malloc 分配的内存被框架释放掉了 
```
-- It's safe to redirect msg directly , gateserver framework will not free msg.
skynet.redirect(agent, c.client, "client", fd, msg, sz)
```
我在示例 service/gate.lua 中也找到了相关的解释

现在关于如何不让框架自动释放内存， wiki 给出了skynet.forward_type方案 , 但是相关代码只在 service/clusterproxy.lua 出现过 ，我初步试了一下， 还没解决
能不能用gateserver 改写个demo
这几天收获颇多，特别感谢云风大佬的耐心解答

**Comment by rdcentermrzhi** [comment]
问题已经解决了， 就是因为框架释放了内存，后来在另一个服务解析protobuf 的时候，内存会出现覆盖掉的情况， 和pbc 没有关系 ， 多谢大佬这段时间的耐心解答

**Comment by rdcentermrzhi** [comment]
https://github.com/cloudwu/skynet/issues/1135， 也是这个问题导致的， 关联一下
