### ISSUE TITLE
热更修复BUG

### ISSUE THREAD

**Issue by fisher-an** [cloudwu/skynet#1138]
假如我的skynet service调用到的函数都以全局table的成员函数形式写比如
player.lua
local player = {}
funciton player:test()
  print("test")
end
return player
在热更的时候能否这样
inject_player.lua
local player = require "player"
function player:test()
    print("new test")
end

感觉这种形式的热更，要比通过修改upvalue更加直观， 请问大神这种写法有什么缺陷吗？

另外我修改了lauxlib.c luaL_loadfilex函数，用skynet封装的rwlock，在新文件的写入CC.L时，直接加写锁，读取缓存时加读锁，目的是为了在热更时可以根据文件名清除个别文件的缓存，同时close 对应的luavm，不至于内存泄漏。
虽然这样做会使得缓存文件的临界区比较大，但是感觉可以在开启服时，通过一个管理service把所有lua文件加载到缓存，之后的newservice都是通过加读锁来读取缓存。大概测了一下，newservie的性能影响不是很大。
这么做的目的是想后期热更修复bug时，通过一个功能服务以如下的形式来热更：
reload  xxx.lua
sleep(5s) --保证所有启动中服务启动完成
notify all service  inject   patch.lua

**Comment by 564052619** [comment]
我修改了lauxlib.c luaL_loadfilex函数，用skynet封装的rwlock，在新文件的写入CC.L时，直接加写锁，读取缓存时加读锁，目的是为了在热更时可以根据文件名清除个别文件的缓存，同时close 对应的luavm，不至于内存泄漏。
虽然这样做会使得缓存文件的临界区比较大，但是感觉可以在开启服时，通过一个管理service把所有lua文件加载到缓存，之后的newservice都是通过加读锁来读取缓存。大概测了一下，newservie的性能不是很大影响。
这么做的目的是想后期热更修复bug时，通过一个功能服务以如下的形式来热更：
reload  xxx.lua
sleep(5s) --保证所有启动中服务启动完成
notify all service  inject   patch.lua

**Comment by fisher-an** [comment]
1. 

- 
-
