### ISSUE TITLE
multicastd的channel_id的越界问题

### ISSUE THREAD

**Issue by hongsx** [cloudwu/skynet#1139]
lua-multicast.c文件里面的channel_id生成函数生成的channel_id的范围是0~2的32次方
static int
mc_nextid(lua_State *L) {
	uint32_t id = (uint32_t)luaL_checkinteger(L, 1);
	id += 256;
	lua_pushinteger(L, (uint32_t)id);
	return 1;
}

但是lua-skynet.c文件的send_message函数里面的session在值大于2的31次方时会变成负数

所以只要某个skynet节点下multicast的channel_id超过2的31次方的时候就会出现如下的错误
[:00000008] lua call [8 to :8 : -2147483648 msgsz = 8] error : ../lualib/skynet.lua:642: ../lualib/skynet.lua:184: ../lualib/skynet/multicast.lua:74: Unknown channel -2147483648
stack traceback:
	[C]: in function 'error'
	../lualib/skynet/multicast.lua:74: in upvalue 'f'
	../lualib/skynet.lua:141: in function <../lualib/skynet.lua:113>
stack traceback:
	[C]: in function 'assert'
	../lualib/skynet.lua:642: in function 'skynet.dispatch_message'

**Comment by cloudwu** [comment]
我觉得限制在 31bit 能解决这个问题。

另外，目前并没有处理同时超过 2^23 （大约 800 万) 个 channel 的情况，会死循环。  https://github.com/cloudwu/skynet/blob/master/service/multicastd.lua#L24

我觉得内存会先不够，但如果真碰到l了可能需要改改。

**Comment by hongsx** [comment]
排查了下，还是游戏业务逻辑有问题，拼命创建累积下来的，multicastd内存达到2g
