### ISSUE TITLE
sharetable 使用方式 疑问

### ISSUE THREAD

**Issue by cloudfreexiao** [cloudwu/skynet#1143]
请教下 云大 sharetable 在使用上 是 多个文件 合并成 一个 大的 文件 里面再加个 key 对应 文件内容
还是 直接 就按 单个文件来使用 哪个 会效率高点

**Comment by cloudwu** [comment]
都差不多。但如果你需要更新部分的话，建议拆分，这样更新时加载方便一点。

管理上讲，一个更好。

**Comment by cloudfreexiao** [comment]
好的 谢谢解答
