### ISSUE TITLE
怎么跑docker?

### ISSUE THREAD

**Issue by minchieh2014** [cloudwu/skynet#1147]
希望加入Dockerfile

**Comment by cloudfreexiao** [comment]
https://github.com/cloudwu/skynet/pull/618

**Comment by cloudfreexiao** [comment]
https://github.com/cloudwu/skynet/issues/1085

**Comment by LeonWQL** [comment]
1) 首先在本地拉取skynet,  

git clone https://github.com/cloudwu/skynet

2) 然后创建一个Dockerfile
------------------------------------------------------------------------------
FROM alpine:latest

# Install tools required for project
# Run `docker build --no-cache .` to update dependencies
RUN apk add --update alpine-sdk
RUN apk add readline-dev readline autoconf

# 设置Git代理，skynet编译会拉取jemalloc
ENV http_proxy http://172.16.40.180:80
ENV https_proxy http://172.16.40.180:80

# 拷贝项目
COPY ./skynet /skynet
# 设置工作路径
WORKDIR /skynet
# 编译
RUN make linux
# 如果需要，在这里清除源码目录

# multi-stage build
FROM alpine:latest 

RUN apk add --no-cache libgcc readline
COPY --from=0 /skynet /skynet
WORKDIR /skynet
CMD ["./skynet", "./examples/config"]
------------------------------------------------------------------------------

3) 编译docker image 
docker build -t skybox:latest .

4) 测试 server
docker run --rm -it --name skybox_srv skybox ./skynet examples/config

5) 测试client
docker exec -it skybox_srv ./3rd/lua/lua examples/client.lua
