### ISSUE TITLE
进程间集群通信,clusteragent内存泄漏

### ISSUE THREAD

**Issue by lxqan2010** [cloudwu/skynet#1150]
进程间集群通信中,每创建一个Agent集群调用时,clusteragent服务c层会泄漏8个字节.

**Comment by cloudwu** [comment]
问题似乎出在这里

https://github.com/cloudwu/skynet/blob/master/service/clusteragent.lua#L84

这里的 msg,sz 替换了消息传入的 msg, sz 。但是消息传入的 msg,sz 会被框架释放，但这个不会。这里应该改用 skynet.packstring 。
