### ISSUE TITLE
websocket 握手失败时，仍会跑到 handshake 

### ISSUE THREAD

**Issue by hangj** [cloudwu/skynet#1152]
https://github.com/cloudwu/skynet/blob/ac38fd620b64c67dc342e23d754b95eae0139592/lualib/http/websocket.lua#L244-L249

如果 `read_handshake` 返回的 code 不为 nil，不管 `httpd.write_response` 返回的 ok 是否为 true，都应该调用 `error`

是否应该改为 
```lua
if code then
    local ok, s = httpd.write_response(self.write, code, err)
    error(ok and s or err)
end
```

**Comment by lvzixun** [comment]
你看下这个PR： https://github.com/cloudwu/skynet/pull/1153 如果握手失败的话， 应该触发`close`直接退出`resolve_accept`函数就好了。
