### ISSUE TITLE
clusterd服务突然生成大量clusteragent服务

### ISSUE THREAD

**Issue by liqigit** [cloudwu/skynet#1155]
### 背景
> A，B，C三台服务器在同一集群并且在同一个物理局域网下，服务器之间通过cluster.call请求。
skynet使用的1.2.0版本，commitid：304272249e667c7dbc9a293e59d981692588946c

### 问题描述

> A上出现大量skynet call faild的错误，B服务器中出现大量生成clusteragent的log。但同时AC，BC之间都是正常的，说明网络应该是没问题。尝试过多次没有复现问题，现在无从下手，请大家多多指教🙏

如下是A服务器上的错误
```
[:0000000a] 02-20 21:06:58 ./skynet/lualib/skynet/socketchannel.lua:411: ./skynet/lualib/skynet.lua:356: call failed
[:0000000a] 02-20 21:07:09 ./skynet/lualib/skynet/socketchannel.lua:411: ./skynet/lualib/skynet.lua:356: call failed
[:0000000a] 02-20 21:07:15 ./skynet/lualib/skynet/socketchannel.lua:411: ./skynet/lualib/skynet.lua:356: call failed
[:0000000a] 02-20 21:08:00 ./skynet/lualib/skynet/socketchannel.lua:411: ./skynet/lualib/skynet.lua:356: call failed
```

如下是B服务器上的log
```
[:00000009] 02-20 21:42:12 socket accept from 47.106.226.241:56538
[:00000917] 02-20 21:42:12 LAUNCH snlua clusteragent 9 29 1282
[:00000009] 02-20 21:42:17 socket accept from 47.106.226.241:56564
[:00000918] 02-20 21:42:17 LAUNCH snlua clusteragent 9 29 1283
[:00000009] 02-20 21:42:22 socket accept from 47.106.226.241:56588
[:00000919] 02-20 21:42:22 LAUNCH snlua clusteragent 9 29 1284
[:00000009] 02-20 21:42:27 socket accept from 47.106.226.241:56610
[:0000091a] 02-20 21:42:27 LAUNCH snlua clusteragent 9 29 1285
```

**Comment by liqigit** [comment]
@cloudwu 哥，请问这个地方是不是有bug，clusteragent应该是clusterd服务生成的，看逻辑应该每个节点映射一个agent。

**Comment by cloudwu** [comment]
一个连接一个，连接断开后销毁。

**Comment by liqigit** [comment]
> 一个连接一个，连接断开后销毁。

看log生成的clusteragent没有销毁，那就是说两台服务器间的连接并没有断开对么？但如果连接没断开的话又怎么会不停地建立连接呢。。烦请云风大大指点一下，感谢 @cloudwu

**Comment by cloudwu** [comment]
你可以尝试重现问题，加点 log 调试，找到问题后欢迎提 pr 。

**Comment by liqigit** [comment]
> 你可以尝试重现问题，加点 log 调试，找到问题后欢迎提 pr 。

@cloudwu 感谢回复～最近几天一直在尝试复现，但还没成功😂。等后面后进展再重开issue吧，再次感谢🙏

**Comment by cloudwu** [comment]
我刚才看到你前面贴的 log 时间似乎对不上：

A服务器上的错误，是 02-20 21:06:58，B 服务器 02-20 21:42:12 socket accept from 47.106.226.241:56538

相差了半个小时以上。

你需要确认是不是真的 A 的 skynet 进程向 B 发起的连接。

如果有别的和 skynet 无关的地方向 B 发起连接而不断开，也会产生这个现象。如果你要搭建 skynet 集群，应该仔细设置防火墙，避免无关的干扰。

**Comment by liqigit** [comment]
> 我刚才看到你前面贴的 log 时间似乎对不上：
> 
> A服务器上的错误，是 02-20 21:06:58，B 服务器 02-20 21:42:12 socket accept from 47.106.226.241:56538
> 
> 相差了半个小时以上。
> 
> 你需要确认是不是真的 A 的 skynet 进程向 B 发起的连接。
> 
> 如果有别的和 skynet 无关的地方向 B 发起连接而不断开，也会产生这个现象。如果你要搭建 skynet 集群，应该仔细设置防火墙，避免无关的干扰。

@cloudwu 感谢回复

上面贴log时没注意时间问题，已经修改到相同时间段的log。log文件里有大量上面这种log，这里我只贴了其中几条。

防火墙已经配置过了，集群端口只允许内网访问。`如果有别的和 skynet 无关的地方向 B 发起连接而不断开，也会产生这个现象`，你提醒的这点我会在内网机器上继续排查，看看是否有其他的进程也在使用相同的端口。

再次感谢～
