### ISSUE TITLE
增加 编译 lua 选项

### ISSUE THREAD

**Issue by cloudfreexiao** [cloudwu/skynet#1158]
在 加入 https://github.com/cloudwu/luareload/blob/proto/Makefile 编译时 报错信息

`/usr/bin/ld: ../skynet/3rd/lua//liblua.a(lapi.o): relocation R_X86_64_32 against hidden symbol `luaO_nilobject_' can not be used when making a shared object
/usr/bin/ld: ../skynet/3rd/lua//liblua.a(ldebug.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
`

`https://github.com/cloudwu/skynet/blob/master/Makefile#L18` 
解决需修改为
`cd 3rd/lua && $(MAKE) CC='$(CC) -std=gnu99 -fPIC' $(PLAT)`

**Comment by cloudwu** [comment]
skynet 并未生成 lua 的动态库，你错误链接了 lua 。
