### ISSUE TITLE
mysql 测试用例 bug

### ISSUE THREAD

**Issue by cloudfreexiao** [cloudwu/skynet#1165]
由于 mysql 字符集 utf8 不是 真正的 utf8 
https://mathiasbynens.be/notes/mysql-utf8mb4
修改测试用例(>= 0x8F 必定为 0x3F) 可重现 此 bug
修改 query 字符集 可解决此问题
https://github.com/cloudfreexiao/skynet/commit/405200b4b75fb8ccabd03e3531d36198fd31a2e9

**Comment by cloudwu** [comment]
提个 pr ?
