### ISSUE TITLE
skynet.timeout 压力大时不准

### ISSUE THREAD

**Issue by liangmanlin** [cloudwu/skynet#1170]
我使用了skynet去模拟客户端，开启了300个lua虚拟机，模拟时发现，两次timeout的时差有时候只有30毫秒。

```
skynet.timeout(10,loop)
```
我是这样进行的update

按道理来时skynet是单调时间，应该都是整100毫秒才对

**Comment by HiKit** [comment]
主循环里用 skynet.now() 或 os.time()
