### ISSUE TITLE
使用skynet.db.mysql模块连接TIDB时可能会有报错

### ISSUE THREAD

**Issue by yulingxie** [cloudwu/skynet#1172]
使用skynet.db.mysql模块连接TIDB时报错如下：
![image](https://user-images.githubusercontent.com/13938007/78645738-91adfa80-78ea-11ea-872e-dc4b8cf0fcf2.png)
推测为字符集问题，查看了skynet.db.mysql的代码，将下列代码中的strrep("\0", 24)改为0，则连接成功：
![image](https://user-images.githubusercontent.com/13938007/78646079-1bf65e80-78eb-11ea-81bc-1c5c01805030.png)

tidb版本5.7.25-TiDB-v3.0.3， 默认字符集utf8

**Comment by cloudwu** [comment]
我对 mysql 不熟悉，能否尝试提一个 pr ，完成代码中的 todo ?

ps. 在 issue 中帖代码(以及 log) 时请不要截图，可按下列方式引用。
https://github.com/cloudwu/skynet/blob/master/lualib/skynet/db/mysql.lua#L410-L420
```lua
local scramble = scramble1 .. scramble_part2
local token = _compute_token(password, scramble)
local client_flags = 260047
local req = strpack("<I4I4c24zs1z",
            client_flags,
            self._max_packet_size,
            strrep("\0", 24), -- TODO: add support for charset encoding
            user,
            token,
            database
        )
```

**Comment by yulingxie** [comment]
额，我对mysql也不是很了解，以后有能力会尝试pr

**Comment by cloudfreexiao** [comment]
@yulingxie  麻烦测试下这个 pr 如果有mysql 环境也一并验证下 谢谢了
https://github.com/cloudwu/skynet/pull/1173

**Comment by cloudwu** [comment]
赞， @yulingxie 看看，如果没有问题我就合并。
