### ISSUE TITLE
关于单个服务内的异步操作

### ISSUE THREAD

**Issue by bjut-hz** [cloudwu/skynet#1175]
写业务逻辑的时候我们很容易遇到这种情况，在一个函数内连续调用多个服务，但是这几个服务是完全独立的，数据之间没有依赖关系，在skynet里，经常用`skynet.call`接口来调用：
```
local ret1 = skynet.call(service1, ...)
local ret2 = skynet.call(service2, ...)
``` 
其实连续两个服务调用时完全独立的，不必等到service1返回后才调用service2。在skynet里怎么能实现service1跟service2的同时调用呢？

我有个不成熟的实现方案：增加一个新的接口，并且实现一个类似于go里面的WaitGroup，碰到上述需求时，在调用最后一个服务后使用WaitGroup的wait操作(wait操作会让出协程)来等待所有服务的返回。调用这个新的接口时，协程不会让出，相当于使用skynet.send发送单向消息给对应的服务，skynet框架对所有的被调用服务的响应做汇总处理，只有都返回时，wait操作才会返回，业务逻辑才会继续向下执行。

**Comment by cloudwu** [comment]
这个你可以自己封装一个，不需要在底层加接口。

同时调用可以用 
```lua
skynet.fork(function() skynet.call(service1, ...) end)
skynet.fork(function() skynet.call(service2, ...) end)
```

如果需要等所有的返回，则需要用 skynet.wakeup / skynet.wait 封装一下。例如：
```lua
local function wait_n(n)
  local id = 0
  local token = {}
  local function wakeup_func()
    id = id + 1
    if id >=n then
        skynet.wakeup(token)
    end
  end
  local function wait_func()
    skynet.wait(token)
  end
  return wait_func, wakeup_func
end
local wait, wakeup = wait_n(2)
skynet.fork(function() skynet.call(service1, ...) wakeup() end)
skynet.fork(function() skynet.call(service2, ...) wakeup() end)
wait()
end
```
以上只是简单的示范，你还需要进一步的用 pcall 处理异常等。

**Comment by hongling0** [comment]
给一个可以直接用的
```lua
local skynet = require "skynet"

---@class parallels
local _M = {}

local _MT = {__index = _M}

---@return parallels
local function new()
    return setmetatable(
        {
            list = {},
            boot_co = nil,
            boot_error = nil
        },
        _MT
    )
end

local function wakeup_waitco(self, err)
    if not self.boot_error then
        self.boot_error = err
    end
    local boot_co = self.boot_co
    if boot_co then
        self.boot_co = nil
        skynet.wakeup(boot_co)
    end
end

local function wait_end(self)
    assert(not self.boot_co, "allready in wait %s", tostring(self.boot_co))
    self.boot_co = coroutine.running()
    if not next(self.list) then
        skynet.yield()
    else
        skynet.wait(self.boot_co)
    end
    if self.boot_error then
        error(self.boot_error)
    end
end

---@param self parallels
---@param func fun(...):...
---@param ... any
---@return void
function _M.add(self, func, ...)
    local token = {}
    local list = self.list
    list[token] = true
    skynet.fork(
        function(...)
            token.co = coroutine.running()
            local ok, err = xpcall(func, debug.traceback, ...)
            if not ok then
                wakeup_waitco(self, err)
            else
                list[token] = nil
                if not next(list) then
                    wakeup_waitco(self)
                end
            end
        end,
        ...
    )
end

---@param self parallels
---@return void
function _M.wait(self)
    return wait_end(self)
end

return new
```
使用
```lua
local pa = require("parallels")()
local ret1,ret2
pa:add(function()
    ret1 = skynet.call(service1, ...)
end)
pa:add(function()
    ret2 = skynet.call(service2, ...)
end)

pa:wait()

print(ret1,ret2)
```

**Comment by cloudwu** [comment]
今天重写了一般，移除了所有的限制。

目前的用法是：

1. 调用 reqs =skynet.request() 创建一个请求对象。
2. 调用 reqs:add { ... } 添加请求。
3. for resp, req in reqs:select(timeout) 处理回应，其中 timeout 为可选。resp.ok 为 fasle 时，请求失败；为 nil 时，地址不存在；为 true 时，可以用 table.unpack(resp, 1, resp.n) 展开回应。req 为对应的请求。

另外，可以用 skynet.request { ... } : select(time) 直接创建单个请求，并设定超时。

具体见： https://github.com/cloudwu/skynet/blob/select/test/testselect.lua

**Comment by zhangshiqian1214** [comment]
> 给一个可以直接用的
> 
> ```lua
> local skynet = require "skynet"
> 
> ---@class parallels
> local _M = {}
> 
> local _MT = {__index = _M}
> 
> ---@return parallels
> local function new()
>     return setmetatable(
>         {
>             list = {},
>             boot_co = nil,
>             boot_error = nil
>         },
>         _MT
>     )
> end
> 
> local function wakeup_waitco(self, err)
>     if not self.boot_error then
>         self.boot_error = err
>     end
>     local boot_co = self.boot_co
>     if boot_co then
>         self.boot_co = nil
>         skynet.wakeup(boot_co)
>     end
> end
> 
> local function wait_end(self)
>     assert(not self.boot_co, "allready in wait %s", tostring(self.boot_co))
>     self.boot_co = coroutine.running()
>     if not next(self.list) then
>         skynet.yield()
>     else
>         skynet.wait(self.boot_co)
>     end
>     if self.boot_error then
>         error(self.boot_error)
>     end
> end
> 
> ---@param self parallels
> ---@param func fun(...):...
> ---@param ... any
> ---@return void
> function _M.add(self, func, ...)
>     local token = {}
>     local list = self.list
>     list[token] = true
>     skynet.fork(
>         function(...)
>             token.co = coroutine.running()
>             local ok, err = xpcall(func, debug.traceback, ...)
>             if not ok then
>                 wakeup_waitco(self, err)
>             else
>                 list[token] = nil
>                 if not next(list) then
>                     wakeup_waitco(self)
>                 end
>             end
>         end,
>         ...
>     )
> end
> 
> ---@param self parallels
> ---@return void
> function _M.wait(self)
>     return wait_end(self)
> end
> 
> return new
> ```
> 
> 使用
> 
> ```lua
> local pa = require("parallels")()
> local ret1,ret2
> pa:add(function()
>     ret1 = skynet.call(service1, ...)
> end)
> pa:add(function()
>     ret2 = skynet.call(service2, ...)
> end)
> 
> pa:wait()
> 
> print(ret1,ret2)
> ```

在某种情况下,  比如批量调含有http操作的函数里面,  因为不是直接调用skynet.call, 所以skynet.select不适用这种情况, 对parallels进行测试, 发现有时会出现还没有等所有操作完成, 就唤醒了wait
