### ISSUE TITLE
关于skynet并发模型的讨论

### ISSUE THREAD

**Issue by linxiaolong** [cloudwu/skynet#1185]
问题：服务内使用call等阻塞接口引起的状态重入

相关手段：
1）业务服务内限制call等接口，使用send+回调方式。本质上没解决状态重入问题，但由于逻辑上的割裂，会显式驱动使用者：
a）不会把call等接口藏匿于深层次的接口，导致无法感知是否挂起 
b）在回调接口内会显式再次检查必要条件

2）skynet.queue。本质上可保证，但对于使用者而言，在一个服务内如何合理划分不同的queue，不同queue访问到共享部分这类问题会增加很大的心智成本

3）业务服务阻塞call，禁止伪并发。大部分的服务要切得足够细（譬如一个玩家一个服务，一个公会一个服务，一个玩家邮件处理一个服务），细到发生阻塞也没关系；对于小部分基于性能等原因考虑而不能切分太细的服务（譬如地图），这类要限制call的使用（使用者是要明确知道在这类服务使用call等是会阻塞的，是否要使用自己决定）

如上，1）2）方式对于实际项目上而言有意义，代价也显而易见，关键也无法根本解决问题。对于3）这种方式思考有一段时间，首先这样一个模型理论上没问题（就算类似地图这类服务里面也可切出很多服务），但在实际落地显而易见会遇到的问题：
1）内存。尽可能地切细，而实际上一个服务就是一个lua vm
2）效率。切得越细，运行内耗越严重，想象极端情况下一个地图每个怪物都来一个服务

参考erlang和golang，思考了下在skynet现行框架下，以协程而非服务来划分业务单元应该会是更佳的选择，更接近于golang的MPG模型。就譬如一个玩家A对应一个协程G：
1）G依赖于消息来驱动逻辑循环
2）G内只能访问A的沙盒数据，与其他G的交互依赖于消息交互
这样带来一些好处：
1）G不需考虑状态重入伪并发问题，阻塞就阻塞了
2）G的内存占用优于服务
3）G交互效率问题，对跨服务的G走的依然是服务间消息，服务内的G不用走服务间交互，也即对于类似同个地图类多个实体（G）的交互，追求高效可以绑定在同个服务内

就具体项目而言，在毫无历史包袱的新项目，在业务框架层面做上面改造难度不大，但对skynet这个框架本身来说，假设能从底层消息调度 服务抽象等方面来考虑，各个方面应该会做得更深入有效。

初步想法，借帖跟cloud讨论，或者cloud和各位对这块有什么最佳实践，也一起讨论下。

**Comment by cloudwu** [comment]
我比较倾向于功能服务设计成无连续状态的。比较类似于 1) 但不使用 callback 的形式。

例如，A 请求 B 发起一个 "购买“ 行为。不设计成： A call B "购买" ，然后 ...

而是， A 向 B 提交了一个请求；然后 A 收到了一个完整的事务： "A 向 B 购买" 已发生。而后者是一开始就注册好的一种行为，可以一次性处理。框架要解决的是，在 A 向 B 提交请求的时候，就构造出一个状态单元，等收到回应的时候，连同回应内容一起合并成一个完整的状态单元，交给业务去处理。

这不同于 callback 机制，而是服务只去处理确定的状态单元，而不是临时设定一个 callback 去处理上下文。

业务是由独立的不同的状态单元构成的，单元之间是状态无关的。

**Comment by linxiaolong** [comment]
> 我比较倾向于功能服务设计成无连续状态的。比较类似于 1) 但不使用 callback 的形式。
> 
> 例如，A 请求 B 发起一个 "购买“ 行为。不设计成： A call B "购买" ，然后 ...
> 
> 而是， A 向 B 提交了一个请求；然后 A 收到了一个完整的事务： "A 向 B 购买" 已发生。而后者是一开始就注册好的一种行为，可以一次性处理。框架要解决的是，在 A 向 B 提交请求的时候，就构造出一个状态单元，等收到回应的时候，连同回应内容一起合并成一个完整的状态单元，交给业务去处理。
> 
> 这不同于 callback 机制，而是服务只去处理确定的状态单元，而不是临时设定一个 callback 去处理上下文。
> 
> 业务是由独立的不同的状态单元构成的，单元之间是状态无关的。

1）对一部分交互较多的逻辑，使用者会写得比较累，譬如需求“点击NPC判断队伍里面所有人是否符合XX条件然后就执行什么”，使用者会在各个注册行为内进行各种回应收集等等。整体来说编写上不舒服了些
2）状态合并。也即一个服务可以有多个状态单元的，且无法重入，这个可以对应到一个实际实现就可以是一个协程。譬如一个服务内有多个玩家协程（玩家状态单元）

**Comment by hanxi** [comment]
@cloudwu 能否给个具体的demo来描述下
> A 请求 B 发起一个 "购买“ 行为

我写了两个例子，感觉都不对，觉得都是你说的
>A call B "购买" ，然后 ...

```lua
-- 先减少库存，再扣钱，最后发货
-- service A
function req_buy(uid, itemid, cnt)
    -- 检查钱是否足够
    local price = get_price(itemid, cnt)
    local have_gold = get_my_gold(uid)
    if have_gold < price then
        return false, "gold shortage"
    end
    local ret,msg = skynet.call("B", "buy", uid, itemid, cnt)
    if not ret then
        return ret, msg
    end

    -- 扣钱
    local ok = sub_gold(uid, price)
    if not ok then
        -- 钱又不够了怎么办？？？
    end

    -- 发货
    add_item(uid, itemid, cnt)
end

-- service B
function CMD.buy(uid, itemid, cnt)
    -- 检查物品数量是否足够
    if check_item_cnt(itemid, cnt) then
        return false, "item not enough"
    end
    -- 卖出物品
    sub_item(itemid, cnt)
    return true
end
```

```lua

-- 先扣钱，再减少库存，最后发货
-- service A
function req_buy(uid, itemid, cnt)
    -- 检查钱是否足够
    local price = get_price(itemid, cnt)
    local have_gold = get_my_gold(uid)
    if have_gold < price then
        return false, "gold shortage"
    end

    -- 扣钱
    local ok = sub_gold(uid, price)
    if not ok then
        return false, "gold not enough"
    end

    local ret,msg = skynet.call("B", "buy", uid, itemid, cnt)
    if not ret then
        -- 出货失败？还钱？？？
        return ret, msg
    end

    -- 发货
    add_item(uid, itemid, cnt)
end

-- service B
function CMD.buy(uid, itemid, cnt)
    -- 检查物品数量是否足够
    if check_item_cnt(itemid, cnt) then
        return false, "item not enough"
    end
    -- 卖出物品
    sub_item(itemid, cnt)
    return true
end
```

**Comment by hanxi** [comment]
@cloudwu 能否给个具体的demo来描述下
> A 请求 B 发起一个 "购买“ 行为

我写了两个例子，感觉都不对，觉得都是你说的
>A call B "购买" ，然后 ...

```lua
-- 先减少库存，再扣钱，最后发货
-- service A
function req_buy(uid, itemid, cnt)
    -- 检查钱是否足够
    local price = get_price(itemid, cnt)
    local have_gold = get_my_gold(uid)
    if have_gold < price then
        return false, "gold shortage"
    end
    local ret,msg = skynet.call("B", "buy", uid, itemid, cnt)
    if not ret then
        return ret, msg
    end

    -- 扣钱
    local ok = sub_gold(uid, price)
    if not ok then
        -- 钱又不够了怎么办？？？
    end

    -- 发货
    add_item(uid, itemid, cnt)
end

-- service B
function CMD.buy(uid, itemid, cnt)
    -- 检查物品数量是否足够
    if check_item_cnt(itemid, cnt) then
        return false, "item not enough"
    end
    -- 卖出物品
    sub_item(itemid, cnt)
    return true
end
```

```lua

-- 先扣钱，再减少库存，最后发货
-- service A
function req_buy(uid, itemid, cnt)
    -- 检查钱是否足够
    local price = get_price(itemid, cnt)
    local have_gold = get_my_gold(uid)
    if have_gold < price then
        return false, "gold shortage"
    end

    -- 扣钱
    local ok = sub_gold(uid, price)
    if not ok then
        return false, "gold not enough"
    end

    local ret,msg = skynet.call("B", "buy", uid, itemid, cnt)
    if not ret then
        -- 出货失败？还钱？？？
        return ret, msg
    end

    -- 发货
    add_item(uid, itemid, cnt)
end

-- service B
function CMD.buy(uid, itemid, cnt)
    -- 检查物品数量是否足够
    if check_item_cnt(itemid, cnt) then
        return false, "item not enough"
    end
    -- 卖出物品
    sub_item(itemid, cnt)
    return true
end
```

**Comment by snowolder** [comment]
（1）扣钱 （2）请求扣除库存发货 如果库存不够应该会有个返回结果把钱加回去?

**Comment by cloudwu** [comment]
我认为 **交易** 是一个需要谨慎处理的行为，不应该太直观的用一次 call 就完成。

如果我来设计，我会设计一个 **交易服务** ，负责所有的交易行为。每条交易有唯一的交易 session 共买卖双方查询和更新交易状态。

卖方先把交易品和报价等相关信息提交给 **交易服务** ，然后通知买方去购买，并可以随时查询交易是否完成，然后选择取回未成功的交易品，或拿到货款。

买方则把对等交易品也提交给 **交易服务** 促成交易。

即：在 **交易服务** 上创建一个交易 session ，并由买卖双方更新交易的状态，然后交易对手都可以在交易完成（或失败）后从 **交易服务** 获取回最后属于他们的东西。

任何一方向 **交易服务** 提交前，都应该自己先冻结提交的物品，贴上相关交易 session 号的封条，然后再提交。如果事后查询相关 session 发现有故障可以解冻，或是根据成功状态删掉冻结品，并拿回最终结果。

**Comment by BanKnight** [comment]
并发模型这个问题非常好，但交易这类功能毕竟有他的特殊性，我觉得单开一个主题去讨论比较好。

我现在做法是类似于3，重点是简单，但实践下来有几个个问题。

1 吞吐量下降
2 服务划分粒度
3 死锁

这里单独对死锁做下解释，在一个长的调用链后，有可能出现环，由于伪并发被禁止，那么就会阻塞在环成型的地方。

以上几个问题感觉都没有完美解，@linxiaolong 提到的用协程来解决，在我看来本质还是一样，并没有实质性解决。

**Comment by linxiaolong** [comment]
> 并发模型这个问题非常好，但交易这类功能毕竟有他的特殊性，我觉得单开一个主题去讨论比较好。
> 
> 我现在做法是类似于3，重点是简单，但实践下来有几个个问题。
> 
> 1 吞吐量下降
> 2 服务划分粒度
> 3 死锁
> 
> 这里单独对死锁做下解释，在一个长的调用链后，有可能出现环，由于伪并发被禁止，那么就会阻塞在环成型的地方。
> 
> 以上几个问题感觉都没有完美解，@linxiaolong 提到的用协程来解决，在我看来本质还是一样，并没有实质性解决。

本质来说我的方案就是第3种，之所以提出以“协程”来替代“服务”作为最基础的业务单元，是因为“协程”更为轻量级（如果lua vm足够轻量也没问题，而事实上不是）。举个例子，一般开发者开发“公会功能”，会很直接地做一个“公会服务”。这时候如果你允许伪并发（并发call）那就面临着各种状态重入问题；而如果不允许伪并发那就面临着处理效率下降（明明A公会和B公会的事情可以各自处理，现在却需要串行）。
禁止伪并发的前提下，要解决处理效率低下的关键在于业务粒度的切分，也即像“公会功能”，那我们的设计可以是每个公会维护自己的协程（这样的协程是可以跨服务不需要放在同个服务），而若需公会管理那么就维护一个公会管理协程。也就一个协程对应一个业务单元，一个业务单元内是禁止伪并发的，业务单元与业务单元之间也可直接通讯（服务内的其实只是一个协程唤醒，跨服务的则需走服务通讯再协程唤醒）
以上都很轻便可以在现有skynet上层去构建一个“业务单元”的通讯层即可，对于业务开发者来说其实心智负担会低很多。
而同时我认为，更为彻底的做法，其实不需服务概念，参考golang MPG模型来说，业务开发者最为关心的就是自己的G（业务单元协程）能舒服地“阻塞式”写法，P（等价于目前的lua vm）其实是两两等价的载体而无任何业务概念。当然，这样处理是彻底干净了，但本身跟skynet本身类erlang的设计来说破坏了很多基础设施的建设，所以只供讨论

**Comment by linxiaolong** [comment]
> 并发模型这个问题非常好，但交易这类功能毕竟有他的特殊性，我觉得单开一个主题去讨论比较好。
> 
> 我现在做法是类似于3，重点是简单，但实践下来有几个个问题。
> 
> 1 吞吐量下降
> 2 服务划分粒度
> 3 死锁
> 
> 这里单独对死锁做下解释，在一个长的调用链后，有可能出现环，由于伪并发被禁止，那么就会阻塞在环成型的地方。
> 
> 以上几个问题感觉都没有完美解，@linxiaolong 提到的用协程来解决，在我看来本质还是一样，并没有实质性解决。

另外提到的死锁问题，依赖于完善的链路追踪设施建设，成环很容易识别，但判断成环之后如何处理那就是见仁见智。实际项目建设的时候，其实个人偏向是能send则send，对于call成环这种会直接打断报警
