### ISSUE TITLE
 win10子系统Ubuntu10.04出现maybe in an endless loop (version = 69503)死循环

### ISSUE THREAD

**Issue by lgbgoingdown** [cloudwu/skynet#1195]
win10子系统内核版本：Linux  4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
出现死循环输出：
[:00000000] A message from [ :00000000 ] to [ :01000001 ] maybe in an endless loop (version = 69505)
[:00000000] A message from [ :00000000 ] to [ :01000001 ] maybe in an endless loop (version = 69505)
[:00000000] A message from [ :00000000 ] to [ :01000001 ] maybe in an endless loop (version = 69505)
[:00000000] A message from [ :00000000 ] to [ :01000001 ] maybe in an endless loop (version = 69505)

**Comment by cloudwu** [comment]
暂不支持 windows , 出现问题可以自己查。如果能修好，欢迎提 pr 。

信息是说 :01000001 这个服务出现了死循环，一直没有返回。通常第一个服务是 log 服务。

**Comment by cloudwu** [comment]
不过奇怪的是：如果 :01000001 是 log 服务，且阻塞，那么理论上你也无法看见 log 信息才对。所以你需要核查 :01000001 到底是什么。

**Comment by lgbgoingdown** [comment]
使用win10的debian子系统测试成功了，可能Ubuntu子系统哪里有问题

**Comment by fanlix** [comment]
wsl用的是MS重写的定制版kernel, 
很多底层系统调用都没实现, 
虽然很轻量,但是各种兼容一言难尽. 
tail -f, gdb, docker这些时不时就会掉坑里.
坑太大, MS自己已经放弃了.

建议只在wsl下开发然后去linux下测试.
或换wsl2

**Comment by fawdlstty** [comment]
提议，打开这个issue，在有pr时再关闭

**Comment by etnlGD** [comment]
WSL1 + Ubuntu 20.04碰到同样的问题，研究了下是libc的sleep有问题，另外一个表现是在控制台运行 `sleep 1s` 会报错 "Error- sleep: cannot read realtime clock: Invalid argument"。这里有个解决办法 https://www.how2shout.com/how-to/how-to-upgrade-ubuntu-18-04-lts-to-20-04-lts-on-wsl-windows-10.html
