### ISSUE TITLE
skynet 监控的一些指标

### ISSUE THREAD

**Issue by cloudfreexiao** [cloudwu/skynet#1196]
打算用 prometheus 做个 监控 skynet 的功能 
目前 我改了个 插件
 https://github.com/cloudfreexiao/skynet-prometheus/tree/master/skynet/service
但是 有点烦恼的地方就是 想拿 skynet 内部的一些数据 导出 但是又不知道 有哪些数据可用
请问 有相关经验的解惑下嘛

**Comment by hanxi** [comment]
每个服务占用的内存（cmem/mem指令），客户端连接数量，协程数量这些吧。

**Comment by sniper00** [comment]
message queue len, service cpu

**Comment by cloudfreexiao** [comment]
我大概知道 怎么搞了
