### ISSUE TITLE
关于 sproto:default  获取缺省表

### ISSUE THREAD

**Issue by lsx1994** [cloudwu/skynet#1199]
我通过sprotoloader加载的协议文件，正确获取缺省的姿势应该是什么样呢？

sprotoloader.load(1):default(typename)  这样会报错哦。

**Comment by cloudfreexiao** [comment]
sproto:default(typename, type) Create a table with default values of typename. Type can be nil , "REQUEST", or "RESPONSE".
https://github.com/cloudwu/sproto

**Comment by lsx1994** [comment]
> sproto:default(typename, type) Create a table with default values of typename. Type can be nil , "REQUEST", or "RESPONSE".
> 
> https://github.com/cloudwu/sproto/blob/master/testrpc.lua#L46-L48

thank
