### ISSUE TITLE
关于clusterd服务的疑惑

### ISSUE THREAD

**Issue by Fanrncho** [cloudwu/skynet#1200]
`function command.socket(source, subcmd, fd, msg)
	if subcmd == "open" then
		skynet.error(string.format("socket accept from %s", msg))
		-- new cluster agent
		cluster_agent[fd] = false
		local agent = skynet.newservice("clusteragent", skynet.self(), source, fd)
		local closed = cluster_agent[fd]
		cluster_agent[fd] = agent
		if closed then
			skynet.send(agent, "lua", "exit")
			cluster_agent[fd] = nil
		end
	else
		if subcmd == "close" or subcmd == "error" then
			-- close cluster agent
			local agent = cluster_agent[fd]
			if type(agent) == "boolean" then
				cluster_agent[fd] = true
			elseif agent then
				skynet.send(agent, "lua", "exit")
				cluster_agent[fd] = nil
			end
		else
			skynet.error(string.format("socket %s %d %s", subcmd, fd, msg or ""))
		end
	end
end`
以上代码截取自“skynet/service/clusterd.lua”文件。
---------------------------------------------------------
假设有A、B两个节点建立的Cluster集群关系，A节点首次通过cluster.call方法调用B节点，需要先建立tcp连接，所以被查询的B节点的“clusterd”服务里创建的“gate”服务内的socketdriver会触发open方法，表示接收到一条新连接，最终会触发调用"clusterd.lua"文件的“command.socket”方法（也就是上面的截取的代码片段），且subcmd参数为“open”，“clusterd”服务会为该连接套接字创建一个"clusteragent"专员服务来处理该连接上的消息（"clusteragent"服务创建后，“gate”上接收的所有关于这个新连接的消息都会重定向给这个"clusteragent"服务处理）。
“clusteragent”服务的创建是一个比较耗时的操作，假设在这个服务创建完成前，这个新连接的套接字上接收到了对端发来的消息，soket线程把接收的消息压入了“clusterd”服务内创建的“gate”服务的消息队列内，且“gate”服务也刚好被某个工作线程取到了这个新消息进行处理，通过源码可以看到，因为“clusteragent”服务还没有创建好，所以直接发送给"clusterd"服务处理，而"clusterd"服务则交给“command.socket”方法（也就是上面的截取的代码片段）处理，这时参数“subcmd”值为"data"，所以只会执行一行错误输出代码（skynet.error(string.format("socket %s %d %s", subcmd, fd, msg or ""))）。
假设A节点调用B节点时用的是cluster.call方法，刚好遇上了上面提到的这种情况，那么就会出现这样一种情况：
B节点的日志文件里会输出一行“socket data 某某套接字 某某消息内容”。因为cluster.call是阻塞操作，所以A节点则一直卡在那儿(B节点不会给这个“查询操作”任何反馈了)。
如果上述情况真的存在，那么这是个很严重的问题，试想：假设这个cluster.call操作是在某个agent服务里执行，且agent服务里的消息处理都放到了skynet.queue队列里执行，那么出现这种情况时就会导致这个agent服务完全不可用了。
云风前辈，我不太确定是不是我漏看了什么，还请您提点提点。 @cloudwu

**Comment by cloudwu** [comment]
我认为你应该先写个测试代码，把你描述的可能显现出来。

**Comment by Fanrncho** [comment]
```
195. function command.socket(source, subcmd, fd, msg)
196. 	if subcmd == "open" then
197. 		skynet.error(string.format("socket accept from %s", msg))
198. 		-- new cluster agent
199. 		cluster_agent[fd] = false
200. 		local agent = skynet.newservice("clusteragent", skynet.self(), source, fd)
201. 		local closed = cluster_agent[fd]
202. 		cluster_agent[fd] = agent
203. 		if closed then
204. 			skynet.send(agent, "lua", "exit")
205. 			cluster_agent[fd] = nil
206. 		end
207. 	else
208. 		if subcmd == "close" or subcmd == "error" then
209. 			-- close cluster agent
210. 			local agent = cluster_agent[fd]
211. 			if type(agent) == "boolean" then
212. 				cluster_agent[fd] = true
213. 			elseif agent then
214. 				skynet.send(agent, "lua", "exit")
215. 				cluster_agent[fd] = nil
216. 			end
217. 		else
218. 			skynet.error(string.format("socket %s %d %s", subcmd, fd, msg or ""))
219. 		end
220. 	end
221. end
```
* 以上代码截取自`skynet/service/clusterd.lua`文件的`195-221`行
--------------------------------------------------
#### 我重新编排一下问题吧：
 * 什么时候程序会执行`skynet/service/clusterd.lua`文件的第`218`行代码？
   * 假设有`A`、`B`两个节点，`A`节点通过`cluster.call/send`方法首次与`B`节点交互时，`B`节点会触发集群服务（`clusterd`）的第`200`行代码（`skynet/service/clusterd.lua`文件），也就是创建`clusteragent`服务，而创建服务是一个比较耗时的操作，所以coroutine会在这一行阻塞挂起，假设要`10`秒时间这个`clusteragent`服务才能创建完成，而在这`10`秒内所有从`A`节点发来的`cluster.call/send`消息都会触发执行`B`节点的`clusterd`服务的第`218`行代码（`skynet/service/clusterd.lua`文件）。

 * 程序执行`skynet/service/clusterd.lua`文件的第`218`行代码会有什么问题？
   * 如果`A`节点是通过`cluster.call`方法查询`B`节点的，必然是想要`B`节点给它一个回复的，但如果这条消息是`B`节点的`clusterd`服务的第`218`行代码（`skynet/service/clusterd.lua`文件）处理了，那么`A`节点的这次`cluster.call`调用则会一直处于阻塞挂起状态，得不到`B`节点的回复，因为外部节点通过`cluster.call/send`访问`B`节点时，只有`B`节点内处理相应外部socket连接的`clusteragent`服务创建完成后才能得到正确的处理。
 
##### 综上所述，如果问题成立，那么比较合理的解决方法我认为是：
* 把第`218`行代码的处理逻辑改成使用队列来缓存在`clusteragent`服务尚未创建完成期间收到的相关socket连接上的消息，待`clusteragent`服务创建完成后，再把队列里缓存的消息重定向给`clusteragent`服务处理。
------------------------------------------------------
##### 还请云风前辈花点时间思考下这个问题。

**Comment by cloudwu** [comment]
我还是认为，既然你觉得自己已经分析透彻，那么不妨构造一个案例触发出问题。然后再就问题讨论。

例如你觉得 `clusteragent` 构造的过程中有并发问题，那么可以在 `clusteragent` 的初始化过程故意延长处理时间，增加出问题的几率。

如果无法暴露出问题，那么再研究自己哪里搞错了。

**Comment by Fanrncho** [comment]
好吧，我先弄个测试用例先验证一下。 @cloudwu

**Comment by Fanrncho** [comment]
用测试用例验证了，是我这边漏看了一部分逻辑，在`clusteragent`服务尚未创建完成前，没有执行`socketdriver.start`，所以不会收到这个 socket 上的数据。叨扰前辈了，我下次注意，先用测试用例验证 @cloudwu
