### ISSUE TITLE
是否有必要增加个 websocket 的 gate 

### ISSUE THREAD

**Issue by cloudfreexiao** [cloudwu/skynet#1201]
实现了个 基于 ws 的 gate 库 它的 接口 与 现有的 gateserver 一致 方便 处理不同协议
https://github.com/cloudfreexiao/skynet/blob/master/lualib/snax/wsserver.lua

**Comment by cloudwu** [comment]
我不太想进一步增加维护负担。应该考虑在 wiki 上单独开辟一个位置方便索引。

**Comment by cloudfreexiao** [comment]
好的
