### ISSUE TITLE
skynet系统跑久了产生的日志时间问题

### ISSUE THREAD

**Issue by moonwith** [cloudwu/skynet#1202]
skynet的日志时间用单调时间来计时，但是系统跑久了，单调时间和实际的wall time有几秒的差别，这个问题怎么处理呢。
uint32_t starttime = skynet_starttime();
uint64_t currenttime = skynet_now();

**Comment by cloudwu** [comment]
skynet 用的 `CLOCK_MONOTONIC` 是会被 ntpd 调整的。你只需要开启 ntpd 校对时钟即可。

**Comment by moonwith** [comment]
@cloudwu 感谢风云大哥的回答，您的意思是开启ntpd会修正CLOCK_MONOTONIC和wall time的误差么，那我试试。

**Comment by cloudwu** [comment]
See https://stackoverflow.com/questions/14270300/what-is-the-difference-between-clock-monotonic-clock-monotonic-raw

**Comment by moonwith** [comment]
顺便再请教下，我们在windows上用单调时钟，跑久了也有同样的问题。不知道是否也可以用ntpd修正呢。
steady_clock::now() // qpt
GetTickCount64
timeGetTime

**Comment by moonwith** [comment]
@cloudwu

**Comment by cloudwu** [comment]
我比较少专门为 windows 开发，根据我对 msdn 描述的理解，可能不会。这点需要实际测试确认。

但是 Windows 似乎有 `GetSystemTimeAdjustment` 这样一个函数，可以获取其它时间源的偏移修正。可以周期性的利用其结果来修正到 wall time。

**Comment by moonwith** [comment]
好的，感谢云风大哥耐心解释。因为我们有windows server 上跑的服务器也面临同样的问题，
用的是steady_clock::now() // qpc，跑久了也产生跟wall time的误差。
