### ISSUE TITLE
对发生错误时对 发起者的追踪

### ISSUE THREAD

**Issue by cloudfreexiao** [cloudwu/skynet#1203]
目前 skynet 发生 call 失败时 案发服务有 挂起 但是这些信息不足以知道 发起服务的相关 信息(可能这次发生错误是由于跨多个服务的链式操作)
请问有什么办法能够比较好的定位 这类问题嘛

**Comment by cloudwu** [comment]
skynet.trace() 可以提供调用路径的 log

https://blog.codingnow.com/2018/05/skynet_trace.html

**Comment by cloudfreexiao** [comment]
看了下 应该是我需要的 谢谢~~
