### ISSUE TITLE
sharetable热更报错：invalid key to 'next'。

### ISSUE THREAD

**Issue by yxhtx** [cloudwu/skynet#1204]
应该是match_table在遍历t时把某个值置nil了。
所以我写了下面这段代码测试：
local t = {a = 1};
for k, v in pairs(t) do
	t[k] = nil
	t.b = 1
end
在Lua5.1环境下没重现这个报错，在Lua5.3环境下必现。
我的想法是在rawset(t, k, nv)前判断nv是否为nil，如果是nil则在遍历完t后再置nil，这样是否可行？

**Comment by lvzixun** [comment]
`The behavior of next is undefined if, during the traversal, you assign any value to a non-existent field in the table. You may however modify existing fields. In particular, you may clear existing fields.
`
https://www.lua.org/manual/5.3/manual.html#pdf-next  能否截取下你sharetable update时报错的调用栈？

**Comment by yxhtx** [comment]
/lualib/skynet.lua:237: invalid key to 'next'
stack traceback:
	[C]: in function 'next'
	./lualib/skynet/sharetable.lua:475: in local 'f'
	./lualib/skynet/sharetable.lua:437: in upvalue 'match_value'
	./lualib/skynet/sharetable.lua:529: in upvalue 'match_funcinfo'
	./lualib/skynet/sharetable.lua:556: in local 'f'
	./lualib/skynet/sharetable.lua:437: in upvalue 'match_value'
	./lualib/skynet/sharetable.lua:529: in upvalue 'match_funcinfo'
	./lualib/skynet/sharetable.lua:556: in local 'f'
	./lualib/skynet/sharetable.lua:437: in upvalue 'match_value'
	./lualib/skynet/sharetable.lua:529: in upvalue 'match_funcinfo'
	...
	./lualib/skynet/sharetable.lua:437: in upvalue 'match_value'
	./lualib/skynet/sharetable.lua:529: in upvalue 'match_funcinfo'
	./lualib/skynet/sharetable.lua:593: in local 'f'
	./lualib/skynet/sharetable.lua:437: in upvalue 'match_value'
	./lualib/skynet/sharetable.lua:566: in local 'f'
	./lualib/skynet/sharetable.lua:437: in upvalue 'match_value'
	./lualib/skynet/sharetable.lua:487: in local 'match_table'
	./lualib/skynet/sharetable.lua:607: in upvalue 'resolve_replace'

**Comment by yxhtx** [comment]
有些修改导致行号可能对不上

**Comment by lvzixun** [comment]
你那边改了sharetable的update？

**Comment by lvzixun** [comment]
能否提供个现在master分支上面报错的测试用例出来？

**Comment by yxhtx** [comment]
没有改update。配置热更报这个错也是很久了才出现了这一次，当时更新的配置也比较难知道改了些什么了。

**Comment by cloudwu** [comment]
有没有可能遍历的这个 t 恰好是 match_value 自身会改变的 table, 例如  record_map 。

做全局替换的时候需要排除一些本身工作用的对象。

**Comment by lvzixun** [comment]
> 有没有可能遍历的这个 t 恰好是 match_value 自身会改变的 table, 例如 record_map 。
> 
> 做全局替换的时候需要排除一些本身工作用的对象。

https://github.com/cloudwu/skynet/blob/master/lualib/skynet/sharetable.lua#L402-L429

这段应该是把`sharetable.update`之后的调用栈都给过滤掉了。按理来说不会标记到`record_map`的。

**Comment by yxhtx** [comment]
没有改动过next。

**Comment by lvzixun** [comment]
@yxhtx  你可以更新下这个PR： https://github.com/cloudwu/skynet/pull/1208 （已合并了）。 看看还会不会出现你遇到的这个问题。

**Comment by yxhtx** [comment]
好的

**Comment by Stevelhf** [comment]
next的报错是因为 遍历的时候采用了luaH_next 每次循环遍历的时候会把当前 k入栈 然后再下次循环的时候取出k对应的位置 然后查找它的下一个k 如果比如你的例子中  t = {a = 1}; 此时hash表的大小是1 你在循环的时候把a置位nil了 又把生成了一个newkey b = 1此时 b会取代a的位置 但是a已经入栈了 下次循环开始的时候 通过findindex  a找不到在hash表中的位置 所以报错了 invalid key to 'next'
