### ISSUE TITLE
skynet时间跟实际时间有误差的问题

### ISSUE THREAD

**Issue by mippo520** [cloudwu/skynet#1207]
看了下之前的讨论,说是ntp对时就没有误差.但是我阅读了一下代码有这样的疑惑,似乎在skynet_updatetime函数里只要代码走了 cp < TI->current_point 这个分支,只是把current_point设置成了当前的time了,但是这一帧进来在实际时间里会有一个跟上一帧的时间差diff似乎就丢失了.那么随着进入 cp < TI->current_point 这个分支的次数越多,那么丢失的diff就越多,所以 TI->current 跟实际时间的误差就越大,这个跟ntp对时没有关系的..

**Comment by cloudwu** [comment]
`CLOCK_MONOTONIC` 顾名思义，其获取的值是单调递增的，即使被 ntpd 校对，依然会保留这个约束。

如果实际依然发现问题，或代码有 bug ，需要有测试案例和重现步骤佐证。

**Comment by mippo520** [comment]
![B7C6752F-00D8-46EA-B0EE-1B9964233949](https://user-images.githubusercontent.com/7939375/85123014-1063d400-b25a-11ea-8b05-ffd6b930055e.png)
我在这下面加了一个log打印现实时间和skynet时间的时间差.
一开始的时候时间差为0,随着cp < TI->current_point这个分支的代码执行,时间差会逐渐积累.
![876F128F-44CC-4AD9-BF46-472D1258BF18](https://user-images.githubusercontent.com/7939375/85123161-54ef6f80-b25a-11ea-85a4-7499929216b2.png)
![0CD62CBF-CA4F-4357-8142-862B040F5A8F](https://user-images.githubusercontent.com/7939375/85123178-5faa0480-b25a-11ea-9045-9822397f675d.png)

**Comment by mippo520** [comment]
@cloudwu

**Comment by cloudwu** [comment]
如果时钟是单调的，为什么会进入这个分支？

因为 `T->current_point` 取的是上次的值，那么下一次 cp 一定是 >= `TI->current_point` 的。写上这个分支是因为有些平台并没有使用单调时钟。那么，如果出现这条信息后，应该把这些平台的实现调整对。

**Comment by mippo520** [comment]
是的,我也觉得会进入上面这个分支很奇怪,我的想法是能不能在进入上面分支之后计算一下diff = 现实时间 - skynet时间..把这个漏掉的diff补上...这样无论走哪个分支都不会有问题
@cloudwu
