### ISSUE TITLE
关于skynet_error的msg复制的疑问

### ISSUE THREAD

**Issue by zhoujiazhi222** [cloudwu/skynet#1213]
复制msg时，为什么要以分配256，512，1024长度的数组来找到可以容纳msg的数组长度，为什么不使用**两次遍历**的做法(第一次遍历获取到msg的长度，在分配长度+1的数组，在copy数据）
1.当msg长度大于256时速度比**两次遍历**慢
2.当msg长度小于256时经过vsnprintf和skynet_strdup两次遍历，速度和**两次遍历**差不多

**Comment by cloudwu** [comment]
1. 随手写的，不是什么重要的地方。
2. 没有什么简单的获取长度的方法。

**Comment by hanxi** [comment]
一次遍历取不到 msg 的长度的，无法确定 vsnprintf 返回的长度。现在这种写法还是比较简单易懂的。

**Comment by zhoujiazhi222** [comment]
@hanxi 
while循环直到搜到**\0**字符，不就拿到长度了？
你看看strlen函数

**Comment by hanxi** [comment]
@zhoujiazhi222 你再仔细看看这几行吧，取到 msg 长度没啥用的，要取 format 后的长度才行。

https://github.com/cloudwu/skynet/blob/master/skynet-src/skynet_error.c#L39-L43

**Comment by zhoujiazhi222** [comment]
@hanxi 
那这个做法还真是简单易懂啊，不过就算有format，一次遍历也能获取到长度吧
长度=len(msg) - sum(len(控制符)) + sum(len(参数))，写起来貌似比较复杂？

**Comment by hanxi** [comment]
show your code 😄 ?  实现起来不会简单，相当于实现一个类似 vsnprintf 的函数用来取长度。
