### ISSUE TITLE
【建议】加入vcpkg的编译支持

### ISSUE THREAD

**Issue by fawdlstty** [cloudwu/skynet#1216]
<https://github.com/microsoft/vcpkg/blob/master/README_zh_CN.md>
vcpkg是一个跨平台工具，可以以非常简单的方式实现跨平台编译实现，并且不需要项目对CMake的支持。比如可以通过mingw工具链实现自动在windows上编译ffmpeg。

**Comment by cloudwu** [comment]
skynet 现在并不支持 windows.
