### ISSUE TITLE
关于skynet.call的一些疑问

### ISSUE THREAD

**Issue by fisher-an** [cloudwu/skynet#1220]
请问各位大神，如何安全使用call,  skynet.call是否会导致协程泄漏
比如:
A call B
skynet.send(B，“lua”, "close")
skynet.call(B, "lua", "test_call")
B 在处理 close 消息后，调用 skynet.exit退出了。
测试发现 test_call没有收到返回

**Comment by wjlovefql** [comment]
我这边测试了一下，skynet.call是可以返回异常的。我看了一下内部相关的源代码，处理这些逻辑的地方主要分为两个地方：
1. 上层的lua虚拟机，主要是针对于已经处理过的消息
`-- report the sources that call me
	for co, session in pairs(session_coroutine_id) do
		local address = session_coroutine_address[co]
		if session~=0 and address then
			c.send(address, skynet.PTYPE_ERROR, session, "")
		end
	end
	for resp in pairs(unresponse) do
		resp(false)
	end
	-- report the sources I call but haven't return
	local tmp = {}
	for session, address in pairs(watching_session) do
		tmp[address] = true
	end
	for address in pairs(tmp) do
		c.send(address, skynet.PTYPE_ERROR, 0, "")
	end`
     可以看到，对于虚拟机内部保存的各种消息都进行了善后处理，包括 skynet.fork创建的，调用我的，我调用其他服务的
2. c层的代码，主要是针对于还没有处理的消息，也就是在发生skynet.exit调用的时候，还在服务的消息队列里面的消息。
  `static void
drop_message(struct skynet_message *msg, void *ud) {
	struct drop_t *d = ud;
	skynet_free(msg->data);
	uint32_t source = d->handle;
	assert(source);
	// report error to the message source
	skynet_send(NULL, source, msg->source, PTYPE_ERROR, 0, NULL, 0);
}`最终会调用这个函数来处理剩下的消息。
从上面你的描述来看,大概率是以下可能：
a skynet.send(B，“lua”, "close") 往B服务的消息队列里面加入lua类型的,内容为 close的消息
b skynet.call(B, "lua", "test_call") 紧接往B服务的消息队列里面加入lua类型的，内容为test_call的消息
B服务在处理close消息的时候调用skynet.exit，这个时候test_call还在消息队里中，所以会触发上面c层次的代码来释放消息并给来源发送错误类型消息，从而在调用处抛出异常。
上面的分析都是以最新的版本为准。

**Comment by fisher-an** [comment]
感谢解惑，由于我的代码中send/call的都是B的名字(skynet.register的localname ".B")所以收不到异常消息。改成B服务的id就可以了。但在drop_message函数中加了日志打印source， 发现两种方式都能在B服务退出后正常打印出A服务ID。

**Comment by wjlovefql** [comment]
我后续再次看了一下最新版本的代码，以及服务对于 PTYPE_ERROR类型消息的处理，大概确定是框架的问题，主要出现在一下地方：
1. 服务默认的错误消息处理函数包含以下片段：
   ``` lua
      for session, srv in pairs(watching_session) do
	    if srv == error_source then
		  tinsert(error_queue, session)
	    end
       end
   ```
    其中的 error_source 在底层是整数表示的
2. 在调用skynet.call的时候，会把相关的信息记录到 watching_session,包含一下代码(我删除了无关的代码)：
   ``` lua
       local function yield_call(service, session)
	     watching_session[session] = service
	     session_id_coroutine[session] = running_thread
	     local succ, msg, sz = coroutine_yield "SUSPEND"
	     watching_session[session] = nil
	     if not succ then
		     error "call failed"
	     end
	     return msg,sz
       end
      function skynet.call(addr, typename, ...)
	   local p = proto[typename]
	   local session = c.send(addr, p.id , nil , p.pack(...))
	   if session == nil then
		   error("call to invalid address " .. skynet.address(addr))
	    end
	   return p.unpack(yield_call(addr, session))
      end
   ```
   从上面的代码可以看到，在yield_call函数中，把传递过去的addr,session在watching_session中建立映射关系，而在我们通过skynet.call进行调用，addr传递的是服务注册的名字的时候，这个service就是一个表示名字的字符串类型。

综上所述：
   1.  当通过skynet.call(".B",...)进行调用的时候，watching_session中记录消息session对应的service是".B",是一个String.
   2.  当服务B退出的时候，给所有的调用自己的服务推送错误消息，但是在错误处理回调中，传递的error_service是整数，是服务的handle.
   3.  所有在进行遍历watching_session的时候，就会匹配不到，从而无法正确唤醒阻塞的协程，所以没有办法抛出异常。

**Comment by fisher-an** [comment]
非常感谢

**Comment by cloudwu** [comment]
我认为：

1.  命名的服务主动退出不合理。因为 skynet 并没有提供新启动一个服务重新命名的机制。
2.  加上更多的检查没什么坏处，所以我增加了 skynet.localname 转换地址的判断。

**Comment by cloudwu** [comment]
我重新考虑了下，回滚了这个检查代码。因为如果服务退出，目前 skynet 的行为是注销关联的名字。这样 skynet.localname 就查不到了。这个检查不会生效也是多余的。

如果要正确处理这种情况，只能在 call 的时候多做检查，当时把 name -> addr 的对应关系记录下来。我认为没有必要增加这个额外的负担。理由上面写了：将具名服务退出，我认为本身就是不合理的。

**Comment by fisher-an** [comment]
感谢云大大的建议，刚从elixir转入skynet，一些习惯还没改过来。确实没有具名服务提前退出的需求，就算有毕竟call是低频操作，上层封装一下，根据addr类型转换一下就可以了。

**Comment by cloudwu** [comment]
我比较倾向于额外做一个服务管理名字。类似 dns 服务那样，仅用 skynet 的地址。skynet 在 C 层面提供字符串名字是一个历史遗留。

如果不希望查询名字的过程产生一次 rpc 调用，那么也可以考虑用一个线程安全的 C 库，提供名字转换。

即使保留现在的机制，也可以考虑用 skynet.localname 先查一次地址，并缓存在本地。这个 skynet.localname 也可以日后换成其它外部机制。

**Comment by sniper00** [comment]
具名服务退出，应该直接终止进程

**Comment by fisher-an** [comment]
skynet新手，没什么经验。目前的做法是，只有公共服务注册了名字，这类服务都是关服才会退出，也就不存在以上的问题了；对于玩家服务，用C维护了一个map<uid, service>，方便其他服务给玩家发消息，不知道合不合理。

**Comment by sniper00** [comment]
> skynet新手，没什么经验。目前的做法是，只有公共服务注册了名字，这类服务都是关服才会退出，也就不存在以上的问题了；对于玩家服务，用C维护了一个map<uid, service>，方便其他服务给玩家发消息，不知道合不合理。

你应该在负责创建玩家的服务里面做映射，没必要用C写，lua table就行

**Comment by cloudfreexiao** [comment]
skynet 自带的 datacenter 可以做 服务  地址<->名字 的管理
