### ISSUE TITLE
skynet程序崩溃

### ISSUE THREAD

**Issue by kuro-karasu** [cloudwu/skynet#1222]
我们公司用的skynet版本是v1.0.0-alpha7 (2015-6-8)
源码一直没改过，然后最近遇到一个问题，skynet进程突然崩溃，查看core文件内容如下：
gdb /home/project/server/skynet core_skynet_7155_1595702675

GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from skynet...done.
[New LWP 7166]
[New LWP 7160]
[New LWP 7167]
[New LWP 7165]
[New LWP 7162]
[New LWP 7168]
[New LWP 7163]
[New LWP 7155]
[New LWP 7170]
[New LWP 7164]
[New LWP 7169]
[New LWP 7161]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./skynet bin/lobby/config/config_lobby71'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000041004f in index2addr ()

(gdb) bt
#0  0x000000000041004f in index2addr ()
#1  0x00000000004109e5 in lua_touserdata ()
#2  0x00007faa473fc9cf in releaseobj (L=<optimized out>) at lualib-src/lua-sharedata.c:664
#3  0x0000000000413cdf in luaD_precall ()
#4  0x00000000004140b3 in luaD_call ()
#5  0x0000000000414111 in luaD_callnoyield ()
#6  0x00000000004134fc in luaD_rawrunprotected ()
#7  0x000000000041435d in luaD_pcall ()
#8  0x00000000004154ff in GCTM ()
#9  0x00000000004155a2 in runafewfinalizers ()
#10 0x00000000004169ca in singlestep ()
#11 0x0000000000416da8 in luaC_fullgc ()
#12 0x0000000000411b5f in lua_gc ()
#13 0x000000000042714f in luaB_collectgarbage ()
#14 0x0000000000413cdf in luaD_precall ()
#15 0x000000000041f586 in luaV_execute ()
#16 0x0000000000413f70 in unroll ()
#17 0x00000000004134fc in luaD_rawrunprotected ()
#18 0x0000000000414170 in lua_resume ()
#19 0x0000000000427727 in auxresume ()
#20 0x0000000000427a57 in luaB_coresume ()
#21 0x0000000000413cdf in luaD_precall ()
#22 0x000000000041f586 in luaV_execute ()
#23 0x00000000004140bf in luaD_call ()
#24 0x0000000000414111 in luaD_callnoyield ()
#25 0x00000000004134fc in luaD_rawrunprotected ()
#26 0x000000000041435d in luaD_pcall ()
#27 0x00000000004116fc in lua_pcallk ()
#28 0x0000000000426930 in luaB_pcall ()
#29 0x0000000000413cdf in luaD_precall ()
#30 0x000000000041f586 in luaV_execute ()
#31 0x00000000004140bf in luaD_call ()
#32 0x0000000000414111 in luaD_callnoyield ()
#33 0x00000000004134fc in luaD_rawrunprotected ()
#34 0x000000000041435d in luaD_pcall ()
#35 0x00000000004116fc in lua_pcallk ()
#36 0x00007faa4b7f8e29 in _cb (context=0x7faa48ef9010, ud=0x7faa48c5c708, type=9, session=0, source=12, msg=0x7fa93bf424d8, sz=3) at lualib-src/lua-skynet.c:50
#37 0x000000000040a018 in dispatch_message (ctx=0x7faa48ef9010, msg=0x7faa4ebf5e00) at skynet-src/skynet_server.c:259
#38 0x000000000040aab0 in skynet_context_message_dispatch (sm=sm@entry=0x7faa52416dc0, q=q@entry=0x7faa48c81680, weight=weight@entry=-1) at skynet-src/skynet_server.c:313
#39 0x000000000040b1cd in thread_worker (p=<optimized out>) at skynet-src/skynet_start.c:162
#40 0x00007faa534bb184 in start_thread (arg=0x7faa4ebf6700) at pthread_create.c:312
#41 0x00007faa52ad603d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

搜了一下是在lapi.c的index2addr函数崩溃的，但分析不出到底是什么原因导致崩溃的

dmesg可以看到的内容如下，但分析不出崩溃的原因
[227175.227571] skynet[3507]: segfault at 4 ip 00007f3622dfc9cf sp 00007f3628ff3240 error 6 in sharedata.so[7f3622dfb000+4000]
[545228.280152] skynet[18589]: segfault at 315f3030327f ip 0000000000410042 sp 00007fbf33bfd210 error 4 in skynet[400000+89000]
[899345.076176] skynet[7166]: segfault at 0 ip 000000000041004f sp 00007faa4ebf5230 error 4 in skynet[400000+89000]
[923920.266011] skynet[7200]: segfault at 0 ip 000000000041004f sp 00007f30ccdfe230 error 4 in skynet[400000+89000]

**Comment by cloudfreexiao** [comment]
更新到 最新 skynet 这里修过个 bug 不知道是否有关联 https://github.com/cloudwu/skynet/pull/1034

**Comment by kuro-karasu** [comment]
> 更新到 最新 skynet 试试 这里修过个 bug 不知道是否有关联 #1034

好的，非常感谢，我试试

**Comment by cloudwu** [comment]
历史版本很难维护。建议浏览所有的 c 文件的更新历史，确认所有的 bugfix 。

**Comment by kuro-karasu** [comment]
> 历史版本很难维护。建议浏览所有的 c 文件的更新历史，确认所有的 bugfix 。

的确是与sharedata模块有关，我们这边正在考虑升级到最新的版本，谢谢您的建议
