### ISSUE TITLE
不清楚关于skynet.call的讨论对不对，算不算一个bug?

### ISSUE THREAD

**Issue by wjlovefql** [cloudwu/skynet#1223]
#1220 中讨论了通过skynet.call接口给命名的服务发送消息(通过本地名字)，在还没有处理到该消息的时候，服务通过调用skynet.exit退出，但是调用方并没有收到任何回复的场景。不清楚里面的分析与结论是不是正确？

**Comment by cloudwu** [comment]
skynet 没有提供任何重复注册名字，以及注销名字的方法。所以隐含的约定就是：如果你使用内置的名字系统，一旦服务绑定了名字，该服务就不应该推出。

鉴于内置名字系统的局限性，你应该自己去设计一套机制去用名字和服务地址之间的映射。例如 cluster 就有自己的管理名字的机制。

最后，同一个话题不要新开 issue 。

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/commit/875b7683c608c8b33bc2307185358de85870a242   这里增加了检查，看看是否能解决问题。
