### ISSUE TITLE
skynet.rawcall 远端的一个服务出错,call failed

### ISSUE THREAD

**Issue by FashGek** [cloudwu/skynet#1226]
我有两个结点，一个网关，一个是游戏服，现在网关把客户端的数据，转发到游戏服，用skynet.rawcall不能，如果用skynet.call感觉有点不好，还是要得到原始的客户端传入的数据，
大家是怎么处理这个问题的呢

**Comment by cloudfreexiao** [comment]
看看 skynet.redirect 是否是你要的？

**Comment by cloudwu** [comment]
客户端到服务器通常需要定义一个协议类型，注册给第一个接收它的服务。见 gate 服务的实现。

然后客户端来的消息再由这个服务按需加工在内部流通。

如果希望减少同一节点内，服务间的消息转发的开销，可以用 skynet.forward_type 。

节点间的消息流动，一定有额外打包解包的工作。

另外，不建议设计纯粹的消息转发的网关。如果一定要这么设计，那么建议不走 cluster 那套，直接用 socket api 实现：即，用 socket api 读到客户端数据，经过浅加工，直接用 socket api 转发给其它节点的端口。最多上百行 lua 代码就能实现。

**Comment by sniper00** [comment]
> 我有两个结点，一个网关，一个是游戏服，现在网关把客户端的数据，转发到游戏服，用skynet.rawcall不能，如果用skynet.call感觉有点不好，还是要得到原始的客户端传入的数据，
> 
> 大家是怎么处理这个问题的呢

可以试试asio+cpp协程，非常适合这个
