### ISSUE TITLE
多线程建立luajit虚拟机会导致性能下降

### ISSUE THREAD

**Issue by ToBeMyOwnHero** [cloudwu/skynet#1232]
云风大大，我想请教一下，如果在C里面创建多个线程，在每个线程中都创建一个luajit虚拟机，用luajit虚拟机去执行一些脚本，脚本功能大都是字符串匹配之类的，但是在做压力测试的时候发现，随着线程数的增加，也就是虚拟机数量增加，luajit虚拟机的性能反而下降，线程越多，虚拟机性能下降越厉害。找了很久没有找到原因。

**Comment by cloudwu** [comment]
我不用 luajit 。且字符串匹配都是 C 库，更没任何必要用 luajit 。
