### ISSUE TITLE
怎么让lua虚拟机运行在不同线程上

### ISSUE THREAD

**Issue by ToBeMyOwnHero** [cloudwu/skynet#1233]
skynet.start会启动一个lua虚拟机，skynet.newservice也会启动一个新的lua虚拟机是吗？如果是，这两个虚拟机是在同一个线程上还是不同线程上呢？

**Comment by bluefeng** [comment]
skynet.newservice也会启动一个新的lua虚拟机

**Comment by bluefeng** [comment]
skynet.newservice 启动lua 虚拟机， skynet.start 只是在这个lua 虚拟机中运行的代码
