### ISSUE TITLE
GateServer是模拟gate用socketdriver 还是直接用socket

### ISSUE THREAD

**Issue by semgilo** [cloudwu/skynet#1239]
看官方示例是用socketdriver，但看socket的介绍又提到skynet.socket是对socketdriver的二次封装，弄得有点混乱，请各位大大指点下

**Comment by hflin84** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    1. skynet里的socket是对socketdriver的封装。2. socket里已register_protocol了skynet.PTYPE_SOCKET，使用socket的服务中不应调用register_protocol注册skynet.PTYPE_SOCKET。3. 使用socket是类似于阻塞式的调用方式编写代码，socket内部已通过coroutine模拟了线程的阻塞。例如，socket.read(fd, size), 当未读取到size个字节的数据时，read调用不会返回。4. socketdriver是类似于事件的方式编写代码，需在服务中通过register_protocol注册skynet.PTYPE_SOCKET，并提供相应的dispatch方法。当fd上有数据到底或事件发生时，skynet通过dispatch将数据/事件通知给服务。
    
     
    

    在2020年09月9日 11:15，semgilo<notifications@github.com> 写道： 




看官方示例是用socketdriver，但看socket的介绍又提到skynet.socket是对socketdriver的二次封装，弄得有点混乱，请各位大大指点下



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.



        font{
            line-height: 1.6;
        }
