### ISSUE TITLE
skynet_timer在时间回绕前添加超长时间定时器有bug

### ISSUE THREAD

**Issue by xfyzfish** [cloudwu/skynet#1243]
假设当前时间已经到了0xffffffff，此时再添加一个超时时间为0xffffff00的定时器，该定时器会被放入near[0]链表。由于时间回绕时刚好满足了ct==0，所以只对t[3][0]的进行了timer_shift，并未对near中的链表重排，导致超时时间戳为0xffffff00这种定时器仍留在near中，那么下一次timer_execute便会触发该定时器，产生逻辑bug。如果认为此处不是bug，而是类似linux的jiffies回绕处理，则至少应在像linux在代码中明示此逻辑。

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/issues/584
https://github.com/cloudwu/skynet/issues/784

**Comment by xfyzfish** [comment]
逻辑严谨恐怖如斯，学习了
