### ISSUE TITLE
关于cluster远程进程kill后，无法再次访问问题

### ISSUE THREAD

**Issue by lf723** [cloudwu/skynet#1244]
1、A节点cluster.call B节点
2、这时候故意kill -9 B节点
3、A节点无法继续请求B节点
4、B节点重启后，A节点仍然无法访问B节点的服务

用telnet查看task，发现cluster.query接口阻塞了，没有任何返回

**Comment by cloudwu** [comment]
请检查连接是否断开。

**Comment by lf723** [comment]
B重新监听了，B启动完成后，也收到A的cluster连接请求。
A节点这边是直接调的 cluster.query(B, name)，是A这边要清理旧的cluster信息?但是B启动后的cluster节点信息，和之前的是一致的

**Comment by cloudwu** [comment]
无法重现。最好可以定位到具体的问题在哪里。

**Comment by cloudwu** [comment]
一些实现细节，或许能帮助定位问题：

1. 所有 A 到 B 的请求（包括 query name），都是经由 A 的 clusterd 服务转交给对应的 clustersender 服务的 command.req 方法发向远程。
2. 每个 cluster node 会有一个唯一的 clustersender 服务，无论这个 node 被重启多少次，该服务都不会换。如果 ip port 被重新配置，会调用 clustersender 服务的 changenode 方法重置 channel 。
3. A 到 B 发送的请求，最终是通过 socketchannel 模块请求以及获得回应的。https://github.com/cloudwu/skynet/blob/master/service/clustersender.lua#L68  每个 clustersender 服务都有这么一个 channel 对象。如果需要调试，可以查看这个 channel 工作是否正常。
4. socketchannel 本身会处理重连等业务。kill 节点本质上是断开了 socketchannel 的一端，当重启后，再次请求，应该通过 socketchannel 重新建立连接。

**Comment by lf723** [comment]
嗯，我在这边环境跟下具体的，有结果再反馈

**Comment by lf723** [comment]
跟进发现：
1. B节点被kill后，socketchannel.lua里判断check_connection返回的是true，socket.lua的s.connected = true
2. socketchannel.lua去等待response的时候，永久无回应了. wait_for_response函数中 skynet.wait(co), co这个协程不会被唤醒

**Comment by lf723** [comment]
这边原因是B节点处于另一台服务器的VM虚拟机内，这时候B节点虽然被kill了，但是B节点的宿主机的端口还监听着，而且还是可以connect，但是服务不会响应，这时候A发起的请求，就会一直等待response，即使B节点重启了，也不会去回应这个req

**Comment by cloudwu** [comment]
s.connected = true  是因为进程没有收到 socket 连接断开的消息，这个消息应该是系统给的。所以它认为连接还是健康的。从你后面的描述看，虽然进程被 kill ，但因为连接并不是直接由进程建立的，所以连接的确没有断开。 
你需要有办法先断开和 A 之间的连接，让 A 知道这件事情。

**Comment by lf723** [comment]
嗯，这个过程看是合理，逻辑上我们调整下

**Comment by PowerGit** [comment]
> s.connected = true  是因为进程没有收到 socket 连接断开的消息，这个消息应该是系统给的。所以它认为连接还是健康的。从你后面的描述看，虽然进程被 kill ，但因为连接并不是直接由进程建立的，所以连接的确没有断开。  你需要有办法先断开和 A 之间的连接，让 A 知道这件事情。
--------------------------------------------------------
我这边遇到了一样的问题，一开始是因为端口忘记加白名单了导致无法连接，sender挂起，之后加了白名单重启服务，但是sender的挂起状态还是没有解开, 请问这种需要这么做才能唤醒挂起的协程？
