### ISSUE TITLE
升级至master最新，出现报错

### ISSUE THREAD

**Issue by sue602** [cloudwu/skynet#1249]
原来最早的第三方库都是可以使用，后来升级后出现报错。
这次 eef2b1fc628c8ec428cee31a9be61dfeaf51ee69  commit 没有问题
而 eaa60ca8ddad83c46a560daabdcb196c8e747c09 则出现如下报错
请问下这是什么情况。
[:00000013] lua loader error : error loading module 'cjson' from file 'game/lib/json/cjson.so':
	dlopen(game/lib/json/cjson.so, 6): Symbol not found: _lua_newuserdata
  Referenced from: game/lib/json/cjson.so
  Expected in: flat namespace
 in game/lib/json/cjson.so
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	game/lib/json/json.lua:2: in main chunk
	[C]: in function 'require'

**Comment by lf723** [comment]
修改lua_newuserdatauv即可，最新的升级到了lua 5.4
```c
#if LUA_VERSION_NUM >= 504
    cfg = lua_newuserdatauv(l, sizeof(*cfg), 0);
#else
    cfg = lua_newuserdata(l, sizeof(*cfg));
#endif
```

**Comment by cloudwu** [comment]
编译时未 link 5.4 的 .h 的缘故。lua_newuserdata 在 5.4 是以宏的方式提供。

**Comment by sue602** [comment]
> 编译时未 link 5.4 的 .h 的缘故。lua_newuserdata 在 5.4 是以宏的方式提供。

好的，我解决了，确实是这样。

**Comment by GameKong** [comment]
> 原来最早的第三方库都是可以使用，后来升级后出现报错。
> 这次 [eef2b1f](https://github.com/cloudwu/skynet/commit/eef2b1fc628c8ec428cee31a9be61dfeaf51ee69) commit 没有问题
> 而 [eaa60ca](https://github.com/cloudwu/skynet/commit/eaa60ca8ddad83c46a560daabdcb196c8e747c09) 则出现如下报错
> 请问下这是什么情况。
> [:00000013] lua loader error : error loading module 'cjson' from file 'game/lib/json/cjson.so':
> dlopen(game/lib/json/cjson.so, 6): Symbol not found: _lua_newuserdata
> Referenced from: game/lib/json/cjson.so
> Expected in: flat namespace
> in game/lib/json/cjson.so
> stack traceback:
> [C]: in ?
> [C]: in function 'require'
> game/lib/json/json.lua:2: in main chunk
> [C]: in function 'require'

老哥  我也遇到了 但是不会解决。。 最终怎么解决的啊。 如何link5.4的.h文件。。。 求告知
