### ISSUE TITLE
更复杂的多actor协作事务问题

### ISSUE THREAD

**Issue by longzhiri** [cloudwu/skynet#1254]
你好！我是最近新了解skynet，想到在多线程游戏逻辑中常会遇到的多actor协作事务问题，在网上看到你之前[博客中的一种解决方案](https://blog.codingnow.com/2016/07/skynet_transaction.html)，顺着这个博客中的例子，我想问的是，假如是更复杂的情况，比如一块共享数据除了在B类事务中需要被操作，在A类事务中也需要被操作，像shop可能还有进货逻辑，bank可能还有存取逻辑等，为了提高并行度，会把例子中的类似锁的transaction拆分的更细粒度，如果是这样是不是还是会退化到多线程中的多个锁的使用，容易死锁的情形。

**Comment by cloudwu** [comment]
不想讨论空想的问题。

有实际的问题和具体的方案，出现了现实的问题后，可以拿出来讨论。
