### ISSUE TITLE
关于sproto_unpack这个算法经过调试发现明显src的索引上超过了srcsz的，这样设计是合理的吗?

### ISSUE THREAD

**Issue by FashGek** [cloudwu/skynet#1268]
问题：对于一个长度为19个字节的buf，我的理解是索引应该是0-18，但算法明显使用到了19，而且我调试之后发现，明显可以索引srcv之后相当长的一段数据，这样设计合理吗？

之所以遇到这个问题，我在用c#来解同一段buf，c#就没有办法越界访问了，导致unpack总是失败。我当然可以在C#版本也多出1个字节，但为什么是一个字节，不是2个字节甚至更多，这样设计没有理论支撑，担心不通用。

**Comment by FashGek** [comment]
这是我加了调试的版本的sprot_unpack


int
sproto_unpack(const void * srcv, int srcsz, void * bufferv, int bufsz) {
	const uint8_t * src = srcv;
	const uint8_t * srct = srcv;
	const uint8_t * srcp = srcv;
	uint8_t * buffer = bufferv;
	uint8_t * pbuf = bufferv;
	printf("init pbuf = %d \n", *pbuf);
	int p = 0;
	for (p = 0; p < srcsz + 30; ++p) {
		printf("%d ", *srcp);
		++srcp;
	}
	printf("\n");


	int size = 0;
	printf("unpack begin srcsz = %d bufsz = %d \n", srcsz, bufsz);
	while (srcsz > 0) {
		printf("srcsz when begin while loop = %d \n", srcsz);
		uint8_t header = src[0];
		--srcsz;
		++src;
		printf("dist of src = %d at = %d\n", src - srct, srct[src-srct]);
		if (header == 0xff) {
			int n;
			if (srcsz < 0) {
				return -1;
			}
			n = (src[0] + 1) * 8;
			if (srcsz < n + 1)
				return -1;
			srcsz -= n + 1;
			++src;
			if (bufsz >= n) {
				memcpy(buffer, src, n);
			}
			bufsz -= n;
			buffer += n;
			src += n;
			size += n;
			char s[1024] = {0};
			int si = 0;
			printf("\n--------------if---------------------\n");
			uint8_t *p = pbuf; 
			int k = 0;
			while (p != buffer) {
				printf("%d ", *p);
				++p; ++k;
				if (k % 8 == 0) printf("\n");
			}
			/*
			int p = 0;
			for (p = 0; p < bufsz; ++p) {
				printf("%d ", buffer[p]);
				if (p % 8 == 0) printf("\n");
			}
			for (i = 0; i < bufsz; ++i) {
				char tmp[9] = {0};
				sprintf(tmp, " %d ", buffer[i]);
				memcpy(&s[si], tmp, strlen(tmp));
				si += strlen(tmp);
			}
			printf("%s \n", s);*/
		} else {
			int i;
			printf("else for loop \n");
			for (i=0;i<8;i++) {
				int nz = (header >> i) & 1;
				if (nz) {
					if (srcsz < 0)
						return -1;
					if (bufsz > 0) {
						*buffer = *src;
					printf("nz = %d srcsz = %d src = %d src_dist = %d bufz=%d bufer=%d header = %d\n ", nz, srcsz, *src, src - srct, bufsz, *buffer, header);
						--bufsz;
						++buffer;
					}
					++src;
					--srcsz;
				} else {
					if (bufsz > 0) {
						*buffer = 0;
					printf("nz = %d srcsz = %d src = %d src_dist = %d bufsz =%d bufer=%d header = %d \n ", nz, srcsz, *src, src - srct, bufsz, *buffer, header);
						--bufsz;
						++buffer;
					}
				}
				++size;
			}
			printf("\n-----------------------------------else--------------\n");
			uint8_t *p = pbuf; 
			int k = 0;
			while (p != buffer) {
				printf("%d ", *p);
				++p; ++k;
				if (k % 8 == 0) printf("\n");
			}

/*

			char s[1024] = {0};
			int si = 0;
			
			int p = 0;
			for (p = 0; p < bufsz; ++p) {
				printf("%d ", buffer[p]);
				if (p % 8 == 0) printf("\n");
			}
			
			for (i = 0; i < bufsz; ++i) {
				char tmp[9] = {0};
				sprintf(tmp, " %d ", buffer[i]);
				memcpy(&s[si], tmp, strlen(tmp));
				si += strlen(tmp);
			}
			printf("%s\n", s);*/
		}
	}
	return size;
}

**Comment by FashGek** [comment]
这是整个算法工作过程，及索引变化，我在开头明显越界。
unpack_pkg size = 21
unpack header len = 19
a = VQIBBgNRAgIEPP////8BAAAAAg== b = 
init pbuf = 0 
85 2 1 6 3 81 2 2 4 60 255 255 255 255 1 0 0 0 2 0 0 0 0 0 49 0 0 0 0 0 0 0 64 116 247 66 63 86 0 0 4 1 0 2 183 182 240 211 0 
unpack begin srcsz = 19 bufsz = 2050 
srcsz when begin while loop = 19 
dist of src = 1 at = 2
else for loop 
nz = 1 srcsz = 18 src = 2 src_dist = 1 bufz=2050 bufer=2 header = 85
 nz = 0 srcsz = 17 src = 1 src_dist = 2 bufsz =2049 bufer=0 header = 85 
 nz = 1 srcsz = 17 src = 1 src_dist = 2 bufz=2048 bufer=1 header = 85
 nz = 0 srcsz = 16 src = 6 src_dist = 3 bufsz =2047 bufer=0 header = 85 
 nz = 1 srcsz = 16 src = 6 src_dist = 3 bufz=2046 bufer=6 header = 85
 nz = 0 srcsz = 15 src = 3 src_dist = 4 bufsz =2045 bufer=0 header = 85 
 nz = 1 srcsz = 15 src = 3 src_dist = 4 bufz=2044 bufer=3 header = 85
 nz = 0 srcsz = 14 src = 81 src_dist = 5 bufsz =2043 bufer=0 header = 85 
 
-----------------------------------else--------------
2 0 1 0 6 0 3 0 
srcsz when begin while loop = 14 
dist of src = 6 at = 2
else for loop 
nz = 1 srcsz = 13 src = 2 src_dist = 6 bufz=2042 bufer=2 header = 81
 nz = 0 srcsz = 12 src = 2 src_dist = 7 bufsz =2041 bufer=0 header = 81 
 nz = 0 srcsz = 12 src = 2 src_dist = 7 bufsz =2040 bufer=0 header = 81 
 nz = 0 srcsz = 12 src = 2 src_dist = 7 bufsz =2039 bufer=0 header = 81 
 nz = 1 srcsz = 12 src = 2 src_dist = 7 bufz=2038 bufer=2 header = 81
 nz = 0 srcsz = 11 src = 4 src_dist = 8 bufsz =2037 bufer=0 header = 81 
 nz = 1 srcsz = 11 src = 4 src_dist = 8 bufz=2036 bufer=4 header = 81
 nz = 0 srcsz = 10 src = 60 src_dist = 9 bufsz =2035 bufer=0 header = 81 
 
-----------------------------------else--------------
2 0 1 0 6 0 3 0 
2 0 0 0 2 0 4 0 
srcsz when begin while loop = 10 
dist of src = 10 at = 255
else for loop 
nz = 0 srcsz = 9 src = 255 src_dist = 10 bufsz =2034 bufer=0 header = 60 
 nz = 0 srcsz = 9 src = 255 src_dist = 10 bufsz =2033 bufer=0 header = 60 
 nz = 1 srcsz = 9 src = 255 src_dist = 10 bufz=2032 bufer=255 header = 60
 nz = 1 srcsz = 8 src = 255 src_dist = 11 bufz=2031 bufer=255 header = 60
 nz = 1 srcsz = 7 src = 255 src_dist = 12 bufz=2030 bufer=255 header = 60
 nz = 1 srcsz = 6 src = 255 src_dist = 13 bufz=2029 bufer=255 header = 60
 nz = 0 srcsz = 5 src = 1 src_dist = 14 bufsz =2028 bufer=0 header = 60 
 nz = 0 srcsz = 5 src = 1 src_dist = 14 bufsz =2027 bufer=0 header = 60 
 
-----------------------------------else--------------
2 0 1 0 6 0 3 0 
2 0 0 0 2 0 4 0 
0 0 255 255 255 255 0 0 
srcsz when begin while loop = 5 
dist of src = 15 at = 0
else for loop 
nz = 1 srcsz = 4 src = 0 src_dist = 15 bufz=2026 bufer=0 header = 1
 nz = 0 srcsz = 3 src = 0 src_dist = 16 bufsz =2025 bufer=0 header = 1 
 nz = 0 srcsz = 3 src = 0 src_dist = 16 bufsz =2024 bufer=0 header = 1 
 nz = 0 srcsz = 3 src = 0 src_dist = 16 bufsz =2023 bufer=0 header = 1 
 nz = 0 srcsz = 3 src = 0 src_dist = 16 bufsz =2022 bufer=0 header = 1 
 nz = 0 srcsz = 3 src = 0 src_dist = 16 bufsz =2021 bufer=0 header = 1 
 nz = 0 srcsz = 3 src = 0 src_dist = 16 bufsz =2020 bufer=0 header = 1 
 nz = 0 srcsz = 3 src = 0 src_dist = 16 bufsz =2019 bufer=0 header = 1 
 
-----------------------------------else--------------
2 0 1 0 6 0 3 0 
2 0 0 0 2 0 4 0 
0 0 255 255 255 255 0 0 
0 0 0 0 0 0 0 0 
srcsz when begin while loop = 3 
dist of src = 17 at = 0
else for loop 
nz = 0 srcsz = 2 src = 0 src_dist = 17 bufsz =2018 bufer=0 header = 0 
 nz = 0 srcsz = 2 src = 0 src_dist = 17 bufsz =2017 bufer=0 header = 0 
 nz = 0 srcsz = 2 src = 0 src_dist = 17 bufsz =2016 bufer=0 header = 0 
 nz = 0 srcsz = 2 src = 0 src_dist = 17 bufsz =2015 bufer=0 header = 0 
 nz = 0 srcsz = 2 src = 0 src_dist = 17 bufsz =2014 bufer=0 header = 0 
 nz = 0 srcsz = 2 src = 0 src_dist = 17 bufsz =2013 bufer=0 header = 0 
 nz = 0 srcsz = 2 src = 0 src_dist = 17 bufsz =2012 bufer=0 header = 0 
 nz = 0 srcsz = 2 src = 0 src_dist = 17 bufsz =2011 bufer=0 header = 0 
 
-----------------------------------else--------------
2 0 1 0 6 0 3 0 
2 0 0 0 2 0 4 0 
0 0 255 255 255 255 0 0 
0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 
srcsz when begin while loop = 2 
dist of src = 18 at = 2
else for loop 
nz = 0 srcsz = 1 src = 2 src_dist = 18 bufsz =2010 bufer=0 header = 0 
 nz = 0 srcsz = 1 src = 2 src_dist = 18 bufsz =2009 bufer=0 header = 0 
 nz = 0 srcsz = 1 src = 2 src_dist = 18 bufsz =2008 bufer=0 header = 0 
 nz = 0 srcsz = 1 src = 2 src_dist = 18 bufsz =2007 bufer=0 header = 0 
 nz = 0 srcsz = 1 src = 2 src_dist = 18 bufsz =2006 bufer=0 header = 0 
 nz = 0 srcsz = 1 src = 2 src_dist = 18 bufsz =2005 bufer=0 header = 0 
 nz = 0 srcsz = 1 src = 2 src_dist = 18 bufsz =2004 bufer=0 header = 0 
 nz = 0 srcsz = 1 src = 2 src_dist = 18 bufsz =2003 bufer=0 header = 0 
 
-----------------------------------else--------------
2 0 1 0 6 0 3 0 
2 0 0 0 2 0 4 0 
0 0 255 255 255 255 0 0 
0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 
srcsz when begin while loop = 1 
dist of src = 19 at = 0
else for loop 
nz = 0 srcsz = 0 src = 0 src_dist = 19 bufsz =2002 bufer=0 header = 2 
 nz = 1 srcsz = 0 src = 0 src_dist = 19 bufz=2001 bufer=0 header = 2
 nz = 0 srcsz = -1 src = 0 src_dist = 20 bufsz =2000 bufer=0 header = 2 
 nz = 0 srcsz = -1 src = 0 src_dist = 20 bufsz =1999 bufer=0 header = 2 
 nz = 0 srcsz = -1 src = 0 src_dist = 20 bufsz =1998 bufer=0 header = 2 
 nz = 0 srcsz = -1 src = 0 src_dist = 20 bufsz =1997 bufer=0 header = 2 
 nz = 0 srcsz = -1 src = 0 src_dist = 20 bufsz =1996 bufer=0 header = 2 
 nz = 0 srcsz = -1 src = 0 src_dist = 20 bufsz =1995 bufer=0 header = 2 
 
-----------------------------------else--------------
2 0 1 0 6 0 3 0 
2 0 0 0 2 0 4 0 
0 0 255 255 255 255 0 0 
0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0

**Comment by cloudwu** [comment]
谢谢。我似乎看到了问题。不过，我建议把原帖排版一下，尤其是代码部分。

**Comment by cloudwu** [comment]
我改了一下，应该修复了这个问题。

**Comment by FashGek** [comment]
./skynet/3rd/lua/lua: ./skynet/lualib/sproto.lua:198: Invalid unpack stream
stack traceback:
        [C]: in function 'sproto.core.unpack'
        ./skynet/lualib/sproto.lua:198: in method 'dispatch'
        ./robots/robot_userlogin.lua:324: in local 'dispatch_package'
        ./robots/robot_userlogin.lua:340: in main chunk
        [C]: in ?

**Comment by FashGek** [comment]
没有修复，反倒不再工作了

**Comment by FashGek** [comment]
用的是这个版本的sproto_unpack

int
sproto_unpack(const void * srcv, int srcsz, void * bufferv, int bufsz) {
	const uint8_t * src = srcv;
	uint8_t * buffer = bufferv;
	int size = 0;
	while (srcsz > 0) {
		uint8_t header = src[0];
		--srcsz;
		++src;
		if (header == 0xff) {
			int n;
			if (srcsz <= 0) {
				return -1;
			}
			n = (src[0] + 1) * 8;
			if (srcsz < n + 1)
				return -1;
			srcsz -= n + 1;
			++src;
			if (bufsz >= n) {
				memcpy(buffer, src, n);
			}
			bufsz -= n;
			buffer += n;
			src += n;
			size += n;
		} else {
			int i;
			for (i=0;i<8;i++) {
				int nz = (header >> i) & 1;
				if (nz) {
					if (srcsz <= 0)
						return -1;
					if (bufsz > 0) {
						*buffer = *src;
						--bufsz;
						++buffer;
					}
					++src;
					--srcsz;
				} else {
					if (bufsz > 0) {
						*buffer = 0;
						--bufsz;
						++buffer;
					}
				}
				++size;
			}
		}
	}
	return size;
}

**Comment by FashGek** [comment]
不太会用这个编辑器，无法保持格式，我再学习下

**Comment by cloudwu** [comment]
学习一下 markdown : https://guides.github.com/features/mastering-markdown/

如果我没理解错，你的数据源有 19 字节： 85 2 1 6 3 81 2 2 4 60 255 255 255 255 1 0 0 0 2

它其实是分为这样几节的：
```
85(01010101) 2 1 6 3
81(01010001) 2 2 4
60(00111100) 255 255 255 255 1
0 0 0
2(00000010)
```
最后这个 2 表示后面必须还有一个字节的数据，你这里没有，所以是 Invalid unpack stream 。

ps. 建议你给出一个完整的你任何能暴露问题的测试数据集。

**Comment by FashGek** [comment]
我使用最新的源码编译安装，然后把examples/login下的服务，增加了sproto的解析，依然会报这个错误

**Comment by cloudwu** [comment]
给一个有错误的测试数据集。

**Comment by FashGek** [comment]
[new-files.tar.gz](https://github.com/cloudwu/skynet/files/5676902/new-files.tar.gz)
这 个文件包含了我的变化，主要就是msgagent增加了request的解析，但是一解析sproto协议就出错，

**Comment by FashGek** [comment]
我上传了

**Comment by cloudwu** [comment]
不要给源代码，给数据。

**Comment by cloudwu** [comment]
我看见在 client.lua 中有这么一个函数:
```lua
local function send_sproto_request(name, args, f)
	session = session + 1
	local str = request(name, args, session)
	local size = #str + 4
	local package = string.pack(">I2", size)..str..string.pack(">I4", session)
	send_package(fd, package)
	
	print("Request:", session)
end
```
明显，这里的 package 中还包含了 4 个字节的 session ，并不是由 sproto 的 pack 产生的数据。

而在 msgagent.lua 中，
```lua
unpack = function (msg, sz)
	return host:dispatch(msg, sz)
end,
```
把这额外的（不由 sproto 产生的） 4 个字节直接传给了 sproto 的 dispatch 函数。

ps. 下次先自己 debug 一下，再提 issue 。

**Comment by FashGek** [comment]
local function do_request(fd, message)
		local u = assert(connection[fd], "invalid fd")
		local session = string.unpack(">I4", message, -4)
		message = message:sub(1,-5)
		local p = u.response[session]

是这样的，msgserver示例， 我的理解是它会把这4个字节脱掉，然后给sproto的是没有那4个字节的

**Comment by FashGek** [comment]
ok，明白了，我在几个服务器之间来回切换，是我锅

**Comment by FashGek** [comment]
感谢
