### ISSUE TITLE
之前用clusterd.reload设置的节点地址连接不上的话，之后再用clusterd.reload也不能切换到新的地址

### ISSUE THREAD

**Issue by loboho** [cloudwu/skynet#1273]
看了一下clusterd.lua，上一个连接未完成的话，后面再调用clusterd.reload，table.insert(reload, name)会被跳过，而open_channel（）的最后虽然有再检测node_address的地址是否变更，但因为连接失败发生assert而跳过了这个检查。

**Comment by cloudwu** [comment]
我把 assert 移到了后面，看看这样是不是就能解决问题？

**Comment by loboho** [comment]
> 我把 assert 移到了后面，看看这样是不是就能解决问题？

不能完全解决，如果之后的cluster.reload是在前一个连接已经报告失败之后执行的，仍然切换不了。

**Comment by cloudwu** [comment]
如果之前没有连接过（包括失败），那么 reload 后，需要等到下一次真正有请求时，由 __index 方法触发 open channel 建立连接。而并非由 loadconfig() 建立。

这个行为和一开始第一次读入 config 一致：所有连接均推迟到第一次真正需要的时候建立。

**Comment by loboho** [comment]
```
                                -- address changed
                                if rawget(node_channel, name) then --之前的连接失败的话，这里条件会一直不成立
                                        node_channel[name] = nil        -- reset connection
                                        table.insert(reload, name)
                                end
                                node_address[name] = address
```
因为连接失败之后，table.insert(reload, name)是一直会被跳过的，因此不会再有机会执行到open_channel，这样之后的请求还一直是会使用之前连接失败的那个地址，实际测试也是这样的。

**Comment by cloudwu** [comment]
当 node_channel[name] 为空时（即 rawget (node_channel, name) 为空） ，下次访问 node_channel 的 name 就应该触发 __index 去调用 open_channel 呀？ 

为什么没有机会调用到？

**Comment by loboho** [comment]
云风兄，我们是通过lualib/skynet/cluster.lua这里的接口调用clusterd服务的，在cluster.lua实现里，第一次调用cluster.send或cluster.call时，会调用pcall(skynet.call, clusterd, "lua", "sender", node)触发node_channel的__index，同时会把返回值缓存起来，之后（在同一个调用者lua环境里）就不会再获取clusterd的sender了，也就不会再触发node_channel的__index。

**Comment by cloudwu** [comment]
1. 你不能在 cluster.reload 里重置 cache ，因为调用 reload 的服务和调用 send 或 call 的在同一个服务。
2. sender 服务一旦创建成功，就不会再销毁，而只会用 changenode 修改。

我大致明白是什么问题了。

**Comment by cloudwu** [comment]
此处的问题在于：只要 node_sender[name] 已经创建好，reload 就有责任触发它的 changenode 命令。因为其它服务有可能 cache 住了 sender 服务地址，所以不会通知 clusterd 触发 __index 方法。

@loboho 麻烦看看这样是不是就正确了？

**Comment by loboho** [comment]
> 此处的问题在于：只要 node_sender[name] 已经创建好，reload 就有责任触发它的 changenode 命令。因为其它服务有可能 cache 住了 sender 服务地址，所以不会通知 clusterd 触发 __index 方法。
> 
> @loboho 麻烦看看这样是不是就正确了？

嗯，这样可以了，测试后可以正常reload连接了，谢谢云风兄。
