### ISSUE TITLE
snlua不支持 lua_setallocf 自定义内存分配器

### ISSUE THREAD

**Issue by lsg2020** [cloudwu/skynet#1280]
lua_resumeX 和 signal_hook  通过 lua_getallocf转换lua_State -> snlua, 如果定义了自己的分配器，将会导致这里取到非法snlua

**Comment by cloudwu** [comment]
不打算支持。

**Comment by cloudwu** [comment]
如果非要使用 ud ，建议继承 struct snlua 结构，再后面加一个 void * ud 。这样可以维持和目前版本的一致。

**Comment by lsg2020** [comment]
嗯，好，我只是想在分配器调用链 里获取lua内存分配信息来做内存的profiler
