### ISSUE TITLE
./skynet examples/config 没跑起来，大家帮忙看下

### ISSUE THREAD

**Issue by hey-man-speak-up** [cloudwu/skynet#1312]
ubuntu@localhost:~/skynet$ ./skynet examples/config
[:01000002] LAUNCH snlua bootstrap
[:01000003] LAUNCH snlua launcher
[:01000004] LAUNCH snlua cmaster
[:01000004] master listen socket 0.0.0.0:2013
[:01000005] LAUNCH snlua cslave
[:01000005] slave connect to master 127.0.0.1:2013
[:01000004] connect from 127.0.0.1:52220 4
[:01000006] LAUNCH harbor 1 16777221
[:01000004] Harbor 1 (fd=4) report 127.0.0.1:2526
[:01000005] Waiting for 0 harbors
[:01000005] Shakehand ready
[:01000007] LAUNCH snlua datacenterd
[:01000008] LAUNCH snlua service_mgr
[:01000009] LAUNCH snlua main
[:01000009] Server start
[:0100000a] LAUNCH snlua protoloader
[:0100000b] LAUNCH snlua console
[:0100000c] LAUNCH snlua debug_console 8000
[:0100000c] Start debug console at 127.0.0.1:8000
[:0100000d] LAUNCH snlua simpledb
[:0100000e] LAUNCH snlua watchdog
[:0100000f] LAUNCH snlua gate
[:0100000f] Listen on 0.0.0.0:8888
[:0100000f] lua call [100000e to :100000f : 3 msgsz = 36] error : ./lualib/skynet.lua:858: ./lualib/skynet.lua:329: ./lualib/snax/gateserver.lua:41: Listen error
stack traceback:
	[C]: in function 'skynet.socketdriver.listen'
	./lualib/snax/gateserver.lua:41: in local 'f'
	./lualib/snax/gateserver.lua:148: in upvalue 'f'
	./lualib/skynet.lua:279: in function <./lualib/skynet.lua:251>
stack traceback:
	[C]: in function 'assert'
	./lualib/skynet.lua:858: in function 'skynet.dispatch_message'
[:0100000e] lua call [100000f to :100000e : 3 msgsz = 0] error : ./lualib/skynet.lua:858: ./lualib/skynet.lua:329: ./lualib/skynet.lua:590: call failed
stack traceback:
	[C]: in function 'error'
	./lualib/skynet.lua:590: in upvalue 'yield_call'
	./lualib/skynet.lua:607: in function 'skynet.call'
	./examples/watchdog.lua:43: in local 'f'
	./examples/watchdog.lua:58: in upvalue 'f'
	./lualib/skynet.lua:279: in function <./lualib/skynet.lua:251>
stack traceback:
	[C]: in function 'assert'
	./lualib/skynet.lua:858: in function 'skynet.dispatch_message'
[:01000009] init service failed: ./lualib/skynet.lua:590: call failed
stack traceback:
	[C]: in function 'error'
	./lualib/skynet.lua:590: in upvalue 'yield_call'
	./lualib/skynet.lua:607: in function 'skynet.call'
	./examples/main.lua:15: in local 'start'
	./lualib/skynet.lua:962: in function <./lualib/skynet.lua:959>
	[C]: in function 'xpcall'
	./lualib/skynet.lua:966: in function 'skynet.pcall'
	./lualib/skynet.lua:970: in function 'skynet.init_service'
	./lualib/skynet.lua:983: in upvalue 'f'
	./lualib/skynet.lua:252: in function <./lualib/skynet.lua:251>
[:01000009] KILL self
[:01000002] KILL self
^C

**Comment by cloudfreexiao** [comment]
监听失败 
```lua
[:0100000f] lua call [100000e to :100000f : 3 msgsz = 36] error : ./lualib/skynet.lua:858: ./lualib/skynet.lua:329: ./lualib/snax/gateserver.lua:41: Listen error
```

**Comment by hey-man-speak-up** [comment]
哦，没错，谢谢：）

**Comment by hey-man-speak-up** [comment]
resolved

**Comment by loserZhang** [comment]
> 哦，没错，谢谢：）

**Comment by loserZhang** [comment]
> 哦，没错，谢谢：）

这个怎么解决呢

**Comment by hanxi** [comment]
> > 哦，没错，谢谢：）
> 
> 这个怎么解决呢

改监听端口
