### ISSUE TITLE
skynet.timeout 不支持传递参数

### ISSUE THREAD

**Issue by ZhouJiaZhi** [cloudwu/skynet#1313]
skynet.fork是支持传递参数的，skynet.timeout能改成和skyney.fork一样传递参数吗
![image](https://user-images.githubusercontent.com/20750357/103535331-7a2c8e00-4ecb-11eb-8b72-3e7e10b3b6ce.png)
![image](https://user-images.githubusercontent.com/20750357/103535358-831d5f80-4ecb-11eb-89de-388856d5af25.png)

**Comment by cloudfreexiao** [comment]
https://github.com/cloudwu/skynet/issues/379

**Comment by cloudwu** [comment]
如果需要可以自己封装，更为灵活。
