### ISSUE TITLE
限制服务最大coroutine数量

### ISSUE THREAD

**Issue by JieTrancender** [cloudwu/skynet#1315]
有一个事件管理器，担心监听同一事件的函数太多，所以每次触发事件都使用了skynet.fork去执行所有这个事件的函数。
现在想限制这个事件管理器最大fork数，求教一下怎么做？

看了skynet.fork函数，协程池如果数量不足时会新建协程，使用后放入协程池。所以协程池会一直变大(如果足够频繁申请)，所以现在想在这个事件管理器里面实现协程数量限制。

**Comment by cloudwu** [comment]
1. 此类问题建议发在 Discussions.
2. 建议看一下这里的讨论：https://github.com/cloudwu/skynet/pull/1277
3. 参考 https://github.com/cloudwu/skynet/blob/master/lualib/snax/gateserver.lua#L65

**Comment by JieTrancender** [comment]
> 1. 此类问题建议发在 Discussions.
> 2. 建议看一下这里的讨论：#1277
> 3. 参考 https://github.com/cloudwu/skynet/blob/master/lualib/snax/gateserver.lua#L65
> 
> 另外，“担心监听同一事件的函数太多” 是什么意思？fork 并不会并行。同一服务永远不会有并行。

1. 谢谢，后面注意发在Discussions
2. 看了下，和 https://github.com/cloudwu/skynet/pull/1277 是类似的问题，我看一下这个和你提到的第3点
3. "担心监听同一事件的函数太多"这句话的意思是当前调用需要快速结束，不能等执行一大批函数之后再结束
