### ISSUE TITLE
mac编译报错

### ISSUE THREAD

**Issue by Tangkysin** [cloudwu/skynet#1321]
master分支，commit 是 53a74ca02986af0841e1cf32ad7542748c56dfde
中午拉下来编译的
macOS版本是 11.1 (20C69)
Apple clang version 12.0.0 (clang-1200.0.32.21)
Target: x86_64-apple-darwin20.2.0
Thread model: posix

_Originally posted by @Tangkysin in https://github.com/cloudwu/skynet/issues/1075#issuecomment-758449155_

**Comment by Tangkysin** [comment]
/Applications/Xcode.app/Contents/Developer/usr/bin/make all PLAT=macosx SKYNET_LIBS="-lpthread -lm -ldl" SHARED="-fPIC -dynamiclib -Wl,-undefined,dynamic_lookup" EXPORT="" MALLOC_STATICLIB="" SKYNET_DEFINES="-DNOUSE_JEMALLOC"
cc -g -O2 -Wall -I3rd/lua  -o skynet skynet-src/skynet_main.c skynet-src/skynet_handle.c skynet-src/skynet_module.c skynet-src/skynet_mq.c skynet-src/skynet_server.c skynet-src/skynet_start.c skynet-src/skynet_timer.c skynet-src/skynet_error.c skynet-src/skynet_harbor.c skynet-src/skynet_env.c skynet-src/skynet_monitor.c skynet-src/skynet_socket.c skynet-src/socket_server.c skynet-src/malloc_hook.c skynet-src/skynet_daemon.c skynet-src/skynet_log.c 3rd/lua/liblua.a -Iskynet-src -I3rd/jemalloc/include/jemalloc   -lpthread -lm -ldl -DNOUSE_JEMALLOC
Undefined symbols for architecture x86_64:
  "_luaL_initcodecache", referenced from:
      _main in skynet_main-678fcc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [skynet] Error 1
make: *** [macosx] Error 2

附上错误信息

**Comment by pickline** [comment]
你看看是不是有些submodule没有拉下来

**Comment by Tangkysin** [comment]
> 你看看是不是有些submodule没有拉下来

看着应该够了，git clone 下来的

![image](https://user-images.githubusercontent.com/5828255/104290014-c3e12e00-54f4-11eb-89df-9e5574c854bb.png)

submodule只有一个，而且mac编译是跳过这个的。
![image](https://user-images.githubusercontent.com/5828255/104290145-f4c16300-54f4-11eb-8e82-fb84273bf58a.png)

**Comment by cloudwu** [comment]
_luaL_initcodecache 这个符号在 https://github.com/cloudwu/skynet/blob/master/3rd/lua/lauxlib.c#L1111  这里定义。应该在  3rd/lua/liblua.a 中。

检查一下 lua 有没有正确编译。

**Comment by Tangkysin** [comment]
> _luaL_initcodecache 这个符号在 https://github.com/cloudwu/skynet/blob/master/3rd/lua/lauxlib.c#L1111 这里定义。应该在 3rd/lua/liblua.a 中。
> 
> 检查一下 lua 有没有正确编译。

我在 3rd/lua 目录下  
make clean 之后重新
make
就可以了
