### ISSUE TITLE
更新skynet.require之后，snax和gateserver冲突。

### ISSUE THREAD

**Issue by wNakiami** [cloudwu/skynet#1326]
pull了最新代码，skynet.start现在被限制只能调用一次。
snax和gateserver都会调用skynet.start，没法同时使用了。

**Comment by cloudwu** [comment]
skynet.start 一直都只能调用一次？你怎么用的？

**Comment by wNakiami** [comment]
之前的版本应该是20年2月份左右的还在用lua5.3。今天尝试升级到最新版，报错之后才发现有同事在snax的init方法里面调用了sky net.start。升级之前并没有错误一直稳定运行的。

我们有一个go的网关服务，负责和客户端链接，然后再转发数据到skynet服务上来。有个gate服务处理和go网关的链接，gate服务同时用的snax和gateserver，这俩都会调用一次skynet.start。

**Comment by cloudwu** [comment]
多次调用 skynet.start 本身是不对的。比如 skynet.start 会向 launcher 发消息确认启动成功，理论上调用多次会虚报多次。而且在 skynet.start 之后，理论上就允许接收消息。而在第一次和第二次 start 之间，如果有任何第二次 start 才开始处理的消息都会报错。

理论上在 skynet.start 之后不应该再运行任何代码，它应该是服务程序的最后一行。

所以你之前的用法是 bug 没有显露而已。

你这个问题是希望 gateserver 模板想独立使用，只注册对应的消息处理函数，而不调用 skynet.start 。我在刚才的 patch 中给 handler 增加了一个 .embed 参数，如果设置为 true ，就只注册消息处理函数，不调用 skynet.start。

**Comment by wNakiami** [comment]
感谢这么快就处理了。
我发现错误调用skynet.start之后已经修改了，所以一开始没提。
