### ISSUE TITLE
升级1.4.0,发现在强杀客户端的情况下有概率出现gateserver.lua中的MSG.close(fd)函数没调用到

### ISSUE THREAD

**Issue by sue602** [cloudwu/skynet#1331]
说明：1.3 版本的没有这个问题。同样都有用nginx做转发业务。

MSG.close 事件由
lua-netpack.c 中的 lfilter 函数触发，类型是 SKYNET_SOCKET_TYPE_CLOSE
而该事件，是由 skynet_socket_poll 触发，类型是 SOCKET_CLOSE 

而 Commit: 56c70dc7ace1fb668debc254b30adddd711f7e48 这次修复 fix socket half close (#1263) 问题有改动到代码。
如下 if (n==0) 的情况

```c
static int
forward_message_tcp(struct socket_server *ss, struct socket *s, struct socket_lock *l, struct socket_message * result) {
	int sz = s->p.size;
	char * buffer = MALLOC(sz);
	int n = (int)read(s->fd, buffer, sz);
	if (n<0) {
		FREE(buffer);
		switch(errno) {
		case EINTR:
			break;
		case AGAIN_WOULDBLOCK:
			skynet_error(NULL, "socket-server: EAGAIN capture.");
			break;
		default:
			// close when error
			force_close(ss, s, l, result);
			result->data = strerror(errno);
			return SOCKET_ERR;
		}
		return -1;
	}
	if (n==0) {
		FREE(buffer);
		if (nomore_sending_data(s)) {
			force_close(ss,s,l,result); 
			return SOCKET_CLOSE;
		} else { 
			s->type = SOCKET_TYPE_HALFCLOSE;
			shutdown(s->fd, SHUT_RD);
			return -1;  // 怀疑此处返回值有问题
		}
	}

	if (s->type == SOCKET_TYPE_HALFCLOSE) {
		// discard recv data
		FREE(buffer);
		return -1;
	}

	stat_read(ss,s,n);

	if (n == sz) {
		s->p.size *= 2;
	} else if (sz > MIN_READ_BUFFER && n*2 < sz) {
		s->p.size /= 2;
	}

	result->opaque = s->opaque;
	result->id = s->id;
	result->ud = n;
	result->data = buffer;
	return SOCKET_DATA;
}
```

**Comment by sue602** [comment]
测试确定，将代码回退到之前的版本，是能够正常回调到 MSG.close(fd)
代码如下：
if (n==0) {
		FREE(buffer);
		force_close(ss,s,l,result); 
		return SOCKET_CLOSE;
	}

**Comment by cloudwu** [comment]
这个问题比较复杂。看看我在 halfclose 分支上刚提交的 patch 能否修复。

**Comment by cloudwu** [comment]
解释一下：之前 skynet 的 socket server 部分，socket 的状态只记录了一个 half close 状态，这个是不够的。

由于 tcp 连接是双工的，那么 half close 应该有两种，一种是关闭了写，也就是对端不再接收写出的数据；另一种是对端不在发送数据，或者我方不再想接收对方的数据，这种即关闭了读。

只有同时关闭读和写才能在底层完全关闭 socket 。

如果逻辑层主动调用 socket.close 关闭 fd ，或是对端关闭了写，当底层还有数据要发送的时候，就应该只关闭读（处于 half close read  状态），需要等数据发送完毕。但是此刻，逻辑层的 SOCKET_CLOSE 消息应该触发。否则，在 tcp 关闭流程无法正确履行完毕时，有可能迟迟无法收到这个 close 消息。（这个时候，还是可以写数据的，但是因为对方不收，数据发不出去）

这次的修改增加了两个不同的 half close 状态，表示不同的单工状态。任何一个 half close 状态都能切换到 close 。但只要 read 被关闭，就会触发逻辑层的 CLOSE 消息。收到 CLOSE 消息后，只要可以写，逻辑层依然可以继续写数据，直到主动调用 socket.close ；如果不能继续写，无论是否调用 socket.close 底层的 fd 都会被彻底关闭。

注意：如果写被关闭，但是读没有关闭，处于 half close write 状态。这个时候可以继续读到数据，但一旦尝试写，会触发 error ，底层会强制关闭 fd （不再读数据）。

**Comment by sue602** [comment]
> 这个问题比较复杂。看看我在 halfclose 分支上刚提交的 patch 能否修复。

更到这个patch，因为该patch有修改  skynet.init rework, See #1322 ，会服务启动的问题问题。./skynet/lualib/skynet.lua:859: ./skynet/lualib/skynet.lua:330: attempt to yield across a C-call boundary 。

**Comment by cloudwu** [comment]
skynet.init 用法没有改变。只是 skynet.init 的调用交给了 https://github.com/cloudwu/skynet/blob/master/lualib/skynet/require.lua#L40

你错在哪里。

**Comment by sue602** [comment]
> skynet.init 用法没有改变。只是 skynet.init 的调用交给了 https://github.com/cloudwu/skynet/blob/master/lualib/skynet/require.lua#L40
> 
> 你错在哪里。


main.lua
skynet.init(function()
	skynet.newservice("service1")
	end)
-----------------------------------------
service1.lua
skynet.init(function()
	require("serviceCenterBase")
	end)
-----------------------------------------
serviceCenterBase.lua
文件头有require("skynet.multicast")

------------------------报错提示-------------------
2021-01-23 09:40:48 1611366048.2 [SNERR] :00000078 init service failed: attempt to yield across a C-call boundary
stack traceback:
	[C]: in function 'coroutine.yield'
	./skynet/lualib/skynet.lua:588: in upvalue 'yield_call'
	./skynet/lualib/skynet.lua:608: in function 'skynet.manager.call'
	./skynet/lualib/skynet.lua:870: in function 'skynet.manager.uniqueservice'
	./skynet/lualib/skynet/multicast.lua:89: in local 'f'
	./skynet/lualib/skynet/require.lua:30: in function 'skynet.require.require'
	(...tail calls...)
	[C]: in upvalue 'require'
	./skynet/lualib/skynet/require.lua:28: in function 'skynet.require.require'
	game/lib/serviceCenterBase.lua:12: in main chunk
	[C]: in upvalue 'require'
	./skynet/lualib/skynet/require.lua:28: in function 'skynet.require.require'
	game/service/log/service1Center.lua:1: in main chunk
	[C]: in upvalue 'require'
	./skynet/lualib/skynet/require.lua:28: in function 'skynet.require.require'
	(...tail calls...)
	game/service/log/service1.lua:14: in local 'f'
	./skynet/lualib/skynet/require.lua:40: in function 'skynet.require.init_all'
	./skynet/lualib/skynet.lua:935: in function <./skynet/lualib/skynet.lua:934>
	[C]: in function 'xpcall'
	./skynet/lualib/skynet.lua:938: in function 'skynet.manager.init_service'
	./skynet/lualib/skynet.lua:951: in upvalue 'f'
	./skynet/lualib/skynet.lua:253: in function <./skynet/lualib/skynet.lua:252>

**Comment by cloudwu** [comment]
我自己试过你的例子没有问题，你这里的问题可能是更复杂的情况。

不过我大概明白哪里有问题了，需要再改进一下 skynet.require 的实现。

**Comment by cloudwu** [comment]
我修了一下 skynet.require 。

前面的问题，在于多层调用 require 。虽然 skynet.require 在官方 require 之后再调用 init ，但是如果有多个层次，那么底层的 C require 就会试图做完两个初始化步骤再返回。即第一步运行 module 的 main function 第二步运行在 main function 中通过 skynet.init 注册的函数。

第二步是可以 yield 的，此时会处于 C require 函数中。

解决的办法是从 Lua 调用 module 的 main function ，也就是通过 package.searchpath(name, package.path) 找到 module 的源文件，通过 loadfile 加载，然后再 call main function 。

同时，这次的 patch 还解决了之前 #1322 没有解决的 bug 。

1. init 函数只能运行一次，如果 module 之前加载过，那么 init 函数也不应该运行。
2. 如果有多个 coroutine 同时 require 一个模块（现在的 require 可能在 init 中挂起），那么只应该有一个运行，其它应该等待。

@hongling0

**Comment by hongling0** [comment]
@cloudwu 
```lua
		local m = modfunc(name, filename)

		for _, f in ipairs(init_list) do
			f()
		end
```
这段代码我觉得需要处理失败的情况
- 唤醒其他等待的协程
- 清除`loading[name]`避免之后其他的代码`require`到这个文件导致卡住

**Comment by sue602** [comment]
> 我自己试过你的例子没有问题，你这里的问题可能是更复杂的情况。
> 
> 不过我大概明白哪里有问题了，需要再改进一下 skynet.require 的实现。

是的，代码有3层嵌套require

**Comment by cloudwu** [comment]
@sue602 如果 require 问题解决了，那么可以回头来看 socket 半关闭问题。那个我今天在 halfclose 分支上也有修改。

**Comment by sue602** [comment]
> @sue602 如果 require 问题解决了，那么可以回头来看 socket 半关闭问题。那个我今天在 halfclose 分支上也有修改。

好，等你修改后，我来测试下halfclose问题

**Comment by cloudwu** [comment]
require 暂时就到这里了，除非再发现问题。

今天 halfclose 分支增加了 netstate info 方便查询状态。

**Comment by cloudwu** [comment]
@sue602 是否有测试 halfclose 分支上的 socket 半关闭问题？

**Comment by fisher-an** [comment]
> error
确实有这样的问题，当客户端闪退时，可能只是关闭了读。此时服务器socket处于SOCKET_TYPE_HALFCLOSE
当服务器要发送数据时，会调用force_close强制关闭socket。但是底层只是打印了："socket-server: invalid socket"
却没有把socket关闭的消息推送给对应的服务。导致应用层无法知道客户端是否还在。
为了规避这个问题，目前我的做法是通过客户端定时心跳协议来确认客户端是存在，长时间收不到心跳就判断玩家掉线了。

**Comment by cloudwu** [comment]
现在主干的版本还有这个问题吗？

**Comment by fisher-an** [comment]
sorry，我的代码是1.22之前的版本。刚拉了最新代码，发现问题已修复。

**Comment by sue602** [comment]
> 现在主干的版本还有这个问题吗？

不好意思，因为版本和测试条件耽搁了这么久
经过这边的外网环境的相同测试，目前这个问题已经修复了。

**Comment by cloudwu** [comment]
这个修改之前引入了一个 bug ，会在某些条件下多发很多 close 消息。该问题已经在 https://github.com/cloudwu/skynet/commit/51a942d095b23ad6a871ccf24c62a62f4ba0a8ff 修复。
