### ISSUE TITLE
lua require 是改动了什么东西么。

### ISSUE THREAD

**Issue by Gowa2017** [cloudwu/skynet#1332]
我使用这个 https://github.com/zhaozg/lua-openssl/issues 。
正常用官版的 LUA  加载 .so 库没问题，skynet 就是 core dump。

然后我用 skynet/3rd/lua 进行编译，
包是加载好了，但是加载好的 openssl 库内的任何东西都是 Nil。

而如果我用官版LUA 去加载 这个 用 skynet/3rd/lua 编译的 so 库，也是 coredump。

补充一下，我的调用代码：

```lua
local skynet = require 'skynet'
local openssl = require 'openssl'

function dump(t)
    for key, value in pairs(t) do
        print(key,value)
    end
end
dump(openssl)
print(openssl.pkey)
print(openssl.erro)
-- local n = pkey.new()
-- skynet.error(n:export())
```

输出：
```
[:0100000a] LAUNCH snlua ssl
rand_load	function: 0x103324b60
engine	function: 0x103339450
lhash_load	function: 0x10333c6e0
list	function: 0x1033245c0
ec	table: 0x7fa63dd0e310
rand_write	function: 0x103324c90
random	function: 0x103324d80
hex	function: 0x103324630
pkcs12	table: 0x7fa63dd11000
asn1	table: 0x7fa63dc00250
base64	function: 0x103324790
print_errors	function: 0x103325050
digest	table: 0x7fa63dd032c0
bn	table: 0x7fa63dd14eb0
dh	table: 0x7fa63dd168d0
rand_status	function: 0x103324ac0
ocsp	table: 0x7fa63dd11790
pkey	table: 0x7fa63dd0d2d0
ssl	table: 0x7fa63dd13f70
dsa	table: 0x7fa63dd166f0
cms	table: 0x7fa63dd12b30
ts	table: 0x7fa63dd122b0
x509	table: 0x7fa63dd0e640
lhash_read	function: 0x10333c5d0
srp	table: 0x7fa63dd16c30
rand_add	function: 0x103324af0
FIPS_mode	function: 0x103325110
pkcs7	table: 0x7fa63dd10b20
hmac	table: 0x7fa63dd0c830
version	function: 0x1033244f0
rsa	table: 0x7fa63dd162b0
bio	table: 0x7fa63d837380
cipher	table: 0x7fa63dd0c730
error	function: 0x103324ef0
clear_error	function: 0x103324ed0
nil
nil
```

**Comment by cloudwu** [comment]
你用不同版本的 lua 编译加载后，一定会 coredump 。

至于为什么 pairs 可以迭代出，但是直接 index 返回 nil ，你可以在你的环境排查一下具体原因。既然 openssl 这个 table 已经返回，我相信和 require 无关。

skynet 的 require 使用的是这个带壳的版本：https://github.com/cloudwu/skynet/blob/master/lualib/skynet/require.lua

**Comment by Gowa2017** [comment]
> so 编译时引用的 lua 代码已经要和宿主 (此处是 skynet）编译时用的一致，否则行为是未确定的（有 coredump 可能） 。
> 
> 至于为什么 pairs 可以迭代出，但是直接 index 返回 nil ，你可以在你的环境排查一下具体原因。既然 openssl 这个 table 已经返回，我相信和 require 无关。
> 
> skynet 的 require 使用的是这个带壳的版本：https://github.com/cloudwu/skynet/blob/master/lualib/skynet/require.lua

感谢，找找原因。

**Comment by Gowa2017** [comment]
找到问题所在，lua-openssl 对 macos 上的支持，可能在编译设置上有点问题，我换 linux 环境，一切 OK。
