### ISSUE TITLE
http 发送post请求 设置超时10s,正常的数据返回也需要等待10s,请问我需要怎么处理

### ISSUE THREAD

**Issue by hujunlong** [cloudwu/skynet#1343]
我看代码  
1. httpc.lua  里面调用了 local fd = socket.connect(hostname, port, timeout)  
2. sockethelper.lua  sockethelper.connect(host, port, timeout) 里面使用了skynet.sleep. 这样只要设置了超时，及使正常情况下也不能提前返回。

请问我该如何实现 http请求的服务器没有返回，在超时的时候返回。如果有返回，就及时返回消息。

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/blob/master/lualib/http/sockethelper.lua#L83

skynet.wakeup 会唤醒 sleep , 你遇到了什么问题。

**Comment by hujunlong** [comment]
我代码比较老，应该是没有更新。下面为我本地的代码，没有wakeup导致都会等到超时才返回，感谢sir.

function sockethelper.connect(host, port, timeout)
	local fd
	if timeout then
		local drop_fd
		-- asynchronous connect
		skynet.fork(function()
			fd = socket.open(host, port)
			if drop_fd then
				-- sockethelper.connect already return, and raise socket_error
				socket.close(fd)
			end
		end)
		skynet.sleep(timeout)
		if not fd then
			-- not connect yet
			drop_fd = true
		end
	else
		-- block connect
		fd = socket.open(host, port)
	end
	if fd then
		return fd
	end
	error(socket_error)
end

**Comment by hujunlong** [comment]
更新成最新代码，我的问题解决了。感谢
