### ISSUE TITLE
socket close 死循环

### ISSUE THREAD

**Issue by fisher-an** [cloudwu/skynet#1346]
测试发现socket close 消息依然有概率出现了死循环。用gdb attach上去打断点发现
reading 是false。问题是无法定位到reading何时被置为false，但是确没有从epoll中移除，导致还是会频繁触发，执行到这里。
所以重新开了个issues，麻烦大神帮忙看看。

(gdb) p n
$22 = 0
(gdb) p *s
$23 = {opaque = 346, high = {head = 0x0, tail = 0x0}, low = {head = 0x0, tail = 0x0}, wb_size = 0, stat = {rtime = 28174, wtime = 28174, read = 2125, write = 12489}, sending = 1, fd = 54,
  id = 126, type = 6, protocol = 0 '\000', reading = false, writing = false, closing = true, udpconnecting = 0, warn_size = 0, p = {size = 64, udp_address = "@", '\000' <repeats 17 times>},
  dw_lock = {lock = {__val = false}}, dw_offset = 0, dw_buffer = 0x0, dw_size = 39}
(gdb) n
socket_server_poll (ss=0x7f33e0e00c40, result=result@entry=0x7f33dfbf66d0, more=more@entry=0x7f33dfbf66cc) at skynet-src/socket_server.c:1656
1656                                            type = forward_message_tcp(ss, s, &l, result);
(gdb)

Thread 4 "skynet" hit Breakpoint 7, forward_message_tcp (result=0x7f33dfbf66d0, l=0x7f33dfbf6650, s=0x7f33e0e06330, ss=0x7f33e0e00c40) at skynet-src/socket_server.c:1391
1391                            ATOM_STORE(&s->type , SOCKET_TYPE_HALFCLOSE_READ);
(gdb)
1392                            if (!s->closing) {
(gdb)
1396                            enable_read(ss, s, false);
(gdb)
1398                    return SOCKET_CLOSE;
(gdb)
socket_server_poll (ss=<optimized out>, result=result@entry=0x7f33dfbf66d0, more=more@entry=0x7f33dfbf66cc) at skynet-src/socket_server.c:1704
1704    }
(gdb) c
Continuing.

Thread 4 "skynet" hit Breakpoint 6, forward_message_tcp (result=0x7f33dfbf66d0, l=0x7f33dfbf6650, s=0x7f33e0e05568, ss=0x7f33e0e00c40) at skynet-src/socket_server.c:1386
1386            if (n==0) {
(gdb) p n
$24 = 256
(gdb) c
Continuing.

Thread 4 "skynet" hit Breakpoint 6, forward_message_tcp (result=0x7f33dfbf66d0, l=0x7f33dfbf6650, s=0x7f33e0e06330, ss=0x7f33e0e00c40) at skynet-src/socket_server.c:1386
1386            if (n==0) {
(gdb) p n
$25 = 0
(gdb) p 8s
Invalid number "8s".
(gdb) p *s
$26 = {opaque = 346, high = {head = 0x0, tail = 0x0}, low = {head = 0x0, tail = 0x0}, wb_size = 0, stat = {rtime = 28174, wtime = 28174, read = 2125, write = 12489}, sending = 1, fd = 54,
  id = 126, type = 6, protocol = 0 '\000', reading = false, writing = false, closing = true, udpconnecting = 0, warn_size = 0, p = {size = 64, udp_address = "@", '\000' <repeats 17 times>},
  dw_lock = {lock = {__val = false}}, dw_offset = 0, dw_buffer = 0x0, dw_size = 39}
(gdb) list
1381                            result->data = strerror(errno);
1382                            return SOCKET_ERR;
1383                    }
1384                    return -1;
1385            }
1386            if (n==0) {
1387                    FREE(buffer);
1388                    if (nomore_sending_data(s)) {
1389                            force_close(ss,s,l,result);
1390                    } else {
(gdb)
1391                            ATOM_STORE(&s->type , SOCKET_TYPE_HALFCLOSE_READ);
1392                            if (!s->closing) {
1393                                    shutdown(s->fd, SHUT_RD);
1394                                    s->closing = true;
1395                            }
1396                            enable_read(ss, s, false);
1397                    }
1398                    return SOCKET_CLOSE;
1399            }
1400

**Comment by cloudwu** [comment]
这里 enable_read 没有检查返回值。会不会是因为 epoll 的调用失败了？能否加个判断把失败的情况 log 下来看看？

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/blob/master/skynet-src/socket_epoll.h#L64

可能是 epoll 返回了 EPOLLHUP 而不是 EPOLLIN ?

**Comment by cloudwu** [comment]
看起来很可能还是 https://github.com/cloudwu/skynet/issues/644 类似的问题。但是之前没有处理完善半关闭状态，仅简单的在 epoll 移除了 fd 。现在可能需要更多的处理。

@fisher-an 能否做进一步的确认？

**Comment by cloudwu** [comment]
我尝试修了一下：

1. 让 epoll 的封装区分 eof 和 read 事件。之前只在解决 kqeueue 的问题时做了区分，见 #858 。而 epoll 将 IN 和 HUP 看成是同一事件，让 read 到 0 的时候一致做后续处理，见 #644 。
2. 鉴于 1 的修改，不能在主循环读到 eof 后就 force_close 了，因为 socket buffer 中可能还有没有读完的数据。所以，`forward_message_tcp` 函数中，需要一直读完数据。
3. 现在只要主动调用 close ，就一定会产生 SOCKET_CLOSE 消息（并只产生一次）。所以在主动调用 close 时，会设置 closing 标记，发送  SOCKET_CLOSE ；而在之后判断 socket 关闭的逻辑中，如果已有 closing 标记，就不再产生 SOCKET_CLOSE 。

目前 SOCKET_CLOSE 会在两种情况下产生：其一，主动调用了 close ；其二，read 到 0 ，且之前没有主动调用 close 。不会多次进入 read 0 的流程是基于这样的假设：当 socket 完全关闭时，epoll 会给一个 HUP 事件，主循环一定会处理这个事件，并 force_close fd ，这样就不再会处理这个 fd ；如果 socket 由对方半关闭（未完全关闭），那么 read 到 0 后，不应再触发 IN 事件。

kqueue 的行为是否正确，需要进一步确认。因为文档似乎暗示 kqueue 在对方关闭读（但没关闭写）时，也会产生 eof 事件。这可能导致写出队列在发送完之前就主动关闭了连接。@lvzixun

**Comment by fisher-an** [comment]
我简单修改了一下，把events 也传进来
forward_message_tcp(struct socket_server *ss, struct socket *s, struct socket_lock *l, struct socket_message * result, struct event *e)

sp_wait(int efd, struct event *e, int max) {
	struct epoll_event ev[max];
	int n = epoll_wait(efd , ev, max, -1);
	int i;
	for (i=0;i<n;i++) {
		e[i].s = ev[i].data.ptr;
		unsigned flag = ev[i].events;
		e[i].events = flag;
		e[i].write = (flag & EPOLLOUT) != 0;
		e[i].read = (flag & (EPOLLIN | EPOLLHUP)) != 0;
		e[i].error = (flag & EPOLLERR) != 0;
		e[i].eof = false;
	}

	return n;
}

1 发现确实是EPOLLHUP， 下面是gdb内容：

1386            if (n==0) {
(gdb) p s
$1 = (struct socket *) 0x7f4d264060a8
(gdb) p *s
$2 = {opaque = 346, high = {head = 0x0, tail = 0x0}, low = {head = 0x0, tail = 0x0}, wb_size = 0, stat = {rtime = 37828, wtime = 37828, read = 2263, write = 17123}, sending = 1, fd = 44,
  id = 129, type = 6, protocol = 0 '\000', reading = false, writing = false, closing = true, udpconnecting = 0, warn_size = 0, p = {size = 64, udp_address = "@", '\000' <repeats 17 times>},
  dw_lock = {lock = {__val = false}}, dw_offset = 0, dw_buffer = 0x0, dw_size = 9}
(gdb) p n
$3 = 0
(gdb) p *e
$4 = {s = 0x7f4d264060a8, read = true, write = false, error = true, eof = false, events = 24}
(gdb) list
1381                            result->data = strerror(errno);
1382                            return SOCKET_ERR;
1383                    }
1384                    return -1;
1385            }
1386            if (n==0) {
1387                    FREE(buffer);
1388                    skynet_error(NULL, "_socket_close opaque: %d, reading: %d, writing: %d, id: %d, fd: %d, type: %d, events: %d", s->opaque, s->reading, s->writing, s->id, s->fd, s->type, e->events);
1389                    if (nomore_sending_data(s)) {
1390                            force_close(ss,s,l,result);
(gdb) c
Continuing.

Thread 4 "skynet" hit Breakpoint 1, forward_message_tcp (e=0x7f4d26400800, result=0x7f4d251f66d0, l=0x7f4d251f6650, s=0x7f4d264060a8, ss=0x7f4d264007c0) at skynet-src/socket_server.c:1386
1386            if (n==0) {
(gdb) p n
$5 = 0
(gdb) p *s
$6 = {opaque = 346, high = {head = 0x0, tail = 0x0}, low = {head = 0x0, tail = 0x0}, wb_size = 0, stat = {rtime = 37828, wtime = 37828, read = 2263, write = 17123}, sending = 1, fd = 44,
  id = 129, type = 6, protocol = 0 '\000', reading = false, writing = false, closing = true, udpconnecting = 0, warn_size = 0, p = {size = 64, udp_address = "@", '\000' <repeats 17 times>},
  dw_lock = {lock = {__val = false}}, dw_offset = 0, dw_buffer = 0x0, dw_size = 9}
(gdb) p *e
$7 = {s = 0x7f4d264060a8, read = true, write = false, error = true, eof = false, events = 24}
(gdb)

events 是24（0x18 = EPOLLERR |  EPOLLHUP）

以下是日志文件：
 * _socket_close opaque: 346, reading: 1, writing: 0, id: 129, fd: 44, type: 5, events: 1
[2021-02-24 11:23:24.294][0000015a]: ERROR_LUA file: ...ard/test/normal/data/game/service/player/playeragent.lua line: 24
 * socket_close 129 17596481011714 宦炳逸
[2021-02-24 11:23:24.303][00000000]:
 * _socket_close opaque: 346, reading: 0, writing: 0, id: 129, fd: 44, type: 6, events: 24
[2021-02-24 11:23:24.303][00000000]:
 * _socket_close opaque: 346, reading: 0, writing: 0, id: 129, fd: 44, type: 6, events: 24
[2021-02-24 11:23:24.303][00000000]:
 * _socket_close opaque: 346, reading: 0, writing: 0, id: 129, fd: 44, type: 6, events: 24
[2021-02-24 11:23:24.303][00000000]:
 * _socket_close opaque: 346, reading: 0, writing: 0, id: 129, fd: 44, type: 6, events: 24
[2021-02-24 11:23:24.303][00000000]:
 * _socket_close opaque: 346, reading: 0, writing: 0, id: 129, fd: 44, type: 6, events: 24
[2021-02-24 11:23:24.303][00000000]:
 * _socket_close opaque: 346, reading: 0, writing: 0, id: 129, fd: 44, type: 6, events: 24
[2021-02-24 11:23:24.303][00000000]:
 * _socket_close opaque: 346, reading: 0, writing: 0, id: 129, fd: 44, type: 6, events: 24
[2021-02-24 11:23:24.303][00000000]:
 * _socket_close opaque: 346, reading: 0, writing: 0, id: 129, fd: 44, type: 6, events: 24
[2021-02-24 11:23:24.303][00000000]:
 * _socket_close opaque: 346, reading: 0, writing: 0, id: 129, fd: 44, type: 6, events: 24
[2021-02-24 11:23:24.303][00000000]:
 * _socket_close opaque: 346, reading: 0, writing: 0, id: 129, fd: 44, type: 6, events: 24
[2021-02-24 11:23:24.303][00000000]:
 * _socket_close opaque: 346, reading: 0, writing: 0, id: 129, fd: 44, type: 6, events: 24
首次执行到这里，reading是1（true）,events是1,之后就一直是24了。

我因为这里既然做了HALFCLOSE_READ，HALFCLOSE_WRITE，那么是否应该改events传回来，对应处理
EPOLLIN | EPOLLRDHUP | EPOLLHUP

**Comment by fisher-an** [comment]
目前该问题只能在debian系统复现，ubuntu无法复现。是否与系统内核有关？
还有这里的 enable_read(ss, s, false); 是否应该提到shutdown(s->fd, SHUT_RD); 之前？

**Comment by cloudwu** [comment]
今天的修改后还有问题？

我认为 epoll 的调用次序不应该和 shutdown 有关。

**Comment by fisher-an** [comment]
@cloudwu 没问题了。

**Comment by fisher-an** [comment]
又遇到一个新问题。ubuntu下客户端强制关闭客户端 epoll events返回0x15（EPOLLIN | EPOLLOUT | EPOLLHUP）
导致了 forward_message_tcp函数中执行到以下代码
if (n==0) {
		if (nomore_sending_data(s)) {
			force_close(ss,s,l,result); 
		} else {
			result->opaque = s->opaque;
			result->id = s->id;
			result->ud = 0;
			result->data = NULL;
		}
		if (s->closing) {
			// Already returned SOCKET_CLOSE
			return -1;
		}
		return SOCKET_CLOSE;
	}
由于还有数据要发送。并不会调用到force_close,直接返回了socket_close
上层函数 socket_server_poll 判断type ！= -1 直接return。
就无法执行到下面的代码。导致死循环。

所以是否能够修改socket_server_poll 的events处理顺序。
先处理if (e->error)， if(e->eof)，if(e->write) ； 再处理 if (e->read)。

---------------------------------------------------------------------------------------------
重现方式很简单，开大量机器人，挤满cpu后，关闭客户端。保证if (nomore_sending_data(s))为false

**Comment by cloudwu** [comment]
为什么是死循环？socket close 发送一次后，之后应该不会再发送了。业务层收到 close 然后主动关闭。最后就结束了。

死循环指什么。

**Comment by cloudwu** [comment]
我明白了，这里应该走的是半关 RD 的流程，也就是 https://github.com/cloudwu/skynet/blob/master/skynet-src/socket_server.c#L1112-L1120 这一段（应该提取出来单列一个和 force_close 平级的函数）

需要关闭 epoll 中的 IN flag 并 shutdown SHUT_RD ，让 socket 处于 HALFCLOSE_READ 状态。

ps. 不可以简单的调整消息的处理次序，就会回到了最初的原点（也就是在处理这些半关闭流程之前的版本），最终会变成简单的断开连接，会丢掉一些没发完的数据。而最近这次的一系列的修改都是为了可以妥善的处理半关闭流程中所有没发送完毕数据的问题。

**Comment by fisher-an** [comment]
由于客户端关闭了。socket，sp_wait 取出的events是0x15（关闭socket为何会是这个数，还没搞清楚。）, 也就是依然会先执行forward_message_tcp。
但是读到数据长度确实0
int n = read_socket(s, &buf); n=0，
此时假如还有数据未发送时无法执行到， 里面的force_close
if (nomore_sending_data(s))
{
	force_close(ss, s, l, result);
}
这里就会return SOCKET_CLOSE;
而上层函数socket_server_poll 是最先处理 read事件。这里直接return了。
if (e->read)
			{
				int type;
				if (s->protocol == PROTOCOL_TCP)
				{
					type = forward_message_tcp(ss, s, &l, result);
				}
				else
				{
					type = forward_message_udp(ss, s, &l, result);
					if (type == SOCKET_UDP)
					{
						// try read again
						--ss->event_index;
						return SOCKET_UDP;
					}
				}
				if (e->write && type != SOCKET_CLOSE && type != SOCKET_ERR)
				{
					// Try to dispatch write message next step if write flag set.
					e->read = false;
					--ss->event_index;
				}
				if (type == -1)
					break;
				return type; // 直接返回socket_close !!!!!!!!!
			}

也就是上次服务会收到socket_close消息，认为这个fd已关闭。
但是epoll_wait 默认是水平触发，也就是我们没有把fd移除，会一直触发并且events都是15，会一直执行到以上所说的：return SOCKET_CLOSE;(目前测试结果确实是这样的，为何关闭socket会触发read? 尚不清楚)
除非上层应该用收到socket_close消息还主动调用shutdown把这个fd移除。

**Comment by cloudwu** [comment]
1. 这里要解决发送多个 SOCKET_CLOSE 消息的问题。这个我明天改一下。
2. 如果业务层收到 SOCKET_CLOSE 有责任调用 socket.close 主动关闭 socket 。

这一系列的修改是主要是为了解决以下问题：

在 skynet 做 web server 时，某些浏览器有这样的行为：

1. 发送一个 http request ，但在发送完请求后，就立刻 shutdown  SHUT_WR 。但是它并没有关闭自己的读。
2. 它会等着 web server 的 response 包。

如果简单粗暴的在 read 返回 0 ，也就是收到了 FIN 包后，就彻底断开连接，业务层的 response 包往往没有机会发送完。也就是说，业务层在收到了 CLOSE 消息后，只能确认是 client 关闭了上行数据，但不等于不接受下行数据。

这个时候，server 还有机会调用若干次 socket.write 写出下行数据，最后再调用 socket.close 关闭整个信道。

**Comment by cloudwu** [comment]
我认为这里的修改方案是，在 read 0 后，调用

ATOM_STORE(&s->type , SOCKET_TYPE_HALFCLOSE_READ);
enable_read(ss,s,false);
shutdown(s->fd, SHUT_RD);

也就是把 socket 设为 halfclose_read 状态。但不应该设置 closing = 1 ，这个标记表示业务层主动关闭 socket ，但底层还有未发送给完的数据。

因为 enable_read  通知了 epoll ，所以不应该再有  EPOLLIN 消息。为了更健壮，可以在后续的 read 处理中多判断 SOCKET_TYPE_HALFCLOSE_READ 这个状态，表示不再读取新的数据。

**Comment by cloudwu** [comment]
@fisher-an 我按上面的思路做了修改，麻烦 review 一下。修改后的流程和我后面的回帖描述的一致。

**Comment by cloudwu** [comment]
注意，目前的实现中，即使 read 到 0 ，也没有待发的数据。只要还没有主动关闭 fd ，也不会 force_close ，而是  close_read 
 。 https://github.com/cloudwu/skynet/blob/master/skynet-src/socket_server.c#L1470

这样，业务层在收到 FIN (read 0) 后，依旧有机会发送数据，直到主动调用 socket.close()

**Comment by cloudwu** [comment]
今天做了一次新的提交：目前，SOCKET_CLOSE 严格只在两种情况之一发出，且一定只发出一次（无论 epoll、kqueue） 是怎样的行为）。

1. 主动调用了 socket.close 。fd 在有未发完的数据时会进入 closing 状态，如果无数据待发就直接关闭。无论如何都会立刻产生 SOCKET_CLOSE 。
2. 收到了对端的关闭信号。通常是  recv 0 或收到 EPOLLHUP。

如果是第二种情况，fd 依旧可写。之后的 socket.write 有可能失败 (EPIPE) ，那么会收到 SOCKET_ERR ，代表对端拒绝接收。

**Comment by fisher-an** [comment]
按之前的方式测了一遍，没有再出现大量触发SOCKET_CLOSE的问题了。
