### ISSUE TITLE
Socket close generates signal SIGSEGV

### ISSUE THREAD

**Issue by srdgame** [cloudwu/skynet#1347]
我们最近使用了Lua实现的MQTT库，在增加超时检测后，现场机出现调用socket.close后出现服务被挂起的现象（只是socket.close没有成功返回)，当服务被手工重启而再次调用socket.close，会出现assert(not s.closing)的异常。

这几天用开发机测试，同样是MQTT心跳超时，现象是socket.close导致进程崩溃，而无法重现现场机的被挂起的现象。 现场机是openwrt/musl/armv7,禁用了jemalloc。开发机是Debian testing X64

测试版本从3号的版本，到最新22号的版本都能重现下面的崩溃问题：

![image](https://user-images.githubusercontent.com/54447/108941100-7200fb80-768f-11eb-8732-8d067b5b37f6.png)

**Comment by srdgame** [comment]
问题现场还在保留中，如需要什么gdb信息，我可以提供。

**Comment by cloudwu** [comment]
今天在尝试修可能相关的问题：细节我写在了 https://github.com/cloudwu/skynet/issues/1346 。

**Comment by cloudwu** [comment]
后面那个崩溃的问题可能是最近的修改引起的，因为在非 force_close 而产生 SOCKET_CLOSE 消息时，没有正确的填写 result 结构，导致了 buf 指针为设置为 NULL 。这样在 forward_message 那里就会 free 一个无效的指针。

我刚才提交的 patch 修复了这个问题。

至于前一个 socket.close 挂起问题，我猜想和半关闭的处理不完善有关，可能这几天的修改能解决。

**Comment by rangercyh** [comment]
> 我们最近使用了Lua实现的MQTT库，在增加超时检测后，现场机出现调用socket.close后出现服务被挂起的现象（只是socket.close没有成功返回)，当服务被手工重启而再次调用socket.close，会出现assert(not s.closing)的异常。
> 
> 这几天用开发机测试，同样是MQTT心跳超时，现象是socket.close导致进程崩溃，而无法重现现场机的被挂起的现象。 现场机是openwrt/musl/armv7,禁用了jemalloc。开发机是Debian testing X64
> 
> 测试版本从3号的版本，到最新22号的版本都能重现下面的崩溃问题：
> 
> ![image](https://user-images.githubusercontent.com/54447/108941100-7200fb80-768f-11eb-8732-8d067b5b37f6.png)

我昨天遇到个问题，clusteragent不知道为什么突然就挂起了。。。现场被破坏了当时没机会看是出了什么问题了，不知道跟这个有没有关系

**Comment by srdgame** [comment]
@cloudwu Testing with your today commit, will let you know about the result.

**Comment by srdgame** [comment]
@cloudwu with latest commits, there is no more issue on close, but the write failed.


![image](https://user-images.githubusercontent.com/54447/109445564-d4387280-7a7a-11eb-95b5-29204890f741.png)

**Comment by srdgame** [comment]
![image](https://user-images.githubusercontent.com/54447/109445607-e87c6f80-7a7a-11eb-9d46-4d56bdfdfc18.png)

**Comment by cloudwu** [comment]
我今天做了一次新的提交： https://github.com/cloudwu/skynet/commit/0d949678b95ef88f4bdfe455c1fe7cf84d02f018

如果主动关闭 fd 在前，就忽略后面的底层 write error 。

但是，在收到 SOCKET_CLOSE 后，是允许继续向 fd 写出的。这是 tcp 协议允许的。即：收到 SOCKET_CLOSE 可能是 remote 发出了 FIN ，但是既然可能在等待接收。只有自身调用 close （发出  FIN），才真正不再写出数据。

但是，写 fd 有可能碰到 remote 拒绝（remote 自己关闭了读，返回了 RST），这个时候会让 write 产生 EPIPE / SIGPIPE 。

目前，如果是自己主动调用 socket.close ，那么底层会忽略 write 错误，直接扔掉需要写出的数据；如果还没有调用 socket.close ，那么即使在收到 SOCKET_CLOSE 后，还是可以继续写（之前底层未写完的数据也会继续尝试写），但有可能收到 SOCKET_ERR 。

https://github.com/cloudwu/skynet/issues/1346 中有其它一些讨论。
