### ISSUE TITLE
require文件中包含sharetable.query，会报错

### ISSUE THREAD

**Issue by ZhouJiaZhi** [cloudwu/skynet#1350]

**Comment by ZhouJiaZhi** [comment]
lua loader error : attempt to yield from outside a coroutine
stack traceback:
	[C]: in function 'coroutine.yield'
	./skynet/lualib/skynet.lua:588: in upvalue 'yield_call'
	./skynet/lualib/skynet.lua:608: in function 'skynet.manager.call'
	./skynet/lualib/skynet.lua:870: in function 'skynet.manager.uniqueservice'
	./skynet/lualib/skynet/service.lua:8: in upvalue 'get_provider'
	./skynet/lualib/skynet/service.lua:19: in function 'skynet.service.new'
	./skynet/lualib/skynet/sharetable.lua:163: in metamethod 'index'
	./skynet/lualib/skynet/sharetable.lua:198: in function 'skynet.sharetable.query'
	src/lualib/server/helper/api_helper.lua:3: in main chunk
	[C]: in upvalue 'require'
	./skynet/lualib/skynet/require.lua:31: in function 'require'


	1. lua_share_table.lua
	local lua_share_table = {}
	return lua_share_table


	2. main.lua

	local sharetable = require 'skynet.sharetable'
	local lua_share_table = require 'lua_share_table'
	skynet.start(function()
		sharetable.loadtable('lua_share_table', lua_share_table)
	end)

	3. util.lua

	local sharetable = require 'skynet.sharetable'
	local lua_share_table = sharetable.query('lua_share_table')
	
	local util = {}
	return util

	4. test.lua

	local util = require 'util'
	skynet.start(function()
	end)

**Comment by cloudwu** [comment]
目前没有办法这样用。因为按现在的设计，只有在 skynet.start 之后才可以对外发请求。

但通常这种问题都容易解决：你可以让服务的主文件只有一行 skynet.start, 其主函数只有一行 require 真正的主文件模块。

**Comment by cloudwu** [comment]
另外，在文档中也提到，模块的主函数中用到任何 skynet 阻塞调用，都应该放到 skynet.init 中。

local lua_share_table = sharetable.query('lua_share_table')

这行裸在外面是不正确的用法。

**Comment by ZhouJiaZhi** [comment]
明白了，感谢
