### ISSUE TITLE
macox 编译报错无任何修改

### ISSUE THREAD

**Issue by Coco10086** [cloudwu/skynet#1352]
cc -g -O2 -Wall -I3rd/lua  -o skynet skynet-src/skynet_main.c skynet-src/skynet_handle.c skynet-src/skynet_module.c skynet-src/skynet_mq.c skynet-src/skynet_server.c skynet-src/skynet_start.c skynet-src/skynet_timer.c skynet-src/skynet_error.c skynet-src/skynet_harbor.c skynet-src/skynet_env.c skynet-src/skynet_monitor.c skynet-src/skynet_socket.c skynet-src/socket_server.c skynet-src/malloc_hook.c skynet-src/skynet_daemon.c skynet-src/skynet_log.c 3rd/lua/liblua.a -Iskynet-src -I3rd/jemalloc/include/jemalloc   -lpthread -lm -ldl -DNOUSE_JEMALLOC
skynet-src/skynet_timer.c:230:2: warning: implicit declaration of function
      'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
        clock_gettime(CLOCK_REALTIME, &ti);
        ^
**skynet-src/skynet_timer.c:230:16: error: use of undeclared identifier**
      'CLOCK_REALTIME'
        clock_gettime(CLOCK_REALTIME, &ti);
                      ^
**skynet-src/skynet_timer.c:239:16: error: use of undeclared identifier**
      'CLOCK_MONOTONIC'
        clock_gettime(CLOCK_MONOTONIC, &ti);
                      ^
**skynet-src/skynet_timer.c:289:16: error: use of undeclared identifier**
      'CLOCK_THREAD_CPUTIME_ID'
        clock_gettime(CLOCK_THREAD_CPUTIME_ID, &ti);
                      ^
1 warning and 3 errors generated.
make[1]: *** [skynet] Error

**Comment by cloudfreexiao** [comment]
https://github.com/cloudwu/skynet/commit/77c965e9e849897f83f1ca34cad6d1d9db34542e

**Comment by cloudwu** [comment]
https://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x

需要 Sierra 10.12 之后的 Mac OS X 。
