### ISSUE TITLE
[Redis] Protocol error: invalid bulk length

### ISSUE THREAD

**Issue by zaxbbun** [cloudwu/skynet#1367]
https://redis.io/topics/protocol

RESP can serialize different data types like integers, strings, arrays. There is also a specific type for errors. **Requests are sent from the client to the Redis server as arrays of strings representing the arguments of the command to execute**. Redis replies with a command-specific data type.

https://github.com/redis/redis/blob/725762c48d6465f65f1b5ead4126a72674ce6a83/src/networking.c#L1879

```
            ok = string2ll(c->querybuf+c->qb_pos+1,newline-(c->querybuf+c->qb_pos+1),&ll);
            if (!ok || ll < 0 ||
                (!(c->flags & CLIENT_MASTER) && ll > server.proto_max_bulk_len)) {
                addReplyError(c,"Protocol error: invalid bulk length");
                setProtocolError("invalid bulk length",c);
                return C_ERR;
            }
```
Null elements in Arrays is not allowed to be send from client. (**ll < 0**) and break

**Comment by zaxbbun** [comment]
db:hmset('test', 'a', nil, 'b', 'b')
response: ERR Protocol error: invalid bulk length

**Comment by zaxbbun** [comment]
```
✗ telnet 127.0.0.1 6379
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
*6
$5   
hmset
$4   
list
$1
a
$1
a
$1
b
$-1
-ERR Protocol error: invalid bulk length
Connection closed by foreign host.

```

**Comment by cloudwu** [comment]
The limit of "Null elements in Arrays" is not documented (Only in implementation).

I think Null is a kind of string.

> "$-1\r\n"
This is called a Null Bulk String.

For the issue of "hmset" , my opinion is that do not use **hmset** to delete keys , use **hdel** instead.

**Comment by zaxbbun** [comment]
如果客户端发送了 **Null Bulk String ($-1\r\n)**， redis服务器在接受数据时会经过下面的函数
https://github.com/redis/redis/blob/725762c48d6465f65f1b5ead4126a72674ce6a83/src/networking.c#L1879
```
            ok = string2ll(c->querybuf+c->qb_pos+1,newline-(c->querybuf+c->qb_pos+1),&ll);
            if (!ok || ll < 0 ||
                (!(c->flags & CLIENT_MASTER) && ll > server.proto_max_bulk_len)) {
                addReplyError(c,"Protocol error: invalid bulk length");
                setProtocolError("invalid bulk length",c);
                return C_ERR;
            }
```

此时, ok = 1; ll = -1;  会直接返回Protocol error: invalid bulk length
可见Null Bulk String不能由客户端发送给服务器，就像redis不接受RESP Integers一样

---
https://redis.io/topics/protocol#null-elements-in-arrays

Null elements in Arrays
Single elements of an Array may be Null. **This is used in Redis replies** in order to signal that these elements are missing and not 
empty strings. This can happen with the SORT command when used with the GET pattern option when the specified key is 
missing. Example of an Array reply containing a Null element:

Null elements  是由服务器回复客户端


对#1340 #1341的提交 6d941a6de170508 不符合规定

**Comment by zaxbbun** [comment]
> The limit of "Null elements in Arrays" is not documented (Only in implementation).
> 
> I think Null is a kind of **Bulk Strings**. https://redis.io/topics/protocol#resp-bulk-strings
> 
> > "$-1\r\n"
> > This is called a Null Bulk String.
> 
> For the issue of "hmset" , my opinion is that do not use **hmset** to delete keys , use **hdel** instead.

如果客户端发送了 **Null Bulk String ($-1\r\n)**， redis服务器在接受数据时会经过下面的函数
https://github.com/redis/redis/blob/725762c48d6465f65f1b5ead4126a72674ce6a83/src/networking.c#L1879
```
            ok = string2ll(c->querybuf+c->qb_pos+1,newline-(c->querybuf+c->qb_pos+1),&ll);
            if (!ok || ll < 0 ||
                (!(c->flags & CLIENT_MASTER) && ll > server.proto_max_bulk_len)) {
                addReplyError(c,"Protocol error: invalid bulk length");
                setProtocolError("invalid bulk length",c);
                return C_ERR;
            }
```

此时, ok = 1; ll = -1;  会直接返回Protocol error: invalid bulk length
可见Null Bulk String不能由客户端发送给服务器，就像redis不接受RESP Integers一样

---
https://redis.io/topics/protocol#null-elements-in-arrays

Null elements in Arrays
Single elements of an Array may be Null. **This is used in Redis replies** in order to signal that these elements are missing and not 
empty strings. This can happen with the SORT command when used with the GET pattern option when the specified key is 
missing. Example of an Array reply containing a Null element:

Null elements  是由服务器回复客户端


对#1340 #1341 的提交 6d941a6de170508 不符合规定，会导致Protocol error: invalid bulk length
@cloudwu

**Comment by cloudwu** [comment]
我认为文档只是说明它的用途，而没有说只有这个用途。只是实现不接受而已。

但 Null Bulk String 的确是一种  RESP Bulk Strings 。且 **A client sends the Redis server a RESP Array consisting of just Bulk Strings.** 我认为只要是由 Bulk Strings 组成的 Array 就是符合文档的。

至于实现，我认为是 redis 目前包括 hmset 在内的指令都不接收 Null Bulk String 。

至于  https://github.com/cloudwu/skynet/commit/6d941a6de170508f9e45189e2763936338c2b99b 主要解决的是阻塞不返回的问题，并没有阻止用不正确的形式向 redis server 发送请求。

**Comment by cloudwu** [comment]
我看了一下 phpredis 的处理 https://github.com/phpredis/phpredis#hmset
> Non-string values are converted to string, using the standard (string) cast. NULL values are stored as empty strings.
它把 NULL 转换为了 empty string 。

但我认为，如果这里使用者应该明确使用 "" 来表示 empty string ，隐式转换不太好。
