### ISSUE TITLE
lua5.4.3 cannot run Test

### ISSUE THREAD

**Issue by ZeroJsus** [cloudwu/skynet#1370]
I cloned the code and executed to the Test link according to the official README, but the server reported an error and failed to start.

![image](https://user-images.githubusercontent.com/19191127/113143820-31346d80-925f-11eb-8a49-9011c92d14c3.png)

My Lua version is 5.4.3, I hope you can get help, thank you!

**Comment by ZeroJsus** [comment]
run `./skynet examples/config` in my skynet folder

**Comment by cloudwu** [comment]
DO NOT post screenshot pictures, use formatted markdown documents instead.

**Comment by ZeroJsus** [comment]
> DO NOT post screenshot pictures, use formatted markdown documents instead.

this is my terminal output when i run `./skynet examples/config`

`[skynet] ./skynet examples/config                                              20:27:05  ☁  master ☀
[:01000002] LAUNCH snlua bootstrap
[:01000003] LAUNCH snlua launcher
[:01000004] LAUNCH snlua cmaster
[:01000004] master listen socket 0.0.0.0:2013
[:01000005] LAUNCH snlua cslave
[:01000005] slave connect to master 127.0.0.1:2013
[:01000006] LAUNCH harbor 1 16777221
[:01000004] connect from 127.0.0.1:57923 4
[:01000004] Harbor 1 (fd=4) report 127.0.0.1:2526
[:01000005] Waiting for 0 harbors
[:01000005] Shakehand ready
[:01000007] LAUNCH snlua datacenterd
[:01000008] LAUNCH snlua service_mgr
[:01000009] LAUNCH snlua main
[:01000009] Server start
[:0100000a] LAUNCH snlua protoloader
[:0100000b] LAUNCH snlua console
[:0100000c] LAUNCH snlua debug_console 8000
[:0100000c] Start debug console at 127.0.0.1:8000
[:0100000d] LAUNCH snlua simpledb
[:0100000e] LAUNCH snlua watchdog
[:0100000f] LAUNCH snlua gate
[:0100000f] Listen on 0.0.0.0:8888
[:0100000f] lua call [100000e to :100000f : 3 msgsz = 36] error : ./lualib/skynet.lua:859: ./lualib/skynet.lua:330: ./lualib/snax/gateserver.lua:44: Listen error
stack traceback:
	[C]: in function 'skynet.socketdriver.listen'
	./lualib/snax/gateserver.lua:44: in local 'f'
	./lualib/snax/gateserver.lua:146: in upvalue 'f'
	./lualib/skynet.lua:280: in function <./lualib/skynet.lua:252>
stack traceback:
	[C]: in function 'assert'
	./lualib/skynet.lua:859: in function 'skynet.dispatch_message'
[:0100000e] lua call [100000f to :100000e : 3 msgsz = 0] error : ./lualib/skynet.lua:859: ./lualib/skynet.lua:330: ./lualib/skynet.lua:591: call failed
stack traceback:
	[C]: in function 'error'
	./lualib/skynet.lua:591: in upvalue 'yield_call'
	./lualib/skynet.lua:608: in function 'skynet.call'
	./examples/watchdog.lua:43: in local 'f'
	./examples/watchdog.lua:58: in upvalue 'f'
	./lualib/skynet.lua:280: in function <./lualib/skynet.lua:252>
stack traceback:
	[C]: in function 'assert'
	./lu[:01000009] init service failed: ./lualib/skynet.lua:591: call failed
stack traceback:
	[C]: in function 'error'
	./lualib/skynet.lua:591: in upvalue 'yield_call'
	./lualib/skynet.lua:608: in function 'skynet.call'
	./examples/main.lua:15: in upvalue 'start'
	./lualib/skynet.lua:936: in function <./lualib/skynet.lua:934>
	[C]: in function 'xpcall'
	./lualib/skynet.lua:938: in function 'skynet.init_service'
	./lualib/skynet.lua:951: in upvalue 'f'
	./lualib/skynet.lua:253: in function <./lualib/skynet.lua:252>
[:01000009] KILL self
[:01000002] KILL self
`

**Comment by ZeroJsus** [comment]
[skynet] ./skynet examples/config                                              20:27:05  ☁  master ☀
[:01000002] LAUNCH snlua bootstrap
[:01000003] LAUNCH snlua launcher
[:01000004] LAUNCH snlua cmaster
[:01000004] master listen socket 0.0.0.0:2013
[:01000005] LAUNCH snlua cslave
[:01000005] slave connect to master 127.0.0.1:2013
[:01000006] LAUNCH harbor 1 16777221
[:01000004] connect from 127.0.0.1:57923 4
[:01000004] Harbor 1 (fd=4) report 127.0.0.1:2526
[:01000005] Waiting for 0 harbors
[:01000005] Shakehand ready
[:01000007] LAUNCH snlua datacenterd
[:01000008] LAUNCH snlua service_mgr
[:01000009] LAUNCH snlua main
[:01000009] Server start
[:0100000a] LAUNCH snlua protoloader
[:0100000b] LAUNCH snlua console
[:0100000c] LAUNCH snlua debug_console 8000
[:0100000c] Start debug console at 127.0.0.1:8000
[:0100000d] LAUNCH snlua simpledb
[:0100000e] LAUNCH snlua watchdog
[:0100000f] LAUNCH snlua gate
[:0100000f] Listen on 0.0.0.0:8888
[:0100000f] lua call [100000e to :100000f : 3 msgsz = 36] error : ./lualib/skynet.lua:859: ./lualib/skynet.lua:330: ./lualib/snax/gateserver.lua:44: Listen error
stack traceback:
	[C]: in function 'skynet.socketdriver.listen'
	./lualib/snax/gateserver.lua:44: in local 'f'
	./lualib/snax/gateserver.lua:146: in upvalue 'f'
	./lualib/skynet.lua:280: in function <./lualib/skynet.lua:252>
stack traceback:
	[C]: in function 'assert'
	./lualib/skynet.lua:859: in function 'skynet.dispatch_message'
[:0100000e] lua call [100000f to :100000e : 3 msgsz = 0] error : ./lualib/skynet.lua:859: ./lualib/skynet.lua:330: ./lualib/skynet.lua:591: call failed
stack traceback:
	[C]: in function 'error'
	./lualib/skynet.lua:591: in upvalue 'yield_call'
	./lualib/skynet.lua:608: in function 'skynet.call'
	./examples/watchdog.lua:43: in local 'f'
	./examples/watchdog.lua:58: in upvalue 'f'
	./lualib/skynet.lua:280: in function <./lualib/skynet.lua:252>
stack traceback:
	[C]: in function 'assert'
	./lu[:01000009] init service failed: ./lualib/skynet.lua:591: call failed
stack traceback:
	[C]: in function 'error'
	./lualib/skynet.lua:591: in upvalue 'yield_call'
	./lualib/skynet.lua:608: in function 'skynet.call'
	./examples/main.lua:15: in upvalue 'start'
	./lualib/skynet.lua:936: in function <./lualib/skynet.lua:934>
	[C]: in function 'xpcall'
	./lualib/skynet.lua:938: in function 'skynet.init_service'
	./lualib/skynet.lua:951: in upvalue 'f'
	./lualib/skynet.lua:253: in function <./lualib/skynet.lua:252>
[:01000009] KILL self
[:01000002] KILL self

**Comment by cloudwu** [comment]
```
./lualib/snax/gateserver.lua:44: Listen error
```

Check if your port 8888 is available.

**Comment by ZeroJsus** [comment]
> ```
> [:0100000f] Listen on 0.0.0.0:8888
> [:0100000f] lua call [100000e to :100000f : 3 msgsz = 36] error : ./lualib/skynet.lua:859: ./lualib/skynet.lua:330: ./lualib/snax/gateserver.lua:44: Listen error
> ```
> 
> Check if your port 8888 is available.

ok That's the question
