### ISSUE TITLE
服务B call 服务A，如果服务A被kill，服务B不会返回

### ISSUE THREAD

**Issue by ZhouJiaZhi** [cloudwu/skynet#1371]
**main.lua**
```lua
local skynet = require "skynet.manager"

skynet.start(function()
    skynet.newservice("debug_console", 8000)
    local a = skynet.newservice("a")
    local b = skynet.newservice("b")
    skynet.send(b, "lua", "start")
    skynet.sleep(450)
    skynet.kill(a)
    --skynet.call(a, "lua", "exit")
end)
```

**a.lua**
```lua
local skynet = require "skynet.manager"
local CMD = {}

function CMD.ping(arg)
    skynet.sleep(300)
    return arg
end

function CMD.exit()
    skynet.exit()
end

skynet.start(function()
    skynet.register(".a")
    skynet.dispatch("lua", function(_, _, command, ...)
        local f = CMD[command]
        skynet.ret(skynet.pack(f(...)))
    end)
end)
```

**b.lua**
```lua
local skynet = require "skynet.manager"
local CMD = {}
local a = skynet.localname('.a')
function CMD.start()
    skynet.fork(function()
        while (true) do
            print('wait for response')
            skynet.call(a, "lua", "ping", "hello")
            print('ok')
        end
    end)
end

skynet.start(function()
    skynet.register(".b")
    skynet.dispatch("lua", function(_, _, command, ...)
        local f = CMD[command]
        skynet.ret(skynet.pack(f(...)))
    end)
end)
```

nc 127.0.0.1 8000
Welcome to skynet console
list
:01000004	snlua cmaster
:01000005	snlua cslave
:01000007	snlua datacenterd
:01000008	snlua service_mgr
:01000009	snlua main
:0100000a	snlua debug_console 8000
:0100000c	snlua b
<CMD OK>

task :0100000c
thread: 0x7fa127e88d68 session: 3	stack traceback:
	[C]: in function 'coroutine.yield'
	./skynet/lualib/skynet.lua:588: in upvalue 'yield_call'
	./skynet/lualib/skynet.lua:608: in function 'skynet.manager.call'
	src/service/b.lua:8: in upvalue 'f'
	./skynet/lualib/skynet.lua:253: in function <./skynet/lualib/skynet.lua:252>
<CMD OK>

PS ：服务A通过skynet.exit()退出时，服务B能返回

**Comment by cloudwu** [comment]
不要使用 kill , 要通知对方让它自己 exit 。

ps. 你怎么知道 skynet.kill 是做什么用的？猜出来的吗？如果是看的 https://github.com/cloudwu/skynet/wiki/LuaAPI 。那么已经解释过了。
