### ISSUE TITLE
关于 cluster 集群使用的疑问

### ISSUE THREAD

**Issue by donneyluck** [cloudwu/skynet#1372]
风大打扰了
在学习skynet cluster 用法时 参考了wiki   和  https://github.com/cloudfreexiao/RillServer
发现代码中 集群横向扩展是这样写的
```
local function start_login()
	for i,v in pairs(servconf.login) do
		local name = string.format("login%d", i)
		if nodename == v.node then
			local p = skynet.newservice("login", "login", i)
		else
			local proxy = cluster.proxy(v.node, name)
			skynet.name(name, proxy)
		end
	end
end

```
config中配置了2个节点 node1 和 node2
启动节点1的时候   集群会直接尝试连接节点2 
但是此时节点2还没有启动   会报错

socket-server: invalid socket
[:0000001d] Connect to 127.0.0.1:2529 failed (Connection refused)
[:00000009] lua call [1d to :9 : 6 msgsz = 0] error : /Users/donney/work/RillServer2/skynet/lualib/skynet.lua:616: /Users/donney/work/RillServer2/skynet/lualib/skynet.lua:183: nil
stack traceback:
	[C]: in function 'assert'
	/Users/donney/work/RillServer2/skynet/service/clusterd.lua:61: in metamethod '__index'
	/Users/donney/work/RillServer2/skynet/service/clusterd.lua:124: in local 'f'
	/Users/donney/work/RillServer2/skynet/service/clusterd.lua:212: in upvalue 'f'
	/Users/donney/work/RillServer2/skynet/lualib/skynet.lua:113: in function </Users/donney/work/RillServer2/skynet/lualib/skynet.lua:112>
stack traceback:
	[C]: in function 'assert'
	/Users/donney/work/RillServer2/skynet/lualib/skynet.lua:616: in function 'skynet.manager.dispatch_message'
[:0000001c] init service failed: /Users/donney/work/RillServer2/skynet/lualib/skynet.lua:358: call failed
stack traceback:
	[C]: in function 'error'
	/Users/donney/work/RillServer2/skynet/lualib/skynet.lua:358: in upvalue 'yield_call'
	/Users/donney/work/RillServer2/skynet/lualib/skynet.lua:375: in function 'skynet.manager.call'
	.../donney/work/RillServer2/skynet/service/clusterproxy.lua:25: in local 'start'
	/Users/donney/work/RillServer2/skynet/lualib/skynet.lua:720: in function </Users/donney/work/RillServer2/skynet/lualib/skynet.lua:717>
	[C]: in function 'xpcall'
	/Users/donney/work/RillServer2/skynet/lualib/skynet.lua:724: in function 'skynet.manager.pcall'
	/Users/donney/work/RillServer2/skynet/lualib/skynet.lua:728: in function 'skynet.manager.init_service'
	...donney/work/RillServer2/skynet/lualib/skynet/manager.lua:68: in upvalue 'f'
	/Users/donney/work/RillServer2/skynet/lualib/skynet.lua:113: in function </Users/donney/work/RillServer2/skynet/lualib/skynet.lua:112>

有什么办法可以避免这种情况吗  感谢

**Comment by hanxi** [comment]
延迟连或者需要的时候才连，又或者用心跳去连。

**Comment by cloudwu** [comment]
config 是可以用代码更新的，不一定依赖文件。所以你可以建一个中心管理服务器，启动起来后再更新  config 。

**Comment by donneyluck** [comment]
> config 是可以用代码更新的，不一定依赖文件。所以你可以建一个中心管理服务器，启动起来后再更新 config 。

这样感觉有点奇怪 先启动node1  在更新配置  然后启动  node2 

我只是想 如果连接失败 不要阻断当前服务 即可 

`local proxy = cluster.proxy(v.node, name)`

现在是失败的话  直接就中断了

**Comment by donneyluck** [comment]
> 延迟连或者需要的时候才连，又或者用心跳去连。

我以为连接失败不会阻断   稍后会继续重连

**Comment by cloudwu** [comment]
并不是要严格的做依赖次序。不用先启动 a 再启动 b 。

而是让整个集群先以只有中心节点的状态拉起来，然后再分发配置，统一更新。

**Comment by donneyluck** [comment]
> 并不是要严格的做依赖次序。不用先启动 a 再启动 b 。
> 
> 
> 
> 而是让整个集群先以只有中心节点的状态拉起来，然后再分发配置，统一更新。

好的 我在体会体会
