### ISSUE TITLE
halfclose状态下调用skynet_socket_start失败，不会收到socket_error消息

### ISSUE THREAD

**Issue by dingdalong** [cloudwu/skynet#1374]
使用的是skynet_package。

当gated这边使用proxy.subscribe启动一个package服务A之后，走完验证，在agent调用proxy.subscribe之前，客户端断开连接。此时会触发skynet_socket_type_error，package服务A正常退出。

agent接下来拿到fd后，调用proxy.subscribe会重启启动一个package服务B，但是此时fd对应的socket已经无效了。在packge中调用的skynet_socket_start会在halfclose_read判断中失败，目前这边返回的是-1，package服务B不会收到socket相关错误信息。

**Comment by cloudwu** [comment]
这里涉及 fd 在服务间迁移的问题，是没有处理的太好。

一个问题是，新增加的 resume/pause 机制中， resume 和 start 共用的同一个 api ，这点以后应该考虑分开。底层目前不太好区分到底是转移到新的服务后产生的 start ，还是一直在同一个服务中 resume 。

我暂时让 resume 的过程中发现 half close 就 raise 一个 error ，这可能会导致 resume 在 half close 过程产生不必要的 error 。但似乎也不会有什么问题（多一行日志？）。

你看看这么改能否解决问题。

**Comment by dingdalong** [comment]
测试后可以解决问题

谢谢~
