### ISSUE TITLE
使用redis遇到的一些问题

### ISSUE THREAD

**Issue by ZhouJiaZhi** [cloudwu/skynet#1380]
1.redis.watch没有db参数来切换数据库
2.重连后没有类似mysql的on_connect函数来执行一些初始化操作，mysql.connect({on_connect = on_connect})
3.不能指定登录用户，auth username password，https://redis.io/topics/acl

**Comment by cloudwu** [comment]
on_connect 我再考虑一下，另外两点我在 redis 分支 https://github.com/cloudwu/skynet/tree/redis 增加了支持。 https://github.com/cloudwu/skynet/commit/5d44e5034ec32074d1b6cecd04f32d84fa4be445

因为我暂时没有测试环境，麻烦看一下有没有问题。

**Comment by ZhouJiaZhi** [comment]
第270行的login_auth() 改成 login_auth(so)
简单测了下，没发现其他问题
