### ISSUE TITLE
域名解析的多返回值问题

### ISSUE THREAD

**Issue by t0350** [cloudwu/skynet#1398]
skynet 对 connect 返回 status 非 0 值且 errno 为 EINPROGRESS 的处理逻辑似乎不够完备。

问题场景是这样的：
1. 本地 hosts 表里对 localhost 配置了 ipv4 以及 ipv6 地址。
2. 启动服务器 A 仅监听 ipv4 地址。
3. 使用 skynet/socket 对 localhost:port 发起连接，解析返回了 ipv6 地址，此时 connect 返回 -1 且 erron 为 EINPROGRESS。

期望是能够正确连接 ipv4 地址（因为即使业务重试，这里仍然返回 ipv6 地址并连不上）。

另外这里也看到一个类似情况，连接一个没有在 listen 的地址返回 EINPROGRESS 的情况，https://curl.se/mail/lib-2001-10/0009.html .

**Comment by cloudwu** [comment]
这个最好能提个 pr :) 看看怎么做好。

**Comment by t0350** [comment]
> 这个最好能提个 pr :) 看看怎么做好。

= = ok，我考虑下这个怎么处理。

**Comment by t0350** [comment]
我晚上想了下，大概有这样的思路。

1. `connect` 无阻塞应该出于考虑不阻塞网络线程，但是使用 hostname connect 的时候，`getaddrinfo` 还是会阻塞线程。
2. 上面提到的问题要处理对，需要能够在 connect 失败后切换到下一个 ip / port 再尝试。需要想办法传递遍历到一半的信息。这个在 C 层暂时没有想到什么思路。

所以其实基于 1 看，传 hostname 本来直接 block connect 也可以，这样和 `getaddrinfo` 阻塞了线程一样表现。因此我觉得考虑 connect 接口只接受 ip 就好了，那这样涉及到 lua api 和 c api。lua api 这边我觉得在 `socket.open` 接口处理，改为先 `dns.resolve` 后尝试连接，c api 目前应该较少用到先忽略吧。

虽然这样看起来是 workaround，不过我觉得还能接受。云风看看如何呢？

**Comment by kinbei** [comment]
```
EINPROGRESS

    The socket socket is non-blocking and the connection could not be established immediately. 
You can determine when the connection is completely established with select; 
see Waiting for I/O. Another connect call on the same socket, before the connection is completely established, 
will fail with EALREADY.
```
是不是可以当 `errno` 为 `EINPROGRESS` 时，加个 `select` 处理，成功则 `break`，超时 `close` ？

**Comment by t0350** [comment]
> ```
> EINPROGRESS
> 
>     The socket socket is non-blocking and the connection could not be established immediately. 
> You can determine when the connection is completely established with select; 
> see Waiting for I/O. Another connect call on the same socket, before the connection is completely established, 
> will fail with EALREADY.
> ```
> 
> 是不是可以当 `errno` 为 `EINPROGRESS` 时，加个 `select` 处理，成功则 `break`，超时 `close` ？

EINPROGESS 现在有处理的，这个时候是返回 -1，等可写事件，report_connect 处才返回消息。

**Comment by cloudwu** [comment]
我觉得这个问题不是处理返回值的问题。其实是：hostname 其实对应的是一组 ip 而不是一个。

connect 是否应该在一组 ip 中做选择。目前的实现是在这组 ip 中选第一个。

因为建立连接是一个异步过程，在 c 层不适合做复杂的轮询操作。这个还是搬去 lua 层做比较合适。

**Comment by cloudwu** [comment]
另外，就原始问题，我认为应该同时监听 ipv4 和 ipv6 地址。因为你一个域名绑定了两个地址，最好让两个都生效。

**Comment by cloudwu** [comment]
我增加了一个 socket.resolve 可以调用 getaddrinfo 获得一个地址列表。它和 connect / bind 时的行为一致，这个系统 api 也是会阻塞的，需要谨慎使用。

我觉得修改 socket.open 还需要再考虑一下，暂时可以上层来决定是调用什么版本（系统版本或 skynet.dns 提供的自己实现的版本）的域名解析，以及是只尝试第一个地址，还是轮流都试一遍。

**Comment by t0350** [comment]
好的。#1402 那边我先 close 了。

我在想是不是可以考虑 C API `skynet_socket_connect` 拒绝掉域名方式的调用，只接收 ip。这样发起 connect 的流程可以认为是不会阻塞的。基于这样的前提再考虑 lua socket api ？（因为现在 getaddrinfo 有时候阻塞掉网络线程也会带来困扰）

比如现在新增的 `socket.resolve` 就是把阻塞的逻辑拆出来单独一个接口（我觉得这个方式挺好的），而再按上面说到的 `skynet_socket_connect` 仅接收 ip，那 `socket.open` 这个接口传递域名也不会有阻塞网络线程的担忧。

**Comment by cloudwu** [comment]
这个保留主要还是处于历史兼容的考虑，直接用域名是不推荐的。这是个拆脚手架的过程，在最早期实现 socket 模块的时候，需要考虑用 C 直接写服务。所以提供了许多方便 C 直接调用的接口。像 lua 版的 dns 查询就是后来加的。

至于直接用协议去做 dns 查询，需要很多的完善。需要做 cache ，如果是长期运行的服务，还需要根据域名自己设定的时间做 cache 失效的处理。这个时间从几小时到几天不等。

另外，可能可以另外本地启一个 http 服务做异步 dns 查询用。Chrome 就有这么一个 aync dns 的选项，用 https 取指定服务器做域名解析。

**Comment by t0350** [comment]
关于 dns cache 可以参考下这个。https://github.com/golang/go/issues/24796

golang 也没有做 dns cache。我觉得其实 skynet 也是可以考虑去掉的。自己做就像云风你提到的，考虑的东西还是比较多的。
golang 官方认为这层 cache 交给 host 来做，当然也是需要 dns query 要经过 host cache。而使用 /etc/resolv.conf 中的 nameserver（Linux 上），目前较新的系统已经是 localhost 了。

**Comment by t0350** [comment]
这个 issue 我先 close 掉了，问题场景是之前项目同事反馈到的，平常基本没有遇到这个问题。

目前新增的 `socket.resolve` 接口可以解决部分问题了。

**Comment by yuanfengyun** [comment]
很多网络环境下解析不到AAAA记录，导致dns解析超时，网络连接失败。
