### ISSUE TITLE
关于 select 的一个 coredump

### ISSUE THREAD

**Issue by rangercyh** [cloudwu/skynet#1399]
（skynet最新源码）

今天在项目中遇到一个 coredump，查了半天发现可能跟新加的 skynet.select 有关，写了还原 coredump 的代码，拜托云风帮忙看看，谢谢。简单描述就是服务 A call 2次服务 B，服务 B select call 服务 C，A 的第二次 call 就挂掉了。

```lua
local skynet = require "skynet.manager"

local function timeout_call(timeout, service, proto, ...)
    for _, resp in skynet.request(
        { service, proto, ... }
        ):select(timeout) do
        -- return resp[1]
        return table.unpack(resp, 1, resp.n)
    end
end

local mode = ...

if mode == "s1" then

skynet.start(function()
    skynet.register("s1")
    skynet.call("s2", "lua", "f")
    skynet.call("s2", "lua", "f")
end)

elseif mode == "s2" then

local command = {
    f = function()
        skynet.retpack(timeout_call(500, "s3", "lua", "f"))
    end,
}
skynet.start(function()
    skynet.register("s2")
    skynet.dispatch("lua", function(session, address, cmd, ...)
        local f = assert(command[cmd], cmd)
        f(...)
    end)
end)

elseif mode == "s3" then

local command = {
    f = function()
        skynet.retpack(true)
    end,
}
skynet.start(function()
    skynet.register("s3")
    skynet.dispatch("lua", function(session, address, cmd, ...)
        local f = assert(command[cmd], cmd)
        f(...)
    end)
end)

else

skynet.start(function()
    skynet.newservice("test_select", "s3")
    skynet.newservice("test_select", "s2")
    skynet.newservice("test_select", "s1")

    print("-----start")
end)

end
```

比较诡异的是如果在 select 收到消息后 resume 的地方 return table.unpack(resp, 1, resp.n) 修改成我注释掉的  return resp[1] 就不会 coredump 了。

堆栈如下：
![QQ截图20210514185234](https://user-images.githubusercontent.com/1217541/118261059-a09baf00-b4e5-11eb-8f98-996e9b66cbec.jpg)

**Comment by cloudwu** [comment]
调用堆栈第 6 层，我这里没有 `get_snlua` 这个函数。

**Comment by rangercyh** [comment]
> 调用堆栈第 6 层，我这里没有 `get_snlua` 这个函数。

可能是因为我开启了 lua 的 apicheck 
![QQ截图20210514191315](https://user-images.githubusercontent.com/1217541/118263174-81525100-b4e8-11eb-8f7d-aabca789fed4.jpg)

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/blob/master/service-src/service_snlua.c 这里面就没有 `get_snlua` 这个函数。

**Comment by rangercyh** [comment]
> https://github.com/cloudwu/skynet/blob/master/service-src/service_snlua.c#L98 这里面就没有 `get_snlua` 这个函数。而且运行流程中也没有调用过 `lua_settop` 。应该是你改过了。

好吧，确实是很久之前改过，sorry :(
