### ISSUE TITLE
想请教，skynet做的游戏，怎么设计互相偷菜的场景（互相修改玩家数据），特别是当其中一个玩家离线的状态

### ISSUE THREAD

**Issue by phzzy** [cloudwu/skynet#1406]
A 和 B 两个玩家都是独立的 agent，各自维护各自的数据
如果 A 要去修改 B 的数据，比如偷了 B 的一棵菜，或者修改 B 的货币
正常应该是  A 发消息给 B 的agent，执行偷菜的操作

但如果 B 不在线，B 的agent不存在呢？ 需要怎么做？

**Comment by cloudfreexiao** [comment]
离线 就 拉起 B 创建个 agent

**Comment by phzzy** [comment]
> 
> 
> 离线 就 拉起 B 创建个 agent

这样新启一个agent，如果agent逻辑比较多，可能需要一定时间，比如1s
那我去看别人家，还需要这个时间，是否太多了？ 并且会不会对系统消耗比较大，毕竟一个玩家上线，是要加载不少数据的

不知道陌陌争霸当时是怎么做的？比如去攻打别人的城

**Comment by sniper00** [comment]
一般拉起是毫秒级。但还是要好好设计：
1. 玩家经常看的数据，建议直接全部加载内存；
2. 玩家下线不要立马删除 agent, 定个策略，如agent数量大于1000(可以参考活跃同时在线量级), 并且离线时间大于10分钟的才删除。

**Comment by phzzy** [comment]
好的。非常感谢
