### ISSUE TITLE
http.httpd 处理请求时，遇到Resume socket错误

### ISSUE THREAD

**Issue by srdgame** [cloudwu/skynet#1408]
当请求的 body较大时会出现下述错误：

Pause socket (393) size : 157123
Resume socket (393)
socket: error on unknown 393 invalid socket

**Comment by cloudwu** [comment]
httpd 设计上无此限制，你可以调试一下确定是什么问题。看出错信息似乎是 resume 时， 393 这个 fd 变得无效了。而 pause 的时候肯定是有效的。

pause/resume 机制发生在 (393) 上行数据过多，而 Lua 层没有读走（处理）的时候发生。

具体见 https://github.com/cloudwu/skynet/blob/master/lualib/skynet/socket.lua#L30-L60

你还可以查看前后的 log 看是否有 393 这个 fd 被关闭的记录。

**Comment by srdgame** [comment]
我问题提错了，并不是http body大小引起的。

而是这里的判断： https://github.com/cloudwu/skynet/blob/master/lualib/skynet/socket.lua#L73-L84

我们是遇到了，sz等与 rr的情况， 而这种情况下:

httpd.read_request 正常返回了，读到了足够的数据，然后就调用了 socket.close(id)。

那这里的pause_socket是不是应该把， sz == rr的情况给排除掉？？

@cloudwu

**Comment by cloudwu** [comment]
从你的描述看，流程已经走完，正常关闭了 fd 。所以只是多了一条无害的 log 。

这个问题和读到多少字节无关，即和 sz == rr 无关。即使 sz > rr ，你依然可以主动关闭 fd ，还是会触发 log 。

这里的问题是，当 driver.close 关闭 fd 后不应该再触发 resume 的流程。应该在 https://github.com/cloudwu/skynet/blob/master/lualib/skynet/socket.lua#L283 加一行 s.pause = nil 就够了。

**Comment by cloudwu** [comment]
看看这样是不是就可以避免写出错 log ？

**Comment by srdgame** [comment]
@cloudwu 好的，今天会进行测试

**Comment by srdgame** [comment]
跑了两天测试，没有任何问题。先关闭了
