### ISSUE TITLE
memory allocation error: block too big

### ISSUE THREAD

**Issue by joeplayer126** [cloudwu/skynet#1409]
socket.read() 报错，没有头绪，请大神指点。

代码:
	local data, err
	while true do
		local presentBuff, err = socket.read(socketId, 4)
        local headString = string.sub(presentBuff, 1, 4)
        local b1, b2, b3, b4 = string.byte(headString, 1, 4)
        local messageSize =  b1 + b2 * 256 + b3 * 65536 + b4 * 16777216
    	if messageSize <= 0 then
		return nil
	end

	local data, err = socket.read(self.id, messageSize)
......

打印错误：
Unknown command : memory allocation error: block too big
stack traceback:
	[C]: in function 'skynet.socketdriver.pop'
	./common/lualib/skynet/socket.lua:275: in function 'skynet.socket.read'
	./common/global/StreamSocket.lua:95: in function 'StreamSocket.onReceive'
	./common/global/StreamSocket.lua:107: in function 'StreamSocket.start'
	./logicServer/service/LogicServiceProcessor.lua:49: in local 'f'
	./logicServer/service/LogicServiceProcessor.lua:161: in upvalue 'f'
	./common/lualib/skynet.lua:141: in function <./common/lualib/skynet.lua:113>

**Comment by cloudwu** [comment]
不是已经写了：memory allocation error: block too big

检查 messageSize

另外，你这协议本身设计就有问题：只要几个连接上来都发个 ff ff ff ff 。你插 1 T 内存也不够用。

**Comment by joeplayer126** [comment]
大概明白原因了，不过我的水平有限，没想到合适的修改……能给一些修改建议或者参考代码吗，谢谢

**Comment by sanikoyes** [comment]
设计一个消息最大大小，超过这个sz的数字可以认为是一个非法值，记录日志后关闭连接

**Comment by joeplayer126** [comment]
> 设计一个消息最大大小，超过这个sz的数字可以认为是一个非法值，记录日志后关闭连接

@谢了
