### ISSUE TITLE
skynet.task 统计数量时未排除 BREAK 协程

### ISSUE THREAD

**Issue by TQING1990** [cloudwu/skynet#1413]
我有一个中心节点，使用 skynet.sleep 实现的 timeout_call 检查节点状态，因为 skynet.wakeup 提前唤醒将协程的状态置为了 BREAK。这个状态会在 skynet.sleep 的设置的时间到了才会设置为 nil。

我在关服流程中检查所有服务的 task 和 mqlen 为 0 时 abort，使用了 timeout_call 的服务就必须等待 BREAK 状态变为 nil。

skynet.task 统计数量时未排除 BREAK 是出于什么原因？

**Comment by cloudwu** [comment]
task 可以增加判断 BREAK 不计数，我之后改一下。这里没排除是因为历史上先有的 task 再增加的 wakeup 。

另外，现在推荐用 select 直接实现 timeout call 。

**Comment by cloudwu** [comment]
稍微改了一下。疫情期间在临时在家办公 ，未能充分测试。烦请帮忙看一下。

**Comment by TQING1990** [comment]
好的

**Comment by TQING1990** [comment]
> task 可以增加判断 BREAK 不计数，我之后改一下。这里没排除是因为历史上先有的 task 再增加的 wakeup 。
> 
> 另外，现在推荐用 select 直接实现 timeout call 。

select 目前用在节点之间是不是只能用 cluster.proxy？

**Comment by TQING1990** [comment]
测试了，没有问题

**Comment by TQING1990** [comment]
@cloudwu  select 目前用在节点之间是不是只能用 cluster.proxy，不能用 cluster.call ?
