### ISSUE TITLE
cmaster.lua报错：disconnect fd = XX, error =XXXXXX

### ISSUE THREAD

**Issue by joeplayer126** [cloudwu/skynet#1417]
公司服务器上没有这个问题，只有在阿里云上运行才会报错，而且报错很多，但是不影响运行。请大神指点

其中一个报错：
[:01000004] connect from 193.93.62.130:63419 1826
[:01000004] disconnect fd = 1826, error = ./common/service/cmaster.lua:36: Invalid serialize stream 0 (line:517)

**Comment by cloudwu** [comment]
设置好防火墙，隔断不明连接。
