### ISSUE TITLE
有计划支持长度超过2G的消息吗？

### ISSUE THREAD

**Issue by drinkwithwater** [cloudwu/skynet#1424]
想在一些处理大数据的场景下使用skynet。

**Comment by cloudwu** [comment]
skynet 的消息长度类型是 size_t , 是 64 bits .

**Comment by drinkwithwater** [comment]
但是lua-seri.c、lua-skynet.c以及lua-cluster.c的实现里有好几处用了int或者uint32作长度，然后lua层首先就无法pack长度超过2G的消息了。

**Comment by cloudwu** [comment]
你可以根据需要实现自己的 lua seri , skynet 允许自定义消息 pack 方式。

**Comment by cloudwu** [comment]
另外，我认为你真的有超过 2g 的数据要通过消息发送的话。不应该放在 lua 里序列化再解开。恐怕内存会有上 G 的浪费，cpu 也会浪费在上面。

你应该自定义一个消息格式，打包后，消息只传递它的指针。

**Comment by drinkwithwater** [comment]
是有一些类型打算用共享指针的方式传，只是在跨进程传输时会全序列化。看来都得自己实现了。多谢。

**Comment by hanxi** [comment]
2G 的数据还不如发文件名，然后用其他的文件服务器传输，还能断点续传。比较好奇什么场景会有 2G 这么大的消息，除了文件共享还没见过这么大的。

**Comment by drinkwithwater** [comment]
> 2G 的数据还不如发文件名，然后用其他的文件服务器传输，还能断点续传。比较好奇什么场景会有 2G 这么大的消息，除了文件共享还没见过这么大的。
做强化学习时的采样数据。
