### ISSUE TITLE
这里换成__mm_pause 对编译器兼容性是否更好

### ISSUE THREAD

**Issue by sniper00** [cloudwu/skynet#1432]
https://github.com/cloudwu/skynet/blob/5c154d34dc52edcff32355c819bdcc8b999cb3da/skynet-src/spinlock.h#L56

https://stackoverflow.com/questions/5833527/how-do-you-use-the-pause-assembly-instruction-in-64-bit-c-code/51908785#51908785

**Comment by cloudwu** [comment]
@colinsusie

**Comment by colinsusie** [comment]
查了下GCC文档，`__builtin_ia32_pause`最早出现在gcc-4.7.4，`__mm_pause`最早出现在gcc-4.8.5(好像是intel提供的接口?)，这两个函数生成了同一个X86 指令：

```c
#include <stdio.h>
#include <immintrin.h> // For _mm_pause
int main(int argc, char const *argv[]) {
	while (1) {
		_mm_pause();
		__builtin_ia32_pause();
	}
	return 0;
}
```
生成的ASM如下：
```asm
0000000000001125 <main>:
    1125:       55                      push   %rbp
    1126:       48 89 e5                mov    %rsp,%rbp
    1129:       89 7d fc                mov    %edi,-0x4(%rbp)
    112c:       48 89 75 f0             mov    %rsi,-0x10(%rbp)
    1130:       f3 90                   pause  
    1132:       f3 90                   pause  
    1134:       eb fa                   jmp    1130 <main+0xb>
    1136:       66 2e 0f 1f 84 00 00    nopw   %cs:0x0(%rax,%rax,1)
    113d:       00 00 00 
```

看起来都是生成pause指令。我在Mac上用Clang编译了下没啥问题，clang应该是高度兼容GCC的。

使用`__mm_pause`的好处是连MSVC好像也支持，这感觉是intel提供的接口，嗯。。。要不要换都可以吧。

**Comment by cloudwu** [comment]
虽然 skynet 不能在 msvc 下直接编译，但是单就这一个文件来说，是不是加个宏判断，把两者都加进去更好？

如果有 immintrin.h 就可以用 _mm_pause 了。

**Comment by colinsusie** [comment]
是的immintrin.h 要早于stdatomic.h，要不换成_mm_pause吧，这样单就atomic版本来说可以支持多个编译器

我等会测一下提个RP吧。
