### ISSUE TITLE
cluster.reload 报错

### ISSUE THREAD

**Issue by wangyi0226** [cloudwu/skynet#1434]
修改examples/cluster2.lua
```lua
local skynet = require "skynet"
local cluster = require "skynet.cluster"

skynet.start(function()
	--在db=false前先生成db的cluster_sender
	print(cluster.call("db", "@sdb", "GET", "a"))

	-- test snax service
		cluster.reload {
			db = false,	-- db is down
			db3 = "127.0.0.1:2529"
		}
end)
```
cluster.reload会触发open_channel,然后报错err = string.format("cluster node [%s] is %s.", key,  address == false and "down" or "absent")

**Comment by cloudwu** [comment]
看了一下，似乎需要让 false 也成为合法的 changenode 的目标 host。https://github.com/cloudwu/skynet/blob/master/service/clustersender.lua#L63
接收到 false 时关闭连接，并成功返回。

然后在 reload 的时候统一把更换 host 转发给 sender 处理。

我现在没有开发环境，要不你尝试改一下提个 pr ?

**Comment by cloudwu** [comment]
我在分支上修了一下。
但目前还有一个问题：reload 返回不表明所有配置均更新了。因为重连所有节点有很多不确定因素，暂时没有做成阻塞操作。

**Comment by cloudwu** [comment]
@wangyi0226 看看是否解决了问题。

**Comment by wangyi0226** [comment]
@cloudwu  不好意思，最近事情比较多， 刚试了下reload已经不会报错，down之后再changenode也能成功。但是还有个问题就是调用已经down的节点报错不会提示节点的key，不过这类报错也基本都能猜到问题在哪里
