### ISSUE TITLE
httpc调用的internal.lua的request的163行content-length:%d\r\n\r\n调用谷歌api的时候影响到json结构导致调用失败

### ISSUE THREAD

**Issue by mrCerberus** [cloudwu/skynet#1441]
local data = string.format("%s %s HTTP/1.1\r\n%scontent-length:%d\r\n\r\n", method, url, header_content, #content)
httpc调用的internal.lua的request的163行content-length:%d\r\n\r\n调用谷歌api的时候影响到json结构导致调用失败，并且header头里没有Content-length(要大写C，不过这个可以通过传入header解决)

**Comment by cloudwu** [comment]
你可以提个 pr , 包括大小写问题。
