### ISSUE TITLE
redis 报错后，db操作不返回，一直卡着协程

### ISSUE THREAD

**Issue by brucelin-cn** [cloudwu/skynet#1445]
skynet 版本 1.3.0 （日志等代码有一些小改动，加了毫秒打印，其它底层没改）

错误信息：
 lualib/skynet/socketchannel.lua:411: LOADING Redis is loading the dataset in memory

代码A:
##########################
function CMD.keepalive()
	
	if DATA.connection then
		local ok, ret = skynet.pcall(DATA.connection.get, DATA.connection, "foo")
		if not ok then
			skynet.error("ping failed reconnect it", ret)

			local ok, ret = skynet.pcall(DATA.connection.disconnect, DATA.connection)

			if not ok then
				skynet.error("disconnect failed", ret)
			end

			DATA.connection = nil

			CMD.connect()
		end
	else
		CMD.connect()
	end
end
##########################
代码说明：
只要redisdb 返回错误，我的代码 就会执行断开redis，再重新连接redis

代码B：
############################
1    skynet.info("roomRunn", cid, room.runningState)
2    local ok, ret = skynet.pcall(StateRun.run, cid)
3    if not ok then
4        skynet.error(" runRoomStat failed  ", cid, ret)
5   end
6  skynet.info("roomRunn", cid, room.runningState)
############################
代码说明：
StateRun.run 内部有很多操作，包括redis操作。

看代码B的 日志，只输出了 line1的 “roomRunn“，line6的没有打印了。

后面有其它请求redisdb 操作，redisdb又有返回了。

感觉是：
StateRun.run 里调用redisdb 失败后 ，一直卡着了。

**Comment by cloudwu** [comment]
1. 用最新版本再做一次看看。
2. 代码最好用 markdown 重新排一下。

**Comment by brucelin-cn** [comment]
> 1. 用最新版本做一次测试看看。
> 2. 代码最好用 markdown 重新排一下。

这个问题不是必现的。就出来一次，新版本一时半会估计也测试不出来。redis版本 是5.7.
我看skynet 1.4 的md，好像没有对网络库，skynet的redis 有改动？

**Comment by cloudwu** [comment]
不是 1.4 ，是 master TOP  。

精力有限，不对任何旧版本做维护。
