### ISSUE TITLE
service在什么情况下会重置luastate

### ISSUE THREAD

**Issue by linse073** [cloudwu/skynet#1446]
发现一个问题，我在c库里面保存了服务的luastate，结果导致程序有一定概率宕机，后面发现luastate的地址有时候会重置。请问什么情况下回重置服务的luastate？

**Comment by linse073** [comment]
原来的luastate销毁了，创建了一个新的luastate，结果导致使用原来的luastate的代码崩溃了。

**Comment by cloudwu** [comment]
没有 api 可以取到服务的 luastate ，你怎么拿到的？

或许你混淆了 lua vm 和 lua thread (coroutine) 。

**Comment by linse073** [comment]
不是，我用了一个第三方c库，然后导出接口给lua调用，这个库因为一些原因保存了lua_State，结果导致服务有时候宕机。

**Comment by linse073** [comment]
我贴一部分代码把。
struct Callback {
    uint64_t handle;
    lua_State* L;
};

static int kcp_output_callback(const char *buf, int len, ikcpcb *kcp, void *arg) {
    struct Callback* c = (struct Callback*)arg;
    lua_State* L = c->L;
    uint64_t handle = c->handle;

    lua_rawgeti(L, LUA_REGISTRYINDEX, handle);
    lua_pushlstring(L, buf, len);
    lua_call(L, 1, 0);

    return 0;
}
static int lkcp_create(lua_State* L) {
    uint64_t handle = luaL_ref(L, LUA_REGISTRYINDEX);
    int32_t conv = luaL_checkinteger(L, 1);

    struct Callback* c = malloc(sizeof(struct Callback));
    memset(c, 0, sizeof(struct Callback));
    c->handle = handle;
    c->L = L;

    ikcpcb* kcp = ikcp_create(conv, (void*)c);
    if (kcp == NULL) {
        luaL_unref(L, LUA_REGISTRYINDEX, handle);
        free(c);
        lua_pushnil(L);
        lua_pushstring(L, "error: fail to create kcp");
        return 2;
    }

    kcp->output = kcp_output_callback;

    *(ikcpcb**)lua_newuserdata(L, sizeof(void*)) = kcp;
    luaL_getmetatable(L, "kcp_meta");
    lua_setmetatable(L, -2);
    return 1;
}

**Comment by linse073** [comment]
> 没有 api 可以取到服务的 luastate ，你怎么拿到的？
> 
> 或许你混淆了 lua vm 和 lua thread (coroutine) 。
我是混淆了这两个概念。
