### ISSUE TITLE
关于MAX_UDP_PACKAGE

### ISSUE THREAD

**Issue by firedtoad** [cloudwu/skynet#1450]
关于MAX_UDP_PACKAGE常量定义的不对，想起多年前做过实验 ，大于 65507的包会发送失败
参考 https://en.wikipedia.org/wiki/User_Datagram_Protocol#UDP_datagram_structure

**Comment by cloudwu** [comment]
这个宏不用于限制包长度。它只要大于上限即可。

**Comment by firedtoad** [comment]
大佬加个注释吧，防止他人误解
