### ISSUE TITLE
httpd模块导入时，会注册socket协议，造成业务逻辑注册时报重复注册错误

### ISSUE THREAD

**Issue by heyilin416** [cloudwu/skynet#1452]
httpd会导入local internal = require "http.internal"
internal会导入local sockethelper = require "http.sockethelper"
sockethelper会导入local socket = require "skynet.socket"
socket会注册socket协议
skynet.register_protocol {
	name = "socket",
	id = skynet.PTYPE_SOCKET,	-- PTYPE_SOCKET = 6
	unpack = driver.unpack,
	dispatch = function (_, _, t, ...)
		socket_message[t](...)
	end
}

**Comment by JieTrancender** [comment]
业务模块也用`local socket = require "skynet.socket"`即可，猜测现在用的是`local socket = require "socket"`。

**Comment by heyilin416** [comment]
不是，是业务需要自己定义注册socket协议，这是升级skynet时出现的，看了老版本的http.internal模块并没有导入http.sockethelper，在创建httpd时并不需要导入skynet.socket模块；

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/pull/1237  是这个把它改坏了. 此处不应该依赖 socket 模块.
