### ISSUE TITLE
是否有API可以根据服务ID获取到注册的名字

### ISSUE THREAD

**Issue by Gowa2017** [cloudwu/skynet#1454]
缘由：
个人想在 logger 服务里面，输出服务的名字，记录是哪个服务产生的消息，当前是，打印的是服务ID 的16 进制字符串形式。

个人追踪过的过程：

我采用 skynet.register 'srvname' 注册名字后，能看到，注册的名字是放到了全局变量 handle_storage *H 的 handle_name *name 数组里面。

我能看到，skynet_handle_findname 这个函数会根据 名字 来查找handle，但通过 handle 来查找，就没看到通过 handle 来查找名字的。

如果有，请帮忙指点一下。
如果没有，也请帮答复一下。

**Comment by hanxi** [comment]
建议：自己实现名字管理服务，自己实现 logger 服务。
不想自己实现名字服务也能做到，改写 `skynet.register` 函数，通知自定义的 logger 服务记录服务器id和服务名字的关系，打印日志的时候查到有名字就打印名字。

**Comment by cloudwu** [comment]
log 服务一开始会拿到每个服务的启动信息。把它记录下来，后面做匹配。

**Comment by Gowa2017** [comment]
我实际上想做的是，skynet_error 将一条消息给到 logger 服务。我是希望输出这发出消息的源服务名。
云大说的那句话没有理解出来。

**Comment by zeroatom** [comment]
1. 发送源处理
    * 本地记录名字
    * 包装log func
    * 有名字时对自定义log服务调名字日志 CMD.name_log(name, ...) or 名字作为日志内容 如: skynet.error(string.format("%s %s",name, log_str))
    * 未使用包装func的log有问题
2. 自定义log服务处理
    * 命名服务时通知自定义log服务
    * CMD.addr_log(addr,...) -> address_name[address] 取名字

**Comment by cloudwu** [comment]
> 我实际上想做的是，skynet_error 将一条消息给到 logger 服务。我是希望输出这发出消息的源服务名。
> 云大说的那句话没有理解出来。

人在阅读 log 的时候，翻阅历史 log ，人是可以知道每个数字 id 实际是什么东西的。

因为所有服务在创建的时候，都以 log 的形式把信息输出到了 logger 服务；所以，logger 服务拥有这些状态，它可以根据状态做任何形式的变换（比如把 id 变成名字）再输出。

logger 服务不需要用额外的协议去同步这些名字，就用已有历史 log 信息就够了。因为这本身就是人去分析 log 的流程。只是用代码去实现人阅读 log 的逻辑。

**Comment by Gowa2017** [comment]
> * 发送源处理
>   
>   * 本地记录名字
>   * 包装log func
>   * 有名字时对自定义log服务调名字日志 CMD.name_log(name, ...) or 名字作为日志内容 如: skynet.error(string.format("%s %s",name, log_str))
>   * 未使用包装func的log有问题
> * 自定义log服务处理
>   
>   * 命名服务时通知自定义log服务
>   * CMD.addr_log(addr,...) -> address_name[address] 取名字

感谢。



> > 我实际上想做的是，skynet_error 将一条消息给到 logger 服务。我是希望输出这发出消息的源服务名。
> > 云大说的那句话没有理解出来。
> 
> 人在阅读 log 的时候，翻阅历史 log ，人是可以知道每个数字 id 实际是什么东西的。
> 
> 因为所有服务在创建的时候，都以 log 的形式把信息输出到了 logger 服务；所以，logger 服务拥有这些状态，它可以根据状态做任何形式的变换（比如把 id 变成名字）再输出。
> 
> logger 服务不需要用额外的协议去同步这些名字，就用已有历史 log 信息就够了。因为这本身就是人分析 log 的流程。只是用代码去实现人阅读 log 的逻辑。

感谢，
