### ISSUE TITLE
https请求某些域名会失败

### ISSUE THREAD

**Issue by colinsusie** [cloudwu/skynet#1459]
如题所述，将test/testhttp.lua的`baidu.com`改成`api-ygsytp.digginggames888.com`即可重现。

在网上查过一些资料，证实是由于目标服务器有多个SSL证书(Server Name Indication(SNI) )，客户端请求时没有向服务器指明域名，导致服务器没有办法正确处理。

解决方法是在TLS握手之前增加：`SSL_set_tlsext_host_name`告诉服务器域名，期望修正这个问题。

**Comment by cloudwu** [comment]
@lvzixun
