### ISSUE TITLE
http body chunked 模式处理

### ISSUE THREAD

**Issue by JieTrancender** [cloudwu/skynet#1461]
当前在做etcd v3版本的watch处理(即监听etcd实时获取配置变化)，对etcd执行`http://127.0.0.1:2379/v3/watch`请求后阻塞在了`recvchunkedbody`函数的while循环：
https://github.com/cloudwu/skynet/blob/fdc4b3528130a52e72ee8c663199d6eb65cab731/lualib/http/internal.lua#L103-L131
当配置变化时函数内部现在能实时收到变更的数据，但现在需要持续的watch数据处理需要放到外部，即需要在请求外部持续读取body数据。
请问云大我现在应该怎样做比较好。

**Comment by cloudwu** [comment]
在最初设计 http 模块时，只想解决一些简单的 http 请求，并没有考虑处理数据流。所以，现有的代码都是把整个回应都收下来后才返回的。

我觉得你可以增加一个处理数据流的接口。你可以尝试逐步实现一部分，我来 review ，完成后合并到主干。

我建议：

1. 在 internal.lua 中仿照 request 增加一个处理流式处理的 api （我建议叫 request_stream）。request 现在返回值为 status code 和 body 的完整串，新接口可以返回 status code 和流对象。
2. 流对象是一个 function ，每次调用它就可以从 http resp 流中返回不为空的若干字节的数据。如果返回 true 就表示流正常关闭；返回 false/nil 表示连接断开了。

在实现上，我们需要把现在的 request 函数的 header 处理和 body 处理分离：

1. 解析完 header 就立刻返回，并把中间状态（除开 header 外已经读到的内容）记在流对象中一并返回。
2. 流对象中还要记录 socket fd ，前一步返回后不应关闭 fd 。
3. 后续每次调用流对象，都从 fd 中读出并尽量解析更多的内存，知道流结束或 fd 断开。

注意：目前 sockethelper 封装的 readbytes 其实就是 socket.read ，从名字看，它是阻塞读指定字节数。但其实，这个 api 如果字节数传 nil ，它可以读 buffer 中的所有字节，如果 buffer 中没有数据，则会等待至少一个新字节。

这里的问题其实不仅仅是 `recvchunkedbody` 。对于 identity mode 也应该一起支持。

identity mode 会比 chunked mode 更容易支持。identity mode 下，header 已经解析完，只要把后续工作放在流中继续读，读完就关闭连接即可。

chunked mode 会复杂一些，因为在传输完数据后，协议还可以把一些 header 信息包含在尾部 （ https://github.com/cloudwu/skynet/blob/master/lualib/http/internal.lua#L133-L139 ） 。我们可以给流函数调用时传入一个 table （通常就是原本的 header 表），让它最后再更新 header 。

**Comment by JieTrancender** [comment]
嗯嗯，我来。
