### ISSUE TITLE
最新master testmongodb服务运行，出现这样的报错,请问云风大佬如何解决

### ISSUE THREAD

**Issue by Taopper** [cloudwu/skynet#1471]
[:00000002] LAUNCH snlua bootstrap
[:00000003] LAUNCH snlua launcher
[:00000004] LAUNCH snlua cdummy
[:00000005] LAUNCH harbor 0 4
[:00000006] LAUNCH snlua datacenterd
[:00000007] LAUNCH snlua service_mgr
[:00000008] LAUNCH snlua main_mongodb
Main Server start
[:00000009] LAUNCH snlua testmongodb 127.0.0.1 27017 testdb test test
Test auth
Test insert without index
[:00000009] socket: auth failed ./lualib/skynet/db/mongo.lua:102: assertion failed!
[:00000009] Connect to 127.0.0.1:27017 failed (no more backup host)
[:00000009] init service failed: [Error: socket]
[:00000009] KILL self
[:00000008] init service failed: ./lualib/skynet.lua:590: call failed
stack traceback:
        [C]: in function 'error'
        ./lualib/skynet.lua:590: in upvalue 'yield_call'
        ./lualib/skynet.lua:607: in function 'skynet.call'
        (...tail calls...)
        ./examples/main_mongodb.lua:6: in upvalue 'start'
        ./lualib/skynet.lua:935: in function <./lualib/skynet.lua:933>
        [C]: in function 'xpcall'
        ./lualib/skynet.lua:937: in function 'skynet.init_service'
        ./lualib/skynet.lua:950: in upvalue 'f'
        ./lualib/skynet.lua:253: in function <./lualib/skynet.lua:252>
[:00000008] KILL self
[:00000002] KILL self

**Comment by taotaoisme** [comment]
function auth_method:auth_scram_sha1(username, password)
    local user = string.gsub(string.gsub(username, "=", "=3D"), ",", "=2C")
    local nonce = crypt.base64encode(crypt.randomkey())
    local first_bare = "n=" .. user .. ",r=" .. nonce
    local sasl_start_payload = crypt.base64encode("n,," .. first_bare)
    local r

    print("auth_scram_sha1 2")

    r = self:runCommand("saslStart", 1, "autoAuthorize", 1, "mechanism", "SCRAM-SHA-1", "payload", sasl_start_payload)
    if r.ok ~= 1 then
        return false
    end

    print("auth_scram_sha1 3")

跟踪下来这个auth_scram_sha1 3没输出日志，2输出了

然后：
function mongo_client:runCommand(...)
    if not self.admin then
        self.admin = self:getDB "admin"
    end
    self.admin = self:getDB "testdb"
    return self.admin:runCommand(...)
end

这里按照之前有个解答改了下，但是还是同样报错，
不加 self.admin = self:getDB "testdb" 
self.admin打印是:
[mongo db :     admin]

加了之后:
[mongo db :     testdb]

**Comment by cloudwu** [comment]
我无能为力。你需要自己了解 mongodb 是怎样工作的，找到问题，解决问题。

**Comment by taotaoisme** [comment]
好的 我看看

**Comment by Gowa2017** [comment]
需要指定 db 名

**Comment by taotaoisme** [comment]
**把auth拿出来后，这是成功了？我这边用python3的pymongo去直接插入，是没问题的**
function mongo.client(conf)
    local first = conf
    local backup = nil
    if conf.rs then
        first = conf.rs[1]
        backup = conf.rs
    end
    local obj = {
        host = first.host,
        port = first.port or 27017,
        username = first.username,
        password = first.password,
        authmod = first.authmod,
        authdb = first.authdb
    }

    obj.__id = 0
    obj.__sock =
        socketchannel.channel {
        host = obj.host,
        port = obj.port,
        response = dispatch_reply,
        backup = backup,
        nodelay = true,
        overload = conf.overload
    }
    obj.__sock.auth = mongo_auth(obj)                --这个拿出来
    setmetatable(obj, client_meta)
    obj.__sock:connect(true) -- try connect only	once
    return obj
end

**输出：**
[:00000002] LAUNCH snlua bootstrap
[:00000003] LAUNCH snlua launcher
[:00000004] LAUNCH snlua cdummy
[:00000005] LAUNCH harbor 0 4
[:00000006] LAUNCH snlua datacenterd
[:00000007] LAUNCH snlua service_mgr
[:00000008] LAUNCH snlua main_mongodb
Main Server start
[:00000009] LAUNCH snlua testmongodb 127.0.0.1 27017 testdb test test
Test auth
Test insert without index
Test insert index
Test find and remove
Test runCommand
Test expire index
check expire    1
check expire    2
check expire    3
check expire    4
check expire    5
check expire    6
check expire    7
check expire    8
check expire    9
check expire    10
check expire    11
check expire    12
check expire    13
check expire    14
check expire    15
check expire    16
check expire    17
check expire    18
check expire    19
check expire    20
check expire    21
check expire    22
check expire    23
check expire    24
check expire    25
check expire    26
check expire    27
check expire    28
check expire    29
check expire    30
check expire    31
check expire    32
check expire    33
check expire    34
check expire    35
check expire    36
check expire    37
check expire    38
check expire    39
check expire    40
check expire    41
check expire    42
check expire    43
check expire    44
check expire    45
check expire    46
check expire    47
check expire    48
check expire    49
check expire    50
check expire    51
check expire    52
check expire    53
check expire    54
check expire    55
check expire    56
check expire    57
check expire    58
test safe batch insert
mongodb test finish.
Main Server exit
[:00000008] KILL self
[:00000002] KILL self

**Comment by taotaoisme** [comment]
不过可能不是这个错 我这边的项目是放在__sock里的貌似没什么问题

**Comment by taotaoisme** [comment]
这个好像 提的有问题 得再看看

**Comment by Gowa2017** [comment]
mongo.client(conf) conf 里面指定 authdb.

**Comment by taotaoisme** [comment]
local function mongo_auth(mongoc)
    local user = rawget(mongoc, "username")
    local pass = rawget(mongoc, "password")
    local authmod = rawget(mongoc, "authmod") or "scram_sha1"
    authmod = "auth_" .. authmod
    local authdb = rawget(mongoc, "authdb")
    **print("mongo_auth trace...1", authdb)**
    if authdb then
        authdb = mongo_client.getDB(mongoc, authdb) -- mongoc has not set metatable yet
    end
    **print("mongo_auth trace...2", authdb)**

打印：
mongo_auth trace...1    testdb
mongo_auth trace...2    [mongo db :     testdb]

db是有的啊

**Comment by banana-framework-lab** [comment]
想问问最后的解决方案是什么
