### ISSUE TITLE
An improper locking due to the unreleased lock

### ISSUE THREAD

**Issue by ryancaicse** [cloudwu/skynet#1475]
Hi developers, in the below codes, the lock `q->lock` could be not released before program's exit `exit(1);` . I think there is no harm to write `pthread_mutex_unlock(&q->lock);`  before the `exit(1)` for better resource management and code symmetry. Thanks!
https://github.com/cloudwu/skynet/blob/ceb278adf666b2d3259408245f1c3a96031b17d7/lualib-src/lua-clientsocket.c#L155-L165

Best,

**Comment by cloudwu** [comment]
As the comments said,

// It's only for demo, limited feature. Don't use it in your project.
// Rewrite socket library by yourself .
