### ISSUE TITLE
skynet uniqueservice 传递table类型的参数会报错

### ISSUE THREAD

**Issue by ZhouJiaZhi** [cloudwu/skynet#1477]
```lua
local t = {}
skynet.uniqueservice("test_service", t)
```

./skynet/lualib/skynet.lua:858: ./skynet/lualib/skynet.lua:330: ./skynet/service/launcher.lua:94: invalid value (table) at index 2 in table for 'concat'
stack traceback:
	[C]: in function 'table.concat'
	./skynet/service/launcher.lua:94: in upvalue 'launch_service'
	./skynet/service/launcher.lua:110: in local 'f'
	./skynet/service/launcher.lua:176: in upvalue 'f'
	./skynet/lualib/skynet.lua:280: in function <./skynet/lualib/skynet.lua:252>
stack traceback:
	[C]: in function 'assert'
	./skynet/lualib/skynet.lua:858: in function 'skynet.dispatch_message'

能否改动下，支持传递table类型的参数

**Comment by cloudwu** [comment]
你可以定义一个初始化协议，或在初始化阶段拉初始化参数。
