### ISSUE TITLE
lua5.4中lua-bson中判断table是否是数组is_rawarray的问题

### ISSUE THREAD

**Issue by sniper00** [cloudwu/skynet#1484]
这篇文章的方式好像不适用lua5.4, https://blog.codingnow.com/2016/06/seri_lua_object.html
这个table用`is_rawarray`判断会认为是数组
```lua
local t = {
    [1] = "a",
    [2] = "b",
    [100] = "c",
}
```

发现 luaH_next函数5.4有所改动: `unsigned int asize = luaH_realasize(t);`.
上面示例执行时直接从hash part开始了

lua5.4
```c
int luaH_next (lua_State *L, Table *t, StkId key) {
  unsigned int asize = luaH_realasize(t);
  unsigned int i = findindex(L, t, s2v(key), asize);  /* find original key */
  for (; i < asize; i++) {  /* try first array part */
    if (!isempty(&t->array[i])) {  /* a non-empty entry? */
      setivalue(s2v(key), i + 1);
      setobj2s(L, key + 1, &t->array[i]);
      return 1;
    }
  }
  for (i -= asize; cast_int(i) < sizenode(t); i++) {  /* hash part */
    if (!isempty(gval(gnode(t, i)))) {  /* a non-empty entry? */
      Node *n = gnode(t, i);
      getnodekey(L, s2v(key), n);
      setobj2s(L, key + 1, gval(n));
      return 1;
    }
  }
  return 0;  /* no more elements */
}
```

lua5.3
```c
int luaH_next (lua_State *L, Table *t, StkId key) {
  unsigned int i = findindex(L, t, key);  /* find original element */
  for (; i < t->sizearray; i++) {  /* try first array part */
    if (!ttisnil(&t->array[i])) {  /* a non-nil value? */
      setivalue(key, i + 1);
      setobj2s(L, key+1, &t->array[i]);
      return 1;
    }
  }
  for (i -= t->sizearray; cast_int(i) < sizenode(t); i++) {  /* hash part */
    if (!ttisnil(gval(gnode(t, i)))) {  /* a non-nil value? */
      setobj2s(L, key, gkey(gnode(t, i)));
      setobj2s(L, key+1, gval(gnode(t, i)));
      return 1;
    }
  }
  return 0;  /* no more elements */
}
```

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/commit/58da8a1a223601f9c612b41d48d410a461edc0db 使用 lua_isinteger 更好。

**Comment by cloudwu** [comment]
这里前面的例子中，把带 [100] 的 table 误判为 rawarray 我觉得倒是小问题，无非少检查出一种错误的输入；而后面没有识别出 array 恐怕是个真正的问题。

**Comment by sniper00** [comment]
> 这里前面的例子中，把带 [100] 的 table 误判为 rawarray 我觉得倒是小问题，无非少检查出一种错误的输入；而后面没有识别出 array 恐怕是个真正的问题。

我是用来做`json`序列化库判断, 限定string key游戏业务许多数据定义开发不太方便，我做了个处理，序列化时把整数key转成字符串，反序列化时判断key是否为整数(一般检测第一个字符即可),转换失败还是按字符串处理。当然这样有一些限制，如这种情况就无法区分了：`["1"]=1,["2"]=2,["3"] =3,` 。游戏业务存库大多都是整数key, 或者 name, level 这样的字符串key。

**Comment by zhaoguoze** [comment]
> > > 这里前面的例子中，把带 [100] 的 table 误判为 rawarray 我觉得倒是小问题，无非少检查出一种错误的输入；而后面没有识别出 array 恐怕是个真正的问题。
> > 
> > 
> > 我是用来做`json`序列化库判断, 限定string key游戏业务许多数据定义开发不太方便，我做了个处理，序列化时把整数key转成字符串，反序列化时判断key是否为整数(一般检测第一个字符即可),转换失败还是按字符串处理。当然这样有一些限制，如这种情况就无法区分了：`["1"]=1,["2"]=2,["3"] =3,` 。游戏业务存库大多都是整数key, 或者 name, level 这样的字符串key。
> 
> 我选用的方法是在入库时给整数加前缀 `_i_` ，读取时删除前缀转为整数。你也可以参考一下
> 
> https://github.com/hanxi/skynet-demo/blob/master/README.md#bson-%E6%94%AF%E6%8C%81%E6%95%B4%E6%95%B0-key-mongodb-%E6%94%AF%E6%8C%81%E4%BF%9D%E5%AD%98%E6%95%B4%E6%95%B0-key

大佬我也想这么处理一下让bson和mongo支持整数 key，看你的链接里给删除了，是碰到什么问题了么？

**Comment by sniper00** [comment]
> > > > 这里前面的例子中，把带 [100] 的 table 误判为 rawarray 我觉得倒是小问题，无非少检查出一种错误的输入；而后面没有识别出 array 恐怕是个真正的问题。
> > > 
> > > 
> > > 我是用来做`json`序列化库判断, 限定string key游戏业务许多数据定义开发不太方便，我做了个处理，序列化时把整数key转成字符串，反序列化时判断key是否为整数(一般检测第一个字符即可),转换失败还是按字符串处理。当然这样有一些限制，如这种情况就无法区分了：`["1"]=1,["2"]=2,["3"] =3,` 。游戏业务存库大多都是整数key, 或者 name, level 这样的字符串key。
> > 
> > 
> > 我选用的方法是在入库时给整数加前缀 `_i_` ，读取时删除前缀转为整数。你也可以参考一下
> > https://github.com/hanxi/skynet-demo/blob/master/README.md#bson-%E6%94%AF%E6%8C%81%E6%95%B4%E6%95%B0-key-mongodb-%E6%94%AF%E6%8C%81%E4%BF%9D%E5%AD%98%E6%95%B4%E6%95%B0-key
> 
> 大佬我也想这么处理一下让bson和mongo支持整数 key，看你的链接里给删除了，是碰到什么问题了么？

This may help you:
https://github.com/sniper00/moon/blob/491a5bf418bc65272fa46ae41ce15ad43db0ac23/lualib-src/lua_json.cpp#L162
https://github.com/sniper00/moon/blob/491a5bf418bc65272fa46ae41ce15ad43db0ac23/lualib-src/lua_json.cpp#L274
https://github.com/sniper00/moon/blob/491a5bf418bc65272fa46ae41ce15ad43db0ac23/lualib-src/lua_json.cpp#L375

**Comment by hanxi** [comment]
> > > > 这里前面的例子中，把带 [100] 的 table 误判为 rawarray 我觉得倒是小问题，无非少检查出一种错误的输入；而后面没有识别出 array 恐怕是个真正的问题。
> > > 
> > > 
> > > 我是用来做`json`序列化库判断, 限定string key游戏业务许多数据定义开发不太方便，我做了个处理，序列化时把整数key转成字符串，反序列化时判断key是否为整数(一般检测第一个字符即可),转换失败还是按字符串处理。当然这样有一些限制，如这种情况就无法区分了：`["1"]=1,["2"]=2,["3"] =3,` 。游戏业务存库大多都是整数key, 或者 name, level 这样的字符串key。
> > 
> > 
> > 我选用的方法是在入库时给整数加前缀 `_i_` ，读取时删除前缀转为整数。你也可以参考一下
> > https://github.com/hanxi/skynet-demo/blob/master/README.md#bson-%E6%94%AF%E6%8C%81%E6%95%B4%E6%95%B0-key-mongodb-%E6%94%AF%E6%8C%81%E4%BF%9D%E5%AD%98%E6%95%B4%E6%95%B0-key
> 
> 大佬我也想这么处理一下让bson和mongo支持整数 key，看你的链接里给删除了，是碰到什么问题了么？

我清理代码时删掉了，在别人 fork 的里面可以找到： https://github.com/fumengame/skynet-demo/blob/f77c2d720fe82bf582505b8c7d7ab460a97e22fd/lualib-src/lua-bson.c

**Comment by cloudwu** [comment]
> 因为 bson 的标准中字典的 key 必须为 string （ https://github.com/cloudwu/skynet/blob/master/lualib-src/lua-bson.c#L465 ） ，而数组的 key 必须为数字 ( https://github.com/cloudwu/skynet/blob/master/lualib-src/lua-bson.c#L427 ) 。
> 
> 是不是这里判断 firstkey 是否为数字就足够了？

这对于检查错误不够。如果编码一个包含离散数字的 table ，这样判断会逃避报错。所以需要进一步判断 ： https://github.com/cloudwu/skynet/commit/58b1bda0d94b131044fcb6838f660decb1902467
