### ISSUE TITLE
skynet c扩展，使用malloc导致crashe

### ISSUE THREAD

**Issue by FashGek** [cloudwu/skynet#1485]
skynet 版本 1.3.0 （日志等代码有一些小改动，加了毫秒打印，其它底层没改）

错误信息：

Segmentation fault (core dumped)

代码A:
##########################
lencrypt(lua_State* L) {

	size_t sz;
	const char* text = luaL_tolstring(L, 1, &sz);

	printf("%s:%d  %s %d \n", __FILE__, __LINE__, text, sz);

	if (sz <= 0) {
		lua_pushstring(L, "");
		return 1;
	}
	char* ciphertext = (char*)skynet_malloc(sizeof(char)*sz);
	memset(ciphertext, 0, sizeof(char)*sz);
	//char ciphertext[512] = {0};

	if (crypto_box_easy(ciphertext, (const unsigned char*)text, sz, nonce, bobpk, alicesk) != 0){
		printf("%s:%d  \n", __FILE__, __LINE__);
				lua_pushstring(L, "");
		//
	} else {
		printf("%s:%d  \n", __FILE__, __LINE__);
		lua_pushstring(L, ciphertext);
		//printf("%s:%d  %s %d \n", __FILE__, __LINE__, ciphertext, sz);

	}
	printf("%s:%d  \n", __FILE__, __LINE__);
	skynet_free(ciphertext); ciphertext = NULL;
	return 1;

}
##########################
代码说明：
只要使用malloc分配空间给ciphertext，就有crashe，如果分配在栈上就没有问题

**Comment by cloudwu** [comment]
你如何保证 `lua_pushstring(L, ciphertext);` 这个 ciphertext 指向内存是 \0 结束？
以后这种问题请自行仔细调试。

ps. 学学 markdown 语法，好好排版代码。

**Comment by FashGek** [comment]
风大说得有道理，crypto_box_easy，有可能在加密之后，会比原始的文本长，虽然我在开始处memset了，但加密之后有可能最后一个字符已经不是0了，我测试下
