### ISSUE TITLE
debug console task 命令不返回

### ISSUE THREAD

**Issue by ZhouJiaZhi** [cloudwu/skynet#1506]
把高位地址改成不存在的地址就会阻塞，预期是能返回一个报错
```
task :010000ff
./skynet/lualib/skynet.lua:605: call to invalid address :010000ff
<CMD Error>

task :110000ff
后面就一直阻塞了

```

**Comment by cloudwu** [comment]
这是一个 feature 。

在 harbor 模式下，底层会缓存所有远程节点的数据，直到远程节点连上。

目前已不推荐使用 harbor 模式，它仅为兼容老项目。你可以通过在 config 中设置 harbor = 0 关闭它。

**Comment by ZhouJiaZhi** [comment]
试了下harbor = 0， 还是会阻塞。

**Comment by cloudwu** [comment]
关闭 Harbor 模式后，应该将所有 remote 节点都关闭，这样才能在向任何远程节点发送信息时报错。现在应该修好了。
