### ISSUE TITLE
datasheet热更时可能存在内存泄露

### ISSUE THREAD

**Issue by etnlGD** [cloudwu/skynet#1508]
在调用 `builder.new` 创建一个datasheet时，初始的引用计数是1，有新的customer后引用计数+1。但是只有customer完成数据热更后才会通知datasheet服务将其引用计数减1。

下面的代码，可以复现：
```
builder.new("foobar", {a = 1, b = 2 , c = {3} })

skynet.sleep(100)

builder.update("foobar", { b = 4, c = { 5 } })
```
期望的结果是，datasheet服务会response collect命令，但是并不会。

如果不sleep 1秒的话，由于第二个update命令会比collect命令更早到达datasheet服务，`datasheet.collect` 中检测到handle已经发生变化，会调用 `skynet.ret()` 来response collect命令，这种情况下不会存在泄漏。

**Comment by cloudwu** [comment]
builder.new 创建的名字现在是无法删除的，会且只会保存最后一个版本。如果你指的是这个，那么，这是一个特性而不是 bug 。

如果你想清理最后一个版本的内存，可以考虑用 builder.update 一个空表，让最后一个版本尽量少占用额外的内存。

ps. 那个 sleep 并不会影响任何东西，行为是一样的。前一个版本都会得到清理。你可以自行加 log 确认。

**Comment by etnlGD** [comment]
又确认了一遍，确实没有问题，之前误以为datasheet.release只有customer会调用。
然后昨天测试时，可能加了日志忘记保存还是咋的，导致日志输出和预期不一致。刚才重新试了下没有问题。

打扰了~
