### ISSUE TITLE
newservice 报错， 偶现

### ISSUE THREAD

**Issue by lsx1994** [cloudwu/skynet#1509]
1000个机器人创建1000个服务，测试了10次， 只有2次报了这个错误。
请问大概原因会是什么？
![Z8JHR8PTM@ 1M ` K%`BF8](https://user-images.githubusercontent.com/66242418/144223393-049feacf-f4d8-4b7b-b49d-ccc824bdd541.png)
![QY{$Y0YR AN2K({}Y0 9GQO](https://user-images.githubusercontent.com/66242418/144223401-1c50e5cf-10c0-4120-be13-3c2ecb0845ef.png)

**Comment by cloudwu** [comment]
1. 不要贴屏幕截图。学一下  markdown 语法，贴文本。
2. 查看一下你进程能打开文件上限。

**Comment by lsx1994** [comment]
> 

非常感谢， 我下次一定注意。
应该就是上限问题，我虚拟机配置调的很低，明天回公司测试下。
