### ISSUE TITLE
mysql的事务如何正确执行

### ISSUE THREAD

**Issue by lqflyc** [cloudwu/skynet#1512]
构造如下简单事务

> db:qurey("start transaction;") -- A
> if db:query("select sleep(5);").badresult then  -- 等待一定秒数 -- B
> &nbsp;&nbsp;&nbsp;&nbsp;db:query("rollback") -- C
> else
> &nbsp;&nbsp;&nbsp;&nbsp;db:query("commit") -- D
> end

多次发送消息到dbserver执行上述语句
因为db:query会等待mysql返回导致当前协程挂起
故上述执行时序有可能变成如下
A1->B1(等待)->A2->B2(等待)->D1->D2
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;B1出错->C1(回滚所有的语句)
显然这个时序对事务来说是灾难的错误, B2有可能被回滚了

暂时能想到的方案类似读写锁的方式:
&nbsp;&nbsp;&nbsp;&nbsp;如果没有任何sql正在执行, 事务执行则开启一个skynet.queue, 后续任何sql执行则阻塞
&nbsp;&nbsp;&nbsp;&nbsp;如果有任何非事务正在执行, 事务开启一个skyet.queue, 事务自己阻塞等待
&nbsp;&nbsp;&nbsp;&nbsp;对于非事务碰到queue则挂起, 否则正常执行
    
但是上述方案我感觉麻烦, 问一下大家是否有更好的方案

**Comment by hanxi** [comment]
可以试试写存储过程

**Comment by lqflyc** [comment]
写存储过程算是一种解决方案，但做起来确实还是非常麻烦，存储过程不太适合做复杂的操作。
我想了一种另外的通用方式，把一个事务所有的sql语句收集起来，集中发送到通用的存储过程。在存储过程中遍历这些sql语句，并解决因sql执行错误导致的rollback问题。

我觉得这个问题本质上还是因为时序引起的资源竞争，跟多线程的资源竞争一样，理论上应该要通过锁来解决。
一是对于数据库来说，多并发可能会加剧脏数据的产生，上面的存储过程同样有这样的问题(对于同一个mysql连接，我暂时不知道mysql内部会不会同时执行多个sql语句)。
二是skynet.queue其实只是一个简单的等待队列，细节全被封装到了函数中，队列的长度无法得到，不适合用来模拟锁。
三是或许可以用lua5.4的close模拟锁，锁超过作用域自动唤醒锁上的协程，不需要再额外将queue的代码用函数包装起来，从而做到不打断流程。

后面我想用方案三来解决这个问题，希望大家有更好的建议可以聊一下，毕竟因为协程挂起的产生的时序问题还是相对多的

**Comment by Gowa2017** [comment]
这个是因为 mysql  sknet 是在一个会话内执行的。所以这个问题还真有点意思了。

**Comment by cloudwu** [comment]
你可以给你的 dbserver 加一个 session 机制。多步操作都需要打开 session 和关闭 session 。同一个 session 不结束，新 session 就需要新建连接。

session 号可以自动生成，用服务号加自增 id 。

**Comment by lqflyc** [comment]
> 你可以给你的 dbserver 加一个 session 机制。多步操作都需要打开 session 和关闭 session 。同一个 session 不结束，新 session 就需要新建连接。
> 
> session 号可以自动生成，用服务号加自增 id 。

感谢云大的指点

这对于并发引起的资源竞争是一个比较简洁的方案，有其它类似的情况可以使用这种方案。
对于dbserver来说，mysql的新建连接代价有点大，通过连接池可以减少代价。
后面我用这种方案实现，可以不用建立session机制，多步操作就从连接池里拿一个连接，单步的走固定的连接。

挂两天看看还有其他朋友的方案没有，没有的话我就后面就关掉它。
