### ISSUE TITLE
redis连接时，有可能因为在进行auth或selectdb时连接断开而被阻塞

### ISSUE THREAD

**Issue by yukun1984** [cloudwu/skynet#1513]
stack traceback:
        [C]: in function 'coroutine.yield'
        .././skynet/lualib/skynet.lua:390: in upvalue 'suspend_sleep'
        .././skynet/lualib/skynet.lua:416: in function 'skynet.manager.wait'
        .././skynet/lualib/skynet/socketchannel.lua:424: in upvalue 'block_connect'
        .././skynet/lualib/skynet/socketchannel.lua:482: in method 'request'
        .././skynet/lualib/skynet/db/redis.lua:155: in function <.././skynet/lualib/skynet/db/redis.lua:153>
        [C]: in function 'pcall'
        .././skynet/lualib/skynet/socketchannel.lua:333: in function <.././skynet/lualib/skynet/socketchannel.lua:269>
        (...tail calls...)
        .././skynet/lualib/skynet/socketchannel.lua:369: in upvalue 'try_connect'
        .././skynet/lualib/skynet/socketchannel.lua:427: in upvalue 'block_connect'
        .././skynet/lualib/skynet/socketchannel.lua:482: in function <.././skynet/lualib/skynet/socketchannel.lua:481>

我先暂时在进行connect时保存当前协程，在触发block_connect时进行一次对比避免阻塞来解决了

**Comment by yukun1984** [comment]
local function block_connect(self, once)
	local r = check_connection(self)
	if r ~= nil then
		return r
	end
	local err

	if #self.__connecting > 0 then
		-- connecting in other coroutine
		local co = coroutine.running()

		-- 检测自身是否连接协程，不是的话才需要阻塞
		if self.__connecting[1] ~= co then
			table.insert(self.__connecting, co)
			skynet.wait(co)
		end
	else
		self.__connecting[1] = coroutine.running()
		err = try_connect(self, once)
		for i=2, #self.__connecting do
			local co = self.__connecting[i]
			self.__connecting[i] = nil
			skynet.wakeup(co)
		end
		self.__connecting[1] = nil
	end

	r = check_connection(self)
	if r == nil then
		skynet.error(string.format("Connect to %s:%d failed (%s)", self.__host, self.__port, err))
		error(socket_error)
	else
		return r
	end
end

**Comment by cloudwu** [comment]
看看这样改行不行？https://github.com/cloudwu/skynet/commit/839975415d213e8d338d671f6e42a9c5cab5b4b8

**Comment by yukun1984** [comment]
感谢回复

因为重现比较麻烦，暂时没办法很快测出结果，不过看代码有些不太明白：
进入try_connect的协程中，它的co并没有被保存进__connecting，只是将self.__connecting[1]设置为了true，然后再次进入block_connect。那么__connecting中应该是找不到当前的co的，还是一样会被阻塞。

**Comment by cloudwu** [comment]
我的疏忽。

又看了一遍，我认为是 https://github.com/cloudwu/skynet/issues/715 这里引入的 bug 。

原本是考虑了在 auth 过程中的状态的，`check_connection` 会处理这个状态。正常连接时，会判断是否在 auth 过程，避免重复连接。

后来增加了对端关闭连接的判断。如果连接被对方断开，也应该判断是否在 auth 过程中，若是，则应该返回 false ，表示连接已经断开。这会引起 auth 过程中 request 出错，最终打断 auth 过程。

https://github.com/cloudwu/skynet/commit/208be03a6facb368892f7b0a85a2ae2850db692c

**Comment by yukun1984** [comment]
好的。感谢，我再更新试试

**Comment by yukun1984** [comment]
经过修改后，这个connect被阻塞在了等待dispatchthread的地方

stack traceback:
        [C]: in function 'coroutine.yield'
        .././skynet/lualib/skynet.lua:390: in upvalue 'suspend_sleep'
        .././skynet/lualib/skynet.lua:397: in function 'skynet.sleep'
        (...tail calls...)
        .././skynet/lualib/skynet/socketchannel.lua:319: in function <.././skynet/lualib/skynet/socketchannel.lua:269>
        (...tail calls...)
        .././skynet/lualib/skynet/socketchannel.lua:367: in upvalue 'try_connect'
        .././skynet/lualib/skynet/socketchannel.lua:429: in upvalue 'block_connect'
        .././skynet/lualib/skynet/socketchannel.lua:484: in function <.././skynet/lualib/skynet/socketchannel.lua:483>
        (...tail calls...)
        ../fwk/service/dbd/dbStorage.lua:229: in upvalue 'write'
        ../fwk/service/dbd/dbStorage.lua:258: in function 'dbStorage.set'
        ../fwk/service/dbd/strings/stringsDB.lua:18: in function <../fwk/service/dbd/strings/stringsDB.lua:14>
        [C]: in function 'skynet.pcall'
        ../fwk/service/dbd/strings/stringsDB.lua:85: in upvalue 'write'
        ../fwk/service/dbd/strings/stringsDB.lua:95: in method 'set'
        ../fwk/service/dbd/strings/stringsHandler.lua:73: in function 'strings.stringsHandler.set'
        ../fwk/service/dbd/protos.lua:226: in function <../fwk/service/dbd/protos.lua:213>
        [C]: in function 'xpcall'
        ../fwk/lib/utils/exceptionUtil.lua:57: in function 'exceptionUtil.xpcall'
        ../fwk/lib/service/snaxltd.lua:182: in upvalue 'dispatcher'
        ../fwk/lib/service/snaxltd.lua:218: in upvalue 'f'
        .././skynet/lualib/skynet.lua:280: in function <.././skynet/lualib/skynet.lua:252>



另外我打印了一些状态：
:0000001d>local _, redis = debug.getupvalue(_ENV.package.loaded.dbStorage.init, 1) local _, redisObj = debug.getupvalue(redis.execute, 1) local rds1 = redisObj[1] for k, v in pairs(rds1) do print(k, v) end
__result        table: 0x7f8828670fc0
__connecting    table: 0x7f8828671040
__dispatch_thread       thread: 0x7f8778513f48
__auth  function: 0x7f8828670ec0
__nodelay       true
__host  xxxxx.redis.rds.aliyuncs.com
__sock  false
__overload      false
__authcoroutine false
__closed        false
__thread        table: 0x7f8828670f80
__request       table: 0x7f8828670f40
__result_data   table: 0x7f8828671000
__port  6379

让我感到奇怪的是__dispatch_thread的状态。正常执行完应该把__dispatch_thread置为nil才对。

:0000001d>local _, redis = debug.getupvalue(_ENV.package.loaded.dbStorage.init, 1) local _, redisObj = debug.getupvalue(redis.execute, 1) local rds1 = redisObj[1] print(coroutine.status(rds1.__dispatch_thread)) print(debug.traceback(rds1.__dispatch_thread))
dead
stack traceback:


另外打印了socketpool的状态，这个服务有两个socket连接，其中一个是mysql，是正常状态，应该是id为48的socket，redis的连接socket应该是id为4980这个
:0000001d>local _, socket_pool = debug.getupvalue(_ENV.package.loaded["skynet.socket"].close, 1) for k, v in pairs(socket_pool) do for k1, v1 in pairs(v) do print(k1, v1) end end
protocol        TCP
id      48
connected       true
buffer  userdata: 0x7f882d8aef20
on_close        function: 0x7f882d403850
pool    table: 0x7f882d8aef80
connected       true
pool    table: 0x7f86237f4440
read_required   false
protocol        TCP
id      4980
buffer  userdata: 0x7f85f3592c60

**Comment by cloudwu** [comment]
邮件收到一个回复，但是 web 上没有？

**Comment by yukun1984** [comment]
我删除了，后续发现了问题，但我不确定是否我对socket加超时造成的，想再看看代码

**Comment by yukun1984** [comment]
之前阻塞时，我没拿到完整堆栈，以为是某种原因socket.open被阻塞了，所以加了超时机制，正常连接成功会用skynet.killthread掉skynet.timeout生成的co。我现在去掉了这个再重新测试

**Comment by yukun1984** [comment]
之前加了超时机制的代码：
local function connect(id, func, timeout)

	timeout = timeout or 1000

	local newbuffer
	if func == nil then
		newbuffer = driver.buffer()
	end
	local s = {
		id = id,
		buffer = newbuffer,
		pool = newbuffer and {},
		connected = false,
		connecting = true,
		read_required = false,
		co = false,
		callback = func,
		protocol = "TCP",
	}
	assert(not socket_pool[id], "socket is not closed")
	socket_pool[id] = s

	-- 添加timeout机制
	local co = coroutine.running()
    local timeoutCo
    local isTimeout = false

    if timeout then
        timeoutCo = skynet.timeout(timeout, function()
            isTimeout = true
            timeoutCo = nil
            skynet.wakeup(co)
        end)
    end

	suspend(s)

    if isTimeout then
        socket_pool[id] = nil
        return nil, "connect timeout"
    else
        if timeoutCo then
            local killco = skynet.killthread(timeoutCo)
            if not killco then
                skynet.error("cant find timeout thread", timeoutCo)
            end

            timeoutCo = nil
        end
	end

	local err = s.connecting
	s.connecting = nil
	if s.connected then
		return id
	else
		socket_pool[id] = nil
		return nil, err
	end
end


这是今天测试时遇到的问题：
阻塞在了等待__dispatch_thread上

stack traceback:
        [C]: in function 'coroutine.yield'
        .././skynet/lualib/skynet.lua:390: in upvalue 'suspend_sleep'
        .././skynet/lualib/skynet.lua:397: in function 'skynet.sleep'
        (...tail calls...)
        .././skynet/lualib/skynet/socketchannel.lua:319: in function <.././skynet/lualib/skynet/socketchannel.lua:269>
        (...tail calls...)
        .././skynet/lualib/skynet/socketchannel.lua:367: in upvalue 'try_connect'
        .././skynet/lualib/skynet/socketchannel.lua:429: in upvalue 'block_connect'
        .././skynet/lualib/skynet/socketchannel.lua:484: in function <.././skynet/lualib/skynet/socketchannel.lua:483>



:0000001d>local _, redis = debug.getupvalue(_ENV.package.loaded.dbStorage.init, 1) local _, redisObj = debug.getupvalue(redis.execute, 1) local rds1 = redisObj[1] for k, v in pairs(rds1) do print(k, v) end
__result        table: 0x7f8828670fc0
__connecting    table: 0x7f8828671040
__dispatch_thread       thread: 0x7f8778513f48
__auth  function: 0x7f8828670ec0
__nodelay       true
__host  xxxxx.redis.rds.aliyuncs.com
__sock  false
__overload      false
__authcoroutine false
__closed        false
__thread        table: 0x7f8828670f80
__request       table: 0x7f8828670f40
__result_data   table: 0x7f8828671000
__port  6379


但查看__dispatch_thread时，发现协程已经执行完成并且已经为dead状态（我怀疑是不是因为我增加超时机制的代码写出的问题）：

:0000001d>local _, redis = debug.getupvalue(_ENV.package.loaded.dbStorage.init, 1) local _, redisObj = debug.getupvalue(redis.execute, 1) local rds1 = redisObj[1] print(coroutine.status(rds1.__dispatch_thread)) print(debug.traceback(rds1.__dispatch_thread))
dead
stack traceback:


另外这是socket_pool的状态：
:0000001d>local _, socket_pool = debug.getupvalue(_ENV.package.loaded["skynet.socket"].close, 1) for k, v in pairs(socket_pool) do for k1, v1 in pairs(v) do print(k1, v1) end end
protocol        TCP
id      48
connected       true
buffer  userdata: 0x7f882d8aef20
on_close        function: 0x7f882d403850
pool    table: 0x7f882d8aef80
connected       true
pool    table: 0x7f86237f4440
read_required   false
protocol        TCP
id      4980
buffer  userdata: 0x7f85f3592c60

id为48的是mysql连接，正常状态，id为4980的是redis连接

**Comment by cloudwu** [comment]
你这个 timeout 实现是有问题的。因为如果超时就继续向后执行，但后续如果连上或断开、出错，依然会触发 wakeup ，这会出现你不希望的 wakeup 。另外，你这个 socket 也没有人去关闭它。

**Comment by yukun1984** [comment]
感谢指正

去掉超时代码后问题依然存在，猜测可能是因为__dispatch_thread调用时，在调用socket.close时被挂起了，后面某种原因这个协程被直接用coroutine.close掉了，所以才会导致状态为dead并且__dispatch_thread没有被置为nil。

我看了下skynet里面调用coroutine.close的地方不多，这个问题最有可能触发的情况是在skynet.lua里的suspend，当result为nil时。是不是因为在处理__dispatch_thread过程中挂起，然后又收到空的dispatch_message导致的问题？

**Comment by yukun1984** [comment]
在日志中确认了这个问题

12/14/21 13:27:48.82 [:0000001e] lua call [0 to :1e : 49594945 msgsz = 0] error : .././skynet/lualib/skynet.lua:859: .././skynet/lualib/skynet.lua:330: .././skynet/lualib/skynet/socketchannel.lua:218: attempt to index a boolean value (field '__sock')

**Comment by cloudwu** [comment]
这个问题的根本是 dispatch thread 在 fork 之后，开始运行之前，`__sock` 可能被关闭，这通常发生在 connecting 阶段，发生在 auth 过程而产生该问题的概率最大。

这也是 https://github.com/cloudwu/skynet/pull/1364 增加 onclose ，考虑不周造成的；最初改造 dispatch thread https://github.com/cloudwu/skynet/issues/877 时，本允许 `__sock` 在进入前先关闭。

**Comment by yukun1984** [comment]
好的。我再更新测试一下。

另外提个建议：skynet中的task命令，在遇到这种情况有大量任务堆积，那几乎没有什么作用。能不能提供一个将task堆栈分组的命令，将堆栈和数量给打印出来，这样排查问题会方便许多。

虽然说用lua脚本也能做到这个功能，但一是性能上较差，二是其实对使用者的门槛要求还是要高一些的，集成这个功能对降低skynet的排查问题使用门槛比较有好处。

**Comment by cloudwu** [comment]
你说的是 https://github.com/cloudwu/skynet/blob/master/lualib/skynet.lua#L1018 `skynet.uniqtask()`  ?

**Comment by yukun1984** [comment]
是的。尴尬。看来我还是得多看看代码和文档了
