### ISSUE TITLE
使用lua_sethook出现异常

### ISSUE THREAD

**Issue by HuangHuimian** [cloudwu/skynet#1516]
lua里调用c层 lua_sethook后，使用skynet.fork(function()end)卡住线程不返回
下面是简化代码
```
static void
_empty_hook(lua_State* L, lua_Debug* arv) {
}

static int
ltesthook(lua_State* L) {
    lua_sethook(L, _empty_hook, LUA_MASKCALL | LUA_MASKRET, 0);
    return 0;
}
```
```
   testhook()
   skynet.fork(function() end)
   print("never") -- 不会执行到
```

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/blob/master/service-src/service_snlua.c#L72

skynet 已经使用 hook 捕获 signal 。

**Comment by cloudwu** [comment]
我测试可以执行到。

但是 hook 本身有可能因为 signal 而出问题（不发 singal 则无影响）。

**Comment by HuangHuimian** [comment]
谢谢云大的回复
是另一个问题，使用lua_setallocf设置了新的ud导致的
看了下旧的ud是个struct snlua*
保留这个ud就正常了
自己的ud怎么传，这个有点麻烦
