### ISSUE TITLE
skynet内置lua-string.format报错

### ISSUE THREAD

**Issue by liqigit** [cloudwu/skynet#1530]
### 问题：
skynet最新版本内置的lua执行string.format("%06s", "a")出错
### 版本：
skynet commit_id：3c4f6737402bda058cd6e092d2605498d88cc239
### 日志：
```
string.format("%06s", "a")
stdin:1: invalid conversion specification: '%06s'
stack traceback:
	[C]: in function 'string.format'
	stdin:1: in main chunk
	[C]: in ?
```

**Comment by Gowa2017** [comment]
难道你不用 skynet 内置就不报错了？

**Comment by Gowa2017** [comment]
我想你需要这个：https://en.cppreference.com/w/c/io/fprintf

**Comment by liqigit** [comment]
> 难道你不用 skynet 内置就不报错了？

不好意思，是我搞错版本了。安装官方5.4.4后没有修改软连接，实际使用的还是官方旧的5.4.2版本，所以测试没问题

**Comment by liqigit** [comment]
> 难道你不用 skynet 内置就不报错了？

不好意思，是我搞错版本了。安装官方5.4.4后没有修改软连接，实际使用的还是官方旧的5.4.2版本，所以测试没问题
