### ISSUE TITLE
gate大并发情况下，cmem狂飙

### ISSUE THREAD

**Issue by bijiaoshenqi** [cloudwu/skynet#1551]
skynet版本：之前是1.4到1.5之间的一个版本，文中有提到。之后升到1.5，问题依旧。

最近一测之前的压测中，发现gate的cmem一直涨，但lua的mem不涨。同时top显示内存占用一直涨到60%左右。
直观反应是内存泄漏，但感觉并不像。因为到了60%之后，gate依旧可以正常收发消息。

压测的后半段，cmem显示total总共占用6281506504，:0000009e(这个就是gate service)5956114120。
这个数值和top中显示内存总共8126460kb, 58.8%的占用对不上，
这还不包括lua的内存占用,6281506504 / 8126460 / 1024 = 75%就已经超越了58%很多了。

连续2次压测跑完：
cmem:
```
:0000009e	5956114120
block	733135
total	7297152656
```
而top命令：
```
top - 19:28:36 up 3 days,  1:50,  3 users,  load average: 0.54, 0.39, 1.10
Tasks: 263 total,   1 running, 262 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.1 us,  2.5 sy,  0.0 ni, 95.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  7924284 total,   595036 free,  7211176 used,   118072 buff/cache
KiB Swap:  8126460 total,   828692 free,  7297768 used.   513228 avail Mem
27984 centos    20   0   10.8g   4.0g   1216 S   5.0 53.2 108:14.94 skynet
```
jmem的打印忘了复制。但之前每隔一会打印了一下，大致和top是对得上的，持续在4，5个G左右。

7297152656 / 7924284 / 1024 ~= 90%
单算cmem就和53.2%差距甚远

具体压测环境为：
* 单区单进程模式，战斗和gate为两个service, 压测时战斗只做定时同步转发。我们的gate仿照skynet里面的例子复制粘贴的。
* 我们的战斗是帧同步，100ms同步一次。压测同时在线跑3000人，捉对厮杀，一共1W人次。理论战斗峰值同步1k+场战斗。

gate负责的东西：
* 我发现pbc解码解的还挺快的，压根不是瓶颈，就直接在gate解码，然后send到其他service中去，其中就有战斗。不是redirect，发的是lua消息
* 接收其他service已经pbc.encode好的msg，直接socketdriver.send(fd, netpack.pack(msg, #msg))。msg有过大时分包逻辑，压测时没有触发分包逻辑。

排查1：
gate出来，解码，然后转发。一开始以为是这里，在send之后没有把之前从gateserver中来的原始msg skynet.trash掉导致内存泄漏。
结果不是，就算是加了skynet.trash(msg)，cmem该涨还是涨。

排查2：
既然不是gate向service发的问题，那就是gate向客户端发的问题
收到其他的service的东西然后socketdriver.send，我把这一步注释掉，然后压测，则cmem此时:0000009e 400672纹丝不动。

排查3：
那我不搞那么多同时战斗了。我拿50/50压测，(50同时在线/50总人次)
这次是偶现，概率50%，两次碰到一次cmem上升

排查4：
socketdriver.send之前打印memory.info()，之后打印memory.info()。
发现在一开始并发没有上来的时候，不会上涨，这次多了几百B，然后就又回去了。过了1分钟左右，并发上来了之后，开始上涨。
我打印了after-before的差值，一开始几十，几百，偶尔有1k左右，都回落了，但自从出现40960这个数字之后，cmem就像脱缰的野马一样开始飙升，然后就开始持续大量的出现40960。
但凡是40960，都没有回落。期间几百几十的，依旧回落。
全局搜skynet，也没看到有40960这个数字。
我查了一下jemalloc的手册，[这个网站](http://jemalloc.net/jemalloc.3.html) 40k是个size。

排查5：
同事有提到过很久以前碰到的一个关于jemalloc的问题，一个空skynet进程，会慢慢的吃内存，之后会稳定在这个百分比上，大概60%。单从百分比上讲，蛮像。
然后翻issue，翻到了这个  [大并发情况下，skynet基础例子main.lua的watchdog服务疑似内存泄露问题 #995](https://github.com/cloudwu/skynet/issues/995)
狠狠的激动了一下。因为项目用到的版本截止为这个：
clean时增加对macosx下的编译目录生效 (#1361)	a39c9b8	风---自由 <996442717qqcom@gmail.com>	Mar 11, 2021 at 3:18 PM
正好就是20号左右。所以，立马升级到tag1.5.0的位置。
然后，cmem该涨继续涨。

排查6：
又花了1天多的时间仔细的看socket_server.c这个里面发送的实现，也看了skynet_free的hook。
当socket能直接write的时候，写完就free了。
异步的给sendctrl_fd后，epoll之后的send_buffer，扫了high，low两个列表，也被write_buffer_free掉了，好像也没啥问题。

虽然经过3天的折腾，基本上感觉不是内存泄漏，应该不会oom，但看着cmem这个数值一直往上彪，有点心虚，万一真是内存泄漏呢。
希望云风大神有空的时候看一下。 @cloudwu

**Comment by bijiaoshenqi** [comment]
补充：最高峰值是，50%左右的CPU占用，理论上可以排除消息处理不过来，堆积导致的内存上升。

**Comment by cloudwu** [comment]
cmem 就是 skynet 明确申请的内存（且不是 lua 分配）。如果一直上涨就是泄漏，即分配出来的内存未释放。你有环境，且明确知道是特定服务下分配出来的内存，应该很容易定位是什么没释放。

**Comment by cloudwu** [comment]
netpack.pack 在 wiki 中已经特别强调过，不建议直接使用。它是一个内部模块。

而且它只接受一个参数，https://github.com/cloudwu/skynet/blob/master/lualib-src/lua-netpack.c#L437 如果你传两个参数，可能是没搞懂它在做什么。

如果你在发生数据包前后比较过内存，有所增长，那么那个 40k 更可能是你发送的数据包的长度。
