### ISSUE TITLE
rwlock 用C11 写锁地方有问题

### ISSUE THREAD

**Issue by wujin1989** [cloudwu/skynet#1552]
hihi,

static inline void
rwlock_wlock(struct rwlock *lock) {
	int clear = 0;
	while (!ATOM_CAS(&lock->write,clear,1)) {}
	while(ATOM_LOAD(&lock->read)) {}
}
clear 需要置位到0，如果一个线程获取了wlock后，第二个线程进来再获取wlock时，在while里判断第一次是失败，第二次循环后clear因为被C11原子置1了，导致第二次推出while循环。

static inline void
rwlock_wlock(struct rwlock *lock) {
	int clear = 0;
	while (!ATOM_CAS(&lock->write,clear,1)) **{clear = 0；**}
	while(ATOM_LOAD(&lock->read)) {}
}

**Comment by cloudwu** [comment]
是的。`__sync_bool_compare_and_swap` 和 `atomic_compare_exchange_weak` 接口不等价。
