### ISSUE TITLE
socket 关闭触发消息死循环

### ISSUE THREAD

**Issue by skynetlua** [cloudwu/skynet#1555]
-- SKYNET_SOCKET_TYPE_CLOSE = 3
socket_message[3] = function(id)
	local s = socket_pool[id]
	if s then
		s.connected = false
		wakeup(s)
	else
		driver.close(id)
	end
	local cb = socket_onclose[id]
	if cb then
		cb(id)
		socket_onclose[id] = nil
	end
end

driver.close(id) 发消息给socket线程。socket线程会发SKYNET_SOCKET_TYPE_CLOSE消息。又回来了。导致雪崩式死循环

**Comment by cloudwu** [comment]
我不认为 SKYNET_SOCKET_TYPE_CLOSE 会不断发出。底层发送该消息是由 socket 自身状态决定的，不是由 driver.close() 触发的。

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/blob/master/skynet-src/socket_server.c#L1123
