### ISSUE TITLE
socket智能调整一次读取数据块长度机制的疑问

### ISSUE THREAD

**Issue by samoyedsun** [cloudwu/skynet#1566]
近期偶然间想分析一下skynet部分源码，试图从中学习一些编程技巧用到自己的项目中。
然后分析到网络数据读取到转化成数据包的过程这里看到以下机制。
感觉云大在这块代码上应该有出于提高并发量的目的，但我没有证据，
希望各位大佬有时间给小弟解解惑。
```c
	if (n == sz) {
		s->p.size *= 2;
		return SOCKET_MORE;
	} else if (sz > MIN_READ_BUFFER && n*2 < sz) {
		s->p.size /= 2;
	}
```

**Comment by ylme** [comment]
首先 [read](https://github.com/cloudwu/skynet/blob/master/skynet-src/socket_server.c#L1405) 出的数据会直接抛给业务层，skynet 中的网关模块用到的[接收缓冲区](https://github.com/cloudwu/skynet/blob/master/lualib-src/lua-netpack.c#L338)和 socket 模块用到的[接收缓冲区](https://github.com/cloudwu/skynet/blob/master/lualib-src/lua-socket.c#L104)都会将此数据记录下来，用于处理 TCP 分包，skynet 想要的效果就是期望读取的字节数与实际读取的字节数接近，增加分配出的接收缓冲区中的内存使用率，避免浪费。
所以
* n == sz 时，期望的读取的数据都读完了，一般都会假设内核接收缓冲区中有更多的数据，所以增加下一次期望读取的字节数。
* n < sz 时，实际读取的自己数比期望的少，一般都会假设接收的数据变少了，所以当 sz > MIN_READ_BUFFER && n*2 < sz 时，就减少下次期望读取的字节数，避免浪费内存。

**Comment by samoyedsun** [comment]
> 首先 [read](https://github.com/cloudwu/skynet/blob/master/skynet-src/socket_server.c#L1405) 出的数据会直接抛给业务层，skynet 中的网关模块用到的[接收缓冲区](https://github.com/cloudwu/skynet/blob/master/lualib-src/lua-netpack.c#L338)和 socket 模块用到的[接收缓冲区](https://github.com/cloudwu/skynet/blob/master/lualib-src/lua-socket.c#L104)都会将此数据记录下来，用于处理 TCP 分包，skynet 想要的效果就是期望读取的字节数与实际读取的字节数接近，增加分配出的接收缓冲区中的内存使用率，避免浪费。 所以
> 
> * n == sz 时，期望的读取的数据都读完了，一般都会假设内核接收缓冲区中有更多的数据，所以增加下一次期望读取的字节数。
> * n < sz 时，实际读取的自己数比期望的少，一般都会假设接收的数据变少了，所以当 sz > MIN_READ_BUFFER && n*2 < sz 时，就减少下次期望读取的字节数，避免浪费内存。

thinks
