### ISSUE TITLE
MysqlDriver使用emoj的问题

### ISSUE THREAD

**Issue by SheepQi** [cloudwu/skynet#1592]
在将表及数据库的编码格式都修改为utf8mb4后。
在表中的varchar类型字段中插入带emoj字符的字符串会报错。报错提示如下:

SQL has error in db:fight_dblog. Msg:Incorrect string value: '\xF0\x9F\x98\x88' for column 'name' at row 1.

但是我在使用navicat链接mysql并使用命令行执行同一sql语句的情况下能够正确执行。

**Comment by aasdpiao** [comment]
```lua
local mode = "[\0\b\n\r\t\26\\\'\"]"
local replace = {
    ['\0'] = "\\0",
    ['\b'] = "\\b",
    ['\n'] = "\\n",
    ['\r'] = "\\r",
    ['\t'] = "\\t",
    ['\26'] = "\\Z",
    ['\\'] = "\\\\",
    ["'"] = "\\'",
    ['"'] = '\\"',
}
function escape(s)
    return string.gsub(s, mode, replace)
end

```
试试用这个处理一下看看

**Comment by cloudwu** [comment]
不太懂 mysql ，但是这似乎 utf8mb4 没起效果。默认的 utf8 最大只能 3 字节。

**Comment by SheepQi** [comment]
> ```lua
> local mode = "[\0\b\n\r\t\26\\\'\"]"
> local replace = {
>     ['\0'] = "\\0",
>     ['\b'] = "\\b",
>     ['\n'] = "\\n",
>     ['\r'] = "\\r",
>     ['\t'] = "\\t",
>     ['\26'] = "\\Z",
>     ['\\'] = "\\\\",
>     ["'"] = "\\'",
>     ['"'] = '\\"',
> }
> function escape(s)
>     return string.gsub(s, mode, replace)
> end
> ```
> 
> 试试用这个处理一

**Comment by SheepQi** [comment]
>

**Comment by SheepQi** [comment]
@aasdpiao 照着你这个尝试了下仍然会报错
@cloudwu 按云大你说的设置了charset=utf8mb4,也还是不行
mysql的字符集我设置的如下:
`
+--------------------------+----------------------------+
| Variable_name            | Value                      |
+--------------------------+----------------------------+
| character_set_client     | utf8mb4                    |
| character_set_connection | utf8mb4                    |
| character_set_database   | utf8mb4                    |
| character_set_filesystem | binary                     |
| character_set_results    | utf8mb4                    |
| character_set_server     | utf8mb4                    |
| character_set_system     | utf8                       |
| character_sets_dir       | /usr/share/mysql/charsets/ |
| collation_connection     | utf8mb4_general_ci         |
| collation_database       | utf8mb4_unicode_ci         |
| collation_server         | utf8mb4_unicode_ci         |
+--------------------------+----------------------------+
`
目前我是暂时把emoj给屏蔽掉了

**Comment by aasdpiao** [comment]
建议直接提供你在navicat执行时候的sql语句出来.

**Comment by aasdpiao** [comment]
```lua
local dbconfig = {
    host=mysqlhost,
    port=mysqlport,
    user=mysqluser,
    password=mysqlpass,
    max_packet_size = 1024 * 1024,
    charset="utf8mb4",
    compact_arrays = true
}

 mysql.connect(dbconfig)
```
这里设置charset试试看

**Comment by SheepQi** [comment]
这个是创建表
```sql
CREATE TABLE `user_info`  (
  `userid` bigint(20) NOT NULL COMMENT 'userid',
  `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '玩家名',
  `face_url` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '头像域名',
  `steamid` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '\"\"' COMMENT 'steamid',
  `create_time` int(11) NULL DEFAULT NULL COMMENT '创建时间',
  `login_time` int(11) NULL DEFAULT NULL COMMENT '最近一次登录的时间点',
  `logout_time` int(11) NULL DEFAULT NULL COMMENT '上次登出的时间点',
  `total_wins` int(11) NOT NULL DEFAULT 0 COMMENT '总获胜场次',
  PRIMARY KEY (`userid`) USING BTREE
) ENGINE = MyISAM CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;
````
这个是插入数据
```sql
INSERT INTO user_info VALUES('281474976710756210', '菜尾😈', '', '', 1635242256,1651131427,0,0);
```

**Comment by SheepQi** [comment]
> 

之前测试就是在这个位置设置的charset="utf8mb4"

**Comment by Gowa2017** [comment]
mysql 有多个级别的设置。数据库级别  服务器级别 客户端  会话级别。建议都看看

**Comment by SheepQi** [comment]
让人懵逼0-0？我刚试了下新建一个数据库然后再进行操作居然就可以了。
感谢各位热情的帮助(*^▽^*)。
看来是mysql需要把已有库删除了之后再导一遍表。
