### ISSUE TITLE
redis驱动的exists和sismember执行异常

### ISSUE THREAD

**Issue by ericzhanchina** [cloudwu/skynet#1616]
项目中使用了local redis = require "skynet.db.redis"  如果调用db:exists()  db:sismember()，都会返回false。读了一下代码，skynet.db.redis里面有两个代码是不是遗留的代码，应该删除才对？

function command:exists(key)
	local fd = self[1]
	return fd:request(compose_message ("EXISTS", key), read_boolean)
end

function command:sismember(key, value)
	local fd = self[1]
	return fd:request(compose_message ("SISMEMBER", table.pack(key, value)), read_boolean)
end

这两个方法我删除之后，调用一切正常了。

**Comment by cloudwu** [comment]
这是一个特性。

**Comment by ericzhanchina** [comment]
> 这是一个特性。

不是太理解特性的含义，麻烦云风大佬给解释一下吧。因为我看redis的command规范sismember是返回0 或者 1的，但是db:sismember()返回的是true false，如果把command:sismember删除了，db:sismember的调用就跟redis的command规范一致了，这两个方法的用处是什么呢？

**Comment by ericzhanchina** [comment]
> 这是一个特性。

云风的意思是，用这样的形式相当于覆盖了redis命令的标准返回是吧，如果不想用自行把这两个方法注释掉就好了，不知道我理解的对不对，哈哈

**Comment by ericzhanchina** [comment]
> 这是一个特性。

像exists已经从3.0开始支持多key查询了，是不是还覆盖exists方法就有问题了

**Comment by cloudwu** [comment]
因为 0 在 lua 中不是 false, 所以转换为 boolean 。
