### ISSUE TITLE
_new_server_ws 时 SSL_do_handshake error :1 ret:-1 . 用户连接时出现

### ISSUE THREAD

**Issue by NNbaba** [cloudwu/skynet#1617]
![323fa5514585f021161c77b0484e36b](https://user-images.githubusercontent.com/48234698/176070243-1e0bfe9e-bd04-48d3-a31b-2f4f5d64b1cb.png)
大量用户连接服务器时会有一定几率出现这个错误

**Comment by cloudwu** [comment]
@lvzixun 

btw， 贴文本不要截图。请学习 markdown 语法，自己稍作排版。

**Comment by NNbaba** [comment]
嗯，谢谢大佬，新手学习中，我改改



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月28日(星期二) 上午10:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cloudwu/skynet] _new_server_ws 时 SSL_do_handshake error :1 ret:-1 . 用户连接时出现 (Issue #1617)





 
@lvzixun
 
btw， 贴文本不要截图。请学习 markdown 语法，自己稍作排版。
