### ISSUE TITLE
未知原因crash

### ISSUE THREAD

**Issue by RiceCN** [cloudwu/skynet#1624]
> **skynet版本**使用的是**2022年5月份的**，出现过两次crash。使用**最新的skynet版本**还是会出现crash

1.  第一次crash，gdb调试结果如下： 

**Program terminated with signal 11, Segmentation fault.**
0  sweep2old (p=0x7f34a6c2ca00, L=0x7f34a5a1d508) at lgc.c:1059
1059    lgc.c: No such file or directory.
Missing separate debuginfos, use: debuginfo-install glibc-2.17-326.el7_9.x86_64 libgcc-4.8.5-44.el7.x86_64 libuuid-2.23.2-65.el7_9.1.x86_64 openssl11-libs-1.1.1k-4.el7.x86_64 zlib-1.2.7-20.el7_9.x86_64
(gdb) bt
0  **sweep2old** (p=0x7f34a6c2ca00, L=0x7f34a5a1d508) at lgc.c:1059
1  **atomic2gen** (g=0x7f34a5bbc5d0, L=0x7f34a5a1d508) at lgc.c:1276
2  **stepgenfull** (g=<optimized out>, L=<optimized out>) at lgc.c:1389
3  **genstep** (g=<optimized out>, L=<optimized out>) at lgc.c:1423
4  **luaC_step** (L=L@entry=0x7f34a5a1d508) at lgc.c:1692
5  0x00000000004447d9 in **luaV_execute** (L=L@entry=0x7f34a5a1d508, ci=<optimized out>, ci@entry=0x7f34a5a61d00) at lvm.c:1356
6  0x000000000042a7fb in **unroll** (L=0x7f34a5a1d508, ud=<optimized out>) at ldo.c:717
7  0x000000000042a21a in **luaD_rawrunprotected** (L=0x7f34a5a1d508, f=0x42c530 <resume>, ud=0x7f34ac7d9d7c) at ldo.c:144
8  0x000000000042d870 in **lua_resume** (L=0x7f34a5a1d508, from=<optimized out>, nargs=4, nresults=0x7f34ac7d9dcc) at ldo.c:822
9  0x00007f34adfe17ec in ?? ()
10 0x00007f34a5a61a40 in ?? ()
11 0x00007f34a5a1d428 in ?? ()
12 0x0000000000000001 in ?? ()
13 0x0000000000000000 in ?? ()

2. 第二次crash， gdb调试结果如下：

**Program terminated with signal 7, Bus error.**
0  0x00007f6aca24afe7 in OPENSSL_sk_dup () from /lib64/libcrypto.so.1.1
Missing separate debuginfos, use: debuginfo-install glibc-2.17-326.el7_9.x86_64 libgcc-4.8.5-44.el7.x86_64 libuuid-2.23.2-65.el7_9.1.x86_64 openssl11-libs-1.1.1k-4.el7.x86_64 zlib-1.2.7-20.el7_9.x86_64
(gdb) bt
0  0x00007f6aca24afe7 in **OPENSSL_sk_dup** () from /lib64/libcrypto.so.1.1
1  0x00007f6aca582838 in **SSL_new** () from /lib64/libssl.so.1.1
2  0x00007f6aca7d8994 in ?? ()
3  0x00007f6ac7bcebf8 in ?? ()
4  0x00007f6ac81c2a88 in ?? ()
5  0x00007f6ac7bcebf8 in ?? ()
6  0x00007f6aca7d8c72 in ?? ()
7  0x0000000000000000 in ?? ()

**Comment by cloudwu** [comment]
学习一下 markdown , 你这样会引用很多 issue

**Comment by RiceCN** [comment]
补充一点，skynet不是在root权限下跑的

**Comment by RiceCN** [comment]
> 学习一下 markdown , 你这样会引用很多 issue

好的，现在已经改了；请问skynet不在root权限下跑，是会有lua gc问题吗？

**Comment by RiceCN** [comment]
最新的crash gdb调试信息如下：

GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /data/app/slg/skynet/skynet...done.

warning: core file may not match specified executable file.
[New LWP 7641]
[New LWP 7633]
[New LWP 7643]
[New LWP 7635]
[New LWP 7642]
[New LWP 7640]
[New LWP 7639]
[New LWP 7638]
[New LWP 7637]
[New LWP 7636]

warning: Could not load shared library symbols for 12 libraries, e.g. ./../lib/loggerx.so.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/data/app/slg/skynet/skynet ../etc/loginAppConf'.
Program terminated with signal 11, Segmentation fault.
0  sweepgen (L=L@entry=0x7f2b11c867a8, p=0x7f2b0fd53b40, p@entry=0x7f2b11d57840, limit=0x7f2b10c06200, pfirstold1=pfirstold1@entry=0x7f2b11d578a8, g=0x7f2b11d577d0) at lgc.c:1107
1107    lgc.c: No such file or directory.
(gdb) bt
0  sweepgen (L=L@entry=0x7f2b11c867a8, p=0x7f2b0fd53b40, p@entry=0x7f2b11d57840, limit=0x7f2b10c06200, pfirstold1=pfirstold1@entry=0x7f2b11d578a8, g=0x7f2b11d577d0) at lgc.c:1107
1  0x00000000004292ab in youngcollection (g=0x7f2b11d577d0, L=0x7f2b11c867a8) at lgc.c:1245
2  genstep (g=0x7f2b11d577d0, L=0x7f2b11c867a8) at lgc.c:1440
3  luaC_step (L=L@entry=0x7f2b11c867a8) at lgc.c:1692
4  0x00000000004219f4 in lua_pushlstring (L=L@entry=0x7f2b11c867a8, s=<optimized out>, len=<optimized out>) at lapi.c:536
5  0x00000000004364ac in luaL_pushresult (B=B@entry=0x7f2b14ffd550) at lauxlib.c:596
6  0x000000000044398a in str_format (L=0x7f2b11c867a8) at lstrlib.c:1376
7  0x000000000042579d in precallC (f=0x4438b0 <str_format>, nresults=1, func=<optimized out>, L=0x7f2b11c867a8) at ldo.c:506
8  luaD_precall (L=L@entry=0x7f2b11c867a8, func=<optimized out>, func@entry=0x7f2b0f82ef60, nresults=1) at ldo.c:572
9  0x0000000000433a83 in luaV_execute (L=L@entry=0x7f2b11c867a8, ci=<optimized out>) at lvm.c:1638
10 0x00000000004259ce in ccall (inc=1, nResults=nResults@entry=-1, func=<optimized out>, L=L@entry=0x7f2b11c867a8) at ldo.c:609
11 luaD_call (L=L@entry=0x7f2b11c867a8, func=<optimized out>, nResults=nResults@entry=-1) at ldo.c:619
12 0x000000000042278f in lua_pcallk (L=L@entry=0x7f2b11c867a8, nargs=<optimized out>, nresults=nresults@entry=-1, errfunc=errfunc@entry=0, ctx=ctx@entry=0, k=k@entry=0x43cc00 <finishpcall>)
    at lapi.c:1081
13 0x000000000043cc90 in luaB_pcall (L=0x7f2b11c867a8) at lbaselib.c:477
14 0x000000000042579d in precallC (f=0x43cc40 <luaB_pcall>, nresults=4, func=<optimized out>, L=0x7f2b11c867a8) at ldo.c:506
15 luaD_precall (L=L@entry=0x7f2b11c867a8, func=<optimized out>, func@entry=0x7f2b0f82ee90, nresults=4) at ldo.c:572
16 0x0000000000433a83 in luaV_execute (L=L@entry=0x7f2b11c867a8, ci=<optimized out>, ci@entry=0x7f2b11d67e80) at lvm.c:1638
17 0x00000000004252f3 in unroll (L=0x7f2b11c867a8, ud=<optimized out>) at ldo.c:717
18 0x0000000000424a2a in luaD_rawrunprotected (L=L@entry=0x7f2b11c867a8, f=f@entry=0x4258a0 <resume>, ud=ud@entry=0x7f2b14ffdd7c) at ldo.c:144
19 0x0000000000425af4 in lua_resume (L=0x7f2b11c867a8, from=<optimized out>, nargs=4, nresults=0x7f2b14ffddbc) at ldo.c:822
20 0x00007f2b183e110d in ?? ()
21 0x00007f2b11d63ec0 in ?? ()
22 0x00000000004216e6 in lua_tointegerx (L=<optimized out>, idx=<optimized out>, pisnum=0x7f2b11c866c8) at lapi.c:395
23 0x00007f2b11d3bd80 in ?? ()
24 0x00007f2b11c866c8 in ?? ()
25 0x00007f2b11c866c8 in ?? ()
26 0x00007f2b11c866c8 in ?? ()
27 0x00007f2b11d6b280 in ?? ()
28 0x00007f2b183e1590 in ?? ()
29 0x00007f2b11d63ec0 in ?? ()
30 0x0000000000000006 in ?? ()
31 0x00007f2b183e15c0 in ?? ()
32 0x00007f2b11d78790 in ?? ()
33 0x00007f2b11d789f0 in ?? ()
34 0x00007f2b11c866c8 in ?? ()
35 0x0000000000425536 in precallC (f=0x7f2b14ffddc0, nresults=-1, func=<optimized out>, L=0x7f2b11c867a8) at ldo.c:506
36 luaD_pretailcall (L=0x7f2b11c867a8, L@entry=0x7f2b11c866c8, ci=ci@entry=0x7f2b11d63ec0, func=<optimized out>, func@entry=0x7f2b11d78850, narg1=<ptimized out>, delta=delta@entry=6) at ldo.c:527
37 0x0000000000433be1 in luaV_execute (L=L@entry=0x7f2b11c866c8, ci=<optimized out>) at lvm.c:1662
38 0x0000000000425a40 in ccall (inc=65537, nResults=<optimized out>, func=<optimized out>, L=0x7f2b11c866c8) at ldo.c:609
39 luaD_callnoyield (L=0x7f2b11c866c8, func=<optimized out>, nResults=<optimized out>) at ldo.c:627
40 0x0000000000424a2a in luaD_rawrunprotected (L=L@entry=0x7f2b11c866c8, f=f@entry=0x420f70 <f_call>, ud=ud@entry=0x7f2b14ffe0b0) at ldo.c:144
41 0x0000000000425d3e in luaD_pcall (L=L@entry=0x7f2b11c866c8, func=func@entry=0x420f70 <f_call>, u=u@entry=0x7f2b14ffe0b0, old_top=192, ef=<optimized out>) at ldo.c:926
42 0x00000000004226e9 in lua_pcallk (L=L@entry=0x7f2b11c866c8, nargs=<optimized out>, nresults=nresults@entry=-1, errfunc=errfunc@entry=0, ctx=ctx@entry=0, k=k@entry=0x43cc00 <finishpcall>)
    at lapi.c:1069
43 0x000000000043cc90 in luaB_pcall (L=0x7f2b11c866c8) at lbaselib.c:477
44 0x000000000042579d in precallC (f=0x43cc40 <luaB_pcall>, nresults=2, func=<optimized out>, L=0x7f2b11c866c8) at ldo.c:506
45 luaD_precall (L=L@entry=0x7f2b11c866c8, func=<optimized out>, func@entry=0x7f2b11d786a0, nresults=2) at ldo.c:572
46 0x0000000000433a83 in luaV_execute (L=L@entry=0x7f2b11c866c8, ci=<optimized out>) at lvm.c:1638
47 0x0000000000425a40 in ccall (inc=65537, nResults=<optimized out>, func=<optimized out>, L=0x7f2b11c866c8) at ldo.c:609
48 luaD_callnoyield (L=0x7f2b11c866c8, func=<optimized out>, nResults=<optimized out>) at ldo.c:627
49 0x0000000000424a2a in luaD_rawrunprotected (L=L@entry=0x7f2b11c866c8, f=f@entry=0x420f70 <f_call>, ud=ud@entry=0x7f2b14ffe370) at ldo.c:144
50 0x0000000000425d3e in luaD_pcall (L=L@entry=0x7f2b11c866c8, func=func@entry=0x420f70 <f_call>, u=u@entry=0x7f2b14ffe370, old_top=48, ef=<optimized out>) at ldo.c:926
51 0x00000000004226e9 in lua_pcallk (L=0x7f2b11c866c8, nargs=<optimized out>, nresults=0, errfunc=<optimized out>, ctx=<optimized out>, k=<optimized out>) at lapi.c:1069
52 0x00007f2b12fe748f in ?? ()
53 0x0000000000000000 in ?? ()

**Comment by RiceCN** [comment]
> 学习一下 markdown , 你这样会引用很多 issue

云大能否帮看下这个问题？

**Comment by RiceCN** [comment]
> 学习一下 markdown , 你这样会引用很多 issue

好的，已经改了

**Comment by RiceCN** [comment]
> 最新的crash gdb调试信息如下：
> 
> GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7 Copyright (C) 2013 Free Software Foundation, Inc. License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law. Type "show copying" and "show warranty" for details. This GDB was configured as "x86_64-redhat-linux-gnu". For bug reporting instructions, please see: http://www.gnu.org/software/gdb/bugs/... Reading symbols from /data/app/slg/skynet/skynet...done.
> 
> warning: core file may not match specified executable file. [New LWP 7641] [New LWP 7633] [New LWP 7643] [New LWP 7635] [New LWP 7642] [New LWP 7640] [New LWP 7639] [New LWP 7638] [New LWP 7637] [New LWP 7636]
> 
> warning: Could not load shared library symbols for 12 libraries, e.g. ./../lib/loggerx.so. Use the "info sharedlibrary" command to see the complete listing. Do you need "set solib-search-path" or "set sysroot"? [Thread debugging using libthread_db enabled] Using host libthread_db library "/lib64/libthread_db.so.1". Core was generated by `/data/app/slg/skynet/skynet ../etc/loginAppConf'. Program terminated with signal 11, Segmentation fault. 0 sweepgen (L=L@entry=0x7f2b11c867a8, p=0x7f2b0fd53b40, p@entry=0x7f2b11d57840, limit=0x7f2b10c06200, pfirstold1=pfirstold1@entry=0x7f2b11d578a8, g=0x7f2b11d577d0) at lgc.c:1107 1107 lgc.c: No such file or directory. (gdb) bt 0 sweepgen (L=L@entry=0x7f2b11c867a8, p=0x7f2b0fd53b40, p@entry=0x7f2b11d57840, limit=0x7f2b10c06200, pfirstold1=pfirstold1@entry=0x7f2b11d578a8, g=0x7f2b11d577d0) at lgc.c:1107 1 0x00000000004292ab in youngcollection (g=0x7f2b11d577d0, L=0x7f2b11c867a8) at lgc.c:1245 2 genstep (g=0x7f2b11d577d0, L=0x7f2b11c867a8) at lgc.c:1440 3 luaC_step (L=L@entry=0x7f2b11c867a8) at lgc.c:1692 4 0x00000000004219f4 in lua_pushlstring (L=L@entry=0x7f2b11c867a8, s=, len=) at lapi.c:536 5 0x00000000004364ac in luaL_pushresult (B=B@entry=0x7f2b14ffd550) at lauxlib.c:596 6 0x000000000044398a in str_format (L=0x7f2b11c867a8) at lstrlib.c:1376 7 0x000000000042579d in precallC (f=0x4438b0 <str_format>, nresults=1, func=, L=0x7f2b11c867a8) at ldo.c:506 8 luaD_precall (L=L@entry=0x7f2b11c867a8, func=, func@entry=0x7f2b0f82ef60, nresults=1) at ldo.c:572 9 0x0000000000433a83 in luaV_execute (L=L@entry=0x7f2b11c867a8, ci=) at lvm.c:1638 10 0x00000000004259ce in ccall (inc=1, nResults=nResults@entry=-1, func=, L=L@entry=0x7f2b11c867a8) at ldo.c:609 11 luaD_call (L=L@entry=0x7f2b11c867a8, func=, nResults=nResults@entry=-1) at ldo.c:619 12 0x000000000042278f in lua_pcallk (L=L@entry=0x7f2b11c867a8, nargs=, nresults=nresults@entry=-1, errfunc=errfunc@entry=0, ctx=ctx@entry=0, k=k@entry=0x43cc00 ) at lapi.c:1081 13 0x000000000043cc90 in luaB_pcall (L=0x7f2b11c867a8) at lbaselib.c:477 14 0x000000000042579d in precallC (f=0x43cc40 <luaB_pcall>, nresults=4, func=, L=0x7f2b11c867a8) at ldo.c:506 15 luaD_precall (L=L@entry=0x7f2b11c867a8, func=, func@entry=0x7f2b0f82ee90, nresults=4) at ldo.c:572 16 0x0000000000433a83 in luaV_execute (L=L@entry=0x7f2b11c867a8, ci=, ci@entry=0x7f2b11d67e80) at lvm.c:1638 17 0x00000000004252f3 in unroll (L=0x7f2b11c867a8, ud=) at ldo.c:717 18 0x0000000000424a2a in luaD_rawrunprotected (L=L@entry=0x7f2b11c867a8, f=f@entry=0x4258a0 , ud=ud@entry=0x7f2b14ffdd7c) at ldo.c:144 19 0x0000000000425af4 in lua_resume (L=0x7f2b11c867a8, from=, nargs=4, nresults=0x7f2b14ffddbc) at ldo.c:822 20 0x00007f2b183e110d in ?? () 21 0x00007f2b11d63ec0 in ?? () 22 0x00000000004216e6 in lua_tointegerx (L=, idx=, pisnum=0x7f2b11c866c8) at lapi.c:395 23 0x00007f2b11d3bd80 in ?? () 24 0x00007f2b11c866c8 in ?? () 25 0x00007f2b11c866c8 in ?? () 26 0x00007f2b11c866c8 in ?? () 27 0x00007f2b11d6b280 in ?? () 28 0x00007f2b183e1590 in ?? () 29 0x00007f2b11d63ec0 in ?? () 30 0x0000000000000006 in ?? () 31 0x00007f2b183e15c0 in ?? () 32 0x00007f2b11d78790 in ?? () 33 0x00007f2b11d789f0 in ?? () 34 0x00007f2b11c866c8 in ?? () 35 0x0000000000425536 in precallC (f=0x7f2b14ffddc0, nresults=-1, func=, L=0x7f2b11c867a8) at ldo.c:506 36 luaD_pretailcall (L=0x7f2b11c867a8, L@entry=0x7f2b11c866c8, ci=ci@entry=0x7f2b11d63ec0, func=, func@entry=0x7f2b11d78850, narg1=, delta=delta@entry=6) at ldo.c:527 37 0x0000000000433be1 in luaV_execute (L=L@entry=0x7f2b11c866c8, ci=) at lvm.c:1662 38 0x0000000000425a40 in ccall (inc=65537, nResults=, func=, L=0x7f2b11c866c8) at ldo.c:609 39 luaD_callnoyield (L=0x7f2b11c866c8, func=, nResults=) at ldo.c:627 40 0x0000000000424a2a in luaD_rawrunprotected (L=L@entry=0x7f2b11c866c8, f=f@entry=0x420f70 <f_call>, ud=ud@entry=0x7f2b14ffe0b0) at ldo.c:144 41 0x0000000000425d3e in luaD_pcall (L=L@entry=0x7f2b11c866c8, func=func@entry=0x420f70 <f_call>, u=u@entry=0x7f2b14ffe0b0, old_top=192, ef=) at ldo.c:926 42 0x00000000004226e9 in lua_pcallk (L=L@entry=0x7f2b11c866c8, nargs=, nresults=nresults@entry=-1, errfunc=errfunc@entry=0, ctx=ctx@entry=0, k=k@entry=0x43cc00 ) at lapi.c:1069 43 0x000000000043cc90 in luaB_pcall (L=0x7f2b11c866c8) at lbaselib.c:477 44 0x000000000042579d in precallC (f=0x43cc40 <luaB_pcall>, nresults=2, func=, L=0x7f2b11c866c8) at ldo.c:506 45 luaD_precall (L=L@entry=0x7f2b11c866c8, func=, func@entry=0x7f2b11d786a0, nresults=2) at ldo.c:572 46 0x0000000000433a83 in luaV_execute (L=L@entry=0x7f2b11c866c8, ci=) at lvm.c:1638 47 0x0000000000425a40 in ccall (inc=65537, nResults=, func=, L=0x7f2b11c866c8) at ldo.c:609 48 luaD_callnoyield (L=0x7f2b11c866c8, func=, nResults=) at ldo.c:627 49 0x0000000000424a2a in luaD_rawrunprotected (L=L@entry=0x7f2b11c866c8, f=f@entry=0x420f70 <f_call>, ud=ud@entry=0x7f2b14ffe370) at ldo.c:144 50 0x0000000000425d3e in luaD_pcall (L=L@entry=0x7f2b11c866c8, func=func@entry=0x420f70 <f_call>, u=u@entry=0x7f2b14ffe370, old_top=48, ef=) at ldo.c:926 51 0x00000000004226e9 in lua_pcallk (L=0x7f2b11c866c8, nargs=, nresults=0, errfunc=, ctx=, k=) at lapi.c:1069 52 0x00007f2b12fe748f in ?? () 53 0x0000000000000000 in ?? ()

这个能直接调试 core文件吗

**Comment by RiceCN** [comment]
> 

这个能直接调试core文件吗？

**Comment by RiceCN** [comment]
最新gdb core文件调试输出：

GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /data/app/slg/skynet/skynet...done.

warning: core file may not match specified executable file.
[New LWP 5366]
[New LWP 5369]
[New LWP 5368]
[New LWP 5359]
[New LWP 5363]
[New LWP 5365]
[New LWP 5361]
[New LWP 5370]
[New LWP 5371]
[New LWP 5362]
[New LWP 5367]
[New LWP 5364]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/data/app/slg/skynet/gameApp_slg_S1 ../etc/gameAppConf'.
Program terminated with signal 11, Segmentation fault.
0  whitelist (g=g@entry=0x7f5c56a91fd0, p=0x7972746e756f4350) at lgc.c:1139
1139    lgc.c: No such file or directory.
(gdb) bt
0  whitelist (g=g@entry=0x7f5c56a91fd0, p=0x7972746e756f4350) at lgc.c:1139
1  enterinc (g=g@entry=0x7f5c56a91fd0) at lgc.c:1316
2  0x00000000004293d3 in fullgen (g=0x7f5c56a91fd0, L=0x7f5c5d7a8ae8) at lgc.c:1346
3  genstep (g=0x7f5c56a91fd0, L=0x7f5c5d7a8ae8) at lgc.c:1428
4  luaC_step (L=L@entry=0x7f5c5d7a8ae8) at lgc.c:1692
5  0x000000000043461e in luaV_execute (L=L@entry=0x7f5c5d7a8ae8, ci=<optimized out>) at lvm.c:1356
6  0x00000000004259ce in ccall (inc=1, nResults=nResults@entry=-1, func=<optimized out>, L=L@entry=0x7f5c5d7a8ae8) at ldo.c:609
7  luaD_call (L=L@entry=0x7f5c5d7a8ae8, func=<optimized out>, nResults=nResults@entry=-1) at ldo.c:619
8  0x000000000042278f in lua_pcallk (L=L@entry=0x7f5c5d7a8ae8, nargs=<optimized out>, nresults=nresults@entry=-1, errfunc=errfunc@entry=0, ctx=ctx@entry=0, 
    k=k@entry=0x43cc00 <finishpcall>) at lapi.c:1081
9  0x000000000043cc90 in luaB_pcall (L=0x7f5c5d7a8ae8) at lbaselib.c:477
10 0x000000000042579d in precallC (f=0x43cc40 <luaB_pcall>, nresults=2, func=<optimized out>, L=0x7f5c5d7a8ae8) at ldo.c:506
11 luaD_precall (L=L@entry=0x7f5c5d7a8ae8, func=<optimized out>, func@entry=0x7f5c6f819960, nresults=2) at ldo.c:572
12 0x0000000000433a83 in luaV_execute (L=L@entry=0x7f5c5d7a8ae8, ci=<optimized out>, ci@entry=0x7f5c52db6040) at lvm.c:1638
13 0x00000000004252f3 in unroll (L=0x7f5c5d7a8ae8, ud=<optimized out>) at ldo.c:717
14 0x0000000000424a2a in luaD_rawrunprotected (L=L@entry=0x7f5c5d7a8ae8, f=f@entry=0x4258a0 <resume>, ud=ud@entry=0x7f5caa3d7d7c) at ldo.c:144
15 0x0000000000425af4 in lua_resume (L=L@entry=0x7f5c5d7a8ae8, from=from@entry=0x7f5c639d4948, nargs=nargs@entry=5, nresults=nresults@entry=0x7f5caa3d7dbc)
    at ldo.c:822
16 0x00007f5cc99e110d in lua_resumeX (nresults=0x7f5caa3d7dbc, nargs=5, from=0x7f5c639d4948, L=0x7f5c5d7a8ae8) at service-src/service_snlua.c:90
17 auxresume (narg=5, co=0x7f5c5d7a8ae8, L=0x7f5c639d4948) at service-src/service_snlua.c:146
18 timing_resume (L=L@entry=0x7f5c639d4948, co_index=co_index@entry=1, n=5) at service-src/service_snlua.c:198
19 0x00007f5cc99e15c0 in luaB_coresume (L=0x7f5c639d4948) at service-src/service_snlua.c:217
20 0x0000000000425536 in precallC (f=0x7f5cc99e1590 <luaB_coresume>, nresults=-1, func=<optimized out>, L=0x7f5c639d4948) at ldo.c:506
21 luaD_pretailcall (L=L@entry=0x7f5c639d4948, ci=ci@entry=0x7f5c56580040, func=<optimized out>, func@entry=0x7f5c4cb2ce10, narg1=<optimized out>, 
    delta=delta@entry=7) at ldo.c:527
22 0x0000000000433be1 in luaV_execute (L=L@entry=0x7f5c639d4948, ci=<optimized out>) at lvm.c:1662
23 0x0000000000425a40 in ccall (inc=65537, nResults=<optimized out>, func=<optimized out>, L=0x7f5c639d4948) at ldo.c:609
24 luaD_callnoyield (L=0x7f5c639d4948, func=<optimized out>, nResults=<optimized out>) at ldo.c:627
25 0x0000000000424a2a in luaD_rawrunprotected (L=L@entry=0x7f5c639d4948, f=f@entry=0x420f70 <f_call>, ud=ud@entry=0x7f5caa3d80b0) at ldo.c:144
26 0x0000000000425d3e in luaD_pcall (L=L@entry=0x7f5c639d4948, func=func@entry=0x420f70 <f_call>, u=u@entry=0x7f5caa3d80b0, old_top=192, ef=<optimized out>)
    at ldo.c:926
27 0x00000000004226e9 in lua_pcallk (L=L@entry=0x7f5c639d4948, nargs=<optimized out>, nresults=nresults@entry=-1, errfunc=errfunc@entry=0, ctx=ctx@entry=0, 
    k=k@entry=0x43cc00 <finishpcall>) at lapi.c:1069
28 0x000000000043cc90 in luaB_pcall (L=0x7f5c639d4948) at lbaselib.c:477
29 0x000000000042579d in precallC (f=0x43cc40 <luaB_pcall>, nresults=2, func=<optimized out>, L=0x7f5c639d4948) at ldo.c:506
30 luaD_precall (L=L@entry=0x7f5c639d4948, func=<optimized out>, func@entry=0x7f5c4cb2cca0, nresults=2) at ldo.c:572
31 0x0000000000433a83 in luaV_execute (L=L@entry=0x7f5c639d4948, ci=<optimized out>) at lvm.c:1638
32 0x0000000000425a40 in ccall (inc=65537, nResults=<optimized out>, func=<optimized out>, L=0x7f5c639d4948) at ldo.c:609
33 luaD_callnoyield (L=0x7f5c639d4948, func=<optimized out>, nResults=<optimized out>) at ldo.c:627
34 0x0000000000424a2a in luaD_rawrunprotected (L=L@entry=0x7f5c639d4948, f=f@entry=0x420f70 <f_call>, ud=ud@entry=0x7f5caa3d8370) at ldo.c:144
35 0x0000000000425d3e in luaD_pcall (L=L@entry=0x7f5c639d4948, func=func@entry=0x420f70 <f_call>, u=u@entry=0x7f5caa3d8370, old_top=48, ef=<optimized out>)
    at ldo.c:926
36 0x00000000004226e9 in lua_pcallk (L=L@entry=0x7f5c639d4948, nargs=nargs@entry=5, nresults=nresults@entry=0, errfunc=errfunc@entry=1, ctx=ctx@entry=0, 
    k=k@entry=0x0) at lapi.c:1069
37 0x00007f5c839e648f in _cb (context=0x7f5c723cbb80, ud=<optimized out>, type=3, session=0, source=17, msg=0x7f5c6b8aca90, sz=40) at lualib-src/lua-skynet.c:67
38 0x0000000000419657 in dispatch_message (ctx=ctx@entry=0x7f5c723cbb80, msg=msg@entry=0x7f5caa3d8440) at skynet-src/skynet_server.c:275
39 0x000000000041a254 in skynet_context_message_dispatch (sm=sm@entry=0x7f5ccb608280, q=q@entry=0x7f5c56337200, weight=weight@entry=-1)
    at skynet-src/skynet_server.c:335
40 0x000000000041aa0d in thread_worker (p=<optimized out>) at skynet-src/skynet_start.c:163
41 0x00007f5ccc818ea5 in start_thread (arg=0x7f5caa3d9700) at pthread_create.c:307
---Type <return> to continue, or q <return> to quit---
42 0x00007f5ccbc1db0d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by sniper00** [comment]
打开这个宏 LUA_USE_APICHECK 试试

**Comment by RiceCN** [comment]
> 

好的，我试试，这个要服务器下次更新才能试，项目在对外开放测试，一两天宕一次，查来查去最大可能还是申请的内存空间越界或者是否double free 了

**Comment by cloudfreexiao** [comment]
看看这个把  LUA_USE_APICHECK MEMORY_CHECK 打开
https://github.com/cloudwu/skynet/issues/1106

**Comment by hanxi** [comment]
> > 
> 
> 这个能直接调试core文件吗？

可以调试 core 文件的，能定位到是哪个 lua 函数的。

从你的堆栈目前只能看出是接收消息 disptch 后挂的。用那个插件应该可以查出是哪行lua代码，调试看看吧。

**Comment by RiceCN** [comment]
有点看不懂怎么调试&gt; gdb lua
(gdb) run core文件
(gdb)&nbsp;source lua-gdb.py
这样吗？这样调试不了
&nbsp;


wuchunming
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月17日(星期三) 晚上6:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cloudwu/skynet] 未知原因crash (Issue #1624)





    
这个能直接调试core文件吗？
  
可以调试 core 文件的，能定位到是哪个 lua 函数的。
 
从你的堆栈目前只能看出是接收消息 disptch 后挂的。用那个插件应该可以查出是哪行lua代码，调试看看吧。

**Comment by RiceCN** [comment]
> > > 
> > 
> > 
> > 这个能直接调试core文件吗？
> 
> 可以调试 core 文件的，能定位到是哪个 lua 函数的。
> 
> 从你的堆栈目前只能看出是接收消息 disptch 后挂的。用那个插件应该可以查出是哪行lua代码，调试看看吧。

有点看不懂怎么调试, 如下：
gdb xxx/lua
(gdb) run core文件
(gdb)source lua-gdb.py
这样吗？这样调试不了

**Comment by terry8210** [comment]
不是纯lua编写吗？为什么还需要自己申请内容，管理内容呢？

**Comment by RiceCN** [comment]
> 

使用了websocket，外接了一个对消息的处理；现在打算换掉，直接使用skynet自带的websocket

**Comment by RiceCN** [comment]
> 

使用了websocket，外接了一个对消息的处理；现在打算换掉，直接使用skynet自带的websocket

**Comment by RiceCN** [comment]
宕机的原因已查明，外部开辟内存不当造成的，使用skynet内置的websocket未出现宕机
