### ISSUE TITLE
http服务 无限打印error，log文件大小无限增长。

### ISSUE THREAD

**Issue by lsx1994** [cloudwu/skynet#1625]
http服务 无限打印 socket: error on unknown Too many open files

bug我知道怎么解决， 但是我只发起了1000次http请求，这个log为什么会无限打印？

就一小会，log文件直接几百M了， 而且无限的往上涨。

服务器代码:
<pre>
HTTPGate.new():Start(nil, function(self)
    local agent = SKY.newservice(SERVICE_NAME)
    -- 监听端口
    local socket = require("skynet.socket")
    local id = socket.listen(IP, PORT)
    socket.start(id, function(id, addr)
        CROSS:Send(agent, "ProcMsg", id)
    end)
end)

------------------------------------------以下是另一个文件 HTTPAgent
function HTTPAgent:ProcMsg(sock)
    socket.start(sock) -- 开始接收一个 socket
    local interface = self:gen_interface(sock)
    if not interface then 
        LOG("gen_interface error, pls check.")
        return
    end
    local code, url, method, header, body = httpd.read_request(interface.read, 8192)
    local sockdata = self:NewSock(sock, interface.write, code, url)
    if code then
        if code ~= 200 then -- 如果协议解析有问题，就回应一个错误码 code 。
            self:Response(sock, 0)
        else
            local path, query = urllib.parse(url)
            local parm = urllib.parse_query(query) --获取请求的参数
            if parm and table.count(parm) > 0 then
                parm.SOCK = sock
                self:Succeed(parm)
                if not sockdata.IsResponse then --如果重写的函数没返回，保底返回一次
                    self:Response(sock, 1)
                end
            else
                self:Response(sock, 0)
            end    
        end
    end
    self:DelSock(sock)
    if interface.close then
        interface.close()
    end
end

function HTTPAgent:Succeed(parm) 
    if not self:VerifyParm(parm, false, "Func") then
        self:Response(parm.SOCK, 0, {msg="Parm func error."})
        return
    else
        local func = self[parm.Func]
        if func then
            func(self, parm)
        else
            self:Response(parm.SOCK, 0, {msg="Func is nil."})
        end
    end
end

function HTTPAgent:Response(sock, state, tab)
    tab = tab or {}
    tab.state = state
    local sockdata = self.SockList[sock]
    if not sockdata then
        LOG("Response sockdata error...")
        return
    end
    if not table.check(tab) then
        LOG("Response tab error,", sockdata.BackUrl, sockdata.BackCode)
        return
    end
    sockdata.IsResponse = true
    local headers = {
        ['Access-Control-Allow-Origin'] = '*', -- 这里写允许访问的域名就可以了，允许所有人访问的话就写*
        ['Access-Control-Allow-Credentials'] = true,
    } 
    local ok, err = httpd.write_response(sockdata.BackWrite, sockdata.BackCode, xTool.cjson.encode(tab), headers)
    if not ok then
        LOG("Response write error,", sockdata.BackUrl, sockdata.BackCode)
    end
end
</pre>

客户端代码:
<pre>
function RobotLogin:RobotStart()
    local token = "Eod.Game.Robot"..ROBOTID
    local state,body = xTool.httpc.request("GET", xSvrInfo:GetV("GAMESVRADDRESS"), "/?Func=GetServerInfo&account="..token, {})
    body = xTool.cjson.decode(body)
    if state == 200 and body.state == 1 then
        --连接服务器
        ROBOT:Connect(body.ip, body.port)
        --开始登录
        ROBOT:SendToServer("LOGIN_CS_EODGUEST", {token=token, platform=99, netmsgvesion=xCfgMgr:GetShareData("netmsgvesion")})
    end
end
</pre>

打印LOG的框架代码:
<pre>
-- SKYNET_SOCKET_TYPE_ERROR = 5
socket_message[5] = function(id, _, err)
	local s = socket_pool[id]
	if s == nil then
		driver.shutdown(id)
		skynet.error("socket: error on unknown", id, err)
		return
	end
	if s.callback then
		skynet.error("socket: accpet error:", err)
		return
	end
	if s.connected then
		skynet.error("socket: error on", id, err)
	elseif s.connecting then
		s.connecting = err
	end
	s.connected = false
	driver.shutdown(id)

	wakeup(s)
end
</pre>

这截图的大小我就运行了十几秒，放着不管能把硬盘撑爆。
![image](https://user-images.githubusercontent.com/66242418/184613968-cc99f045-1e22-49da-8e50-54cbdba29288.png)

**Comment by cloudwu** [comment]
你先确定一下 "Too many open files" 是从 C 的哪一行抛出来的？

**Comment by lsx1994** [comment]
> 1. 你先确定一下 "Too many open files" 是从 C 的哪一行抛出来的？
> 2. 确定代码更新到最新。

已更新最新版，依然有这个问题。

加log定位到位置：
https://github.com/cloudwu/skynet/blob/master/skynet-src/socket_server.c#L1683

**Comment by lsx1994** [comment]
> 1. 你先确定一下 "Too many open files" 是从 C 的哪一行抛出来的？
> 2. 确定代码更新到最新。

不好意思，经过测试发现是HTTP后的websocket.connect导致的。
C代码位置：https://github.com/cloudwu/skynet/blob/master/skynet-src/socket_server.c#L1683

**Comment by sniper00** [comment]
自动重连捕获到网络错误时，建议sleep(1s) 再进行重连尝试

**Comment by lsx1994** [comment]
> 自动重连捕获到网络错误时，建议sleep(1s) 再进行重连尝试

不是重连问题，客户端代码我都屏蔽了只留了 websocket.connect，具体原因我还在查
目前定位到打印log的位置是：https://github.com/cloudwu/skynet/blob/master/skynet-src/socket_server.c#L1683

**Comment by lsx1994** [comment]
> 1. 你先确定一下 "Too many open files" 是从 C 的哪一行抛出来的？
> 2. 确定代码更新到最新。

不好意思，之前判断有误，不是http引起的， 是http后的websocket.connect，代码已经更新到最新了，还是有问题，等我排查一下其他原因再反馈。

WS服务器
<pre>
function WSGate:StartListening()
    --监听端口
    self:Timeout(2, function()  --延迟2秒，避免服务器还没启动客户端就连接。
        local listenid = socket.listen(xSvrInfo:GetV("IPLOCAL"), xSvrInfo:GetV("ServerPort"))
        socket.start(listenid, function(clientid, clientaddr)
            websocket.accept(clientid, self.handler, xSvrInfo:GetV("wsmode"), clientaddr)
        end)
        LOG("WSGate 开始监听...")
    end)
end
</pre>

WS客户端
<pre>
function WSClient:Connect(ip, port)
    if self.fd then
        self:DisConnect()
    end
    
    self.fd = websocket.connect(string.format("ws://%s:%d", ip, port))
    --self.CloseHandle = self:StartUpdate()
    --self:OpenConnect(self.fd)
end
</pre>


客户端只保留websocket.connect，其他全部屏蔽掉了。
服务器的log会无限增长，客户端的log文件是正常的。

**Comment by lsx1994** [comment]
![image](https://user-images.githubusercontent.com/66242418/184825979-12d4c00f-81d3-4e44-9fcf-91d76080bd19.png)
客户端log是固定不变的，服务器我刚刚没关，直接卡死机了。

**Comment by lsx1994** [comment]
> 1. 你先确定一下 "Too many open files" 是从 C 的哪一行抛出来的？
> 2. 确定代码更新到最新。

问题找到了，把open files改成100， 启动100个机器人。 机器人请求httpc.request成功后连接websocket，大概在第77个httpc.request处出错，服务器会无限打印log。 单独测试没问题应该是httpc.request用完就释放了，所以没达到上限。

我在 https://github.com/cloudwu/skynet/blob/master/skynet-src/socket_server.c#L1578 下添加 close(client_fd);就正常了，但是不知道这样改对不对。

**Comment by lsx1994** [comment]
没查明原因就提问这个我下次我注意。

**Comment by cloudwu** [comment]
看看 emfile 分支上的 patch 能否解决这个问题。我暂时没有测试。

**Comment by lsx1994** [comment]
> 看看 emfile 分支上的 patch 能否解决这个问题。我暂时没有测试。

不会无限打印log了， 但是socket的openfiles没打印，文件打开上限skynet.require先报错了。

**Comment by lsx1994** [comment]
可以了，一切正常
