### ISSUE TITLE
socket_driver对fd的控制转移中会出现丢包现象

### ISSUE THREAD

**Issue by SheepQi** [cloudwu/skynet#1627]
具体流程如下:
       在接收到一个新的链接后A服务先执行了socket.readline读取了一个数据包，然后立即使用socket.abandon终止。然后B服务调用socket.start,并开始接收数据。

这个过程中如果客户端是同时发送的两个数据包，第二个数据包并不会被B服务所接收而是会在A服务内被丢弃。

**Comment by cloudwu** [comment]
你需要在用户层解决这个问题。你的协议应该让两端协商好，并根据用户层协议确保数据已经全部接收到，并不再发送新的数据。然后才能用 abandon 转移。

**Comment by CoolDesert** [comment]
如果可以确认 A 服务的 socket 数据已经处理完毕(没有缓存)，在 socket.bandon 之前调用 socket.pause，让 epoll 关闭读事件。
