### ISSUE TITLE
Makefile 首字母需要大写

### ISSUE THREAD

**Issue by LCB14** [cloudwu/skynet#1641]
/3rd/lua/ 下的 Makefile 文件首字母需要大写， 不然 make 编译完执行./3rd/lua/lua examples/client.lua 时，会提示找不到相关文件。

**Comment by cloudwu** [comment]
为什么？

**Comment by LCB14** [comment]
具体原因目前暂不清楚，我使用的是macos系统，/3rd/lua/ 下的 makefile 文件修改前命名前我执行./3rd/lua/lua examples/client.lua 会出现我上面提到的问题，起初怀疑是我自己误修改了什么地方的代码导致的，就和老的版本（v1.4.0、v1.3.0）对比了一下，发现文件命名有比较明显的区别，尝试调整了一下，重新操作一遍之前的流程，发现就可以跑通了。

**Comment by cloudwu** [comment]
建议先搞清楚原因，确定不是自己环境的问题。

**Comment by cloudwu** [comment]
建议从 clone 项目开始，列出操作步骤，环境，以及出错信息。
