### ISSUE TITLE
lua_resetthread 不兼容Official Lua

### ISSUE THREAD

**Issue by dpull** [cloudwu/skynet#1686]
文档中说:

> About Lua version
> Skynet now uses a modified version of lua 5.4.4 ( https://github.com/ejoy/lua/tree/skynet54 ) for multiple lua states.
> 
> Official Lua versions can also be used as long as the Makefile is edited.

但是 lua_resetthread 的函数定义不同, 建议恢复对Official Lua的兼容

**Comment by dingdalong** [comment]
这个是最新的修改，lua新版本还没发布，这边提前合并进来了
https://github.com/lua/lua/blob/be908a7d4d8130264ad67c5789169769f824c5d1/lua.h#L156

**Comment by cloudwu** [comment]
回退的维护成本较高，所以以 lua 的官方仓库为准。

**Comment by dpull** [comment]
你的意思是指使用`https://github.com/lua/lua`的master分支最新?

> 回退的维护成本较高，所以以 lua 的官方仓库为准。

**Comment by cloudwu** [comment]
> 你的意思是指使用`https://github.com/lua/lua`的master分支最新?
> 
> > 回退的维护成本较高，所以以 lua 的官方仓库为准。

对

**Comment by cloudwu** [comment]
昨天更新了 lua 5.4.6 ，所以恢复了 lua_resetthread 的 abi 。当然推荐用 lua_closethread 替代。

**Comment by dpull** [comment]
https://github.com/dpull/skynet-mingw/blob/master/platform/platform.h#L108

**Comment by cloudwu** [comment]
官方 5.4.6 应该马上发布了。看起来不会和现在的 rc1 有什么区别。
