### ISSUE TITLE
cluster 数据没有指定大小端吗？

### ISSUE THREAD

**Issue by world100** [cloudwu/skynet#1693]
lua-seri.c 中

wb_integer 函数里 uint16_t, uint32_t, uint64_t 数据写入与读取没指定大小端

在不同cpu决定大小端不一样的机子上放置节点会有问题
我在windows上测试了接入数据是小端发来， 但我机子是大端

**Comment by sniper00** [comment]
> lua-seri.c 中
> 
> wb_integer 函数里 uint16_t, uint32_t, uint64_t 数据写入与读取没指定大小端
> 
> 在不同cpu决定大小端不一样的机子上放置节点会有问题 我在windows上测试了接入数据是小端发来， 但我机子是大端

啥机器

**Comment by cloudwu** [comment]
lua-seri 设计时假定在同种机器上使用。所以不能混用不同的机器组成 cluster 。

因为这种混用场合很少，目前几乎所有的硬件都能使用小端，所以也不打算修改 seri 代码。

**Comment by cloudwu** [comment]
如果实在有需求的话，可以改一个大端版本的 seri 模块，在大端机器上部署。cluster 本身的通讯协议是考虑过大小端的。

**Comment by world100** [comment]
好的
