### ISSUE TITLE
skynet-1.6.0 和 skynet-master 编译报错

### ISSUE THREAD

**Issue by world100** [cloudwu/skynet#1713]
[root@localhost skynet-1.6.0]# make linux
make all PLAT=linux SKYNET_LIBS="-lpthread -lm -ldl -lrt" SHARED="-fPIC --shared" EXPORT="-Wl,-E" MALLOC_STATICLIB="3rd/jemalloc/lib/libjemalloc_pic.a" SKYNET_DEFINES=""
make[1]: Entering directory `/root/work/tools/skynet-1.6.0'
cd 3rd/lua && make CC='cc -std=gnu99' linux
make[2]: Entering directory `/root/work/tools/skynet-1.6.0/3rd/lua'
make all SYSCFLAGS="-DLUA_USE_LINUX" SYSLIBS="-Wl,-E -ldl"
make[3]: Entering directory `/root/work/tools/skynet-1.6.0/3rd/lua'
cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g   -c -o lapi.o lapi.c
cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g  -c lcode.c
cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g   -c -o lctype.o lctype.c
cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g   -c -o ldebug.o ldebug.c
cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g   -c -o ldo.o ldo.c
cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g   -c -o ldump.o ldump.c
cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g   -c -o lfunc.o lfunc.c
cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g   -c -o lgc.o lgc.c
cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g  -c llex.c
cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g   -c -o lmem.o lmem.c
cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g   -c -o lobject.o lobject.c
cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g   -c -o lopcodes.o lopcodes.c
cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g  -c lparser.c
cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g   -c -o lstate.o lstate.c
cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g   -c -o lstring.o lstring.c
In file included from lstring.c:23:0:
../../skynet-src/atomic.h:33:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>

stdatomic.h 这个文件好像是要c11

我用的系统是
[root@localhost skynet-1.6.0]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core)

**Comment by sniper00** [comment]
> [root@localhost skynet-1.6.0]# make linux make all PLAT=linux SKYNET_LIBS="-lpthread -lm -ldl -lrt" SHARED="-fPIC --shared" EXPORT="-Wl,-E" MALLOC_STATICLIB="3rd/jemalloc/lib/libjemalloc_pic.a" SKYNET_DEFINES="" make[1]: Entering directory `/root/work/tools/skynet-1.6.0' cd 3rd/lua && make CC='cc -std=gnu99' linux make[2]: Entering directory `/root/work/tools/skynet-1.6.0/3rd/lua' make all SYSCFLAGS="-DLUA_USE_LINUX" SYSLIBS="-Wl,-E -ldl" make[3]: Entering directory `/root/work/tools/skynet-1.6.0/3rd/lua' cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g -c -o lapi.o lapi.c cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g -c lcode.c cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g -c -o lctype.o lctype.c cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g -c -o ldebug.o ldebug.c cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g -c -o ldo.o ldo.c cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g -c -o ldump.o ldump.c cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g -c -o lfunc.o lfunc.c cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g -c -o lgc.o lgc.c cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g -c llex.c cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g -c -o lmem.o lmem.c cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g -c -o lobject.o lobject.c cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g -c -o lopcodes.o lopcodes.c cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g -c lparser.c cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g -c -o lstate.o lstate.c cc -std=gnu99 -O2 -Wall -Wextra -DLUA_USE_LINUX -I../../skynet-src -g -c -o lstring.o lstring.c In file included from lstring.c:23:0: ../../skynet-src/atomic.h:33:23: fatal error: stdatomic.h: No such file or directory #include <stdatomic.h>
> 
> stdatomic.h 这个文件好像是要c11
> 
> 我用的系统是 [root@localhost skynet-1.6.0]# cat /etc/redhat-release CentOS Linux release 7.6.1810 (Core)

升级最新GCC

**Comment by world100** [comment]
如果对gcc版本有要求， 建议在readme里加上说明

**Comment by world100** [comment]
![image](https://user-images.githubusercontent.com/4382414/225252905-4f9b07c2-607b-41ce-ac0c-c505fbe2c8bf.png)

**Comment by hanxi** [comment]
> 如果对gcc版本有要求， 建议在readme里加上说明

https://github.com/cloudwu/skynet/wiki/Build#%E7%BC%96%E8%AF%91%E5%B7%A5%E5%85%B7-compiling-tool

Wiki 中有写。
