### ISSUE TITLE
Skynet中使用pbc（protobuf）报错

### ISSUE THREAD

**Issue by mishuawu** [cloudwu/skynet#1723]
Skynet中使用pbc（protobuf）报错

下载好pbc之后，进入了binding/lua53目录下，执行make，生成了一个protobuf.so的文件，我把这个文件放到了luaclib下，
然后写了一个lua代码，当我执行  require “protobuf”这条语句时，会报错，报错内容如下：

[:00000008] lua loader error : error loading module 'protobuf.c' from file './luaclib/protobuf.so':
	./luaclib/protobuf.so: undefined symbol: lua_newuserdata
stack traceback:
	[C]: in ?
	[C]: in upvalue 'require'
	./skynet/lualib/skynet/require.lua:31: in function 'require'
	./lualib/protobuf.lua:1: in main chunk
	[C]: in upvalue 'require'
	./skynet/lualib/skynet/require.lua:31: in function 'require'
	./service/4_2_2_Main.lua:3: in local 'main'
	./skynet/lualib/loader.lua:50: in main chunk

想求教下，出现问题的原因，以及解决办法。

**Comment by sniper00** [comment]
用lua5.4重新编译下

**Comment by mishuawu** [comment]
> 用lua5.4重新编译下

啊，谢谢，确实解决了www
