### ISSUE TITLE
对一个fork然后sleep的协程killthread，会导致sleep时间到了后报错。

### ISSUE THREAD

**Issue by kingbird2011** [cloudwu/skynet#1755]
看代码是因为清理了fork_queue以后，会直接return
但是没有将session_id_coroutine置为BREAK

还是说我用法不对，不能直接对他killthread？

**Comment by kingbird2011** [comment]
目前我自己改了下kill thread， 我看目前的代码，在kill 一个fork的协程时，直接return了，没考虑他已经是sleep或者call挂起的

**Comment by cloudwu** [comment]
killthread 原本设计时是出于调试用途，而不是常规控制流程。所以我不确定这里的出错是不是正常的。

**Comment by kingbird2011** [comment]
如果我有这个需求，比如怪死了，身上的ai协程我要他立刻结束，更好的办法是如何处理

**Comment by cloudwu** [comment]
让它自己 raise error ，然后 pcall ，做收尾工作，然后正常退出。

常规 os 的线程库也不会提倡从另外的线程杀掉它。

**Comment by cloudwu** [comment]
你的修改可以提个 pr 。不过我个人不建议把 killthread 用于常规流程控制。

**Comment by kingbird2011** [comment]
好的

**Comment by cloudwu** [comment]
我有个疑问：在 fork queue 里的 coroutine 不应该阻塞在 sleep 或 call 上？这个 queue 并不是由外部消息驱动的。

**Comment by kingbird2011** [comment]
关闭

**Comment by cloudwu** [comment]
我怀疑你错误引用了 coroutine 。因为 skynet 会复用已经执行完毕的 coroutine ，所以你可能持有一个错误的引用。

**Comment by kingbird2011** [comment]
fork了之后返回的我拿住了？

**Comment by cloudwu** [comment]
你可以引用它，但是你需要自己确定执行结束后解引用。

**Comment by kingbird2011** [comment]
我看到fork的co_creat代码里，在执行完我的函数后，还做了一些工作，我直接kill，可能这部分代码就跑不到了，的确直接杀会有问题。

**Comment by sniper00** [comment]
加递增序列号，sleep后面检查一下，不一样就return
