### ISSUE TITLE
启动skynet失败，socket_server_create err

### ISSUE THREAD

**Issue by mrzhangjing** [cloudwu/skynet#1767]
在skynet中执行os.execute("nohup ./skynet config >/dev/null 2>&1 &")启动另一个skynet

`skynet: skynet-src/socket_server.c:423: socket_server_create: Assertion `ss->recvctrl_fd < FD_SETSIZE' failed.`

os.execute 执行，这种情况概率出现。
手动执行 ‘nohup ./skynet config >/dev/null 2>&1 &’ 正常。

**Comment by cloudwu** [comment]
可能是因为父进程使用了太多 fd ，建议不要这么做。考虑在一个干净的进程内启动 skynet 。
