### ISSUE TITLE
Lua 5.4.6浮点运算崩溃

### ISSUE THREAD

**Issue by LazyPlanet** [cloudwu/skynet#1843]
The **Issues** is for bug report only.

Goto **Discussions** for feature request , questions, etc.

**Update to master branch HEAD first**, and
最新版本

**Describe the bug**
Lua 5.4.6  Copyright (C) 1994-2023 Lua.org, PUC-Rio
lua 5.4.6 版本下，浮点运算导致系统core fault/dump
可能是lua本身问题导致skynet在浮点运算的时候崩溃
如何降版本解决？
**To Reproduce**
1.代码 test.lua
`local baseValue = 0
local pctValue = 1
local addValue = 0
local value = baseValue * (1 + pctValue * 0.01) + addValue
print(type(value))
print(tostring(value))`
2.执行 lua test.lua

**Additional context**
无

**Comment by hanxi** [comment]
在 lua5.4.6中没复现，输出结果如下
```
number
0.0
```

```lua
local baseValue = 0
local pctValue = 1
local addValue = 0
local value = baseValue * (1 + pctValue * 0.01) + addValue
print(type(value))
print(tostring(value))
```

**Comment by LazyPlanet** [comment]
> 在 lua5.4.6中没复现，输出结果如下
> 
> ```
> number
> 0.0
> ```
> 
> ```lua
> local baseValue = 0
> local pctValue = 1
> local addValue = 0
> local value = baseValue * (1 + pctValue * 0.01) + addValue
> print(type(value))
> print(tostring(value))
> ```
大佬是linux系统吗
Lua version: Lua 5.4.6  Copyright (C) 1994-2023 Lua.org, PUC-Rio
System version: CentOS Linux release 7.9.2009 (Core)

![image](https://github.com/cloudwu/skynet/assets/15156350/f1abc9ef-1776-4ad5-b4c1-2227d292e22b)

**Comment by hanxi** [comment]
建议你先diff一下lua目录看看是不是有不小心修改的地方，我用官方的lua和skynet里的lua都跑了下，都没问题。

**Comment by LazyPlanet** [comment]
> 建议你先diff一下lua目录看看是不是有不小心修改的地方，我用官方的lua和skynet里的lua都跑了下，都没问题。

这个就奇怪了，我用官方的lua和skynet的lua都有问题，我都是在centos在跑的，腾讯云、阿里云和本地的wsl都不行，大佬是什么平台跑的呢？

**Comment by LazyPlanet** [comment]
g++ (GCC) 10.1.0
Copyright © 2020 Free Software Foundation, Inc.
编译有问题，但是4.8.5没问题。
