### ISSUE TITLE
clusteragent中`register_name_mt.__index`重入,导致请求结果"Invalid name"。

### ISSUE THREAD

**Issue by kang-dd** [cloudwu/skynet#1948]
如题，我有一个节点同时关闭多个service，每次关闭clusteragent会收到一条`namechange`消息，在这期间对同个name派发消息时，会出现"Invalid name"。
消息顺序：
1. 收到`namechange`后调用`new_register_name`产生register_name_a。
2. 收到消息执行`dispatch_request`方法，此时register_name_a[name]为nil，执行`register_name_mt.__index`方法，此时inquery_name[name]为nil，然后`queryname`协程挂起。
3. 再次收到`namechange`后调用`new_register_name`产生register_name_b。
4. 再次收到消息执行`dispatch_request`方法，register_name_b[name]为nil，执行`register_name_mt.__index`方法，此时inquery_name[name]非nil，协程等待挂起。
5. 第2步的`queryname`结果返回，`register_name_a[name] = abbr`, 并唤醒的携程
6. 唤醒第4步中的协程，`rawget(register_name_b, name)`为nil，返回"Invalid name"。

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/pull/870 实现有疏漏，这里加的 `inquery_name` 应为 `register_name` 的关联状态，应该绑在一起。cc @hongling0 也可以看看。

**Comment by hongling0** [comment]
我觉得不能直接删除inquery_name ,之前的修改是为了保证消息有序返回, 删除之后就没有这个保证了
```
local inquery_name = {}
local register_name

local register_name_mt = { __index =
	function(self, name)
		local waitco = inquery_name[name]
		if waitco then
			local co = coroutine.running()
			table.insert(waitco, co)
			skynet.wait(co)
			if ctx == register_name then
				return rawget(register_name, name)
			end
		else
			waitco = {}
			inquery_name[name] = waitco

			while true do
				local ctx = register_name
				local addr = skynet.call(clusterd, "lua", "queryname", name:sub(2))	-- name must be '@xxxx'
				if addr then
					ctx[name] = addr
				end
				if ctx == register_name then
					inquery_name[name] = nil
					for _, co in ipairs(waitco) do
						skynet.wakeup(co)
					end
					return addr
				end
			end
		end
	end
}

local function new_register_name()
	register_name = setmetatable({}, register_name_mt)
end
new_register_name()
```
我觉得可以这边   栈上保留异步之前的register_name引用
调用完成之后判断register_name有没有被修改, 修改了的话就证明namechange调用过了, 直接重试就可以了

@cloudwu @kang-dd 你们看看这样修改行不行

**Comment by cloudwu** [comment]
@hongling0 要不你提一个 pr ？我这两天在忙其它项目，麻烦你们多关注这个问题。

**Comment by kang-dd** [comment]
@cloudwu @hongling0 测试了一下，这两种方法都能解决这个问题。第一种也没有出现乱序的情况。

**Comment by hongling0** [comment]
不好意思 刚刚看到你的回复 @kang-dd
我仔细想了下乱序的问题, 你是对的, 你的代码并不会导致乱序.

我思考了下我提的pr是否合理, 发现了里面是有问题的
clusterd中的queryname和namechange, 都是简单消息, 在clusterd那边他们不会乱序, 所以说queryname拿到的地址一定是对的
多次namechange夹杂的queryname拿回的地址也是对的, 那么其实没有必要重新去queryname.

那么我们只需要保证你的6步能获取正确的地址即可

```
local inquery_name = {}
local register_name

local register_name_mt = { __index =
	function(self, name)
		local waitco = inquery_name[name]
		if waitco then
			local co = coroutine.running()
			table.insert(waitco, co)
			skynet.wait(co)
			return rawget(register_name, name)
		else
			waitco = {}
			inquery_name[name] = waitco

			local addr = skynet.call(clusterd, "lua", "queryname", name:sub(2))	-- name must be '@xxxx'
			if addr then
				register_name[name] = addr
			end
			inquery_name[name] = nil
			for _, co in ipairs(waitco) do
				skynet.wakeup(co)
			end
			return addr
		end
	end
}

local function new_register_name()
	register_name = setmetatable({}, register_name_mt)
end
new_register_name()

```
和最开始的版本比较的话就是 返回的地址存放进最新的register_name表, 唤醒的协程也是直接从最新的register_name获取
我觉得这个才是对的修改@cloudwu

**Comment by cloudwu** [comment]
chong
