### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by hulonghui106** [cloudwu/skynet#196]
make[2]: Entering directory `/root/skynet/3rd/lua'
make all SYSCFLAGS="-DLUA_USE_LINUX" SYSLIBS="-Wl,-E -ldl -lreadline"
make[3]: Entering directory`/root/skynet/3rd/lua'
ar rcu liblua.a lapi.o lcode.o lctype.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o lmem.o lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o ltm.o lundump.o lvm.o lzio.o lauxlib.o lbaselib.o lbitlib.o lcorolib.o ldblib.o liolib.o lmathlib.o loslib.o lstrlib.o ltablib.o loadlib.o linit.o 
ranlib liblua.a
cc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_USE_LINUX    -c -o lua.o lua.c
lua.c:67:31: 错误：readline/readline.h：没有那个文件或目录
lua.c:68:30: 错误：readline/history.h：没有那个文件或目录
lua.c: 在函数‘pushline’中:
lua.c:265: 警告：隐式声明函数‘readline’
lua.c:265: 警告：赋值时将整数赋给指针，未作类型转换
lua.c: 在函数‘loadline’中:
lua.c:297: 警告：隐式声明函数‘add_history’
make[3]: **\* [lua.o] 错误 1
make[3]: Leaving directory `/root/skynet/3rd/lua'
make[2]: *** [linux] 错误 2
make[2]: Leaving directory`/root/skynet/3rd/lua'
make[1]: **\* [3rd/lua/liblua.a] 错误 2
make[1]: Leaving directory `/root/skynet'
make: **\* [linux] 错误 2

**Comment by scanor** [comment]
我也遇到了这个编译问题，也懵逼了，然后我先谷歌了，然后解决了

**Comment by yingnierxiao** [comment]
万事先google
