### ISSUE TITLE
引入skynet.multicast模块有可能导致服务退出后cmem无法释放

### ISSUE THREAD

**Issue by LokerLi** [cloudwu/skynet#1992]
引入skynet.multicast模块有可能导致服务退出后cmem无法释放，下面的服务new10个必现，cmem看 [:0000017b 0.0722656K] 是一直无法释放

代码：

```
local skynet = require "skynet"
local mc = require "skynet.multicast"
skynet.start(function()
	skynet.exit()
end)
```

+11 [:0000000c 0.0722656K]
+12 [:0000000d 0.0722656K]
+13 [:0000000e 0.0722656K]
+14 [:0000000f 0.0722656K]
+15 [:00000010 0.0722656K]
+16 [:00000019 0.0722656K]
+17 [:0000001c 0.0722656K]

**Comment by cloudwu** [comment]
如果你计较这个，可以考虑把 skynet.so 静态链接到主程序。

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/issues/415
