### ISSUE TITLE
在wsl中 timer  skyent.now异常

### ISSUE THREAD

**Issue by fanyh** [cloudwu/skynet#2013]
# 环境
wsl ubuntu 24.04

# 问题描述
在 wsl 中 skynet.now 的时间会相对系统时间越来越慢； 在linux（centos） 系统下不存在这个问题

ps： 对比测试发现wsl ubuntu 24.04  下： CLOCK_REALTIME 与 CLOCK_MONOTONIC 表现不太符合预期

# 重新步骤
## code
```lua
local skynet = require "skynet"
local start = os.time()
while true do
    skynet.sleep(100)
    skynet.error(skynet.now .. "vs" .. os.time() - start)
end
```
### log
```log
[:01000009] 584vs5
[:01000009] 684vs6
[:01000009] 784vs7
[:01000009] 884vs8
[:01000009] 984vs9
[:01000009] 1084vs10
[:01000009] 1184vs14
```

## c debug code
```skynet_timer.c
void skynet_timer_init(void) {
    ...
    struct timespec ti;
    clock_gettime(CLOCK_MONOTONIC, &ti);
    TI->t1 = (uint32_t)ti.tv_sec;
}

uint64_t skynet_now(void) {
    struct timespec ti;
    clock_gettime(CLOCK_MONOTONIC, &ti);

    struct timespec ti1;
    clock_gettime(CLOCK_REALTIME, &ti1);
    skynet_error(NULL, "pass:%d real:%d", ((uint32_t)ti.tv_sec - TI-> t1), ((uint32_t)ti1.tv_sec - TI->starttime));
    return TI->current;
}
```

### c log
```log
[:01000009] 1084vs10
[:00000000] pass:10 real:10
...
[:00000000] pass:10 real:11
[:00000000] pass:10 real:11
[:00000000] pass:10 real:11
[:00000000] pass:10 real:11
[:00000000] pass:10 real:11
[:00000000] pass:10 real:11
[:00000000] pass:10 real:11
[:00000000] pass:10 real:11
[:00000000] pass:10 real:11
[:00000000] pass:11 real:11
...
[:00000000] pass:11 real:13
...
[:00000000] pass:11 real:14
...
[:01000009] 1184vs14
```

**Comment by cloudwu** [comment]
建议把这个问题报告给 wsl 项目。

**Comment by cloudwu** [comment]
我不确定是否和这个问题相关：https://github.com/microsoft/WSL/issues/10006

**Comment by fanyh** [comment]
根据wsl 改善方案（重启wsl对时）操作了下； 然并卵。
但是根据他们的问题描述（休眠会导致 `CLOCK_MONOTONIC`异常），采用重启（windows）大法，暂时隐藏了这个问题

btw: 重启后`CLOCK_MONOTONIC`又快了 ...

wsl本来也并非我们的标准环境，这个问题就先这样。
 
 感谢云大侠

**Comment by tomlau10** [comment]
我們的團隊在最近遇到 (或者說最近才發現) **疑似是相同問題**

- 我們是用 skynet 作為 mmorpg 項目的 server，標準開發環境是 `macos + docker`
- 部分同事則是用 windows notebook `win11 + wsl2 + docker desktop`
而他們近來發現 client 跟 server 連接時，packet 層的 timestamp 驗證邏輯經常不通過
導致 client 被踢 / 移動時回彈
- 加上 verbose log 後發現是 server 的 timestamp 似是有些問題
於是有位技術大佬寫了些 `clock_gettime()` 相關的 test 程序來跑
發現在他們的 docker container 上，以至是 `wsl2` 上，也是有時間飄移問題
- docker desktop 的預設 backend 是 `wsl2`
為了驗證是否跟 docker 有關
我們嘗試將 docker desktop 的 backend 改成 `hyper-v` 
  - 這時在 docker container 上跑 test 就正常了 ✅ 
  - 只有 wsl2 上跑的才有問題 ❌ 
  - => 說明肯定是 `wsl2` 的問題


## 對我們有效的方法

網上搜到很多似是有關的文章，但對應解法都沒作用
最後讓我找到一個 **看似不關事** 的 stackoverflow post，而當中的一個 reply **有點意思**:
https://stackoverflow.com/a/79015508

我沒理解錯的話，這個 reply 的大概意思是
- `window host` 上的 ntp
跟 `wsl` 的 default ntp **不是同1個 server**
- 由於 wsl 本身也會跟 host 的 clock 做 sync
這會導致 2邊 sync 的時候
時間就會忽來忽去 🧐 
- 而給出的解法
是 **停掉** wsl 內的 timesync service

我們試著操作了一下，果然有效 👍 

## 我們目前對這問題的理解 (不一定準確 ⛑ )
- monotonic clock 保證的，只是 不會回退 => 只會往前
- 儘管 ntp 改變 wall clock 時，mono clock 不會有即時影響
但 mono clock 的 **update frequency** 是有可能因而被 system 改變 (?)
比如說每 tick 走快一些 / 慢一些，以追回 wall clock 的時間 (?)
- 而在 wsl 下，最大問題是 **2個不同的 ntp source**
導致 wall clock 經常改變
所以上述 post 的解決方式是 **停掉 wsl 內** 的 timesync service，讓他只跟 window host 做同步

**Comment by fanyh** [comment]
`WSL默认与宿主机Windows共享硬件时钟，但某些情况下（如长时间休眠）可能导致时间偏差。`

我们的工作环境可能长期不关机（休眠）从而产生时间差值问题；使用 ntpdate一定程度上可以消除这个问题

**Comment by tomlau10** [comment]
> 但某些情况下（如长时间休眠）可能导致时间偏差。

嗯，雲大上邊貼的 issue 是描述這種情況
但按該 issue 的 comment，休眠導致大幅度 time skew 的這個問題
沒理解錯的話應該是在 kernel `5.15.*` 版本修復了？
- https://github.com/microsoft/WSL/issues/10006#issuecomment-1904745877
- https://github.com/microsoft/WSL/releases/tag/2.1.1

---

而我們團隊遇到的，並非因休眠引起
而是因為 wsl 內的 ntp 跟 window host 上的 **ntp server 不相同**
=> 導致 wsl 內的經常用不同的 source 來同步 wall clock (?)
- 關掉 wsl timesync 是一種解法 (只按 window host 來同步)
- 而假如不想關掉 wsl 的 timesync
那我相信 **將 wsl 內的 ntp server，也改成 windows host 上使用的**
可能會有幫助 🤔 ?

當然我們遇到的問題，跟你在這 issue 說的，確實又未必相同 😕
