### ISSUE TITLE
Failed when running the client example

### ISSUE THREAD

**Issue by catric** [cloudwu/skynet#217]
I built skynet successfully, but when I try the examples, it failed as below

[root@localhost skynet]# lua examples/client.lua 
lua: error loading module 'clientsocket' from file 'luaclib/clientsocket.so':
    luaclib/clientsocket.so: undefined symbol: luaL_setfuncs

I checked the file "luaclib/clientsocket.so", it existed in ./luaclib/  ,  seems the function "luaL_setfuncs"  not be exported to the so lib?

the version I am using is f15cd1d4587e7baa0b9e1a398a18e6e59ff29cf0

could you please take a look at this issue ?

**Comment by goxinzhong** [comment]
if _VERSION ~= "Lua 5.3" then
        error "Use lua 5.3"
end
