### ISSUE TITLE
run in pi,arm-linux error

### ISSUE THREAD

**Issue by yingnierxiao** [cloudwu/skynet#223]
status = bind(fd, (struct sockaddr *)ai_list->ai_addr, ai_list->ai_addrlen);
	if (status != 0){
		printf("bind _failed  %d\n",status);
		goto _failed;
	}

[:01000001] LAUNCH logger 
[:01000002] LAUNCH snlua bootstrap
[:01000003] LAUNCH snlua launcher
[:01000004] LAUNCH snlua cmaster
enter to driver.listen
[:01000004] master listen socket 0.0.0.0:2013
start skynet_socket_listen
start socket_server_listen
send_request
[:01000005] LAUNCH snlua cslave
start socket.listen127.0.0.1:2526
enter to driver.listen
start skynet_socket_listen
start socket_server_listen
bind _failed  -1
listen_fd -1
fd -1
[:01000005] init service failed: ./lualib/socket.lua:324: Listen error
stack traceback:
	[C]: in function 'listen'
	./lualib/socket.lua:324: in function 'listen'
	./service/cslave.lua:229: in function 'start'
	./lualib/skynet.lua:627: in function <./lualib/skynet.lua:624>
	[C]: in function 'xpcall'
	./lualib/skynet.lua:632: in function 'init_service'
	./lualib/skynet.lua:645: in function 'f'
	./lualib/skynet.lua:105: in function <./lualib/skynet.lua:104>

**Comment by yingnierxiao** [comment]
no find port is used,change port is the some,same time do not print error->[:01000005] init service failed: ./lualib/socket.lua:324: Listen error
stack traceback:

**Comment by cloudwu** [comment]
I have no  "pi,arm-linux"  environment, please find the reason. :)

**Comment by yingnierxiao** [comment]
env error  .
