### ISSUE TITLE
STM的数据版本生命周期管理是不是有问题？

### ISSUE THREAD

**Issue by chuenlungwang** [cloudwu/skynet#227]
我对有没有问题并不是非常确定，只是有些许疑问，若是我思考疏忽那真是实在抱歉。

我觉得`skynet/lualib-src/lua-stm.c`中的，`stm_releasereader`和`stm_grab`并不匹配。原因是`stm_grab`由`lcopy`调用，而不是在生成`struct boxreader`的方法`lnewreader`中，但是`stm_releasereader`是在`struct boxreader`的 __gc 方法中调用，这样就会不匹配。

对应于teststm.lua中的就是如果接收者对同一个obj调用了`stm.newcopy(obj)`多次，就会导致失败。并且如果发送者希望发送给多个接收者，就必须调用`local copy = stm.copy(obj)`多次。

不知道我所想的是否有偏差，浪费您的时间实在抱歉。

**Comment by cloudwu** [comment]
对。每次发个一个新接收者就可以调用 stm.copy 生成一份新副本。在

https://github.com/cloudwu/skynet/wiki/ShareData

Wiki 上有明确说明。

**Comment by chuenlungwang** [comment]
O(∩_∩)O谢谢，原来是有意的。
