### ISSUE TITLE
skynet中simpledb.lua那个例子，怀疑有socket的fd泄露

### ISSUE THREAD

**Issue by hjcapple** [cloudwu/skynet#233]
我将example/watchdog.lua中SOCKET.open的打印，修改成
skynet.error("New client from : " .. fd .. " " .. addr)
跟着启动skynet服务器。不断地运行lua example/client.lua, 再关闭。同一时间只有一个客户端连上服务器。但是发现socket的fd数字不断上升，每次加1。因此怀疑有socket的fd泄露。

我不确定这种情况是不是正常的。

**Comment by cloudwu** [comment]
fd 递增是一个特性，关不关 fd 新的都会递增，尽量避免逻辑错误（不小心操作了不对应的 fd)
客户端主动断开是由 gateserver 去处理的，不需要外部调用关闭，它会向外发出通知。
 gateserver.closeclient 用于服务器主动关闭。

**Comment by hjcapple** [comment]
多谢回复。我后来从你博客找到一些描述了。

“gate 会为每个连接赋予一个唯一 id 号。注意，这个 id 号是尽量不复用的。在 skynet 的生命期内是单调递增的。这是因为在这样的多服务并发的复杂系统内，短期复用 id 是很危险的一件事。”

也就是说。skyent中的socket经过封装，返回的并非直接是系统层级的fd，而是内部有个id到真正fd的对应关系。
