### ISSUE TITLE
移植lproto协议库到skynet

### ISSUE THREAD

**Issue by hanxi** [cloudwu/skynet#234]
我已经把我实现的lproto协议库移植到了skynet。自我感觉比sproto更简单易懂，所以来这问问需要提PR吗？

已经移植到的skynet在这里
<https://github.com/hanxi/skynet/blob/master/lualib/lproto.lua>

lproto地址 <https://github.com/hanxi/lproto>

文档地址 <https://github.com/hanxi/blog/issues/2>

**Comment by cloudwu** [comment]
第三方库请自行维护。如果你向做通告，可以向 skynet maillinglist 发贴 :)

**Comment by hanxi** [comment]
懂了。😊
