### ISSUE TITLE
wiki建议

### ISSUE THREAD

**Issue by luyang177** [cloudwu/skynet#237]
wiki中
https://github.com/cloudwu/skynet/wiki/Build
编译Lua时，需要libreadline-dev，虽然http://www.lua.org/manual/5.2/readme.html
上面写了，但是对于不了解Lua的人（比如我），还是花了一点时间找到这个。

可以的话，请把“需要libreadline-dev”写在skynet的wiki里面吧。

**Comment by fantasyni** [comment]
wiki 是大家都可编辑的

**Comment by LaoZhongGu** [comment]
其实如果不熟悉lua的话，学习skynet也是很难的，特别是要用lua开发。我记得有写的，在FAQ里面。

**Comment by lidashuang** [comment]
好像没有入门指引类的教程，指导新手做出一个简单的helloworld？

**Comment by vanehu** [comment]
不熟悉LUA的话 完全不知道怎么做

**Comment by hanxi** [comment]
根据报错提示就知道少了readline吧。况且遇到错误搜一下就明了的。我第一次报这个错误也是搜来的。

**Comment by lidashuang** [comment]
@vanehu 那就加到wiki里啊，wiki 都可以编辑的

**Comment by rangercyh** [comment]
这个问题好像被问了无数次了.....我也问过,囧~

**Comment by peimin** [comment]
建议上手skynet前先熟悉一下lua，特别是lua和c交互的部分。
