### ISSUE TITLE
lua编译没有开启64位支持

### ISSUE THREAD

**Issue by hanxi** [cloudwu/skynet#239]
lua的Makefile指定了使用gnu99,但是在skynet的Makefile将$(CC)重置了，可以将这行<https://github.com/cloudwu/skynet/blob/lua53/Makefile#L17>中的$(CC)去掉解决。暂时没找到更好解决办法。但是又遇到一个新问题，freebsd10默认安装的是clang而不是gcc。

https://github.com/cloudwu/skynet/blob/lua53/3rd/lua/Makefile#L9

https://github.com/cloudwu/skynet/blob/lua53/Makefile#L17

**Comment by cloudwu** [comment]
看看我这样改行不?

**Comment by hanxi** [comment]
可以了。
