### ISSUE TITLE
关于loginserver的疑问

### ISSUE THREAD

**Issue by OpenGamex** [cloudwu/skynet#240]
如果希望创建多个loginserver，关于用户已登录目前的snax模版好像不支持，是否可以把snax模版中的master和slave拆成多个skynet节点，slave只负责验证，master负责管理用户登陆以及同登陆点的交互。

**Comment by cloudwu** [comment]
loginserver 不需要多个。因为 loginserver 和登录点是分离的。

https://github.com/cloudwu/skynet/wiki/LoginServer

发自我的 iPhone
