### ISSUE TITLE
增加调整时间的接口

### ISSUE THREAD

**Issue by niuys** [cloudwu/skynet#246]
游戏开发过程中经常遇到时间相关的逻辑不好测试，有一个调时间的接口还是很方便测试的，直接修改底层获取时间的接口，没这个接口的话也可以在逻辑层绕过去，但是这个接口暴力有效。云大以为是否有必要？

**Comment by cloudwu** [comment]
如果你有这个需要, 可以在 config 里定义自己的 lualoader
然后在 lualoader 里改写 skynet.time/now 函数, 定义成你需要的样子.

在 2015年3月7日 下午3:50，snail <notifications@github.com>写道：

>
> 游戏开发过程中经常遇到时间相关的逻辑不好测试，有一个调时间的接口还是很方便测试的，直接修改底层获取时间的接口，没这个接口的话也可以在逻辑层绕过去，但是这个接口暴力有效。云大以为是否有必要？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudwu/skynet/issues/246>.
>



-- 
http://blog.codingnow.com

**Comment by niuys** [comment]
比如说有个需求是测试每天0点做什么事情，这个实现是用skynet.timeout来实现的，这种改法没办法影响到timer的触发。

**Comment by niuys** [comment]
又想了一下，在lua层改一下timer的实现，用sleep来做，修改时间的时候把timer thread wakeup一下，再判断时间到没到，也可以实现，就是麻烦一点。

**Comment by cloudwu** [comment]
类似 cron 的服务你应该单独做一个服务方便管理, 而不应该直接用 timeout . 这种定期活动就可以向 cron 服务注册申请和调整.

在 2015年3月8日 下午4:02，snail <notifications@github.com>写道：

> 比如说有个需求是测试每天0点做什么事情，这个实现是用skynet.timeout来实现的，这种改法没办法影响到timer的触发。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudwu/skynet/issues/246#issuecomment-77738061>.
>



-- 
http://blog.codingnow.com

**Comment by niuys** [comment]
嗯，是有一个单独的服务来管理的。每个服务还是有一些自己管理的timeout，如果调时间的话还是要保证这些timeout的触发，保持整个skynet网络的逻辑时间一致。

**Comment by cloudwu** [comment]
那这些 timeout 改成对唯一服务的 call 调用. 这个服务做时间安排.
ps. skynet response 可以用的上. 不要用 sleep.

**Comment by niuys** [comment]
好的
