### ISSUE TITLE
sharedata无法用于skynet.pack

### ISSUE THREAD

**Issue by jintiao** [cloudwu/skynet#250]
起因是我现在用sharedata保存配置表，其中一张记录出生点的表 
{ map = 1, pos { x = 10, y = 10, z = 10 } }
当我想把pos在skynet.call中传过去时报错了。
当然如果建一个临时表把pos全拷贝一下再传是没问题的，我想知道你们是怎么处理这种情况的？或者你们没有这样的需求？

测试代码：

	local skynet = require "skynet"
	local sharedata = require "sharedata"

	local mode = ...

	if mode == "host" then

	skynet.start(function()
	        sharedata.new("foobar", { a=1, b= { "hello",  "world" } })
	end)

	else

	skynet.start(function()
	        skynet.newservice(SERVICE_NAME, "host")

	        local obj = sharedata.query "foobar"
	        local b = obj.b
	        for k,v in ipairs(b) do
	                skynet.error(string.format("b[%d]=%s", k,v))
	        end
	        skynet.pack (b)
	end)

	end

报错信息：

	[:01000010] LAUNCH snlua share
	[:01000012] LAUNCH snlua sharedatad
	[:01000019] LAUNCH snlua share host
	[:01000010] b[1]=hello
	[:01000010] b[2]=world
	[:01000010] init service failed: ./examples/share.lua:22: Unsupport type userdata to serialize
	stack traceback:
	        [C]: in function 'skynet.pack'
	        ./examples/share.lua:22: in local 'start'
	        ./lualib/skynet.lua:630: in function <./lualib/skynet.lua:627>
	        [C]: in function 'xpcall'
	        ./lualib/skynet.lua:635: in upvalue 'init_service'
	        ./lualib/skynet.lua:648: in upvalue 'f'
	        ./lualib/skynet.lua:105: in function <./lualib/skynet.lua:104>
	[:01000010] KILL self

**Comment by cloudwu** [comment]
skynet.pack 没有调用 `__pairs` 。所以你需要复制一次。
因为 sharedata 里的数据是常量，所以理论上打包后的数据也是常量，你可以找到方法避免多次做这件事情。

**Comment by jintiao** [comment]
ok，理解。

再提个问题

	local skynet = require "skynet"

	local t = { ... }

	if #t > 0 then

	skynet.start(function()
	        for k, v in pairs (t) do
	                print (k, v)
	        end
	end)

	else

	skynet.start(function()
	        skynet.newservice(SERVICE_NAME, "hello world")
	end)

	end

输出是

	1       hello
	2       world

"hello world"被拆成了两个字符串，这是故意的么？

**Comment by cloudwu** [comment]
一个服务的初始化参数只能是一个字符串.
所以复杂的初始化过程最好单独用一个初始化消息传进去。
snax 对这个做了一点封装。
