### ISSUE TITLE
crash(skynet 1.0 alpha Commits on Mar 9, 2015)

### ISSUE THREAD

**Issue by iskygame** [cloudwu/skynet#252]
(gdb) bt
#0  je_arena_dalloc_bin_locked (arena=0x7f566bc1b480, chunk=<value optimized out>, ptr=0x7f56655f4c80, mapelm=<value optimized out>) at src/arena.c:1900
#1  0x0000000000454d88 in je_tcache_bin_flush_small (tbin=0x7f56654060a8, binind=4, rem=63, tcache=0x7f5665406000) at src/tcache.c:127
#2  0x0000000000434c21 in je_tcache_dalloc_small (ptr=0x7f56667eb1c0) at include/jemalloc/internal/tcache.h:366
#3  je_arena_dalloc (ptr=0x7f56667eb1c0) at include/jemalloc/internal/arena.h:1014
#4  je_idalloct (ptr=0x7f56667eb1c0) at include/jemalloc/internal/jemalloc_internal.h:830
#5  je_iqalloct (ptr=0x7f56667eb1c0) at include/jemalloc/internal/jemalloc_internal.h:849
#6  je_iqalloc (ptr=0x7f56667eb1c0) at include/jemalloc/internal/jemalloc_internal.h:856
#7  ifree (ptr=0x7f56667eb1c0) at src/jemalloc.c:1249
#8  je_free (ptr=0x7f56667eb1c0) at src/jemalloc.c:1324
#9  0x000000000040df55 in skynet_lalloc (ud=<value optimized out>, ptr=<value optimized out>, osize=<value optimized out>, nsize=<value optimized out>) at skynet-src/malloc_hook.c:221
#10 0x0000000000415141 in luaM_realloc_ ()
#11 0x0000000000413c2b in sweeplist ()
#12 0x0000000000413c77 in sweepstep ()
#13 0x0000000000414f50 in luaC_step ()
#14 0x000000000041278b in luaD_precall ()
#15 0x000000000041d1f6 in luaV_execute ()
#16 0x0000000000412530 in unroll ()
#17 0x0000000000411bbb in luaD_rawrunprotected ()
#18 0x0000000000411e18 in lua_resume ()
#19 0x0000000000425d37 in auxresume ()
#20 0x0000000000426017 in luaB_coresume ()
#21 0x00000000004127a8 in luaD_precall ()
#22 0x000000000041d1f6 in luaV_execute ()
#23 0x0000000000412a9c in luaD_call ()
#24 0x0000000000411bbb in luaD_rawrunprotected ()
#25 0x0000000000411c3f in luaD_pcall ()
#26 0x000000000040f802 in lua_pcallk ()
#27 0x0000000000424e40 in luaB_pcall ()
#28 0x00000000004127a8 in luaD_precall ()
#29 0x000000000041d1f6 in luaV_execute ()
#30 0x0000000000412a9c in luaD_call ()
#31 0x0000000000411bbb in luaD_rawrunprotected ()
#32 0x0000000000411c3f in luaD_pcall ()
#33 0x000000000040f802 in lua_pcallk ()
#34 0x00007f56671fc923 in _cb (context=0x7f5667709be0, ud=0x7f56655d5b08, type=1, session=41, source=12, msg=0x7f566400b000, sz=5492) at lualib-src/lua-skynet.c:50
#35 0x0000000000408d30 in dispatch_message (ctx=0x7f5667709be0, msg=0x7f5668df8df0) at skynet-src/skynet_server.c:254
#36 0x0000000000408fbf in skynet_context_message_dispatch (sm=0x7f566b80e160, q=0x7f5666542500, weight=-1) at skynet-src/skynet_server.c:308
#37 0x0000000000409c81 in _worker (p=<value optimized out>) at skynet-src/skynet_start.c:128
#38 0x00007f566cacf9d1 in start_thread () from /lib64/libpthread.so.0
#39 0x00007f566c18c8fd in clone () from /lib64/libc.so.6

**Comment by iskygame** [comment]
[:0000000c] LAUNCH snlua centerdb

12是一个redis操作的服务

**Comment by cloudwu** [comment]
无法重现,不能解决.
需要你有环境来找到具体问题.

到底是 gc 回收什么的时候出的错.

**Comment by cloudwu** [comment]
另外你需要确认是不是和 https://github.com/cloudwu/skynet/issues/249 一样的问题. 它在 alpha2 中修复.

**Comment by iskygame** [comment]
有可能是该问题，我升级后再观察。

**Comment by iskygame** [comment]
升级后没有再出现，可关闭。
