### ISSUE TITLE
使用域名连接外部服务器时, socket 线程会阻塞在 getaddrinfo 函数

### ISSUE THREAD

**Issue by JiessieDawn** [cloudwu/skynet#253]
使用域名连接外部服务器时, socket 线程会阻塞在 getaddrinfo 函数, 网络消息不能及时处理
在使用 httpc 的时候发现了这个问题
目前我们项目解决方案是实现一个服务进行域名解析, 解析得到地址之后再用ip地址进行连接
但感觉还是底层解决掉比较好

**Comment by cloudwu** [comment]
我会考虑这个问题, 不过实现完整的 dns 异步解析会很麻烦.  短期内很难搞定.

**Comment by cloudwu** [comment]
作为一个变通的解决方案, 我给 skynet 增加了一个异步 dns 查询库
https://github.com/cloudwu/skynet/commit/a9b1993686ae0cb46336352dae2493ff01e2a11a

因为不太想改变原有的行为(有潜在的破坏老代码的可能性), 这样一个额外的库的形式会好一点.
你看看能不能满足需要?

**Comment by cloudwu** [comment]
另外, 如果在 httpc 中使用 ip 做 host 的话, 需要自己在 header 里指定正确的域名. 我增强了 httpc 模块这方面的支持:
https://github.com/cloudwu/skynet/commit/36ed8679b869c17f84e1a46db4f702470385c5ea

**Comment by JiessieDawn** [comment]
项目中一般都可以明确哪些地方使用域名进行连接 这样就已经可以实现需求了

**Comment by cloudwu** [comment]
注意，今天打了个 patch 修复了 udp 模块中的一个内存泄露问题。 https://github.com/cloudwu/skynet/commit/03399e86a9f5886e4227cbbf6a5508263b1fa7a3

**Comment by cloudwu** [comment]
我更新了 httpc 模块， 允许使用异步 dns 查询了。
