### ISSUE TITLE
sharemap:commit失败

### ISSUE THREAD

**Issue by jintiao** [cloudwu/skynet#257]
https://github.com/cloudwu/skynet/blob/master/test/testsm.lua#L35
只要把代码里{ x=0,y=0,s="hello" }的任意一项数据去掉，就会造成sharemap:commit调用出错。

例如改成{ x=0,y=0}，就会报以下错误：
[:01000010] init service failed: gettable chain too long; possible loop
stack traceback:
	[C]: in function 'sproto.core.encode'
	./lualib/sproto.lua:54: in function 'sproto.encode'
	./lualib/sharemap.lua:22: in function 'sharemap.commit'
	./test/testsm.lua:49: in local 'start'
	./lualib/skynet.lua:630: in function <./lualib/skynet.lua:627>
	[C]: in function 'xpcall'
	./lualib/skynet.lua:635: in upvalue 'init_service'
	./lualib/skynet.lua:648: in upvalue 'f'
	./lualib/skynet.lua:105: in function <./lualib/skynet.lua:104>

如果设计的本意是强制proto中每一项都不能为空，那使用起来就不大方便了。

**Comment by cloudwu** [comment]
这是个  bug, 已修复。 谢谢
