### ISSUE TITLE
LoginServer 406

### ISSUE THREAD

**Issue by flashjay** [cloudwu/skynet#259]
if not conf.multilogin then
		if user_login[uid] then
			write(fd, "406 Not Acceptable\n")
			error(string.format("User %s is already login", uid))
		end

		user_login[uid] = true
	end

	local ok, err = pcall(conf.login_handler, server, uid, secret)
	-- unlock login
	user_login[uid] = nil

1、loginserver.lua 这段代码“406 Not Acceptable”部分永远不会执行到；
2、建议：WIKI和范例都没有合适的用户退出流程和实现？

**Comment by cloudwu** [comment]
为什么执行不到?

**Comment by cloudwu** [comment]
loginserver 本身只负责框架上的认证,不负责处理用户在线或离线状态. 这些是 `conf.login_handler` 也就是你注册的处理方法去做的.

如果你需要一个用户只能有一个实例在线, 那么你应该在那里记录并判断.

同理, 在你自己的设计下, 到底同一个用户再登录的时候, 是顶掉前一次还是拒绝登录,还是允许同时登录, 都是你的业务设计的责任, 当然,实现也是你来做的.

**Comment by flashjay** [comment]
哦哦，了解了；这部分是防止在调用login_handler的时候多个并发请求导致多个同时登陆：）
这个提示应该是这样的：User %s is already in logining progress
