### ISSUE TITLE
Lua seri lib crash when table depth more then 33

### ISSUE THREAD

**Issue by hlouis** [cloudwu/skynet#265]
Follow the simpest test service to recreate this crash:

-----------------------------------------------------------------------
local skynet = require "skynet"

local function _key()
end

local tbl1 = {}
tbl1['hehe'] = { lala = _key }

local tb = {}
local dtb = tb
for i=1,40 do
	local t = {}
	tb[i] = t
	tb = t
end

local function _test()
	-- test more depth table
	skynet.pack(dtb)
end

skynet.start(function()
	skynet.fork(_test)
end)

**Comment by hlouis** [comment]
This crash only happen on mac OSX, can't reproduce on ubuntu 14.04 and CentOS 6.5

**Comment by cloudwu** [comment]
This patch may fix this issue :)

**Comment by hlouis** [comment]
This issue is fixed, tks
