### ISSUE TITLE
socketchannel中有在gc中调用socket.close

### ISSUE THREAD

**Issue by gaopan461** [cloudwu/skynet#270]
channel_meta.__gc = channel.close
而channel.close->close_channel_socket->socket.close，这样就是在gc中调用了socket.close，是不是应该改为调用socket.shutdown？

**Comment by cloudwu** [comment]
这里涉及 socket 不准在 __gc 里调用 close , 是因为 close 有可能需要等待别的 coroutine 读 socket. 本质上是由于 socket 是一个 id 而不是对象。

而 socketchannel 是一个对象，如果触发 gc 则一定没有上诉情况。
另外在  close channel socket 里也用 pcall 调用，保证在 gc 是不抛出异常。

**Comment by gaopan461** [comment]
谢谢，顿时明白了，socketchannel管理一个socket，在gc时一定不会出现还有co等待读的情况
