### ISSUE TITLE
debug_console的inject命令用于热修复无法获取变量的问题以及正确的使用办法

### ISSUE THREAD

**Issue by antsmallant** [cloudwu/skynet#271]
我使用inject命令来热修复我的服务， 发现没法获取到原服务的一些变量， 即下面代码中提到的vars变量，请问我的使用方法是否有问题？ 另外，想知道除了inject，还有什么方法可以热修复，除了用snax框架写的服务

我的服务的代码大概如下：
local skynet = require "skynet"
local command = {}
local vars = {j = 100}

function command.a()
    vars.j = vars.j + 1
    print("vars.j = ", vars.j)
    return {"ok"}
end

skynet.start(
  省略代码
}

修复的代码如下：
if not _P then
    print("hotfix fail, no _P")
end

local command = _P.lua.command
local vars = _P.lua.vars

command.a = function ()
    vars.j = vars.j + 2
    print("new vars.j = ", vars.j)
    return {"ok"}
end

**Comment by cloudwu** [comment]
其实 inject 就是让你可以在那个服务运行一段 lua 脚本.  `_P`  仅仅是帮你从 upvalue 里取了一些东西回来.

这里 vars 是 command.a 的 upvalue , 如果 inject 没有帮你去取, 那么你可以自己用 lua 的 debug 库去找到它.  这些需要你有 lua debug api 的只是,可以去看看文档. 

换句话说, inject 只给你了最基本的能力. 如果你要做的事情是一个经常性的, 可以自己封装一套库.

**Comment by antsmallant** [comment]
@cloudwu  感谢云大指导，参考skynet/inject.lua的代码，顺利把我的问题解决了：）
