### ISSUE TITLE
使用debug_console无法退出debug模式

### ISSUE THREAD

**Issue by adzhang** [cloudwu/skynet#276]
输入空cmdline或者cont都不能退出debug模式

**Comment by cloudwu** [comment]
要先进入 debug 模式才可以退出它.

**Comment by adzhang** [comment]
服务已经进入Enter debug mode，通过上面两种方式都退不出来。

**Comment by cloudwu** [comment]
我试了一下可以,你可以调试一下看为什么.

**Comment by adzhang** [comment]
原来我这边的终端回车输入的是 \r\n，问题解决了。^ ^
