### ISSUE TITLE
lua-netpcak.c 建议增加一个清理 fd 内存的接口

### ISSUE THREAD

**Issue by JiessieDawn** [cloudwu/skynet#280]
lua-netpcak.c 建议增加一个清理 fd 内存的接口用于在连接关闭之后清理 fd 上的 uncomplete netpack
连接关闭之后不清理 uncomplete netpack 的话
远程可以通过简单的重复 connect -> send uncomplete netpack -> close connection 使服务器的内存不停增长

**Comment by JiessieDawn** [comment]
socket id 环回时还会影响正常连接(这个还没测试到)

**Comment by cloudwu** [comment]
我会看一看

**Comment by cloudwu** [comment]
我在 lua-netpack.c 里处理 socket 断开（或出错）时处理了 uncomplete 的结构清理，麻烦 review 一下 :)

**Comment by JiessieDawn** [comment]
ok 了
