### ISSUE TITLE
skynet.lua 的三处笔误

### ISSUE THREAD

**Issue by chuenlungwang** [cloudwu/skynet#283]
我在阅读 skynet.lua 代码时发现了 3 处笔误；

1.	177 行,  当 size == nil 时 param 是一个 Lua 字符串不需要被删除, 当 size ~= nil 时, param 才是一个 light userdata 才需要被回收内存；
2.	435 行, 格式化字符串缺少 %s ；
3.	482 行, 最后一个参数或许需要 proto[prototype].name , 因为 unknown_request 把最后一个参数当做 string 类型；

**Comment by cloudwu** [comment]
谢谢
