### ISSUE TITLE
lua-socket.c 两处疑似 bug

### ISSUE THREAD

**Issue by chuenlungwang** [cloudwu/skynet#286]
1.	`check_sep` 方法，当比较到最后一个 `struct buffer_node` 的末尾，若再取其下一个(不存在的节点)进行比较时将出错；
2.	`pop_lstring` 方法，若 `skip` 横跨三个 `struct buffer_node` 时将会出错，因为当 sz 不断减小之后最终会小于 `skip`，使得 `luaL_addlstring(&b, current->msg + sb->offset, (sz - skip < bytes) ? sz - skip : bytes);` 错误地添加 bytes长度。虽然这个问题没有出现在框架代码中，但有可能会有人恶意调用 `readline` 设置非常长的分割字符串；

**Comment by cloudwu** [comment]
1. 我不认为能走到那种情况，你可以制造一个案例试试。
2. 似乎是一个问题，我再核对一下增加判断。

**Comment by chuenlungwang** [comment]
我尝试改变登录流程的分割字符串为 `"\r\n"`，然后在 examples/login/client.lua 中的 `writeline` 方法改为 `"\r"` 确实没有出错； 不过 lua-socket.c 中的 check_sep 的 `node = node->next;` 确实没有检查下一个是否为NULL，请问是哪一步做到不出错的？

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/blob/master/lualib-src/lua-socket.c#L335

**Comment by chuenlungwang** [comment]
原来就在这里，一不小心就看飘了眼。 O(∩_∩)O谢谢
