### ISSUE TITLE
关于安全退出skynet

### ISSUE THREAD

**Issue by xmlzhaodj** [cloudwu/skynet#288]
推荐用什么方法来实现。主要需求在于kill或者关服指令发起后，部分有状态的服务需要做完退出事件，最后才退出进程。

simplemonitor只是获取到服务退出消息吧。具体的实现是否还是需要增加服务的退出消息，然后自杀？

或者有其他处理方案？谢谢

**Comment by niuys** [comment]
由一个服务专门用于管理其他服务的启动和关闭，关闭的时候调用每个snax服务的exit接口或者自定义接口。

**Comment by linse073** [comment]
请问通常是如何通知这个服务做善后工作的？

**Comment by tangyiyang** [comment]
我是这么做的，按照你的业务，给每个服务发送一个close的消息，收到消息后，每个服务该干啥干啥，干完了skynet.exit()。
 举个例子：在我的服务里，当watchdog收到close 消息之后，给所有的active的agent发close消息，让他们做好自己的善后工作之后退出。
然后又一个moniter，会记录所有的service，等所有的service都关闭了，就可以kill掉这个进程自己了。

至于怎么通知，你写个web服务，然后用curl发个消息给这个服务就行了。比较简单粗暴。:D

**Comment by dpull** [comment]
我们项目的做法  http://www.dpull.com/blog/2014-04-08-skynet_exit

**Comment by smlam** [comment]
我在 `skynet.error` 後行 `skynet.abort`。
發覺 message 未 flush 已經掛掉。
有什麼辦法令到 logger flush？

**Comment by cloudwu** [comment]
自定义一个 log 服务，接收一个消息叫结束，然后再 abort 前 call 它，返回后再 abort 。
