### ISSUE TITLE
service_harbor.c 疑似内存泄露

### ISSUE THREAD

**Issue by chuenlungwang** [cloudwu/skynet#290]
云风先生，我在阅读 service_harbor.c 源码时一直没有找到 `dispatch_name_queue` 和 `dispatch_queue` 方法在调用 `send_remote` 之后释放 *已经发送过的buffer* 的内存指令？ 请问是否我遗漏哪些地方还是确实没有释放？ 不吝指正。

**Comment by cloudwu** [comment]
所有进入 socket 模块的 buffer 都是这里释放 https://github.com/cloudwu/skynet/blob/master/skynet-src/socket_server.c#L707

你不是读过 https://github.com/cloudwu/skynet/blob/master/lualib-src/lua-socket.c#L486-L490 ?
也是一样的.

**Comment by chuenlungwang** [comment]
可是 [这里](https://github.com/cloudwu/skynet/blob/master/service-src/service_harbor.c#L329) 将 buffer 的内容拷贝出来了.

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/blob/master/service-src/service_harbor.c#L680 这里释放的。

不过 `pop_queue` 之后调用 `send_remote` 似乎没有释放。这个分支只在启动的时候调用有限几次，我需要再核对一下。

**Comment by cloudwu** [comment]
应该修好了. 这个泄露危害很小，不改的话，只在握手阶段有一两次没有释放。所以最好能帮忙再复核一下，怕万一改错了，反而不好。

**Comment by chuenlungwang** [comment]
的确是修好了。您写的代码非常优雅，对我来说简直是饕餮盛宴，希望有一日能与您共事。

**Comment by cloudwu** [comment]
谢谢, 什么时候有兴趣, 欢迎给我份简历.
