### ISSUE TITLE
skynet timer的疑问

### ISSUE THREAD

**Issue by linxiaolong** [cloudwu/skynet#291]
###疑问
static void 
timer_update(struct timer *T) {
	// try to dispatch timeout 0 (rare condition)
	timer_execute(T);
        //NO LOCK，假设增加了定时器A，则该定时器永远不会执行到
	// shift time first, and then dispatch timer message
	timer_shift(T);

	timer_execute(T);

}

注释NO LOCK部分

**Comment by cloudwu** [comment]
你说的情况不可能发生. 或者请给出 test case

**Comment by cloudwu** [comment]
这里以前修过这个 bug, 但是没有改对. 把锁调整一下就可以了.
谢谢.
