### ISSUE TITLE
关于lualib/skynet.lua里的profile模块的疑问

### ISSUE THREAD

**Issue by linxiaolong** [cloudwu/skynet#297]
此处：
coroutine.resume = profile.resume
coroutine.yield = profile.yield
我看了lualib-src/lua-profile.c模块，发现除了额外做了部分时间记录的工作好像没其他作用？请教一下，使用这个模块的考量是什么？

**Comment by cloudwu** [comment]
寻找有性能问题的热点用。

**Comment by linxiaolong** [comment]
好的，以为是另有考虑。
