### ISSUE TITLE
关于request_package结构体dummy bytes的疑问

### ISSUE THREAD

**Issue by linxiaolong** [cloudwu/skynet#301]
socket_server.c文件内有定义如下：
struct request_package {
	uint8_t header[8];	// 6 bytes dummy
	union {
		char buffer[256];
		struct request_open open;
		struct request_send send;
		struct request_send_udp send_udp;
		struct request_close close;
		struct request_listen listen;
		struct request_bind bind;
		struct request_start start;
		struct request_setopt setopt;
		struct request_udp udp;
		struct request_setudp set_udp;
	} u;
	uint8_t dummy[256];
};

想问下，这里dummy bytes存在的意义是什么？如果是出于内存对齐考量的话，一般来说编译器会进行优化的吧，不需手动填充？

**Comment by cloudwu** [comment]
保证有充足后续空间. 你需要读代码.

**Comment by cloudwu** [comment]
例如: https://github.com/cloudwu/skynet/blob/master/skynet-src/socket_server.c#L1278

**Comment by cloudwu** [comment]
这里的结构并不做持久储存用, 所以无所谓.

**Comment by linxiaolong** [comment]
我看了下还是存在疑问：
1、例子中的host字段，可以开足够固定的数组就可以解决？
2、我想到一种用处，那就是开静态内存的时候，使用可以利用后面的dummy数组来塞一些定制数据，不过我看了涉及到的代码，似乎没这样用
3、header字段开了8字节，也只是用了最后2个字节

**Comment by cloudwu** [comment]
不想解释了. "这里的结构并不做持久储存用, 所以无所谓."
如果真的觉得有所谓, 可以 fork 改改.

**Comment by cloudwu** [comment]
这只是一个简单粗暴的方法来让其它部分需要满足的约定最少. 比如如果扩展一个子结构,允许 256 字节以下的 padding 串. 和目前已有的实现无关. 而这些子结构很多也是一开始没有的.

至于 header 是为了对齐.

**Comment by linxiaolong** [comment]
明白了
