### ISSUE TITLE
skynet.send的疑惑

### ISSUE THREAD

**Issue by wangyanglong** [cloudwu/skynet#306]
服务中注册的skynet.dispatch函数中写成 skynet.ret(skynet.pack(f(...))),会导致skynet.send出错,
报错信息如下:
[:01000014] Response message :
[:01000014] lua call [100000f to :1000014 : 0 msgsz = 0] error : ./lualib/skynet.lua:506: ./lualib/skynet.lua:436: Unknown session : 0 from 100000f
stack traceback:
	[C]: in function 'assert'
	./lualib/skynet.lua:506: in function 'skynet.dispatch_message'
我的目的是：一个服务的调用，既可以被send，也可以被call,但是目前的表现是send会报错，我应该使用skynet.register_protocol自定义dispatch函数吗？谢谢。

**Comment by cloudwu** [comment]
你返回一个不需要返回的请求当然出错了. 不然接收方以什么逻辑处理返回包?

**Comment by wangyanglong** [comment]
我是否可以这样理解，skynet的服务是既可以被send，也可以被call的，但是在同一一个服务中，这两种调用方法其实是互斥的，谢谢

**Comment by PowerGit** [comment]
我也遇到了一样的疑问，请问怎么解决的呢？

**Comment by PowerGit** [comment]
知道原因了，send发送的消息 dispatch收到的session是0, 用这个来判断是否需要ret就行了

**Comment by cloudwu** [comment]
一条消息是否需要回应，不应该是实现这个消息处理函数，以及发送消息的人心里都应该清楚吗？它是一个确定的行为，为何要推给一个和逻辑无关的 session 来决定。

当你实现了一条消息的处理过程：如果有回应，而发送消息的人用 send （无视回应）；或是你实现了一条消息不给回应，而发送消息的人用 call （等待回应）；都是错误的行为。

如果脑子是迷糊的，无法设计清楚，那么我建议只用 call 一种方式，把 send 这个 api 屏蔽掉，直到能设计清楚为止。

**Comment by PowerGit** [comment]
谢谢云大耐心解答。可能我上面表达有误，就是接收方如何判定该消息是send或是call。
我现在用这样的方法来判定处理完是否需要调用ret，是否正确呢？
```
    skynet.dispatch("lua", function(session, source, cmd, ...)
        local f = assert(CMD[cmd])
        if session > 0 then
            skynet.retpack(f(...))
        else
            f(...)
        end
    end)
```

**Comment by cloudwu** [comment]
接收方应该按业务约定来决定，不应该由发送方的行为。发送方也应该按业务约定来调用对应 api ，如果使用错误，应该报错。

**Comment by PowerGit** [comment]
再次感谢云大耐心解答。那是否可以理解为 一个server的设计应该避免同时支持send和call两种调用方式而只使用一种，或者将skynet.ret调用写在消息处理函数内。

**Comment by cloudfreexiao** [comment]
应该是 你先得想清楚 啥时候（哪些业务） 用call 或者 send 来处理   而不是避免某种 发消息的情况

**Comment by cloudwu** [comment]
怎么设计框架是你的事情。你完全可以把不需要回应和需要回应的处理函数分到两个 table 里，分开处理。
