### ISSUE TITLE
关于单个 lua 服务内存大小的疑问

### ISSUE THREAD

**Issue by llj098** [cloudwu/skynet#312]
在初步测试 lua 服务的内存消耗大小，得到:  __形如 example/agent.lua 的服务，占用 200-300 KB内存。__

测试方法如下：分别启动 1000 、2000 个 agent 服务，即，将 `example/main.lua` 中加入

```
        for i = 1, 2000 do -- or 1000
                skynet.newservice("agent")
        end
```

`ps -aux`  1000个 、2000个 服务的执行结果：

```
root@32d0389f7e0d:~/skynet# ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      7184 31.6 15.4 447460 315924 pts/0   Sl+  02:27   0:01 ./skynet examples/config
```

```
root@32d0389f7e0d:~/skynet# ps -aux
root      7146 21.5 28.9 730084 592632 pts/0   Sl+  02:24   0:04 ./skynet examples/config
```

也就是说，每一个 形如 agent 的 lua 服务要占用 200~300KB 内存，我有两个问题：

1. 我这种测试方法是否正确？
2. 如果正确，既然已经启用了 code share，为什么每一个lua 服务还需要这么多的内存呢？

谢谢。

------------

尝试这加入了自己的业务逻辑代码，发现100个lua服务，占用 680M+ 内存. 源码如下：

```lua

-- imagent.lua

local skynet = require "skynet"
require "skynet.manager"        -- import skynet.register

local parser = require"sip.sipparser"
local message = require"sip.sipmessage"

skynet.start(function()
end)

```

```lua
-- example/config
local skynet = require "skynet"
local sprotoloader = require "sprotoloader"

local max_client = 64

skynet.start(function()
        print("Server start")
        skynet.uniqueservice("protoloader")
        local console = skynet.newservice("console")
        skynet.newservice("debug_console",8000)
        skynet.newservice("simpledb")
        for i = 1, 100 do
                skynet.newservice("imagent")
        end


        local watchdog = skynet.newservice("watchdog")
        skynet.call(watchdog, "lua", "start", {
                port = 8888,
                maxclient = max_client,
                nodelay = true,
        })
        print("Watchdog listen on ", 8888)

        skynet.exit()
end)
```

内部逻辑代码不方便贴出，主要就是 sipparser 和 sipmessage 两个文件，实现 sip 的解析和消息封装。 主要引用第三方库： penlight, lpeg, microlight， ps -aux 结果(100个 imagent)：

```
root@32d0389f7e0d:~/rongtalk/app/src/main/assets/sip# ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root     13845 31.0 33.8 828388 693000 pts/0   Sl+  07:49   0:00 ./skynet examples/config
```

内存使用正常么？

**Comment by zxfishhack** [comment]
似乎是example引用的sprotoloader占用了100多KB的内存，若是一个最小的agent，即什么包都不引用，我这测试大小为63K左右

**Comment by llj098** [comment]
hi @zxfishhack 我更新了一下正文，最新测试结果发现加入逻辑之后，每一个服务大概 6-7M

**Comment by leeonix** [comment]
@llj098 问题是，你要问什么问题呢？即便这样占，那又有什么问题呢？

**Comment by LittlePeng** [comment]
@leeonix 内存消耗相比Erlang高太多，在IM服务器上单机需求是 ~100w agent

**Comment by llj098** [comment]
@leeonix 我的问题是，如果一个服务（轻量进程）可以用到几百K甚至更高（我的场景6M），那么这个服务（轻量进程）就太重了。和 skynet 最初设计主旨有一点点不符？

**Comment by llj098** [comment]
@leeonix 同时，我对skynet还是新手，我也是想弄清楚：我这样测试方法，对不对，有没有什么问题。

**Comment by cloudwu** [comment]
skynet 并没有要求你用单个 agent 处理一个用户. 你应该根据你的需求来做设计.

**Comment by leeonix** [comment]
@llj098 首先，轻量级是代码轻量，这才是主旨。这与占用内存大小并没关系。况且内存现在白菜价，我买了32G内存，也没有多少钱。现在你买不到64G的内存，别说开发服务器了。

其次，如果你的逻辑代码没法公开一些典型代码，是没法说清楚“占”多少内存的。就好比看病一样，你总是说，我病很重啊。那就只能病很重了。

云风的主旨是，一个好CPU就定一个高级程序员，如果内存不够，就加内存条。（笑

**Comment by lf723** [comment]
一个服务占用了6M+，一般是设计问题，一些共享配置可以放到sharedata等，包含业务逻辑处理也不应该放到agent中，这些处理好，agent占用自然下降
