### ISSUE TITLE
关于socketchannel的疑问

### ISSUE THREAD

**Issue by hqwrong** [cloudwu/skynet#314]
关于socketchannel，有个问题没想明白。

socketchannel是异步send，有一个poll的大循环来处理socket的事件，如果侦测到这个socket已被对方关闭的话，就会给该socket置一个INVALID标志，并通知发起写请求的服务。这个服务收到通知后会清掉对应状态，下次再发起写请求，它会尝试重连。

我没想明白的是，是不是有这种情况：

   如果底层侦测到socket被对方关闭，将该socket状态置为INVALID，但发起服务还没有收到底层的通知，这时它再发起写请求，还会重用这个invalid socket, 那么代码应该会报错.

这是在服务器上收集到的log，可能和这个有关:

./skynet/lualib/socketchannel.lua:268: in function 'request'
./service/replay.lua:53: in function 'func'
./skynet/lualib/skynet.lua:370: in function 'f'
./skynet/lualib/skynet.lua:113: in function <./skynet/lualib/skynet.lua:112>

**Comment by cloudwu** [comment]
socket  id 几乎不会被重用吧? 要等 32bit 轮转才重用的啊.

**Comment by hqwrong** [comment]
不是重用的问题啊 是底层侦测到该socket已经被对方关闭 但上层还没收到通知，还在向这个已关闭的socket写数据

**Comment by cloudwu** [comment]
你什么版本? socketchannel.lua:268 并不是 request 这个函数.

**Comment by hqwrong** [comment]
哦 是mmzb项目fork的分支， 对应master是这一行

https://github.com/cloudwu/skynet/blob/master/lualib/socketchannel.lua#L320

**Comment by cloudwu** [comment]
抛出 socket_error 不是设计特性吗?

**Comment by hqwrong** [comment]
但我认为我的用法是合理的，不应该抛出错误呀。
我的用法：

   local sockfd = Socketchannel.channel{host = ip, port = port}
    while true do
        local data = table.remove(verify_queue)
        if data then
            data = json.encode(data)
            local raw = struct.pack(">I4c0", #data, data)
            sockfd:request(raw)
        else
            Skynet.sleep(10*100)    -- 10 seconds
        end
    end

**Comment by jintiao** [comment]
我插一句，涉及到IO失败这类错误，你想要框架怎么处理，通知你还是不通知你呢，现在没有任何系统能保证IO操作100%成功啊

**Comment by cloudwu** [comment]
socket channel 的请求总有可能失败, 如果失败是因为 socket error, 你需要自己重发.

这个是之前讨论过的: socket error 是框架帮你重发, 还是业务层自己处理. 结论是, 业务层自己处理比较好.

**Comment by cloudwu** [comment]
btw, 检查 socket channel request 的错误是不是 socket error 的方法是用 pcall, 然后判断错误对象是否是

Socketchannel.error

**Comment by hqwrong** [comment]
哦 我问的其实就是这个error是不是合理的，我应不应该用pcall调用。 因为我看socketchannel本身有做断线重连的，所以猜测它会handle所有情况。

再麻烦看一下我这么改是对的么：

    local sockfd = Socketchannel.channel{host = ip, port = port}
    while true do
        local data = table.remove(verify_queue)
        if data then
            data = json.encode(data)
            local raw = struct.pack(">I4c0", #data, data)
            local ok, err = pcall(sockfd.request, sockfd, raw)
            if not ok then
                if err == Socketchannel.error then
                    Skynet.sleep(10*100)
                else
                    error(err)
                end
            end
        else
            Skynet.sleep(10*100)    -- 10 seconds
        end
    end

**Comment by cloudwu** [comment]
重连不用等待。断开后第二次请求就已经阻塞在连接上了。
