### ISSUE TITLE
关于netpack的疑问

### ISSUE THREAD

**Issue by ag6ag** [cloudwu/skynet#315]
最近看了netpack的实现有一个疑问
我看到netpack.filter对消息解析后是通过lightuserdata把数值返回到lua的,lightuserdata应该是没有办法被gc回收的,这样的话是不是会有内存泄露的问题呢.还是说通过了别的方式回收了内存呢?
目前我只发现在调用netpack.tostring的时候会把这个lightuserdata给释放了.
另外我看到examples的simpledb的例子里watchdog用了gate,而gate是根据snax.gateserver实现的,然后通过skynet.redirect转发给agent,agent再通过host:dispatch解析数据,并没用netpack.tostring去处理.这样是不是会内存泄露了呢?
而且如果要手动用netpack.tostring感觉这样就把内存管理转交到lua层了,这样感觉比较复杂.
不知道我是不是理解有问题?

**Comment by cloudwu** [comment]
首先, 不要直接调用 netpack 的接口, 它只是用于更上层的模块. 如果你想实现类似的东西, 建议自己写, 如果你想使用 netpack, 请务必了解它的实现.

skynet 的消息在 lua 服务中都可以有两种形式发送出去.

1. 发送 lua string , 框架会复制一份发送.

2. 发送 lightuserdata , 由接收者(框架)释放.  

如果你采用第 2 种形式, 可以避免一次消息复制, (调用 netpack 的 gate 使用的方式) . 但是, 你需要确保, 从 netpack 返回 lightuserdata 到发送出去之间, 不可以有阻塞调用, 不可以抛出 error .

**Comment by ag6ag** [comment]
谢谢,云大的解释.还有一点不太理解的就是
https://github.com/cloudwu/skynet/blob/master/examples/agent.lua#L51
这里的msg应该是从gate转发来的吧,但是我感觉这里并没有进行释放.难道是unpack的调用方对msg进行了释放吗?

**Comment by ag6ag** [comment]
刚刚自己看了下底层的,的确是在转发后就会由底层来释放这个lightuserdata.是我自己之前理解的有问题.
