### ISSUE TITLE
关于rwlock的疑问

### ISSUE THREAD

**Issue by linxiaolong** [cloudwu/skynet#319]
static inline void
rwlock_rlock(struct rwlock *lock) {
    for (;;) {
        while(lock->write) {
            __sync_synchronize();
        }
        __sync_add_and_fetch(&lock->read,1);
        if (lock->write) {
            __sync_sub_and_fetch(&lock->read,1);
        } else {
            break;
        }
    }
}

static inline void
rwlock_wlock(struct rwlock *lock) {
    while (__sync_lock_test_and_set(&lock->write,1)) {}
    while(lock->read) {
        __sync_synchronize();
    }
}

rwlock.h里面的读写锁实现，想问下两个__sync_synchronize内存屏障是出于什么考量？read和write两个均用原子操作来设置，这个应该已经保证了多核cache的一致性？

**Comment by cloudwu** [comment]
原子操作和内存屏障是两回事, 原子操作只是让读写保证原子性而已.

**Comment by cloudwu** [comment]
这里用 http://locklessinc.com/articles/locks/  cpu_relax() 好一些.

**Comment by t0350** [comment]
cpu_relax应该只是对spinlock busy wait的优化，没明白rlock和wlock两处barrier是否必要。
rlock似乎没有在临界区前加barrier？对wlock那个barrier理解是避免临界区的代码乱序到前面，但是这样不是只要把barrier挪到循环外，而不需要放在循环内？
不知道是不是理解错了，求云风指教，谢谢！

**Comment by cloudwu** [comment]
目前 skynet 可直接用 pthread 的 rwlock, 所以不用纠结这个问题。

**Comment by linan0827** [comment]
我觉得两处__sync_synchronize()均无必要，gcc定义的几个原子操作均可视为full-barrier。
https://gcc.gnu.org/onlinedocs/gcc-4.1.2/gcc/Atomic-Builtins.html

**Comment by cloudwu** [comment]
```
while(lock->write) {
  __sync_synchronize();
}
```
展开就是
```
if (!lock->write) goto out;
__sync_synchronize();
if (!lock->write) goto out;
__sync_synchronize();
if (!lock->write) goto out;
__sync_synchronize();
...
out : 
```
这里想设 barrier 的是对 lock->write 的循环读操作，和后面的操作无关。

**Comment by linan0827** [comment]
谢谢解答。

**Comment by Zirpon** [comment]
我真的不懂 这个__sync_synchronize 在这里是用来做什么的

**Comment by Zirpon** [comment]
非常confuse

**Comment by Zirpon** [comment]
cloud wu, pleaes refer to this : __asm__ (".byte 0xf3, 0x90")
