### ISSUE TITLE
c.command接口优化

### ISSUE THREAD

**Issue by niuys** [cloudwu/skynet#321]
skynet.lua里用到了c.command接口，这个接口的参数和返回值都是用的字符串，需要tostring和tonumber的调用，返回值又要经过sprintf。NOW和TIMEOUT的返回值是递增的，它的字符串是重用性很低的，调用次数和产生的字符串的量又是很大的，有没有必要调整一下接口的实现，跳过c.command这一层?

**Comment by cloudwu** [comment]
如果你有证据证明这是性能热点, 我可以考虑改一下.

**Comment by cloudwu** [comment]
如果只是在 lua 里对 now 和 timeout 做优化, 可以在下个版本里做一点.

**Comment by cloudwu** [comment]
看一下是不是这个意思?

**Comment by niuys** [comment]
是不是热点可能和具体使用的方式有关，我们现在调用now,time,timeout这三个接口是非常频繁的，根据prof结果发现在返回值sprintf和tostring是一个地方，sprintf也会被tonumber调用，然后lua的newlstr也是一个地方，当然newlstr不只是这里调用的。这些加起来有5个点。因为中间过程产生的字符串是一次性的，估计对内存回收还有影响，这个就没测出来具体数据。
我想是直接不用sprintf接口，避免任何的字符串和数字之间的转换，skynet.time接口也直接c接口实现。

**Comment by cloudwu** [comment]
上面已经改了， 但我不想给 skynet 的核心模块增加新的 C API 。

**Comment by niuys** [comment]
明白。谢谢云大。
