### ISSUE TITLE
关于sproto的一个建议

### ISSUE THREAD

**Issue by ag6ag** [cloudwu/skynet#324]
我在写一个C#的sproto的解析器的时候发现sproto在decode数组类型的时候没有办法预先知道数组的长度,感觉这样在解析的时候比较不方便,我看了代码应该是可以提前计算出数组的长度的,所以修改了下加上了长度.我感觉有个长度对很多语言做解析器应该会方便很多.所以在这里提议下.

**Comment by cloudwu** [comment]
如果可以算出来, 你可以在  C# 实现里算吧? 不建议修改 wire 协议.

**Comment by ag6ag** [comment]
应该不会修改到协议本身,我只是在sproto_arg里加多了一个用来表示数组长度的字段,这个字段是可以在decode的时候得出来的,比如整型数组:
https://github.com/cloudwu/skynet/blob/master/lualib-src/sproto/sproto.c#L1009
这里可以根据sz/sizeof(uint64_t)得出这个数组的长度,然后通sproto_arg传给上层就行了.这个值也只能通过
在sproto.c才能得到吧.
对结构数组和字符串数组可能就会麻烦点
https://github.com/cloudwu/skynet/blob/master/lualib-src/sproto/sproto.c#L953
要先把长度算出来再传上去.

**Comment by cloudwu** [comment]
我需要考虑一下,这个优先级别不高.

**Comment by ag6ag** [comment]
是的,这个并不是特别重要,有这个只是说能方便在写一些其它语言的解释器的时候容易一点.直接分配一个固定长度的数组总会比别的方法容易一点.
