### ISSUE TITLE
skynet_send 错误时, 是否增加释放 data 判断?

### ISSUE THREAD

**Issue by KAndQ** [cloudwu/skynet#327]
在 skynet_server.c 的 skynet_send 函数里面, 当产生错误的时候, data 是直接被 skynet_free 掉的, 但是参考 skynet_sendname, 在错误的时候它会有 1 个 if (type & PTYPE_TAG_DONTCOPY) 的判断. 

skynet_send 里面是否也需要增加 type 的标记判断?

if ((sz & MESSAGE_TYPE_MASK) != sz) {
	skynet_error(context, "The message to %x is too large", destination);
	if (type & PTYPE_TAG_DONTCOPY)
		skynet_free(data);
	return -1;
}

...

if (skynet_context_push(destination, &smsg)) {
	if (type & PTYPE_TAG_DONTCOPY)
		skynet_free(data);
	return -1;
}

**Comment by cloudwu** [comment]
ok, 我会看一下.
