### ISSUE TITLE
部分客户端的消息包收不到

### ISSUE THREAD

**Issue by wangyanglong** [cloudwu/skynet#334]
云大，将skynet部署到远程服务器时，部分客户端会出现这种情况，服务器会收到客户端的socke连接信息，但是后续的其他消息包会收不到，除第一条socket创建日志外，gateserver中打印不出其他log。可以确定客户端是发出了消息包，因为公司内，其他电脑能正常登录(这台电脑之前可以正常登录)。出问题的电脑连接本地服务器是没有问题的。本地服务器是用得mac，远程服务器使用的是centos，希望你能给一点解决思路，谢谢。

**Comment by cloudwu** [comment]
思路吗? tcpdump 抓包看.
