### ISSUE TITLE
skynet.cache.clear 可能致内存泄露

### ISSUE THREAD

**Issue by flashjay** [cloudwu/skynet#336]
我在测试的时候，因为不想要某lua service代码缓存，所以在这个service里面调用了skynet.cache.clear，但是会导致内存一直增长。

看不懂cache这部分实现代码。

**Comment by flashjay** [comment]
就算把skynet.cache.clear去掉，用cmem看也总有 32字节的泄露：
skynet > cmem
...
:0000041e	32
:0000041f	32
:00000428	32
:00000439	32
:0000043c	32
:0000043d	32
:0000043e	32
:0000043f	32
:00000448	32
:00000459	32
:fffffffe	7040
:ffffffff	8446048

**Comment by cloudwu** [comment]
等我出差回去看一下。不过不要用 cache.clear 清除特定的 lua 服务。它会重置所有的 cache.

你应该写一个极简的程序，用 io.read 读入特定文件，再用 loadstring 加载读入的字符串。loadstring 并不 cache .

**Comment by cloudwu** [comment]
cache.clear 本身并不会释放之前已经加载的的 bytecode , 只是会新建一个空的 cache 。不知道你说的情况是否在此范畴之内？

**Comment by flashjay** [comment]
应该是，通过 cmem 看同一个service泄露的值都是一样的；代码多的 service 泄露的多点。
不过每次都调用cache.clear，是没有必要的；就算是泄露的话应该也还好。
我现在去掉了就不再有内存泄露问题，就是使用的时候要稍微注意。

**Comment by cloudwu** [comment]
这不是泄露, 这是故意的.

特定 lua 代码加载不希望被共享, 请参考我上面写的方法. 不要 clear cache .
