### ISSUE TITLE
gate目录问题

### ISSUE THREAD

**Issue by ballbillow** [cloudwu/skynet#337]
想看下gate服务代码，从文档和代码目录看到好几个和gate相关的代码？
不知道之间是啥关系：
service-src/service_gate.c
lualib/snax/gateserver.lua
service/gate.lua有引用local gateserver = require "snax.gateserver"，但是文档里面好像说是gateserver.lua是范例

**Comment by cloudwu** [comment]
service-src/service_gate.c 是废弃的, 只为兼容过去的应用.

**Comment by ballbillow** [comment]
加个说明比较好，呵呵
