### ISSUE TITLE
操作系统文件句柄数不够的时候会导致cpu 100%

### ISSUE THREAD

**Issue by xinmingyao** [cloudwu/skynet#339]
ulimit  -n 16
./skynet examples/config

在另一终端：
在example/client.lua中增加多个连接:
local i = 1
while i< 10  do
   socket.connect("127.0.0.1", 8888)
   i = i + 1
end
运行 ./3rd/lua/lua examples/client.lua

skynet cpu会到100%并且不会下降
在master分支进行的测试

**Comment by cloudwu** [comment]
这个问题我倾向于不解决.

因为, 当文件句柄数不够的时候, 系统会陷入一种不可能正常运行下去的状态, 很难从错误中恢复. 你应该限制你对外可能的连接数. 比如 gate 就可以限制最大连接.

就这个问题的直接原因是: listen 的连接, 在 accept 时, 由于文件句柄不够, 而不能正常 accept . 而 listen 的 socket 总处于可读状态. 从而导致了死循环. 我认为用复杂的手段去消除这个死循环没有意义（比如可以关闭 listen 的 fd, 然后重新做一次 listen ），也无法从根本上解决问题的（从不正常状态下恢复回来）。

**Comment by xinmingyao** [comment]
如果不解决的话建议在死循环的时候能够输出错误日志，这样能帮助快速定位问题

**Comment by cloudwu** [comment]
你一定会看到文件不能打开的错误日志.

**Comment by cloudwu** [comment]
准确说,程序并没有进入死循环. 如果有新的网络消息进来, 它还是可以正确处理.

当你的 socket 的 `TIME_WAIT` 状态过去(通常要等几分钟), accept 也能继续工作.

**Comment by xinmingyao** [comment]
上面那个case是可以看到文件打开的错误日志，如果网络几分钟后才有响应，客户端会超时掉的，我们一个服务器在压力测试下，socket有泄漏，导致了cpu100%，没有看到文件打开的错误日志，后来gdb跟进去才发现是文件句柄不够

**Comment by cloudwu** [comment]
这里打日志会被刷屏的。

**Comment by cloudwu** [comment]
我做了点修改， 当 accept 的时候发现文件打开超限，则关闭 listen socket 。
现在有更多的出错信息了。
