### ISSUE TITLE
关于“maybe in an endless loop”以及signal调试

### ISSUE THREAD

**Issue by benqktc** [cloudwu/skynet#344]
四个服务之间偶然会发生了“maybe in an endless loop”问题，对四个服务分别signal：只有[:00000059] lua call [0 to :59 : 615251 msgsz = 0] error : [31m(no error message)[0m这样的信息出现。

冒昧请问一下，是否能够确定是[:00000059] 服务的lua代码编写造成的，（用gdb调试skynet，我不会啊T_T。在生产服务器上，这个问题也需要等几天才会重现）

--------------------------------------------------------
# git log
commit 6c33f7bc44d0eafe743e5490af3b1e5d86727c45
Author: Cloud Wu <cloudwu@gmail.com>
Date:   Fri Sep 4 12:14:09 2015 +0800
---------------------------------------------------------

[:00000000] A message from [ :00000012 ] to [ :0000001f ] maybe in an endless loop (version = 143524551)
[:00000000] A message from [ :00000059 ] to [ :00000019 ] maybe in an endless loop (version = 143701823)
[:0000001f] recv a signal 0
[:00000000] A message from [ :00000012 ] to [ :0000001f ] maybe in an endless loop (version = 143524551)
[:00000000] A message from [ :00000059 ] to [ :00000019 ] maybe in an endless loop (version = 143701823)
[:00000019] recv a signal 0
[:00000000] A message from [ :00000012 ] to [ :0000001f ] maybe in an endless loop (version = 143524551)
[:00000000] A message from [ :00000059 ] to [ :00000019 ] maybe in an endless loop (version = 143701823)
[:00000000] A message from [ :00000012 ] to [ :0000001f ] maybe in an endless loop (version = 143524551)
[:00000000] A message from [ :00000059 ] to [ :00000019 ] maybe in an endless loop (version = 143701823)
[:00000012] recv a signal 0
[:00000059] recv a signal 0
[:00000059] lua call [0 to :59 : 615251 msgsz = 0] error : [31m(no error message)[0m
[:00000000] A message from [ :00000012 ] to [ :0000001f ] maybe in an endless loop (version = 143524551)
[:00000000] A message from [ :00000059 ] to [ :00000019 ] maybe in an endless loop (version = 143701823)

**Comment by cloudwu** [comment]
signal 只能打断 lua vm 的运行,不能打断 C 代码的运行.

你的首要任务是确定这几个服务是做什么的, 执行了什么代码. 推断发生了什么事情. 不要过渡依赖调试手段.

**Comment by benqktc** [comment]
[:00000011] LAUNCH snlua pbParser pbc的wrapper
[:00000019] LAUNCH snlua GS_model_userManager  用户信息管理
[:0000001f] LAUNCH snlua GS_model_tableFrame游戏桌子逻辑host
[:00000059] LAUNCH snlua GS_controller_login 游戏登录控制器

单个用户信息是c++实现，在GS_model_userManager 里面管理的是指向c++实例的light user data，为了避免同时访问，在c++模块的访问方法里面用了std::lock_guard<std::mutex>来进行限制比如：

static int l_someAction(lua_State *L)
{

	ServerUserItem* itemPtr = (ServerUserItem*) lua_touserdata(L, 1);
	{
		std::lock_guard<std::mutex> lg(itemPtr->accessMutex);
		//这里是具体的操作

	}
	return 0;
}
---------------------------
会是std::lock_guard<std::mutex>的问题吗
