### ISSUE TITLE
unable to pass compile unser TinyCC

### ISSUE THREAD

**Issue by microcai** [cloudwu/skynet#349]
TinyCC does not have __sync_add_and_fetch/__sync_lock_test_and_set as such.

why TinyCC? because it supper fast to compile C code!

**Comment by microcai** [comment]
OK, 改好了，给个编译速度， CC=tcc make -j8

0.25s !!!!!!!
0.25s 编译完整个项目！！！！！
我了个艹
tcc 实在是快死了

**Comment by cloudwu** [comment]
tcc 有替代品? 所有的原子操作指令定义在这里:

https://github.com/cloudwu/skynet/blob/master/skynet-src/atomic.h
