### ISSUE TITLE
mysql 链接断开的问题

### ISSUE THREAD

**Issue by yingnierxiao** [cloudwu/skynet#359]
服务中建立个mysql的链接   专门写数据的  没断开  时间久了 socket: error on  id 的错误  就断开链接

**Comment by cloudwu** [comment]
说明写数据的时候发现链接断开了. 你要查为什么断开.

**Comment by yingnierxiao** [comment]
应该是时间到达mysql的时间  链接被主动关闭了   当是mysql驱动内没有处理这块   如果写个检查链接状态的或者断线重连的机制比较好点

**Comment by cloudwu** [comment]
socket channel 会在下次发起请求时重连.

**Comment by fztcjjl** [comment]
这个问题我遇到过，重连的时候，mysql连接的一些选项要重新设置一下

**Comment by cloudwu** [comment]
可以加一个接口把要执行的指令注册到 socket channel 的 auth 流程中去. 我不用 mysql, 你们谁用谁加一下, 提个 pr .

**Comment by cloudwu** [comment]
建议在创建的时候允许传一个 on_connect 的回调. https://github.com/cloudwu/skynet/blob/master/lualib/mysql.lua#L493

然后在这里 https://github.com/cloudwu/skynet/blob/master/lualib/mysql.lua#L493 检查有回调就在 auth 的最后一步调用一下， 这样就可以再重连后正常工作。

@fztcjjl  来做一下？

**Comment by yingnierxiao** [comment]
问题似乎不是这样的   有读得那分部链接没出过问题   就是写的时候加了队列才出问题的 ，问题应该是这样的关闭socket的时候出现了临界，有几率出现的  如果断开还没重新链接的时候写入就出问题了，这个时候队列里面可能获取到的是断开前的fd

**Comment by fztcjjl** [comment]
已提交pr

**Comment by cloudwu** [comment]
@yingnierxiao 没有得到回应的请求是会抛异常的。

**Comment by yingnierxiao** [comment]
so[1]	89  --close_channel_socket 打印了
[:0000000f] socket: error on 89   --mysqlcenter.lua 这个服务里面的
[:0000000f] lua call [0 to :f : 0 msgsz = 24] error : ./libdev/lualib/skynet.lua:506: ./libdev/lualib/skynet.lua:156: [Error: socket]
stack traceback:
	[C]: in function 'assert'
	./libdev/lualib/skynet/queue.lua:29: in upvalue 'lock'
	./cok/service/mysqlcenter.lua:195: in upvalue 'func'
	./libdev/lualib/skynet.lua:450: in upvalue 'f'
	./libdev/lualib/skynet.lua:105: in function <./libdev/lualib/skynet.lua:104>
stack traceback:
	[C]: in function 'assert'
	./libdev/lualib/skynet.lua:506: in function 'skynet.dispatch_message'

**Comment by cloudwu** [comment]
似乎你在用一个老版本， error on 89 后没有具体错误信息，而现在的版本应该有的。

**Comment by yingnierxiao** [comment]
close	3
[:0000000f] lua call [0 to :f : 27 msgsz = 0] error : ./libdev/lualib/skynet.lua:518: ./libdev/lualib/skynet.lua:156: [Error: socket]
stack traceback:
	[C]: in function 'assert'
	./libdev/lualib/skynet/queue.lua:29: in upvalue 'lock'
	./cok/service/mysqlcenter.lua:196: in upvalue 'func'
	./libdev/lualib/skynet.lua:454: in upvalue 'f'
	./libdev/lualib/skynet.lua:110: in function <./libdev/lualib/skynet.lua:104>
stack traceback:
	[C]: in function 'assert'
	./libdev/lualib/skynet.lua:518: in function 'skynet.dispatch_message'
这个是更新完的版本  现在成了必定报错之前还是有几率的

**Comment by yingnierxiao** [comment]
channel:request中socket_write  写入失败了 就被关闭close_channel_socket  error(socket_error)

**Comment by cloudwu** [comment]
我更新了一个 patch 用来正确报告连接失败的错误信息。https://github.com/cloudwu/skynet/commit/935863f43455c5e902d1c62a7e9d481b3eda2cb1

没有收到对端的关闭消息是不正常的。
写失败的具体原因需要查。

**Comment by cloudwu** [comment]
另外，任何 request 的异常都需要捕获并重试。request 异常很可能是连接断开导致的，只有再次发起 request 才会重新建立连接。

**Comment by yingnierxiao** [comment]
static int
lsend(lua_State *L) {
	struct skynet_context * ctx = lua_touserdata(L, lua_upvalueindex(1));
	int id = luaL_checkinteger(L, 1);
	int sz = 0;
	void *buffer = get_buffer(L, 2, &sz);
	int err = skynet_socket_send(ctx, id, buffer, sz);
	lua_pushboolean(L, !err);
	return 1;
}
err结果为-1    已经更新patch  没新的错误报告

**Comment by cloudwu** [comment]
send 出错通常是内部已经关闭了这个 fd 。是有一定可能存在这种中间状态，通常有一个内部的 close 消息已经发出，但还没有被 lua 层处理。

但无论是何情况，socket channel 的 request 出现的  error 都需要妥善处理。

**Comment by yingnierxiao** [comment]
发送的时候fd的状态为SOCKET_TYPE_INVALID ，socket_server.c的  ctrl_cmd case K没打印出被关闭的消息出来。mysql里面的还要对socket channel的错误进行处理下才行

**Comment by cloudwu** [comment]
这得查具体问题的， 如果没有检测到断开，fd 就不会被设置为 invalid 。所以一定是某个环节有问题。

**Comment by yingnierxiao** [comment]
看了下socketchannel里面   只有主动关闭   才回会标示关闭     不然就是要等到写错误的时候才关闭    forward_message_tcp2 出来的事件没有接受处理

**Comment by cloudwu** [comment]
socketchannel 可以检测到对端断开了，see #715

**Comment by yingnierxiao** [comment]
好
