### ISSUE TITLE
客户端用C#，有时候发包给skynet后客户端会抛出ConnectionAborted的错误

### ISSUE THREAD

**Issue by LokerLi** [cloudwu/skynet#361]
我们的客户端用C#和sproto，有时候发包skynet后客户端会抛出ConnectionAborted的错误，很难重现，客户端排查后不能确认问题，skynet也没有发现相关错误日志，但能确认这个包skynet是收到的，所以不能确定是客户端问题还是服务器问题，云大有什么建议？

**Comment by cloudwu** [comment]
你可以在 socket 模块加 log， 确定是哪一行把 socket 关闭。
