### ISSUE TITLE
http/httpc.lua在发送http请求BODY为二进制数据，而非字符串时候会有BUG

### ISSUE THREAD

**Issue by cpejlgc** [cloudwu/skynet#365]
```
if content then
    local data = string.format("%s %s HTTP/1.1\r\n%scontent-length:%d\r\n\r\n", method, url, header_content, #content)
    write(data)
    write(content)
else
    local request_header = string.format("%s %s HTTP/1.1\r\n%scontent-length:0\r\n\r\n", method, url, header_content)
    write(request_header)
```

云大，很抱歉，我不太会用markdown编辑代码，上面是我修改的request函数的部分代码

**Comment by cloudwu** [comment]
fixed.

ps. 你的编辑框上面有 `Styling with Markdown is supported` 可点。

**Comment by peimin** [comment]
@cpejlgc  

md 语法很简单的  代码你 ```编程语言名称  ```即可

![qq 20151028152137](https://cloud.githubusercontent.com/assets/5111673/10781998/9cce3636-7d87-11e5-82ac-ede22c42b9ea.png)

**Comment by sishui** [comment]
许多md编辑器都可以选中代码，点菜单上的相应选项，就可以生成md语法，不需要自己会

**Comment by cpejlgc** [comment]
@peimin 谢谢，有时间会学习一下。
