### ISSUE TITLE
自己实现了一个websocketnetpack, 出现服务器异常core dump!!! 

### ISSUE THREAD

**Issue by sctangqiang** [cloudwu/skynet#367]
我写了一个新的netpack模块 websocketnetpack， 我希望通过websocketnetpack, gateserver可以将收到的包按websocket解析， 还写了一个wsgateserver（在gateserver基础上做了调整，记录每个socket是否已经通过websocket握手的状态， 同时将包给websocketnetpack解析时会告诉websocketnetpack是否已经握手成功）, 当运行起来以后， 在解析webscoket帧包时，如果需要解析两个以上原始包才能拼成一个websocket帧包时服务器就会core dump, 原因有时是double free() , 有时是invalid next value
求解决啊！！！！！！！！！！！！！！！！！！！！！！！

急需解决啊， 联系方式： qq469790883
////////////////////////////////////////////////////////////////////////lua-websocketnetpack.c/////////////////////////////////////////////////
#include "skynet_malloc.h"
#include "skynet_socket.h"

#include <lua.h>
#include <lauxlib.h>

#include <assert.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <arpa/inet.h>
#include <stdio.h>

#define QUEUESIZE 1024
#define HASHSIZE 4096
#define SMALLSTRING 2048
#define HEADERSIZE 512
#define WEBSOCKET_HEADER_LEN  2
#define WEBSOCKET_MASK_LEN    4

#define TYPE_DATA 1
#define TYPE_MORE 2
#define TYPE_ERROR 3
#define TYPE_OPEN 4
#define TYPE_CLOSE 5
#define TYPE_WARNING 6

struct netpack {
	int id;
	int size;
	void * buffer;
};

struct uncomplete {
	struct netpack pack;
	struct uncomplete * next;
	int read;
	int header_size;
	uint8_t header[HEADERSIZE];
};

struct queue {
	int cap;
	int head;
	int tail;
	struct uncomplete * hash[HASHSIZE];
	struct netpack queue[QUEUESIZE];
};

static void
clear_list(struct uncomplete * uc) {
	while (uc) {
		skynet_free(uc->pack.buffer);
		void * tmp = uc;
		uc = uc->next;
		skynet_free(tmp);
	}
}

static int
lclear(lua_State *L) {
	struct queue * q = lua_touserdata(L, 1);
	if (q == NULL) {
		return 0;
	}
	int i;
	for (i=0;i<HASHSIZE;i++) {
		clear_list(q->hash[i]);
		q->hash[i] = NULL;
	}
	if (q->head > q->tail) {
		q->tail += q->cap;
	}
	for (i=q->head;i<q->tail;i++) {
		struct netpack *np = &q->queue[i % q->cap];
		skynet_free(np->buffer);
	}
	q->head = q->tail = 0;

	return 0;
}

static inline int
hash_fd(int fd) {
	int a = fd >> 24;
	int b = fd >> 12;
	int c = fd;
	return (int)(((uint32_t)(a + b + c)) % HASHSIZE);
}

static struct uncomplete *
find_uncomplete(struct queue *q, int fd) {
	if (q == NULL)
		return NULL;
	int h = hash_fd(fd);
	struct uncomplete * uc = q->hash[h];
	if (uc == NULL)
		return NULL;
	if (uc->pack.id == fd) {
		q->hash[h] = uc->next;
		return uc;
	}
	struct uncomplete * last = uc;
	while (last->next) {
		uc = last->next;
		if (uc->pack.id == fd) {
			last->next = uc->next;
			return uc;
		}
		last = uc;
	}
	return NULL;
}

static struct queue *
get_queue(lua_State *L) {
	struct queue *q = lua_touserdata(L,1);
	if (q == NULL) {
		q = lua_newuserdata(L, sizeof(struct queue));
		q->cap = QUEUESIZE;
		q->head = 0;
		q->tail = 0;
		int i;
		for (i=0;i<HASHSIZE;i++) {
			q->hash[i] = NULL;
		}
		lua_replace(L, 1);
	}
	return q;
}

static void
expand_queue(lua_State *L, struct queue *q) {
	struct queue *nq = lua_newuserdata(L, sizeof(struct queue) + q->cap * sizeof(struct netpack));
	nq->cap = q->cap + QUEUESIZE;
	nq->head = 0;
	nq->tail = q->cap;
	memcpy(nq->hash, q->hash, sizeof(nq->hash));
	memset(q->hash, 0, sizeof(q->hash));
	int i;
	for (i=0;i<q->cap;i++) {
		int idx = (q->head + i) % q->cap;
		nq->queue[i] = q->queue[idx];
	}
	q->head = q->tail = 0;
	lua_replace(L,1);
}

static void
push_data(lua_State *L, int fd, void *buffer, int size, int clone) {
	if (clone) {
		void * tmp = skynet_malloc(size);
		memcpy(tmp, buffer, size);
		buffer = tmp;
	}
	struct queue *q = get_queue(L);
	struct netpack *np = &q->queue[q->tail];
	if (++q->tail >= q->cap)
		q->tail -= q->cap;
	np->id = fd;
	np->buffer = buffer;
	np->size = size;
	if (q->head == q->tail) {
		expand_queue(L, q);
	}
}

static struct uncomplete *
save_uncomplete(lua_State *L, int fd) {
	struct queue *q = get_queue(L);
	int h = hash_fd(fd);
	struct uncomplete * uc = skynet_malloc(sizeof(struct uncomplete));
	memset(uc, 0, sizeof(*uc));
	uc->next = q->hash[h];
	uc->pack.id = fd;
	q->hash[h] = uc;

	return uc;
}

static uint64_t ntoh64(uint64_t host)
{
    uint64_t ret = 0;
    uint32_t high, low;
    low = host & 0xFFFFFFFF;
    high = (host >> 32) & 0xFFFFFFFF;
    low = ntohl(low);
    high = ntohl(high);
    ret = low;
    ret <<= 32;
    ret |= high;
    return ret;
}
/*
* @return -1表示包头长不够 -2表示包前两个字节无效逻辑需要扔掉
*/
static inline int
read_size(uint8_t * buffer, int size, int* pack_head_length) {
	
	if (size < 2)
	{
		return -1;
	}
	
	char fin = (buffer[0] >> 7) & 0x1;
    char rsv1 = (buffer[0] >> 6) & 0x1;
    char rsv2 = (buffer[0] >> 5) & 0x1;
    char rsv3 = (buffer[0] >> 4) & 0x1;
    char opcode = buffer[0] & 0xf;
    char mask = (buffer[1] >> 7) & 0x1;

    if (0x0 != rsv1 || 0x0 != rsv2 || 0x0 != rsv3)
    {
        return -2;
    }

    int offset = 0;
	int pack_size = 0;
    //0-125
    char length = buffer[1] & 0x7f;
    offset += WEBSOCKET_HEADER_LEN;
    //126
    if (length < 0x7E)
    {
        pack_size = length;
    }
    //Short
    else if (0x7E == length)
    {
		if (size < WEBSOCKET_HEADER_LEN + sizeof(short))
		{
			return -1;
		}
        pack_size = ntohs(*((uint16_t *) (buffer+WEBSOCKET_HEADER_LEN)));
        offset += sizeof(short);
    }
    else
    {
		if (size < WEBSOCKET_HEADER_LEN + sizeof(int64_t))
		{
			return -1;
		}
        pack_size = ntoh64(*((uint64_t *) (buffer+WEBSOCKET_HEADER_LEN)));
        offset += sizeof(int64_t);
    }
	
	
    if (mask)
    {
        char masks[WEBSOCKET_MASK_LEN];
        memcpy(masks, (buffer + offset), WEBSOCKET_MASK_LEN);
        offset += WEBSOCKET_MASK_LEN;
        if (pack_size)
        {
            int i;
            for (i = 0; i < pack_size; i++)
            {
                buffer[i + offset] ^= masks[i % WEBSOCKET_MASK_LEN];
            }
        }
    }

	*pack_head_length = offset;

	return pack_size;
}

static int websocket_strnpos(char *haystack, uint32_t haystack_length, char *needle, uint32_t needle_length)
{
    assert(needle_length > 0);
    uint32_t i;

    for (i = 0; i < (int) (haystack_length - needle_length + 1); i++)
    {
        if ((haystack[0] == needle[0]) && (0 == memcmp(haystack, needle, needle_length)))
        {
            return i;
        }
        haystack++;
    }

    return -1;
}
/*
* @param  buffer   数据buffer
* @param  size     数据buffer的大小
* @return  -1表示解析失败， >0表示解析成功返回header的长度
*/
static int get_http_header(uint8_t* buffer, int size)
{
	int n = websocket_strnpos((char*)buffer, size, "\r\n\r\n", 4);
	if (n < 0)
	{
		return n;
	}
	
	return (n+4);
}
static void
push_more(lua_State *L, int fd, uint8_t *buffer, int size, int wsocket_handeshake) {

	int pack_size = 0;
	int pack_head_length = 0;
	if (wsocket_handeshake)
	{
		//认为socket初次建立连接读取握手协议
		pack_size = get_http_header(buffer, size);			
	}
	else
	{
		//读取帧大小
		while ((pack_size = read_size(buffer, size, &pack_head_length)) == -2)
		{
			buffer += WEBSOCKET_HEADER_LEN;
			size -= WEBSOCKET_HEADER_LEN;
		}
	}
	
	if (pack_size == -1)
	{			 
		struct uncomplete * uc = save_uncomplete(L, fd);
		uc->read = -1;
		uc->header_size = size;
		memcpy(uc->header, buffer, size);
		return;			
	}	

	buffer += pack_head_length;
	size -= pack_head_length;

	if (size < pack_size && !wsocket_handeshake) {
		struct uncomplete * uc = save_uncomplete(L, fd);
		uc->read = size;
		uc->pack.size = pack_size;
		uc->pack.buffer = skynet_malloc(pack_size);
		memcpy(uc->pack.buffer, buffer, size);
		return;
	}
	push_data(L, fd, buffer, pack_size, 1);

	buffer += pack_size;
	size -= pack_size;
	if (size > 0) {
		push_more(L, fd, buffer, size, wsocket_handeshake);
	}
}

static void
close_uncomplete(lua_State *L, int fd) {
	struct queue *q = lua_touserdata(L,1);
	struct uncomplete * uc = find_uncomplete(q, fd);
	if (uc) {
		skynet_free(uc->pack.buffer);
		skynet_free(uc);
	}
}

static int
filter_data_(lua_State *L, int fd, uint8_t * buffer, int size, int wsocket_handeshake) {
	struct queue *q = lua_touserdata(L,1);
	struct uncomplete * uc = find_uncomplete(q, fd);
	if (uc) {
		// fill uncomplete
		if (uc->read < 0) {
			// read size
			int pack_size = 0;
			int pack_head_length = 0;
			int copy_size = uc->header_size + size > HEADERSIZE ? (HEADERSIZE - uc->header_size) : size;
			memcpy(uc->header+uc->header_size, buffer, copy_size);
			uc->header_size += copy_size;

			buffer -= copy_size;
			size -= copy_size;
			
			if (wsocket_handeshake)
			{
				//认为socket初次建立连接读取握手协议
				pack_size = get_http_header(uc->header, uc->header_size);			
			}
			else
			{
				//读取帧大小
				while ((pack_size = read_size(uc->header, uc->header_size, &pack_head_length)) == -2)
				{
					uc->header_size -= WEBSOCKET_HEADER_LEN;
					memmove(uc->header, uc->header + WEBSOCKET_HEADER_LEN, uc->header_size);
				}
			}			
			if (pack_size == -1)
			{			
				int h = hash_fd(fd);
				uc->next = q->hash[h];
				q->hash[h] = uc;
				return 1;			
			}
			//去掉帧数据的包头
			if (!wsocket_handeshake)
			{
					uc->header_size -= pack_head_length;
					memmove(uc->header, uc->header + pack_head_length, uc->header_size);				
			}
			
			//取得包头长度以后开始生成新包
			uc->pack.buffer = skynet_malloc(pack_size);
			uc->pack.size = pack_size;
			uc->read = uc->header_size < pack_size ? uc->header_size : pack_size;
			memcpy(uc->pack.buffer, uc->header, uc->read);
			uc->header_size -= uc->read;
			if (uc->header_size > 0)
			{
				memmove(uc->header, uc->header + uc->read, uc->header_size);								
			}
			else
			{
				uc->header_size = 0;
			}
		}
		int need = uc->pack.size - uc->read;
		if (size < need) {
			memcpy(uc->pack.buffer + uc->read, buffer, size);
			uc->read += size;
			int h = hash_fd(fd);
			uc->next = q->hash[h];
			q->hash[h] = uc;
			return 1;
		}
		if (need != 0)
		{
			memcpy(uc->pack.buffer + uc->read, buffer, need);			
		}
		
		buffer += need;
		size -= need;
		
		if (size == 0) {
			lua_pushvalue(L, lua_upvalueindex(TYPE_DATA));
			lua_pushinteger(L, fd);
			lua_pushlightuserdata(L, uc->pack.buffer);
			lua_pushinteger(L, uc->pack.size);
			skynet_free(uc);
			return 5;
		}
		// more data
		push_data(L, fd, uc->pack.buffer, uc->pack.size, 0);
		skynet_free(uc);
		push_more(L, fd, buffer, size, wsocket_handeshake);
		lua_pushvalue(L, lua_upvalueindex(TYPE_MORE));
		return 2;
	} else {
		int pack_size = 0;
		int pack_head_length = 0;
		if (wsocket_handeshake)
		{
			//认为socket初次建立连接读取握手协议
			pack_size = get_http_header(buffer, size);			
		}
		else
		{
			//读取帧大小
			while ((pack_size = read_size(buffer, size, &pack_head_length)) == -2)
			{
				buffer += WEBSOCKET_HEADER_LEN;
				size -= WEBSOCKET_HEADER_LEN;
			}
		}
		
		if (pack_size == -1)
		{		
			struct uncomplete * uc = save_uncomplete(L, fd);
			uc->read = -1;
			uc->header_size += size;
			memcpy(uc->header, buffer, size);
			return 1;			
		}
		buffer+=pack_head_length;
		size-=pack_head_length;
		
		if (size < pack_size && !wsocket_handeshake) {
			struct uncomplete * uc = save_uncomplete(L, fd);
			uc->read = size;
			uc->pack.size = pack_size;
			uc->pack.buffer = skynet_malloc(pack_size);
			memcpy(uc->pack.buffer, buffer, size);
			return 1;
		}
		if (size == pack_size) {
			// just one package
			lua_pushvalue(L, lua_upvalueindex(TYPE_DATA));
			lua_pushinteger(L, fd);
			void * result = skynet_malloc(pack_size);
			memcpy(result, buffer, size);
			lua_pushlightuserdata(L, result);
			lua_pushinteger(L, size);
			return 5;
		}
		// more data
		push_data(L, fd, buffer, pack_size, 1);
		buffer += pack_size;
		size -= pack_size;
		push_more(L, fd, buffer, size, wsocket_handeshake);
		lua_pushvalue(L, lua_upvalueindex(TYPE_MORE));
		return 2;
	}
}

static inline int
filter_data(lua_State *L, int fd, uint8_t * buffer, int size, int wsocket_handeshake) {
	int ret = filter_data_(L, fd, buffer, size, wsocket_handeshake);
	// buffer is the data of socket message, it malloc at socket_server.c : function forward_message .
	// it should be free before return,
	//skynet_free(buffer);
	return ret;
}

static void
pushstring(lua_State *L, const char * msg, int size) {
	if (msg) {
		lua_pushlstring(L, msg, size);
	} else {
		lua_pushliteral(L, "");
	}
}

/*
	userdata queue
	lightuserdata msg
	integer size
	return
		userdata queue
		integer type
		integer fd
		string msg | lightuserdata/integer
 */
static int
lfilter(lua_State *L) {
	struct skynet_socket_message *message = lua_touserdata(L,2);
	int size = luaL_checkinteger(L,3);
	int wsocket_handeshake = luaL_checkinteger(L,4);
	char * buffer = message->buffer;
	if (buffer == NULL) {
		buffer = (char *)(message+1);
		size -= sizeof(*message);
	} else {
		size = -1;
	}

	lua_settop(L, 1);

	switch(message->type) {
	case SKYNET_SOCKET_TYPE_DATA:
		// ignore listen id (message->id)
		assert(size == -1);	// never padding string
		return filter_data(L, message->id, (uint8_t *)buffer, message->ud, wsocket_handeshake);
	case SKYNET_SOCKET_TYPE_CONNECT:
		// ignore listen fd connect
		return 1;
	case SKYNET_SOCKET_TYPE_CLOSE:
		// no more data in fd (message->id)
		close_uncomplete(L, message->id);
		lua_pushvalue(L, lua_upvalueindex(TYPE_CLOSE));
		lua_pushinteger(L, message->id);
		return 3;
	case SKYNET_SOCKET_TYPE_ACCEPT:
		lua_pushvalue(L, lua_upvalueindex(TYPE_OPEN));
		// ignore listen id (message->id);
		lua_pushinteger(L, message->ud);
		pushstring(L, buffer, size);
		return 4;
	case SKYNET_SOCKET_TYPE_ERROR:
		// no more data in fd (message->id)
		close_uncomplete(L, message->id);
		lua_pushvalue(L, lua_upvalueindex(TYPE_ERROR));
		lua_pushinteger(L, message->id);
		pushstring(L, buffer, size);
		return 4;
	case SKYNET_SOCKET_TYPE_WARNING:
		lua_pushvalue(L, lua_upvalueindex(TYPE_WARNING));
		lua_pushinteger(L, message->id);
		lua_pushinteger(L, message->ud);
		return 4;
	default:
		// never get here
		return 1;
	}
}

/*
	userdata queue
	return
		integer fd
		lightuserdata msg
		integer size
 */
static int
lpop(lua_State *L) {
	struct queue * q = lua_touserdata(L, 1);
	if (q == NULL || q->head == q->tail)
		return 0;
	struct netpack *np = &q->queue[q->head];
	if (++q->head >= q->cap) {
		q->head = 0;
	}
	lua_pushinteger(L, np->id);
	lua_pushlightuserdata(L, np->buffer);
	lua_pushinteger(L, np->size);

	return 3;
}

/*
	string msg | lightuserdata/integer

	lightuserdata/integer
 */

static const char *
tolstring(lua_State *L, size_t *sz, int index) {
	const char * ptr;
	if (lua_isuserdata(L,index)) {
		ptr = (const char *)lua_touserdata(L,index);
		*sz = (size_t)luaL_checkinteger(L, index+1);
	} else {
		ptr = luaL_checklstring(L, index, sz);
	}
	return ptr;
}

#define FRAME_SET_FIN(BYTE) (((BYTE) & 0x01) << 7)
#define FRAME_SET_OPCODE(BYTE) ((BYTE) & 0x0F)
#define FRAME_SET_MASK(BYTE) (((BYTE) & 0x01) << 7)
#define FRAME_SET_LENGTH(X64, IDX) (unsigned char)(((X64) >> ((IDX)*8)) & 0xFF)

static int
lpack(lua_State *L) {
	size_t len;
	const char * ptr = tolstring(L, &len, 1);

	int pos = 0;
    char frame_header[16];

    frame_header[pos++] = FRAME_SET_FIN(1) | FRAME_SET_OPCODE(4);
    if (len < 126)
    {
        frame_header[pos++] = FRAME_SET_MASK(0) | FRAME_SET_LENGTH(len, 0);
    }
    else
    {
        if (len < 65536)
        {
            frame_header[pos++] = FRAME_SET_MASK(0) | 126;
        }
        else
        {
            frame_header[pos++] = FRAME_SET_MASK(0) | 127;
            frame_header[pos++] = FRAME_SET_LENGTH(len, 7);
            frame_header[pos++] = FRAME_SET_LENGTH(len, 6);
            frame_header[pos++] = FRAME_SET_LENGTH(len, 5);
            frame_header[pos++] = FRAME_SET_LENGTH(len, 4);
            frame_header[pos++] = FRAME_SET_LENGTH(len, 3);
            frame_header[pos++] = FRAME_SET_LENGTH(len, 2);
        }
        frame_header[pos++] = FRAME_SET_LENGTH(len, 1);
        frame_header[pos++] = FRAME_SET_LENGTH(len, 0);
    }
		
	uint8_t * buffer = skynet_malloc(len + pos);
	memcpy(buffer, frame_header, pos);
	memcpy(buffer+pos, ptr, len);

	lua_pushlightuserdata(L, buffer);
	lua_pushinteger(L, len + pos);

	return 2;
}

static int
ltostring(lua_State *L) {
	void * ptr = lua_touserdata(L, 1);
	int size = luaL_checkinteger(L, 2);
	if (ptr == NULL) {
		lua_pushliteral(L, "");
	} else {
		lua_pushlstring(L, (const char *)ptr, size);
		skynet_free(ptr);
	}
	return 1;
}

int
luaopen_websocketnetpack(lua_State *L) {
	luaL_checkversion(L);
    luaL_Reg l[] = {
        { "pop", lpop },
        { "pack", lpack },
        { "clear", lclear },
        { "tostring", ltostring },
        { NULL, NULL },
    };
    luaL_newlib(L,l);

    // the order is same with macros : TYPE_* (defined top)
    lua_pushliteral(L, "data");
    lua_pushliteral(L, "more");
    lua_pushliteral(L, "error");
    lua_pushliteral(L, "open");
    lua_pushliteral(L, "close");
    lua_pushliteral(L, "warning");
    lua_pushcclosure(L, lfilter, 6);
    lua_setfield(L, -2, "filter");
    return 1;
}	

////////////////////////////////////////////////////////////////////////wsgateserver.lua/////////////////////////////////////////////////
local skynet = require "skynet"
local netpack = require "websocketnetpack"
local socketdriver = require "socketdriver"
local httpd = require "http.httpd"
local urllib = require "http.url"
local string = require "string"
local crypt = require "crypt"
local gateserver = {}

local socket	-- listen socket
local queue		-- message queue
local maxclient	-- max client
local client_number = 0
local CMD = setmetatable({}, { __gc = function() netpack.clear(queue) end })
local nodelay = false
local connection = {}  --{ isconnect, iswebsocket_handeshake (default 1) }

-------------websocket 握手时解析http请求头--------------------------------
local function parse_httpheader(http_str)
    local header = {}
    local i = 0
    local start = 0
    local str
    i = string.find(http_str, "\r\n", i+1)
    while true  and i ~= nil do
       start = i + 2
       i = string.find(http_str, "\r\n", start)
       if i ~= nil then
            str = string.sub(http_str, start, i-1)
            local key, value = string.match(str, "([%a-]+)%s*: (.*)")
            if key ~= nil and value ~= nil then
                print(":"..value..":"..key..":")
            end
	        if key ~= nil then
                header[key:lower()] = value
            end
       end
    end

	return header
end

------------------websocket 握手时使用的相关接口  begin----------------------
local function getwebsocket_response(key, protocol)
    protocol = protocol or ""
    if protocol ~= "" then
        protocol = protocol .. "\r\n"
    end

    local accept = crypt.base64encode(crypt.sha1(key .. "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"))
    return string.format("HTTP/1.1 101 Switching Protocols\r\n" ..
                        "Upgrade: websocket\r\n" ..
                        "Connection: Upgrade\r\n" ..
                        "Sec-WebSocket-Accept: %s\r\n" ..
                        "%s\r\n", accept, protocol)
    
end

local function checkwebsocket_valid(header, check_origin, check_origin_ok)
    -- Upgrade header should be present and should be equal to WebSocket
    if not header["upgrade"] or header["upgrade"]:lower() ~= "websocket" then
        return 400, "Can \"Upgrade\" only to \"WebSocket\"."
    end

    -- Connection header should be upgrade. Some proxy servers/load balancers
    -- might mess with it.
    if not header["connection"] or not header["connection"]:lower():find("upgrade", 1,true) then
        return 400, "\"Connection\" must be \"Upgrade\"."
    end

    -- Handle WebSocket Origin naming convention differences
    -- The difference between version 8 and 13 is that in 8 the
    -- client sends a "Sec-Websocket-Origin" header and in 13 it's
    -- simply "Origin".
    local origin = header["origin"] or header["sec-websocket-origin"]
    if origin and check_origin and not check_origin_ok(origin, header["host"]) then
        return 403, "Cross origin websockets not allowed"
    end

    if not header["sec-websocket-version"] or header["sec-websocket-version"] ~= "13" then
        return 400, "HTTP/1.1 Upgrade Required\r\nSec-WebSocket-Version: 13\r\n\r\n"
    end

    local key = header["sec-websocket-key"]
    if not key then
        return 400, "\"Sec-WebSocket-Key\" must not be  nil."
    end

    local protocol = header["sec-websocket-protocol"] 
    if protocol then
        --local i = protocol:find(",", 1, true)
        --protocol = "Sec-WebSocket-Protocol: " .. protocol:sub(1, i or i-1)
    end

    return nil, getwebsocket_response(key, protocol)

end

local function writefunc(fd)
	return function(content)
		local ok = socketdriver.send(fd, content)
		if not ok then
			error(socket_error)
		end
	end
end
------------------websocket 握手时使用的相关接口  end----------------------

function gateserver.openclient(fd)
	if connection[fd] ~= nil  and  connection[fd].isconnect then
		socketdriver.start(fd)
	end
end

function gateserver.closeclient(fd)
	local c = connection[fd]
	if c then
		connection[fd] = nil
		socketdriver.close(fd)
	end
end

function gateserver.checkwebsocket(fd, header)

    local code, result = checkwebsocket_valid(header, nil, nil)
	print (code, result)
    if code then
		httpd.write_response(writefunc(fd), code, result)
        gateserver.closeclient(fd)
		return false
    else
        socketdriver.send(fd, result)
		return true
    end
	return true
end

function gateserver.start(handler)
	assert(handler.message)
	assert(handler.connect)

	function CMD.open( source, conf )
		assert(not socket)
		local address = conf.address or "0.0.0.0"
		local port = assert(conf.port)
		maxclient = conf.maxclient or 1024
		nodelay = conf.nodelay
		skynet.error(string.format("Listen on %s:%d", address, port))
		socket = socketdriver.listen(address, port)
		socketdriver.start(socket)
		if handler.open then
			return handler.open(source, conf)
		end
	end

	function CMD.close()
		assert(socket)
		socketdriver.close(socket)
	end

	local MSG = {}

	local function dispatch_msg(fd, msg, sz)
		if connection[fd] ~= nil and connection[fd].isconnect then
			if connection[fd].iswebsocket_handeshake == 1 then
				--websocket 握手回包处理
				local str_msg = netpack.tostring(msg, sz)
                print ("str_msg"..str_msg)
				local header = parse_httpheader(str_msg)
				if (gateserver.checkwebsocket(fd, header)) then
					connection[fd].iswebsocket_handeshake = 0
					print("websocket soucess")
				end								
			else
				print("====size:"..sz)
				--local str_msg = netpack.tostring(msg, sz)
                --print ("str_msg"..str_msg)
				handler.message(fd, msg, sz)
			end
		else
			print("Drop message from fd(%d)", fd)
			skynet.error(string.format("Drop message from fd (%d) : %s", fd, netpack.tostring(msg,sz)))
		end
	end

	MSG.data = dispatch_msg

	local function dispatch_queue()
		local fd, msg, sz = netpack.pop(queue)
		if fd then
			-- may dispatch even the handler.message blocked
			-- If the handler.message never block, the queue should be empty, so only fork once and then exit.
			skynet.fork(dispatch_queue)
			dispatch_msg(fd, msg, sz)

			for fd, msg, sz in netpack.pop, queue do
				dispatch_msg(fd, msg, sz)
			end
		end
	end

	MSG.more = dispatch_queue

	function MSG.open(fd, msg)
		if client_number >= maxclient then
			socketdriver.close(fd)
			return
		end
		if nodelay then
			socketdriver.nodelay(fd)
		end
		connection[fd] = {}
		connection[fd].isconnect = true
		connection[fd].iswebsocket_handeshake = 1
		client_number = client_number + 1
		handler.connect(fd, msg)
	end

	local function close_fd(fd)
		local c = connection[fd]
		if c ~= nil then
			connection[fd] = nil
			client_number = client_number - 1
		end
	end

	function MSG.close(fd)
		if fd ~= socket then
			if handler.disconnect then
				handler.disconnect(fd)
			end
			close_fd(fd)
		else
			socket = nil
		end
	end

	function MSG.error(fd, msg)
		if fd == socket then
			socketdriver.close(fd)
			skynet.error(msg)
		else
			if handler.error then
				handler.error(fd, msg)
			end
			close_fd(fd)
		end
	end

	function MSG.warning(fd, size)
		if handler.warning then
			handler.warning(fd, size)
		end
	end

	skynet.register_protocol {
		name = "socket",
		id = skynet.PTYPE_SOCKET,	-- PTYPE_SOCKET = 6
		unpack = function ( msg, sz )
            local _, fd = socketdriver.unpack(msg, sz)
			if (connection[fd] == nil ) then
                    print ("---1")
					return netpack.filter( queue, msg, sz, 1)
			elseif connection[fd].isconnect then
                    print ("---2")
					return netpack.filter( queue, msg, sz, connection[fd].iswebsocket_handeshake)
			end

                    print ("---3")
			return netpack.filter( queue, msg, sz, 1)
		end,
		dispatch = function (_, _, q, type, ...)
			queue = q
			if type then
				MSG[type](...)
			end
		end
	}

     skynet.start(function()
     skynet.dispatch("lua", function (_, address, cmd, ...)
     local f = CMD[cmd]
          if f then
                       skynet.ret(skynet.pack(f(address, ...)))
          else
                        skynet.ret(skynet.pack(handler.command(cmd, address, ...)))
             end
        end)
    end)
end

                                          
return gateserver

**Comment by cloudwu** [comment]
拜托先学点 markdown 语法 :(
另外学会用 github 至少 gist 啊.

调试这种事情还是得自己来.

**Comment by hanxi** [comment]
这代码好长啊。还不如贴个github地址呢。

如果是自己游戏逻辑里面定了协议的话，解析websocket没必要考虑粘包问题，让客户端每发的一个websocket包都是一个协议就ok了。

还有一点，你真要考虑粘包的话，没必要把每个buffer拷贝出来，直接弄个bufferlist存buffer的地址就行了，解析完成后再free掉bufferlist中前面解析完的部分。

**Comment by sctangqiang** [comment]
好的， 我考虑下， 我的linux下github提交不了（git client有问题）代码地址如下
https://code.csdn.net/snippets/1273962  lua-websocketnetpack.c
https://code.csdn.net/snippets/1273963  wsgateserver.lua

**Comment by sctangqiang** [comment]
filter_data(lua_State *L, int fd, uint8_t * buffer, int size, int wsocket_handeshake) {
	int ret = filter_data_(L, fd, buffer, size, wsocket_handeshake);
	// buffer is the data of socket message, it malloc at socket_server.c : function forward_message .
	// it should be free before return,
	//skynet_free(buffer);    我把这个代码注释了能输出几个消息来， 但是只要我的客户端一断开连接就会core dump
	return ret;
}

**Comment by sctangqiang** [comment]
filter_data(lua_State *L, int fd, uint8_t * buffer, int size, int wsocket_handeshake) {
int ret = filter_data_(L, fd, buffer, size, wsocket_handeshake);
// buffer is the data of socket message, it malloc at socket_server.c : function forward_message .
// it should be free before return,
skynet_free(buffer);        这行注释当开始处理websocket帧包的时候，只要netpack收到的第一个包不够一个完整帧包时， 在这个地方毕core dump 
return ret;
}

core信息如下：
*** glibc detected *** ./skynet: double free or corruption (!prev): 0x00007f2264000a30 ***
======= Backtrace: =========
/lib64/libc.so.6[0x37f8c75366]
/lib64/libc.so.6[0x37f8c77e93]
./luaclib/websocketnetpack.so(+0x1954)[0x7f22719e7954]
./skynet[0x411f00]
./skynet[0x41d2ce]
./skynet[0x41220c]
./skynet[0x41130b]
./skynet[0x41138f]
./skynet(lua_pcallk+0x72)[0x40ef02]
./skynet[0x4250b0]
./skynet[0x411f00]
./skynet[0x41d33b]
./skynet[0x41220c]
./skynet[0x41130b]
./skynet[0x41138f]
./skynet(lua_pcallk+0x72)[0x40ef02]
./luaclib/skynet.so(+0x1ad3)[0x7f2278684ad3]
./skynet[0x4085e6]
./skynet(skynet_context_message_dispatch+0x7f)[0x4088ff]
./skynet[0x4095dd]
/lib64/libpthread.so.0[0x37f9007851]
/lib64/libc.so.6(clone+0x6d)[0x37f8ce767d]
