### ISSUE TITLE
sproto 导致奔溃

### ISSUE THREAD

**Issue by yingnierxiao** [cloudwu/skynet#368]
Assertion failed: (sz <= size-SIZEOF_LENGTH), function encode_object, file lualib-src/sproto/sproto.c, line 680.

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/blob/master/lualib-src/sproto/sproto.c#L680

callback 函数里 buffer 溢出了, 你可以输出 size 和 sz 看看为什么.

**Comment by cloudwu** [comment]
我看了一下, 最可能是 assert 位置不对. 你看看是不是这个问题.

**Comment by yingnierxiao** [comment]
重启后没重现了   在观察下看看
