### ISSUE TITLE
socketdriver.close无法关闭socket的问题

### ISSUE THREAD

**Issue by niuys** [cloudwu/skynet#371]
特殊情况下，客户端已经关闭，但是tcp连接仍是established状态，并且socket的write buffer已满,但是在buffer list仍有数据需要等待发送。这个时候调用socketdriver.close,会先处理剩余的需要发送的数据，并设置为halfclose状态,而write的返回值会一直是EAGIN,导致无法触发socket的close或error，必须等待tcp连接检查到自身断开，这个时间系统默认配置会比较久。我们现在的处理办法是逻辑不依赖于socketdriver.close是否触发close。这种情况是否要加一个接口忽略剩余数据的发送结果，或者加一个halfclose状态的timer，或者有什么其他的好办法？

**Comment by cloudwu** [comment]
我加一个 shutdown 好了.

**Comment by niuys** [comment]
好的，这样和posix 接口相似了。

**Comment by cloudwu** [comment]
我已经修改了 socket.shutdown 的逻辑, 让它丢弃没有发出的数据.  麻烦 review 一下看是否解决了问题.

**Comment by niuys** [comment]
解决了问题了，我的需求只是关掉socket，数据有丢失是允许的。如果是对某种需求，建立连接之后，发送一段数据，然后立即关掉连接，既要要保证数据发送完整，又想收到close事件，考虑到这个issue开始的问题，好像调用close和shutdown都不合适，只能满足其中之一。加一个类似系统的shutdown接口的how的是否保证数据发送完的选项是否可行呢？

**Comment by cloudwu** [comment]
目前 lua 这边 socket.close 就会保证发送完；socket.shutdown 丢掉未发送的。

C 那边也有对应两个接口了。

**Comment by cloudwu** [comment]
今天 https://github.com/cloudwu/skynet/commit/6c3e969e913e2e38c112f7eaded3d497e0eaa8b0 这个在半关闭发生时增加了 shutdown 的调用。
