### ISSUE TITLE
lua-netpack.c疑问

### ISSUE THREAD

**Issue by sctangqiang** [cloudwu/skynet#378]
我看了skynet中 netpack.c和 watchdog.lua的例子， 有个疑问， netpack.c的pop返回一个lightuserdata , 但是在c层没有看到释放的地方， 请问下这个会不会内存泄露呢

**Comment by cloudwu** [comment]
* https://github.com/cloudwu/skynet/wiki/GateServer#netpack-api
* https://github.com/cloudwu/skynet/wiki/LuaAPI#%E6%B6%88%E6%81%AF%E7%9A%84%E5%BA%8F%E5%88%97%E5%8C%96
