### ISSUE TITLE
关于skynet.timeout的疑问

### ISSUE THREAD

**Issue by puXiaoyi** [cloudwu/skynet#379]
弱弱问一下，```lua skynet.timeout(ti, func) ``` 如果func想传参怎么实现？

**Comment by fztcjjl** [comment]
function timeout(ti, f, ...)
	local args = {...}
	local function run()
		f(table.unpack(args))
	end
	skynet.timeout(ti, run)
end

**Comment by cloudwu** [comment]
严格来说，应该 `table.pack(...)`
然后 `table.unpack(t,1,t.n)`

不然会丢失 nil .

**Comment by puXiaoyi** [comment]
tks
