### ISSUE TITLE
可以给skynet增加一个从地址转化成skynet.register时起的名字的方法么。不是skynet.address()

### ISSUE THREAD

**Issue by tangyiyang** [cloudwu/skynet#382]
比如 skynet.name('foo', skynet.self) , 在这个service里 skynet.name() -> 就可以得到 foo.

这样在输出日志的时候，就可以更好的看出来是哪一个service的日志了。 :D

**Comment by cloudwu** [comment]
不建议使用 skynet.register . 自己做一个名字服务 和 log 服务.

**Comment by tangyiyang** [comment]
没太理解这个 名字服务 的含义，现在都是把数字地址直接传给对应的service去做的。

什么样的场景需要名字服务呢。

参考user_log, log服务到是写的差不多了 :D

**Comment by cloudwu** [comment]
每启动一个你的服务,都给一个服务发个消息, 让它知道叫什么名字. 这就是名字服务.
你想查的时候去那里查就好了.

**Comment by tangyiyang** [comment]
get it √。thank you.
