### ISSUE TITLE
skynet http-client的功能。

### ISSUE THREAD

**Issue by tangyiyang** [cloudwu/skynet#386]
在做alipay的时候，需要给支付宝的服务端通知。
现在想的是，直接把lua-curl集成进来，但是又感觉太重量了。
有轻量一点的解决方案么。

**Comment by gitfancode** [comment]
不是有httpc.lua 么

**Comment by cloudwu** [comment]
补充一点, 用 httpc 的时候,域名先用 dns 模块解析出来, 避免卡住网络线程.  https://github.com/cloudwu/skynet/wiki/Socket#%E5%9F%9F%E5%90%8D%E6%9F%A5%E8%AF%A2

**Comment by tangyiyang** [comment]
啊咧，真的没看到这个模块。我今天白天花了1个小时已经把curl集成进来了，还写了测试代码，看来可以移除了，解决问题了，感谢。:D
