### ISSUE TITLE
关于给 skynet 加入三方插件系统。

### ISSUE THREAD

**Issue by tangyiyang** [cloudwu/skynet#389]
在项目开发的过程中，总会有一些库可以和别人共享。从简单的加密到一些复杂的service。因为skynet独立虚拟机的缘故，数据很好的被离开，所以理论上，如果遵循某种规范，应该可以写出很多复用性很高的模块，skynet有这方面的考虑么，或者说，在skynet下面，应该如何去做类似plugin的系统呢？

**Comment by tangyiyang** [comment]
使用skynet接近两个月，感觉skynet留了很多工作给开发者，当然这样的自由度是有必要的。觉得skynet是“框架的框架”。 那么如果这个框架有一个"plugin 系统规范"，应该是很好的practice？

**Comment by cloudwu** [comment]
你应该把 skynet 做 submodule 引入, 其它模块单独开列. 不要在开发时把自己的东西放在 skynet 工程目录下, 也不要修改它的 makefile .

skynet 的 config 允许你配置而外模块的路径.

**Comment by tangyiyang** [comment]
我现在是这样做的，我的lib是和skynet分开独立的。:)
我想说的是 skynet的生态圈，就像node.js有npm和npm背后庞大的生态圈一样。

**Comment by cloudwu** [comment]
你可以单独开个项目, 就好像 lua rocks 和 lua 的关系.
