### ISSUE TITLE
一个关于  yield across a C-call boundary 的问题。

### ISSUE THREAD

**Issue by tangyiyang** [cloudwu/skynet#394]
本来这个应该是和业务相关的，不应该提到这里。
问题：在skynet框架下，哪一些条件下会容易产生yield across a C-call boundary 的问题呢？能详细讲下这个C-call boundary和这个异常产生的原因么？ 嗯，因为项目比较着急，没那么时间深究。这里伸手提问，感谢。:)

以下这个错误是我在重构项目里的配置文件（项目之前的配置是直接写Lua table里require的）时产生的错误，看起来应该不是multicastd的问题，因为我revert我修改代码回去是正常的。

[:0100002d] [E], [Tue Dec  1 16:03:32 2015] [Agent] ------- ERROR START ------
[:0100002d] [E], [Tue Dec  1 16:03:32 2015] attempt to yield across a C-call boundary
[:0100002d] [E], [Tue Dec  1 16:03:32 2015] stack traceback:
	./service/agent.lua:62: in function <./service/agent.lua:59>
	[C]: in function 'profile.yield'
	../lib/skynet/lualib/skynet.lua:375: in upvalue 'yield_call'
	../lib/skynet/lualib/skynet.lua:389: in function 'skynet.call'
	../lib/skynet/lualib/skynet.lua:530: in function 'skynet.uniqueservice'
	../lib/skynet/lualib/multicast.lua:93: in local 'f'
	../lib/skynet/lualib/skynet.lua:591: in function 'skynet.init'
	../lib/skynet/lualib/multicast.lua:102: in main chunk
	[C]: in function 'require'
	./game/handler/user_handler.lua:258: in main chunk
	[C]: in function 'require'
	./game/handler/route_handler.lua:19: in function 'route_handler.ctor'
	./lualib/util/class.lua:23: in function 'route_handler.new'
	./service/agent.lua:205: in function <./service/agent.lua:197>
	[C]: in function 'xpcall'
	./service/agent.lua:262: in upvalue 'f'
	../lib/skynet/lualib/skynet.lua:110: in function <../lib/skynet/lualib/skynet.lua:104>
[:0100002d] [E], [Tue Dec  1 16:03:32 2015] [Agent] ------- ERROR END ------
[:0100002d] [E], [Tue Dec  1 16:03:32 2015] [Agent] ------- CLOSE ------
[:0100002d] Response message : "+
[:0100002d] lua call [1000008 to :100002d : 2 msgsz = 5] error : ../lib/skynet/lualib/skynet.lua:519: ../lib/skynet/lualib/skynet.lua:443: Unknown session : 2 from 1000008
stack traceback:
	[C]: in function 'assert'
	../lib/skynet/lualib/skynet.lua:519: in function 'skynet.dispatch_message'

**Comment by tangyiyang** [comment]
根据之前的经验，自己感觉应该是在某个service还没启动起来的时候就 skynet.call 出去了。:( 再去查查。

**Comment by cloudwu** [comment]
```
C (skynet framework)->lua (skynet service) -> C -> lua
```

最后这个 lua 里如果调用了 yield 就会产生。

这里 require 就是一个 C 函数.

skynet.init 就是为了避免你在 require 阶段运行阻塞代码， https://github.com/cloudwu/skynet/blob/master/lualib/skynet.lua#L588-L600
把它推迟到 skynet.start 再运行。

除非你别的地方破坏了这个行为，让  https://github.com/cloudwu/skynet/blob/master/lualib/skynet.lua#L602 不小心运行了。

**Comment by tangyiyang** [comment]
有点明白了。:D 
我大概知道从哪里去查我的问题了，感谢。

**Comment by cloudwu** [comment]
btw, 理论上实现一个 yieldable 的 require 并非不可行。在 C 里用 `lua_callk` 代替 `lua_call` 即可。

但是这里会有一个潜在的问题：如果你在一个 coroutine 里 require 一个 yield 的模块，由于 yield 了，
会导致这个模块没有 cache 到表中。这个时候另一个 coroutine 也 require 了同一个模块，会导致被多次运行。

这也是为什么几乎所有语言的模块初始化过程都主张用单线程完成，不考虑并发问题。

**Comment by tangyiyang** [comment]
:(
review了所有的code，确定没有rpc调用在require的时候被执行。
感觉上是破坏了 init_all 的行为。

**Comment by cloudwu** [comment]
你只需要在调用 `init_all` 的地方 print traceback 一下就找出来了。

**Comment by tangyiyang** [comment]
仍然没有找到问题。我写了一个测试用例，麻烦帮看下。:)

file1: test_agent.lua
```Lua
local skynet = require "skynet"

local CMD = {}

function CMD.start()
	-- !!! IMPORTANT !!!
	-- 如果加上这行代码，就会出yield across a C-call boundary.
	local mc = require "multicast"

	local config_data = skynet.call('test_sharedata', 'lua', 'query', 'test_data')
	
	return true
end

skynet.start(function()
	skynet.dispatch("lua", function(_,_, command, ...)
		local f = CMD[command]
		
		local function ret (ok, ...)
			if ok then
      			skynet.retpack (...)
      		end
		end

		ret (xpcall (f, function(err)
				skynet.error(err)
				skynet.error(debug.traceback())
			end, ...))
	end)
end)
```

file2: test_data.lua
```Lua
local test_data = {
	foo = {
		bar = "fooo",
		arr = {1, 2, 3, 4, 5},
		bool = true,
		{ t1 = 't1', 't2', 't3'},
	}
}

return test_data
```

file3:test_multicast.lua
```Lua
local skynet = require "skynet"
local mc = require "multicast"

local world_channel

local CMD = {}

function CMD.start()
	world_channel = mc.new()

	return true
end

skynet.start(function()
	skynet.dispatch("lua", function(_,_, command, ...)
		local f = CMD[command]
		
		local function ret (ok, ...)
			if ok then
      			skynet.retpack (...)
      		end
		end

		ret (xpcall (f, function(err)
				skynet.error(err)
				skynet.error(debug.traceback())
			end, ...))
	end)
end)
```

file4: test_sharedata.lua
```Lua
local skynet = require "skynet"
require "skynet.manager"
local sharedata = require "sharedata"

local CMD = {}

local function print_r(root)
    local cache = {  [root] = "." }
    local function _dump(t,space,name)
        local temp = {}
        for k,v in pairs(t) do
            local key = tostring(k)
            if cache[v] then
                table.insert(temp,"+" .. key .. " {" .. cache[v].."}")
            elseif type(v) == "table" then
                local new_key = name .. "." .. key
                cache[v] = new_key
                table.insert(temp,"+" .. key .. _dump(v,space .. (next(t,k) and "|" or " " ).. string.rep(" ",#key),new_key))
            else
                table.insert(temp,"+" .. key .. " [" .. tostring(v).."]")
            end
        end
        return table.concat(temp,"\n"..space)
    end

    print("\n------------------------------------------------------------------------\n" 
        .. _dump(root, "","")
        .. "\n------------------------------------------------------------------------")
end

function CMD.start()
	local data = require "test_data"
	print_r(data)
	sharedata.new("test_data", data)
	return true
end

function CMD.query(name)
	skynet.error('call test_sharedata, query, name = ' .. name)
	return sharedata.query(name)
end

skynet.start(function()
	skynet.register('test_sharedata')
	skynet.dispatch("lua", function(_,_, command, ...)
		local f = CMD[command]
		
		local function ret (ok, ...)
			if ok then
      			skynet.retpack (...)
      		end
		end

		ret (xpcall (f, function(err)
				skynet.error(err)
				skynet.error(debug.traceback())
			end, ...))
	end)
end)
```
file5: main.lua
```Lua
local skynet = require "skynet"
require "skynet.manager"

skynet.start(function()	

	local test_sharedata = skynet.uniqueservice('test_sharedata')
	skynet.call(test_sharedata, 'lua', 'start')
	skynet.error('test_sharedata init finished.')

	local test_multicast = skynet.uniqueservice('test_multicast')
	skynet.call(test_multicast, 'lua', 'start')
	skynet.error('test_multicast init finished.')

	local test_agent = skynet.newservice('test_agent')
	skynet.call(test_agent, 'lua', 'start')
	skynet.error('finish running test.')

end)
```

以下是出错日志：

[:01000001] LAUNCH logger 
[:01000002] LAUNCH snlua bootstrap
[:01000003] LAUNCH snlua launcher
[:01000004] LAUNCH snlua cmaster
[:01000004] master listen socket 0.0.0.0:22013
[:01000005] LAUNCH snlua cslave
[:01000005] slave connect to master 127.0.0.1:22013
[:01000006] LAUNCH harbor 1 16777221
[:01000004] connect from 127.0.0.1:50465 4
[:01000004] Harbor 1 (fd=4) report 127.0.0.1:22526
[:01000005] Waiting for 0 harbors
[:01000005] Shakehand ready
[:01000007] LAUNCH snlua datacenterd
[:01000008] LAUNCH snlua service_mgr
[:01000009] LAUNCH snlua main
[:0100000a] LAUNCH snlua test_sharedata
[:0100000b] LAUNCH snlua sharedatad
+foo+1+1 [t2]
    | +2 [t3]
    | +t1 [t1]
    +bool [true]
    +arr+1 [1]
    |   +2 [2]
    |   +3 [3]
    |   +4 [4]
    |   +5 [5]
    +bar [fooo]
[:01000009] test_sharedata init finished.
[:0100000c] LAUNCH snlua test_multicast
[:0100000d] LAUNCH snlua multicastd
[:01000009] test_multicast init finished.
[:0100000e] LAUNCH snlua test_agent
[:0100000e] attempt to yield across a C-call boundary
[:0100000e] stack traceback:
	./service/test/test_agent.lua:27: in function <./service/test/test_agent.lua:25>
	[C]: in function 'profile.yield'
	../lib/skynet/lualib/skynet.lua:375: in upvalue 'yield_call'
	../lib/skynet/lualib/skynet.lua:389: in function 'skynet.call'
	../lib/skynet/lualib/skynet.lua:530: in function 'skynet.uniqueservice'
	../lib/skynet/lualib/multicast.lua:93: in local 'f'
	../lib/skynet/lualib/skynet.lua:591: in function 'skynet.init'
	../lib/skynet/lualib/multicast.lua:102: in main chunk
	[C]: in function 'require'
	./service/test/test_agent.lua:8: in function <./service/test/test_agent.lua:5>
	[C]: in function 'xpcall'
	./service/test/test_agent.lua:25: in upvalue 'f'
	../lib/skynet/lualib/skynet.lua:110: in function <../lib/skynet/lualib/skynet.lua:104>
[:0100000e] Response message : "
[:0100000e] lua call [1000008 to :100000e : 2 msgsz = 5] error : ../lib/skynet/lualib/skynet.lua:519: ../lib/skynet/lualib/skynet.lua:443: Unknown session : 2 from 1000008
stack traceback:
	[C]: in function 'assert'
	../lib/skynet/lualib/skynet.lua:519: in function 'skynet.dispatch_message'

**Comment by tangyiyang** [comment]
好吧，发完这个issue之后我好像有点明白了。。。。

**Comment by cloudwu** [comment]
所以并不需要那么长的测试案例。

本质上因为 multicast 模块在加载后，需要有一个 init 过程，而这个过程是需要 yield 的。为了把 init 过程自动化，调用了 skynet.init 。但是它并不适合这种场合。

把 `require "multicast"` 放在外面即可。

**Comment by tangyiyang** [comment]
嗯 testcase顺手就写多了。：）
