### ISSUE TITLE
不同版本的lua之间是不是不能通过sproto通讯？

### ISSUE THREAD

**Issue by linse073** [cloudwu/skynet#397]
服务器是5.3的，客户端是5.1的，他们之间通过sporto通讯，在传递大数的时候不一致，请问是否只能通过同步版本才可以解决？

**Comment by szoyj** [comment]
可能跟int64有关

**Comment by yingnierxiao** [comment]
大数据考虑用string传

**Comment by cloudwu** [comment]
lua 5.2  之前, lua 本身的 number 类型只有 2^52 整数精度.

**Comment by cloudwu** [comment]
sproto 首先是个 C 库,其次才有 lua binding . 对于 luajit, 你可以改写 binding, 让其可以利用 luajit 的 int64 类型.

lua 5.1/5.2 没有什么好的方法, 传字符串会比较通用.

btw, 如果你用 json , 也会有类似问题. javascript 里用 json 也不主张你直接对 int64 做 number 类型编码. 这并非协议的问题.
