### ISSUE TITLE
关于handle分配的性能提高点

### ISSUE THREAD

**Issue by yuliying** [cloudwu/skynet#399]
是否可以通过handle id段分组加锁来提高handle分配的性能？类似下面的代码。

![qq 20151203144109](https://cloud.githubusercontent.com/assets/10045670/11553675/fb3b0b80-99cb-11e5-8a78-414a7b6a09db.png)

**Comment by cloudwu** [comment]
没有特殊的理由，不增加不必要的复杂性。
