### ISSUE TITLE
关于skynet.call调用回复的疑问

### ISSUE THREAD

**Issue by sctangqiang** [cloudwu/skynet#400]
知道一个A服务请求的session 和 source地址， 有没有方法在B服务不通过skynet.ret和skynet.response 去给A的相应请求恢复

**Comment by linse073** [comment]
用skynet.redirect就可以了。

**Comment by sctangqiang** [comment]
function MsgProxy.send_redirectmsgto_gateagent(gatesvr_id, agent_address, session, ...)
	skynet.redirect(agent_address, skynet.self(), "lua", session, ...)
end

我想这样填写对吗， 还有我传入的参数 ...是两个table （skynet.ret(skynet.pack(...)) 回应没有问题）， 在执行时报invalid table
