### ISSUE TITLE
skynet在linux下nohup 后台运行debug_console listen会出错。

### ISSUE THREAD

**Issue by tangyiyang** [cloudwu/skynet#408]
重现：nohup ./skynet examples/config&
平台: aliyun, ubuntu 14.04
错误：
[:0100000b] LAUNCH snlua console
[:0100000c] LAUNCH snlua debug_console 8000
[:0100000b] lua call [0 to :100000b : 0 msgsz = 56] error : ./lualib/skynet.lua:519: ./lualib/skynet.lua:156: ./lualib/socket.lua:367: assertion failed!
stack traceback:
	[C]: in function 'assert'
	./lualib/socket.lua:367: in function 'socket.lock'
	./service/console.lua:15: in upvalue 'func'
	./lualib/skynet.lua:455: in upvalue 'f'
	./lualib/skynet.lua:105: in function <./lualib/skynet.lua:104>
stack traceback:
	[C]: in function 'assert'
	./lualib/skynet.lua:519: in function 'skynet.dispatch_message'
[:0100000c] Start debug console at 127.0.0.1 8000
[:0100000d] LAUNCH snlua simpledb

**Comment by cloudwu** [comment]
不要在后台运行 console
