### ISSUE TITLE
内存问题

### ISSUE THREAD

**Issue by yibiaochen** [cloudwu/skynet#413]
我们线上的游戏，物理机160G内存，用到70%多的时候，就开始了使用swap，此时7000+人，频繁读swap导致游戏内明显的卡。而我写指令在skynet内进行压测，可以跑到把物理内存都用完，才开始使用swap。
云风对这个现象有何建议么

**Comment by cloudwu** [comment]
1. 应该严格杜绝使用 swap (最好直接把 swap 关掉)
2. 运维应该有一个内存使用的报警机制. 最好可以结合这个自动关闭新用户登录.
3. 70% 指 top 看到的? 这个应该和系统有关, 不是 skynet 自己可以控制的.
4. 7000+ 人使用 100G 内存有点偏多, 有优化的空间.

**Comment by yibiaochen** [comment]
70%是top看到的，运维在持续怀疑skynet，我口水都说干了。。。
这个项目做得很赶，5个多月就上了线，对skynet的一些使用经验不足，确实可以对内存做比较大的优化

**Comment by cloudwu** [comment]
你可以看看是不是有别的进程占用了物理内存。

毕竟如何分配和使用物理内存是由 os 决定的。

**Comment by yibiaochen** [comment]
查了之后，按照运维的说法，发现很多内存是被cache占用了，高达几十G
这部分已经在查证重现是否protobuff的问题（我们在不同服务内会重复去读同一个pb文件）

**Comment by yibiaochen** [comment]
对了，http://xy.4399sy.com/这个是我们游戏，一个mmorpg，3月份开始用skynet做，8月份上线，现在线上运行情况还算比较满意 ,至少没有想象中遇到的坑那么多 :D
现在我想开源一下这个项目的部分代码，算是抛砖引玉，跟大家一起交流交流对skynet的使用，云风啥时候跟去年一样搞个交流会啊，哈哈

**Comment by yibiaochen** [comment]
对了，http://xy.4399sy.com/ 这个是我们游戏，一个mmorpg，3月份开始用skynet做，8月份上线，现在线上运行情况还算比较满意 ,至少没有想象中遇到的坑那么多 :D
现在我想开源一下这个项目的部分代码，算是抛砖引玉，跟大家一起交流交流对skynet的使用，云风啥时候跟去年一样搞个交流会啊，哈哈

**Comment by cloudwu** [comment]
protobuff 应该重用. 如果你用的 pbc 库， 那么那个协议结构是一个 C 结构， 加载完后是一个 C 指针，且只读是线程安全的。所以没有必要加载很多次（加载时间和内存都浪费）

https://github.com/cloudwu/pbc/blob/master/binding/lua53/protobuf.lua#L21

你只需要在 require 库之前，把那个结构指针放在 lua 的注册表中 `PROTOBUF_ENV` 即可。在所有依赖的服务之前，通常是服务器启动环节，单独用一个加载服务搞定即可。

**Comment by yibiaochen** [comment]
嗯，昨天已经将pbc改成了重用，跟你说的做法一样，这周维护时放出去看看效果如何

**Comment by firedtoad** [comment]
抄梦幻抄的比较成功的游戏！！！！！

2015-12-23 11:55 GMT+08:00 billchen <notifications@github.com>:

**Comment by yibiaochen** [comment]
里面的内容策划下了很大功夫，数值和一些规则很不一样

**Comment by firedtoad** [comment]
就是 同一套大话1的策划案 走到 梦幻 天龙 大话2 的不同方向上了 但愿你们能走出一套自己的方向

2015-12-23 14:55 GMT+08:00 billchen <notifications@github.com>:

**Comment by kawaiSky** [comment]
@yibiaochen 看起来客户端使用了unity3d 的 ulua 。
请教下是只有热更新部分使用了 ulua，还是游戏的逻辑都是用lua写的？

**Comment by yibiaochen** [comment]
@kawaiSky 客户端游戏逻辑都用lua写的

**Comment by kawaiSky** [comment]
@yibiaochen 非常感谢.:-)
正好这两天想从 cocos-lua 转unity。在查看一些使用lua开发unity的解决方案

**Comment by yibiaochen** [comment]
今天放出了protobuff的修改在外服测试，cache出现了明显的大量下降
关于操作系统的内存分配还有一个让人吐血的地方，use+cache>=物理内存的时候，就开始使用swap，而不是从cache里面拿，只有强制关了swap，才会从cache拿

**Comment by szoyj** [comment]
PROTOBUF_ENV在哪里进行设置的？@yibiaochen
