### ISSUE TITLE
skynet agent内存泄露。

### ISSUE THREAD

**Issue by tangyiyang** [cloudwu/skynet#415]
嗯，没有任何用例。只是单纯的启动skynet ./example/config。 然后开启agent，退出agent。从debug_console, cmem看到有内存未释放。example好像只有几百个字节。我的项目里是正好的1k。不知道是为什么 :( 

日志如下：
mem
:01000004	62.95 Kb (snlua cmaster)
:01000005	73.88 Kb (snlua cslave)
:01000007	45.40 Kb (snlua datacenterd)
:01000008	62.51 Kb (snlua service_mgr)
:0100000a	269.85 Kb (snlua protoloader)
:0100000b	66.94 Kb (snlua console)
:0100000c	119.27 Kb (snlua debug_console 8000)
:0100000d	51.57 Kb (snlua simpledb)
:0100000e	49.76 Kb (snlua watchdog)
:0100000f	56.21 Kb (snlua gate)
:01000029	219.77 Kb (snlua agent)
OK
cmem
:01000002	165408
:01000003	62784
:01000004	60016
:01000005	90992
:01000006	144
:01000007	11952
:01000008	58080
:01000009	88240
:0100000a	17760
:0100000b	8720
:0100000c	42384
:0100000d	8880
:0100000e	14608
:0100000f	31776
:01000010	17136
:01000012	144
:01000019	144
:01000020	208
:01000022	208
:01000029	32
:fffffffe	32
:ffffffff	6325392
OK
cmem
:01000002	165408
:01000003	60784
:01000004	60016
:01000005	90992
:01000006	144
:01000007	11952
:01000008	58080
:01000009	88240
:0100000a	17760
:0100000b	8720
:0100000c	42576
:0100000d	8880
:0100000e	14640
:0100000f	31776
:01000010	17136
:01000012	144
:01000019	144
:01000020	208
:01000022	208
:01000029	176
:fffffffe	32
:ffffffff	6325392

**Comment by cloudwu** [comment]
1. 你要先确定不是共享代码 proto 或是共享短字符串造成的。
2. 如果你不知道怎么确定 1 ，那么把 3rd/lua 替换为标准的 lua 实现再看。
3. 如果代码简单，且你确定是泄露，那么就直接找到问题在哪里。

**Comment by cloudwu** [comment]
我在我的机器上做了简单的测试， 发现了 cmem 显示有几十字节未回收。但并没有反复增长的趋势。

这里可以做一个可信的解释：

skynet 的 cmemory 统计是基于这样的原理：在切换工作线程时，会把正在处理的服务 id 记在一个 TLS 变量里，当有任何内存的请求，那么会去查当前线程的 TLS 变量，取得正在工作的服务 id ，然后在一个全局数组里记录这次分配。

所以，发生在当前服务激活状态下的任何 C 代码层面的内存分配，但会被记在这个服务名下。

在正常逻辑下，有这样几种情况分配出来的内存，不会因为服务退出而立刻释放掉：

最常见的是发送消息，消息的内存是由发送者分配的，只要接收者还没有处理，那么内存就还在。当然，释放只是推迟，如果始终无法释放，那么是接收方的代码有误（如果是 lua 编写的服务，不会发生这种情况）。

另一个常见的情况（很可能是上面的现象原因），当前 lua 服务 require 了一个 C 编写的模块。而 C 模块是一个动态库，由 dlopen 打开的，dlopen 发生在当前服务的线程中，所以被记为该服务分配出来的内存。

而由于动态库是整个进程共享的，由引用计数控制，所以服务退出时调用 dlclose 未必会释放相关内存。
