### ISSUE TITLE
lualib编译出错 原因如下 求修正

### ISSUE THREAD

**Issue by wjlin** [cloudwu/skynet#417]
malloc_current_memory没有在skynet.def中设置为导出
而lua-memory.c(46):    lua_pushinteger(L, malloc_current_memory()); 使用了该函数指针
链接时候保错 求修正

**Comment by cloudwu** [comment]
skynet.def 是什么文件? 我没见过。

**Comment by firedtoad** [comment]
估计是编译dll用到的

2015-12-24 13:15 GMT+08:00 云风 <notifications@github.com>:

**Comment by wjlin** [comment]
不好意思我发错了 我应该发到 https://github.com/sanikoyes/skynet/tree/vs2013 上
