### ISSUE TITLE
客户端向skynet发送数据包时，服务端抛出./skynet: double free or corruption (fasttop)的异常

### ISSUE THREAD

**Issue by Manistein** [cloudwu/skynet#421]
云大，最近我在尝试实现客户端和skynet进行通讯，自己用C++写了客户端与服务器发送数据的代码，不过，我连续向gateserver发送数据包时，服务端抛出如下错误：
*** glibc detected *** ./skynet: double free or corruption (fasttop): 0x0000000000e9c8a0 ***
======= Backtrace: =========
/lib/libc.so.6(+0x788d6)[0x7f2e661788d6]
/lib/libc.so.6(cfree+0x73)[0x7f2e6617ef13]
./skynet(skynet_context_message_dispatch+0x7f)[0x40951f]
./skynet[0x40a24d]
/lib/libpthread.so.0(+0x69ca)[0x7f2e66b1e9ca]
/lib/libc.so.6(clone+0x6d)[0x7f2e661eb45d]
======= Memory map: ========
00400000-0043f000 r-xp 00000000 08:05 1049116                            /home/manistein/workspace/server-app/GreatFighter/skynet/skynet
0063e000-0063f000 r--p 0003e000 08:05 1049116                            /home/manistein/workspace/server-app/GreatFighter/skynet/skynet
0063f000-00640000 rw-p 0003f000 08:05 1049116                            /home/manistein/workspace/server-app/GreatFighter/skynet/skynet
00640000-00740000 rw-p 00000000 00:00 0 
00e4e000-00eb1000 rw-p 00000000 00:00 0                                  [heap]
......
问题找了很久，发现自己没法解决，希望云大赐教

**Comment by Manistein** [comment]
我在发送数据时，已经为其加上描述数据长度的首部，服务端一开始还能输出日志显示客户端发送的字符串，但是过一阵子就会抛出异常

**Comment by cloudwu** [comment]
最大可能是你释放了由框架负责释放的指针。

代码在你手上，环境也在，问题又能重现，你有能力找到问题，何必寻求帮助？

发自我的 iPhone

**Comment by cloudwu** [comment]
服务器出问题, 和你客户端发了什么数据无关. 你发什么都不应该导致服务器的故障.

**Comment by Manistein** [comment]
感谢云大的回答，应当是我在服务端某个地方处理有问题，我再看看example那里，agent和gate部分的例子

**Comment by Manistein** [comment]
经过跟踪和调试，已经定位出问题所在，原来是我agent服务中，接收client类消息时，unpack函数调用了netpack.tostring函数，原本是想通过这个函数，把msg和sz转化为lua的string，查阅文档和跟踪代码后，才知道netpack.tostring已经进行一次free，而gate发给agent的消息中，又会进行一次free（发送方创建，接收方释放），因此产生了同一个指针被释放两次bug，不过好奇怪，一开始的几次还是好好的，不知道我上面的理解是否正确，目前把unpack函数改为调用skynet.tostring就没有问题了。
