### ISSUE TITLE
多次在codingnow.com里看到，使用名字服务不好，原因是？

### ISSUE THREAD

**Issue by tangyiyang** [cloudwu/skynet#423]
我的理解是，名字就好像一个单例一样的存在着。提供了一个类似“全局变量”的东西。但是这个全局变量也有一些好处。比如直接去call某个服务不需要把地址当成局部变量一步一步的传递进来。

很想知道，这个 “名字服务在什么样的场景下会造成什么样的问题？” :D 

经验不足，还望解答。

**Comment by cloudwu** [comment]
因为我一直想把这个特性从底层去掉, 只是用的人太多...

但是, 还是想删.
