### ISSUE TITLE
mysql.lua里面一个问题

### ISSUE THREAD

**Issue by alpha2z** [cloudwu/skynet#430]
local function _send_packet(self, req, size)
    local sock = self.sock

```
self.packet_no = self.packet_no + 1


local packet = _set_byte3(size) .. strchar(self.packet_no) .. req

return socket.write(self.sock,packet)
```

end
这个socket.write是不是没有引用socket.lua库文件？

**Comment by cloudwu** [comment]
整个 `_send_packet` 函数应该是不用的，是 changfeng 从 open resty 移植过来时没删干净。

我这就删掉。
