### ISSUE TITLE
httpc get不到内容

### ISSUE THREAD

**Issue by OpenGamex** [cloudwu/skynet#431]
httpc第三方api, 会有个别获取不到内容，调试代码发现body其实获取了，只是实体报头有些问题，没有transfer-encoding和content-length, 导致body被置nil, 下面是具体的响应头:
HTTP/1.1 200 OK
Connection: close
Date: Thu, 07 Jan 2016 01:53:53 GMT
Server: Microsoft-IIS/6.0
X-Powered-By: PHP/5.2.17
Expires: -1
Cache-Control: no-store, private, post-check=0, pre-check=0, max-age=0
Pragma: no-cache
Access-Control-Allow-Origin: *
Content-type: text/plain; charset=UTF-8

**Comment by cloudwu** [comment]
麻烦看一下, 我这么改行不行.

如果没有 content-length 就读所有的数据.

**Comment by OpenGamex** [comment]
恩, 测试了几个第三方的都可以了,谢谢！
