### ISSUE TITLE
multicast 问题

### ISSUE THREAD

**Issue by wangyanglong** [cloudwu/skynet#432]
嗨，云大
   我在同一harbor下，不同的服务订阅相同的global_channel时，出现很奇怪的现象
在multicastd.lua中的SUB函数中,print("SUB",channel, c, group),出现如下现象
SUB	table: 0x7fb26a70d200	1	table: 0x7fb26a70e930
SUB	table: 0x7fb26a70d200	1	nil
第一个print可以打印group,是因为global_channel在该服务中初始的，
第二个服务subscribe时，相同的channel，相同的c,却取不到group，但是此时遍历channle,可以打印出
1 table: 0x7fb26a70e930

**Comment by cloudwu** [comment]
如果使用上有 bug 请给 test case

如果只是代码理解上有问题，自己慢慢调试慢慢看。
