### ISSUE TITLE
关于httpc疑问

### ISSUE THREAD

**Issue by sctangqiang** [cloudwu/skynet#436]
httpc.dns调用在一个服务初始化时调用一次和每次httpc请求都调用，有什么不同？

**Comment by sctangqiang** [comment]
httpc的一个对外请求有没有超时时间？是否需要逻辑层支持超时？

**Comment by dpull** [comment]
可以使用 这个  https://github.com/dpull/lua-webclient   它是对curl的简单封装，有参数设置超时

**Comment by cloudwu** [comment]
目前可以设置 httpc.timeout 。
