### ISSUE TITLE
mysql断线重连报错

### ISSUE THREAD

**Issue by LokerLi** [cloudwu/skynet#437]
mysql断开重连报错，之前的版本是正常的

[:0000000c] lua call [3a to :c : 42 msgsz = 15] error : ../3rd/skynet/lualib/skynet.lua:521: ../3rd/skynet/lualib/skynet.lua:155: [Error: socket]
stack traceback:
	[C]: in function 'error'
	../3rd/skynet/lualib/socketchannel.lua:394: in function <../3rd/skynet/lualib/socketchannel.lua:378>
	(...tail calls...)
	../server/service/mysqld.lua:22: in field 'q'

**Comment by LokerLi** [comment]
重连是可以的，是我的实现问题

**Comment by puXiaoyi** [comment]
更新版本后，我也出现了一样的问题，请问你是怎么解决的？ @hlouis

**Comment by puXiaoyi** [comment]
@LokerLi 更新后，我也出现一样的问题，请问你是怎么修改的？

**Comment by LokerLi** [comment]
我的处理比较粗暴，如果请求失败，执行一次SELECT 1, 这时重连是成功的，然后再执行之前的失败请求

**Comment by puXiaoyi** [comment]
@LokerLi 恩。 我这边手动重启mysqld服务后，第一次query会失败报错，第二次query就成功执行了。socketchannel的query方法里会执行block_connect进行了成功重连。
可是项目遇到的问题是，更新skynet版本后，每天早上mysql的query方法都会报错，并且一直没有重连成功。因为处于测试阶段，所以晚上并没有活动的数据库连接，wait_timeout的超时时间过了后，数据库连接就断开了。我猜测是这个样子，但是为什么不能重连成功呢？

**Comment by cloudwu** [comment]
在 socket channel 里加点 log 看看 connect 流程是怎么走的。另外可以 log 一下你这个服务的输入消息。方法是在 debug console 上用 logon 打开这个服务的消息 log https://github.com/cloudwu/skynet/wiki/DebugConsole

打开 log 能在 log 文件里看到所有的 socket 类消息的输入，可以分析出 socket 断开，连上等等消息的情况。

**Comment by puXiaoyi** [comment]
[bugfix: socketchannel order mode may blocked. (used by redis driver)](https://github.com/cloudwu/skynet/commit/c1c032eab4a0e2e98ba5ac150e14e73ccde85e2e#diff-c85b3bafb60775454ee2021006c89a72)
这个版本***dispatch_by_order*方法改成非阻塞后，无法检测到客户端socket主动断开。**

原本 *dispatch_by_order* 循环中，*socket.block* 方法是挂起协程阻塞的，当客户端socket主动断开的时候，*socket* 协程被唤醒发现 *connected* 为 *false*，继续执行了 *close_channel_socket(self)* 和 *wakeup_all(self)*，进而调用 *socket.close* 关闭了 *socket* 。所以，*channel:request* 中的*block_connect* 方法 *check_connection* 返回false，执行了相关的重连逻辑。更新版本后，*dispatch_by_order* 循环中不处理客户端 *socket* 主动关闭，从而 *channel:request* 中*block_connect* 方法 *check_connection* 返回true，重连逻辑没有被执行，直接在已经断开的 *socket* 上执行 *write* 方法报错，报错之后 *socket* 关闭标识会被更新，所以在下一次执行*channel:request* 的时候，重连逻辑会被触发运行。

> 我的处理比较粗暴，如果请求失败，执行一次SELECT 1, 这时重连是成功的，然后再执行之前的失败请求

@LokerLi 提供的方法，SELECT 1，会触发socketchannel报错并更新*socket.__closed*标识，再执行正式的请求就会重连返回正确的消息了。 我们现在采取的方式是pcall调用数据库查询方法，如果报错再执行一遍。
```lua
local CMD = {}
local pool = {}

local size = 10
local index = 1

local function getdb()
        local db = pool[index]
        index = index + 1
        if index > size then
                index = 1
        end
        return db
end

function CMD.query(sql)
        local db = getdb()
        local ok, result = pcall(db.query, db, sql)
        print(ok, result)
        if not ok then
                result = db:query(sql)
        end
        local result = db:query(sql)
        print(dump(result))
        return result
end
```

> 可是项目遇到的问题是，更新skynet版本后，每天早上mysql的query方法都会报错，并且一直没有重连成功。因为处于测试阶段，所以晚上并没有活动的数据库连接，wait_timeout的超时时间过了后，数据库连接就断开了。我猜测是这个样子，但是为什么不能重连成功呢？

后来确认是mysql断开确实是因为wait_timeout默认为8小时，项目开发阶段晚上并没有活动的数据库连接，所以早上上班测试的发现连接已经断开。一直没有被发现的原因，是因为以前sockectchannel自动重连。又因为采用了100大小的连接池，所以错认为一直重连不成功，只是没有在一个连接中重复请求罢了。

经测试，redis断开之后，也是第二次才能重连成功。

@cloudwu 云大，不清楚当初那个patch [bugfix: socketchannel order mode may blocked. (used by redis driver)] 的修改初衷是为了什么，难道现在重连必须二次才能成功吗？还是我的理解有错误，希望你能指点一二。

**Comment by cloudwu** [comment]
原来的版本在某种情况下会一直阻塞，具体不记得了。

不知道你说的两次是什么。按设计初衷，任何请求都可能因为链接问题失败。失败后怎样重试交给应用层自己处理。所以应用层必须考虑请求失败的情况。

**Comment by puXiaoyi** [comment]
谢谢 @cloudwu 
第一次request失败会后，下一次request才能重连成功，相对于之前感觉是两次了。
现在在项目中，redis和mysql的应用层都加了pcall处理，现在没有什么问题了。
