### ISSUE TITLE
请教下云大，sproto相关问题

### ISSUE THREAD

**Issue by cwnjitwx071** [cloudwu/skynet#438]
1、整个skynet，目前已经能过通过text的形式进行服务器和客户端通信，目前我们客户端是嵌入式的板卡，代码基本用C开发实现，暂且不支持lua。
2、sproto底层用C实现，跟lua进行binding，编码和解码都在sproto.c中，目前这块代码已看，大体的流程和编解码格式有所了解，想做一个sproto和C binding，请问能否和C进行binding，主要是客户端上暂且不能运行lua，如果在sproto.c的基础上进行封装，这样做是否能行，能给点建议不，谢谢。

**Comment by cloudwu** [comment]
sproto 理论上可以完全在 c 里工作，但是我认为 c 不具备动态类型的能力，所以最好是根据定义好的协议生成 c 结构和相关代码，然后在编译到客户端里。

不过我认为更好的方法是嵌入一个 lua vm , 不必用它做任何业务逻辑，仅仅用来做数据的编解码。然后再把读写数据的接口定义成 c api , 把 lua 完全藏起来。

lua 本身可以裁剪，比如去掉解释器，去掉标准库。
