### ISSUE TITLE
请问云大 关于热更新的实现 有没有什么比较好或者建议的方案 

### ISSUE THREAD

**Issue by johnhom** [cloudwu/skynet#440]
目前有一个思路
专门起一个中心服的skynet实例
由console作命令输入
当输入热更新命令后
把本地的脚本 以字符串形式读入
大概形式{['aa.lua']=str1,['bb.lua']=str2}
再传给其他skynet实例
但是有一个还没想通的地方   另外一个实例gate里面收到这个脚本的表
需要传给所有的服务，在对应的服务 进行loadstring
问题1.  不具名的服务newservice好像就找不到了。
问题2.  记得一个文档说了  不能保证服务间传递消息的先后顺序
问题3.  是不是snax实现的 热修复BUG 比较可靠， 那么我考虑所有skynet服务改成 snax服务
问题4.  热更配置数据 因为配置数据是放在sharedata服务， 数据有点大，直接sharedata.update(name, value) 全部配置，  有没有性能上的问题

**Comment by dpull** [comment]
我们使用的是一个自定义的Import函数，实现可以看这儿  http://www.dpull.com/blog/2012-12-18-lua_utils  Import的lua版本。。

非云风公司，看到硬答 ：）

**Comment by cloudwu** [comment]
沿用常规的 lua 更新的方法做就好了。如果过去从来没有做过，那么久理解 lua 如何工作，然后考虑怎么做。这和 skynet 无关，没有彻底完美的方法，只是看你需要做到什么程度。需要结合自己对 lua 的理解来做。

sharedata 的重要设计目的就是可以更新(否则实现会简单的多) ，大规模数据更新，可以考虑由 sharedata 服务自己加载文件，而不是传一个巨大的字符串给它。

我个人比较建议在原地（保持服务地址）重新开启新的虚拟机，这样最为干净。可以参考 http://blog.codingnow.com/2016/03/skynet_reload.html ，但需要想办法从老的虚拟机中继承状态，这部分需要你自己实现。
