### ISSUE TITLE
skynet.call "call failed" error，设计上应该怎么规避这种错误呢。

### ISSUE THREAD

**Issue by tangyiyang** [cloudwu/skynet#441]
https://github.com/cloudwu/skynet/blob/master/lualib/skynet.lua#L375-L383

触发这个错误的原因，是因为我call到agent里，但是这个时候 agent 对应的玩家下线退出了。

所有这个call就没有返回。然后就出错了。

要用什么机制能最好的保证，agent 在退出的时候，所有的msg都回复了之后在退出呢。

简单的用cs太粗暴了。:(

**Comment by cloudwu** [comment]
怎么没有返回? 明明返回了, 否则你哪来的出错的机会.

**Comment by tangyiyang** [comment]
我搞清楚我的需求了。问题提的不对。我想知道的是如何正确的去管理agent的生命周期。:)

我大概想了一下，不应该在收到socket.close()的时候就去关闭玩家的agent。应该做一个状态机去管理。

收到socket.close()之后把玩家设置成 afk 状态。

然后在watchdog那里做一个超时去关闭agent，这样应该就能安全的退出了。
