### ISSUE TITLE
关于cluster.call问题

### ISSUE THREAD

**Issue by linxiaolong** [cloudwu/skynet#446]
cluster原生并不支持send，想在上层想达到send效果，目前是采用fork出来去cluster.call。这种做法会出现失序的可能性（跟开发者的预料相悖），就譬如:
1)  a cluster_send b
2）a cluster_call b
以及
1）b cluster_send a
2）b cluster_retpack a
以上情况都会出现失序。可以在规范去约束提醒开发者，但个人觉得不好。目前是采用skynet.wait+skynet.fork解决第一个失序，然后又采用skynet.response+skynet.fork解决第二个问题，本质上都是将cluster操作队列化到fork队列里面去，这些封装好使用起来倒还正常，只是感觉在上层解决这个问题代价略大。目前cluster采用socketchannel，粗略看了下改造一下应该是没问题，cluster不提供send操作有其他方面的考虑？

**Comment by cloudwu** [comment]
你可以额外做一个代理服务, 然后 send 给它. 它来 call . 如果担心转发效率, 可以用 C 写,纯转发以及扔掉回应包.

cluster 希望维持在一个最小功能.

**Comment by linxiaolong** [comment]
之前考虑过额外做服务，但如果要同时保证以上所列情况不失序，实际上需要 cluster_call cluster_send cluster_retpack这些操作都需走同样的路径，也即实际上cluster所涉及的包都会经过两次中转（发送者的代理，接受者的代理），相当于cluster.call的api作用也被悬空了，上层直接skynet.send携带一些信息来模拟了。

**Comment by cloudwu** [comment]
无论是 call 还是 send 还是 response, 都是包传递而已. 你写个 proxy 不考虑处理逻辑一定可以严格按次序转发, 你需要的只是把 send 的 response 扔掉而已.

你可以在 proxy 上分两个类型处理要 response 和不要 response 的包, 这样比较容易过滤.

**Comment by cloudwu** [comment]
所谓次序, 需要保证的其实是 A 到 B 两个服务间的消息次序, 而不用保证一个集群节点和另一个节点间所有通讯的次序.

所以如果你做一个 proxy, 那么可以让有需求的用; 原来的 cluster 还是可以留给没有这类需求的用. 它们其实是相互不影响的.

**Comment by linxiaolong** [comment]
目前另外封装了接口来解决了，算是一种解决方法，有兴趣的同学可以看下

想达到的目标：
不论是本地call/send还是cluster的call/send，确定了发送者A和接受者B，AB之间就会拥有固定的两条A->B B->A路径。

遇到的问题（以cluster为例）
1）发送时机。（这个是因为没原生cluster_send，然后fork模拟造成的跟call或者retpack的失序）
2）发送路径。就譬如A和B，B收到了A的cluster_call：
      a）B cluster_call A
      b）B retpack A
一般没这种循环call的事情，举个例子，a）操作和b）操作目前走的路径是不同的，也即就算用方法保证了发送时机，最终还是会不确定到达A的次序。

目前的解决：
1）决定所有的call（本地/cluster）都封装成 send（本地/cluster） + skynet.wait + skynet.wakeup来模拟类似call功能，相比于原先的call/cluster_call增加代价就是会多携带一些元信息。也即在更上层模拟了call的来回，主要两个原因：可以在上层严格控制来回的路径是固定的/同时也方便做超时等逻辑。
2）本地send本身就提供，而cluster原生没有，所以稍微修改了增加了send支持：clusterd服务增加resq_send接口，send_request之后不关心返回值也即不返回；然后增加cluster.send接口调用resq_send接口。cluster_send和cluster_call本质上一样的流程，都会在clusterd上发生wait。因为采用1）的方案，也即上层不再关心retpack的回包，只需在封装好的返回接口统一retpack(nil)来绕开。

**Comment by cloudwu** [comment]
我今天发现，只需要改一点点地方就可以让 clusterd 支持单向 push 消息（即支持 send），而不用影响过去的特性。

https://github.com/cloudwu/skynet/commit/ace41d7c2261241c047cb7ef0ead77f6c3cc9b6d
https://github.com/cloudwu/skynet/commit/a3eccf5e371a04f8d88522cc87227fb8d1ab4ca0

所以就合并到 master 了。

这样就增加了 cluster.send 方法。但是要求接收方在消息收到的第一行写上
```
skynet.ret()
```
现在 skynet.ret 如果发现 session == 0 会忽略掉回应消息。

**Comment by cloudwu** [comment]
@linxiaolong 今天完善了 cluster.send ，不再需要接收方写 `skynet.ret()` 。另外 cluster proxy 也可以完全工作了。https://github.com/cloudwu/skynet/commit/6289b2b8e4c5333561c2ea69c45fc97b5eeeed73

但是：依然需要提醒的是，cluster.send 会因为 cluster 间网络连接不稳定而丢包。由于没有回应机制，所以无法确定一个 send 推送的包真的收到；而且调用 cluster.send 一边没有返回机制，非阻塞调用，也无法知道出错。
