### ISSUE TITLE
sharedata使用疑问？

### ISSUE THREAD

**Issue by sctangqiang** [cloudwu/skynet#451]
用sharedata在服务A构建了数据中心 创建了cfgmng共享数据节点， 提供了一个configdao接口在其他服务中访问共享数据，   当我在A服务中重新加载配置执行sharedata.update(name, value)  [**value为新的table对象**]后, **通过下面的接口读取不到配置， 这是什么原因？**

configdao中一个接口如下：
**function ConfigDAO.get_business_conf(platform, channel, business)
	if cfgcentermng == nil then
		 cfgcentermng = sharedata.query("cfgmng")
		 platforms = cfgcentermng.platforms
	end
	………………
	return conf
end**

**Comment by cloudwu** [comment]
需要可运行的 testcase .

**Comment by sctangqiang** [comment]
云大的说明是对的， 是client程序有问题
