### ISSUE TITLE
skynet玩家离线数据操作?

### ISSUE THREAD

**Issue by tangyiyang** [cloudwu/skynet#452]
问题: 想直接操作全服所有玩家的数据的时候，应该怎么做呢？

现在玩家的数据是放在数据服务（缓存里）或者agent里，通过定时或者其他机制刷到数据库里。

现在如果想直接修改玩家的数据，需要直接去操作agent里的玩家数据(玩家在线时)，
或者去操作缓存里的数据（缓存数据本身有标志）。

但是如果是有一些针对全服玩家的所有操作，比如简单的给服务器的每一个人都发一封
邮件。这里需要给全服所有玩家的数据载入到内存里。

通常服务器的内存容量并不能支持这个操作。。

现在想到的办法是，将这个操作推迟到玩家上线的时候。这样做看起来可以解决，
还有其他做法么，或者其他想法 :) 

edit: 全服邮件只是一个例子:) 就是这种需要操作玩家所有数据的情况。

**Comment by firedtoad** [comment]
全服邮件只要 保存一封全局副本就行了 等到玩家上线的时候 改一下接收者ID 在发下去就行了没必要操作离线数据 很多死账号没必要浪费内存

在 2016年2月19日 下午3:30，唐艺洋 <notifications@github.com>写道：

**Comment by zuiaiqun** [comment]
这种操作等玩家上线就可以了。但是有些必须要立刻修改的数据，肯定得马上载入。
可以一下载入部分，载入操作数据后，然后从内存里面卸载。控制载入的数据量就好了。

**Comment by tangyiyang** [comment]
@firetoad 感谢，嗯，邮件只是一个例子啦。主要是要考虑需要一起操作所有玩家数据的这种情况。还是说，这是一个业务related 的需求，并没有通用的做法。

**Comment by szoyj** [comment]
估计得具体问题具体分析，因为这个东西跟你相应的功能的设计有关系，从发邮件这个功能来说，我们的设计是邮件不做缓存，所以发邮件就直接写数据库了，如果你们设计是有缓存的，那就得遍历每个玩家在线发给agent一个消息，不在线直接写数据库。一句话这事跟业务功能和程序设计有关，没有标准的、最好的解决办法。

**Comment by tangyiyang** [comment]
感谢@szoyj @zuiaiqun @firedtoad  的回复。:)

嗯，大概想清楚我的需求了。
分成两类，一类是需要立即生效的离线数据。另一类是不需要立即生效的。

稍微通用一点，后者，能抽象出一个pending task 的模块来。:D
把玩家不需要立即完成，等玩家上线的时候去查询对应的task来finish。

需要立即生效的，只有分批次一点一点改了，并且这个需要根据具体的业务去实现。

**Comment by linxiaolong** [comment]
将一些需要考虑离线的（譬如发奖励/邮件）的流程都统一为：先入库（全局离线表，以玩家ID建索引） -> 通知在线agent查询取库并删除/不在线或通知不到的等到上线时候都会去查询取库并删除，个人感觉这样从设计来说是最简单保险的，当然会有不必要的数据库损耗，但在严谨的分布式应用其实重要操作都应该是先入库再行通知，看个人权衡了。
