### ISSUE TITLE
string.pack "string length does not fit in given size".

### ISSUE THREAD

**Issue by tangyiyang** [cloudwu/skynet#454]
嗯，请教一下解决思路，异常如下：
000027f3: [Sun Feb 21 09:01:41 2016] [user_id : 56c57a32b5c8e22e24b8e883, user_name Dante] [Agent] CLIENT-MSG response = login
000027f3: [Sun Feb 21 09:01:41 2016] lua call [2b to :27f3 : 44 msgsz = 1] error : ../lib/skynet/lualib/skynet.lua:521: ../lib/skynet/lualib/skynet.lua:155: ./service/agent.lua:140: bad argument #2 to 'pack' (string length does not fit in given size)
stack traceback:
	[C]: in function 'string.pack'
	./service/agent.lua:140: in upvalue 'send_package_fd'
	./service/agent.lua:145: in upvalue 'send_package'
	./service/agent.lua:172: in upvalue 'f'
	../lib/skynet/lualib/skynet.lua:104: in function <../lib/skynet/lualib/skynet.lua:103>
stack traceback:
	[C]: in function 'assert'
	../lib/skynet/lualib/skynet.lua:521: in function 'skynet.manager.dispatch_message'

这个出错发生在运行1天左右。这个错误感觉有一定的蔓延性，某一个agent一旦出现，其他agent也会跟着出现，导致无法登陆。 :(

**Comment by tangyiyang** [comment]
难道是消息超64k了？

**Comment by firedtoad** [comment]
pack 函数用的格式和参数里面的不一样

2016-02-21 17:55 GMT+08:00 唐艺洋 <notifications@github.com>:

**Comment by xjn9854262** [comment]
老哥，这个问题你解决了吗，我这边也遇到了，能请教是什么问题吗

**Comment by HappyLL** [comment]
超了 协议长度只能2个字节 string.pack("s2", 协议) 长度超过2个字节长度就报错了
