### ISSUE TITLE
sharedata优化建议

### ISSUE THREAD

**Issue by spin6lock** [cloudwu/skynet#456]
https://github.com/cloudwu/skynet/blob/master/lualib/sharedata/corelib.lua#L74 这里assert一下key比较好，现在如果key为nil，会卡住不报错。

**Comment by cloudwu** [comment]
按 lua 的标准，禁止用 nil 去 __index

**Comment by cloudwu** [comment]
我试了一下, key 为 nil 会抛 error

**Comment by firedtoad** [comment]
local tx={}
print(tx[nil])
访问不会报错

2016-02-25 11:40 GMT+08:00 云风 <notifications@github.com>:

**Comment by cloudwu** [comment]
sharedata 的结构要求 key 必须为正整数或字符串, 其它类型的 key 均被认为是非法的.
https://github.com/cloudwu/skynet/wiki/ShareData

**Comment by spin6lock** [comment]
是我看漏了，别的地方pcall住，没看到抛栈，sharedata的行为是对的
