### ISSUE TITLE
client.lua和simpledb.lua无法正常工作

### ISSUE THREAD

**Issue by luyang177** [cloudwu/skynet#458]
先启动simpledb.lua，再启动client.lua

simpledb的终端显示
connect from 127.0.0.1:33368 5

client的终端显示
Request:	1
Request:	2

然后client的终端输入hello回车
则
stack traceback:
	[C]: in function 'error'
	examples/client.lua:46: in upvalue 'recv_package'
	examples/client.lua:92: in local 'dispatch_package'
	examples/client.lua:105: in main chunk
	[C]: in ?

而simpledb的终端显示
disconnect fd = 5, error = ./service/cmaster.lua:36: closed

**Comment by luyang177** [comment]
似乎是client.lua中的
local package = string.pack(">s2", pack)
这句有问题，这个package的第一个字节是0啊

**Comment by cloudwu** [comment]
1. 无法重现
2. simpledb 没有监听端口,显示 connect from 从何说起?
3. cmaster.lua 是用于节点间互连用的, 和 client.lua 和 simpledb.lua 没有关系.

建议先搞清楚工作流程以及什么信息是由什么服务输出的.

**Comment by luyang177** [comment]
抱歉提了这个愚蠢的问题。

我知道原因了
我没有启动gate服务
而且把client的连接端口改成2013也就是master的监听端口了
然后我发现examples里面现成的main.lua把这些都写好了
结果我自己把config里面的start = "simpledb"
哎，我为什么要多此一举呢
现成的main.lua都写好了啊。
