### ISSUE TITLE
cluster有内存泄露吗？

### ISSUE THREAD

**Issue by ZangXu** [cloudwu/skynet#461]
用cluster做的集群，两个互联的节点直接通过call调用（测试每10ms调用10次call，每次call时传递一个一模一样的长字符串），这两个节点的内存会一直增长，差不多1s增长100kb左右，并且不会回落。

**Comment by cloudwu** [comment]
1. 请 fork 一个 skynet 补上 test case 和启动脚本, 以及使用说明.
2. 如果是简单测试就能发现的问题, 可以自己通过 debug console 查看内存使用情况, 并在增长的服务 (例如 clusterd ) 中添加调试代码输出内存使用情况.

**Comment by gongchenic** [comment]
是不是clusterproxy没有kill掉？我们游戏有跨服副本的类似功能。每次玩家打完退出之后，就会残留一个clusterproxy的service,50KB左右。需要自己退出。

**Comment by cloudwu** [comment]
读一下 https://github.com/cloudwu/skynet/blob/master/service/clusterproxy.lua

如果看不懂就不建议使用它。
