### ISSUE TITLE
linux下怎么使用valgrind调试内存泄露情况？

### ISSUE THREAD

**Issue by sue602** [cloudwu/skynet#462]
在skynet_main.c 的主函数里随便插入一个malloc函数，使用valgrind检测不出内存泄露。
skynet_malloc(80000);
printf("askdjalksdfjaksdfasdf");
skynet_start(&config);
skynet_globalexit();
luaS_exitshr();

valgrind 测试指令如下
valgrind --tool=memcheck --leak-check=full ./skynet ./examples/config

**Comment by tangyiyang** [comment]
之前也试过用valgrind，最后回到skynet_malloc上，其实我们并不需要 valgrind, skynet为我们提供了hook。

你需要参考下云风之前发的帖子和其他的issue，我有提过。

**Comment by sue602** [comment]
解决了。修改makefile，在linux下也去掉jemalloc就行
