### ISSUE TITLE
socketdriver 有相关文档吗？

### ISSUE THREAD

**Issue by defp** [cloudwu/skynet#467]
socket和socketdriver有什么区别？

比如socket.close(fd) 和 socketdriver.close(fd) 应该用哪一个？

**Comment by defp** [comment]
别外，当服务端主动关闭连接的时
socket.close(fd)不能正确关闭的，
而 socketdriver.close(fd) 是可以关闭的

![image](https://cloud.githubusercontent.com/assets/12042737/13668868/83e6214c-e6fa-11e5-888a-a5efb2be0cda.png)

**Comment by cloudwu** [comment]
区别在于，socket 模块的 C 部分基于 socketdriver ，应用层不要使用 socketdriver 这个模块。socket.close 有可能阻塞，依赖协程的工作。它会通知并等待其它协程中对这个 socket 的阻塞操作结束。

socket.close_fd 等价于 socketdriver.close ，会粗暴的关闭 fd ，通常只用于服务退出时 gc 过程回收漏掉没有关闭的 fd 资源。只是一种后备策略。

https://github.com/cloudwu/skynet/blob/master/lualib/socket.lua#L226-L235

**Comment by defp** [comment]
明白了，我应用层使用socket.close(fd) 没起作用是因为还有其它操作阻塞

**Comment by defp** [comment]
https://github.com/cloudwu/skynet/blob/master/lualib/socket.lua#L236-L239

我现在调用socket.close(agent.fd) 时

打印是nil

![](http://lidashuang.u.qiniudn.com/16-3-11/56387109.jpg)

而我调用close_fd(agent.fd)时，也不会报错

**Comment by cloudwu** [comment]
明显异常的问题请自己调试找到原因
