### ISSUE TITLE
time diff error 是什么错误 ？

### ISSUE THREAD

**Issue by defp** [cloudwu/skynet#468]
`time diff error: change from 145761353309 to 145761353379`

**Comment by cloudwu** [comment]
这次 gettime() 获取的时间比上次获取的时间早，因为潜在的约束条件是时间是单向流逝的。

**Comment by defp** [comment]
遇到这个log，需要注意什么呢？

**Comment by cloudwu** [comment]
检查你的平台上的 gettime() 的实现为什么会返回这样的结果，然后改进这个实现。

**Comment by cpejlgc** [comment]
我在Mac mini上出现过这个问题。

**Comment by harrywong** [comment]
更新时的时间戳比前面记录的时间戳要靠前，检查下系统时钟的时间为什么会变化吧。是不是自动网络对时了。

**Comment by cloudwu** [comment]
在 linux 上，因为使用 `clock_gettime(CLOCK_MONOTONIC, &ti);` 可以不受自动对时服务影响。
mac 上需要有对应实现。
