### ISSUE TITLE
cluster.call的被调用方拿到的address是不是失效的

### ISSUE THREAD

**Issue by warmsun-li** [cloudwu/skynet#471]
cluster.call的被调用方拿到的address是不是失效的？
如果失效的话，请问云大有没有什么好方法拿到调用方服务的address？

**Comment by cloudwu** [comment]
自己传。

**Comment by warmsun-li** [comment]
如何知道是哪个节点调用的call呢，传个string过去？

**Comment by cloudwu** [comment]
这个随便，想怎么设计都行。
