### ISSUE TITLE
 sharedata new的数据cjosn无法encode :Cannot serialise userdata: type not supported

### ISSUE THREAD

**Issue by wujiyu115** [cloudwu/skynet#475]
sharedata 的数据cjosn在encode时抛出Cannot serialise userdata: type not supported.求解
`
local sharedata = require "sharedata"
local json = require "cjson"
skynet.init(function (  )
	local test_data = {a =1}
	sharedata.new("test_data",test_data)
	local share_test  =  sharedata.query("test_data")
	print(test_data,type(test_data))
	local  test = json.encode(test_data)
	print(test)
	local  test1 =json.encode(share_test)
	
end)
`

**Comment by cloudwu** [comment]
更新你的 json 库，让它在遍历 table 的时候支持 `__pairs` 方法。
或者在 encode 前做一次深拷贝。

**Comment by wujiyu115** [comment]
先打个patch。
`local json = require "cjson"
local json_safe = require "cjson.safe"
local old_encode = json.encode
local tableutil = require "public/util/tableutil"

json.encode = function ( tab )
	local safe_resuslt = json_safe.encode(tab)
	if  safe_resuslt then
		return safe_resuslt
	end
	local other_table = tableutil.deep_copy(tab)
	return old_encode(other_table)
end`
