### ISSUE TITLE
关于harbor.queryname不返回

### ISSUE THREAD

**Issue by H-Vilian** [cloudwu/skynet#476]
master进程用harbor.globalname("my",hdl)注册了一个服务。slave进程通过harbor.queryname("my")无法获得返回。后来把注册的动作放在查询之后，才能触发该查询并返回结果，这是个bug还是我没正确使用呢？

**Comment by cloudwu** [comment]
这是前段时间引入的 bug ，已修。

bug 出现在注册全局名字时，slave 没有启动。如果 slave 启动好后才注册的名字则没有问题。

在 slave 启动后，master 目前没有推送已知名字的义务（过去的实现有这个行为）。

直接向已注册名字发送消息时，harbor 会发送查询，但 harbor.queryname 里漏了发送查询。
