### ISSUE TITLE
reserve_id 

### ISSUE THREAD

**Issue by doublefox1981** [cloudwu/skynet#488]
skynet在给每一个套接字分配skynet内部id的时候，最坏的时候会遍历MAX_SOCKET次，请问在有大量连接的情况下，每次创建连接开销是否会很大呢？

**Comment by cloudwu** [comment]
请给 testcase 和对比数据。

**Comment by cloudwu** [comment]
请给 testcase 和对比数据。

**Comment by cloudwu** [comment]
请给 testcase 和对比数据。

**Comment by doublefox1981** [comment]
暂时不太好找数据，因为实在不好去创建几万个连接，我是看代码的时候想到这个问题，但是我想如果有问题的话云大不可能没想到，可能是我没想透彻，所以好奇一问。

**Comment by firedtoad** [comment]
创建链接开销 应该和操作系统成正相关性 应用层没法干涉吧

**Comment by doublefox1981** [comment]
抱歉，这里的创建连接不是指os的那三次握手，指的是分配skynet内部连接id的过程。
