### ISSUE TITLE
mysql  查询返回全表的时候数据

### ISSUE THREAD

**Issue by yingnierxiao** [cloudwu/skynet#496]
The message to 1d is too large (sz = 28141198)   数据包太大
这个有什么解决方案么 ？限制查询返回结果的数量感觉要分多次也是多此一举

**Comment by cloudwu** [comment]
是不是不应该再回答（帮助解决）不更新到最新版本产生的问题？

**Comment by yingnierxiao** [comment]
更新到最新版本完，所有服务器一段时间后都出现 [:00000027] May overload, message queue length = 1264
提示，debug看:00000027	mqlen:1	task:1
我在找找看什么原因

**Comment by cloudwu** [comment]
我写了 一篇 blog 谈 overload 的问题

http://blog.codingnow.com/2016/05/skynet_proxy.html

**Comment by yingnierxiao** [comment]
linux 上面没这个overload的问题，不过mac上面出现，还在排除问题，怀疑是multicastd出了问题，刚刚开始mqlen的长度出现问题，后面导致其他服务器一起出现问题。
