### ISSUE TITLE
socket server half close problem

### ISSUE THREAD

**Issue by lparam** [cloudwu/skynet#50]
客户端发送一个数据请求包后，紧接着调用shutdown(fd, SHUT_WR)发送一个FIN，
socket server接受到FIN后就马上调用force_close关闭链接，导致响应包无法发送
到客户端，这种情况下，是不是应该让业务逻辑知道这个HALF CLOSE状态，在完成响应包的发送后再由业务逻辑主动关闭链接，而不是让socket server来做这个工作。

**Comment by cloudwu** [comment]
@lparam 目前的版本已经可以在收到客户端的 FIN 后发送完数据。
