### ISSUE TITLE
socket.start阻塞

### ISSUE THREAD

**Issue by yblunan** [cloudwu/skynet#500]
云大，请问下
socket 不能中途转让吗？
在另一个服务里start会一直阻塞
然后『socket: drop package ...』

**Comment by cloudwu** [comment]
可以，否则就不需要 socket.start 这个函数。你用错了，请自己 debug 。

ps. 如果之前的服务不再使用这个 socket, 最好调用 socket.abandon ，否则服务退出的时候会自动 close 。

**Comment by cloudwu** [comment]
https://gist.github.com/cloudwu/9ba552ed9bc87a34f8051e84a6ea0731

我修改了 testsocket.lua , 可以 nc 连接上后发一个 trans ，观察 socket 控制权转移的过程。

**Comment by yblunan** [comment]
这两天发现这一问题的规律，我在skynet.start里直接socket.skynet会阻塞，，目前我用dispatch的方式来处理就ok
还没有抽空 去测试你上面的testsocket.lua
但是我看到你在start里用了fork，，难道在start的coroutine里不行，必须在另一个coroutine里？


目前我用skynet在做一个非游戏项目
用着蛮爽的，谢谢云大
有个小意见，，timerout能否加cancel功能？

**Comment by cloudwu** [comment]
cancel 自己写就好了。

```lua
local timeout_handle = setmetatable({},{ __mode = "kv" })

function timeout(ti, f)
  local function tf()
    if not timeout_handle[tf] then
      f()
    else
      timeout_handle[tf] = nil
    end
   skynet.timeout(ti, tf)
   return tf
end

function cancel(tf)
  timeout_handle[tf] = true
end
```

**Comment by cloudwu** [comment]
1. 下次提 issue 请带 test case 。
2. skynet.newservice 会等对方 skynet.start 执行完才返回。
3. 请尽量自己查问题。

**Comment by yblunan** [comment]
多谢，初创公司，项目赶，人手少，请多见谅
