### ISSUE TITLE
datacenter的key设置问题

### ISSUE THREAD

**Issue by yksalun** [cloudwu/skynet#503]
local skynet = require "skynet"
local datacenter = require "datacenter"

skynet.start(function()
	datacenter.set("hello", "world")
	print(datacenter.get "hello")

	datacenter.set("hello", "world", "funny")
	print(datacenter.get("hello", "world"))	
end)

如果是这样用的话，第二次set的时候会报错，通过看实现:
	if select("#",...) == 0 then
		local ret = db[key]
		db[key] = value
		return ret, value
	else
		if db[key] == nil then
			db[key] = {}
		end
		return update(db[key], value, ...)
	end
得知：db[key]如果之前被设置过，再次调用时不会生成新的table，导致后面调用db[key]会报错。
是不是我的用法有问题呢？

**Comment by cloudwu** [comment]
你自己要规划好结构， 如果 hello.world 是一个分支（有子节点），那它就不能事后再修改为一个页节点。
