### ISSUE TITLE
cmaster.lua:36: Invalid serialize stream 9 (line:515)

### ISSUE THREAD

**Issue by lswzzz1** [cloudwu/skynet#507]
客户端发送的是已序列化的protobuf数据，这个错误的原因应该是agent.lua文件中register_protocol的unpack编写错误导致的，这里我传输二进制数据是否需要自定义一个c库供unpack调用？还是skynet已有自带的方法了？

**Comment by cloudwu** [comment]
在你不懂的时候，不要用 master/slave 模式。

**Comment by lswzzz1** [comment]
明白了，我将harbor设置为0解除了这个错误，但是我发送的所有数据skynet似乎都无法收到，我不知道是哪里出错了，在gate的handler.message我都无法捕获到信息

**Comment by MrChang0** [comment]
没有加数据长度
