### ISSUE TITLE
lua-skynet.c 中_cb 函数似乎多余的 lua_pushvalue

### ISSUE THREAD

**Issue by Astone-Chou** [cloudwu/skynet#508]
https://github.com/cloudwu/skynet/blob/master/lualib-src/lua-skynet.c#L42

在 lua-skynet.c : 38
lua_rawgetp(L, LUA_REGISTRYINDEX, _cb);
lua_rawgetp 实际上已经将 skynet.dispatch_message 推入栈中了.
似乎没必要在 lua_pushvalue, 

在 lua-skynet.c : 52
r == LUA_OK 之后直接返回了, 我看一下 lua_gettop(L) 是 2, 似乎没有将栈清理干净.

**Comment by cloudwu** [comment]
这是个特性。故意的。

**Comment by Astone-Chou** [comment]
哦, 如果后面用 L 的时候小心些, 确实可以省去 
lua_pushcfunction(L, traceback);
lua_rawgetp(L, LUA_REGISTRYINDEX, _cb);
这两句. 明白了, 多谢.
