### ISSUE TITLE
Add C++ support

### ISSUE THREAD

**Issue by feiyunw** [cloudwu/skynet#515]
对于C++项目迁移到skynet框架的情况，skynet应可提供支持C++的头文件。
可以采用类似lua.hpp的做法，将导出函数接口包含在extern "C"代码块中，例如：
extern "C" {
# include "lua.h"
# include "lualib.h"
# include "lauxlib.h"

}

**Comment by sanikoyes** [comment]
1、云大是c++黑，不会加的
2、这种支持你在你自己项目里include skynet头文件的时候处理好就行
