### ISSUE TITLE
git command in Makefile

### ISSUE THREAD

**Issue by feiyunw** [cloudwu/skynet#516]
在make目标文件时自动调用git命令更新代码，这不是恰当的做法，特别是在用于正规的项目版本发布过程中更应避免意外修改代码。
建议在Makefile中新增一个target专门处理更新代码的需求，例如make update，将编译目标文件和更新代码分离开来。

**Comment by cloudwu** [comment]
谢谢，建议已收到，不予采纳。

**Comment by hanxi** [comment]
为了时刻保持最新的`skynet`代码，杜绝提出重复的 `bug` 也是挺拼的。
