### ISSUE TITLE
proto空表传输相关问题

### ISSUE THREAD

**Issue by flyy3** [cloudwu/skynet#518]
云大，请教个问题

协议如下

```

bags_list 10 {
  response {
    equipments 0 : *equipment(id)
    props 1 : *prop(id)
  }
}

```

服务器传入的传输数据是下面的表

```
{
  equipments = {},
  props = {}
}
```

客户端收到的数据应该是

![](http://7xjt5x.com1.z0.glb.clouddn.com/empty3.png)

还是

![](http://7xjt5x.com1.z0.glb.clouddn.com/empty2.png)

客户端两种结果都出现了，skynet是否对传输的空表进行处理？

**Comment by lidashuang** [comment]
应该是客户端和服务端sproto版本不一样

**Comment by cloudwu** [comment]
请写一个 testcase 贴在 gist 上，encode/decode 一下你给的例子。用 github 的 sproto 项目跑一下结果看有没有问题。

**Comment by flyy3** [comment]
@lidashuang  根据你说的，解决问题了。谢谢。也谢谢云大
