### ISSUE TITLE
多播消息打包有内存泄漏？

### ISSUE THREAD

**Issue by Garfielt** [cloudwu/skynet#519]
多播使用的过程中发现内存占用量不断上升，debug_console下cmem对应服务的内存占用量不断增大，[lua-multicast#L22](https://github.com/cloudwu/skynet/blob/master/lualib-src/lua-multicast.c#L22)中ret指针未发现free的地方，在[lua-multicast:L110](https://github.com/cloudwu/skynet/blob/master/lualib-src/lua-multicast.c#L110)处增加skynet_free(pack)后内存增量消失，standalone模式下运行，不知其他模式又无影响？

**Comment by cloudwu** [comment]
谢谢，这似乎是个历史问题。和之前一次 bugfix 有关，见 pr #220 。

不过,简单加一句 free 还有点小问题。具体见上面的 bugfix commits  。

**Comment by Garfielt** [comment]
感谢云大开源了这么优秀的框架，使用学习受益良多！赞！
