### ISSUE TITLE
snlua_init() handle_id optimization

### ISSUE THREAD

**Issue by feiyunw** [cloudwu/skynet#520]
Here is the patch for service-src/service_snlua.c:
@@ -1,4 +1,5 @@
 #include "skynet.h"
+#include "skynet_server.h"
 
 #include <lua.h>
 #include <lualib.h>
@@ -150,10 +151,7 @@
 	char * tmp = skynet_malloc(sz);
 	memcpy(tmp, args, sz);
 	skynet_callback(ctx, l , launch_cb);
-	const char * self = skynet_command(ctx, "REG", NULL);
-	uint32_t handle_id = strtoul(self+1, NULL, 16);
-	// it must be first message
-	skynet_send(ctx, 0, handle_id, PTYPE_TAG_DONTCOPY,0, tmp, sz);
+	skynet_send(ctx, 0, skynet_context_handle(ctx), PTYPE_TAG_DONTCOPY,0, tmp, sz);
 	return 0;
 }

**Comment by cloudwu** [comment]
It makes no sense, and I don't want to include `skynet_server.h` in C service .
