### ISSUE TITLE
web server 文件下发

### ISSUE THREAD

**Issue by hyd998877** [cloudwu/skynet#522]
local function read_file( path )
    local filename = www .. path
    local file = io.open(filename, 'rb')
    if file then
        local value = file:read('*all')
        io.close(file)
        res_header["Content-Type"] = mimetypes.guess(filename or '')
        return value, header
    end
end
https://github.com/hyd998877/skynet_webserver.git
在web server上添加了个文件处理，作为web服务器，如果同时下发几个100k文件，速度非常慢，这是什么原回呢，@云风，是否可以解决下

**Comment by cloudwu** [comment]
有没有分析数据看卡在哪里？

ps. 你用 `filename = www ..  path` 有安全问题。攻击者在 path 里加几个 .. 你就完蛋了。

**Comment by hyd998877** [comment]
我分析了下，是不是在send_socket这儿，
发送文件，第一次s->high.head == NULL && s->low.head == NULL的时候
write不能一次写完，则进入了send_list的逻辑
这时socket线程只有一个，又同时并发多个文件，一个文件在多次调用send_list的时候，造成了抢占

不知道是不是这个原因，如果有空，可以使用https://github.com/hyd998877/skynet_webserver.git这个例子测试一下

恢常感谢指出的安全问题

**Comment by zxfishhack** [comment]
使用ab作并发测试，并未发现skynet写的webserver与nginx本身有特别大的差别。

**Comment by cloudwu** [comment]
有没有实际数据证明问题在上面？

才几个 100K  文件，IO 量这么小，不会在底层 IO 处理上有问题。

**Comment by zxfishhack** [comment]
单机测试时，有较为明显的差距

以下为skynet webserver:
Server Software:        
Server Hostname:        127.0.0.1
Server Port:            9080

Document Path:          /b_about.png
Document Length:        694194 bytes

Concurrency Level:      20
Time taken for tests:   0.973 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      694262000 bytes
HTML transferred:       694194000 bytes
Requests per second:    1028.11 [#/sec] (mean)
Time per request:       19.453 [ms] (mean)
Time per request:       0.973 [ms] (mean, across all concurrent requests)
Transfer rate:          697048.95 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       1
Processing:     5   19   5.6     19      42
Waiting:        2   17   5.0     17      40
Total:          6   19   5.6     19      43

Percentage of the requests served within a certain time (ms)
  50%     19
  66%     21
  75%     22
  80%     23
  90%     27
  95%     30
  98%     34
  99%     36
 100%     43 (longest request)

以下为nginx
Server Software:        nginx/1.4.6
Server Hostname:        127.0.0.1
Server Port:            9080

Document Path:          /b_about.png
Document Length:        694194 bytes

Concurrency Level:      20
Time taken for tests:   0.094 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      694440000 bytes
HTML transferred:       694194000 bytes
Requests per second:    10673.50 [#/sec] (mean)
Time per request:       1.874 [ms] (mean)
Time per request:       0.094 [ms] (mean, across all concurrent requests)
Transfer rate:          7238382.56 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       1
Processing:     1    2   0.8      2       7
Waiting:        0    0   0.4      0       4
Total:          1    2   0.8      2       7

Percentage of the requests served within a certain time (ms)
  50%      2
  66%      2
  75%      2
  80%      2
  90%      2
  95%      3
  98%      6
  99%      6
 100%      7 (longest request)

**Comment by firedtoad** [comment]
10倍不是差距么？？

2016-06-22 18:04 GMT+08:00 zxfishhack <notifications@github.com>:

**Comment by firedtoad** [comment]
你不能这么算 nginx  用的是aio 处理静态文件 你用的是 lua 自带IO系统 不慢才怪

2016-06-22 18:52 GMT+08:00 哈蟆 <dietoad@gmail.com>:

**Comment by firedtoad** [comment]
你应该把相同文件的请求缓存住(只要文件时间戳没有发生变化) 你这样同时对一个文件多次请求导致多次读取 如果不慢就没天理了

2016-06-22 18:54 GMT+08:00 哈蟆 <dietoad@gmail.com>:

**Comment by zxfishhack** [comment]
此服务器的信息与node.js的基本网页文件服务器的性能差不多了

Server Software:        NodeJs(v4.2.6)
Server Hostname:        127.0.0.1
Server Port:            9080

Document Path:          /b_about.png
Document Length:        694194 bytes

Concurrency Level:      20
Time taken for tests:   0.944 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      694342000 bytes
HTML transferred:       694194000 bytes
Requests per second:    1059.49 [#/sec] (mean)
Time per request:       18.877 [ms] (mean)
Time per request:       0.944 [ms] (mean, across all concurrent requests)
Transfer rate:          718409.19 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       1
Processing:     7   19   2.7     18      43
Waiting:        7   18   2.7     18      43
Total:          8   19   2.8     18      43

Percentage of the requests served within a certain time (ms)
  50%     18
  66%     19
  75%     20
  80%     20
  90%     22
  95%     23
  98%     26
  99%     29
 100%     43 (longest request)

正如firedtoad所言，要提高性能，需要增加缓存策略和aio读取。

**Comment by cloudwu** [comment]
如果是细微的优化很有很多可以做的。不过我觉得不在极端需求下意义不大。

除了 cache 住文件，skynet 层面可以不用 socket.write 去写字符串（那样会多拷贝一次内存，从 lua 到 skynet socket 层）；你可以把文件读到一个 C buffer 里，然后用 socket.write 写 lightuserdata + len （这样可以减少一次内存拷贝）。

这个 C buffer 由 malloc 分配即可，skynet socket 层会调用 free 。

更极端的优化可以自定义 buffer 的分配释放，用引用计数来管理 buffer 。这样把同一个文件发到多个 socket 可以更快（减少更多的内存拷贝）。这个技术有个用 skynet 做视频广播的同学用过。方法是使用 `socket_server_userobject` https://github.com/cloudwu/skynet/blob/master/skynet-src/socket_server.h#L64 这个 C API 。
