### ISSUE TITLE
lua-bson把字典当作array序列化时会出错

### ISSUE THREAD

**Issue by t0350** [cloudwu/skynet#524]
https://github.com/cloudwu/skynet/commit/098d44162b8df9d8001f99213b3ec45668203c55#diff-5578de472bc9b4f73b3322adf3f65a7fR499
云风，这里is_rawarray判断分支，会误把a = {[1] = 1, [2] = 2, [4]=4} 当作array，然后pack_array处会报错。之前is_rawarray会走pack_dict流程所以没问题。

**Comment by cloudwu** [comment]
这是个特性。以前没有检测出来是 bug 。

**Comment by cloudwu** [comment]
如果你要编码一个字典，在 bson 里，需要保证 key 都是字符串。所以你应该用 a = { ['1'] = 1, ['2'] = 2 , ['4'] = 4 }

**Comment by t0350** [comment]
就是现在序列化，依赖提供了__len方法的视为array，提供了__pairs方法的视为document。另外两个情况，需要自己保证要么是连续的数组，要么保证是字符串为key的字典？

**Comment by cloudwu** [comment]
对。

同时提供了 `__len` 和 `__pairs` 也视为数组。

如果能检测出数组部分不连续或有额外的字符串 key ，会尽量按字典 encode 。但（出于性能取舍）并不保证一定检测出来。

**Comment by t0350** [comment]
好吧，这样是明确些。
就是本来现在是直接把lua table扔给bson，可能要改成构造个table给bson。

**Comment by cloudwu** [comment]
就你的需求，是不是直接给个metatable, 把 `__pairs` 设置为 next 最简单？

另外，什么情况下有这样的数据？

**Comment by cloudwu** [comment]
如果需求合理，我可以考虑以下在 `is_rawarray()` 里进一步增加一次 O(n) 遍历，查找是否有空洞。

**Comment by t0350** [comment]
是打算这样做。就是数据发到mongodb服务后，mongodb服务存盘时就会。

**Comment by cloudwu** [comment]
为什么数据里会有不连续的数字下标？

**Comment by t0350** [comment]
就是确实存了{[1] = 1, [2] = 2, [4] =4}(这里当然也能故意改为100, 102, 104来绕开)。用的时候就是把它当作map，并没有当作array来用。

**Comment by cloudwu** [comment]
但是 mongodb 不是要求 document 的 key 是 cstring 么？并不能和 lua table 一一对应啊。比如也不能用 true/false 做 key 。

**Comment by cloudwu** [comment]
所以，即使在 `is_rawarray()` 里遍历，找到空洞，把它当字典去编码也无法解决你的问题。在 decode 的时候，这些 key 也会变成字符串的。即，你改成 101, 102, 104 并不能解决问题。decode 后会变成 '101'  '102'  '104' 。

在  bson 规范里，无法区分单个 key 的类型是否是整数。

**Comment by t0350** [comment]
是恩。从bson load回数据时是会依赖定义文件作转换的。原来是lua table直接扔给bson，没有做一层转化，按现在的修改是要做一层。
现在是符合spec，只是改起来必须绕一次(加__pairs绕开就好)，现在这样比之前意义明确就好。is_rawarray那做多一次遍历判断也没有必要的感觉。
