### ISSUE TITLE
so文件在skynet中无法调用

### ISSUE THREAD

**Issue by flyy3** [cloudwu/skynet#529]
skynet调用so文件出问题了，请教下云大。
自己写了一个libastar.so文件，so文件源码是cpp文件。makefile文件如下：

```
CC = g++
CFLAGS := -Wall -O3 -std=c++11 -DLUA_COMPAT_ALL

OBJS = AstarControl.o BinaryHeap.o QuickAStar.o luaopen_astar.o
LIB = libastar.so

INCLUDES = -I ./../include/lua

all: $(LIB)

%.o: %.cpp
    $(CC) $(CFLAGS) -fpic -c $< -o ./src/$@ $(INCLUDES)

$(LIB) : $(OBJS)
    rm -f $@
    g++ -shared -o $@ $(OBJS) -llua
    rm -f $(OBJS)
    mv $(LIB) ./../bin/$(LIB)

tags :
    ctags -R *

clean:
    rm -f $(OBJS) $(TARGET) $(LIB)

```

直接用lua执行lua文件可以正常执行，lua文件代码如下

```
local Astar = require "libastar"

local handle = Astar.new()
Astar.initMap(handle, 4, 4, 
    { 1, 1, 2, 3, 3, }, 
    { 1, 3, 3, 2, 3, })
```

但在skynet中,调用失败，利用调用服务来测试testsolib.lua，文件代码如下。

```

local skynet = require "skynet"
local Astar = require "libastar"

local CALL = {}

function CALL.open(conf_in)

  local handle = Astar.new()
  Astar.initMap(handle, 4, 4, 
    { 1, 1, 2, 3, 3, }, 
    { 1, 3, 3, 2, 3, })

end

skynet.start(function()
   skynet.dispatch("lua", function(session, address, cmd, ...) -- luacheck: no unused args
    local f = assert(CALL[cmd], "unknown control_master call command " .. cmd)
    skynet.ret(skynet.pack(f(...)))
  end)
end)

```

libastar.so放luaclib目录下，在example/main.lua中加入如下代码,执行testsolib.lua文件

```
    local testdo = skynet.newservice("testsolib")
    skynet.call(testdo, "lua", "open", {})
```

报错如下：
![a8d6c357-4584-400c-8029-24c5949a428b](https://cloud.githubusercontent.com/assets/8134609/16892834/e3b8bc2a-4b53-11e6-876e-462703a14bf5.png)

**Comment by cloudwu** [comment]
1. 你应该 print 一下 AStar 的内容看里面是什么，现在你的出错信息指没有 AStar.new 这个方法。

2. 通常不应该把 -llua 链入动态库。http://lua-users.org/wiki/BuildingModules

**Comment by flyy3** [comment]
谢谢云大。按你给的建议，查了些资料，修改了makefile。最终可运行的makefile为
CC = g++
CFLAGS := -Wall -O3 -std=c++11 -DLUA_COMPAT_ALL
LDFLAGS = -bundle -undefined dynamic_lookup -all_load
OBJS = AstarControl.o BinaryHeap.o QuickAStar.o luaopen_astar.o
LIB = libastar.so

BUILD_CFLAGS =      -I/skynet_path/skynet/3rd/lua -I/usr/local/include

all: $(LIB)

%.o: %.cpp
	$(CC) -c $(CFLAGS) $(BUILD_CFLAGS) -o $@ $<

$(LIB) : $(OBJS)
	rm -f $@
	g++ $(LDFLAGS) -o $@ $(OBJS)
	rm -f $(OBJS)
	mv $(LIB) ./../bin/$(LIB)

tags :
	ctags -R *

clean:
	rm -f $(OBJS) $(TARGET) $(LIB)
