### ISSUE TITLE
【mongo】在存储user对象的时候，有一定几率出现：Invalid value type : nil

### ISSUE THREAD

**Issue by wwxx** [cloudwu/skynet#533]
近日使用最新的skynet的时候，发现服务器上在存储玩家数据的时候有一定几率抛出如下的异常：
此异常并非100%的重现，偶尔可能会出现连续几次都不成功。

这部分存储代码一直没有改变过，不确定是否是因为近日同步了最新skynet源码导致。

详细原因还在筛查。请各位大神给点思路，谢谢。

异常原文为：
:0000000c: [Sat Sep  3 00:44:04 2016] [-] [DB_User.update] user_id = 57ca1914813143884a56cb1b, user_name = Frankpual, passport = 57ca191428c1aae4690009e6
:0000000c: [Sat Sep  3 00:44:04 2016] [-] ../lib/skynet/lualib/mongo.lua:362: Invalid value type : nil
:0000000c: [Sat Sep  3 00:44:04 2016] [-] stack traceback:
	./service/database.lua:190: in function <./service/database.lua:188>
	[C]: in function 'bson.encode'
	../lib/skynet/lualib/mongo.lua:362: in method 'update'
	./lualib/db/db_user.lua:166: in function 'db_user.update'
	[C]: in function 'xpcall'
	./service/database.lua:188: in upvalue 'f'
	../lib/skynet/lualib/skynet.lua:109: in function <../lib/skynet/lualib/skynet.lua:103>
:00000024: [Sat Sep  3 00:44:04 2016] [-] [watchdog] IN command = get_user, subcmd = table: 0x7ffad0fdcf80

堆栈部分涉及的源码为：
function DB_User.update(user)
	log.i(string.format('[DB_User.update] user_id = %s, user_name = %s, passport = %s', 
			user._id, user.user_name, user.passport))
	assert(user._id and user.user_name)

	local collection = col_get_func('users', user.user_name or 'user_name')

	collection:update({_id = user._id}, user, true)
end

**Comment by cloudwu** [comment]
1. 检查是否有编码数组时，数组内有空洞 (nil)

2. 在 bson c 代码中抛出异常前多加 log , 确认被编码的东西是什么， dump 出来分析。

**Comment by wwxx** [comment]
感谢云大的回复

我自己测试下了
当我代码是这样写的时候会复现这个异常：
   b = bson.encode {
        ax = {"xx", nil, "zz"},
    }

而如果是写为：
   b = bson.encode {
        ax = {[1] = "xx", [2] = nil, [3] = "zz"},
    }
这种情况bson就不会异常，请问这两种写法有什么不同么？

**Comment by t0350** [comment]
一个是SETLIST，一个是SETTABLE方式构造，可以看内部ax的rawlen返回结果是不一样的。
如果是数组应该指定__len方法，且保证没有空洞，不然直接bson.encode可能出错。。

**Comment by tangyiyang** [comment]
```Lua
static void
pack_array(lua_State *L, struct bson *b, int depth, size_t len) {
	int length = reserve_length(b);
	size_t i;
	for (i=1;i<=len;i++) {
		char numberkey[32];
		size_t sz = bson_numstr(numberkey, i - 1);
		const char * key = numberkey;
		lua_geti(L, -1, i);

		if(!lua_isnil(L, -1)) {
			append_one(b, L, key, sz, depth);
		}

		lua_pop(L, 1);
	}
	write_byte(b,0);
	write_length(b, b->size - length, length);
}
```

pack array的时候，简单粗暴的判空可以么？

**Comment by wwxx** [comment]
按照tangyiyang的修改方式，进一步尝试了如下测试代码，测试通过：
    b = bson.encode {
        ax = {"xx", nil, "zz"},
    }
    t = b:decode()
    for k, v in pairs(t.ax) do
        print(k)
        print(v)
    end

**Comment by cloudwu** [comment]
如果需要编码"空"，一定要使用 bson.null , 而不能使用 lua 自己的 nil .
