### ISSUE TITLE
require "clientsocket" 后 io.read()行为改变

### ISSUE THREAD

**Issue by RockyDong** [cloudwu/skynet#539]
io.read()等待读取一行命令行的输入，以回车结束；
require "clientsocket"后，io.read() 需要先按回车，然后输入，再按两次回车，输入才会生效。
请问这是怎么回事？

**Comment by RockyDong** [comment]
--测试代码
package.cpath = "./luaclib/?.so;"
--local socket = require "clientsocket"
local CMD = {}
local loop_flag = true

function CMD.exit(...)
    print("reach the end...")
    loop_flag = false
end

local function start(cmd, ...)
    local f = assert(CMD[cmd], "command " .. cmd .. " not found")
    f(...)
end

while loop_flag do
    local cmd = io.read()
    local ok, status = pcall(start, cmd)
    if not ok then
        print(status)
    end
end
--------------------------测试结果---------------------
注释require "clientsocket"前：
dongsongtao:skynet ((v1.0.0-rc5))$ lua examples/loop_test.lua 
exit(回车)
(回车)
(回车)
examples/loop_test.lua:12: command  not found
(回车)
exit(回车)
(回车)
reach the end...
注释require "clientsocket"后：
dongsongtao:skynet ((v1.0.0-rc5))$ lua examples/loop_test.lua 
exit(回车)
reach the end...

**Comment by cloudwu** [comment]
不要使用 clientsocket ， 仅用于 examples 。请使用更成熟的 socket 库或自己实现。

**Comment by zhouyanlt** [comment]
#### 这里有解答：
[skynet clientsocket 导致 io.read 无法正确工作的问题](http://blog.csdn.net/gneveek/article/details/78940693)
