### ISSUE TITLE
clusterproxy.lua  问题！！！！

### ISSUE THREAD

**Issue by sctangqiang** [cloudwu/skynet#543]
云大， 你好：
    这个模块的使用能写个例子吗？ 现在有两点疑问， 1.映射消息没有释放内存， 要防止内存泄露， 请问下这个通过skynet.ret或是skynet.rawcall发送后也需要吗？；2.如果node和address每条代理消息不一样应该怎么处理？。
   我自己写了个proxy，但是每次都会unpack和pack， 看了这个例子后， 希望改进。

**Comment by cloudwu** [comment]
一般 lua 里收到的外部消息，都是一对 lightuserdata/size , 不需要再 lua 层面释放，处理完后，在 C 里会释放；但是用这个模式， C 就不释放了 。

skynet.rawcall 返回的消息实际是通过 response 类型发进来的，和 skynet.call 不同，这个消息不做任何解包处理，还保留了 lightuserdata ；之后通过 skynet.ret 把 lightuserdata/size 又转发出去。

这个过程可以节省把 skynet.call 的返回值解包，以及把解包后的数据重新打包的过程。

我不太懂第 2 个问题。如果是说想根据包的内容来分发消息的话，你可以把 rawcall 的返回解开，然后探查里面的内容。但是不用重新打包，还是可以转发前面说的 lightuserdata 的。

另外，可以考虑另外实现一个（修改出一个版本） unpack, 只解开包的第一个元素，这样可能会省一些。

**Comment by sctangqiang** [comment]
恩， 明白多谢云大；懂的第二个问题：怎么将你的代理改造下， 当在每个消息中添加目的svr_id和对应节点上服务地址后，实现每个消息转发到不同的节点； 云大你说明后我已经知道怎么改了
