### ISSUE TITLE
debug console是否支持服务字符串别名？？！！

### ISSUE THREAD

**Issue by sctangqiang** [cloudwu/skynet#544]
在用debug_console做外部命令工具时，觉得用数字地址不灵活， 在实际开发中一些主要的服务一般都会设置别名， 这样方便记忆以及做命令行控制工具。强烈建议云大添加这个功能的支持。

**Comment by PolarSnow** [comment]
不支持。同一个服务可以启动多次，很多时候没有必要给他们命名。比如agent

**Comment by cloudwu** [comment]
debug console 支持用 http GET 去操作，你可以额外开发 web 界面的控制端。
