### ISSUE TITLE
关于客户端断开和snax.gateserver服务的网络连接的问题

### ISSUE THREAD

**Issue by korialuo** [cloudwu/skynet#545]
local handler = {}
function handler.disconnect(fd)
   ...
end
gateserver.start(handler)

请问云风老师，当网络连接断开时，这个回调函数会被调用2次，是我哪里弄错了吗？

**Comment by cloudwu** [comment]
自带的 example 里不会调用两次。

**Comment by korialuo** [comment]
好的，谢谢云风老师，我对比检查一下。

**Comment by korialuo** [comment]
找到问题了，我在disconnect回调方法里调用了gateserver.closeclient(fd)，导致重复回调了disconnect方法。看来是我理解错了。

**Comment by feifeigd** [comment]
问题解决了，是不是要close？
