### ISSUE TITLE
cluster 问题， 紧急！紧急！！！！

### ISSUE THREAD

**Issue by sctangqiang** [cloudwu/skynet#547]
使用cluster遇到进程间通信连接暴涨的问题？  进程启动后刚开始很正常两个进程间只有两个连接， 如果有程序访问还很正常， 放置一段时间后（只有进程间的心跳）就会出现连接数暴涨， 我的虚拟机配置 cpu 1核， 然后我的skynet进程开了8个线程。

**如果需要代码，我可以单传过去， 可以轻松部署。**

**Comment by morzz** [comment]
目前在用 cluster ，尚未发现此问题（开发中的项目），怀疑是使用的原因，方便的化可以发份代学习一下
