### ISSUE TITLE
对 cluster.call 的调用无法得知到底是连接失败，还是接口调用失败

### ISSUE THREAD

**Issue by morzz** [cloudwu/skynet#548]
目前项目中使用了 cluster，我这边期望，在网络异常时(目标集群节点重启)能够阻塞当前调用，直到连接恢复后在返回，对于调用异常来说（调用了不存在的接口或者出现未曾预料到的错误时），能够返回调失败的结果，然后目前在执行 cluster.call 时，却无法分别错误到底是网络异常还是调用异常（总是返回 ../skynet/lualib/skynet.lua:375: call failed ），还请云大和各位大神指教, 谢谢

**Comment by cloudwu** [comment]
暂时无法区分。

如果在目前结构上想做到这点，我个人建议这样：

在 cluster 的接收请求的那边实现一个永远不返回的接口，一开始你就调用它，由于永不返回，所以调用不可能因为链接断开以外的任何原因异常。

然后在捕捉到异常后，设置一个标记。其他调用在 error 后可以检查这个标记。

这个方法有可能误判一次（时序问题），但是最终一定能判断出连接是否曾断开过。

**Comment by morzz** [comment]
感谢云大的回复：）

**Comment by morzz** [comment]
在云大回复的基础上进一步想了一下，可以在捕获到 cluster.call 之后通过立即调用一个永远不会失败的接口来对异常进行区分，伪代码如下


local node
local address = ".performer"
function  cluster_call(...)
    while true do
        local rets = table.pack(pcall(cluster.call, node, address, ...))
        if rets[1] then
            return table.unpack(rets, 1, rets.n)
        else
            while true do
                local ok = pcall(cluster.call, node, address, "test")
                if ok then
                    return false, "call failed"
                else
                    skynet.sleep(300)
                end
            end
       end
    end
end

-- test cluster_call
local ok, msg = cluster_call()
if ok then
   -- ok
else
  skynet.error(msg)
  assert(false)
end

**Comment by morzz** [comment]
上面的代码同样存在误判的可能，还需要在 test 接口中返回一个时间戳（节点的启动时间，初次建立连接后双方进行同步）或一个动态标记，这样在调用 test 之后进一步判断返回值与本地记录的标记是否一致，如果一致说明 cluster.call 是 call failed，反之则意味着网络异常。。。

**Comment by cloudwu** [comment]
不要贴图片啊。github 可以和方便的帖代码。

**Comment by cloudwu** [comment]
clusterd 其实完全能区分是网络断开还是对方抛出 error 。问题在于目前已有的框架下，发起 rpc 的服务到 clusted 之间丢掉了这个信息。如果自己改造 clusterd 传过来这个信息的话，可以做的好一些。我在考虑是否有办法加上这个特性，而不改变现在的接口。

用再次查询的方式有个问题，socket channel 会在断开后，下次请求时重新建立连接。往往这个时候后续的查询就连上了。

不过，我的个人观点：

内部网络断开，应该是一个低频事件，而且一旦发生不应该被藏起来。

如果是主动行为（例如更新版本，重启等等），应该在上层建立一套机制来支持。比如有额外的手段监控对方运行是否良好等等。

**Comment by cloudwu** [comment]
如果你想试试的话，

https://github.com/cloudwu/skynet/blob/master/service/clusterd.lua#L85

```lua
function command.req(...)
	local ok, msg, sz = pcall(send_request, ...)
	if ok then
		if type(msg) == "table" then
			skynet.ret(cluster.concat(msg))
		else
			skynet.ret(msg)
		end
	else
		skynet.error(msg)   -- 当 msg 为 sc.error 时表示网络异常
		skynet.response()(false)
	end
end
```

这里如果 msg == sc.error 就证明是网络问题。如果有办法传递给调用方，那么就可以让调用方感知到。

**Comment by morzz** [comment]
如果 skynet.response()(false, {badcall=true})，在传入 false 时，能够用第二个参数替代默认的错误数据，那就方便的多了

**Comment by 253980289** [comment]
这种调用还需要考虑一个重复调用的问题，如果上次发起调用接收方已成功接收，正在处理过程中网络断开，调用方检测到网络异常而在网络恢复时重新发起调用，而该请求是否存在被多次执行的情况？
