### ISSUE TITLE
求救，skynet mem+cmem统计出的内存是实际进程内存的1/2

### ISSUE THREAD

**Issue by gustars** [cloudwu/skynet#550]
目前一台物理机开三个虚拟服务器，跑1个月的时间，skynet进程差不多60G左右，但是mem+cmem统计的内存只有30G。一台物理机日活跃大概有5000人，同时在线400人。

**Comment by cloudwu** [comment]
所有内存都是由 jemalloc 接管，
使用 cmemory.dumpinfo 看 jemalloc 的报告。
https://github.com/cloudwu/skynet/blob/master/service/cmemory.lua#L4

**Comment by gustars** [comment]
___ Begin jemalloc statistics ___
Version: 4.0.4-0-g91010a9e2ebfc84b1ac1ed7fdde3bfed4f65f180
Assertions disabled
Run-time option settings:
  opt.abort: false
  opt.lg_chunk: 21
  opt.dss: "secondary"
  opt.narenas: 160
  opt.lg_dirty_mult: 3 (arenas.lg_dirty_mult: 3)
  opt.stats_print: false
  opt.junk: "false"
  opt.quarantine: 0
  opt.redzone: false
  opt.zero: false
  opt.tcache: true
  opt.lg_tcache_max: 15
CPUs: 40
Arenas: 160
Pointer size: 8
Quantum size: 16
Page size: 4096
Min active:dirty page ratio per arena: 8:1
Maximum thread-cached size class: 32768
Chunk size: 2097152 (2^21)
Allocated: 38871949896, active: 48147595264, metadata: 1742642176, resident: 55461556224, mapped: 68742021120
Current active ceiling: 48176300032

Merged arenas stats:
assigned threads: 27
dss allocation precedence: N/A
min active:dirty page ratio: N/A
dirty pages: 11754784:1360730 active:dirty, 1273227 sweeps, 4774074 madvises, 12969037 purged
                            allocated      nmalloc      ndalloc    nrequests
small:                    36123689544 123494228571 123145671207 191815717056
large:                     2156339200    166447660    166412918    172121586
huge:                       591921152         2817         2667         2817
total:                    38871949896 123660679048 123312086792 191987841459
active:                   48147595264
mapped:                   68727341056
metadata: mapped: 1729974272, allocated: 2255232

**Comment by gustars** [comment]
感谢云风百忙回复，从日志上看，分配的和占用的对不上，一开始有怀疑jemalloc有问题，后面编译去掉jemalloc,用了一台物理机跑了一段时间也是这样的情况

**Comment by gustars** [comment]
skynet尝试过几个版本，包括最新的版本，都是一样的

**Comment by gustars** [comment]
游戏现在大概开了60台物理机，内存的问题排查了一段时间了，没有取得进展，这样导致迁移到云主机很困难（云主机内存太贵了），希望云风能够帮忙指点下排查的方向

**Comment by cloudwu** [comment]
你贴的里面不是写了  mapped: 68742021120 么。

管理内存不是切蛋糕，你切 10 个字节就少 10 个字节。

**Comment by cloudwu** [comment]
另外，云主机不是内存太贵，是整个性价比低而已。本来虚拟化本身就一定会给原本的硬件的性价比上打个折扣（即你买 10000 块钱应该获得的性能，有 2000 到 4000 浪费在虚拟化上了。

如果单台机器上跑多个虚拟机更加是：本来一套硬件上只需要一份操作系统占用的资源，现在变成了多套。

然后卖虚拟机的商家还需要利润养活自己。这些钱肯定是从你这么赚的啊。如果云主机成本更低，那才是奇怪了。

**Comment by gustars** [comment]
谢谢答复，jemalloc参数看起来是没有问题的，只是以前不确定，差距太大了。后续先从业务上优化一轮把内存降下来
