### ISSUE TITLE
harbor 集群本地最多只支持256个节点有点少？

### ISSUE THREAD

**Issue by abaelhe** [cloudwu/skynet#551]
。

**Comment by finaldie** [comment]
@abael 关于吐糟, 建议给出具体异常报错,系统环境信息,skynet版本信息, 如有可能并附加PR去fix, 更有助于项目良好发展 :)

**Comment by findstr** [comment]
多嘴说一句， so不是本来就应该-fPIC么

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/wiki/Cluster  先读文档。看不同方案的适用范围。

**Comment by abael** [comment]
关注重点:  cluster 的伸缩空间。
如果comment不能有助skynet的提升改进, 请莫费话。
槽是避免再有用户踩到 -rdynamic。开源不是开吵。

**Comment by cloudwu** [comment]
skynet 的 harbor 不是为集群设计的。
