### ISSUE TITLE
云大能否加上Raft投票协议避免单master故障 支持配置中心？

### ISSUE THREAD

**Issue by abaelhe** [cloudwu/skynet#552]
。

**Comment by abael** [comment]
可以参考 Baidu的iNexus设计, 不过百度开源iNexus实现的Raft协议不完备。

**Comment by cloudwu** [comment]
这些不应成为 skynet 的一部分，而应该单独子项目开发。

如果你有兴趣可以搞，开发过程中碰到底层缺乏支持的地方可以提出要求。

**Comment by wsd1** [comment]
skynet是个混合语言非阻塞网络程序框架，的确没必要变成个要你命3000。我觉得etcd挺好的，标准用途，专注实现一致性。
