### ISSUE TITLE
skynet 有支持 websocket 的打算吗？

### ISSUE THREAD

**Issue by chuenlungwang** [cloudwu/skynet#554]
现在 h5 游戏越来越多，而 h5 支持的长连接只有 websocket ，请问云大：skynet 可以加上对 websocket 作为通讯协议底层的支持吗？我们公司的棋牌游戏在需要 websocket 的时候是对 socket.lua 上加了新的一层，以及修改 lua-netpack.c 文件加入 websocket 解码。有没有更加通用的方法，或者支持协议对上层透明？

**Comment by cloudwu** [comment]
websocket 并不需要核心层提供额外的支持。你能自己写不就已经完成了？
