### ISSUE TITLE
一个特殊的需求需要毫秒内任务

### ISSUE THREAD

**Issue by yingnierxiao** [cloudwu/skynet#559]
skynet.sleep(0)的话即使空运行也会出现cpu过高的情况。有没办法优化呢？

**Comment by cloudwu** [comment]
另外写一个服务常开，让它用更高精度去 usleep（在这个服务里，sleep(0) 的后面接着 usleep 更短的时间）, 然后由这个服务向你的服务提供高精度定时订阅服务。

**Comment by yingnierxiao** [comment]
好的

**Comment by cloudwu** [comment]
注意，这样的一个高精度定时器订阅服务会占据一个 skynet 的一个 work thread ，所以这样使用的时候，建议在配置文件里多配置一个 work thread 。
