### ISSUE TITLE
skyent.call redis.connect导致游戏服开不起来问题

### ISSUE THREAD

**Issue by albus0x01** [cloudwu/skynet#560]
服务器，每个服一个进程，每个进程会连接32个redis实例。
一台物理服务器可开多个服。
但最近一台物理服开了进57个服，碰到一个redis的奇怪问题。
同一台物理服批量开服时，会有不少服卡在了redis.connect这个地方。（每个服启动的时候间隔为3秒）
导致游戏服开不起来，而且也没有报错。
但把服主动关闭后，再手动开就可以开起来（虽然有部分服还是会开不起来，但多试几次就可以）。
检查过redis服务器一切正常。
启动代码
```
for index, v in pairs(db_conf.roledb) do
	local db = skynet.newservice("roledbd", index)
	skynet.call(db, "lua", "open",v)
end
```
roledbd.lua
```
function command.open( conf )
	dbcon = redis.connect(conf) --目前知道堵在了这个地方。
	return true
end
```
还有我们处理关服是没有主动去关闭redis的连接。
~~求解。。。

**Comment by firedtoad** [comment]
好像单台机器不应该启动那么多服务

大跃进都过去快60年了

还有人有多大胆地有多大产的想法的人存在么

**Comment by cloudwu** [comment]
显然你应该用 tcpdump 先查 tcp 连接的原因啊。

当然楼上说的对，你一台机器启动 57 个进程么？应该改设计啦。每个进程都去连 32 个 redis 连接不淡疼么？就算你不合成一个进程，也应该共用一个和数据库交互的服务啊。

**Comment by cloudwu** [comment]
嗯，我觉得你可以一个玩家一个数据库，然后所有玩家构成一个数据库集群，可以保证良好的数据隔离性。（这是反讽）

**Comment by xtime2100** [comment]
检查下redis所在机器支持的最大连接数数量，redis自身的连接数控制和操作系统的最大描述符限制。

**Comment by albus0x01** [comment]
@xtime2100 连接数和操作系统的最大描述符限制是第一个检查的，没有超过。
@cloudwu tcpdump也很早就查过，这个连接只是很短的时间连不上。
至于为什么要放到一台，因为是老服人少，运营又不希望合服太频繁，所以把部分迁移到一台。
但其实迁移后，这台也没啥压力。至于数据库的独立服务也很早就做了，已经在线上跑了。
只是觉得奇怪redis.connect为什么没有超时，而系统也是没有压力，所以抛出先前遇到的问题来。

**Comment by cloudwu** [comment]
正确的做法是，把这些进程合成一个。不应该把因为运营需要而展示给玩家的“服” 按进程分离。

所谓分服合服都是运营的需求，属于开发需求之一，不应该被这个影响技术上的设计。如果按这种做法推导，单机游戏要联网的话，就变成一个用户一个服了。

如果你们早就做了 “数据库的独立服务” 就不应该同一台机器上 57 个进程每个都启动一个 “数据库的独立服务”， 那就不叫独立服务。

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet_group  供参考
