### ISSUE TITLE
cocos2d如何用lua加载proto协议发送消息

### ISSUE THREAD

**Issue by lindxsea** [cloudwu/skynet#566]

**Comment by hanxi** [comment]
也许应该去 https://github.com/cloudwu/sproto/issues 项目里面提 issues。或者去群里问更快。 💯

**Comment by lindxsea** [comment]
上楼的能说的具体点吗

**Comment by hanxi** [comment]
已经很具体了。难道要手把手。

**Comment by hanxi** [comment]
@lindxsea 你应该开始着手弄，遇到问题直接发问题，卡在哪一步。

**Comment by gameloses** [comment]
这里有很具体的 https://github.com/gameloses/cocos2dx_lua_skynet_client.git  使用socket+pbc+proto和skynet通信。已经用于项目开发。
