### ISSUE TITLE
OP_FORLOOP指令应该也需要加上lua_checksig检测？

### ISSUE THREAD

**Issue by linxiaolong** [cloudwu/skynet#568]
目前skynet定制的lua，OP_JMP\OP_CALL\OP_TAILCALL\OP_TFORLOOP指令都加上了lua_checksig检测，但OP_FORLOOP并没有，有其他考虑？

**Comment by cloudwu** [comment]
因为 OP_FORLOOP 本身会产生函数调用。

**Comment by linxiaolong** [comment]
假设OP_FORLOOP不加lua_checksig，测试了下，譬如以下这种循环是无法打破的：
for i = 1, 10000000000 do
...
end

这是预期的么？

**Comment by cloudwu** [comment]
我搞错了，加上。
