### ISSUE TITLE
cluster.call有时候不能返回

### ISSUE THREAD

**Issue by LokerLi** [cloudwu/skynet#572]
cluster.call有些时候不能返回，没有查到原因，写的测试案例也没有重现过，大大们给点思路，情况如下:

1.被CALL的方法是一个很简单的直接返回数字，没有任何的耗时操作，CALL过来的请求是接收到了，也skynet.ret了，但请求方就是没有收到返回
2.被CALL的服务会有cluster.send请求，一开始我一直以为这个有影响
3.同一个节点里的其他服务，用skynet.call这个服务的同一个方法是能成功返回的

**Comment by cloudwu** [comment]
1. 由 cluster.send 的方法需要在被调用方的函数第一行写上  `skynet.ret()` 。

2. 如果需要加一些 log 查看细节，由于 cluster 间是用 session 来区分每个请求的，所以打印出发起请求的 session 以及回应的 session 可以看到在哪个环节丢失。

https://github.com/cloudwu/skynet/blob/master/service/clusterd.lua#L155  这里是正常回应时，打包的地方。其它还有几处调用 `cluster.packresponse` 是异常回应。

https://github.com/cloudwu/skynet/blob/master/service/clusterd.lua#L14 这里是接收回应包的解包的地方。

https://github.com/cloudwu/skynet/blob/master/service/clusterd.lua#L120 这里是接收到的请求包的位置，当然从你的描述看，这个包一定收到了。

除了在 clusterd.lua 里加 log ，也可以考虑在 https://github.com/cloudwu/skynet/blob/master/lualib-src/lua-cluster.c C 代码里监控。

**Comment by cloudwu** [comment]
简述一下 cluster 的工作流程：

请求会通过 cluster 模块把消息发到 clusterd 服务。

clusterd 服务收到内部请求后，会根据目的节点生成一个递增的 session 号，打包后通过 socketchannel 发送请求。

目的节点的 clusterd 收到 socket 包后，解包获得请求 session 号以及请求包的目的地址以及数据。

目的节点的 clusterd 会将收到的请求转发给本地目的地址，等待回应。取得回应后，将回应数据打包，加上之前记录的 session 号，发回请求方。

发起方节点的 clusterd 通过 socketchannel 收到这个回应（由 socketchannel 按 session 匹配），回应给本地的提起请求方。

**Comment by LokerLi** [comment]
写log定位到这行一直没有返回
[https://github.com/cloudwu/skynet/blob/master/service/clusterd.lua#L152](url)

**Comment by cloudwu** [comment]
`ok , msg, sz = pcall(skynet.rawcall, addr, "lua", msg, sz)`

这行不返回就应该说问题不在 clusterd.lua 里，在对方 addr 这个服务中。

如果要继续排查的话，可以先看看不返回的 addr 是一个（同一类），还是一种普遍现象。各种 addr 都有可能不返回。

如果具体追查到某一类 addr ，可以用 `skynet.unpack(msg,sz)` 看看消息到底是什么。

btw. 在 debug console 里可以用 logon addr 记录 addr 服务收到的所有消息（需要在 config 中配置 logpath），不需要手动加 log 。

**Comment by LokerLi** [comment]
和#578 是同一个问题，云大威武。

**Comment by faruba** [comment]
我也遇到了类似的问题. 不过和这个不一样.自己通过看代码,加log的方式解决了.就顺便在这里分享一下.希望可以帮到遇到同样问题的人.
j简单说就是 服务A call -> 服务B -> call 服务A . 这会导致 服务A的消息队列锁死.要在逻辑上避免这种情况.

**Comment by Cheungwq** [comment]
您好，您发给我的邮件已收到。
