### ISSUE TITLE
lua loader error : ./libdev/service/snaxd.lua:9: module 'snax.loader' not found:

### ISSUE THREAD

**Issue by yingnierxiao** [cloudwu/skynet#574]
这个推送里面的   'snax.loader'   默认不存在的时候报错https://github.com/cloudwu/skynet/commit/d637d720db90f6ba869c6a1ebbbc04548087d8d9#diff-0be7124333a065c183f4cf2194a6c1f1

**Comment by cloudwu** [comment]
我先简单处理一下。
@hqwrong  没测试么？

**Comment by hqwrong** [comment]
啊 这个是我疏忽了><  我本地配置了snax_loader,没跑到or 后面那一句...
