### ISSUE TITLE
云大，sproto decode error 可以让skynet崩溃，有什么方法避免吗？

### ISSUE THREAD

**Issue by wvvmomo** [cloudwu/skynet#575]
建立一个连接，死循环发‘\0’字符串，大概一分钟左右就崩溃了。

**Comment by cloudwu** [comment]
请给 testcase， 或分析具体原因。

**Comment by wvvmomo** [comment]
lua call [1000012 to :1000015 : 0 msgsz = 0] error : ^[[31m./lualib/skynet.lua:516: ./lualib/sproto.lua:202: decode error
stack traceback:
        [C]: in function 'assert'
        ./lualib/skynet.lua:516: in function 'skynet.dispatch_message'^[[0m

**Comment by wvvmomo** [comment]
如果'\0'字符串过长，就会被检测到进入死循环，然后就被干掉了

**Comment by wvvmomo** [comment]
想在decode错误时断开连接，不知道怎么改

**Comment by cloudwu** [comment]
这不是你自己的事么？爱怎么搞怎么搞。
而且上面并没有指出问题的原因。

**Comment by tangyiyang** [comment]
理论上来说，客户端发上来的消息应该都是合法的。不应该出现empty string

**Comment by wvvmomo** [comment]
客户端发上来的消息是合法的，如果是别人恶心你了，建一个连接，只发空字符串

**Comment by mrvon** [comment]
@wvvmomo 我觉得你理解错了，这仅仅是agent内部发生解包错误而已，包的正确性应该由客户端保证，而不是什么“skynet崩溃”。

**Comment by cloudwu** [comment]
如果是没有处理内存溢出的情况导致的崩溃，需要自己处理在异常时终止。另外，单个服务可以限制内存上限：https://github.com/cloudwu/skynet/blob/master/test/testmemlimit.lua

**Comment by wvvmomo** [comment]
谢谢云大

**Comment by sswanv** [comment]
@wvvmomo 我也遇到这个问题了，不知道怎么解决，请问你解决了吗

**Comment by wvvmomo** [comment]
把连接直接踢了 不接收就行了 或者 按云大说的 设置单个服务内存上限

**Comment by sswanv** [comment]
我和你的错误是一样的，仔细查了下，好像是接收到了两条消息导致的，第一条消息长度为0，第二条消息是客户端发上来的正常的包，但是客户端只是发了一条消息，有点纳闷

**Comment by sswanv** [comment]
@wvvmomo 我和你的错误是一样的，仔细查了下，好像是接收到了两条消息导致的，第一条消息长度为0，第二条消息是客户端发上来的正常的包，但是客户端只是发了一条消息，有点纳闷

**Comment by sswanv** [comment]
@wvvmomo 我和你的错误是一样的，仔细查了下，好像是接收到了两条消息导致的，第一条消息长度为0，第二条消息是客户端发上来的正常的包，但是客户端只是发了一条消息，有点纳闷

**Comment by wvvmomo** [comment]
客服端的问题 你叫客服端发消息后 抓个包 然后把抓下来的数据 让他用sproto解包 自己找原因。服务端不被搞挂 才是你应该处理的问题

**Comment by sswanv** [comment]
@wvvmomo 能留个联系方式吗，请教下相关问题

**Comment by sswanv** [comment]
@wvvmomo 我写了一个测试代码，感觉是打包解包的时候有问题，由于某些限制，客户端使用的是lua5.1，打包形式为lpack的string.pack(">a")，服务器的为lua5.3的string.pack(">s2")，这两个是等价的吗，感谢！

**Comment by wvvmomo** [comment]
没试过

**Comment by PowerGit** [comment]
@sswanv  '>s2' 的意思是大端2个字节编码长度， 5.1的话需要自己实现这个函数
