### ISSUE TITLE
使用cluster做进程间通信时出现消息顺序异常问题？！！！

### ISSUE THREAD

**Issue by sctangqiang** [cloudwu/skynet#576]
A, B服务进程通信（skynet的cluster），

请求： A-->C1--->C2--->B, B通过skynet.retpack返回, A到C1是skynet.call, C1到C2是cluster.call, C2到B时skynet.call

通知: B-->C2-->C1-->A, B到C2时skynet.send,  C2到C1是cluster.call, C1到A是skynet.send

现在问题是为什么B到A的通知在B的skynet.retpack调用，怎么比B到C的通知后到达呢？？？？

关键是这个问题是有时出现， 大部分情况是期望的顺序

**Comment by cloudwu** [comment]
没看懂，请看懂的同学答疑。建议写完了自己读一遍，例如后面莫名其妙出了个 C 。

另， cluster 间通信如果数据超过 64k 会分包，不保序。

**Comment by cloudfreexiao** [comment]
A-> C1(属于cluster1)   ====   C2 ->B(属于cluster2)
A 发条消息 到B  B回复(a) 顺便再发条消息到 C1(b)
会出现 b 比 a 后到达

**Comment by cloudwu** [comment]
cluster 间全部都是单项通道。A 到 B 和 B 到 A 是两个 tcp 连接，它们是独立的，不保证谁先谁后。就这个具体问题，如果要求保证次序，必须在发送的通知被确认后再发回应。

**Comment by sctangqiang** [comment]
@cloudwu  上面没描述清楚
A, B服务间通信（使用skynet的cluster作为通信模块）：

请求： A-->C1（cluster）--->C2(cluster)--->B, A到C1采用skynet.call请求, C1到C2采用cluster.call请求, C2到B采用skynet.cal请求，B通过skynet.retpack回复C2到B的call,  以上是一个跨进程的调用链。 

通知: B-->C2（cluster）-->C1(cluster)-->A, B到C2采用skynet.send, C2到C1采用cluster.call, C1到A采用skynet.send， 改通知也是一个调用请求链。

现在问题是， B先回复A的请求， 然后再发起到A的通知， 现在出现的问题是B回复的请求，比B发出的通知后到达A？？ 我期望是B回复的请求比B发出的通知先到达A， 有针对cluster连个通道我有没有什么比较好的解决方案？

**Comment by cloudwu** [comment]
如果消息间有关联，那么不要建立双向通道。不要用 C2 到 C1 的请求，而是 C1 query C2 的通知，让 C1 先发出多个 query ，C2 收到后先 skynet.reponse 保存起来，等 C1 需要发通知的时候再返回之前的 query 。

反过来也可以，让 C1 请求发过来不直接回应，而是统一从 C2 向 C1 依次推送结果和通知。

这里要注意一个问题：如果传输的单个包超过 64k 依然有延后的可能。

ps. 发之前还是改一下错别字比较好。另外 github 也可以再编辑。

**Comment by sctangqiang** [comment]
云大，我明白你说的意思， 现在主要是不知道怎么从C2向C1推送之前的响应， 能给一个例子吗？

**Comment by cloudwu** [comment]
上面给出了两个方案都可以解决单向请求的问题。

1. 不要发送通知，而是回应通知请求。C1 一开始就 query C2 ，询问是否有新的通知。C2 收到查询后，调用 skynet.reponse() 保存查询。等你需要通知的时候（在 skynet.ret 回应之后）调用该函数返回需要通知的内容。

2. C1 不发起请求，而是推送请求（不接收回应），然后等待 C2 收到请求后，把回应内容以请求的方式调用 C1 。

解决问题的根本是：不要把 cluster.call 看成是单纯的请求回应，而看成发包（可以是请求包或回应包）并收到确认（包发到了）。在这个基础上再建立有时序要求的，双向的请求回应机制。我建议你做一下封装，把这类有时序要求的逻辑封装到一个通道上。
