### ISSUE TITLE
cluster send 导致了额外的BUG

### ISSUE THREAD

**Issue by zhulu-mike** [cloudwu/skynet#578]
比如，我有两个节点组成了cluster集群。一个gate，一个world，假如我从gate节点call一个消息到world，在world的处理逻辑里同时cluster.send给gate节点一个消息，在gate节点的这个消息处理里发生了某个异常。从此，从gate节点call到world节点的消息再也得不到回应了，可以确认world能收到并且处理，但是回应永远被挂起在clusted的服务中。

**Comment by cloudwu** [comment]
1. cluster.send 依旧是走的请求回应流程，和 cluster.call 在实现上没有区别。
2. 提 issue 请给 test case 或直接提 pr 修正。

**Comment by cloudwu** [comment]
找到一个可能的地方导致了这个问题，并不确定是否可以解决，烦请测试。

回应并没有挂起在 clusterd 中，或许是因为 clusted response 给调用 cluster.send 的一方一个不带 session d的 error report 让它误会 clusterd 挂掉了，自己忽略掉了消息。

**Comment by zhulu-mike** [comment]
确实，skynet.lua修改后，这个问题就解决了，可以收到回应了。谢谢云大。我会继续用好skynet。
