### ISSUE TITLE
配置文件中对cpath的解析能否支持多个?的写法？

### ISSUE THREAD

**Issue by jxlczjp77** [cloudwu/skynet#581]
skynet_module.c中_try_open目前只支持替换一个问号，是否可以改成支持多个问号，比如这样

cpath = root .. "?.framework/?"
lua_cpath = lroot .. "?.framework/?"

标准lua的lua_cpath支持这种多问号写法，但是cpath不支持

**Comment by cloudwu** [comment]
如果你可以写一个，提个 pr 。
