### ISSUE TITLE
关于skynet日志和github使用的问题

### ISSUE THREAD

**Issue by facingwaller** [cloudwu/skynet#582]
请教下如果想查找目前github上你的fork中是否有改进skynet日志模块的代码（或者将来想看看其他coder是否有改进其他模块的）。我可以如何做?

**Comment by cloudwu** [comment]
blame

**Comment by facingwaller** [comment]
也就是说，没办法很方便的去查找了。

**Comment by qinhanlei** [comment]
@facingwaller 
如果是自己业务逻辑的，可以看看这个，我们自己线上的项目也在用。
https://github.com/qinhanlei/terminator/blob/master/service/tm_logger.lua
https://github.com/qinhanlei/terminator/blob/master/lualib/tlog.lua
skynet内部的日志模块建议就不要再改了，不然将来合并官方的更新徒增烦恼。
定制过C的，但最后决定还是直接用lua算了。

**Comment by facingwaller** [comment]
@qinhanlei  谢谢。目前我这边已经改了skynet的内部日志模块C代码。上层lua代码完全不用管。

**Comment by cloudwu** [comment]
注意读文档： https://github.com/cloudwu/skynet/wiki/Config

通过配置 logservice 可以使用自己的 log 服务。

**Comment by lidashuang** [comment]
@qinhanlei https://github.com/qinhanlei/terminator/blob/master/lualib/tlog.lua#L46-L50 TEST_LOGGER 场景是什么？

**Comment by lidashuang** [comment]
@qinhanlei  感觉没必要做日志切分，好多现在成的工具，比如logrotate

**Comment by qinhanlei** [comment]
@lidashuang 
hi, 
TEST_LOGGER 应该是我当时用来测试效率用的，比如定量log的IO总耗时。
当时线上项目log太大，download下来查看不便，所以就顺手写了简单的切分。
还真没用过 logrotate 😅

**Comment by lidashuang** [comment]
> 测试效率
根据返回纪录请求时间？

**Comment by qinhanlei** [comment]
@lidashuang 
差不多是这个意思。
https://github.com/qinhanlei/terminator/blob/master/test/testlogger.lua#L14-L16
这里测试时用 skynet.call 保证了最后 cost 是想要看到的 IO 完毕的总耗时。
正常情况，就用 skynet.send 投递过去不管了。

**Comment by mark-perfect** [comment]
```lua
skynet.register_protocol {
	name = "SYSTEM",
	id = skynet.PTYPE_SYSTEM,
	unpack = function(...) return ... end,
	dispatch = function()
		-- reopen signal
		print("SIGHUP")
	end
}
```
reopen 这里应该怎么操作， 对应c中的 freopen
