### ISSUE TITLE
skynet定时器bug

### ISSUE THREAD

**Issue by 2081618539** [cloudwu/skynet#584]
超时时间  time =        111111 111111 111111 111111 11001111    
当前时间  curr_time = 000000 000000 000000 000000 00111111
	node->expire = current_time + time
	node->expire = 00001110  //此处溢出,导致 放在最低的8bit

add_node 函数中，执行下面逻辑:
         if ((time|TIME_NEAR_MASK)==(current_time|TIME_NEAR_MASK)) {
		link(&T->near[time&TIME_NEAR_MASK],node);    //存放在near中，
	}

 存放在near中，会导致马上超时

**Comment by cloudwu** [comment]
这里 time 是个负数，不支持传入负数。

**Comment by 2081618539** [comment]
@cloudwu     
 timer_add(struct timer *T,void *arg,size_t sz,int time) 
之前没注意  time的 类型是int, 以为还是uint32,  那定时器的最大值为< 2^31
