### ISSUE TITLE
daemon后如果write_pid出错看不到错误信息

### ISSUE THREAD

**Issue by lcy03406** [cloudwu/skynet#590]
目前write_pid里错误信息是用printf打到stderr的，但是这时已经daemon了，stderr已经是/dev/null。如果真的出错了的话，是看不到这个错误信息的。（好吧我承认我把config->daemon填成了“”而不是NULL然而这不是重点）

**Comment by cloudwu** [comment]
看看这个 patch ，改成自己关闭 std fds 了。

**Comment by lcy03406** [comment]
赞！没问题了！
