### ISSUE TITLE
debug_console 调试服务

### ISSUE THREAD

**Issue by CandyMi** [cloudwu/skynet#592]
先上代码

main.lua
```lua
local skynet = require "skynet"
local socket = require "socket"



skynet.start(function()

	local id = socket.listen("192.168.2.5",80)
	
	socket.start(id , function(fd,addr)
	
		local cnn = skynet.newservice "network"
		skynet.send(cnn,"lua","SOCKET",fd)
		socket.abandon(fd)

	end)
	--skynet.exit()
end)
```

network.lua
```lua
local skynet = require "skynet"
local socket = require "socket"

skynet.init(function()
	print("init was success...")
end)

local CMD = { }


function CMD.SOCKET(fd)

	socket.start(fd)
	socket.write(fd,"welcome!\n\r>>")

	while fd do

		local buf = socket.readline(fd)

		if buf and buf ~= "exit()" then

			socket.write(fd,"you say: " .. buf .. "\r\n>>")

		else
			skynet.error("Client Closed this Connection...")
			socket.close(fd)
			break
		end
	end

end

skynet.start(function()
	skynet.dispatch("lua",function(_,_,cmd,fd)

		local f = assert(CMD[cmd])
		if f then
			f(fd)
		end
	end)
end)
```

Skynet 运行后，在client端连接上后正常通信！ 假设客户端因为异常通信后关闭了套接字，console的debug命令在单步调试这个服务address时，将直接出现以下情况：
![0](https://cloud.githubusercontent.com/assets/13453599/24088943/8aa8a2d2-0d6b-11e7-88f7-89624ce50fd8.png)

**Comment by cloudwu** [comment]
1. 我无法重现。可以正常进入 debug 模式。
2. 可自己调试问题。
3. 你的 network.lua 似乎没有什么可供调试的东西。根据 http://blog.codingnow.com/2015/02/skynet_debugger.html 目前调试模式仅支持 watch 方法监控一条消息，但是 network.lua 在启动后就没有任何新信息进入了。`CMD.SOCKET` 只在启动的时候触发一次。

**Comment by CandyMi** [comment]
因为我没有使用skynet.exit来退出这个服务，所以会导致这个client在已经断开后服务一直处于一个停止的状态。
而我发现如果处于这个停止的状态，debug进去后就会出现Connection closed by foreign host.

**Comment by CandyMi** [comment]
Sorry！可能是我描述不当
   如果当其中的某个服务已经运行完成后，debug进去后能否知道是否具体运行位置而非close 掉console。

**Comment by cloudwu** [comment]
服务只要没有退出，不存在一个停止状态。你说的是 debug 的目标是一个不存在的服务，这个我可以改一下。

**Comment by CandyMi** [comment]
事实上，上面的network服务是存在一个while 循环跳出后是永远不会退出的。
而这个状态我们假设为：“内存泄漏”。因为这个服务实际上在client close掉连接后，list是可以看到的。
而debug连接后又无明确信息network服务具体状态，我再来debug的时候仅仅弹出connected close。

**Comment by cloudwu** [comment]
这里有一个 bug ，我提交了一个 patch 修复。修的并不好，但是可以解决这里的问题。是否有更好的方法，需要再考虑一下。

但就你提出的问题，其实和这个 bug 不是一回事。

1. 每个服务不调用 exit 是不会退出的，这个是 skynet 的特性。如果你 list 可以看到，那么就是可以 debug 的。我无法重现你不能再次 debug 的问题。这个和连接是否断开无关。

2. 服务并不存在一个状态无法接收消息。你认为它的事情做完了应该退出必须自己明确写。只要服务可以接收新的消息，那么就可以被调试。**而debug连接后又无明确信息network服务具体状态** 这里的状态是你定义的概念， skynet 并没有这个状态的概念。

3. 无论你用什么手段让服务退出，也就是 debug console 下如果调试一个不存在的服务，那么有因为 bug 断开控制台连接。这个 bug 和你上面的例子没有太大关系。只需要 debug 一个不存在的服务就会触发。

关于 3 ，这是一个特殊情况导致的 bug 。暂时没有特别好的修复方式。它是因为控制台连接的控制权从控制台主循环转移到 debug 指令和 debug agent 交互。skynet 不允许同时有两个 thread (用 skynet.fork 生成) 读同一个 socket ，否则会抛出 error 。debug console 在捕获这个 error 后断开了连接。

这里的修复方法是，当控制台连接的控制权转移到 debug 指令下后，一定要确定控制权交回才能返回。避免两个 thread 同时读一个 socket 的情况发生。
