### ISSUE TITLE
关于skynet公共配置是否可以增加一个方法加载进来

### ISSUE THREAD

**Issue by zhangshiqian1214** [cloudwu/skynet#593]
关于skynet公共配置是否可以增加一个方法加载进来,这样关于公共配置就不用重复配置
使用方法就像这样:
![qq 20170320134724](https://cloud.githubusercontent.com/assets/9353330/24089626/c46a8b68-0d73-11e7-9a9d-4f9845e13c42.png)

而config_public就像这样:
![qq 20170320134844](https://cloud.githubusercontent.com/assets/9353330/24089643/f37d663c-0d73-11e7-9280-305cbb244334.png)

只要修改skynet_main.c里面就可了,
```lua
//remove ater line 95
static const char * load_config = "\
	local config_name = ...\n\
	local f = assert(io.open(config_name)) \n\
	local code = assert(f:read \'*a\') \n\
	local function getenv(name) return assert(os.getenv(name), \'os.getenv() failed: \' .. name) end \n\
	code = string.gsub(code, \'%$([%w_%d]+)\', getenv) \n\
	f:close() \n\
	local result = {} \n\
	local function include(path) loadfile(path,'t',result)() end \n\
	setmetatable(result, {__index={include=include}}) \n\
	assert(load(code,\'=(load)\',\'t\',result))() \n\
	return result\
";

**Comment by cloudwu** [comment]
我考虑加一个 include 。

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/commit/832d4b4c438a16e8f7429b1e92cade598bd070bd

加了。当初想加一个跟完善的，让 include 的文件可以相对 config 文件自己所在路径。过于麻烦，先这样了。

**Comment by zhangshiqian1214** [comment]
加上去之后,已经很好用了

**Comment by uvtong** [comment]
这个代码不够完美，include的那些文件不支持环境变量的替换了

**Comment by cloudwu** [comment]
本来是不想加的，想想还是加上好了。

**Comment by uvtong** [comment]
https://github.com/cloudwu/skynet/pull/595/files      。。。。 研究了半天才提交上去

**Comment by cloudwu** [comment]
3a4a673b43dab351a8458c28b2bf41a002bedaf2 果然一点懒都不能偷。现在相对路径也支持了。

**Comment by uvtong** [comment]
云大，辛苦了！

**Comment by zhangshiqian1214** [comment]
云大，辛苦了！

**Comment by hanyu363** [comment]
关于公共配置的方法是好的。。
但是支持这个接口之后，原来在配置中。使用
pairs 方法，统统不能用了。无法再配置写一些简单的逻辑。

**Comment by hanyu363** [comment]
做出了如下修改
static const char * load_config = "\
	local result = {}\n\
	local function getenv(name) return assert(os.getenv(name), [[os.getenv() failed: ]] .. name) end\n\
	local sep = package.config:sub(1,1)\n\
	local current_path = [[.]]..sep\n\
	**function include(filename)**\n\
		local last_path = current_path\n\
		local path, name = filename:match([[(.*]]..sep..[[)(.*)$]])\n\
		if path then\n\
			if path:sub(1,1) == sep then	-- root\n\
				current_path = path\n\
			else\n\
				current_path = current_path .. path\n\
			end\n\
		else\n\
			name = filename\n\
		end\n\
		local f = assert(io.open(current_path .. name))\n\
		local code = assert(f:read [[*a]])\n\
		code = string.gsub(code, [[%$([%w_%d]+)]], getenv)\n\
		f:close()\n\
		assert(load(code,[[@]]..filename,[[t]],result))()\n\
		current_path = last_path\n\
	end\n\
	**setmetatable(result, { __index = _G} )**\n\
	local config_name = ...\n\
	include(config_name)\n\
	setmetatable(result, nil)\n\
	return result\n\
";

**Comment by Zirpon** [comment]
[[%$([%w_%d]+)]] 这个串 是为了匹配什么环境变量
