### ISSUE TITLE
能否即时察觉到 cluster 死掉

### ISSUE THREAD

**Issue by hangj** [cloudwu/skynet#594]
当前代码有没有检查 cluster 是否还活着的方式

**Comment by zhangshiqian1214** [comment]
是啊,同问, 现在目前是通过心跳来判断某个cluster节点是否存活的

**Comment by hangj** [comment]
还是心跳好了。

**Comment by cloudwu** [comment]
向任何一个对端服务做一次远程调用，而不要返回就能知道。

一旦 cluster 连接断开，这个远程调用就会抛出 error 。

**Comment by hangj** [comment]
ok ~
