### ISSUE TITLE
求教，如果把rabbitmq的client端融入skynet，可以收发消息队列中的消息

### ISSUE THREAD

**Issue by zhulu-mike** [cloudwu/skynet#596]
RT，求思路。是分开做，还是要跟skynet搞到一起？

**Comment by cloudwu** [comment]
建议参考 https://github.com/wingify/lua-resty-rabbitmqstomp 来开发一个 driver ，并不算太复杂。

**Comment by cloudwu** [comment]
模仿现有的 redis driver 做。
