### ISSUE TITLE
关于skynet_malloc.h定义问题

### ISSUE THREAD

**Issue by linxiaolong** [cloudwu/skynet#597]
以下：
#define skynet_malloc malloc
#define skynet_calloc calloc
#define skynet_realloc realloc
#define skynet_free free

应该是：
#define malloc skynet_malloc
#define calloc skynet_calloc
#define realloc skynet_realloc
#define free skynet_free

如若不是错误，暂时没想到这样的意图是什么？

**Comment by cloudwu** [comment]
首先，你可以查询这个文件的修改历史，这样做是有意而为。

在过去， glibc 为内存分配器提供 hook 来允许自定义。后来这个做法不被提倡了。

在 linux 上，是通过重新实现 malloc 等符号来改写分配器的。这里加 skynet 前缀是提示使用者，这可能是自定义的内存 api . 单实际上它取代了 glibc 中对应的东西。

目前也可以通过定义NOUSE_JEMALLOC 来还原使用 glibc 的内存api 。

**Comment by xiaowei0516** [comment]
#define skynet_malloc malloc
#define skynet_calloc calloc
#define skynet_realloc realloc
#define skynet_free free

这个是正确的写法，从#define 的语法上来看。

如果使用下面的写法，编译宏展开之后代码中的malloc会被sky_malloc替换，这样肯定是错的。

**Comment by linxiaolong** [comment]
明白了。不过这样的话，其实skynet-src的其他模块直接使用malloc或者free这种原生接口就行了，因为符号已经重定向

**Comment by cloudwu** [comment]
不直接写 malloc 是因为需要在语义上做区分，以及日后有修改的话不用再修改源代码。事实上目前的做法也和一开始的不同。
