### ISSUE TITLE
建议调用skynet.abort()后回调所有服务再结束进程

### ISSUE THREAD

**Issue by korialuo** [cloudwu/skynet#600]
云风您好！
我在console服务里加了一个quit的命令，里面调用了skynet.abort()来结束进程，但是我想在结束进程前做一些收尾工作，比如存储部分信息到数据库。是否考虑可以增加一个类似skynet.init()的回调接口？

**Comment by korialuo** [comment]
我的建议是，增加一个skynet.quit()的API，传入一个function，当某个地方调用skynet.abort()后，遍历所有服务，回调这个function，如果服务没有注册skynet.quit()回调方法，就不回调。不知是否合理？或者您有更好的方法？

**Comment by cloudwu** [comment]
这是你上层业务框架设计的范畴，不应在底层做。框架应尽量减少回调约定，尤其是不应脱离业务设计流程。

**Comment by cloudwu** [comment]
另外 console 属于线上应急机制，不应作为常规运维手段。应该为你的业务开发运维系统。

**Comment by cloudwu** [comment]
为你的业务开发框架有很多可以利用的底层机制，比如：

https://github.com/cloudwu/skynet/wiki/Config 可以配置 preload 。

`skynet.register_protocol` 注册独立的协议。

**Comment by korialuo** [comment]
谢谢云风。我了解一下。
