### ISSUE TITLE
loginserver 为什么以"\n" 为分包，而不是gateserver的【一个 2 字节的包头加内容】

### ISSUE THREAD

**Issue by dingmingxin** [cloudwu/skynet#601]
如题。
loginserver的请求和回应包为什么设计成以"\n"分割。如果用【一个 2 字节的包头加内容】这种方式会有什么不妥？
我在实际使用中，客户端要为此实现两种分包机制，一个基于"\n"的，一个基于2 字节包头的。用两套，这样会比较麻烦。

**Comment by Ding8222** [comment]
可以改吧...我就改了的。
loginserver那边我都改成sproto解析了

**Comment by cloudwu** [comment]
不喜欢自己改。

**Comment by dingmingxin** [comment]
看来没有别的设计原因喽？

**Comment by cloudwu** [comment]
一个潜在不说的原因就是，适应各个单独设计的模块像搭积木那样搭起来，容忍这些不同，而不受限于“统一” 才能放在一起用。

**Comment by dingmingxin** [comment]
了解了

**Comment by cloudwu** [comment]
比如你用基于 http 的 oauth 协议做认证，可能还需要弹浏览器，加完全不同的协议。

**Comment by dingmingxin** [comment]
谢谢云大
