### ISSUE TITLE
求助,skynet服务器内存一直在涨

### ISSUE THREAD

**Issue by zhangshiqian1214** [cloudwu/skynet#602]
我使用skynet搭建了个棋牌服务器,刚试了下开了100个游戏台agent, 游戏里面现在一个人都没有,启动完后看着内存从300M涨到1200M还在涨,服务器是使用cluster模式搭建的, 因为项目完成的差不多了,临近上线, 出了这个问题, 所以希望各位大大帮忙出个主意

**Comment by cloudwu** [comment]
数据这种东西，求不要再贴图片了。

**Comment by zhangshiqian1214** [comment]
嗯,好的,以后注意

**Comment by zhangshiqian1214** [comment]
云大威武, 用了新修改了cluster.send后开了3000个agent内存就稳定下来了,现在平均1M可以开2个游戏台了, 之前没有注意到cluster WIKI上要注意收到cluster.send要skynet.ret回去, 现在使用了新版的cluster.send后不用skynet.ret后好用很多,全部都统一在dispatch里通过session判断怎么分发请求就可以了

**Comment by cloudwu** [comment]
顺便可以测试一下新的改动是否有 bug ，当然最好能仔细 review 一下代码。我今天打算写一篇 blog 详细讲解一下细节设计，帮助 review 。

**Comment by zhangshiqian1214** [comment]
目前测试下来没有问题, 结合着blog的看了代码,能够理解之前那么做的原因了
