### ISSUE TITLE
dns模块pack_header时候报unsigned overflow的错

### ISSUE THREAD

**Issue by antsmallant** [cloudwu/skynet#605]
local next_tid = 1
local function gen_tid()
	local tid = next_tid
	next_tid = next_tid + 1
	return tid
end

local function pack_header(t)
	return string.pack(">HHHHHH",
		t.tid, t.flags, t.qdcount, t.ancount or 0, t.nscount or 0, t.arcount or 0)
end

以上没对tid超过无符短整数的最大值后进行处理，当超过时，string.pack就会报unsigned overflow的错

**Comment by cloudwu** [comment]
是说 t.tid 这么么？

**Comment by cloudwu** [comment]
看看这么改可以么

**Comment by antsmallant** [comment]
可以了
