### ISSUE TITLE
macosx环境下. 输出到终端stdout的信息较长时, 经常显示不全

### ISSUE THREAD

**Issue by yanyiyun** [cloudwu/skynet#606]
测试环境是macosx 10.12.1
在skynet需要打印比较长的信息时. 用print或者skynet.error. 输出是到stdout.  经常会显示不全, 消息被截断. 
然而, 如果我用lldb 挂接进去执行. 又一切输出正常. 
一脸懵逼.

**Comment by qinhanlei** [comment]
我也有碰到这个问题。
应该是 mac 的 terminal 的缓冲刷新机制的问题，日志输出到文件是没问题的，后来就没再管了。

**Comment by mrvon** [comment]
过长的输出就会重现。
ubuntu，terminal也有这个问题，暂时没查到原因。

**Comment by yanyiyun** [comment]
蛋疼, 要看比较多的内容, 还得输入日志.

**Comment by cloudwu** [comment]
活用重定向和 tail -f :)

**Comment by yingnierxiao** [comment]
mac下没遇到过，缓冲器设置大点，或者重定向到文件去
