### ISSUE TITLE
关于windows版本的socket的error无法正常返回

### ISSUE THREAD

**Issue by heyilin416** [cloudwu/skynet#615]
由于socket_server.c的头文件包含顺序，winsock2.h定义SOCKET_ERROR=-1，而skynet定义是4，然后socket_server_poll处理时，如果是-1就直接continue掉了，造成windows版本socket的error就一直阻塞，通过将socket_server.h的包含调整到最下面可以解决此问题。

**Comment by cloudwu** [comment]
skynet 并没有 windows 版本。

**Comment by cloudwu** [comment]
如果是使用第三方的 windows 版，可以去那边提个 issue 。

**Comment by cloudwu** [comment]
我换个名字，避免重名。

**Comment by firedtoad** [comment]
我的版本已经修复了

2017-04-19 11:02 GMT+08:00 云风 <notifications@github.com>:
