### ISSUE TITLE
如何使用在skynet使用xpcall或者pcall

### ISSUE THREAD

**Issue by yanyiyun** [cloudwu/skynet#616]
逻辑需求, 比如消息的逐条处理, 或者事件系统的投递处理. 不希望在这些处理函数中因为某条消息异常导致逻辑中止. 所以在对应的地方使用了xpcall.  作用类似try catch.
这也同时意味着这些处理函数不能使用skynet的阻塞函数, 比如skynet.call. 否则会提示yield across a C-call. 
我想了解下, skynet又没有比较好的方式处理这类问题. 

代码如下

```
--事件系统的消息投递
function fire(eventId, params)
    local eventList = table.copy(events[eventId]);

    for _, info in ipairs(eventList) do
        if info.func then
            --如何解决info.func函数内无法调用skynet.call的问题
            local status, err = xpcall(function() info.func(params); end, __G__TRACKBACK__);
            if not status then
                print(err);
            end
        end
    end
end

```

**Comment by small630** [comment]
问题不在pcall或者xpcall，应该是table.sort中调用了RPC。
http://blog.codingnow.com/2015/11/rpc.html

**Comment by yanyiyun** [comment]
small630, 你说的我可以理解. 看来我举的例子不是特别合适.  其实我想表明的是skynet.call无法越过pcall的问题.  pcall作为一个try catch功能, 是为了出错的时候后续代码行为还能继续下去, 或者做出错处理.  但是有了这个限制就变得很为难. 设计上要特别谨慎.

**Comment by cloudwu** [comment]
skynet.call 和 pcall 并无冲突。

**Comment by cloudwu** [comment]
例如： https://github.com/cloudwu/skynet/blob/master/test/testdeadcall.lua#L28-L30

**Comment by yanyiyun** [comment]
啊. 我弄错了
