### ISSUE TITLE
关于Skynet运行时的错误....

### ISSUE THREAD

**Issue by CandyMi** [cloudwu/skynet#617]
Skynet 运行时报错......
![7calvj tgg1 xzjl bkf4mt](https://cloud.githubusercontent.com/assets/13453599/25220276/dee3ce68-25e3-11e7-8519-a64a2b099b3c.png)

错误中的目录是不存在的......

**Comment by CandyMi** [comment]
附上一个gdb的图。
![b2qo sabxl52 2b m 7s4ec](https://cloud.githubusercontent.com/assets/13453599/25220601/db7ac15e-25e4-11e7-8b0a-39889afbda6c.png)

**Comment by cloudwu** [comment]
1. 能贴代码的时候不要贴屏幕截图。
2. 所有释放内存引起的问题，先查有没有 double free 。

**Comment by CandyMi** [comment]
@cloudwu 
请教上图中#2与#3中的2次dlclose就是说明double free了吧？

**Comment by cloudwu** [comment]
double free 参考 https://github.com/cloudwu/skynet/issues/527

不要链接 jemalloc 可以用 glibc 定位 double free 。 两次 dlclose 和 double free 没有直接联系。

**Comment by CandyMi** [comment]
好的，谢谢指教！
