### ISSUE TITLE
sproto如果超时未收到回应，如何清理__session？

### ISSUE THREAD

**Issue by lcy03406** [cloudwu/skynet#620]
目前看代码似乎sproto用__session表记录有效的session，发出请求时记录，收到应答时清除。
我们sproto是用在服务器和客户端之间的，所以必须考虑对端的各种异常情况。如果客户端长时间不回应，我们希望能把客户端踢下线并清理相关的各种资源和引用，请教如何清除__session里的未回应的session？

**Comment by cloudfreexiao** [comment]
客户端 不回应？ 难道不是 客户端请求吗？

**Comment by cloudwu** [comment]
客户端下线后应该把整个 host 对象扔掉。

**Comment by lcy03406** [comment]
所以需要为每个连接构造一个host？我目前是一个服务实例用一个，属于错误用法吗？

**Comment by cloudwu** [comment]
似乎没有什么理由多个连接合用一个。

**Comment by tdlrobin** [comment]
如果服务器只有通知客户端，没有response项是不是就不用担心？
