### ISSUE TITLE
建议lua seri 时候忽略function类型，但不报错。

### ISSUE THREAD

**Issue by korialuo** [cloudwu/skynet#621]
云风，您好！
有时候在skynet.call或者skynet.send的时候，传一个table过去，table里难免有function的类型。我之前的解决方案是，先把这个function变量设为nil，传过去后，再设回原来的function，这样感觉有点不便。我修改了几行代码，如下，不知道是否合理？或者您有更好的解决方式？
https://github.com/korialuo/skynet/commit/dac3b60570ca586a3eec30667c5a1786ba971621

由于我fork的本地仓库里，自己的commit太多，就不提pr了。暂时还不知道怎么在提交pr的时候筛选部分commit。

**Comment by cloudwu** [comment]
有特殊需求的可以注册新的类型，用独立的 pack 函数。
