### ISSUE TITLE
dispatch消息嵌套使用的问题

### ISSUE THREAD

**Issue by huji0624** [cloudwu/skynet#622]
类似如下调用以后，会出现诡异的问题，服务端就收不到客户端的消息了，感觉像是死锁了，想问下是不是不支持类似lua消息的嵌套使用.

skynet.dispatch("lua", function(session, source, cmd, subcmd, ...)

		skynet.dispatch("lua", function(session, source, cmd, subcmd, ...)
		
               end)

end)

**Comment by cloudwu** [comment]
不明白这样用的意义。

**Comment by rikxqd** [comment]
在大类消息里，再dispatch小类消息？看似也没必要这样嵌套使用dispatch。甚至当skynet.dispatch嵌套使用时直接报错？

**Comment by huji0624** [comment]
不会直接这样使用，大概的场景是这样的

在一个服务中
local xx = require 'xx'
skynet.dispatch("lua", function(session, source, cmd, subcmd, ...)
if cmd == ''xx' then
    xx.foo("event")
end
 end)

然后在xx中
function foo(event)
    	skynet.dispatch("lua", function(session, source, cmd, subcmd, ...)
	    if cmd == event then
                  do someting here.
           end
         end)
end

xx不是一个服务，主要是用xx来封装一些操作，不知道我有没有说明白

**Comment by huji0624** [comment]
不知道大家是怎么写skynet的服务代码的，但我感觉这种写法我是比较常用的，这里xx其实是利用skynet.self()是取到的这个服务本身，xx是一段纯lua代码.

**Comment by cloudwu** [comment]
不知道你这么写的意义是什么，期待完成什么任务。

dispatch 只是设置一个分发函数，而一个类型的分发函数同时只有一个。你运行过 xx.foo 后，这个分发函数就永久变成了下面一个。这样做意义何在？

**Comment by huji0624** [comment]
是这样的，不知道skynet是否有自己的消息订阅和广播的模块，我把wiki 看了一遍貌似没发现，所以我写了下面这个snax服务：
`local skynet = require 'skynet'
local log = require 'lnlog'

local subrepos = {}

function accept.pub(event,...)
	-- body
	local subs = subrepos[event]
	if subs then
		for i,v in ipairs(subs) do
			skynet.send(v.addr,'lua',event,...)
		end
	else
		log.info(event.." has no subscriber.ignore.")
	end
end

function accept.sub(event,addr,callback)
	-- body
	local subs = subrepos[event]
	if not subs then
		subs = {}
		subrepos[event] = subs
	end

	v = {}
	v.addr = addr
	v.callback = callback

	table.insert(subs,v)

	log.info("订阅事件 "..event.." for "..addr)
end

function accept.unsub(event,addr)
	local subs = subrepos[event]
	if subs then
		local rindex = -1
		for i,v in ipairs(subs) do
			if v.addr == addr then
				rindex = i
				break
			end
		end
		if rindex>=0 then
			table.remove(subs,rindex)
			log.info("unsub "..event.." for "..addr)
		end
	end
end

function  init( ... )
	-- body
	log.info('kafka init.')
end

function exit( ... )
	-- body
	log.info('kafka exit.')
end`


然后我嫌用起来麻烦，就给这个snax服务加了一个封装：
`local skynet = require "skynet"
local snax = require "snax"

local kafkaapi = {}
function kafkaapi.pub(event, ... )
	-- body
	local kafka = snax.queryglobal("kafka")
	kafka.post.pub(event,...)
end

function kafkaapi.sub(event,callback)
	skynet.dispatch("lua",function(session, source, cmd, ...)
  		if cmd == event then
  			callback(...)
  		end
	end)

	-- body
	local kafka = snax.queryglobal("kafka")
	kafka.post.sub(event,skynet.self())

end

function kafkaapi.unsub(event)
	-- body
	local kafka = snax.queryglobal("kafka")
	kafka.post.unsub(event,skynet.self())
end

return kafkaapi`


然后在代码里面大概就这么用

发布一个事件：kafka.pub("exitGame",uid,u.fd)

订阅一个事件并处理：
`kafka.sub("exitGame",function (uid,fd)
		-- body
		CMD.exitGame(uid,fd)
end)`

我只是感觉这么写起来比较简单，不知道是不是自己思路完全错了.....还请云大大指点.

**Comment by yingnierxiao** [comment]
https://github.com/cloudwu/skynet/wiki/Multicast

**Comment by cloudwu** [comment]
思路精奇，有跟上思路的同学帮着讲讲。

**Comment by huji0624** [comment]
谢谢云大大，我的意思就是想问下是否能支持注册函数列表，目前不支持的原因是因为性能问题么?

感谢 @yingnierxiao ，multicast可以满足需求.

**Comment by cloudwu** [comment]
我觉得你应该考虑的是如果有这样的接口，应该有怎样的具体行为；以及为什么需要框架实现这样的行为，自己实现有什么困难。

**Comment by huji0624** [comment]
好的，抱歉耽误你的时间了.
