### ISSUE TITLE
send_request 函数的错误处理

### ISSUE THREAD

**Issue by guojuntao** [cloudwu/skynet#624]
````
static void
send_request(struct socket_server *ss, struct request_package *request, char type, int len) {
	request->header[6] = (uint8_t)type;
	request->header[7] = (uint8_t)len;
	for (;;) {
		int n = write(ss->sendctrl_fd, &request->header[6], len+2);
		if (n<0) {
			if (errno != EINTR) {
				fprintf(stderr, "socket-server : send ctrl command error %s.\n", strerror(errno));
			}
			continue;
		}
		assert(n == len+2);
		return;
	}
}
````

当 write 失败的时候，比如 **EPIPE (Broken pipe)** ，就会一直卡在死循环里，独占线程并且浪费机器的 CPU资源。
是不是应该把 continue 改为 break 比较适合，丢消息+告警；或者干脆 panic

**Comment by cloudwu** [comment]
为什么会有 EPIPE ? 有没有 testcase 。

**Comment by cloudwu** [comment]
这里是内部代码，fd 有明确的类型。write 只是一个针对所有类型 fd 的通用接口。在没有实际案例可以探讨的情况下，简单修改是不负责任的做法。

如果有实际案例，再来围绕案例讨论发生这种情况的原因，修改也不会只针对这一行。

**Comment by guojuntao** [comment]
根据 /proc/pid/fd 跟 lsof 的结果，EPIPE 的原因是管道的读端的 fd 被关闭了，同时 stderr，也就是 fd 2 也被关闭了。

至于为什么这两个 fd 被关闭了。目前还在查。

**Comment by cloudwu** [comment]
这里的 fd 不可能被关闭。这是你的 bug 。另外 fd  2 也不应该被关闭。

**Comment by guojuntao** [comment]
原因查出来，是我的 bug。
我在 skynet 上面加上 mosquitto 的客户端，创建 socket 的时候，把 skynet socket 的 id 存在 mosq 的 socket fd 位置。读取的逻辑都改了，通过 skynet 的 socket 去读写数据；close 的逻辑没改。导致 mosquitto 直接 close（id）。/捂脸。。。
