### ISSUE TITLE
luaservice的rqurie路径问题

### ISSUE THREAD

**Issue by yanyiyun** [cloudwu/skynet#626]
luaservice lua 服务代码所在的位置。可以配置多项，以 ; 分割。 如果在创建 lua 服务时，以一个目录而不是单个文件提供，最终找到的路径还会被添加到 package.path 中。比如，在编写 lua 服务时，有时候会希望把该服务用到的库也放到同一个目录下。

根据这个意思. 我总觉得loader.lua 中的这句
local service_path = string.match(pattern, "(.*/)[^/?]+$")

其中"(.*/)[^/?]+$" 应该改为 "(.*/)%?[^/?]+$" 吧. 这样才会对应加入服务的路径

**Comment by cloudwu** [comment]
```
servicename = "myservice"
pattern = "/path/?/init.lua"
service_path = string.match(pattern, "(.*/)[^/?]+$")
service_path = string.gsub(service_path, "?", servicename)
path = service_path .. "?.lua"
print(path)	-- /path/myservice/?.lua
```
是这个意思。
