### ISSUE TITLE
调用 mysql 报错 attempt to yield across a C-call boundary

### ISSUE THREAD

**Issue by fhbzyc** [cloudwu/skynet#633]
我先写了一个文件  db.lua 里面是:
local mysql = require("mysql")
mysql.connect(.......)
return mysql

然后在snax服务里写 :
local db = require("db")
就会报下面的错
请问是哪里有问题

/Users/speed/server_skynet/skynet/lualib/skynet.lua:525: /Users/speed/server_skynet/skynet/lualib/skynet.lua:155: /Users/speed/server_skynet/skynet/service/snaxd.lua:46: attempt to yield across a C-call boundary
stack traceback:
	[C]: in function 'profile.yield'
	/Users/speed/server_skynet/skynet/lualib/skynet.lua:289: in function 'skynet.wait'
	/Users/speed/server_skynet/skynet/lualib/socket.lua:33: in upvalue 'suspend'
	/Users/speed/server_skynet/skynet/lualib/socket.lua:184: in function </Users/speed/server_skynet/skynet/lualib/socket.lua:167>
	(...tail calls...)
	/Users/speed/server_skynet/skynet/lualib/socketchannel.lua:230: in upvalue 'connect_once'
	/Users/speed/server_skynet/skynet/lualib/socketchannel.lua:268: in upvalue 'try_connect'
	/Users/speed/server_skynet/skynet/lualib/socketchannel.lua:320: in function </Users/speed/server_skynet/skynet/lualib/socketchannel

**Comment by cloudwu** [comment]
search issue with "attempt to yield across a C-call boundary"
