### ISSUE TITLE
socket_server的疑问

### ISSUE THREAD

**Issue by yc90s** [cloudwu/skynet#634]
socket_server的recvctrl_fd为什么要在epoll里面注册读事件，发给socket_server的命令不是用的select获取的吗，而且epoll_wait的返回值里面，recvctrl_fd也是直接过滤掉的

**Comment by cloudwu** [comment]
提高它的处理优先级

**Comment by cloudwu** [comment]
需要用读事件唤醒epoll

**Comment by 1050676515** [comment]
提高它的处理优先级可以理解，但是用recvctrl_fd的读事件去唤醒epoll有什么意义吗

**Comment by lin1314** [comment]
这个问题的后续...
云风:
1. pipe 需要用最高优先级处理，因为 pipe 是进程内用于线程数据交换的，而且是阻塞的，你不立刻读走，那边就写不进去。
2.处理很多外部 fd 时，一次 epoll 数量有限，很可能处理不到 pipe

我: 可是 checkctrl = 1 是在 sp_wait一返回就设置的, 然后下一次循环就去select( 已经满足优先检查pipe消息的设定). 这个时候, 感觉还是没必要在epoll中注册 pipe read呀.
云风:  如果你不注册 pipe 到 epoll, 那么如果没有任何外部 fd 的消息，epoll 就不返回了，即使 pipe 里有数据需要读。多想想再提问
------------------------------------------
解释: 如果没有注册给epoll,   此时产生ctr_cmd事件, 但没有其他fd的事件. 
        这边的checkctrl标志位, 就不会被置1. 为了补偿这个, 可能得每次写pipe都去设置一次(很stupid)
        这边巧妙地使用了epoll, 佩服!
