### ISSUE TITLE
关于socketchannel

### ISSUE THREAD

**Issue by nanke-** [cloudwu/skynet#636]
正常情况下，socketchannel 是有重连机制的，但是在收到这样一个报错： **socket: error on 4 Connection timed out** 之后，我看到确实还是有重连的，fd 换了，但是后面继续用socketchannel 发消息就一直报错，而且已经收不到消息了

求解惑

**Comment by nanke-** [comment]
socket.lua 中在收到这样一样报错之后，是调用socketdriver的shutdown，但是手动模拟之，并不能重现，至于为什么会收到Connection timed out， 问题还在排查中，不知道会有什么关联呢

**Comment by cloudwu** [comment]
无法重现。加一些 log 看看是什么流程导致出错。出错后为什么无法重新连接上，或是重新连接无法正确工作。

目前的报告无助于解决问题。

**Comment by cloudwu** [comment]
https://www.chiark.greenend.org.uk/~sgtatham/bugs.html How to Report Bugs Effectively
