### ISSUE TITLE
gc 导致multicast unsubscribe

### ISSUE THREAD

**Issue by dingmingxin** [cloudwu/skynet#637]
场景：server A 是个广播中心，agent B 和 agent C订阅了A的多播消息

在agent中订阅消息我是这样写的
```lua
local mc_channel = nil

local function init_mc_channel(channel_id)
         mc_channel = multicast.new {
		channel = channel_id,
		dispatch = function(channel, source, data) {
                -- do something
                }
         }
         mc_channel:subscribe()
end
```

一开始多播是没问题的，运行一段时间以后，agent A 或者agent B就收不到多播消息了。我在agent也没有手动取消订阅。

后来在skynet/lualib/multicast.lua 中看到了gc的代码，才明白：
```lua
local chan_meta = {
	__index = chan,
	__gc = function(self)
		self:unsubscribe()
	end,
	__tostring = function (self)
		return string.format("[Multicast:%x]",self.channel)
	end,
}
```
运行环境
macos 10.12.3
2.2 GHz Intel Core i7
16 GB 1600 MHz DDR3
skynet version：1.0.0

既然我没有手动取消订阅，为何要在gc中取消订阅，这一点让我很困惑。
是我使用的方式不对吗，请问如何避免mc_channel 被gc掉？

**Comment by DeanHH** [comment]
你的mc_channel被持有引用就行了，如果这是个独立的lua文件，你return mc_channel出去交给package持有就行了。

**Comment by dingmingxin** [comment]
@DeanHH 如何交给package持有
```lua
_G["mc_channel"] = mc_channel
```
这样么？

**Comment by dingmingxin** [comment]
最后找到原因了，是因为我对发给agent的消息处理做了profile(skynet带的那个profile），把profile屏蔽掉，就没有问题了。

开启profile的时候，即使我把mc_channel在好多地方引用，也会触发它的gc，屏蔽掉就没问题了。
当然profile只能是开发时用，但是我怀疑profile影响了gc或者破坏了gc @cloudwu

**Comment by cloudwu** [comment]
我不认为 profile 会和 gc 有关系。

**Comment by dingmingxin** [comment]
那请教下，我在agent这个虚拟机中，把mc_channel放到全局，并没有设置其为nil，为什么还会触发gc呢

**Comment by dingmingxin** [comment]
最终找到原因了，前面说的profile确实不是该问题的原因。问题的核心原因是我写的一个接口多次调用：

出问题的接口：
```lua
function agent:bind_broadcast_center(channel_id)
	local channel = multicast.new{
		channel = channel_id,
		dispatch = function(channel, source, data)
			--do some thing
		end
	}
	self.channel = channel
end
```
修改后的接口：
```lua
function agent:bind_broadcast_center(channel_id)
	if self.channel then
		self.channel:unsubscribe()
		self.channel = nil
	end
	local channel = multicast.new{
		channel = channel_id,
		dispatch = function(channel, source, data)
			--do some thing
		end
	}
	self.channel = channel
end
```
这是个教训，挺低级的一个错误，接口重入没处理好
