### ISSUE TITLE
timer_shift 问题

### ISSUE THREAD

**Issue by suzuiyuegjy** [cloudwu/skynet#641]
当`T->time`为32位无符号整数的最大值时，下一次+1, 它会变成0， 代码里在这种情况下的处理是将T->t[3][0]的timer_node 移除然后重新添加到计时器队列里。
考虑一下一下特殊情况， 当`T->time` 时间为 0000 0000 0000 0000 0000 0001 0000 0000时，添加一个timer_node，其`expire_time`为0000 0000 0000 0000 0000 0000 0000 0001时，它高18位和当前时间高18位相同，所有应该会被添加到T->t[0][0]中， 之后T->time值增加，T->t[0][0]也不会被移除重新添加到timer。当`T->time`变为0时，也只会重新添加t[3][0], 该节点拥有不会被处理。
根据我的理解，skynet里是将时间由近及远分为五个等级来处理，但是如果时间小于当前时间(无符号加法溢出)，实际上应该是距离当前时间最远的，可以将其加入到t[3][0],这样就可以正确处理。
也有可能是我代码有地方理解错误了，希望大家可以指出，谢谢。

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/issues/584

**Comment by suzuiyuegjy** [comment]
如果`T->time`最高位是0的话，由于设置时间是int，且不能为负数，最高位一定是0，`expiretime`不会溢出, 如果`T->time`最高位是1，溢出之后最高位一定是0，`T->time`与`exporetime`最高位一定不同，所有一定会被分配到t[3][0]list里，所有没有问题，多谢。

**Comment by suzuiyuegjy** [comment]
超时设置时传入的time参数为int类型，且负数时直接返回，只有time是正数时才会添加到timer中，`T->time`最高位为0时，`expiretime`不会溢出。当`T->time`最高位为1时，'expiretime'可能溢出，但溢出后最高位肯定为0， 所以这两个时间最高位肯定不相等，会被加入到`T->t[3]`中，ct==0时, 重新添加T->t[3][0]的节点, t[3][i]的节点也会在之后更新`T->time`时得到处理。所以没有问题。
