### ISSUE TITLE
gateserver突然出现大量不存在的socket fd的close事件。服务器基本瘫痪。

### ISSUE THREAD

**Issue by piouswolf** [cloudwu/skynet#642]
使用的是gate方式。gateserver中注册：
```
skynet.register_protocol {
		name = "socket",
		id = skynet.PTYPE_SOCKET,	-- PTYPE_SOCKET = 6
		unpack = function ( msg, sz )
			return netpack.filter( queue, msg, sz)
		end,
		dispatch = function (_, _, q, type, ...)
			queue = q
			if type then
				MSG[type](...)
			end
		end
	}
```
function MSG.close(fd)突然被大量调用。但是fd却是无效的，没有出现在watchdog的连接记录中。
有效/无效的fd是都是连续的。
这种事件，应该是服务器主动关闭socket的。
服务器一直都运行得比较稳健。这是突然出现的。
比对了版本代码，没发现近期修改有影响的代码。（也可能是我没能看出来。按理修改都是业务，没有涉及到框架。）

以下是错误日志：
```
[:0000019b] New client from:  180.241.133.121:23777 86471 64370 Thu May 25 06:16:20 2017 334（有效链接占据了64370）
[:0000019b] socket close 64371（非法的fd 64371是跟着递增的）
[:0000019b] lua call [19c to :19b : 0 msgsz = 16] error : ^[[31m./lualib/skynet.lua:516: ./lualib/skynet.lua:155: ./lualib/skynet.lua:382: dest address type (nil) must be a string or number.
stack traceback:
        [C]: in function 'skynet.core.send'
        ./lualib/skynet.lua:382: in function 'skynet.manager.call'
        ./hgame/watchdog.lua:41: in upvalue 'close_agent'
        ./hgame/watchdog.lua:64: in local 'f'
        ./hgame/watchdog.lua:157: in upvalue 'f'
        ./lualib/skynet.lua:109: in function <./lualib/skynet.lua:103>
stack traceback:
        [C]: in function 'assert'
        ./lualib/skynet.lua:516: in function 'skynet.manager.dispatch_message'
[:0000019b] New client from:  180.241.133.121:23777 86471 64370 Thu May 25 06:16:20 2017 334
[:0000019b] socket close 64372（又是非法fd的close事件，大量出现）
[:0000019b] lua call [19c to :19b : 0 msgsz = 16] error : ^[[31m./lualib/skynet.lua:516: ./lualib/skynet.lua:155: ./lualib/skynet.lua:382: dest address type (nil) must be a string or number.
stack traceback:
        [C]: in function 'skynet.core.send'
        ./lualib/skynet.lua:382: in function 'skynet.manager.call'
        ./hgame/watchdog.lua:41: in upvalue 'close_agent'
        ./hgame/watchdog.lua:64: in local 'f'
        ./hgame/watchdog.lua:157: in upvalue 'f'
        ./lualib/skynet.lua:109: in function <./lualib/skynet.lua:103>
stack traceback:
        [C]: in function 'assert'
        ./lualib/skynet.lua:516: in function 'skynet.manager.dispatch_message'
```

**Comment by cloudwu** [comment]
1. 根据这个无法确定问题。
2. 可以排查一下消息从 `skynet_socket.c` 发出去的时候是否正常。即在这个文件中 `SKYNET_SOCKET_TYPE_CLOSE` 这类消息是否真的是由它发出；这可以确定是发出方的问题，还是消息在内部传输过程中被篡改。
3. 这里的 fd 是 skynet 赋予的 id 不是系统 fd 。如果有机会用 gdb 或自己加 printf 可以看看 `skynet_socket.c` 中定义的全局变量 `SOCKET_SERVER` ，里面有所有的 socket 相关的信息。其全部 socket 都在这样一个数组中 `struct socket slot[MAX_SOCKET];` 非常容易用 gdb 查看。你还可以在 socket 创建处看看是否创建过。

**Comment by piouswolf** [comment]
skynet.register_protocol {
		name = "socket",
		id = skynet.PTYPE_SOCKET,	-- PTYPE_SOCKET = 6
		unpack = function ( msg, sz )
			return netpack.filter( queue, msg, sz)
		end,
		dispatch = function (source, session, q, type, ...)
			queue = q
			if type then
				MSG[type](...)
			end
		end
	}

skynet_socket.c中：
struct skynet_message message;
message.source = 0;
message.session = 0;
message.data = sm;
message.sz = sz | ((size_t)PTYPE_SOCKET << MESSAGE_TYPE_SHIFT);

监控dispatch 的source/session值，能否说明消息是否是从skynet_socket.c中发过来的？
传输过程中，source/session是不会被修改的吧？

**Comment by piouswolf** [comment]
skynet.register_protocol {
name = "socket",
id = skynet.PTYPE_SOCKET,	-- PTYPE_SOCKET = 6
unpack = function ( msg, sz )
return netpack.filter( queue, msg, sz)
end,
dispatch = function (source, session, q, type, ...)
queue = q
if type then
MSG[type](...)
end
end
}

skynet_socket.c中：
struct skynet_message message;
message.source = 0;
message.session = 0;
message.data = sm;
message.sz = sz | ((size_t)PTYPE_SOCKET << MESSAGE_TYPE_SHIFT);

监控dispatch 的source/session值，能否说明消息是否是从skynet_socket.c中发过来的？
传输过程中，source/session是不会被修改的吧？

**Comment by cloudwu** [comment]
1. 贴代码请看 https://guides.github.com/features/mastering-markdown/ ，学一下 markdown 。
2. 作为不正常的情况，多加 log 调试，确定真正的问题源头。

**Comment by piouswolf** [comment]
第一次提issue。
正在加log调试。
感谢！

**Comment by piouswolf** [comment]
skynet日志，大量socket close：
[:0000019b] socket close 119938
[:0000019b] socket close 119939
[:0000019b] socket close 119940
[:0000019b] socket close **119941**


gdb打印的信息，只贴了开头一部分，后面的大致重复：
(gdb) p *SOCKET_SERVER
$4 = {
  recvctrl_fd = 5, 
  sendctrl_fd = 6, 
  checkctrl = 0, 
  event_fd = 4, 
  alloc_id = **119941**, 
  event_n = 1, 
  event_index = 1, 
  soi = {
    buffer = 0x0, 
    size = 0x0, 
    free = 0x0
  }, 
  ev = {{
      s = 0x0, 
      read = true, 
      write = false
    }, {
      s = 0x7f4e22200758, 
      read = true, 
      write = false
    }, {
      s = 0x7f4e22200938, 
      read = true, 
      write = false
    }, {
      s = 0x7f4e22200758, 
      read = true, 
      write = false
    }, {
      s = 0x7f4e22200988, 
      read = true, 
      write = false
    }, {
      s = 0x7f4e22200758, 
      read = true, 
      write = false
    }, {
      s = 0x7f4e222007f8, 
      read = true, 
      write = false
    }, {
      s = 0x7f4e226dbfe8, 
      read = true, 
      write = false
    }, {
      s = 0x7f4e222006b8, 
      read = true, 
      write = false
    }, {
      s = 0x0, 
      read = false, 
      write = false
    } <repeats 55 times>}, 
  slot = {{
      opaque = 412, 
      high = {
        head = 0x0, 
        tail = 0x0
      }, 
      low = {
        head = 0x0, 
        tail = 0x0
      }, 
      wb_size = 0, 
      fd = 361, 
      id = 65536, 
      protocol = 0, 
      type = 0, 
      p = {
        size = 64, 
        udp_address = "@", '\000' <repeats 17 times>
      }
    }, {
      opaque = 412, 
      high = {
        head = 0x0, 
        tail = 0x0
      }, 
      low = {
        head = 0x0, 
        tail = 0x0
      }, 
      wb_size = 0, 
      fd = 361, 
      id = 65537, 
      protocol = 0, 
      type = 0, 
      p = {
        size = 64, 
        udp_address = "@", '\000' <repeats 17 times>
      }
    }, {
      opaque = 10, 
      high = {
        head = 0x0, 
        tail = 0x0
      }, 
      low = {
        head = 0x0, 
        tail = 0x0
      }, 
      wb_size = 0, 
      fd = 7, 
      id = 2, 
      protocol = 0, 
      type = 3, 
      p = {

**Comment by cloudwu** [comment]
again: https://guides.github.com/features/mastering-markdown/ , 参考 https://github.com/cloudwu/skynet/issues/644 是怎样贴 log 的。

**Comment by piouswolf** [comment]
手动生成了core文件。
SOCKET_SERVER->alloc_id确实是这么大的。
但是lua层却没看到有那么多链接进来。
看起来是产生了大量的非法fd。

**Comment by tangyiyang** [comment]
你先描述清楚你的问题，大家才能帮你看啊。


2017-05-27 14:50 GMT+08:00 piouswolf <notifications@github.com>:

**Comment by piouswolf** [comment]
错误信息/错误描述/堆栈我都写了啊……

服务器运行了几天，突然触发大量关闭socket事件，导致服务器基本瘫痪。
lua层接收到的socket close fd都是没有连接记录的。
结合堆栈可以看到socket fd确实是存在的SOCKET_SERVER->alloc_id。而且，不断的递增，然后发送close事件到lua层。

**Comment by cloudwu** [comment]
供参考： close 事件通常是在 send 出错的时候从底层抛出的。可以 grep `SOCKET_CLOSE` 查看代码中那些地方会制造这个事件。

可以在 C 层多加些 log 来确定问题。可以确定一下这些 fd 是如何创建出来，并加入 epoll 的。

**Comment by piouswolf** [comment]
好的。
感谢！
我再细细琢磨琢磨代码吧。

**Comment by piouswolf** [comment]
问题已找到。skynet很稳定，是我们自己使用的问题！


使用的是gate方式，并设置maxclient = 1024 * 5。
由于，我们做了链接的合法性验证。如果非法，服务器会主动调用gateserver.closeclient(fd)把该链接关闭。
但是gateserver.closeclient(fd)没有调用close_fd(fd)，所以client_number没有被相应减少。
所以，随着时间的积累，client_number会比实际在线值大得越来越多（client_number越来越接近maxclient）。
最后会出现MSG.open的时候直接关闭新到来的连接请求。
```
        function MSG.open(fd, msg)
                if client_number >= maxclient then
		        socketdriver.close(fd)
			return
	        end
                ...
	end
```

```
        function gateserver.closeclient(fd)
	        local c = connection[fd]
	        if c then
		        connection[fd] = nil
		        socketdriver.close(fd)
	        end
        end
        ...
        local function close_fd(fd)
		local c = connection[fd]
		if c ~= nil then
			connection[fd] = nil
			client_number = client_number - 1
		end
	end

	function MSG.close(fd)
		if fd ~= socket then
			if handler.disconnect then
				handler.disconnect(fd)
			end
			close_fd(fd)
		else
			socket = nil
		end
	end

	function MSG.error(fd, msg)
		if fd == socket then
			socketdriver.close(fd)
			skynet.error(msg)
		else
			if handler.error then
				handler.error(fd, msg)
			end
			close_fd(fd)
		end
	end
```


MSG.close(fd)或者MSG.error(fd, msg)都会调用close_fd(fd)，从而把client_number减1。


感谢云大指导！

**Comment by piouswolf** [comment]
考虑转换成service_package方式。
有疑问顺便请教一下：
1. 想抛弃socket_proxyd，在连接请求到来以后，在agent中由agent自己去skynet.launch("package", skynet.self(), fd)进行注册是否可以？
2. 读取消息的时候，每个agent都fork一个协程，自己只管读自己的消息，这种方式是否正确？

skynet.fork(function()
        while true do
            local ok, s, size = pcall(read, client_fd)

            if not ok then
                    skynet.error("socket CLOSE",  address_package,  client_fd,  client_pid)
                    break
            end

            if s == "quit" then
                    skynet.error("agent quit", address_package, client_fd, client_pid)
                    break
            end
        
            pcall(request,  host:dispatch(s, size))
        end

        skynet.send(address_package, "text", "K")
        ...
    end)

**Comment by cloudwu** [comment]
1. 我认为去掉 `socket_proxyd` 后就失去了一个统一监控和管理的地方。

2. 没有什么问题。

**Comment by piouswolf** [comment]
感谢！！！
