### ISSUE TITLE
求分享skynet实际运行数据

### ISSUE THREAD

**Issue by fonzieyang** [cloudwu/skynet#643]
可以将项目名称匿名，然后列出 机器配置+服务器厂商(如果有，比如阿里云)+承载人数+游戏类型+....等等等等

**Comment by chenzuo** [comment]
我也想看一下实际数据：）

**Comment by PolarSnow** [comment]
云风已经有项目上线了，你们连百度都不会用么

**Comment by fonzieyang** [comment]
首先百度数据不够精细，另外云风自己（因为是作者）的项目不太具有参考意义。

**Comment by antsmallant** [comment]
一个全区全服游戏，25w在线。
耗cpu、耗内存，配置就不贴了。
但有bug可以极其方便的hotfix，无论是clearcache或inject都很方便。
一次也没coredump过，这点很完美。

**Comment by wjx0912** [comment]
我也想知道，因为新手可能没有多少概念。比如1000人200桌的斗地主，只有一个skynet节点，
会有多少个lua虚拟机，多少个协程，cpu和内存网络带宽什么配置合适？
有做过的大侠帮忙回答下。谢啦

**Comment by chenzuo** [comment]
希望能有一个架构图示，能否有一个实践的图示最好。都想学习一下。

________________________________
chenzuo@hotmail.com

发件人： 拥剑公子<mailto:notifications@github.com>
发送时间： 2017-09-28 11:08
收件人： cloudwu/skynet<mailto:skynet@noreply.github.com>
抄送： chenzuo<mailto:chenzuo@hotmail.com>; Comment<mailto:comment@noreply.github.com>
主题： Re: [cloudwu/skynet] 求分享skynet实际运行数据 (#643)

我也想知道，因为新手可能没有多少概念。比如1000人200桌的斗地主，只有一个skynet节点，
会有多少个lua虚拟机，多少个协程，cpu和内存网络带宽什么配置合适？
有做过的大侠帮忙回答下。谢啦
