### ISSUE TITLE
疑似的空指针使用问题

### ISSUE THREAD

**Issue by richardxx** [cloudwu/skynet#645]
问题所在位置和触发途径如下图所示：

![image](https://cloud.githubusercontent.com/assets/1880553/26662521/ff5d2448-46b6-11e7-8dc3-5ef5dbf6ae8f.png)

大体问题就是：databuffer.h的[83行](https://github.com/cloudwu/skynet/blob/master/service-src/databuffer.h#L83) 函数调用可能将db->head清空，然后回到循环头后， 最终[70行](https://github.com/cloudwu/skynet/blob/master/service-src/databuffer.h#L70)的current指针从db->head拿到了空指针并使用。

这是我们的自动工具找到的一个高度疑似问题，希望开发人员看一看。

**Comment by cloudwu** [comment]
工具还需要加强 :)

这个函数的逻辑人来看是非常清晰的：

`databuffer_read` 的作用是从 db 中读出 sz 个字节，首先需要 db 中有这么多字节可以读，所以在 66 行有 `assert(db->size >= sz);` ，这个约束条件是其它部分来保证的。

这个 for(;;) 循环的意义是，不断的从 db 的链表中读出若干字节，直到读够了 sz 个。所以在前两个条件分支都有 return ；而怀疑有问题的第三分支是指 db 的链表中的当前节点上的字节数不够 sz 个，所以只读取一部分。

既然 当前节点 current 上的字节数 < sz ，而前面又保证了 `db->size >= sz` ，所以 current 一定不是 db 内部链表的最后一个节点，这样 `_return_message` 里的 m->next 就不可能为 NULL 了。

**Comment by richardxx** [comment]
@cloudwu 多谢解释 :+1: 

工具要精确判定这个问题需要知道一个很重要的隐藏条件，即db->size就是所有链表元素的size之和。这个很有难度能自动从程序中判定出来。

**Comment by cloudwu** [comment]
从已有的 assert  条件，或是增加 assert 是否可以帮助推导？

**Comment by yangchao1p** [comment]
什么工具了，能否分享一下？

发自我的 iPhone

在 2017年6月6日，17:42，Xiao Xiao <notifications@github.com<mailto:notifications@github.com>> 写道：


@cloudwu<https://github.com/cloudwu> 多谢解释 👍

工具要精确判定这个问题需要知道一个很重要的隐藏条件，即db->size就是所有链表元素的size之和。这个很有难度能自动从程序中判定出来。

**Comment by richardxx** [comment]
@cloudwu 

assert条件我们都是有使用的。但工具需要两个关键条件从这段代码没法自动化推理到：

1. db->size >= current->size;
2. 链表元素个数和sz的关系，即：current->size < sz => db->head->next != nullptr

而上面两个条件要知道，就需要自动推理出这个链表是一个分段的buffer，然后db->size = 所有链表元素的size之和。除非人工标注这个数据结构的不变量，否则自动化工具很难搞定这段代码的verification。

**Comment by richardxx** [comment]
@yangchao1p 

我们自己开发的一个程序分析工具：www.sourcebrella.com

**Comment by cloudwu** [comment]
@richardxx 机器推导是不容易，但是我还是从人阅读代码的角度尝试分析一下：

一个小问题：这里 db->size 并不是所有 m->size 之和，而是所有 m->size 之和减去 db->offset 。

这里 db->size db->offset 和所有 m->size 起始值都是 0 。

修改 db->size 的地方并不多，一处在 https://github.com/cloudwu/skynet/blob/master/service-src/databuffer.h#L113-L115 ，这里把 db->size 累加了 sz ，同时给链表加了新节点并把 m->size 也赋为 sz 。

另一个地方是 https://github.com/cloudwu/skynet/blob/master/service-src/databuffer.h#L67 把 db->size 减了 sz ，下面的循环不断地减少链表，也就是减少每个节点的 m->size 直到减到接近 sz ，再把插值补到 db->offset 上。

我觉得最后这个环节不太好推导，但并非理论上不可行。

这段代码不算太复杂（像 m->size 除了初始化值和清零都没有别的操作）可以做个测试案例。

**Comment by richardxx** [comment]
@cloudwu 对，我们的工具其实就尽可能的在模拟人的思考方式去推理程序的行为。但人和机器有个很大的鸿沟难以越过。就像你的分析过程，人在推导的时候首先对代码所操作的数据结构有一个概念性的理解，其次人可以抽象出只对理解问题所需要的代码片段进行分析，再者人可以得到一个代码片段精确的语义描述，从而组建起对整个代码的精确理解。

但对于机器来说，输入的是整个skynet程序，它首先不能很好的建立起数据结构的概念，而只能建立在每个程序点上内存状态的概念（把内存想象成一个很大的数组M，M[i]表示内存中第i个位置的值， 程序分析的结果就是这个M[i]可能的取值，注意是可能的，而不是肯定的）。其次由于对数据结构的操作几乎涉及到循环和递归，由于图灵停机问题的理论限制，in general计算一个确定的数学公式描述循环对内存操作的效果是不可能的。所以除非人为的限定问题的范围和给一些提示，否则你说到的那个不好推倒的环节是基本上推不出来的。

当然，其实因为你是作者所以你能很快的明白我报告的问题不成立。而我其实在提交issue前看了很久也没有发现问题的关键，这也说明其实人来分析这个问题也不是那么容易的，:>。

最后，非常感谢你的详细讨论。我也会持续改进工具，争取发现更深的问题。

**Comment by cloudwu** [comment]
skynet 或许是个还不错的测试案例，因为我尽量将模块分离了。就好像这个例子，其实不会和别的源文件产生关系。这样分析复杂度不会太高。

这个问题本身的确没有那么明显，因为我写的时候就已经意识到这里有一些隐晦。但是没想好怎么更好的写assert 。

因为我本来就考虑过这个问题，所以可以立刻回想起来。我希望代码都能写成明显没有bug ，换句话说也就是可以用简单的手段分析。用这个标准，这里是不合格的。不过这个模块其实已经用 lua 重写过了，留在这里只是为了兼容，所以就不太理会。
