### ISSUE TITLE
luaclib 中的部分动态库不可用问题

### ISSUE THREAD

**Issue by xhwfish** [cloudwu/skynet#655]
新版的 skynet 整合了命名空间暴露出 luaclib 中部分动态库不可用问题

https://github.com/cloudwu/skynet/blob/master/examples/login/client.lua#L4

在新版应该换成
`local crypt = require "skynet.crypt"`

执行的时候会报错
lua: error loading module 'skynet.crypt' from file 'luaclib/skynet.so':
	luaclib/skynet.so: undefined symbol: dump_mem_lua

需要在生成 skynet.so 的时候需要引入 mallock_hook.c ，但后续还有其他实现缺失的报错

其实在老版本的 skynet 也有那么几个库是不能单独被 require 使用的，不过因为各个库是分开的，没有被引入用到也就没发现，经测试 lua-skynet.c lua-memory.c lua-socket.c 对应的几个库是不能单独直接用的，专门为了这几个库的健康可用修改一下编译文件也行

目前粗暴的建议是反正不支持单独 require 使用，不如直接剔除掉，生成 skynet.so 的时候直接去掉上面的几个部分，skynet.so 就健康可用了

**Comment by cloudwu** [comment]
要去掉的其实是 client

**Comment by xhwfish** [comment]
刚才光顾着这边的错误信息了，确实砍掉那些库，主程序都没法跑了😂，client要用单独编译一个crypt就好

**Comment by cloudwu** [comment]
先把 crypt 复制一份到了 client 下，clientsocket 改为 client.socket 。

麻烦再帮忙看一下。

**Comment by xhwfish** [comment]
新版正常没问题👌
