### ISSUE TITLE
最新版本require "skynet"报错

### ISSUE THREAD

**Issue by korialuo** [cloudwu/skynet#656]
MacBook-Pro:skynet korialuo$ ./skynet examples/config
[:01000001] LAUNCH logger 
[:01000002] LAUNCH snlua bootstrap
[:01000002] lua loader error : error loading module 'skynet.core' from file './luaclib/skynet.so':
	dlopen(./luaclib/skynet.so, 6): Symbol not found: _BIO_free_all
  Referenced from: ./luaclib/skynet.so
  Expected in: flat namespace
 in ./luaclib/skynet.so
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	./lualib/skynet.lua:2: in main chunk
	[C]: in function 'require'
	./service/bootstrap.lua:1: in local 'main'
	./lualib/loader.lua:48: in main chunk
[:01000002] KILL self

这是在macOS 10.12.5 下用系统自带的clang编译器编译的.
 _BIO_free_all 这个我不了解。

**Comment by YongHaoWu** [comment]
10.12.4 (16E195) 正常
```
$ CC --version
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by cloudwu** [comment]
`_BIO_free_all` 是否是这个？ https://linux.die.net/man/3/bio_free_all

现在并没有链接 openssl 。

**Comment by korialuo** [comment]
哦，我自己fork出来的工程里面，添加了https支持，链接了openssl库。我研究下怎么解决。
