### ISSUE TITLE
关于skynet内存hook

### ISSUE THREAD

**Issue by linxiaolong** [cloudwu/skynet#666]
使用debug_console mem+cmem统计出的内存占用和top rss显示的出入很大，往往mem+cmem 1G不到，而top rss却可以到4G。而实际上按内存hook的使用，目前应该除了lua vm的内存分配器不在统计范围内，算是覆盖了整个进程的内存使用，这种出入不太合理？

**Comment by cloudwu** [comment]
默认 jemalloc 的话，可用 skynet.memory.dumpinfo() 查看 jemalloc 的报告。目前默认情况，进程所有内存分配都被 jemalloc 接管。

一般情况下，除开分配器保留给以后使用（所谓内存池）外，有效利用内存占物理内存的 50%~60% 左右都是合理的。正常内存分配器会产生接近 50% 的不可利用碎片及自身占用的元信息。

**Comment by linxiaolong** [comment]
从jemalloc的分析报告来说，基本跟top rss是一致的。从整体内存使用来说，对比mem和cmem输出，观察了一段时间，基本排除内存泄漏可能性，确实更像是内存池/内存碎片等因素影响。不过在观察过程中，有个现象有些疑惑，现象：一批玩家登陆，此时内存top rss上升，然后把这批玩家登出并强制执行lua gc，此时内存top rss下降，至此正常，但稍过一段时间top rss会持续上升到一个阈值然后基本稳定，这个阈值会略低于之前内存使用的阈值。关于这个现象，我自己的猜测是jemalloc基于内存分配的某种设定或者优化导致，但总感觉不太合理，这里想咨询一下云风的看法。

**Comment by linxiaolong** [comment]
从jemalloc的分析报告来说，基本跟top rss是一致的。从整体内存使用来说，对比mem和cmem输出，观察了一段时间，基本排除内存泄漏可能性，确实更像是内存池/内存碎片等因素影响。不过在观察过程中，有个现象有些疑惑，现象：一批玩家登陆，此时内存top rss上升，然后把这批玩家登出并强制执行lua gc，此时内存top rss下降，至此正常，但稍过一段时间top rss会持续上升到一个阈值然后基本稳定，这个阈值会略低于之前内存使用的峰值。关于这个现象，我自己的猜测是jemalloc基于内存分配的某种设定或者优化导致，但总感觉不太合理，这里想咨询一下云风的看法。

**Comment by cloudwu** [comment]
jemalloc 会将整页闲置内存 munmap 掉，但不可能 munmap 不连续内存，只能留待以后使用。

批量申请和释放内存更可能归还一些整页连续的闲置内存。

**Comment by linxiaolong** [comment]
我后续继续观察一下
