### ISSUE TITLE
mongo存储数据发生丢失数据

### ISSUE THREAD

**Issue by Fayman** [cloudwu/skynet#668]
如题。查了一下，是lua-bson.c的write_string函数调用了utf8_copy没有正确拷贝数据导致内容丢失。而这个string是使用skynet.packstring序列化出来的字串，猜测是由于不符合utf8而导致其没能正确被打包导致数据丢失。我暂时的解决办法是把lua-bson.c回滚到上一个版本了(直接使用memcopy)。

**Comment by cloudwu** [comment]
skynet.packstring 的返回结果不是 utf8 串，不符合 mongo 标准。mongo / bson  区分了 utf8 string 类型和 bnary 串类型。

`utf8_copy` 现在如果发现错误的字符串，会 raise error 。

如果硬写到 mongo 会导致其它语言的 driver 读不出来。

binary 字符串应该用 bson.binary(blob) 转换，读出来的时候应该用 bson.type 转换为 binary 串。

**Comment by Fayman** [comment]
谢谢云大的建议，增加bson.binary处理的确会比较合理一点。

**Comment by lrh** [comment]
@cloudwu 云大你好，我也遇到类似问题，是普通utf8字符串，保存时被自动分割成最长每段字符串256字节，边缘的utf8字符可能被拆散，导致utf8_copy判断整个字符格式时返回错误，这里会不会是用回以前直接拷贝的方法比较好

**Comment by cloudwu** [comment]
你应该用正确的算法切割 utf8 string, 不能按字节截断。

**Comment by lrh** [comment]
不是我切的😂，传到bson_encode函数后自动切的，具体位置我还没找到

**Comment by cloudwu** [comment]
那样就是 bug , 最好能给个测试数据。

**Comment by lrh** [comment]
最新版本测试没问题，出问题代码是上一个版本的，也有修改过，我再看看

**Comment by hanxi** [comment]
https://github.com/cloudwu/skynet/blob/master/3rd/lua/lutf8lib.c#L57-L84

lua5.4 更新了 utf8 的范围， `utf8_copy` 是否需要更新？

**Comment by cloudwu** [comment]
这个问题是不正确的 utf8 的问题。要求合法的 utf8 是 mongo 的约定。lua 5.4 只是兼容畸形的 utf8 串而已。
