### ISSUE TITLE
最新的skynet更新内容？同一个skynet服务里面如果两次require “socket” 包错！！！

### ISSUE THREAD

**Issue by sctangqiang** [cloudwu/skynet#669]
1.请问云大，skynet有什么更新内容， 出于什么考虑做了些调整？

2.在同一个skynet服务里面如果先后require "socket" 和require "http.httpc"会报错, 报错位置是
function skynet.register_protocol(class)
	local name = class.name
	local id = class.id
	assert(proto[name] == nil and proto[id] == nil)       这个位置assert了
	assert(type(name) == "string" and type(id) == "number" and id >=0 and id <=255)
	proto[name] = class
	proto[id] = class
end

看代码原因是socket里面会注册 一个SOCKET协议， 同时httpc里面引用的模块最终也会require “socket” 注册一个SOCKET协议， 这样就出发了上面的assert， 我讲上面的assert修改以后就不会报错了，让我比较疑惑的是，我的老版本skynet为什么不会出错？

**Comment by cloudwu** [comment]
1. skynet 的开发可以看我的 blog 上 skynet 标签：http://blog.codingnow.com/eo/skynet/

2. 你更新后没有清理老的库文件，目前 socket 已经更名为 skynet.socket 。需要兼容需要加 compat10 路径。
