### ISSUE TITLE
再问两个cluster节点之间请求，通知顺序问题

### ISSUE THREAD

**Issue by feihuroger** [cloudwu/skynet#681]
cluster之间调用是双向的，也就是A->B 和 B->A 是两个socket通道。
对于一种简单的请求+后续广播的需求，遇到了消息到达顺序问题。

之前看到了这个讨论：https://github.com/cloudwu/skynet/issues/576
基本和我的问题一致，文中的方案可以解决，但总感觉应该有更好的设计方法
来解决，或者之前自己被绕的设计想法不对。

简化一下例子描述，
一个节点是gate（所有玩家的agent都在其中）简称G
一个节点是 room。 简称R

当一个agent进入room的时候，调用room上enter接口，是从 G->R 的socket调用
enter接口先给这个agent返回"进入OK"，是从G->R 的socket返回的。
enter接口然后调用room里的其他服务，其他服务处理完成后，给这个room里的所
有玩家发“通知”（包括刚才新进room的agent），这些通知消息是从 R->G 的socket发送的。

对于gate上的这个agent，它是从 G->R 的socket获得“进入OK”，从 R->G 的socket获得“通知”

按预期，应该是“进入OK” 比 “通知” 要先到达。但因为通过room里的不同的服务处理，通过两个不同socket传输，所以有时“通知”比“进入OK”要先到达这个agent。

有什么好的设计或者实现方式，可以让对于gate上的这个agent，能先收到“进入OK”，再收到“通知”。让代码编写简单，简洁一些。

**Comment by cloudwu** [comment]
最简单的方法是不要推送，一切都要等接收方回应。

这样你就可以简单的在 "进入OK" 这件事情得到确切回应后，才会发起 "通知" 。

**Comment by feihuroger** [comment]
gate上的agent收到“进入OK”的回应，然后再调用room上的接口，让room去发通知。
