### ISSUE TITLE
mongo driver的mongo_auth问题

### ISSUE THREAD

**Issue by linxiaolong** [cloudwu/skynet#684]
[https://github.com/cloudwu/skynet/blob/master/lualib/skynet/db/mongo.lua](url)
_        有个问题确定下：
        mongo3.4版本，目前采用了master-slave架构，有部分进程直接访问slave库，按以上代码会执行到120行的分支，但rs_data.me属性只有采用replica-sets复制集才会拥有，所以会报错。目前我这边改成master-slave模式的必然只走108分支。_

**Comment by cloudwu** [comment]
不清楚 master-slave 怎么处理。不过根据 mongo 的文档 https://docs.mongodb.com/manual/core/master-slave/  master-slave 模式 Deprecated since version 3.2

**Comment by linxiaolong** [comment]
嗯，官网有说丢弃master-slave这个特性，不过实际上还是可以按master-slave部署，如果原生master-slave方式，则该driver必然会报错。云风是考虑兼容原生master-slave部署，还是推荐使用复制集来实现master-slave，driver不管这个事情？

**Comment by cloudwu** [comment]
这一块是包子做的，其实我不懂这个地方的协议。如果要支持 master-slave 需要把这里的协议搞清楚才能写 driver 。

**Comment by linxiaolong** [comment]
我考虑转成复制集来实现master-slave。但我看了下代码，这个driver所有对secondary的读写目前应该都是被路由到primary，就算是secondary已经设置了可读，这应该不满足很多依赖该特性的常见需求（譬如部分进程直接访问secondary库），晚点验证一下。

**Comment by bttscut** [comment]
我是看了这个issue才知道mongodb有个master/slave模式，但是replica set显然是更先进的集群模式，我觉得我们又不是通用的driver，直接不支持就好了。
之前我做这的时候，目的就一个，就是容灾。并没有完整支持replica set的完整特性。
读写分离的话，我个人认为在mongodb已经支持多线程，并且支持了collection级别的锁之后，在游戏逻辑相关的db应用中，问题都不大，但是如果严重依赖读写分离的特性的话，要么就直接配置secondary的地址来进行访问，或者完善driver支持read preference

**Comment by cloudwu** [comment]
@linxiaolong  如果有想法改进 driver 的话，可以试着提个 PR 。

btw, 1.1.0 计划在下周封版，目前这个版本算 RC 。

**Comment by linxiaolong** [comment]
@bttscut，目前版本的driver尝试了采取replica set，假设skynet进程直接配置secondary地址进行访问，按目前逻辑会changehost到primary

@cloudwu，等了解这方面协议会尝试完善这个driver的replica set特性，目前在游戏应用这边反而不期望有这个特性，所以暂时在自己分支完整去掉了replica set特性
