### ISSUE TITLE
socket 模块 direct write 锁临界问题

### ISSUE THREAD

**Issue by harrywong** [cloudwu/skynet#691]
skynet-src/socket_server.c 中L1501处，是先写入事件，再释放锁，然后在L725处，有判断如果不能进入锁，就返回，有没有种可能，写入事件，然后执行send_buffer，未进入锁，然后L1503处释放，导致dw_buffer未被写入。下次dw_buffer有可能被覆盖的错误？

**Comment by cloudwu** [comment]
dw_buffer 未被写入，是由锁来保证禁止覆盖的。和这里注册写事件到 epoll 中无关。

注册写事件必须被锁保护，以防止关闭 fd 之后注册了已关闭的 fd 。

**Comment by harrywong** [comment]
那是否有可能注册写事件，然后socket thread执行send_buffer，此时未释放锁，导致此次写入未执行的情况？

**Comment by cloudwu** [comment]
写事件未处理，会不断触发。

**Comment by harrywong** [comment]
看明白了，谢谢云大。
