### ISSUE TITLE
这代码真不忍看

### ISSUE THREAD

**Issue by rotencode** [cloudwu/skynet#693]
什么东西都自己造个轮子，这样真的好么？代码还没有严格的工程化风格。各种不同含义的int不能用typedef重命名一下？看的不是一般的难受。c里面还硬编码了lua代码。用c++可以不超过2000行代码，用go可以不超过500行代码搞定的事，结果整出数万行代码。

c调用那么多lua vm的代码好么？lua vm和c互相调用，简直和机房的布线一样乱。连个流程文档都没有。

现在为止，没有一个ide支持makefile，该换了。要不要我pr一个cmake？

**Comment by ChrisPei** [comment]
？

**Comment by harrywong** [comment]
特意开个issue砸场子？觉得不忍看不要看就是了。

**Comment by jonesgithub** [comment]
搬凳子去了。

**Comment by diandian-xue** [comment]
你说的不忍心看到项目，现在已经5k+ star， 2k+ fork。 你写过一个忍心看的项目超过10个star的？

**Comment by mskmkt0704** [comment]
看你这吐槽 你是用C++的吧

**Comment by cloudfreexiao** [comment]
看你这吐槽 你是用C++的吧

**Comment by dingmingxin** [comment]
看你这吐槽 你是用C++的吧

**Comment by rotencode** [comment]
@harrywong 

我只是说，这工程并没有别人吹的那么好。这个库的代码我看了一周，整个流程反复跟了几遍才知道意图，你可以说我技术不行。lua-skynet.c这个主要代码，我花了两天，还没太理解这个文件在整个工程中的作用。反过来，我要是是企业老板，我会觉得是写代码的人有问题，好的代码应该很容易看明白，不容易明白就把文档写的容易明白。

光一个读取配置的问题，没有必要用lua代码，我跟了一天代码，才意识到这config就是一个lua代码，难怪一个配置文件也是各种lua vm交互。简单的事情复杂化，越复杂越难保证正确。如果写c的人都有简单问题复杂化的习惯，那我建议所有企业都不要招c开发人员。

全部的c代码，所有场合的void *都没有区别用途，ide不能推导void *，全靠人根据上下文来理解。用typedef重命名一下，代码可读性会瞬间提升。这个问题到处都是。

加cmake是因为clion/qt/vs等工具可以使用，简单省事的跟代码快捷有效。炫技狂魔肯定会说有vi不需要ide，当我没说。

软件工程不是炫耀技术的事情，而应该考虑开发简易度，故障排查复杂度，维护简易度。如果不理解这行字的人回复我，我会无视。

这个库用在企业线上环境，是需要勇气的。

**Comment by harrywong** [comment]
@rotencode 

你可能没怎么接触过 lua 嵌入的项目，lua 用作 config 配置是惯用法，而且 lua 官方也将这个作为一个适用优势来宣传。

lua-skynet.c 一共也就不到 400 行，就是把 skynet 核心的方法导出到 lua 中，如果了解 skynet 要解决的问题和使用方式，没有什么难理解的。

c 代码中使用 void * 是很常见的，这和 C++ 不同。

加不加 CMake 没意义的，skynet 的 Makefile 很简单，已经足够了，需要的话加上提个 pr 也没什么。

**Comment by owlwisp** [comment]
围观  围观

**Comment by rotencode** [comment]
@harrywong 

回应别人讥讽我也写一个star超过10个的话，我是成年人，我对炫耀技术没兴趣。我只关心业务和产品是否是用户所需要的。如果代码也算产品，那么应该根据其他人是否简单易用易于接手为标准。

是的，个人主要经验是围绕c++/python/go/web前端展开的。
lua-skynet.c难理解是因为都是涉及参数栈操作，代码也没注释。单步跟进都需要猜。
makefile简单不简单，不是我指责的原因。原因在于没有ide支持makefile。

**Comment by dingmingxin** [comment]
http://blog.codingnow.com/2008/09/replacement_of_ide_1.html
http://blog.codingnow.com/2008/09/replacement_of_ide_2.html
http://blog.codingnow.com/2008/09/replacement_of_ide_3.html
http://blog.codingnow.com/2008/09/replacement_of_ide_4.html
http://blog.codingnow.com/2008/10/replacement_of_ide_5.html

**Comment by rotencode** [comment]
@dingmingxin 

我只告诉你，应该摆脱为了技术而技术的思维。cloud的文章是错的（我坚持认定）。不要盲目崇拜和接受他人看法（包括我的）。搬砖的目的不是为了搬砖，既然搬砖不是目的，那么更快更舒服的搬砖才是对的手段。

未来生产力提升，说不定连写代码都可以自动化，如果有那天，可以肯定实现代码自动化的人是选择ide的人，因为他们目的明确，更好的实现目的，而不是更牛逼更装b的写代码。纠结vi爽还是ide爽有什么意义？

接不接受，随意。任何一个选择题，都需要做决定，我的选择不一定对，但我有我选择的理由和出发点。

就工程代码管理来说，cmake比makefile至少先进十年。

**Comment by mskmkt0704** [comment]
建议先看文档理解完思路再去看代码. 你想的工程化未必就是对的,不同项目在不同的环境下的组织并不是一成不变的

**Comment by watercoldyi** [comment]
是你没读仔细,以我的阅读感受来说。skynet的核心层划分是很清晰的，分为service,socket,timer,monitor四个模块。
## service
实现了actor模型，是最重要的一个模块。其又依赖handle,mq,module三个模块。handle是管理actor的生命周期，采用的是一种常用的id映射与引用计数手法，好处在于可以用handle检测对象是否有效。mq是消息队列和服务队列，常规的实现，用自旋锁保证线程安全。module是动态库加载，因为skynet约定用动态库来承载服务。服务的调度是基于多线程的，比例为m:n,每个服务只能被一个线程所持有。

## socket
这个模块实现了一个线程安全的proactor模式，之所以放在核心层是为了避免调度的开销。

## timer
时光轮算法的计时器，放在核心层同socket.

## monitor
提供了死循环，消息录像，消息处理开销三种监测。

核心层的各个模块依赖是很清晰的。

## lua支持
用c/c++开发服务比较低效。所以又提供了lua的支持，主要有两点好处：
1. 动态语言的便捷和安全。
2. 用lua的协程可以消除异步回调的分隔。

因为skynet核心是以动态库为承载的，所有要支持lua必须要做两件事：
1. 提供一个c服务来做lua的宿主。
2. 将核心层的外部接口封装为lua库。

snlua就是宿主，lua-skynet.c就是skynet.h的lua库。

## skynet的运行流程
1. /skynet-src/skynet_main.c
    加载配置文件，嵌入lua代码，是为了方便，在lua层解析比用c api方便。
2. /skynet-src/skynet.start.c
    初始化子模块，创建工作线程。
3. 创建日志服务，bootstrap服务。

skynet的代码并不庞大也不复杂，提不提供cmake等都无所谓。你所说的混乱在我的阅读过程并无感觉，只要以actor被背景，静下心来，1周内是绝对能看明白主要代码的。

**Comment by rotencode** [comment]
@watercoldyi 

skynet_main.c的启动流程内容不多，这个工程代码难阅读的地方不在这个流程。毕竟，这里只需要跟main函数走一边就知道了。lua vm和c交互过度，代码没有注释，诸多自己实现的数据结构让代码阅读性低到我觉得这个库没有别人吹的那么好。

不再回复。

**Comment by diandian-xue** [comment]
@rotencode  我没有讽刺你，我只是觉得你将自己个人非技术讨论的开发放在issue上非常不对。想提醒你在不知道skynet是干什么，解决什么的基础上强看代码。意图通过紧紧通过代码就能了解整个项目的构架和思路，我觉得skynet还不是这么低级的项目。 最后关于ide不支持makefile的说法，skynet不需要跨windows，有了cmake也没多大用，skynet c代码基本在一个目录下，你导入ide也就点几下按钮的事。

**Comment by l1000965431** [comment]
看不懂,开源的东西就是拿出来一个个人想法,然后大家完善。你觉着不好，你自己clone一份，然后自己按照自己想法改不就完了吗？非得发个Issues，告诉大家这个工程没有吹的那么好。用你告诉我们好不好吗？

**Comment by tiancaiamao** [comment]
围观围观....

**Comment by ChouYW** [comment]
原来Issues是这么用的，领教领教

**Comment by berlinhuang** [comment]
简单地 添加了cmakelist [https://github.com/berlinhuang/skynet](url) 
可以在Clion支持Cmake的IDE上运行了
大家多指教

**Comment by Manistein** [comment]
@rotencode skynet结构和流程一直很清晰，是你看不懂而已，实在看不懂可以参考这篇http://note.youdao.com/share/?id=9d2b8a03fdd9cd4947ca4128d30af420&type=note#/，有高见可以提交一些建设性文档到社区，而不是无脑喷，不懂没问题，做人谦虚点还有救。

**Comment by zw0** [comment]
@Manistein 不能看

**Comment by lmess** [comment]
装完b就跑真tm刺激.jpg

**Comment by Manistein** [comment]
@zw0 不能看就不要看了，这个没人强求，这个楼主也是搞笑，看不懂就喷人家设计不好，为啥不是自己水平低呢，为啥就有人看得懂？是不是该好好反思一下，连服务器设计都说不出所以然来，就出来乱喷。

**Comment by lidashuang** [comment]
@Manistein  想学习一下，可以贴社区wiki

**Comment by Manistein** [comment]
@zw0 万分抱歉，刚才会错意，希望见谅，链接贴错了。@lidashuang 兄台你好，链接已经修正，该文wiki上能找到，如果有意向一起探讨，欢迎加群QQ185017593

**Comment by liyqxtu** [comment]
用C有个好处，那就是无论啥版本的编译器都支持，不像C++，一会儿是c++11，一会儿又是C++14,17,20之类的，搞得眼花缭乱的，为了运行代码，还得不停地换vs/gcc的版本
这个库本来就不是工程化代码，也没有遵循那么多所谓的编码规范，就简洁性易懂而言，还是不错的啦。
当然啦，能用vs之类的工具调试的话，会更加易于理解

**Comment by sniper00** [comment]
1.并不需要不停地切换编译器版本，Cpp现在三年一个版本，我认为这相比其它语言是比较慢的。2. Cpp有大量游戏相关的库，如物理，AI相关的，一些特殊算法用Cpp写也更加方便。

**Comment by sniper00** [comment]
> 用C有个好处，那就是无论啥版本的编译器都支持，不像C++，一会儿是c++11，一会儿又是C++14,17,20之类的，搞得眼花缭乱的，为了运行代码，还得不停地换vs/gcc的版本 这个库本来就不是工程化代码，也没有遵循那么多所谓的编码规范，就简洁性易懂而言，还是不错的啦。 当然啦，能用vs之类的工具调试的话，会更加易于理解

并不需要不停的更换编译器 1. Cpp 有强大地向下兼容能力  2. Cpp 三年一个版本，相比其它语言是比较慢的，三年对于IT行业是比较久的时间了。

**Comment by liyqxtu** [comment]
gcc -std=gnu99 -includeplatform.h -g -O2 -Wall -Iplatform -I3rd/lua/src  --shared service-src/service_snlua.c -o cservice/snlua.so -Iskynet-src -llua54 -lskynet -lplatform -lws2_32 -L.
service-src/service_snlua.c: In function 'luaB_auxwrap':
service-src/service_snlua.c:236:7: error: too many arguments to function 'lua_resetthread'
  236 |       lua_resetthread(co, L);  /* close variables in case of errors */
      |       ^~~~~~~~~~~~~~~
In file included from service-src/service_snlua.c:4:
3rd/lua/src/lua.h:156:21: note: declared here
  156 | LUA_API int        (lua_resetthread) (lua_State *L);
      |                     ^~~~~~~~~~~~~~~
make: *** [Makefile:92: cservice/snlua.so] Error 1
这里是不是就是skynet使用了未公开的特性导致的编译错误？

**Comment by alittlesir** [comment]
建议内核代码用c++重构！
linus：去你大爷的

**Comment by Cheungwq** [comment]
您好，您发给我的邮件已收到。
