### ISSUE TITLE
模块实例创建返回值疑惑

### ISSUE THREAD

**Issue by xingleixu** [cloudwu/skynet#694]
skynet_module.c文件
```
void * 
skynet_module_instance_create(struct skynet_module *m) {
	if (m->create) {
		return m->create();
	} else {
		return (void *)(intptr_t)(~0);
	}
}
```
**_return (void *)(intptr_t)(~0);_**
为什么要返回INVALID_HANDLE_VALUE而不是NULL，或者为什么不直接assert呢？这里是否有什么特殊的原因。
另，INVALID_HANDLE_VALUE不是跟平台还有编译器有关吗？
不明白这里为什么这样处理， 希望云大解惑，谢谢！

**Comment by cloudwu** [comment]
一个合法的 module 允许没有 create 这个  api 。

**Comment by xingleixu** [comment]
谢谢！
也就是说，这个只是一个标记，说明该module没有实现create这个API，对吗？

**Comment by cloudwu** [comment]
只有非 NULL 才是合法的 module 对象。

**Comment by xingleixu** [comment]
懂了，谢谢云大！
