### ISSUE TITLE
netpack在哪里，找不到

### ISSUE THREAD

**Issue by lichq5** [cloudwu/skynet#696]
在启动start.sh脚本的时候，会报这样的错误
[:0100000a] lua loader error : ./../src/talkbox/talkbox.lua:3: module 'netpack' not found:
	no field package.preload['netpack']
	no file './lualib/netpack.lua'
	no file './lualib/netpack/init.lua'
	no file './luaclib/netpack.so'

我也确实在skynet目录下找不到netpack.lua文件，既然在talkbox.lua要require("netpack")，那应该要有netpack.lua文件呀。求回复呀，谢谢

**Comment by zhust2003** [comment]
grep -rn 'netpack' .
./skynet/lualib-src/lua-netpack.c:28:struct netpack {
Binary file ./skynet/luaclib/netpack.so matches
这个是一个c写的lua模块，自己搜索下，很简单的问题。

**Comment by lichq5** [comment]
我是有找到netpack.so，但是我要的是netpack.lua呀

**Comment by cloudfreexiao** [comment]
https://cloudwu.github.io/lua53doc/manual.html#pdf-package.loaded
查看 package.searchpath

**Comment by cloudwu** [comment]
netpack 已经转移到 skynet.netpack 。

**Comment by lichq5** [comment]
ok
