### ISSUE TITLE
client.socket是什么文件，在哪里可以找到

### ISSUE THREAD

**Issue by lichq5** [cloudwu/skynet#697]
我想请问一下在example/client.lua中的local socket = require "client.socket"这行代码中的client.socket是指clientsocket.so吗？？

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/blob/master/lualib-src/lua-clientsocket.c

**Comment by lichq5** [comment]
意思是通过Makefile编译得到client.so动态库，这个动态库就是要require的文件吗？？

**Comment by cloudwu** [comment]
http://www.lua.org/manual/5.3/

**Comment by lichq5** [comment]
你的意思是，require会利用package.searchers这张表中的四个查找器函数去查找要加载的加载器。从第一个查找器就是简单的在 package.preload 表中查找加载器到第二个查找器用于查找 Lua 库的加载库也就是在 package.path 中的路径来做查找工作，再到第三个查找器用于查找 C 库的加载库。 查找储存在 package.cpath 中的路径，然后发现uaopen_client_socket(lua_State *L)函数，就找到了要加载的模块加载器了。
如果是这样的话就明白了。谢谢你花时间点出了解决问题的要点在哪，学到了。谢谢，谢谢
