### ISSUE TITLE
定时器timer_shift疑惑

### ISSUE THREAD

**Issue by guitaryang** [cloudwu/skynet#699]
static void
timer_shift(struct timer *T) {
	int mask = TIME_NEAR;
	uint32_t ct = ++T->time;
	if (ct == 0) {
		move_list(T, 3, 0);
	}
        ....
}
move_list(T,3,0) 这个有必要吗？为什么会是level3和idx0呢

**Comment by samuelyao314** [comment]
建议你看看这篇文章.  http://www.cnblogs.com/Jackie-Snow/p/6559381.html.    当ct 走完最大级别的周期时,  在上文中, 就是百位数,  剩下没有处理的, 只会是百位数剩下的一个1.   针对skynet 的情况,  就是level=3 和 idx = 0.   这个定时器的实现,  核心就是时间轮算法.   具体你可以阅读  https://www.ibm.com/developerworks/cn/linux/1308_liuming_linuxtime3/index.html,  https://www.ibm.com/developerworks/cn/linux/l-cn-timers/index.html
