### ISSUE TITLE
skynet.queue assert 出错

### ISSUE THREAD

**Issue by doitian** [cloudwu/skynet#700]
出现很多这个错误，大概原因是什么？会不会对后续的调用造成影响？

```
[C]: in function 'assert'
	skynet/queue.lua:29: in upvalue 'lock'
```

对应代码

```
assert(ref == 0)
```

**Comment by cloudwu** [comment]
定位问题：看看 ref 为什么不等于 0 ，把 ref ++ 和 ref -- 都定位一遍。

**Comment by cloudwu** [comment]
是否有额外用到 coroutine ？

**Comment by cloudwu** [comment]
这个 assert 通常是用来防止你错误的调用 skynet.wakeup 唤醒了由 skynet.queue 挂起的 coroutine ，而不是由 skynet,.queue 自己的第 17 行唤醒的。

**Comment by doitian** [comment]
明白了，确实有用到 wakeup 去唤醒一个后台任务，但任务可能正在执行中。
