### ISSUE TITLE
socket_server 的ctrl_cmd为什么用-1当做正常情况的返回值

### ISSUE THREAD

**Issue by happyxgang** [cloudwu/skynet#702]
看云风大大的代码，看到socket_server里的send_socket函数。
当buffer正常发送完成之后会直接freebuff然后返回-1。
惯性的以为这是错误逻辑，后面看了一下原来上层的socket_server_poll在判断ctrl_cmd的时候默认-1是正常逻辑，或者说内部正常流程，不需要关闭socket。
总感觉这里怪怪的

**Comment by cloudwu** [comment]
每种 socket 事件都定义在 https://github.com/cloudwu/skynet/blob/master/skynet-src/socket_server.h#L6-L13  ，这是一组非负的值。

-1 表示还有后续消息要处理，流程还没有走完，和这组值做区分。

-1 不会返回到模块外面。

**Comment by happyxgang** [comment]
恩，对封装的层次理解还不透彻，多谢大大回复
