### ISSUE TITLE
skynet.call相同字符串地址，第二次出错

### ISSUE THREAD

**Issue by PolarSnow** [cloudwu/skynet#703]
服务器报错内容

![image](https://user-images.githubusercontent.com/3401768/29016666-e740a098-7b85-11e7-8dd3-c42c5a4274a9.png)
涉及代码

![image](https://user-images.githubusercontent.com/3401768/29016876-d1a8b3fa-7b86-11e7-948d-a1493d425bfb.png)
该项是自定义的一个watchdog，但是只是定制了转发部分，和gate的CMD.forward（重命名了文件，不影响原来的gate.lua）.
出错过程，当一个TCP连接上来时，断开该TCP连接，第二次建立TCP连接触发function SOCKET.open(fd, addr)即会100%触发该bug

**Comment by cloudwu** [comment]
学着看 log 啊。

明明有 [:0000000d] KILL self

ps. 拜托不要把文本贴成图片了，学学怎么用 markdown 。

**Comment by PolarSnow** [comment]
谢谢云大。下次再用md，这个log没注意到，下次细心点❤
