### ISSUE TITLE
How handle Unix signals?

### ISSUE THREAD

**Issue by docall** [cloudwu/skynet#707]
For example, we might want a server to gracefully shutdown when it receives a SIGTERM, or a command-line tool to stop processing input if it receives a SIGINT. Here’s how to handle signals in skynet ?

**Comment by cloudwu** [comment]
You can write a C service to register signals by posix C api  (sigaction, etc) . Mark signal in a global variable, and use a timer in the C service to check this global variable, and send a skynet message to other service to handle it.

No official way to handle signals in skynet now.

ps. logger service can handle SIGHUP now, see 

* https://github.com/cloudwu/skynet/blob/master/skynet-src/skynet_start.c#L248-L253
* https://github.com/cloudwu/skynet/blob/master/skynet-src/skynet_start.c#L113-L126
