### ISSUE TITLE
lsocket 如何在windows下用mingw编译呀

### ISSUE THREAD

**Issue by lichq5** [cloudwu/skynet#709]
如果要在windows上安装lsocket是报No such file or directory
#include <arpa/inet.h>

这样是不是说明lsocket并不满足在windows下的编译呀？还是说我补上缺少的文件？
求解，谢谢

**Comment by cloudfreexiao** [comment]
安装 mingw  https://sourceforge.net/projects/mingw/files/

**Comment by cloudfreexiao** [comment]
ps 先编译下 lua

**Comment by docall** [comment]
使用虚拟机开发吧
