### ISSUE TITLE
bus error

### ISSUE THREAD

**Issue by afafaxin** [cloudwu/skynet#710]
项目 在linux下运行大概半个月 报了bus error错误 已经有俩三次了 没找到具体原因 大神求解？

**Comment by cloudwu** [comment]
https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by afafaxin** [comment]
确实让人摸不着头脑，我只是寄希望与 大神也碰到过类似的情况，因为 发现时 进程已经被强制中断了，日志里也只留下了  bus error 这个提示 也还原不了 具体情况。

**Comment by afafaxin** [comment]
![default](https://user-images.githubusercontent.com/30899389/29173027-7b5cbc40-7e14-11e7-98d3-adbd849899ad.png)

**Comment by afafaxin** [comment]
还是谢谢 大神的 邮件 已经开启了 core dump功能 等待下一次 bus error 分析 core dump 文件
