### ISSUE TITLE
socketchannel在被动断开时候处理

### ISSUE THREAD

**Issue by hongling0** [cloudwu/skynet#715]
代码
lualib/skynet/socket.lua
```
socket_message[3] = function(id) -- SKYNET_SOCKET_TYPE_CLOSE=3
    local s = socket_poll[id]
    if s==nil then return end
    s.connected =  false
    wakeup(s)
end

local function wakeup(s)
    local co=s.co
    if co then
        s.co=nil
        skynet.wakeup(co)
    end
end
```
__在channel没有请求的时候是没有co挂起的__
lualib/skynet/socketchannel.lua的check_connection函数中没有检测self.__sock[1]的有效性
socketchannel空闲时候被动断开之后的第一个请求不会重连,在write的时候才会抛出异常
用socket.invalid判断?

**Comment by cloudwu** [comment]
socket.invalid 无法判断这种情况，新增了一个 api socket.disconnected ，麻烦看一下。

**Comment by hongling0** [comment]
可以了

**Comment by chengdd1987** [comment]
为什么去掉了driver.clear(s.buffer,buffer_pool)前对于s.buffer的判断
更新代码后启动抛异常 init service failed: .//lualib/skynet/socket.lua:247: Need buffer object at param 1

**Comment by cloudwu** [comment]
我的疏忽，应该在 C 里面忽略这个 nil ，上面已加上。

目前仅在监听的 fd 上不产生 s.buffer ，导致关闭的时候出错。你这里是否是这个情况？

**Comment by chengdd1987** [comment]
是的，周一我再拉一次代码
