### ISSUE TITLE
config中对snax路径的设置无效。

### ISSUE THREAD

**Issue by feihuroger** [cloudwu/skynet#717]
git最新版本的skynet，正好写了个snax，没有放到skynet自己的lualib/snax 目录下。
config文件中设置了snax到新的路径
启动的时候报错找到不这个snax，报错信息显示
查找路径，已经还是在skynet自己的路径下寻找，
没有显示在设置的snax下查找的过程。

**Comment by cloudwu** [comment]
不太想维护 snax 这一块，欢迎提 pr 修复这个 bug 。

相关路径处理见 https://github.com/cloudwu/skynet/blob/master/lualib/snax/interface.lua#L80-L81

**Comment by cloudwu** [comment]
@hqwrong 这个是你最后修改过的。

**Comment by feihuroger** [comment]
哈，同感，skynet开发原生service已经足够简单了，再弄snax包装一层，也简化不到那里去，
反而多增加一个学习了解成本。
