### ISSUE TITLE
是否有泄漏的嫌疑

### ISSUE THREAD

**Issue by ghost319** [cloudwu/skynet#726]
```lua
local dispatch_message = skynet.dispatch_message

function skynet.forward_type(map, start_func)
	c.callback(function(ptype, msg, sz, ...)
		local prototype = map[ptype]
		if prototype then
			dispatch_message(prototype, msg, sz, ...)
		else
			dispatch_message(ptype, msg, sz, ...)
			c.trash(msg, sz)
		end
	end, true)
	skynet.timeout(0, function()
		skynet.init_service(start_func)
	end)
end
```
假设 dispatch_message(ptype, msg, sz, ...) 这报错了, 那么无法执行 c.trash 来进行释放

**Comment by cloudwu** [comment]
dispatch_message 设计上是不会抛出 error 的，如果有，那是 bug 。

**Comment by ghost319** [comment]
往 skynet.lua 看了下 raw_dispatch_message 函数，里面会调用 p.unpack， 这里面解包也会有报错导致不释放的可能。 这与原本的 skyent.start 还是有些区别，毕竟unpack是可以注册的，可能是我考虑过多了。谢谢云大的解答

**Comment by cloudwu** [comment]
`dispatch_message` 就是 `skynet.dispatch_message` ，有 pcall 调用  `raw_dispatch_message`

**Comment by ghost319** [comment]
问题就是这里，虽然有 pcall 调用 raw_dispatch_message，但是下面还有个 assert 再次报错
`assert(succ, tostring(err))`

**Comment by cloudwu** [comment]
任何 assert 如果触发了就是 bug 。

**Comment by ghost319** [comment]
好的。那我关闭issue了

**Comment by cloudwu** [comment]
我考虑在这里多加一个判断。

**Comment by cloudwu** [comment]
我在这里多加了一个 pcall 。

**Comment by ghost319** [comment]
好的
