### ISSUE TITLE
用skynet做了一个客户端长连接，断线重连之后出现问题socket-server: write to 10 (fd=0) error 

### ISSUE THREAD

**Issue by xiaoxinda** [cloudwu/skynet#730]
socket-server: write to 10 (fd=0) error :Bad file descriptor.
close socket:: Bad file descriptor
用socketchannel也是一样的问题存在，
但是读取却没问题，

**Comment by cloudwu** [comment]
1. 提 issue 前请更新到最新版本。
2. fd=0 说明写到了 stdin ，你要去查为什么关闭了 stdin 从而让新连接使用了 fd 0 。
