### ISSUE TITLE
将socket_server.c中使用select地方改为poll是否更好

### ISSUE THREAD

**Issue by great90** [cloudwu/skynet#733]
我们项目对网络部分稍微进行了一些改动，允许多次调用socket_server_create创建多个socket_server，再游戏运行一段时间后调用会在assert(ss->recvctrl_fd < FD_SETSIZE)处失败。这是对select的限制检查，如果has_cmd不用select方式，改用poll是否会好一些，不用担心fd超过FD_SETSIZE这个问题，改动后可以删除rfds，has_cmd函数的代码如下：
static int
has_cmd(struct socket_server *ss) {
    struct pollfd fd = { ss->recvctrl_fd, POLLIN };
    int retval = poll(&fd, 1, 0);
    if (retval == 1) {
        return 1;
    }
    return 0;
}
需要包含头文件poll.h

**Comment by cloudwu** [comment]
1. poll 不具备移植性。
2. 不要创建多个 socket_server 。
3. 即使要多个，需要先创建好 fd 。
