### ISSUE TITLE
测试了2天，终于找到问题所在，可是不知道如何解决，关于socket client的问题

### ISSUE THREAD

**Issue by xiaoxinda** [cloudwu/skynet#734]
我的业务需求是用skynet作客户端，放在客户的本地服务器里，以客户端的形式和我云端服务器保持长连接，用来接收服务器对客户服务器进行管理，和客户服务器向云端服务器发送请求。
但我发现，我无论用socket还是socketchannel，创建的客户端连接在skynet服务器启动的时候是可行的，如果没有因为网络等原因断开触发重连，一切都很好使，
但是问题出现了，只要一断开，进入重连，就会出现连接上之后大约几秒后自动断开的情况了，
经过我用死循环，每间隔60s自己断开重连测试发现，如果把socket放在fork中就有上述问题。如果不放在fork中，写一个死循环就每次都能正常连接且不会自动断开，不知道这个问题到底该如何下手了。
恳求大神们的帮助。感激不尽

**Comment by tangyiyang** [comment]
TCP需要发心跳包，你发了吗。 另外你的需求，其实自己用luasocket做一个客户端不就好了吗？为什么要用如此骚的操作。

>

**Comment by luckyyyyy** [comment]
兄弟你路子有点野啊，为什么要拿skynet作为客户端来保持TCP。。。

**Comment by BorgLee** [comment]
skynet做客户端？

**Comment by redXpanda** [comment]
操作太骚，闪了自己的腰
