### ISSUE TITLE
worker权重的疑问

### ISSUE THREAD

**Issue by samuelyao314** [cloudwu/skynet#737]
请问工作线程的权重表为什么是这样的值？ 有什么理论依据吗？

static int weight[] = { 
		-1, -1, -1, -1, 0, 0, 0, 0,
		1, 1, 1, 1, 1, 1, 1, 1, 
		2, 2, 2, 2, 2, 2, 2, 2, 
		3, 3, 3, 3, 3, 3, 3, 3, };

**Comment by Manistein** [comment]
skynet_context_message_dispatch 这个函数已经说明了一切了，每个worker有一个权重值，这个权重决定了本worker一次消费一个服务多少条消息
`	int i,n=1;
	struct skynet_message msg;

	for (i=0;i<n;i++) {
		if (skynet_mq_pop(q,&msg)) {
			skynet_context_release(ctx);
			return skynet_globalmq_pop();
		} else if (i==0 && weight >= 0) {
			n = skynet_mq_length(q);
			n >>= weight;
		}
		int overload = skynet_mq_overload(q);
		if (overload) {
			skynet_error(ctx, "May overload, message queue length = %d", overload);
		}

		skynet_monitor_trigger(sm, msg.source , handle);

		if (ctx->cb == NULL) {
			skynet_free(msg.data);
		} else {
			dispatch_message(ctx, &msg);
		}

		skynet_monitor_trigger(sm, 0,0);
	}`
如上所示，如果weight<0则每次只消费一条消息，而如果weight>=0，那么一次消费n>>weight条消息（即n右移weight位，每位移一位相当于除以2），前四个worker一次只消费一条消息，保证了没有服务会被饿死，后面的则一次消费n>>weight条消息。因为每次入队出队操作，都要加锁和解锁，我想云大这样设计可能是为了避免多个worker过度得去加锁解锁操作，从而提升一些性能。

**Comment by samuelyao314** [comment]
对权重的设计本身我不怀疑。 我感觉奇怪的是为什么是这个数值表。 为什么要前4个woker 消费一条消息，如果是前8个，前2个会比前4个差？  这个数值表是如何得出的

**Comment by samuelyao314** [comment]
不可能是脑袋一拍想出的吧？

**Comment by Manistein** [comment]
这里一个服务，并不和一个worker绑定，也就是说，一个服务有机会一次只消费一条消息，也有机会一次消费整个次级消息队列的1/8,1/4,1/2甚至全部，我想这个数字很有规律了，这里也只是对前32个worker进行处理，前八个进行处理，就没有机会进行一个服务一次消费完所有消息，只有前两个，那么“没有服务会被饿死”恐怕效果就会稍微差一点了

**Comment by Manistein** [comment]
这种设计一般是为了性能，如果有人和你说这样配置性能最佳，你相信吗，所以自己动手丰衣足食，自己测试一下没那么难吧

**Comment by cloudwu** [comment]
没有什么特别的原因，拍脑袋定的。8 核的开发机比较多，所以让它一半公平处理，另一半尽量消化堆积的消息；如果生产机核心比较多的话，就尽量摊开。
