### ISSUE TITLE
全局名字长度限制

### ISSUE THREAD

**Issue by spin6lock** [cloudwu/skynet#738]
根据https://github.com/cloudwu/skynet/wiki/LuaAPI，
> skynet.register(name) 可以为自己注册一个别名。（别名必须在 32 个字符以内）

但https://github.com/cloudwu/skynet/blob/master/skynet-src/skynet_harbor.h#L7 
```c
#define GLOBALNAME_LENGTH 16
``` 

https://github.com/cloudwu/skynet/blob/master/service-src/service_harbor.c#L595 索引的就是GLOBALNAME_LENGTH，能不能改为32？

**Comment by korialuo** [comment]
太长了不好用吧

**Comment by cloudwu** [comment]
32 是笔误，不建议修改。
