### ISSUE TITLE
除了sproto的RPC功能还能接入其他RPC框架吗？

### ISSUE THREAD

**Issue by dreamrepo** [cloudwu/skynet#739]
云大，你好！ 我看sproto没有支持多语言，如果skynet要与其他语言系统通信只能是自己实现RPC，这样效率和质量会是问题；如果skynet能与gRPC, Thrift等RPC框架对接或将sproto支持多语言那就好了。

**Comment by cloudwu** [comment]
可以自己实现。

sproto 有很多语言的第三方实现。

**Comment by dreamrepo** [comment]
谢谢云大！可惜没有Java的实现:)

**Comment by samoyedsun** [comment]
机会来了，正好你实现一个……

2017年9月18日 17:48，"Yimi" <notifications@github.com>写道：
