### ISSUE TITLE
关于clusterd大包的一点疑问

### ISSUE THREAD

**Issue by HuangHuimian** [cloudwu/skynet#741]
云大你好，我在用cluster的时候发现，在clusterd.lua里有个表large_request,这表并没有对应给每个fd另外分配一个表。这样就在多节点组网的时候就会有个问题，因为session是不同的fd自己管理的，不保证唯一。而且在任意一个fd关闭时都会清空large_request。这里是不是有点问题?

**Comment by cloudwu** [comment]
谢谢，这是一个 bug ，我刚提交了 patch ，可以看看。
