### ISSUE TITLE
assert有可能是false的

### ISSUE THREAD

**Issue by zhkefa** [cloudwu/skynet#744]
https://github.com/cloudwu/skynet/blob/55136b77ad6c0cafd75a094cb9c649e39816d8eb/skynet-src/socket_server.c#L703

在send_list_xxx 在某条数据完全没发送时，会走到这个assert

**Comment by cloudwu** [comment]
需要完整的事故报告，或制作一个最小出错的案例。

**Comment by cloudwu** [comment]
我可能看见了问题，国庆后再仔细研究。

**Comment by cloudwu** [comment]
手机上改了下，没环境细搞。麻烦帮忙看看。

**Comment by sunlighing** [comment]
请问是在什么情况下出错的，有日志打印出来吗
