### ISSUE TITLE
 日志service疑问

### ISSUE THREAD

**Issue by ghost** [cloudwu/skynet#751]
logger_cb 记录一条日志

https://github.com/cloudwu/skynet/blob/18bc3216aeb6cee6ef85a40681ab8ef299d9ebc8/service-src/service_logger.c#L34-L51

现在需要处理不同的level，比如info error debug

这个 logger_cb  type参数 可以用吗？

**Comment by cloudwu** [comment]
你可以编码在消息字符串中，或定义新的 PTYPE，然后直接给这个服务发指定消息。

**Comment by docall** [comment]
怎么定义新的 PTYPE？

**Comment by cloudwu** [comment]
PTYPE 可自行约定，不超过 255 的整数。

**Comment by docall** [comment]
> PTYPE 可自行约定 

向 logger service 发消息时处理，修改skynet.error ？

**Comment by cloudwu** [comment]
不用 skynet.error, 直接用 skynet.send 发。
