### ISSUE TITLE
初始测试无法通过

### ISSUE THREAD

**Issue by syj2010syj** [cloudwu/skynet#754]
环境是win10应用商店提供的Ubuntu，Build完成后跑Test，分别提示
[:01000001] LAUNCH logger
[:01000002] LAUNCH snlua bootstrap
[:01000003] LAUNCH snlua launcher
[:01000004] LAUNCH snlua cmaster
[:01000004] master listen socket 0.0.0.0:2013
[:01000005] LAUNCH snlua cslave
[:01000005] slave connect to master 127.0.0.1:2013
[:01000005] init service failed: ./service/cslave.lua:232: Can't connect to master
与
./3rd/lua/lua: examples/client.lua:15: Connect 127.0.0.1 8888 failed

请问应该如何解决

**Comment by MrChang0** [comment]
这个是wsl的bug,你可以去[](https://github.com/Microsoft/WSL/issues)看看

**Comment by Edimier** [comment]
云大说了，这种test不负责维护。

**Comment by syj2010syj** [comment]
https://github.com/Microsoft/WSL/issues/1554
卸载WeGame后问题解决。
