### ISSUE TITLE
设置Limit值后在腾讯云mongodb会只能取到101条数据的错误

### ISSUE THREAD

**Issue by tdlrobin** [cloudwu/skynet#755]
`pack = driver.query(request_id, self.__flags, self.__collection.full_name, self.__skip, -self.__limit, query, self.__selector)

pack = driver.more(request_id, self.__collection.full_name, -self.__limit, self.__cursor)
`

在 skynet.db.mongo 的 mongo_cursor:hasNext() 方法中
第558行和560行 为什么要把 __limit 变成负值
经反复测试发现在连接腾讯云的mongodb服务器时，只要设置了Limit值，无论多少数据（大于101条），只能返回101条，如果skip(1)就会只返回100条

**Comment by tdlrobin** [comment]
经测试，把-self.__limit的负号去掉，得到的数据条数会变得正常了

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/commit/5b469c0a9a832908863f4a707354060cbbd3e136#diff-351876b7b591c99b59b117868cfc8e3f

这个要 @learno 解释一下。

根据  https://docs.mongodb.com/manual/reference/mongodb-wire-protocol/ 这里负数会关闭 cursor .

不过我认为没有传负数的必要。

**Comment by cloudwu** [comment]
@tdlrobin   今天我们又看了一下这个问题。如果把 query 设置正的 limit 值，似乎只会限制单次的上限，而不会限制 cursor 的上限，这样就改变了之前 limit 的语义。

我们无法重现你的问题。建议你再测试一下，把 query 那行保留 -self.__limit ，但是把 more 那行的 -self.__limie 改成 0 看看是否可以解决问题。

**Comment by cloudwu** [comment]
@tdlrobin https://github.com/cloudwu/skynet/commit/d5c0d687b3111a3a88c16f4c74b31e4f1cc36740 看看这样是不是能解决问题。

**Comment by tdlrobin** [comment]
可以的，解决问题了，返回的数据条数也是正确的了，limit终于有效。看来腾迅云mongodb并不支持负值的limit用法
