### ISSUE TITLE
cluster.send调用乱序

### ISSUE THREAD

**Issue by darjun** [cloudwu/skynet#757]
云大你好，我们项目使用skynet的cluster模式做进程间通信。发现进程A通过cluster.send**顺序**调用另一个进程B的两个方法f1,f2，进程B那边收到的顺序**有时**是f2,f1。看了之前的issue， #587 和我们现象比较像。但是我更新skynet代码之后，问题仍然存在。请教下，有什么其他可能会造成乱序吗？谢谢~

**Comment by cloudwu** [comment]
还有一种很少见的情况：f1 的包很大，被拆解成多个，socket 把它推迟发送了。

具体可以在底层代码中多加一些 log ，定位一下具体原因，如果发现问题，我们再来看怎么改。

**Comment by cloudwu** [comment]
主要 log 一下发送端的发出的次序，和接收端收到的次序，确定是哪一步的问题：

发送在 command.push 里：https://github.com/cloudwu/skynet/blob/master/service/clusterd.lua#L104

接收在 command.socket 里，由 gate 转发过来： https://github.com/cloudwu/skynet/blob/master/service/clusterd.lua#L180

**Comment by darjun** [comment]
谢谢云大回复。我昨天在底层加了一些简单的日志，确实有个包的大小是1040字节。这个大小会造成分包吗？我今天再详细输出一下日志。

**Comment by darjun** [comment]
云大你好，我刚刚加了log测试了几次。出现这个情况的时候，没有分包。我看源码里面的MULTI_PACK=0x8000，我的包大小才1040，而且日志也打印了padding为nil。

我在command.push里，打印出来的顺序是f1->f2->f3->f4，在command.socket里收到的顺序是f2->f3->f1->f4。command.socket中msg是打包后的二进制，我是提取可打印字符和前面发送的作对比。

另外我在进程B的日志中发现很多socket accept from addr:port。通过netstat  和 ps发现都是进程A连过来的socket，一共用30多个。我不太明白为啥会建立这么多连接。

还望云大不吝赐教~

**Comment by lmess** [comment]
有一种可能：在未有连接时候，连续调用command.push 就会出现多个连接多次的情况，同个node可能出现并行的两个以上的连接，在连接建立完成时是由skynet来乱序唤醒的，这时就可能导致后连接的请求先写数据出去。

**Comment by darjun** [comment]
@lmess，我看这边的源码 https://github.com/cloudwu/skynet/blob/master/service/clusterd.lua#L30
open_channel（ https://github.com/cloudwu/skynet/blob/master/service/clusterd.lua#L17 ）里面是第一次调用会创建连接，后面就直接复用的。不知道为啥会用这么多连接。

**Comment by cloudwu** [comment]
open_channel 的 connect 是一个会切出的操作，的确有可能同时连接多次。我改一下。

**Comment by cloudwu** [comment]
我改了一下，把并发的连接请求放在了队列中。

之前很少有人发现可能是因为：

1. 这个次序错误只存在于第一次建立连接时，有一定概率发生。
2. 通常第一次建立连接是一次请求操作，比如用 cluster.query 查询名字。这种操作不会和 cluster.send 并发。

不过这是一个 bug ，至少会导致建立多余的连接。

**Comment by darjun** [comment]
合了云大的代码，目前测试下来没有问题了。后面持续观察。谢谢云大~
