### ISSUE TITLE
配置里不能包含 $ ??

### ISSUE THREAD

**Issue by ifsc01** [cloudwu/skynet#758]
config.lua

```
aa = "asdf$fasdf"
```

`[skynet config]:2: os.getenv() failed: fasdf`

**Comment by qinhanlei** [comment]
@zw0 
试试 `aa = "asdf\$fasdf"`

**Comment by lidashuang** [comment]
@qinhanlei 试过，不行

**Comment by zw0** [comment]
@qinhanlei 不行

**Comment by uvtong** [comment]
不行啊，$开头的字符串会拿去查找系统环境变量

**Comment by zw0** [comment]
@uvtong 这个不算$ 开关，有$字符而已

**Comment by cloudwu** [comment]
目前只能 \x24 来转义了

**Comment by uvtong** [comment]
@zw0 skynet_main.c:106行 code = string.gsub(code, [[%$([%w_%d]+)]], getenv)\n\  


你$开头的 会被gsub正则匹配到啊，匹配到fasdf，然后调用getenv查找这个系统环境变量啊。。。。。
