### ISSUE TITLE
使用sockethelper.writefunc(fd)写入大于27715字节以上的数据时丢失

### ISSUE THREAD

**Issue by peigongdh** [cloudwu/skynet#759]
阅读simpleweb后，我做出修改，将reponse的body部分修改为从解析的路径下读取文件的内容，并调用
`local ok, err = httpd.write_response(sockethelper.writefunc(id), ...)`
在测试中，浏览器实际获取的字符长度最大值为27715byte
【UNP-p72(3.9)】中认为该现象仅出现在内核中缓冲区到达极限，并且wirte一个套接字为非阻塞的的前提下。

实际中，我做了更多的测试，包括模仿【UNP】中实现的writen去分多次write数据：
```
function socket_extend.writefunc(fd)
    return function(content)
        local write_buffer_size = tonumber(skynet.getenv("write_buffer_size"))
        while #content > write_buffer_size do
            local content_chip = string.sub(content, 1, write_buffer_size)
            local ok = writebytes(fd, content_chip)
            if not ok then
                error(socket_error)
            end
            content = string.sub(content, write_buffer_size - #content)
        end
        
        local ok = writebytes(fd, content)
        if not ok then
            error(socket_error)
        end
    end
end
```
因为我无法获取native write返回的写入长度，故每次写入一个固定的长度write_buffer_size（例如4K），改进后发现该write_buffer_size可以修改至超过上面27715。
例如，我在读取一个content-length=83097的文件时，将上面的write_buffer_size设置为83096，然后用上面的socket_extend.writefunc替代sockethelper.writefunc可以完整写入83097byte，也就是说此时我分两次调用socket.write分别写入83096byte和1byte即可完整写入，但是如果用socket.write一次写入83097byte只能写入27715byte

我的测试环境：
Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-96-generic x86_64)
写缓冲区大写：
```
$ cat /proc/sys/net/ipv4/tcp_wmem
4096    16384   4194304
```

希望能解答我的困惑。

**Comment by cloudwu** [comment]
你可以在 c 层 socket_server.c 中加 log 调试，看为什么在写入全部数据前就断开了连接。

**Comment by cloudwu** [comment]
另外，提任何 issue 前请确保更新到最新版本，注明测试环境版本，避免浪费精力。

例如： https://github.com/cloudwu/skynet/issues/711 要确保不是已解决的问题。

**Comment by peigongdh** [comment]
更新到最新master版本后顺利解决，看来还是得多留意下issue，感谢帮助！
