### ISSUE TITLE
skynet/jemalloc线上内存分配现象

### ISSUE THREAD

**Issue by linxiaolong** [cloudwu/skynet#762]
采用skynet默认的jemalloc，线上的现象：

（未发生lua GC前）：

查看debug_console:
mem:6.7G左右
cmem:0.3G左右
也即框架使用的有效内存大概7G左右

查看top:
该skynet进程占用MEM大概20G左右

查看jemalloc分析报告：
Allocated:8.4G左右
active:15G左右
metadata:1.6G左右
resident:18G左右
mapped:64G左右
retained:2.2G左右
Current active celling:15G左右

（发生了lua 全量GC后）：

查看debug_console:
框架使用的有效内存大概3G左右

查看top:
该skynet进程占用MEM大概18G左右

查看jemalloc分析报告：
Allocated:4.3G左右
active:12G左右
metadata:1.6G左右
resident:15G左右
mapped:64G左右
retained:2.3G左右
Current active celling:12G左右

目前该机器采用32G内存，排除其他应用和buffers/cached加起来10G，该skynet进程经常性地在占用19G到22G之间波动，总内存差不多到32G的时候，该进程总会往下降低占用，而不会导致OOM。已经确定不存在内存泄漏，看了gg group和issue，发现部分类似的反馈，个人之前也提过一个相关issue，cloud认为按以上的数据来看属于正常？

**Comment by lmess** [comment]
正常，遇到过。

**Comment by cloudwu** [comment]
jemalloc 的报告看 allocated 即可，其它都是它的 cache 策略和本身的维护开销。

无论什么分配器算法，通常程序能利用的部分和真正物理内存申请相差 2 倍都属正常。除非你的程序业务简单到分配一块连续内存顺着使用。

**Comment by linxiaolong** [comment]
按jemalloc显示，应该resident是jemalloc真正占用的内存，如果是lua gc前看起来尚可接受，但lua gc后看起来程序利用的部分和真正物理内存申请相差大概是3-4倍，而我看了jemalloc的opt.retained选项没被打开，这正是困惑的地方，因为如果GC后真正内存和分配内存差那么远的话，其实线上内存比较难评估，只能是尽量加多内存了。

**Comment by cloudwu** [comment]
jemalloc 这个级别的内存管理器，都不会立刻把不用的内存归还给系统的，那样效率太低。jemalloc 会保持一段时间，这个时间可以用 mallctl 调整。

硬要清理的话， http://jemalloc.net/jemalloc.3.html#mallctl_namespace   

`arena.<i>.purge` 应该是做这个事情的。

**Comment by linxiaolong** [comment]
按这两天观察的话，假设刚开始是X人同时在线，而skynet进程稳定占用了40%，把人全部踢下去，然后持续观察了一天多，实际上skynet进程还是稳定占用40%左右，也即13G，而实际上这时候debug_console看到的mem+cmem才400M不到。cloud说的mallctl时间调整是指？

**Comment by cloudwu** [comment]
看看上面给出的 jemalloc 文档，我没实际用过。

**Comment by linxiaolong** [comment]
按文档purge做法做了个指令作用不大，我再持续观察一下
