### ISSUE TITLE
skynet_sample  客户端连接出错

### ISSUE THREAD

**Issue by skeleton1231** [cloudwu/skynet#764]
https://github.com/cloudwu/skynet_sample 项目

VMWARE 虚拟机 Ubuntu 16.05 lts

server端:

 ./run.sh 
[:00000001] LAUNCH logger 
[:00000002] LAUNCH snlua bootstrap
[:00000003] LAUNCH snlua launcher
[:00000004] LAUNCH snlua cdummy
[:00000005] LAUNCH harbor 0 4
[:00000006] LAUNCH snlua datacenterd
[:00000007] LAUNCH snlua service_mgr
[:00000008] LAUNCH snlua main
[:00000008] Server start
[:00000009] LAUNCH snlua console
[:0000000a] LAUNCH snlua debug_console 8000
[:0000000a] Start debug console at 127.0.0.1 8000
[:0000000b] LAUNCH snlua protoloader
[:0000000b] load proto [proto.c2s] in slot 1
[:0000000b] load proto [proto.s2c] in slot 2
[:0000000c] LAUNCH snlua hub
[:0000000d] LAUNCH snlua socket_proxyd
[:0000000e] LAUNCH snlua auth
[:0000000f] LAUNCH snlua manager
[:0000000c] Listen 0.0.0.0:5678
[:00000008] KILL self
[:00000002] KILL self
[:00000010] LAUNCH package 13 4
[:0000000e] signin userid = alice
[:0000000e] signup userid = alice
[:0000000e] signin userid = alice
[:00000012] LAUNCH snlua agent
[:0000000f] Assign 4 to alice [18]
[:00000012] login succ alice fd=4
[:00000012] ping
[:00000010] timeout 4
[:00000010] KILL self
[:00000012] fd=4 is gone. error = /home/taoge/Project/skynet_sample/lualib/socket_proxy.lua:43: disconnect
[:00000012] lua call [10 to :12 : 10 msgsz = 0] error : /home/taoge/Project/skynet_sample/skynet/lualib/skynet.lua:516: /home/taoge/Project/skynet_sample/skynet/lualib/skynet.lua:155: /home/taoge/Project/skynet_sample/lualib/socket_proxy.lua:26: subscribe first
stack traceback:
	[C]: in function 'assert'
	/home/taoge/Project/skynet_sample/lualib/socket_proxy.lua:26: in upvalue 'get_addr'
	/home/taoge/Project/skynet_sample/lualib/socket_proxy.lua:52: in function 'socket_proxy.close'
	/home/taoge/Project/skynet_sample/lualib/client.lua:46: in function 'client.close'
	/home/taoge/Project/skynet_sample/service/agent.lua:31: in upvalue 'func'
	/home/taoge/Project/skynet_sample/skynet/lualib/skynet.lua:452: in upvalue 'f'
	/home/taoge/Project/skynet_sample/skynet/lualib/skynet.lua:104: in function </home/taoge/Project/skynet_sample/skynet/lualib/skynet.lua:103>
stack traceback:
	[C]: in function 'assert'
	/home/taoge/Project/skynet_sample/skynet/lualib/skynet.lua:516: in function 'skynet.dispatch_message'

client端:

taoge@ubuntu:~/Project/skynet_sample$ ./client.sh 
signin	alice	false
signup	true
signin	alice	true
server push	welcome
login	true
ping
/home/taoge/Project/skynet_sample/skynet/3rd/lua/lua: [socket error]

不知道为什么会出现这个错误

**Comment by cloudwu** [comment]
这个不维护，自己解决。

**Comment by syj2010syj** [comment]
https://github.com/Microsoft/WSL/issues/1554
试试卸载WeGame
