### ISSUE TITLE
cluster模式下中心服务器，每天不定时会有一些clusterd.lua中的trace

### ISSUE THREAD

**Issue by darjun** [cloudwu/skynet#766]
云大你好，我们是线上游戏，使用skynet的cluster模式。游戏一共有4个进程，我们作为中心的center服务器每天会不定时的出trace。trace如下：
171115-11:35:28 00000009 lua call [c to :9 : 0 msgsz = 16] error : ./3rd/skynet/lualib/skynet.lua:534: ./3rd/skynet/lualib/skynet.lua:156: ./3rd/skynet/service/clusterd.lua:158: Invalid cluster message (size=0)
stack traceback:
	[C]: in function 'skynet.cluster.core.unpackrequest'
	./3rd/skynet/service/clusterd.lua:158: in local 'f'
	./3rd/skynet/service/clusterd.lua:230: in upvalue 'f'
	./3rd/skynet/lualib/skynet.lua:111: in function <./3rd/skynet/lualib/skynet.lua:105>
stack traceback:
	[C]: in function 'assert'
	./3rd/skynet/lualib/skynet.lua:534: in function 'skynet.dispatch_message'
171115-11:35:28 00000009 lua call [c to :9 : 0 msgsz = 182] error : ./3rd/skynet/lualib/skynet.lua:534: ./3rd/skynet/lualib/skynet.lua:156: ./3rd/skynet/service/clusterd.lua:158: Invalid req package type -1
stack traceback:
	[C]: in function 'skynet.cluster.core.unpackrequest'
	./3rd/skynet/service/clusterd.lua:158: in local 'f'
	./3rd/skynet/service/clusterd.lua:230: in upvalue 'f'
	./3rd/skynet/lualib/skynet.lua:111: in function <./3rd/skynet/lualib/skynet.lua:105>
stack traceback:
	[C]: in function 'assert'
	./3rd/skynet/lualib/skynet.lua:534: in function 'skynet.dispatch_message'
171115-11:35:33 00000009 socket close 267 
171115-11:35:33 00000009 socket accept from 180.163.8.254:38496
171115-11:35:33 00000009 lua call [c to :9 : 0 msgsz = 16] error : ./3rd/skynet/lualib/skynet.lua:534: ./3rd/skynet/lualib/skynet.lua:156: ./3rd/skynet/service/clusterd.lua:158: Invalid cluster message (size=0)
stack traceback:
	[C]: in function 'skynet.cluster.core.unpackrequest'
	./3rd/skynet/service/clusterd.lua:158: in local 'f'
	./3rd/skynet/service/clusterd.lua:230: in upvalue 'f'
	./3rd/skynet/lualib/skynet.lua:111: in function <./3rd/skynet/lualib/skynet.lua:105>
stack traceback:
	[C]: in function 'assert'
	./3rd/skynet/lualib/skynet.lua:534: in function 'skynet.dispatch_message'
171115-11:35:33 00000009 lua call [c to :9 : 0 msgsz = 47] error : ./3rd/skynet/lualib/skynet.lua:534: ./3rd/skynet/lualib/skynet.lua:156: ./3rd/skynet/service/clusterd.lua:189: Invalid serialize stream 21 (line:500)
stack traceback:
	[C]: in function 'skynet.core.unpack'
	./3rd/skynet/service/clusterd.lua:189: in local 'f'
	./3rd/skynet/service/clusterd.lua:230: in upvalue 'f'
	./3rd/skynet/lualib/skynet.lua:106: in function <./3rd/skynet/lualib/skynet.lua:105>
stack traceback:
	[C]: in function 'assert'
	./3rd/skynet/lualib/skynet.lua:534: in function 'skynet.dispatch_message'

----------------------

1. 这个trace并不影响正常功能
2. c to 9这里c是gate，9是clusterd
3. 我们进程间通信是直接调用cluster_send，cluster_call来做的。或者是用local_send，local_call到cluster.proxy的返回对象。
4. trace周围必然会有socket accept from。这个是我们在center开的web服务收到的连接。

请教云大排查思路~

**Comment by cloudwu** [comment]
目前 cluster 间并没有握手协议，所以任何人连上去都可以推数据。这个安全性需要由你自己建防火墙，限制 ip 端口。理论上，cluster 互联用的端口一定不能对外网开放。

你查一下谁给 cluster 用的端口发包了。

**Comment by darjun** [comment]
谢云大回复~
我们是用腾讯云的主机，clustername配置的都是腾讯云内部可以访问的地址和端口，外网无法访问。唯一开放的端口是给充值回调用的。但是充值回调那边是用socket和httpc的库，应该不会走到clusterd才对呀。

**Comment by darjun** [comment]
谢云大回复~

我们用的是腾讯云主机，clustername中配置的ip和port只能在内网访问，外网无法访问。唯一开放的端口是给充值回调用的。但是充值回调是用的socket和http库做的管理，应该不会到clusterd的吧？

---
抱歉误操作关闭了issue

**Comment by darjun** [comment]
让运维重新检查了一下防火墙，封了centor的外网端口，确实没问题了
