### ISSUE TITLE
线程权重等于0时，一次性要把队列所有消息处理完毕？

### ISSUE THREAD

**Issue by zhulu-mike** [cloudwu/skynet#767]
`for (i=0;i<n;i++) {
		if (skynet_mq_pop(q,&msg)) {
			skynet_context_release(ctx);
			return skynet_globalmq_pop();
		} else if (i==0 && weight >= 0) {
			n = skynet_mq_length(q);
			n >>= weight;
		}`
消息处理的源代码，这里如果线程权重为0，岂不是要把队列里所有消息一次性处理完毕？是BUG吗？

**Comment by Yoodaa** [comment]
权重那么高难道不需要及时处理掉？

发自我的 iPhone

**Comment by zhulu-mike** [comment]
已经看到了之前类似的issue，得到了答案，关闭了
