### ISSUE TITLE
endless loop问题

### ISSUE THREAD

**Issue by MrXRYang** [cloudwu/skynet#770]
不知怎么触发这个问题，但不一直死循环，过几分钟又好了，日志显示是对几个玩家服务而不是对一个服务，因为偶然发生，没反应过来看日志，所以一直没来得及console调试，直觉这种会是什么问题呢？或有什么其他方法跟踪调试。

[:00000000] A message from [ :0100000d ] to [ :01000881 ] maybe in an endless loop (version = 1014415)
[:00000000] A message from [ :0100000d ] to [ :0100086e ] maybe in an endless loop (version = 1010495)
[:00000000] A message from [ :0100000d ] to [ :01000884 ] maybe in an endless loop (version = 1025207)
[:00000000] A message from [ :0100000d ] to [ :0100086d ] maybe in an endless loop (version = 1013839)
[:00000000] A message from [ :0100000d ] to [ :0100086c ] maybe in an endless loop (version = 1019295)
[:00000000] A message from [ :0100000d ] to [ :01000872 ] maybe in an endless loop (version = 1026275)
[:00000000] A message from [ :0100000d ] to [ :01000870 ] maybe in an endless loop (version = 1018143)

**Comment by zhangshiqian1214** [comment]
不一定是死循环吧，执行时间久也会打印这个出来

**Comment by Manistein** [comment]
可以查看from服务到to服务，中从from服务发给to服务的接口，看看是否有死循环，是否有过于密集的运算，可以通过debug_console查看服务地址对应什么服务，skynet节点会有一条monitor线程，用于检测服务进行callback调用的时候是否执行太久，如果执行超过数秒会抛出这样的日志以供你查询，更多skynet相关的内容，可以参考ThirdPartDocument中的《skynet源码赏析》一文

**Comment by Edimier** [comment]
我们也遇到过类似问题，最终发现是在业务层调用了系统的curl进行http操作，如果http不稳定或者类似curl的系统调用过多就一定会出现endless loop的警告。大部分情况都是业务层代码没写好才会出现这种问题。
