### ISSUE TITLE
skynet 怎么配置 core dump ？

### ISSUE THREAD

**Issue by feihuroger** [cloudwu/skynet#772]
今天系统做压力测试的时候，非虚拟机，PC运行centos，某个节点运行一段时间后就中止消失了。
程序自己的逻辑日志，没有错误输出，os层的message，也没有特别日志。现在摸不到头脑。 

看blog《skynet 服务的沙盒保护》提到一段：配置 core dump 文件输出。这个应该怎么配置呢？

**Comment by Astone-Chou** [comment]
ulimit -a， 看 core file size. ulimit -c 设置 core file size 大小, 代码里调系统 api 也可以.

**Comment by feihuroger** [comment]
我去试一试。
