### ISSUE TITLE
cluster中session溢出问题

### ISSUE THREAD

**Issue by Edimier** [cloudwu/skynet#773]
lua-cluster.c中的packrequest函数中，if(++session < 0) { session = 1;}  这条语句没有执行到，导致我服务器还是出现了session溢出的问题。我的服务器运行的环境是ubuntu14  64位，通过我的逐步排查，是由于编译选项里的-O2导致的，当我把-O2选项去掉的时候，溢出就不会出现了。

想问云大，有啥完美的解决办法，既要-O2选项，又要session溢出问题解决。
ps：我还有一个疑问，为什么当时解决session溢出时，不使用  if(  ++ session >= INT_MAX ) { session = 1;}

**Comment by Edimier** [comment]
刚刚我试了一下，  把session的类型声明为volatile int 完美解决这个问题。。。

**Comment by cloudwu** [comment]
看看这么改行么？

**Comment by Edimier** [comment]
我测试了一下，这样可以。谢谢云大。

**Comment by t0350** [comment]
问题是出在signed integer type溢出是未定义行为，也就是发生什么事情都不意外。而这里改成unsigned后沿用原来写法是可以的。
标准没有规定signed integer types实现上是two's complement。
