### ISSUE TITLE
对外消息包可能会乱序

### ISSUE THREAD

**Issue by CoolDesert** [cloudwu/skynet#774]
## 测试环境
+ skynet最新版本
+ Ubuntu 16.04.3 LTS

##  问题描述
 + 参照[skynet_sample](https://github.com/cloudwu/skynet_sample)的用法,搭建了压力测试机器人。每个机器人都是单独的服务，创建单独的package与服务器通信。
 + 通讯协议里有一个包序号,即每次发包序号+1，服务器会检测包序号是否一致。
 + 机器人在[send_out](https://github.com/cloudwu/skynet_sample/blob/master/src/service_package.c#L298-L308)函数里作包序号+1的操作。
 + 在2000人并发的情况下,必然会出现个别机器人发包乱序的情况(服务器会直接踢掉)。
 + 通过日志,可以发现乱序的时刻正是机器人向服务器发包最为集中的情况。机器人进入区域以后,收到周围对象列表,然后向服务器请求对象详细信息，一个对象一个请求, 在对象数量比较多的情况下,就会一次性发几十个包。

##  修改测试
 注释掉[work线程write操作](https://github.com/cloudwu/skynet/blob/master/skynet-src/socket_server.c#L1476-L1514),强行通过管道序列化到socket线程, 就不再出现乱序的情况。

**Comment by cloudwu** [comment]
1. 你在 `send_out` 里递增全局序号再调用 `skynet_socket_send` 发送数据，这两者一起并不是原子操作。没有任何地方可以保证先加的序号的包会先调用 `skynet_socket_send`。

2. 如果多线程调用 `skynet_socket_send`  ，skynet 从来没有承诺过，先调用的数据必须先发出去。skynet 只保证发送的数据块本身是原子的，即：不会将某次 `skynet_socket_send` 发送的数据中间打断，插入其它调用发送的数据。

如果你需要保证次序，这个序号必须是在 P 中，即和服务相关。同一个服务的 callback 函数是不会并发的。即：`send_out` 这个 C 函数可能多线程并发，但 P （服务对象）本身不可能并发，所以对 `P->fd` 的 `skynet_socket_send` 调用在这里是有序的。如果你有其它服务向相同的 fd 发送数据，skynet 只保证不会打断这里的数据包，而不保证任何先后次序。

**Comment by cloudwu** [comment]
我想我明白了。当有个发送消息送进队列后，可能还没有处理，然后就 direct write 了。这样有可能乱序。我想办法确认一下再处理。

**Comment by cloudwu** [comment]
我给 socket 加了一个 sending 做发送计数。针对 tcp 协议，每次投递发送指令前，都累加这个计数。在 socket 队列真的发送后，减去计数。direct write 只能在 sending 计数为 0 时才能工作。

请帮忙 review 及 test 上面这个修改分支。

**Comment by cloudwu** [comment]
btw, 最好能帮忙测试一下，修改过后，direct write 是否还可以正常触发。谢谢。

**Comment by CoolDesert** [comment]
早上测试了下，发现会触发[assert](https://github.com/cloudwu/skynet/blob/tcpwriteorder/skynet-src/socket_server.c#L571)。然后再review代码，应该是[direct write 没写完](https://github.com/cloudwu/skynet/blob/tcpwriteorder/skynet-src/socket_server.c#L746)导致发送节点增加，但sending计数没有增加导致的。

**Comment by CoolDesert** [comment]
我这边在send_buffer处理direct write的地方对sending计数加1，测试表现正常，应当修复了。

**Comment by cloudwu** [comment]
这样改就 ok 了？

**Comment by CoolDesert** [comment]
惭愧，我就是用的add_sending_ref。直接加应该没问题的。

**Comment by cloudwu** [comment]
@linxiaolong 这个问题你们应该也会遇到。

**Comment by harrywong** [comment]
这里没有理解清楚，之前判断是否 direct_write 的时候是判断 send list 是否为空，send list 被清空也是发送结束后才被清空的，这句`list->head = tmp->next;`，在新修改的版本里面，也是在 `ATOM_DEC(&s->sending);` 后面的。

**Comment by cloudwu** [comment]
这里有锁，引用计数的位置没有什么关系。

**Comment by cloudwu** [comment]
这个 issue 的标题有误解。并不是多线程写 socket 乱序，如果在不同服务（多线程）中写同一个 socket 次序是不保证的（但保证原子性）；bug 在于在同一服务中写同一个 socket 应该保证次序，但 bug 导致了乱序。

bug 的原因是：

如果前一次写操作，由于检测到不能 direct write ，改为向 socket 线程投递写消息；后一个操作却可能在 socket 线程处理前一条写消息前，通过了 direct write 检查，而直接向 socket 先发了包。

这里的解决方案是，一旦向 socket 线程投递写消息，就把 sending 引用计数加到 1 以上，保证在有未发完的包的时候，一定不触发 direct write 。

**Comment by CoolDesert** [comment]
谢谢云大，这个issue可以关闭了。

**Comment by linxiaolong** [comment]
@cloudwu ，收到。不过有两点想提下：
1）按目前的设计，是否考虑socket写操作完全绕开管道，直接挂在socket写缓冲区上面，这里用自旋锁来保证或者把锁粒度更细化一些也可以，感觉这样整体会简洁一些
2）这次修改有个疑惑的地方，add_sending_ref那里 // socket id changed, just return 这个在什么情况下会发生？

**Comment by cloudwu** [comment]
1. 写操作目前需要由 epoll 的写消息驱动，不能盲写。epoll 消息是在 socket 线程统一管理的。
2. 发送的时候，可能 socket 关闭，正好有新的 socket 创建复用了结构。这里不能对新的 socket 的 sending 操作。

btw, 今天有一个新的 issue https://github.com/cloudwu/skynet/issues/777 麻烦 @CoolDesert  重新测试一下 :)

**Comment by CoolDesert** [comment]
@cloudwu 新的分支测试正常。
