### ISSUE TITLE
failed to build skynet with mips toolchain

### ISSUE THREAD

**Issue by srdgame** [cloudwu/skynet#777]
mips-openwrt-linux-gcc -g -O2 -Wall -I3rd/lua  -o skynet skynet-src/skynet_main.c skynet-src/skynet_handle.c skynet-src/skynet_module.c skynet-src/skynet_mq.c skynet-src/skynet_server.c skynet-src/skynet_start.c skynet-src/skynet_timer.c skynet-src/skynet_error.c skynet-src/skynet_harbor.c skynet-src/skynet_env.c skynet-src/skynet_monitor.c skynet-src/skynet_socket.c skynet-src/socket_server.c skynet-src/malloc_hook.c skynet-src/skynet_daemon.c skynet-src/skynet_log.c 3rd/lua/liblua.a -Iskynet-src -I3rd/jemalloc/include/jemalloc  -Wl,-E -lpthread -lm -ldl -lrt -DNOUSE_JEMALLOC
/tmp/cc9xZUFB.o: In function `send_list_tcp':
/home/cch/mycode/skynet/skynet-src/socket_server.c:570: undefined reference to `__sync_sub_and_fetch_8'
/tmp/cc9xZUFB.o: In function `send_buffer':
/home/cch/mycode/skynet/skynet-src/socket_server.c:751: undefined reference to `__sync_add_and_fetch_8'
/tmp/cc9xZUFB.o: In function `add_sending_ref':
/home/cch/mycode/skynet/skynet-src/socket_server.c:1481: undefined reference to `__sync_bool_compare_and_swap_8'
/home/cch/mycode/skynet/skynet-src/socket_server.c:1481: undefined reference to `__sync_bool_compare_and_swap_8'

**Comment by MrChang0** [comment]
Your gcc does't provide these atomic functions.

**Comment by cloudwu** [comment]
I think we should need use `spin_lock` to implement these atomic functions.

**Comment by cloudwu** [comment]
I changes socket.sending from 64bit integer to 32bit. Does it solve this issue ?

**Comment by srdgame** [comment]
@cloudwu I have built the atomic32 branch and got the binary successfully.  We are working testing mips port.
Actually, I have come out similar solution as yours yesterday, but your code has better quality.
