### ISSUE TITLE
关于May overload, message queue length = 1520

### ISSUE THREAD

**Issue by zifiyu** [cloudwu/skynet#783]
请教这条日志该从哪里找原因

**Comment by cloudwu** [comment]
对应服务收到消息的速度超过了它的处理能力。去查抛出警告的服务。

**Comment by zifiyu** [comment]
992	stack traceback:
	[C]: in function 'skynet.profile.yield'
	./lualib/skynet.lua:292: in function 'skynet.manager.wait'
	./lualib/skynet/socket.lua:33: in upvalue 'suspend'
	./lualib/skynet/socket.lua:285: in function 'skynet.socket.read'
	(...tail calls...)
	./lualib/websocket.lua:237: in function 'websocket.recv_frame'
	./lualib/websocket.lua:213: in function 'websocket.recv'
	./lualib/websocket.lua:342: in function 'websocket.start'
	./myexample/web_socket.lua:79: in function <./myexample/web_socket.lua:72>
	[C]: in function 'pcall'
	./myexample/web_socket.lua:133: in field 'callback'
	./lualib/skynet/socket.lua:105: in field '?'
	./lualib/skynet/socket.lua:161: in upvalue 'f'
	./lualib/skynet.lua:111: in function <./lualib/skynet.lua:105>
998	stack traceback:
	[C]: in function 'skynet.profile.yield'
	./lualib/skynet.lua:292: in function 'skynet.manager.wait'
	./lualib/skynet/socket.lua:33: in upvalue 'suspend'
	./lualib/skynet/socket.lua:285: in function 'skynet.socket.read'
	(...tail calls...)
	./lualib/websocket.lua:237: in function 'websocket.recv_frame'
	./lualib/websocket.lua:213: in function 'websocket.recv'
	./lualib/websocket.lua:342: in function 'websocket.start'
	./myexample/web_socket.lua:79: in function <./myexample/web_socket.lua:72>
	[C]: in function 'pcall'
	./myexample/web_socket.lua:133: in field 'callback'
	./lualib/skynet/socket.lua:105: in field '?'
	./lualib/skynet/socket.lua:161: in upvalue 'f'
	./lualib/skynet.lua:111: in function <./lualib/skynet.lua:105>

:01000027	cpu:1.38366	message:3347	mqlen:0	task:256
用html连接到256，html之后就完全连接不上了 测试客户端还可以连接
