### ISSUE TITLE
skynet_timer延时回绕问题

### ISSUE THREAD

**Issue by linxiaolong** [cloudwu/skynet#784]
按timer_shift实现，实际上这个模块应该是考虑了定时回绕的情况：
static void
timer_shift(struct timer *T) {
	int mask = TIME_NEAR;
	uint32_t ct = ++T->time;
       //这里考虑了回绕
	if (ct == 0) {
		move_list(T, 3, 0);
	} else {
		uint32_t time = ct >> TIME_NEAR_SHIFT;
		int i=0;

		while ((ct & (mask-1))==0) {
			int idx=time & TIME_LEVEL_MASK;
			if (idx!=0) {
				move_list(T, i, idx);
				break;				
			}
			mask <<= TIME_LEVEL_SHIFT;
			time >>= TIME_LEVEL_SHIFT;
			++i;
		}
	}
}

而在add_node处理的时候有bug，假设极端情况：T->time = 2^32-1，这个时候加一个延时为2^32 - 1的定时器，会得到node->expire = 2^32-2（无符号32位回绕），进入目前的add_node处理，会将该node放置于T->near，而实际上应该放置于T->t[3][0]。按理应该在node->expire小于T->time的时候统一放置于T->t[3][0]即可。

**Comment by cloudwu** [comment]
这个 api 接收参数是由符号的，无法传入 2^32 - 1 。

https://github.com/cloudwu/skynet/blob/master/skynet-src/skynet_timer.h#L6

**Comment by linxiaolong** [comment]
收到，没注意到。不过其实可以支持到32位，我稍改下
