### ISSUE TITLE
请问endless loop卡死无法调试，如何入手

### ISSUE THREAD

**Issue by MrXRYang** [cloudwu/skynet#787]
如题，本以为在案发现场可以调试，但整个服务器都卡住了，无法nc连接调试端口，其实日志也没在写，卡个10分钟左右，然后好了突然就一下写一堆endless loop日志
几次故障还固定在中午14点左右，真是神奇了，代码中没有对14点做任何东西的。
或者有什么办法去掉不出现endless loop提示啊

**Comment by pigparadise** [comment]
endless loop一般是指出现死循环了,可以试试用gdb调试一下, 打印出lua调用栈,看看是什么代码导致的.

在 2017年12月22日 下午2:22，MrXRYang <notifications@github.com>写道：

**Comment by cloudwu** [comment]
整个卡住连日志都没有，可以检查硬件/系统问题，如果是虚拟机，查看是否是宿主机问题。
