### ISSUE TITLE
关于ep_wait问题

### ISSUE THREAD

**Issue by lindxmooc** [cloudwu/skynet#790]
云风大神，我想请教一下，如果我只是在Linux下开发，这个
static int 
sp_wait(int efd, struct event *e, int max) {
	struct epoll_event ev[max];
	int n = epoll_wait(efd , ev, max, -1);
	int i;
	for (i=0;i<n;i++) {
		e[i].s = ev[i].data.ptr;
		unsigned flag = ev[i].events;
		e[i].write = (flag & EPOLLOUT) != 0;
		e[i].read = (flag & EPOLLIN) != 0;
	}

	return n;
}
是否可以改成这样：
static int 
sp_wait1(int efd, **struct epoll_event *ev**, int max) {
	int n = epoll_wait(efd , ev, max, -1);
	return n;
}
不做for循环，毕竟在socket_server_poll()函数里已经有一个for (;;) {...}了，这样做，会不会高效点？

**Comment by zhongfq** [comment]
事件不要了？这样不知道每一个fd的情况吧

**Comment by lindxmooc** [comment]
我是在这里修改处理了：
socket_server_poll(struct socket_server *ss, struct socket_message * result, int * more) {
	for (;;) {

		if (ss->event_index == ss->event_n) {
			ss->event_n = sp_wait1(ss->event_fd, ss->evs, MAX_EVENT);
			//...
		}

		int _i = ss->event_index ++;
		struct event e[1];
		e->read = ss->evs[_i].events & (EPOLLIN | EPOLLHUP);
		e->write = ss->evs[_i].events & EPOLLOUT;
		e->error = ss->evs[_i].events & EPOLLERR;
		e->s = ss->evs[_i].data.ptr;

		// struct event *e = &ss->ev[ss->event_index++];
		struct socket *s = e->s;
		//...

**Comment by lindxmooc** [comment]
这样做可以吗，对于只在Linux下开发，能提高一点效率吗？

**Comment by samoyedsun** [comment]
不能，这岂不是用一块栈空间代替了指针…，还有这样操作的？

**Comment by cloudwu** [comment]
你的程序效率出现问题了？

**Comment by lindxsea** [comment]
不是，我是在了解源码的时候看到的，所以才产生这个疑问，比如现在有6400个连接服务器，感觉就for循环了6400 * 2，因为ep_wait会分成100次回调，在每一次当中，sp_wait中for循环64次，在外面又循环处理64次，不知道是不是这样理解？

**Comment by lindxmooc** [comment]
不是，我是在了解源码的时候看到的，所以才产生这个疑问，比如现在有6400个连接服务器，感觉就for循环了6400 * 2，因为ep_wait会分成100次回调，在每一次当中，sp_wait中for循环64次，在外面又循环处理64次，不知道是不是这样理解？

**Comment by samoyedsun** [comment]
不是这样理解的，这块代码的意思外循环的代码都是处理事件的，只有当事件处理完了才会进入sp_wait阻塞等待并获取事件，获取到事件后又会进入外循环处理事件，处理完了就再进入sp_wait阻塞等待并获取事件, 然后就这样循环下去….;  其实我们是可以将外面处理事件的代码放到sp_wait里的循环里执行的，只是云大没有那样写而已，每个人的代码书写习惯不一样，你在自己看看吧.
