### ISSUE TITLE
疑似内存泄漏问题请教

### ISSUE THREAD

**Issue by ben-xue** [cloudwu/skynet#791]
整体的工作流程还在学习，但是看到skynet_server.c   689行 - 694行

```
       if (needcopy && *data) {
		char * msg = skynet_malloc(*sz+1);
		memcpy(msg, *data, *sz);
		msg[*sz] = '\0';
		*data = msg;
	}
```

有种可能会引起内存泄露的感觉，如果不是，还请了解的前辈给解释解释咦

**Comment by flyinghare** [comment]
needcopy 从 PTYPE_TAG_DONTCOPY  来

如果 needcopy 为 true ，则调用者的意思就是 ‘你分配一块内存把内容拷贝进去吧，我来释放那片内存’
