### ISSUE TITLE
socket_server待发送数据堆积超过65535次导致崩溃

### ISSUE THREAD

**Issue by lcy03406** [cloudwu/skynet#794]
我们的应用场景需要在短时间发送大量的小的数据包。在较差的wifi环境下会出现这个问题。
现象是报几次warning回调，在超过4096后，有几率崩在in send_list_tcp at skynet-src/socket_server.c:571 assert((s->sending & 0xffff) != 0);

**Comment by cloudwu** [comment]
为了解决这个问题，我做了两处修改。

1.  sending 计数器只用于和 socket thread 通讯，在包加入队列后就把计数器减少。（之前要等包真的发出去）
2. 在递增 sending 计数器的时候做一个检查，如果要溢出了，就开始忙等 socket thread 递减。

请帮忙测试新提交的分支能否修复这个问题。另外，在忙等分支里加一行 printf log 看看会不会跑进去更好。我认为做了 1 修改后，理论上很难进入这个分支。（除非你在一个服务中的一个时间片一次发送 64K 个以上的包）

**Comment by cloudwu** [comment]
今天发现这里修改引入的一个新 bug ，已经修复。

之前在修改这里的时候去掉了 udp 检查，这是有风险的。因为 udp socket 的创建流程和 tcp 不同，udp socket 会先 reserve id ，然后在 socket thread new fd 。sending ref 是在 new fd 初始化的，这有可能引起问题：send udp 包先 inc 了，然后被初始化为 0 ，再 dec 就 assert 。
