### ISSUE TITLE
socket_server_send()函数发送数据问题

### ISSUE THREAD

**Issue by skiing886** [cloudwu/skynet#798]
@云风
将socket_server从skynet中剥离出来单独使用，一个进程作为服务器，一个进程作为客户端，服务器起来后，客户端通过socket_server_connect（）能正常连接上去，但是通过socket_server_send（）发送数据会导致客户端进程挂掉；
客户端调用处代码如下：
![image](https://user-images.githubusercontent.com/5564049/35427525-e9d4d382-02a4-11e8-8278-558d05cb834f.png)

挂掉的地方如下图
![image](https://user-images.githubusercontent.com/5564049/35427419-3f798158-02a4-11e8-8169-614bdca3cae2.png)
![image](https://user-images.githubusercontent.com/5564049/35427475-8e21eebc-02a4-11e8-9303-11fad059855a.png)

**Comment by skiing886** [comment]
难道只能在一个进程内 发数据吗

**Comment by cloudwu** [comment]
发送的数据 buffer 需要用 malloc 分配。
