### ISSUE TITLE
UDP的SO_REUSEADDR问题

### ISSUE THREAD

**Issue by lcy03406** [cloudwu/skynet#799]
目前在创建socket时就被设置了SO_REUSEADDR，导致可以重复绑定到同一个端口，希望能够报异常让应用重新选一个端口。

**Comment by Jamy325** [comment]
很好奇, 什么样的场景下要自动重新绑定订一个端口?你自己改配置文件不就行了?

**Comment by lcy03406** [comment]
@Jamy325 看重点“导致可以重复绑定到同一个端口”，问题是你的应用跟别的不知道什么应用端口冲突了，没有任何报错，程序正常启动但报文乱收。

在创建socket时就被设置了SO_REUSEADDR —— 原因
导致可以重复绑定到同一个端口 —— 问题
希望能够报异常 ——修改方案1
让应用重新选一个端口 ——只是一种可能的处理方式

**Comment by great90** [comment]
那你又如何保证之后其他程序也监听这个端口呢，接收方和发送方通信的端口也不能完全保证没有别的“客户端”捣乱吧

**Comment by findix** [comment]
我刚刚甚至想提个issue咨询是否应该加入SO_REUSEPORT……
