### ISSUE TITLE
cluster.call

### ISSUE THREAD

**Issue by mahal907** [cloudwu/skynet#803]
cluster模式下，A,B两个独立的服务，如果A服务还没有收到来自注册中心的配置，调用cluster.reload更新，此时不知道B服务的地址，如果调用cluster.call则会卡住coroutine，在很多情况下，A是注册服务，B可能是新增的一台游戏服务器，此时B可能没有上线，也就不会向注册中心注册自己；此时如果有往B服务的投递可能导致卡住很多的courtine；最好能在cluster.call进行消息发送的时候找不到B对应的集群名字时，不要发送，直接错误返回不存在的节点名。

**Comment by cloudwu** [comment]
目前已有的机制是为了解决集群各节点启动次序无法保证的问题，默认都会在可预见时间起来。简单的修改 cluster.call 的行为会破坏这个语义，可能对已有项目造成影响。

如果集群是弹性的，建议再建立一套中心机制来解决。例如：设定一个中心节点，一定是启动起来的。负责管理新加入的节点。

然后其它节点向它订阅（请求）新节点的列表，以及用于 reload 的配置表。注：cluster.reload 可以接收一个 table 而不用从文件加载。

另外，中心节点也可以发布一假节点信息，比如它可以把自己模拟成一个日后要用的节点，把这个信息投放出去，这个假节点会负责回应信息（服务器没上线）。等真节点上线，再通过中心节点更新。

ps. 是否有需求给 cluster 加一个 api 查询一个节点名当前是否存在？

**Comment by pigparadise** [comment]
我们项目把cluster模式中的节点进行了划分了层次，子节点初始化时通过配置知道了自己的父节点，子节点上的服务如果需要在其他节点被调用，都是需要子节点主动注册的．父节点上的服务在子节点注册完信息前，是不会主动发消息给子节点上的服务(因为还不知道)．

在 2018年2月24日 上午10:36，周陵 <notifications@github.com>写道：

**Comment by mahal907** [comment]
专门有一个注册中心负责接受A,B两个节点的cluster信息,每个节点上线就会汇报自己的node addre, name,然后同步到集群中的每个机器,此时他们就会调用cluster.reload更新配置; 1). B服务器如果从来没有上线过,A调用Cluster.call就会有新的coroutine生成,等待B上线,相当于缓存住了这次请求; 2).B服务器上线过,维护的时候下线了,那么A已经cluster.reload了这个B的信息,此时调用cluster.call就会立刻因为invalid socket返回,  我是觉得同样的请求,同样B服务器不在线,仅仅因为A没有cluster.reload加载关于B对应的地址端口,逻辑截然不同,有点难受;
ps.如果有一个查询节点的操作更好,那么我就可以在B服务下线前注销掉注册中心的信息了.也能在调用前进行一下判断,就是稍微麻烦些,主要还是上述说的同样的调用2个逻辑结果不同,特别是这样会造成大量的coroutine等待返回,然后B服务一上线,缓存的coroutine就都来了.

**Comment by pigparadise** [comment]
我认为得看B服务是正常的下线，还是意外的下线．如果是正常的下线，可以考虑在下线流程中通知注册中心自己要下线了，然后通知中心可以告诉其他节点．如果是意外的下线，比如crash了，确实会比较麻烦．

在 2018年2月24日 下午3:37，周陵 <notifications@github.com>写道：

**Comment by cloudwu** [comment]
目前的机制是为了解决启动集群的时候，A 调用 B 但是 B 比 A 更晚拉起来，让 A 的流程不出错设计的。如果修改有可能引起兼容问题。

我觉得在目前的基础上，是不是可以试着做个假节点更好？B 下线后，让中心节点把 B 的地址指向自己再更新出去？

另外，我觉得就这个需求来说，我想给 B 节点加一个明确的下线语义更好。也就是在 config 配置信息里，明确说明 B 这个节点是关闭的，任何发起的请求都必须出错。在不修改现有代码的基础上，可以通过把 B 节点的地址配置成一个无法建立连接的端口就可以做到。

**Comment by t0350** [comment]
中心节点把B地址指向自己，然后再更新出去。这个期间内，一样是有失败的请求吧。觉得对这类情况，对cluster.call做超时的处理比较恰当一些？

**Comment by cloudwu** [comment]
现在没有超时语义。要么成功要么失败。开发人员不用考虑超时出错的问题。

**Comment by cloudwu** [comment]
我今天增加了一个特性，如果在 reload 的时候，指定 node = false, 那么就明确了 node 这个节点下线了，cluster.call 的时候就会立刻出错。@mahal907  你看是否能解决你的问题。

**Comment by mahal907** [comment]
@cloudwu 这是最好的方法，可以选择是否准备让A等待B拉起，你说的这种等待拉起，我们也是有需求的。

**Comment by cloudwu** [comment]
今天加了个新特性，可以在配置表里填上 `__nowaiting = true` ，所有没有配置的节点在尝试连接的时候就会立刻报错，而不是等待。
