### ISSUE TITLE
关于监控线程的疑问

### ISSUE THREAD

**Issue by Tancen** [cloudwu/skynet#806]
在 skynet_context_message_dispatch 函数中

    skynet_monitor_trigger(sm, msg.source , handle);

    if (ctx->cb == NULL) {
        skynet_free(msg.data);
    } else {
        dispatch_message(ctx, &msg);
    }

    skynet_monitor_trigger(sm, 0,0);
		

如果 dispatch_message 中 ctx->cb 处理消息耗时比较长的话，是否有可能导致 thread_monitor 中

    for (;;) {
        CHECK_ABORT
        for (i=0;i<n;i++) {
            skynet_monitor_check(m->m[i]);
        }
        for (i=0;i<5;i++) {
            CHECK_ABORT
            sleep(1);
        }
    }

整个最外层 for 执行 >= 2次，从而进入 skynet_monitor_check 

    if (sm->version == sm->check_version) {
        if (sm->destination) {
            skynet_context_endless(sm->destination);
            skynet_error(NULL, "A message from [ :%08x ] to [ :%08x ] maybe in an endless loop (version = %d)", sm->source , sm->destination, sm->version);
        }
    } else {
        sm->check_version = sm->version;
    }
的 skynet_context_endless ？
而 skynet_context_endless 会导致 ctx 的 ref 减1。当 ctx->cb 执行完后， ctx->ref 又会在 skynet_context_message_dispatch 的末尾处又减 1，进而直接让该模块退出
但是，在该模块中，有可能这个消息确实需要一个比较长的时间来处理，所以，thread_monitor 的 

    for (i=0;i<5;i++) {
        CHECK_ABORT
        sleep(1);
    }
是否应该为一个可配置项更合理呢？

**Comment by cloudwu** [comment]
光猜测不设计一个测试案例，是在浪费时间。

**Comment by Tancen** [comment]
特地做了下测试，原来忽略了skynet_context_endless 里 skynet_context_grab 里 ref 加1
非常感谢
