### ISSUE TITLE
测试simpleweb并发问题

### ISSUE THREAD

**Issue by xiuzhifu** [cloudwu/skynet#808]
使用jmeter测试simpleweb的并发，发现请求会一个正确，一个错误，这样返回，50%的错误率，而且很规律。然后我把返回数据的response(id, code, table.concat(tmp,"\n"))改成response(id, code)减少数据量就不会有问题了，怀疑是数据没有write完就close了。看文档write操作又是阻塞的，请问下现在是什么原因，有什么办法可以解决这个问题，tks

**Comment by cloudwu** [comment]
看看和 https://github.com/cloudwu/skynet/issues/759 是否相关。

**Comment by xiuzhifu** [comment]
我是用最新的主线，在ubuntu16.04.4测试的，
加了些日志，发现是listen那里没有accept到新的连接。这个问题不会跟系统设置有关系吧，我即便一个线程，只发两个请求，也会第一个正确，第二个错误，

**Comment by cloudwu** [comment]
把 backlog 调大一些看看。

**Comment by xiuzhifu** [comment]
我把socket.listen的backlog改为1024，然后，系统的tcp_max_syn_backlog跟somaxconn也改大了，情况并没有改变。

---
我怀疑是我的测试方法有问题，做了如下尝试:
1.  使用jmeter用同样的方法，对www.163.com进行测试，返回值正常。
1.  使用jmeter用同样的方法，对www.baidu.com进行测试，返回值跟测试simpleweb一样。
1.  基于以上，换了一个测试工具，使用ApacheBench测试了下，返回值正常。

---
可能跟skynet的关系不是很大，暂时先关闭issue。
