### ISSUE TITLE
cluster之间rpc调用时session异常

### ISSUE THREAD

**Issue by guangb** [cloudwu/skynet#809]
`
[:00000009] ./skynet/service/clusterd.lua:71: Invalid request session -2147483648
`

昨天节点A往集群中另一个节点B,call的时候，session置为-2147483648，原因尚未找到
导致系统节点A中大部分业务异常，只有重启之后恢复正常

**Comment by cloudwu** [comment]
-2147483648 ==  0x80000000 。可能是某种越界回绕造成。

**Comment by guangb** [comment]
多谢，是这个问题，我线上版本没有更新最新代码。
