### ISSUE TITLE
关于skynet.call 是如何挂起当前协程的疑问，希望能解答一下，谢谢

### ISSUE THREAD

**Issue by makeitworks** [cloudwu/skynet#811]
是看到bootstrap.lua中，start函数的回调有调用 skynet.newservice :
`local ok, slave = pcall(skynet.newservice, "dummy")`
而skynet.newservice 是调用了 skynet.call
｀function skynet.newservice(name, ...)
	return skynet.call(".launcher", "lua" , "LAUNCH", "snlua", name, ...)
end｀

在skynet.call中就调用了 yield_call 来挂起当前协程了，  请问一下当前协程是什么时候 create的 以及 是在什么地方 resume的？  （因为在yield之前，必须要 resume这个协程吧？bootstrap.lua中 new service 调用skynet.call这个api 的协程是什么时候resume的？resume的代码在哪？）

看了网上的一些文章，说是每条消息被派发时，会创建一个协程来处理。 skynet.call 并不是这种情况吧？

**Comment by harrywong** [comment]
你需要仔细看代码。
bootstrap.lua的代码是包在`skynet.start`中的，skynet.start中调用了skynet.timeout，这样传入的function就是在一个co中运行的，该co是由`skynet.timeout`创建的。
然后发消息给.launcher，launcher负责启动新的脚本，然后收到的消息后在`raw_dispatch_message`处理，消息类型为PTYPE_RESPONSE的消息会调用`suspend`，在该函数中resume co。
