### ISSUE TITLE
执行例子程序，后查看内存的疑问。

### ISSUE THREAD

**Issue by quanning** [cloudwu/skynet#812]
运行例子
./skynet examples/config
./3rd/lua/lua examples/client.lua 

运行client三次后，分别用mem和cmem指令查看内存。
mem
:01000004       64.29 Kb (snlua cmaster)
:01000005       75.49 Kb (snlua cslave)
:01000007       46.79 Kb (snlua datacenterd)
:01000008       64.33 Kb (snlua service_mgr)
:0100000a       287.42 Kb (snlua protoloader)
:0100000b       68.76 Kb (snlua console)
:0100000c       121.35 Kb (snlua debug_console 8000)
:0100000d       53.15 Kb (snlua simpledb)
:0100000e       48.34 Kb (snlua watchdog)
:0100000f       106.62 Kb (snlua gate)
<CMD OK>
cmem
:01000001       1280
:01000002       167424
:01000003       61616
:01000004       58208
:01000005       91632
:01000006       144
:01000007       12016
:01000008       59280
:01000009       91008
:0100000a       17696
:0100000b       8560
:0100000c       99360
:0100000d       9424
:0100000e       12080
:0100000f       32352
:01000010       17072  <--- 第一个agent
:01000012       208      <--- 第二个agent
:01000019       144      <--- 第三个agent
:fffffffe       32
:ffffffff       8423472
block   5895
total   9163008
<CMD OK>

mem指令看agent已退出。
cmem指令还看到三次agent使用的内
第一个的属于agent的codecache的话，第二、第三个是什么情况？
第二第三个多久会释放？（不释放的话一直循环创建和退出service，会有内存占用累积吧）

**Comment by cloudfreexiao** [comment]
skynet 用jemalloc 它自己有一套分配机制

**Comment by cloudwu** [comment]
cmem 严格意义上讲是指该服务分配出来的内存，而服务推出并不意味着它分配出来的内存一定释放。

例如：发送出去的消息，需要等接收方释放。lua require 的 dll 可能不会随着 vm 的 close 即时释放等等。此类情况还有一些，很难一一枚举。如果你感兴趣，可以在源码里多加一些 log 追踪。

**Comment by quanning** [comment]
谢谢！
