### ISSUE TITLE
新手请教下如何指定pid启动skynet

### ISSUE THREAD

**Issue by iosliujun** [cloudwu/skynet#815]
如题，试过了config里面的skynet.pid 好像不生效 启动后ps -ef查看pid还是随机分配的

**Comment by gongchenic** [comment]
随机开n个skynet，开到指定的id就停止，然后杀掉其他的skynet

**Comment by cupen** [comment]
还有这个配置项？ 好奇要如何实现…… 万一配置的是 1 咋办，万一不同的软件配置的同一个 pid 咋办…… 

不过正经点说，你可能是在[这里][ref]看到的。这里的参数名是 `daemon` ，一般 Linux 软件也会用 `pid` 做名字，但其并不是指定 pid，而是指定 **pid 所保存的位置，也就是 URL**。 

那么 pid 是哪来的？内核自己分配的呀，完全不需要也没必要用户操心。

[ref]: https://github.com/cloudwu/skynet/blob/master/examples/config#L15

**Comment by iosliujun** [comment]
我其实是想知道当前在跑的这个skynet进程号是多少 谢谢解答
