### ISSUE TITLE
clusteragent直接通过名字分发消息

### ISSUE THREAD

**Issue by hongling0** [cloudwu/skynet#823]
现在单个节点重启能正常运行是需要这个节点重启前后的服务id一致(其他节点缓存了该地址)
严格依赖服务的启动顺序。

*能否在clusteragent中通过名字分发消息*
*取消 cluster.name接口和clusterproxy服务(不再缓存地址)*

根据[远端名字服务](https://github.com/cloudwu/skynet/wiki/Cluster#%E8%BF%9C%E7%AB%AF%E5%90%8D%E5%AD%97%E6%9C%8D%E5%8A%A1)
>你可以如上面一节所述的方式，给 skynet 的服务命名，然后使用字符串来替代数字地址。同时，cluster 还提供另一套命名方案。
>
>在本地进程内调用 cluster.register(name [,addr]) 可以把 addr 注册为 cluster 可见的一个字符串名字 name 。如果不传 addr 表示把自身注册为 name 。
>
>远端可以通过调用 cluster.query(node, name) 查询到这个名字对应的数字地址。如果名字不存在，则抛出 error 。
>
>由于历史原因，这套命名方案和上一节的方案并存。但这节描述的方案更为推荐。因为这套命名体系仅在 cluster 的模块中存在，并不影响 skynet 底层的命名系统，更容易为日后扩展。而 skynet 底层的命名系统已不再推荐使用。

建议取消cluster对skynet.name的支持。只能通过clusername获取地址
或者限制addr是:.开头的名字的走skynet.sendname,其他的通过clusername获取地址。

**Comment by cloudwu** [comment]
取消 skynet.name 这个会有兼容性问题，我们有很多项目依赖这个。

cluster proxy 这个我考虑一下支持连接断开后重新查询名字。

对名字更好的支持我再多考虑一下有什么兼容的方案。

**Comment by hongling0** [comment]
clusteragent收到消息是通过skynet.rawcall来实现的
如果addr是字符串的话，底层是用skynet_sendname来实现的

>1 字符串地址是以*.*或者*:*开始的消息走skynet_send
>2 其他字符串地址的消息走skynet_harbor_send

2种集群模式同时使用的话才会使用到第二点
可不可以第二种直接用clustername来转换消息地址（2种集群方式同时用的情况应该比较少）

要不就新加接口来实现派发通过cluster.register注册的服务消息
cluster.callname(node,name,...)
cluster.sendname(node,name,...)

我还是觉得不缓存服务地址是最简单的做法

**Comment by cloudwu** [comment]
看看我新提交的分支，用 @ 加字符串来代表通过 cluster.register 注册的服务。其它的没有变化，只是可以在 cluster.proxy 和 cluster.push cluster.send 里用这个名字。这样可以吗？

**Comment by hongling0** [comment]
试了下，没有发现什么问题
