### ISSUE TITLE
关于debug的问题

### ISSUE THREAD

**Issue by wujianv5** [cloudwu/skynet#824]
连上debug console后，print 变量总是会滞后一行。

例如：
line 1. local data = get_user_data()
line 2. -- do whatever with data
line 3. -- any code 

只有debug走到第3行的时候，print(data)才能打印出东西，在第2行的时候，print(data)输出为nil。

如果我的代码如下：
line 1. for k, v in pairs(mydata) do
line 2.     if v ~= "ok" then
line 3.         return
line 4.     end
line 5. end

如果v的值不是"ok"的话，那我debug的时候是永远都无法知道v的值究竟是多少。
这个是bug吗？还是我的用法不对？

skynet版本为1.1.0

btw, 为什么qq群不允许加入呢？

**Comment by cloudwu** [comment]
不明白，也不太用。你可以自己找一下问题，欢迎提 pr 。

**Comment by cloudwu** [comment]
你可以看看是不是你的控制台问题。然后进一步查 remotedebug.lua 里的 `gen_print` 函数是否有把数据发送出去。

可能是回车造成的。

**Comment by cloudwu** [comment]
你可以自己查一下 remotedebug.lua 里的 `run_cmd` 函数，以及 injectcode.lua 。

**Comment by cloudwu** [comment]
在线调试的用法见：https://blog.codingnow.com/2015/02/skynet_debugger.html
