### ISSUE TITLE
sproto有js版的吗？

### ISSUE THREAD

**Issue by leonshi001** [cloudwu/skynet#828]
我前端用的cocos Creator 后端用skynet，但协议这里遇到点麻烦，所以需要求助：
1、我看了不少skynet相关的例子，但客户端都用的lua，直接用sproto打包，sproto有没有js版呀？
2、假如没有js版的，我在js环境下调用lua版的sproto打包和解包，这种想法靠谱吗？
3、各位有没有其他好的建议，或者相关的资料，留个链接也行。
谢谢了！

**Comment by LaoZhongGu** [comment]
都不去sproto项目的wiki看看的吗？https://github.com/cloudwu/sproto/wiki。有好多语言的版本，js有人提供了，如果不好就自己写个咯。目前看着缺少Java和ActionScript的版本。

**Comment by leonshi001** [comment]
疏忽了，多谢了

**Comment by firedtoad** [comment]
有

leonshi001 <notifications@github.com> 于2018年7月12日周四 下午12:07写道：
