### ISSUE TITLE
lua-socket.c 的问题

### ISSUE THREAD

**Issue by Aaronchens** [cloudwu/skynet#829]
lua-socket.c 

static bool
check_sep(struct buffer_node * node, int from, const char *sep, int seplen) {
	for (;;) {
		int sz = node->sz - from;
		if (sz >= seplen) {
			return memcmp(node->msg+from,sep,seplen) == 0;
		}
		if (sz > 0) {
			if (memcmp(node->msg + from, sep, sz)) {
				return false;
			}
		}
		node = node->next;
		sep += sz;
		seplen -= sz;
		from = 0;
	}
}
这个函数是不是需要在 node = node->next; 后面加个node为NULL 的判断啊 不然可能会崩溃的吧

**Comment by cloudwu** [comment]
此处是内部函数，参数的数据结构也是内部的。你需要举出实际出现你所说的的情况的案例。

**Comment by Aaronchens** [comment]
这是个循环啊 如果seplen很大 跨过几个node 那么一直取node->next 到最后一个node 就会为空的吧

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/issues/286

**Comment by cloudwu** [comment]
类似的问题，还可以参见 https://github.com/cloudwu/skynet/issues/645

**Comment by Aaronchens** [comment]
好吧 但我觉得那个地方只是改了pop_lstring 分割字符串跨节点的问题 但是check_sep还是有问题的吧 当然因为http请求的分割符只有两个字节 所以一般情况下应该还是没问题的
