### ISSUE TITLE
core信息求助

### ISSUE THREAD

**Issue by chengdd1987** [cloudwu/skynet#831]
#0  luaS_remove (L=0x7fa000849308, ts=0x7f9ff742a020) at lstring.c:157
157	  while (*p != ts)  /* find previous element */
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.209.el6_9.1.x86_64 libgcc-4.4.7-18.el6.x86_64 libstdc++-4.4.7-18.el6.x86_64
(gdb) bt
#0  luaS_remove (L=0x7fa000849308, ts=0x7f9ff742a020) at lstring.c:157
#1  0x0000000000415c53 in freeobj (L=0x7fa000849308, p=0x7f9fd2a74a40, count=33) at lgc.c:723
#2  sweeplist (L=0x7fa000849308, p=0x7f9fd2a74a40, count=33) at lgc.c:755
#3  0x0000000000415c97 in sweepstep (L=<value optimized out>, g=0x7fa0008493d8, nextstate=3, nextlist=0x7fa000849440) at lgc.c:1044
#4  0x0000000000416f50 in luaC_step (L=0x7fa000849308) at lgc.c:1148
#5  0x0000000000411847 in lua_pushlstring (L=0x7fa000849308, s=<value optimized out>, len=<value optimized out>) at lapi.c:486
#6  0x00007f9ffd4ba2e3 in luaseri_unpack (L=0x7fa000849308) at lualib-src/lua-seri.c:591
#7  0x00000000004147c3 in luaD_precall (L=0x7fa000849308, func=0x7f9fe0fb7bb0, nresults=-1) at ldo.c:434
#8  0x000000000041feb9 in luaV_execute (L=0x7fa000849308) at lvm.c:1146
#9  0x0000000000414a4b in luaD_call (L=0x7fa000849308, func=<value optimized out>, nResults=<value optimized out>) at ldo.c:499
#10 0x0000000000414a81 in luaD_callnoyield (L=0x7fa000849308, func=<value optimized out>, nResults=<value optimized out>) at ldo.c:509
#11 0x0000000000413a1b in luaD_rawrunprotected (L=0x7fa000849308, f=0x411340 <f_call>, ud=0x7f9fff4d0260) at ldo.c:142
#12 0x0000000000413a9f in luaD_pcall (L=0x7fa000849308, func=<value optimized out>, u=<value optimized out>, old_top=176, 
    ef=<value optimized out>) at ldo.c:729
#13 0x0000000000411272 in lua_pcallk (L=0x7fa000849308, nargs=5, nresults=-1, errfunc=<value optimized out>, ctx=0, 
    k=<value optimized out>) at lapi.c:969
#14 0x0000000000427c70 in luaB_pcall (L=0x7fa000849308) at lbaselib.c:424
#15 0x00000000004147c3 in luaD_precall (L=0x7fa000849308, func=0x7f9fe0fb7a90, nresults=2) at ldo.c:434
#16 0x000000000041feb9 in luaV_execute (L=0x7fa000849308) at lvm.c:1146
#17 0x0000000000414a4b in luaD_call (L=0x7fa000849308, func=<value optimized out>, nResults=<value optimized out>) at ldo.c:499
#18 0x0000000000414a81 in luaD_callnoyield (L=0x7fa000849308, func=<value optimized out>, nResults=<value optimized out>) at ldo.c:509
#19 0x0000000000413a1b in luaD_rawrunprotected (L=0x7fa000849308, f=0x411340 <f_call>, ud=0x7f9fff4d0560) at ldo.c:142
#20 0x0000000000413a9f in luaD_pcall (L=0x7fa000849308, func=<value optimized out>, u=<value optimized out>, old_top=48, 
    ef=<value optimized out>) at ldo.c:729
#21 0x0000000000411272 in lua_pcallk (L=0x7fa000849308, nargs=5, nresults=0, errfunc=<value optimized out>, ctx=0, k=<value optimized out>)
    at lapi.c:969
#22 0x00007f9ffd4b91b3 in _cb (context=0x7fa000846380, ud=0x7fa000849308, type=10, session=0, source=17, msg=0x7f9fc316c1c0, sz=22253)
    at lualib-src/lua-skynet.c:52
#23 0x00000000004097ed in dispatch_message (ctx=0x7fa000846380, msg=0x7f9fff4d0650) at skynet-src/skynet_server.c:274
#24 0x0000000000409aef in skynet_context_message_dispatch (sm=0x7fa0064e9920, q=0x7fa00089e100, weight=0) at skynet-src/skynet_server.c:334
#25 0x000000000040a86d in thread_worker (p=<value optimized out>) at skynet-src/skynet_start.c:162
#26 0x00007fa00730aa51 in start_thread () from /lib64/libpthread.so.0
---Type <return> to continue, or q <return> to quit---bt
#27 0x00007fa0069c793d in ?? () from /lib64/libc.so.6
#28 0x0000000000000000 in ?? ()
(gdb) 
------------------------------------------
问题. 在#22的参数列表中source=17是否表示消息是从与之对应的debug_console:list中的服务号对应的 如果是 这个消息是从我的db服务发送过来的 db用的是mongo
这个问题无法复现 日志无法定位到问题
求助各位大佬有什么信息帮助我定位的 多谢

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/wiki/MemoryHook

**Comment by chengdd1987** [comment]
@cloudwu 
打开了MEMORY_CHECK
并没有收集到更多的信息 新的core产生内容如下,还是没有任何头绪,日志也排查过暂没有发现异常
#0  0x0000000000003bd6 in ?? ()
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.166.el6_7.7.x86_64 libgcc-4.4.7-18.el6.x86_64 libstdc++-4.4.7-18.el6.x86_64
(gdb) bt
#0  0x0000000000003bd6 in ?? ()
#1  0x00007f5490070142 in _cb (context=0x7f54789beb80, ud=<value optimized out>, type=1, session=894, source=0, msg=0x0, sz=0)
    at lualib-src/lua-skynet.c:37
#2  0x00000000004097ed in dispatch_message (ctx=0x7f54789beb80, msg=0x7f5495a8c650) at skynet-src/skynet_server.c:274
#3  0x0000000000409aef in skynet_context_message_dispatch (sm=0x7f5498aa0680, q=0x7f5471704a80, weight=-1) at skynet-src/skynet_server.c:334
#4  0x000000000040a86d in thread_worker (p=<value optimized out>) at skynet-src/skynet_start.c:162
#5  0x00007f54998c1aa1 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f5498f7e93d in clone () from /lib64/libc.so.6

**Comment by chengdd1987** [comment]
问题后续
Program terminated with signal 6, Aborted.
#0  0x00007feee4703625 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.166.el6_7.7.x86_64 libgcc-4.4.7-18.el6.x86_64 libstdc++-4.4.7-18.el6.x86_64
(gdb) bt
#0  0x00007feee4703625 in raise () from /lib64/libc.so.6
#1  0x00007feee4704e05 in abort () from /lib64/libc.so.6
#2  0x00007feee46fc74e in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007feee46fc810 in __assert_fail () from /lib64/libc.so.6
#4  0x000000000040f65e in clean_prefix (ptr=0x7feec295c050) at skynet-src/malloc_hook.c:114
#5  free (ptr=0x7feec295c050) at skynet-src/malloc_hook.c:187
#6  0x00007feedb8b37c3 in packrequest (L=0x7feed5d6df68, is_push=1) at lualib-src/lua-cluster.c:191
#7  0x0000000000414873 in luaD_precall (L=0x7feed5d6df68, func=0x7feeb5a27e20, nresults=3) at ldo.c:434
#8  0x000000000041ff69 in luaV_execute (L=0x7feed5d6df68) at lvm.c:1146
#9  0x00000000004145b0 in unroll (L=0x7feed5d6df68, ud=<value optimized out>) at ldo.c:556
#10 0x0000000000413acb in luaD_rawrunprotected (L=0x7feed5d6df68, f=0x4149c0 <resume>, ud=0x7feede8c2f1c) at ldo.c:142
#11 0x0000000000413d67 in lua_resume (L=0x7feed5d6df68, from=<value optimized out>, nargs=2) at ldo.c:664
#12 0x0000000000429127 in auxresume (L=0x7feed76cb308, co=0x7feed5d6df68, narg=2) at lcorolib.c:39
#13 0x00000000004293d7 in luaB_coresume (L=0x7feed76cb308) at lcorolib.c:60
#14 0x0000000000414873 in luaD_precall (L=0x7feed76cb308, func=0x7feed75a6260, nresults=-1) at ldo.c:434
#15 0x000000000041ff69 in luaV_execute (L=0x7feed76cb308) at lvm.c:1146
#16 0x0000000000414afb in luaD_call (L=0x7feed76cb308, func=<value optimized out>, nResults=<value optimized out>) at ldo.c:499
#17 0x0000000000414b31 in luaD_callnoyield (L=0x7feed76cb308, func=<value optimized out>, nResults=<value optimized out>) at ldo.c:509
#18 0x0000000000413acb in luaD_rawrunprotected (L=0x7feed76cb308, f=0x4113f0 <f_call>, ud=0x7feede8c3260) at ldo.c:142
#19 0x0000000000413b4f in luaD_pcall (L=0x7feed76cb308, func=<value optimized out>, u=<value optimized out>, old_top=176, ef=<value optimized out>)
    at ldo.c:729
#20 0x0000000000411322 in lua_pcallk (L=0x7feed76cb308, nargs=5, nresults=-1, errfunc=<value optimized out>, ctx=0, k=<value optimized out>) at lapi.c:969
#21 0x0000000000427d20 in luaB_pcall (L=0x7feed76cb308) at lbaselib.c:424
#22 0x0000000000414873 in luaD_precall (L=0x7feed76cb308, func=0x7feed75a6090, nresults=2) at ldo.c:434
#23 0x000000000041ff69 in luaV_execute (L=0x7feed76cb308) at lvm.c:1146
#24 0x0000000000414afb in luaD_call (L=0x7feed76cb308, func=<value optimized out>, nResults=<value optimized out>) at ldo.c:499
#25 0x0000000000414b31 in luaD_callnoyield (L=0x7feed76cb308, func=<value optimized out>, nResults=<value optimized out>) at ldo.c:509
#26 0x0000000000413acb in luaD_rawrunprotected (L=0x7feed76cb308, f=0x4113f0 <f_call>, ud=0x7feede8c3560) at ldo.c:142
#27 0x0000000000413b4f in luaD_pcall (L=0x7feed76cb308, func=<value optimized out>, u=<value optimized out>, old_top=48, ef=<value optimized out>)
    at ldo.c:729
#28 0x0000000000411322 in lua_pcallk (L=0x7feed76cb308, nargs=5, nresults=0, errfunc=<value optimized out>, ctx=0, k=<value optimized out>) at lapi.c:969
#29 0x00007feedb8ab1b3 in _cb (context=0x7feed76c3500, ud=0x7feed76cb308, type=6, session=0, source=0, msg=0x7feec06598a0, sz=24)
    at lualib-src/lua-skynet.c:52
#30 0x00000000004097ed in dispatch_message (ctx=0x7feed76c3500, msg=0x7feede8c3650) at skynet-src/skynet_server.c:274
#31 0x0000000000409aef in skynet_context_message_dispatch (sm=0x7feee42db700, q=0x7feed76fe480, weight=0) at skynet-src/skynet_server.c:334
实际上已经缩小了很大的范围了,但是还没有看出是什么原因引起的 业务中只有一个地方使用了cluster

**Comment by chengdd1987** [comment]
已经定位解决 多播的时候数据处理方式错误引起的

**Comment by firedtoad** [comment]
隐隐看到被锁定在4.4 恐惧

2018-05-09 16:33 GMT+08:00 Elliott <notifications@github.com>:
