### ISSUE TITLE
连接mysql报错

### ISSUE THREAD

**Issue by wushimang886** [cloudwu/skynet#836]
已经检查过了。 myql可以正常连接 和 账号 密码也都正确。
但是，服务器连接mysql 就是会报错。请各位看看 这个到底是什么问题。
也不是 必现。 偶尔在重启服务器的时候， 就会报错。

01:35:38 : [:00000011] socket: auth failed ./lualib/skynet/db/mysql.lua:68: bad argument #3 to 'strunpack' (initial position out of string)
01:35:38 : [:00000011] Connect to 47.96.25.120:23306 failed (nil)
01:35:38 : [:00000011] init service failed: [Error: socket]
01:35:38 : [:00000011] KILL self
01:35:38 : [:00000008] init service failed: ./lualib/skynet.lua:537: ./service/service_mgr.lua:25: ./lualib/skynet.lua:383: call failed
stack traceback:
	[C]: in function 'assert'
	./lualib/skynet.lua:537: in function 'skynet.uniqueservice'
	./myservice/main.lua:32: in local 'start'
	./lualib/skynet.lua:621: in function <./lualib/skynet.lua:618>
	[C]: in function 'xpcall'
	./lualib/skynet.lua:625: in function 'skynet.pcall'
	./lualib/skynet.lua:629: in function 'skynet.init_service'
	./lualib/skynet.lua:642: in upvalue 'f'
	./lualib/skynet.lua:106: in function <./lualib/skynet.lua:105>

**Comment by zhixue8075714** [comment]
请问你解决这个问题了吗，是怎么解决的，我也遇到类似的问题了

**Comment by lujingwei002** [comment]
试一下mysql的修改最大链接数量 
[mysqld]
max_connections = 1024
