### ISSUE TITLE
服务中用self报错

### ISSUE THREAD

**Issue by leonshi001** [cloudwu/skynet#837]
![qq 20180517120423](https://user-images.githubusercontent.com/18082547/40156207-8a741204-59ca-11e8-88cd-87ad51ceceb4.png)

我新写的一个服务，然后在main中调用
![qq 20180517120456](https://user-images.githubusercontent.com/18082547/40156242-ceafc26a-59ca-11e8-8307-797856bdd69c.png)

然后就报了如下错误，
![qq 20180517120445](https://user-images.githubusercontent.com/18082547/40156251-d9efb4b4-59ca-11e8-8f3e-1f7e158f91d2.png)

这里不能用self吗，我看别人的代码就可以用呀！请大神指导，谢谢了

**Comment by leonshi001** [comment]
我知道了，这样写就行了，
skynet.start(function()
	skynet.dispatch("lua", function(_,_, command, ...)
		local p = SVTest[ command ]
		if p then
			local r = cs( p, SVTest, ... )
			skynet.ret(skynet.pack(r))
		end
	end)
end)

**Comment by great90** [comment]
Please close this issue. @leonshi001

**Comment by koll1009** [comment]
你的函数调用语法不对
