### ISSUE TITLE
c# des加密和skynet对接问题

### ISSUE THREAD

**Issue by sundream** [cloudwu/skynet#845]
c#自带des加密接口需要一个秘钥和一个初始向量,代码大致如下:
DESCryptoServiceProvider dCSP = new DESCryptoServiceProvider();
dCSP.CreateEncryptoer(加密秘钥,初始向量);
skynet中crypt.desencode接口只需要一个秘钥，想请教下C#中des的初始
向量应该如何设置才能和skynet正确对接

**Comment by cloudwu** [comment]
没用过 c# , skynet 本身不依赖 des ，你可以自己用一个兼容的 lua 库。

**Comment by sundream** [comment]
改用其他加密了(*-*)
