### ISSUE TITLE
skynet是否可以支持 websocket

### ISSUE THREAD

**Issue by cloudfreexiao** [cloudwu/skynet#846]
云大 你好：
skynet 有几个第三方 websocket库 
[skynetpatch](https://github.com/sctangqiang/skynetpatch)
[skynet_websocket](https://github.com/Skycrab/skynet_websocket)
请问 是否能够 支持 官方 websocket库
感谢 !!

**Comment by cloudwu** [comment]
既然已经有这么多了，就不增加单一仓库的维护负担了。
