### ISSUE TITLE
新学skynet交流群：188323917

### ISSUE THREAD

**Issue by G0561** [cloudwu/skynet#849]
近来很多人在qq上抱怨为什么skynet哪个大群加不进去了，那是因为那个群已经加满了！学习代码最好的还是看代码，看Issues， 现在一般问题云大在这里回复还是很快的，qq群只能说是有时候比较及时而已，
 如果现在大家如果加不进1群，可以加这个skynet群：188323917，这个群创建于14年，目前近1000人

**Comment by yuanfengyun** [comment]
免费skynet视频教程：[](url)https://ke.qq.com/course/310360?tuin=104cb0e2
