### ISSUE TITLE
skynet.queue

### ISSUE THREAD

**Issue by koll1009** [cloudwu/skynet#851]
通过把后续运行的函数插入到队列，从而保证了函数的运行时序，但代码里有两处我想不通什么条件下会发生 1是current_thread ~= thread(coroutine.running())  2是ref = ref + 1 ref=ref-1

**Comment by ylme** [comment]
https://my.oschina.net/iirecord/blog/1670916  看一下代码，运行一下示例，你就明白了。

**Comment by koll1009** [comment]
@ylme  看代码的时候没想到同一个协程嵌套调用
