### ISSUE TITLE
关于时间轮实现有几个不明白的地方

### ISSUE THREAD

**Issue by MrWen** [cloudwu/skynet#853]
1. TI->t[3][0]为什么是存储的是超时的定时器，根据add_node最后一行
link(&T->t[i][((time >> (TIME_NEAR_SHIFT + i * TIME_LEVEL_SHIFT)) & TIME_LEVEL_MASK)], node);
最后高位6字节是0的情况才能加入，但这个好像并非存储不下的情况
2. timer_add方法
node->expire = time + T->time; 当这个time+T->time越界了才应该属于TI->t[3][0]的定时器吧
没看懂，求指导下

**Comment by cloudwu** [comment]
issue 搜索 timer

**Comment by MrWen** [comment]
懂了，感谢云大
