### ISSUE TITLE
请教如何扩展mongodb driver以支持aggregate？

### ISSUE THREAD

**Issue by wujianv5** [cloudwu/skynet#855]
想用到mongodb的aggregate操作，但是现有的driver没有这个功能，求教扩展driver的思路是什么？有没有相关课参考的文档？谢谢！

**Comment by longshaowu** [comment]
具体是怎么使用的啊？

**Comment by wujianv5** [comment]
> 具体是怎么使用的啊？

我就是这么做的：
db:runCommand("aggregate", collection, "pipeline", pipeline, "cursor", {})

其中collection就是你的要操作的collection的名字，pipeline是一个table

**Comment by longshaowu** [comment]
要使用sum计算的话是在pipeline内和查询语句写在一起吗？

**Comment by longshaowu** [comment]
解决了

**Comment by hanxi** [comment]
参考文档： https://docs.mongodb.com/manual/reference/command/
