### ISSUE TITLE
datasheet 在处理 大于2^31和小于-2^31的数字的时候 会报错

### ISSUE THREAD

**Issue by yidayoung** [cloudwu/skynet#857]
local builder = require "skynet.datasheet.builder"
builder.new("test", {a=2147483647})  --ok
builder.new("test", {a=2147483648})  --error

看起来是dump.lua:62中
if math.tointeger(v) then
     return '\1', string.pack("<i4", v)

math.tointerger 能检查通过的值不一定能放到4字节的带符号整型里
暂时改成
if math.tointeger(v) and v <= 0x7FFFFFFF and v>= -(0x7FFFFFFF+1) then 

可以解决上面的问题，但是感觉这样改还是很粗糙，希望可以有更好的办法

**Comment by cloudwu** [comment]
这样改倒是没问题，但是大于 sint32 的数字会丢失精度。这是 C 结构的限制。
