### ISSUE TITLE
skynet怎么设置keepAlive 呀？

### ISSUE THREAD

**Issue by leonshi001** [cloudwu/skynet#861]
服务器需要进行掉线检测，skynet怎么设置keepAlive 呀？有相关文档、网页，或者相关代码，给个链接，谢谢了，大神！！！

**Comment by hanxi** [comment]
你是要这玩意吗？
https://github.com/cloudwu/skynet/blob/master/examples/agent.lua#L27

**Comment by leonshi001** [comment]
@hanxi 多谢了
