### ISSUE TITLE
datasheet异常

### ISSUE THREAD

**Issue by koll1009** [cloudwu/skynet#862]
1.我在一个服务里load了一批共享数据，然后在别的服务里调用datasheet.query总是报init.lua:72: /home/koll/testskynet/skynet/lualib/skynet.lua:383: dest address type (nil) must be a string or number.
2.我在lua文件头部同时local builder=require "skynet.datasheet.builder"
                                   local datasheet=require"skynet.datasheet"，则进程会core dump
3.如果2里的require顺序颠倒，则进程会阻塞
由于datasheet的源码还没看，感觉测试成本很高，希望能出有个文档，介绍用法

**Comment by cloudwu** [comment]
看看和  https://github.com/cloudwu/skynet/blob/master/test/testdatasheet.lua 用法有什么不同。

**Comment by koll1009** [comment]
找到问题了，使用的时候 skynet.datasheet的返回值不能作为local变量使用？ @cloudwu
