### ISSUE TITLE
dns.lua  udp crash 

### ISSUE THREAD

**Issue by lshain** [cloudwu/skynet#863]
socket_server_udp
  -> reserve_id 里面的 dw_lock 并未 pthread_mutex_init
  -> send_request(ss, &request, 'U', sizeof(request.u.udp));  
      ... 等待 socket thread 处理
      -> add_udp_socket()
          -> new_fd
                -> spinlock_init(&s->dw_lock);

此时 socket_server_udp_connect
        socket_lock -> pthread_mutex_lock 会有问题，这个dw_lock 有概率还未 pthread_mutex_init, socket thread 还未处理 'U' 的话

dns.lua:
local function connect_server()
  local fd = socket.udp(function(str, from)
    resolve(str)
  end)
  local ok, err = pcall(socket.udp_connect,fd, dns_server.address, dns_server.port)
  ...

**Comment by cloudwu** [comment]
我看看，可能有更好的改法。

这个问题可能和 https://github.com/cloudwu/skynet/issues/852 有关联。

**Comment by cloudwu** [comment]
我想了一下，统一初始化更好。我先这样改了。

在 release 里统一 destroy 有可以商榷的地方：其实不释放更安全，可以防止其它线程尝试加锁。不过这个函数调用的时候，skynet 启动的所有工作线程都已经退出了，所以没有问题。
