### ISSUE TITLE
云风前辈，

### ISSUE THREAD

**Issue by craigtao** [cloudwu/skynet#864]
云凤前辈，是不是考虑转人工智能，智能制造业呢？  机器视觉，制造业对整个国家的实力水平有很大的提高的，

**Comment by firedtoad** [comment]
要能转 早转了 能等到现在


craigtao <notifications@github.com> 于2018年7月24日周二 下午5:03写道：

**Comment by firedtoad** [comment]
哪个行业都需要很多年的积累才能 才能做的不错
国内哪家传统制造业的公司会收留互联网行业的一个小领域的专业的人
并且给与充分的信任,而且让你挑大梁,你能过政审么
 更何况 老吴头上的光环 比起另外一个老吴 只能是萤火之光与日月争辉

craigtao <notifications@github.com> 于2018年7月25日周三 上午8:24写道：

**Comment by hanxi** [comment]
云凤是谁？
