### ISSUE TITLE
sharedata唯一地址为nil

### ISSUE THREAD

**Issue by hongsx** [cloudwu/skynet#868]
./skynet/lualib/skynet.lua:387: dest address type (nil) must be a string or number.
stack traceback: [C]: in function 'skynet.core.send' ./skynet/lualib/skynet.lua:387: in function 'skynet.call' ./skynet/lualib/sharedata.lua:24: in function 'sharedata.query' 
比较奇怪，agent服务require("sharedata")，原本会调用
skynet.init(function()
	service = skynet.uniqueservice "sharedatad"
end)
但是在后面调用sharedata.query过程中，报service地址为nil，偶发现象

**Comment by cloudwu** [comment]
skynet.init 注入的函数，正常应该在 skynet.start 的时候调用，你可以写 log 追查一下为何没有调用。

**Comment by hongsx** [comment]
嗯，苏丹的复仇跑了快三年，今天线上第一次遇到。。

**Comment by cloudwu** [comment]
检查一下，是否有不常见的分支，在 skynet.start 之前就调用了某些 skynet 阻塞 api 。

通常会出现在为项目专门开发的 lua 的库中，在 require 这些库的时刻执行了某些逻辑。

**Comment by hongsx** [comment]
没有关联，两个问题是我们线上不同服务器不同时间遇到的问题。
