### ISSUE TITLE
sharedata的服务没有响应

### ISSUE THREAD

**Issue by hongsx** [cloudwu/skynet#869]
游戏进程跑着跑着发现agent服务启动的时候初始化一些本地数据时使用 sharedata.query ，挂住协程了，没有响应，所有的agent服务启动都有问题，通过debug console 去task agent服务地址，截图如下，目前我们项目的物理机有119台，在同一台机器上出现了两次这个问题，两次时间间隔大概10个月左右
<img width="937" alt="2018-08-01 6 55 34" src="https://user-images.githubusercontent.com/7930351/43517801-8320f30e-95bc-11e8-9625-1aedbda9d60e.png">

**Comment by xhwfish** [comment]
可以看看当前 skynet 的 addressreuse 分支是否能解决你的问题

**Comment by cloudwu** [comment]
对。这个是服务地址重用时的一个 bug , 目前在分支上修复了。可以阅读一下并测试。我认为可以解决这个 issue 。

这个分支我会在下个月合并到主干。
