### ISSUE TITLE
skynet跑一段时间后，skynet.now()的时间要大于主机时间

### ISSUE THREAD

**Issue by gamepdc** [cloudwu/skynet#871]
skynet跑一段时间后，skynet.now()的时间会大于主机时间。集群里多台主机跑skynet时，会导致各个主机之间的skynet.now()取到的时间不一致，skynet连续跑二十天不重启的话，最大出现过十几秒的时间差异。

**Comment by cloudwu** [comment]
man clock_gettime , 参考 CLOCK_MONOTONIC 的说明。

**Comment by gamepdc** [comment]
明白了，skynet_timer本身就是设计为CLOCK_MONOTONIC时钟。如果要取主机时间，还得用系统函数来获取。

**Comment by cloudwu** [comment]
https://stackoverflow.com/questions/14270300/what-is-the-difference-between-clock-monotonic-clock-monotonic-raw

skynet 使用 CLOCK_MONOTONIC 是因为需要保证时钟的单调性。

CLOCK_MONOTONIC 会被 ntp 影响调整频率以适应时间变化，只是不能被主动调整时间影响。所以和 wall time 有可能有差异，但只是 ntp 对时应该不会有累计影响。在比较老的 skynet 曾经用过 CLOCK_MONOTONIC_RAW 但是现在已经改过来了。

**Comment by gamepdc** [comment]
确认了一下，我们项目现在的skynet版本就是用的CLOCK_MONOTONIC_RAW。多谢云风大神追加的答案。
