### ISSUE TITLE
gc问题

### ISSUE THREAD

**Issue by shizhenren** [cloudwu/skynet#872]
--master.lua
local mc = require"skynet.multicast"
local dc = require"skynet.datacenter"
local ch

skynet.start(function()
  ch = mc.new()
  dc.set("channel", ch.channel)

  skynet.fork( function()    --一直发布消息
     ch:publish("xxxxxxxxxxxxxx")
     skynet.sleep(100)
  end)
end)

--agent.lua
local mc = require"skynet.multicast"
local dc = require"skynet.datacenter"
local ch

skynet.start(function()
   ch = mc.new{
         channel = dataCenter.get("channel"),
	dispatch = function ( channel, src, msg )
		print("from channel:", msg)             --这里始终打印不出
	end
  }

 ch:subscribe()
skynet.timeout(100, function()   --1秒后gc下
   collectgarbage()
end)
 
end)

我的猜测，agent.ch变量只有从nil赋值为非nil后，其他没地方使用过，导致被gc认为该变量可以回收。

**Comment by shizhenren** [comment]
云风哥，怎样算"无引用的 channel", agent的ch不算吗

**Comment by cloudwu** [comment]
你需要直接或间接的被全局变量引用。

**Comment by shizhenren** [comment]
有点怪怪的感觉，gc没法找到模块的local变量吗

**Comment by cloudwu** [comment]
模块并不引用 local 变量，函数才引用。

**Comment by cloudwu** [comment]
这里主要是 dispatch 表是弱表，改成强表就可以自己记住引用。但是这里的最初的考虑是为了避免在服务退出时忘记  unsubscribe 而造成资源泄露。

**Comment by shizhenren** [comment]
哦。。明白了，云风哥，谢谢了。

**Comment by cloudwu** [comment]
我看了一下，好像改成强表也没什么问题。等以后想起来有什么别的问题再说，先改了。

**Comment by shizhenren** [comment]
之前是不是为了方便使用，即使不显示调用unsubscribe，也能释放资源。
