### ISSUE TITLE
wakeup多个coroutine时，中间抛error会停住，请问这个情况是设计如此吗？

### ISSUE THREAD

**Issue by drinkwithwater** [cloudwu/skynet#873]
类似这样的写法：
```
local skynet = require "skynet"

local coList = {}
local function wakeup()
        for k, co in pairs(coList) do
                skynet.wakeup(co)
        end
end

local function wait(i)
        local co = coroutine.running()
        coList[i] = co
        skynet.wait(co)
        if i == 5 then
                error("no:"..i)
        else
                skynet.error("yes:", i)
        end
end

skynet.start(function()
        for i=1, 10 do
                skynet.fork(wait, i)
        end
        skynet.fork(wakeup)


        -- skynet.sleep(1)
end)

```
到了i=5抛出错误时，只打印了前四个coroutine的log，就停住不动了。
但如果在最后sleep一下，则会继续打印6~10

看skynet.lua代码，suspend会把错误抛出，所以没有执行接下来的dispatch_wakeup。

**Comment by cloudwu** [comment]
造成这个问题的原因是 skynet 是由消息驱动的，fork 出来的 coroutine 并非由外部消息触发，所以必须借助已有消息。目前是放在 SUSPEND 指令中的。除了阻塞调用外，正常的消息处理完也会触发一次 SUSPEND ，但是异常消息不会。

该问题设计的时候就考虑过，但是考虑到完全没有外部消息的场合很少（基本上是做纯运算），所以并没有特殊处理。如果要解决这个问题，可以在 error 的时候注册一个 timeout 0 ，跑一个空消息即可。我已经提交了 patch 。

**Comment by cloudwu** [comment]
btw, 上面例子中的写法不推荐。因为目前并没有承诺 fork 的 coroutine 的唤醒次序。如果 wakeup 在  wait 之前先被运行，将导致 coList 中尚未写入 wait 的 coroutine 。

**Comment by hongling0** [comment]
@cloudwu 这样会延迟wakeup_queue中co的执行，因为消息队列中可能已经有消息了。
#870 wakeup的co需要在新的消息之前处理完。

**Comment by cloudwu** [comment]
@hongling0 wakeup 的运行时机并没有做任何承诺（比其它消息先还是后），目前只保证 wakeup 本身的次序。插入 `fork_queue` 会导致 wakeup 本身无序，我倾向于在同一个位置分发 wakeup 的消息。
