### ISSUE TITLE
des填充模式

### ISSUE THREAD

**Issue by ivebeendreamingforsolong** [cloudwu/skynet#876]
这个为什么要写个自定义的填充模式呢，用java来做des的加解密完全不匹配，最后没办法，看着你的填充模式自己实现的java端填充模式。

**Comment by cloudwu** [comment]
自己写个库或找个合适的 lua 库，这个和 skynet 无关。

**Comment by cloudwu** [comment]
btw, 我并没有自己发明 padding 算法，这里使用的是 https://www.di-mgt.com.au/cryptopad.html 的 method 2 .

**Comment by zhangdeke** [comment]
能不能修改为和主流语言的一致，我用unity3d 也无法兼容




| |
zhangdeke
邮箱：zhangdeke@126.com
|

Signature is customized by Netease Mail Master

在2018年08月17日 08:35，云风 写道：

btw, 我并没有自己发明 padding 算法，这里使用的是 https://www.di-mgt.com.au/cryptopad.html 的 method 2 .

**Comment by cloudwu** [comment]
skynet 并没有位置依赖 des 加密，也没有计划做成一个包罗万象的工具包，有需求可以自己实现。

**Comment by cloudwu** [comment]
我不了解 java 和 C# 中的 padding 模式，刚才查了一下 java 和 C# 也是不一致的。没有任何规范表明，有默认的 padding 算法。但是，java 提供有 nopadding 模式，可以自己 padding 。 参考：http://zhcheng.iteye.com/blog/1052309

**Comment by ivebeendreamingforsolong** [comment]
感谢您的回复，最后照着您的padding方式用java实现了

**Comment by ivebeendreamingforsolong** [comment]
作者使用的加密方式是 DES/ECB, 但是填充模式采用的策略和已知的PKCS5, ZERO等不一样，有需求的可以自己先对数据进行填充之后，再使用DES/ECB/NoPadding模式进行加密。

**Comment by toplifangkai** [comment]
package com;

import lombok.extern.slf4j.Slf4j;

import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.DESKeySpec;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;

@Slf4j
public class DES {
    private final static String Algorithm = "DES/ECB/NoPadding";//加密方法／运算模式／填充模式

    private static SecretKeyFactory keyFactory;
    private static final byte P = (byte) 0x80;

    static {
        try {
            keyFactory = SecretKeyFactory.getInstance("DES");
        } catch (NoSuchAlgorithmException e) {
            log.error("des key init failed", e);
        }
    }

    public static byte[] encrypt(byte[] msg, byte[] secret) {
        try {
            Cipher cipher = Cipher.getInstance(Algorithm);
            cipher.init(Cipher.ENCRYPT_MODE, getKey(secret));
            msg = padding(msg, cipher.getBlockSize());
            return cipher.doFinal(msg);
        } catch (Exception e) {
            log.error("encrypt failed", e);
            return msg;
        }
    }

    public static byte[] decrypt(byte[] msg, byte[] secret) {
        try {
            Cipher cipher = Cipher.getInstance(Algorithm);
            cipher.init(Cipher.DECRYPT_MODE, getKey(secret));
            return unPadding(cipher.doFinal(msg), cipher.getBlockSize());
        } catch (Exception e) {
            log.error("decrypt failed", e);
            return msg;
        }
    }

    private static byte[] padding(byte[] msg, int blockSize) {
        int paddingSize = blockSize - msg.length % blockSize;
        byte[] result = new byte[msg.length + paddingSize];
        System.arraycopy(msg, 0, result, 0, msg.length);
        result[msg.length] = P;
        for (int i = 0; i < paddingSize - 1; i++) {
            result[msg.length + i + 1] = 0;
        }
        return result;
    }

    private static byte[] unPadding(byte[] msg, int blockSize) {
        int len = msg.length;
        int unPadding = 0;
        for (int i = 1; i <= blockSize; i++) {
            if (msg[len - i] == 0) {
                unPadding++;
            } else if (msg[len - i] == P) {
                unPadding++;
                break;
            }
        }
        byte[] result;
        if (unPadding > 0) {
            result = new byte[len - unPadding];
            int sz = len - unPadding;
            System.arraycopy(msg, 0, result, 0, sz);
        } else {
            result = msg;
        }
        return result;
    }

    private static SecretKey getKey(byte[] secret) throws InvalidKeyException, InvalidKeySpecException {
        DESKeySpec key;
        try {
            key = new DESKeySpec(secret);
        } catch (InvalidKeyException e) {
            log.error("new des key failed", e);
            throw e;
        }
        try {
            SecretKey secretKey = keyFactory.generateSecret(key);
            return secretKey;
        } catch (InvalidKeySpecException e) {
            log.error("gen des key failed", e);
            throw e;
        }
    }
}

java版本，测试了下，应该没问题，可以参考下。

**Comment by cloudwu** [comment]
skynet 内置的 crypt 库目前支持多种 padding https://github.com/cloudwu/skynet/pull/1179
