### ISSUE TITLE
pbc传int64的bug？

### ISSUE THREAD

**Issue by gzkjh** [cloudwu/skynet#880]
今天发现用pbc传送一个很大的整数，protobuf里面按int64来定义的，发现接收到的比原来的少了1，如果传送的数值<int32的就没问题，大家有遇到这种情况？暂时我用string来代替了

**Comment by LaoZhongGu** [comment]
使用sproto可以吗？pbc都已经不再维护了，另外源码也是开放的可以考虑自己修改一下，看能否引入Lua 5.3的来解决。
