### ISSUE TITLE
jemalloc allocated分配的内存比程序占用的内存高出很多,怎样去优化内存使用呢

### ISSUE THREAD

**Issue by xxmio** [cloudwu/skynet#889]
线上跨服服务器运行10多天后, top工具看程序占用3.2G内存.进入console看了下,程序占用的内存不到500M.
跨服服务器和普通服务器一样,除了在活期期间容纳额外5个服数据, 这个时候会是个整个游戏里的峰值,
allocated分配的内存和实际占用是6:1左右,普通服务器是2:1左右.
能否通过什么方式优化程序内存分配,达到allocated和实际占用是1.5:1以下呢?

jemalloc使用的启动配置是
const char *je_malloc_conf = "background_thread:true,lg_tcache_max:8,dirty_decay_ms:3000,muzzy_decay_ms:0";

跨服服务器的内存信息
mapped      3203817472
active      3044864000
allocated   2997021464
total       460688423

普通服务器的内存信息
mapped      1427329024
active      1323036672
allocated   1248044472
total       563676999

**Comment by cloudwu** [comment]
是否有统计对：debug console 下 cmem 和 mem 之和才是有效内存占用。

**Comment by xxmio** [comment]
cmem和mem之和就是total值.
刚刚pstack程序,发现background_thread没启动.
打印jemalloc运行数据,mapped和retained非常大,应该是jemalloc没还给OS.
对比jemalloc_conf初始化参数和运行参数,应该是生效了
这个跟jemalloc 5.1.0手册对上不啊

jemalloc初始化参数
const char *je_malloc_conf = "background_thread:true,lg_tcache_max:8,dirty_decay_ms:3000,muzzy_decay_ms:0";

程序jemalloc运行中的参数
Run-time option settings
  opt.abort: false 
  opt.abort_conf: false 
  opt.retain: true
  opt.dss: "secondary"
  opt.narenas: 8
  opt.percpu_arena: "disabled"
  opt.metadata_thp: "disabled"
  opt.background_thread: true (background_thread: false)
  opt.dirty_decay_ms: 3000 (arenas.dirty_decay_ms: 3000) 
  opt.muzzy_decay_ms: 0 (arenas.muzzy_decay_ms: 0)

**Comment by xxmio** [comment]
这个线上一个服的数据
top出来程序占用了15G.
console的mem和cmem加起来是2G左右, stats.mapped是3.7G
下面是jemalloc现场,绝大部分未使用的数据都在mapped和retained

___ Begin jemalloc statistics ___
Version: "5.1.0-0-g0"
Build-time option settings
  config.cache_oblivious: true
  config.debug: false
  config.fill: true
  config.lazy_lock: false
  config.malloc_conf: ""
  config.prof: false
  config.prof_libgcc: false
  config.prof_libunwind: false
  config.stats: true 
  config.utrace: false
  config.xmalloc: false
Run-time option settings
  opt.abort: false
  opt.abort_conf: false
  opt.retain: true 
  opt.dss: "secondary"
  opt.narenas: 96
  opt.percpu_arena: "disabled"
  opt.metadata_thp: "disabled"
  opt.background_thread: true (background_thread: false)
  opt.dirty_decay_ms: 3000 (arenas.dirty_decay_ms: 3000)
  opt.muzzy_decay_ms: 0 (arenas.muzzy_decay_ms: 0)
  opt.junk: "false"
  opt.zero: false
  opt.tcache: true 
  opt.lg_tcache_max: 8
  opt.thp: "not supported"
  opt.stats_print: false
  opt.stats_print_opts: ""
Arenas: 96
Quantum size: 16
Page size: 4096 
Maximum thread-cached size class: 14336
Number of bin size classes: 36
Number of thread-cache bin size classes: 36
Number of large size classes: 196
Allocated: 2088172056, active: 3431829504, metadata: 252981832 (n_thp 0), resident: 3687518208, mapped: 3783319552, retained: 14770708480
Background threads: 0, num_runs: 0, run_interval: 0 ns
                           n_lock_ops       n_waiting      n_spin_acq  n_owner_switch   total_wait_ns     max_wait_ns  max_n_thds
background_thread                 903               0               0             130               0               0           0
ctl                               843               0               0             101               0               0           0
prof                                0               0               0               0               0               0           0
Merged arenas stats:
assigned threads: 29
uptime: 74735075600302
dss allocation precedence: "N/A"
decaying:  time       npages       sweeps     madvises       purged
   dirty:   N/A          821       286377      2512953      8835386
   muzzy:   N/A            0            0            0            0
                            allocated     nmalloc     ndalloc   nrequests
small:                     1483131416  1731308710  1715598654  3490888255
large:                      605040640      219926      218759      219926
total:                     2088172056  1731528636  1715817413  3491108181
                                     
active:                    3431829504
mapped:                    3783319552
retained:                 14770708480
base:                       252247616
internal:                      734216
metadata_thp:                       0
tcache_bytes:                 5875880
resident:                  3687518208
                           n_lock_ops       n_waiting      n_spin_acq  n_owner_switch   total_wait_ns     max_wait_ns  max_n_thds
large                           12267               0               0            2929               0               0           0
extent_avail                  6237788               9              20          270965         1000016         1000016           1
extents_dirty                15006204              61            5315         1317713        18000292        11000179           2
extents_muzzy                 2997555               0               0            4881               0               0           0
extents_retained              9618261               2               7          279121               0               0           1
decay_dirty                   2052795               0              11         1016599               0               0           0
decay_muzzy                   3520529               0               9         1014937               0               0           0
base                          1647003               0               0            3403               0               0           0
tcache_list                     12295               0               0            2956               0               0           0
bins:           size ind    allocated      nmalloc      ndalloc    nrequests      curregs     curslabs regs pgs   util       nfills     nflushes       nslabs     nreslabs      n_lock_ops       n_waiting      n_spin_acq  n_owner_switch   total_wait_ns     max_wait_ns  max_n_thds
                   8   0         9448        44711        43530      1591117         1181            5  512   1  0.461        40702        40801        37105            0          167974               0               0            3661               0               0           0
                  16   1       709872      1935553      1891186      7338882        44367          452  256   1  0.383       508906       308531         1498       319778         1193292               0              15          510318               0               0           0
                  32   2     16133568     92526832     92022658    306721452       504174        11176  128   1  0.352      6294021      1107584        99871     15831099        12126979             274            3909         3719161       118001584        12000182           3
                  48   3    135772032    245343191    242514607    717570998      2828584        24717  256   3  0.447      8310619      2563075       129795     30672356        19184720             874           12082         6271702       441006132        14000213           6
                  64   4    631448384    960285624    950419243   1018065395      9866381       157227   64   1  0.980     26501907     14911131      2856569    178060765        77993762           19162          266822        20803229      5216075750        30000462          11
                  80   5     76808320    131662481    130702377    716586565       960104        13002  256   5  0.288      5328813      1430762        38925     34560289        19398432            1388           19438         9125191       902012996        22000335           6
                  96   6     20006016     11169243     10960847     12865221       208396         3010  128   3  0.540      1548113       422759        15684      3604221         3955277               3             702         2215354         1000015         1000015           1
                 112   7     16695168     12672652     12523588     14323073       149064         1891  256   7  0.307      1535329       425527         8174      4125485         4570462              12             685         2615429         9000119         6000072           3
                 128   8      8300672     12799507     12734658     71479426        64849         3987   32   1  0.508      2755915       647867        26744      8016019         7962619              36            1716         4464097        48000663         9000111           3
                 160   9     50791200     73017255     72699810    255695680       317445        12303  128   5  0.201      4500561       906323        55960     22822228        13191707             695            6567         6189191       361005266        18000221           8
                 192  10     11680512      8844237      8783401      9245845        60836         2056   64   3  0.462      1801565       442685        36658      3183664         4555395              17             479         2180198        45000655        11000135           3
                 224  11     13076448      4450759      4392382      4020916        58377         1493  128   7  0.305       727205       370613         5976      1770367         2295205               4             135         1413617         7000093         5000063           1
                 256  12      9634048      3087793      3050160      3093690        37633         3400   16   1  0.691       886482       415616        57589      1562870         2737897               1             262         1306237         2000030         2000030           1
                 320  13    118737920     90061587     89690531    198655716       371056        14316   64   5  0.404      7331894      1582839       244593     27533429        18202641             741           10174         6806210       489007079        11000171           6
                 384  14      8508672      4557836      4535678      5176276        22158          971   32   3  0.713       851866       378612        23212      2411138         2726107               3             158         1576393         5000060         5000060           1
                 448  15      4633664      3397067      3386724      3229209        10343          222   64   7  0.727       548911       399403        14496      1718718         2231685               1              64         1274215               0               0           1
                 512  16      4321280       604907       596467       487687         8440         1081    8   1  0.975       191915       224875        50920       166880          776256               1              13          239555         1000017         1000017           1
                 640  17     45287040     27876325     27805564     82669287        70761        10015   32   5  0.220      3488743      1059749       127757     15559144        12270658             293            5554         5184206       166002329        13000161           4
                 768  18      6592512       467651       459067       557700         8584          662   16   3  0.810       177214       169541        13525       192778          560027               0               1          250040               0               0           0
                 896  19      6981632       643471       635679       463138         7792          606   32   7  0.401       191464       209478         5210       298277          578664               0               3          227478               0               0           0
                1024  20      2469888       673572       671160       477165         2412          619    4   1  0.974       236269       260139        33860       571728          789605               0               4          314554               0               0           0
                1280  21     58627840     37282294     37236491     49655134        45803        11965   16   5  0.239      6030384      2474776       627040     14746456        14450153             102            2725         3120773       107001644        13000197           4
                1536  22      2270208       168334       166856       186567         1478          326    8   3  0.566        89669        99715         5242        94118          285617               0               1          121380               0               0           0
                1792  23      8592640       315401       310606       235786         4795          344   16   7  0.871       138171       155301         3790       171753          431733               0               0          184812               0               0           0
                2048  24      1634304       356787       355989       290280          798          411    2   1  0.970       162938       139686        81100       236456          594335               0               1          169258               0               0           0
                2560  25     90490880      4667554      4632206      7344971        35348         7067    8   5  0.625      1264713       676653       176297      2602203         3504161               6             178         1247377         3000045         3000045           1
                3072  26       156672       199898       199847       173966           51           21    4   3  0.607       109890       116475        12341       136981          348959               0               0          137310               0               0           0
                3584  27      2494464       100335        99639        86358          696           97    8   7  0.896        56123        75606         4111        34727          202184               0               1           85596               0               0           0
                4096  28       466944        40673        40559        30402          114          114    1   1      1        24156        35961        40673            0          177090               0               0           44376               0               0           0
                5120  29     54778880      1320629      1309930      1869357        10699         4161    4   5  0.642       456357       373238        99039       993519         1453603               2              20          575325         7000105         6000090           2
                6144  30       141312        40053        40030        32189           23           18    2   3  0.638        25743        37493         9512        21024          116827               0               0           42008               0               0           0
                7168  31       100352        29837        29823        22897           14            8    4   7  0.437        17195        26032         3746        12455           79924               0               1           31847               0               0           0
                8192  32        90112        18809        18798        12710           11           11    1   2      1        11658        17475        18809            0           89638               0               0           21696               0               0           0
               10240  33     74475520       628408       621135       621828         7273         3657    2   5  0.994       286247       235765       145093       453322         1009446               0               5          267772               0               0           0
               12288  34        98304        10085        10077         6581            8            8    1   3      1         6278         9493        10085            0           54207               0               0           13815               0               0           0
               14336  35       114688         7359         7351         4791            8            7    2   7  0.571         4477         6707         2737         2471           33108               0               0           10576               0               0           0
large:          size ind    allocated      nmalloc      ndalloc    nrequests  curlextents
               16384  36            0         3674         3674         3674            0
               20480  37      2314240       107986       107873       107986          113
               24576  38       737280         7383         7353         7383           30
               28672  39        57344         3037         3035         3037            2
               32768  40        98304         3225         3222         3225            3
               40960  41     11632640        40220        39936        40220          284
               49152  42            0         1673         1673         1673            0
               57344  43            0         1823         1823         1823            0
               65536  44       131072          377          375          377            2
               81920  45      1228800        18628        18613        18628           15
               98304  46        98304         2755         2754         2755            1
              114688  47            0         2311         2311         2311            0
              131072  48       131072          692          691          692            1
              163840  49      1474560        13468        13459        13468            9
              196608  50            0         1068         1068         1068            0
              229376  51            0          574          574          574            0
              262144  52            0           75           75           75            0
              327680  53       655360         4747         4745         4747            2
              393216  54            0          799          799          799            0
              458752  55       458752          181          180          181            1
              524288  56            0          880          880          880            0
              655360  57       655360         1175         1174         1175            1
              786432  58    520617984          677           15          677          662
              917504  59      5505024           49           43           49            6
             1048576  60     10485760           24           14           24           10
             1310720  61      5242880         1223         1219         1223            4
             1572864  62     15728640          120          110          120           10
             1835008  63      3670016          151          149          151            2
             2097152  64      8388608           24           20           24            4
             2621440  65      5242880          678          676          678            2
             3145728  66      6291456            7            5            7            2
                     ---
             4194304  68      4194304            1            0            1            1
             5242880  69            0           81           81           81            0
             6291456  70            0           85           85           85            0
                     ---
            10485760  73            0           55           55           55            0
                     ---
arenas[0]:
assigned threads: 1
uptime: 74735075600302
dss allocation precedence: "secondary"
decaying:  time       npages       sweeps     madvises       purged
   dirty:  3000            0            0            0            0
   muzzy:     0            0            0            0            0
                            allocated     nmalloc     ndalloc   nrequests
small:                         581656        2331          77         947
large:                        2252800          32           0          32
total:                        2834456        2363          77         979
                                     
active:                       3121152
mapped:                      61841408
retained:                     1597440
base:                        43812928
internal:                      734216
metadata_thp:                       0
tcache_bytes:                  422520
resident:                    46960640
                           n_lock_ops       n_waiting      n_spin_acq  n_owner_switch   total_wait_ns     max_wait_ns  max_n_thds
large                             423               0               0             101               0               0           0
extent_avail                      499               0               0             134               0               0           0
extents_dirty                     499               0               0             134               0               0           0
extents_muzzy                     499               0               0             134               0               0           0
extents_retained                  574               0               0             134               0               0           0
decay_dirty                       423               0               0             101               0               0           0
decay_muzzy                       423               0               0             101               0               0           0
base                             1046               0               0             152               0               0           0
tcache_list                       423               0               0             101               0               0           0
bins:           size ind    allocated      nmalloc      ndalloc    nrequests      curregs     curslabs regs pgs   util       nfills     nflushes       nslabs     nreslabs      n_lock_ops       n_waiting      n_spin_acq  n_owner_switch   total_wait_ns     max_wait_ns  max_n_thds
                   8   0          808          101            0            1          101            1  512   1  0.197            1            0            1            0             424               0               0             102               0               0           0
                  16   1         1600          100            0            0          100            1  256   1  0.390            1            0            1            0             423               0               0             101               0               0           0
                  32   2         3072          100            4            0           96            1  128   1  0.750            1            0            1            0             424               0               0             102               0               0           0
                  48   3        27696          600           23          520          577            3  256   3  0.751            6            0            3            1             433               0               0             103               0               0           0
                  64   4        27328          448           21          398          427            7   64   1  0.953            7            0            7            1             437               0               0             103               0               0           0
                  80   5         6880          100           14            0           86            1  256   5  0.335            1            0            1            0             427               0               0             103               0               0           0
                  96   6         9504          100            1            0           99            1  128   3  0.773            1            0            1            0             426               0               0             103               0               0           0
                 112   7        11200          100            0            0          100            1  256   7  0.390            1            0            1            0             425               0               0             102               0               0           0
                 128   8         4096           32            0            0           32            1   32   1      1            1            0            1            0             425               0               0             102               0               0           0
                 160   9        16000          100            0            0          100            1  128   5  0.781            1            0            1            0             425               0               0             102               0               0           0
                 192  10        12096           64            1            0           63            1   64   3  0.984            1            0            1            0             426               0               0             103               0               0           0
                 224  11        22400          100            0            0          100            1  128   7  0.781            1            0            1            0             425               0               0             102               0               0           0
                 256  12         4096           16            0            0           16            1   16   1      1            1            0            1            0             425               0               0             102               0               0           0
                 320  13        20160           64            1            0           63            1   64   5  0.984            1            0            1            0             426               0               0             103               0               0           0
                 384  14        11520           32            2            0           30            1   32   3  0.937            1            0            1            0             427               0               0             103               0               0           0
                 448  15        28672           64            0            0           64            1   64   7      1            1            0            1            0             423               0               0             101               0               0           0
                 512  16         5120           10            0            0           10            2    8   1  0.625            1            0            2            0             426               0               0             102               0               0           0
                 640  17        17920           32            4            0           28            1   32   5  0.875            1            0            1            0             428               0               0             105               0               0           0
                 768  18        33792           44            0           28           44            3   16   3  0.916            1            0            3            0             455               0               0             103               0               0           0
                 896  19        26880           32            2            0           30            1   32   7  0.937            1            0            1            0             426               0               0             103               0               0           0
                1024  20            0            0            0            0            0            0    4   1      1            0            0            0            0             423               0               0             101               0               0           0
                     ---
                1280  21        20480           16            0            0           16            1   16   5      1            1            0            1            0             425               0               0             102               0               0           0
                1536  22        15360           10            0            0           10            2    8   3  0.625            1            0            2            0             426               0               0             102               0               0           0
                1792  23        28672           16            0            0           16            1   16   7      1            1            0            1            0             425               0               0             102               0               0           0
                2048  24            0            0            0            0            0            0    2   1      1            0            0            0            0             423               0               0             101               0               0           0
                     ---
                2560  25        23040           10            1            0            9            2    8   5  0.562            1            0            2            1             427               0               0             103               0               0           0
                3072  26        27648           10            1            0            9            3    4   3  0.750            1            0            3            1             428               0               0             103               0               0           0
                3584  27        32256           10            1            0            9            2    8   7  0.562            1            0            2            1             427               0               0             103               0               0           0
                4096  28            0            0            0            0            0            0    1   1      1            0            0            0            0             423               0               0             101               0               0           0
                     ---
                5120  29        51200           10            0            0           10            3    4   5  0.833            1            0            3            0             427               0               0             102               0               0           0
                6144  30            0            0            0            0            0            0    2   3      1            0            0            0            0             423               0               0             101               0               0           0
                7168  31            0            0            0            0            0            0    4   7      1            0            0            0            0             423               0               0             101               0               0           0
                8192  32            0            0            0            0            0            0    1   2      1            0            0            0            0             423               0               0             101               0               0           0
                     ---
               10240  33        92160           10            1            0            9            5    2   5  0.900            1            0            5            1             430               0               0             103               0               0           0
               12288  34            0            0            0            0            0            0    1   3      1            0            0            0            0             423               0               0             101               0               0           0
               14336  35            0            0            0            0            0            0    2   7      1            0            0            0            0             423               0               0             101               0               0           0
                     ---
large:          size ind    allocated      nmalloc      ndalloc    nrequests  curlextents
                     ---
               24576  38       712704           29            0           29           29
                     ---
               65536  44        65536            1            0            1            1
                     ---
              163840  49       163840            1            0            1            1
                     ---
             1310720  61      1310720            1            0            1            1
                     ---

**Comment by xxmio** [comment]
在jemalloc.stat看到了opt.retain:true.
这个选项是默认开启的吗?

**Comment by xxmio** [comment]
调整opt.retain:false后, 在压力测试时,当内存占用达到1/3后,会出现<jemalloc>: Error in munmap(): Cannot allocate memory, 程序申请不到内存后崩溃退出.

**Comment by sheldonzeng** [comment]
> 调整opt.retain:false后, 在压力测试时,当内存占用达到1/3后,会出现: Error in munmap(): Cannot allocate memory, 程序申请不到内存后崩溃退出.

请问xxmio你Error in munmap(): Cannot allocate memory这个问题是怎么解决的

**Comment by haley05** [comment]
> 线上跨服服务器运行10多天后, top工具看程序占用3.2G内存.进入console看了下,程序占用的内存不到500M.
> 跨服服务器和普通服务器一样,除了在活期期间容纳额外5个服数据, 这个时候会是个整个游戏里的峰值,
> allocated分配的内存和实际占用是6:1左右,普通服务器是2:1左右.
> 能否通过什么方式优化程序内存分配,达到allocated和实际占用是1.5:1以下呢?
> 
> jemalloc使用的启动配置是
> const char *je_malloc_conf = "background_thread:true,lg_tcache_max:8,dirty_decay_ms:3000,muzzy_decay_ms:0";
> 
> 跨服服务器的内存信息
> mapped 3203817472
> active 3044864000
> allocated 2997021464
> total 460688423
> 
> 普通服务器的内存信息
> mapped 1427329024
> active 1323036672
> allocated 1248044472
> total 563676999


> 线上跨服服务器运行10多天后, top工具看程序占用3.2G内存.进入console看了下,程序占用的内存不到500M.
> 跨服服务器和普通服务器一样,除了在活期期间容纳额外5个服数据, 这个时候会是个整个游戏里的峰值,
> allocated分配的内存和实际占用是6:1左右,普通服务器是2:1左右.
> 能否通过什么方式优化程序内存分配,达到allocated和实际占用是1.5:1以下呢?
> 
> jemalloc使用的启动配置是
> const char *je_malloc_conf = "background_thread:true,lg_tcache_max:8,dirty_decay_ms:3000,muzzy_decay_ms:0";
> 
> 跨服服务器的内存信息
> mapped 3203817472
> active 3044864000
> allocated 2997021464
> total 460688423
> 
> 普通服务器的内存信息
> mapped 1427329024
> active 1323036672
> allocated 1248044472
> total 563676999

xxmio你好，请问后来你的这个问题是怎么解决的？我现在也遇到占用内存很多，不释放的问题
