### ISSUE TITLE
测试及开发服务器跑的很欢乐，但是生产出问题了。websocket

### ISSUE THREAD

**Issue by chigco** [cloudwu/skynet#898]
[:01000011] lua call [0 to :1000011 : 0 msgsz = 24] error : [31m./skynet/lualib/skynet.lua:526: ./skynet/lualib/skynet.lua:156: ./skynet/lualib/skynet/socket.lua:253: assertion failed!
stack traceback:
	[C]: in upvalue 'assert'
	./skynet/lualib/skynet/socket.lua:253: in function 'skynet.socket.read'
	(...tail calls...)
	./build/lualib/websocket.lua:236: in function 'websocket.recv_frame'
	./build/lualib/websocket.lua:212: in function 'websocket.recv'
	./build/lualib/websocket.lua:341: in function 'websocket.start'
	./service/wsgate/main.lua:57: in upvalue 'handle_socket'
	./service/wsgate/main.lua:88: in field 'callback'
	./skynet/lualib/skynet/socket.lua:105: in field '?'
	./skynet/lualib/skynet/socket.lua:161: in upvalue 'f'
	./skynet/lualib/skynet.lua:111: in function <./skynet/lualib/skynet.lua:105>
stack traceback:
	[C]: in upvalue 'assert'
	./skynet/lualib/skynet.lua:526: in function 'skynet.dispatch_message'[0m

求解是为什么？

**Comment by cloudfreexiao** [comment]
skynet 没有 websocket 自己找找 谁写的吧 要不然 这没法看
看这 assert 似乎是 fd 被 意外 关闭了 ？

**Comment by chigco** [comment]
是加了前置nginx，会不会是这一块有问题。因为我直连测试OK。
要上WSS加了前置nginx反向代理

**Comment by cloudwu** [comment]
不是有调用堆栈么？你把这个 socket close 了，导致对象为空啊。

**Comment by cloudfreexiao** [comment]
忘了提醒了 skynet里用 websocket 建议使用[ws](https://github.com/sctangqiang/skynetpatch) 这个
有个 [lua 版本](https://github.com/Skycrab/skynet_websocket) 有bug 如果你要查 你去找找 那个库的bug吧 反正 如果你用的这个 恭喜你 踩坑了

**Comment by chigco** [comment]
主要是我在测试或者开发都是没有问题的。
一在生产上做部署，就会抛这个异常。
skynet + nginx websocket 反向 用的wss的。

**Comment by cloudfreexiao** [comment]
那只是 开发时候 没触发这个bug 又 不代表 没bug 不是吗？

**Comment by chigco** [comment]
@cloudfreexiao 项目好像就是用的这个啊。。。。

**Comment by chigco** [comment]
我换库看一下。nginx把能延长能配的都配了，还是出现这个问题。

**Comment by qq190219044** [comment]
@chigco 我也是用的你之前在用的这个websocket.lua库.
最近也有个项目是用nginx在前面,用于支持wss. 之前没加nginx时在生产环境也跑了一年多了,加了nginx也跑了有四五个月了吧.
像这个程序我基本都是几个月不重启的,也从来还没遇到过你的这种情况.
可能是我运气好没触发bug,也可能是我们线上用户没你们多(单个该程序同时维护4k+个socket).也可能是你自己的哪部分逻辑有问题吧.
建议你自己在open fd和 close fd的地方加些调试日志,看究竟是被哪里意外关闭了连接.
