### ISSUE TITLE
问下云大，sproto能直接序列化和解析"a[1000]=10"的格式么？格式怎么写？

### ISSUE THREAD

**Issue by teahouse** [cloudwu/skynet#899]
资料太少，没有这方面的介绍，我基本用｛id=1000，val=10｝，然后*struct(id)这样的写法，不过比较不方便，因为服务器计算结果的结果集也要转换为id、val格式。响应的客户端也要改解析方法。其他都非常方便。

**Comment by cloudwu** [comment]
不能。
