### ISSUE TITLE
skynet的lua取消了module函数？

### ISSUE THREAD

**Issue by gzkjh** [cloudwu/skynet#904]
本来打算用 module("abc")来封装一个模块，结果报错：call a nil value (global 'module')
直接用lua命令来执行这个文件是正常的....

**Comment by cloudwu** [comment]
直接在 preload 里写 print = function(...) ... end
或者 _G.print = 更明确。

**Comment by gzkjh** [comment]
谢谢解答，我检查了一下，外部安装的是lua5.1的...难怪可以通过。
另外，我在preload里面加了没用，看代码，是因为snax服务里面启动的时候，有 loadfile(filename,"bt",G) 这里的G替换了全局环境，这里是忘记继承原来的环境变量，还是刻意不继承的？

**Comment by cloudwu** [comment]
那就不要用 snax
