### ISSUE TITLE
我有个疑问，关于linux信号，运维

### ISSUE THREAD

**Issue by gyx9208** [cloudwu/skynet#906]
我问了公司别的项目的服务器同事，他们用c++写的服务器，运维会给服务器进程发信号，比如更新数值文件，发个信号，进程就知道了。

我想知道skynet能接收信号吗？或者说和运维合作上，一般怎么做呢？我能想到的是通过网络。。。在skynet内部再做一个service专门接收指令。。。。

是这样的吗？

**Comment by qinhanlei** [comment]
Make a simple http server

**Comment by cloudwu** [comment]
btw, debug console 本身就是一个 simple http server 。比如你可以用 http://127.0.0.1:8000/list 列出所有服务。
