### ISSUE TITLE
skynet.call 疑问

### ISSUE THREAD

**Issue by kevin8990** [cloudwu/skynet#907]
假设a服务向b服务发起一个call，b服务在相应这个请求的时候没有skynet.ret或者调用了skynet.ignoreret()，
那么a服务的这个发起请求的coroutine,是不是永远都不会返回了，一直处于挂起状态了？

**Comment by cloudwu** [comment]
如果你没有调用 skynet.ignoreret 会收到警告。如果调用了，那么久永远不会返回了。ignoreret 就是让你重视这种 bug 。
