### ISSUE TITLE
请问跨服务的异常，该怎么捕捉？

### ISSUE THREAD

**Issue by renyankankan** [cloudwu/skynet#910]
A服务call B服务，B服务中使用assert，并抛出异常，请问A该怎么捕获这个assert异常，目前在A服务里只能获取到如下异常: skynet.lua:369: call failed

**Comment by cloudwu** [comment]
你这不是捕获到了？

**Comment by renyankankan** [comment]
@cloudwu 谢谢云大回复，我表达的意思是assert抛出的详细异常信息，比如: assert(false,{code=1, msg="test1"}), 能不能在A服务中活到到{code=1, msg="test1"}??

**Comment by renyankankan** [comment]
谢谢云大回复，我表达的意思是assert抛出的详细异常信息，比如: assert(false,{code=1, msg="test1"}), 能不能在A服务中获得到{code=1, msg="test1"}??

**Comment by cloudwu** [comment]
那我认为你的需求是：B 能不能有两种方式回应 A 的请求，一是用正常的途径 skynet.ret 回应，二是异常回应，比如用 assert false 回应一个对象。

你可以针对这个需求自己封装。

1. 定义一个新的协议和 lua 类似，比如叫 exlua 。
2. 在 exlua 的 dispatch 函数中使用 pcall 捕获异常，如果发生异常，调用 skynet.ret(skynet.pack(false, errobj)) 。
3. 正常回应 skynet.ret(skynet.pack(true, response))
4. 封装 skynet.call ，使用 exlua 协议，并处理回应的第一个 boolean 值，识别是那种回应形式。根据需要再用 error raise 到上一层。注意，依然需要 pcall ，捕获因为对方服务退出导致的异常。

**Comment by renyankankan** [comment]
@cloudwu 感谢解答，是的，需求如你上面所说； 但如果自定义协议的话，就不能使用snax了吧，看来只能有所取舍
