### ISSUE TITLE
出现Unknown command错误

### ISSUE THREAD

**Issue by EvilKnight331** [cloudwu/skynet#912]
偶现的问题，常发生在服务节点启动后的半个小时内，类似的报错日志如下：
[0000001a] ./lualib/service.lua:153 -- Unknown command : [gettitle] --- stack traceback:
	./lualib/service.lua:153: in upvalue 'f'
	./skynet/lualib/skynet.lua:111: in function <./skynet/lualib/skynet.lua:105>

gettitle消息是在某一个服务（地址19）中处理的，而此处的消息却在另一个服务（地址1a）上被接收到。这是跨节点服务调用，消息目标节点没有问题，只是该目标节点上的服务没对。使用cluster.send或者cluster.call发送消息，node和address都是注册过的。

skynet版本：1.1.0（2017-10-31）

**Comment by cloudwu** [comment]
cluster 消息全部在 clusterd 服务中中转，你可以加 log 调试，或直接用 skynet.trace() 跟踪 log . https://blog.codingnow.com/2018/05/skynet_trace.html

跨节点传输消息，目标地址是编码在消息中的。除非打包消息环节出错，否则不可能投递错误。

**Comment by cloudwu** [comment]
btw, 没有特殊理由，请不要使用老版本。尽量跟进 master HEAD .
