### ISSUE TITLE
mac 10.14 (18A391)版本下 socket断开连接会崩溃？

### ISSUE THREAD

**Issue by paradiseboy9527** [cloudwu/skynet#913]
skynet(40456,0x700009187000) malloc: *** error for object 0x7fb0e3e607d0: pointer being freed was not allocated
skynet(40456,0x700009187000) malloc: *** set a breakpoint in malloc_error_break to debug

报这个错误？

**Comment by cloudwu** [comment]
无法重现，请帮忙定位问题。

**Comment by korialuo** [comment]
macbook pro 10.14 测试代码如下， 用 nc 连接服务端，不管是服务端主动断开连接还是客户端主动断开，暂未发现问题。
```
local skynet = require "skynet"
local socket = require "skynet.socket"

skynet.start(function()
    local lsnfd = socket.listen("127.0.0.1", 12345)
    socket.start(lsnfd, function(clifd, addr)
        skynet.error("client connected: "..clifd.." "..addr)
        socket.start(clifd)
        socket.write(clifd, "hello!\n")
        skynet.fork(function()
            skynet.sleep(200)
            skynet.error("close client fd: "..clifd)
            socket.close(clifd)
        end)
    end)
end)
```

**Comment by paradiseboy9527** [comment]
我电脑升级前是 没问题的 升级到10.14后就出这个问题了，我今天上午再做一些详细的测试

**Comment by paradiseboy9527** [comment]
切到 https://github.com/cloudwu/skynet_sample 代码没做任何修改 居然也报
skynet(14161,0x70000dd46000) malloc: *** error for object 0x7ffb8499f660: pointer being freed was not allocated
skynet(14161,0x70000dd46000) malloc: *** set a breakpoint in malloc_error_break to debug
./run.sh: line 18: 14161 Abort trap: 6           $ROOT/skynet/skynet $ROOT/config
难道我本地装了某些第三库导致的？

**Comment by paradiseboy9527** [comment]
没有

**Comment by paradiseboy9527** [comment]
系统清理了下，重新clone了一份代码  重新编译，现在问题不出现了，感谢两位大神
