### ISSUE TITLE
模拟服务消息返回解开一个挂起的协程

### ISSUE THREAD

**Issue by TQING1990** [cloudwu/skynet#914]
服务A call 服务B，由于Bug导致 B 无法 ret，导致 A 中的一个业务死锁。task A 查到挂起协程的session后，注入执行下面的方法，可以解开死锁。

local skynet = require("skynet")
function breakCoroutine( session, msg, size )
    skynet.dispatch_message(1, msg, size, session, 0)
end

请问，使用这种方法是否会导致其他的问题？

**Comment by cloudwu** [comment]
如果你需要以 B 的身份给 A 发条消息，不需要非要让 B 发。任何服务用 skynet.redirect 都可以指定发送者地址。

**Comment by TQING1990** [comment]
明白了，谢谢

**Comment by cloudwu** [comment]
另外。你应该发送一个 error 类型的消息更好，而不是回应一个正常的返回。
