### ISSUE TITLE
 sharedata 更新数据

### ISSUE THREAD

**Issue by kevin8990** [cloudwu/skynet#917]
有个疑问，假如我有一个配置文件需要热更新，调用package.loaded["xxx"] = nil ，再require "xxx"，，然而skynet的使用的lua版本是修改过的，这样不行。有什么方法，还是使用skynet版本的lua，又可以重新加载到这个文件？？

**Comment by cloudwu** [comment]
不要用 require 读数据，那个是读代码用的。

数据应该用 io.open 打开，用 content = f:read "a" 读出来。如果数据是 lua 代码，再用 load(content) 。

**Comment by kevin8990** [comment]
ok，谢谢云大！！
