### ISSUE TITLE
lua-netpack的异常判断

### ISSUE THREAD

**Issue by sheldonzeng** [cloudwu/skynet#920]
lua-netpack.c filter数据的时候没有对pack_size==0的情况异常处理

**Comment by cloudwu** [comment]
这是一个内部模块，只能处理 `SKYNET_SOCKET_TYPE_*` 类型的消息，skynet 保证不会传递 pack_size == 0 的情况。

**Comment by sheldonzeng** [comment]
我自己在应用层对包长度0的情况做了异常处理（关掉连接），但我觉得在网络层过滤掉更好，不应该传0长度的包给应用层

**Comment by cloudwu** [comment]
我理解错了，是说发过来 00 00 00 00 这样的包？会有怎样的问题？

**Comment by sheldonzeng** [comment]
> 我理解错了，是说发过来 00 00 00 00 这样的包？会有怎样的问题？
> 
> 单单说长度为 0 的数据包，是合法的。

可能应用场景不一样，我这里使用场景包数据至少会有个消息号，所以pack_size==0的情况就是异常包

**Comment by cloudwu** [comment]
这个是底层协议，并不应该禁止长度为 0 ，或长度为 1 ... 的包。你那个是应用层协议。应该放在应用层解决。

**Comment by sheldonzeng** [comment]
明白
