### ISSUE TITLE
package.loaded[file]=nil后再require file 并没有更新

### ISSUE THREAD

**Issue by judithzzh** [cloudwu/skynet#921]
while true do
	local a = require "test"
	print(a.b)
	package.loaded["test"] = nil
	Sleep(2)
end
在运行期间 改变test里a.b的值，我用原生lua执行，test里值更改后，print出来的是最新的，而用skynet/3rd/lua/lua执行，a.b的值不变 恳请各位大神指点一二

**Comment by judithzzh** [comment]
从之前的issue里找到答案了

**Comment by oalpha** [comment]
@judithzzh  请问下怎么解决的？

**Comment by ylme** [comment]
> 
> 
> @judithzzh 请问下怎么解决的？

阅读文档 RTFM 
https://github.com/cloudwu/skynet/wiki/CodeCache
io.open 打开文件 然后 load 加载。
