### ISSUE TITLE
sproto相关

### ISSUE THREAD

**Issue by judithzzh** [cloudwu/skynet#922]
请问下，不同的sproto文件如何共享同一个结构呢？
比如，a.sproto里有个 .PlayerData{xxx}，现在b.sproto和c.sproto里也要用到.PlayerData

**Comment by cloudwu** [comment]
楼上说的对。sproto.core.newproto 的输入参数是字符串而不是文件。解决方案在于，你怎么提供你要的字符串，而不在于文件怎么组织。
