### ISSUE TITLE
疑是内存泄漏问题

### ISSUE THREAD

**Issue by zlibrary** [cloudwu/skynet#929]
最近写了个“SKYNET”测试， 怀疑是虚拟机没有能干净的释放内存， 下面是问题的描述， 请帮忙看看。

1. 创建N多个不做任何事情的服务

~~~
local skynet = require "skynet"

skynet.start(function()
        skynet.dispatch("lua", function(session, address, ...)
                skynet.exit()
        end)
end)
~~~

2. 在主服务中连续创建释放上述服务

~~~
local skynet = require "skynet"
local memory = require "memory"

skynet.start(function()
        for i = 1, 40 do
                local svc = skynet.newservice("svcname")
                skynet.send("svc", "lua")
                skynet.sleep(20)
        end

        skynet.fork(function()
                skynet.sleep(300)
                for k, v in pairs(memory.info()) do
                        print(string.format('%s : %s', k, v))
                end
        end)
end)
~~~

3. 打印的结果

2 : 166864
3 : 132784
4 : 71632
5 : 41136
6 : 12592
7 : 58688
8 : 9504
9 : 5296
10 : 64
11 : 64
13 : 64
14 : 64
15 : 64
16 : 64
4294967295 : 6327648
25 : 64

从我自己的认知来看， 从 10 开始的服务已经关闭了， 而且共享的代码块应该是 9 这个服务分配内存来保存的， 那么 10 开始的服务不应该出现内存剩余的问题了。有人可以帮忙解释一下原因吗？？

**Comment by zhouyanlt** [comment]
请把 `memory.lua` 的代码贴出来

**Comment by hongling0** [comment]
这个内存是在正常的
见代码https://github.com/cloudwu/skynet/blob/master/3rd/lua/lauxlib.c
里面的load函数

**Comment by zlibrary** [comment]
memory是“skynet”自带的内存查询代码， 如果这个内存是正常的， 按我们这边的业务需要， 比如某个类型的服务存在大批量的创建， 销毁过程， 那不是会出现内存泄漏的情况了吗？

**Comment by hongling0** [comment]
```
static const void *
load(const char *key) {
  if (CC.L == NULL)
    return NULL;
  SPIN_LOCK(&CC)
    lua_State *L = CC.L;
    lua_pushstring(L, key);
    lua_rawget(L, LUA_REGISTRYINDEX);
    const void * result = lua_touserdata(L, -1);
    lua_pop(L, 1);
  SPIN_UNLOCK(&CC)

  return result;
}
```
不是泄漏
内存消耗在lua_pushstring(L, key)这里，这里申请的内存会被gc掉

你代码里面的require会调用到这个

**Comment by zlibrary** [comment]
继续上述的测试， 发现增加了 fullgc 代码后， 确实内存是被完全释放了， 但是还是有点疑惑， 从我的测试代码来看， 在打印内存信息的时候， VM其实已经关闭了， 这个时候其实已经没有任何办法对已经关闭的VM进行GC操作了，在我没有在VM关闭前，手工进行 fullgc 的情况下， 实际上还是出现内存泄漏的问题。

**Comment by zlibrary** [comment]
确实如此， 是我想错了。感谢hongling0的帮助。

**Comment by cloudwu** [comment]
See #415 #336
