### ISSUE TITLE
dns模块解析会先检查 hosts 文件的设置？

### ISSUE THREAD

**Issue by feihuroger** [cloudwu/skynet#933]
环境都是一样的，centos 7.5
配置了一个http的api接口服，设置了一个子域名到内网IP，但发现在有的测试环境是有效的，使用本地的hosts设置。但在有的测试环境无效，直接跳过了本地hosts的设置。这个已经成为了薛定谔的猫。

在出问题的测试机终端上，ping这个域名，得到是hosts里的设置。

尝试解决，也设置了 host.conf，显性的确定解析顺序，order hosts,bind。

**Comment by cloudwu** [comment]
dns 模块是直接走的 udp 协议，不检查本地 host 配置。

**Comment by feihuroger** [comment]
谢谢，后来我们也看来源码，确实是直接UDP了。 这个问题最终原因还是不知道怎么回事，我们以为正确的工作方式，不是按照源码的本意在运行。也可能也和研发内网的网络环境，nameserver有一定关系。后来想到一个QD的解决方案，直接修改dns的源码，统一返回的时候写死域名解析IP。毕竟一个项目里面固定需要解析的域名只有一两个。
