### ISSUE TITLE
仍然出现error loading module 'skynet.core' 的问题

### ISSUE THREAD

**Issue by xiaozia** [cloudwu/skynet#935]
`error loading module 'skynet.core' from file '/home/hupan/skynet/luaclib/skynet.so':
	/home/hupan/skynet/luaclib/skynet.so: undefined symbol: dump_mem_lua
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	lualib/skynet.lua:2: in main chunk
	[C]: in function 'require'
	lualib/skynet/manager.lua:1: in main chunk
	[C]: in function 'require'
	my_workspace/agentE.lua:4: in main chunk
	[C]: in ?
`
今天在github上check的最新版的skynet，虚拟机上的ubuntu18.04上，学习skynet，跑example下的agent.lua，仍然会出现这样的问题。require "skynet"的时候，报错的。查看了之前的issues，说是解决了，最新版的仍然出现的问题。。。求助中。。。

**Comment by cloudwu** [comment]
先读 wiki ，了解 skynet 如何工作。

**Comment by xiaozia** [comment]
好的，我先去看文档去。谢谢风大大的回复
