### ISSUE TITLE
sharedata 的 query api 在查询一个不存在的共享数据时，是不是应该返回nil 好一点呢？

### ISSUE THREAD

**Issue by disemboltura** [cloudwu/skynet#937]
现在是直接断言失败， 为啥不返回nil 呢？

**Comment by cloudwu** [comment]
因为不希望用的人每次取都判断一次。这是这个模块的 api 约定。

**Comment by sendysucc** [comment]
sharedata存在的目的是啥，redis是否可以完全代替sharedata呢

**Comment by disemboltura** [comment]
> > 因为不希望用的人每次取都判断一次。这是这个模块的 api 约定。
> 
> 使用redis是否会比使用 sharedata 来共享数据是否会好一点？ 如果在有redis的情况下，什么情况使用sharedata呢？

虽然sharedata 使用要比redis 简单方便一些
