### ISSUE TITLE
日志文件被切割后，写入后文件大小没有变

### ISSUE THREAD

**Issue by BreezeCode** [cloudwu/skynet#938]
假如清空前的日志文件a.log大小是1342，执行 truncate -s 0 a.log 后变为了0，当写入一个大小为46的日志，a.log的大小为1388，并不是46

**Comment by BreezeCode** [comment]
将service_logger.c中 inst->handle = fopen(parm,"w"); 改成 inst->handle = fopen(parm,"ab"); 问题解决，但不知是否妥当

**Comment by cloudwu** [comment]
用 logrotate , 使用 kill -HUP 发信号触发 freopen 。

**Comment by BreezeCode** [comment]
好的，感谢！
