### ISSUE TITLE
fork协程后无限While循环加sleep，内存增长，不会自动gc

### ISSUE THREAD

**Issue by kingbird2011** [cloudwu/skynet#939]

**Comment by kingbird2011** [comment]
如题，fork了一些协程来做一些update逻辑，无限while循环，里面有sleep
发现sleep会导致内存增加，并且不会自动gc
手动debug上去后，看内存是无限增加的。手动gc可以让内存恢复到一个稳定值。
否则内存占用会持续增加。开了一夜内存增加100多M

**Comment by cloudwu** [comment]
无法重现，建议自己分析，看什么对象没有释放。

**Comment by kingbird2011** [comment]
用snapshot看过update_aoi函数前后，没有新增table。。。

debug看内存，随时间增长



手动gc后，内存恢复，并且恢复到同一个值。



 skynet.fork(function ()
  while true do
   skynet.sleep(100)
   update_aoi()
  end
 end)

**Comment by kingbird2011** [comment]
<CMD OK>
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	106.58 Kb (snlua debug_console 8888)
:0000000a	4959.10 Kb (snlua test_aoiserver)
:0000000b	53.19 Kb (snlua multicastd)
<CMD OK>
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	108.66 Kb (snlua debug_console 8888)
:0000000a	4961.96 Kb (snlua test_aoiserver)
:0000000b	53.19 Kb (snlua multicastd)
<CMD OK>
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	110.75 Kb (snlua debug_console 8888)
:0000000a	4964.82 Kb (snlua test_aoiserver)
:0000000b	53.19 Kb (snlua multicastd)
<CMD OK>
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	112.83 Kb (snlua debug_console 8888)
:0000000a	4967.20 Kb (snlua test_aoiserver)
:0000000b	53.19 Kb (snlua multicastd)
<CMD OK>
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	114.91 Kb (snlua debug_console 8888)
:0000000a	4970.54 Kb (snlua test_aoiserver)
:0000000b	53.19 Kb (snlua multicastd)
<CMD OK>
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	116.99 Kb (snlua debug_console 8888)
:0000000a	4972.92 Kb (snlua test_aoiserver)
:0000000b	53.19 Kb (snlua multicastd)

**Comment by kingbird2011** [comment]
`<CMD OK>
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	106.58 Kb (snlua debug_console 8888)
:0000000a	4959.10 Kb (snlua test_aoiserver)
:0000000b	53.19 Kb (snlua multicastd)
<CMD OK>
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	108.66 Kb (snlua debug_console 8888)
:0000000a	4961.96 Kb (snlua test_aoiserver)
:0000000b	53.19 Kb (snlua multicastd)
<CMD OK>
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	110.75 Kb (snlua debug_console 8888)
:0000000a	4964.82 Kb (snlua test_aoiserver)
:0000000b	53.19 Kb (snlua multicastd)
<CMD OK>
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	112.83 Kb (snlua debug_console 8888)
:0000000a	4967.20 Kb (snlua test_aoiserver)
:0000000b	53.19 Kb (snlua multicastd)
<CMD OK>
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	114.91 Kb (snlua debug_console 8888)
:0000000a	4970.54 Kb (snlua test_aoiserver)
:0000000b	53.19 Kb (snlua multicastd)
<CMD OK>
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	116.99 Kb (snlua debug_console 8888)
:0000000a	4972.92 Kb (snlua test_aoiserver)
:0000000b	53.19 Kb (snlua multicastd)
`

**Comment by kingbird2011** [comment]
`
<CMD OK>
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	106.58 Kb (snlua debug_console 8888)
:0000000a	4959.10 Kb (snlua test_aoiserver)
:0000000b	53.19 Kb (snlua multicastd)
<CMD OK>
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	108.66 Kb (snlua debug_console 8888)
:0000000a	4961.96 Kb (snlua test_aoiserver)
:0000000b	53.19 Kb (snlua multicastd)
<CMD OK>
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	110.75 Kb (snlua debug_console 8888)
:0000000a	4964.82 Kb (snlua test_aoiserver)
:0000000b	53.19 Kb (snlua multicastd)
<CMD OK>
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	112.83 Kb (snlua debug_console 8888)
:0000000a	4967.20 Kb (snlua test_aoiserver)
:0000000b	53.19 Kb (snlua multicastd)
<CMD OK>
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	114.91 Kb (snlua debug_console 8888)
:0000000a	4970.54 Kb (snlua test_aoiserver)
:0000000b	53.19 Kb (snlua multicastd)
<CMD OK>
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	116.99 Kb (snlua debug_console 8888)
:0000000a	4972.92 Kb (snlua test_aoiserver)
:0000000b	53.19 Kb (snlua multicastd)

`

**Comment by kingbird2011** [comment]
`
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	147.55 Kb (snlua debug_console 8888)
:0000000a	5475.25 Kb (snlua test_aoiserver)
:0000000b	53.19 Kb (snlua multicastd)
<CMD OK>
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	90.17 Kb (snlua debug_console 8888)
:0000000a	5479.54 Kb (snlua test_aoiserver)
:0000000b	53.19 Kb (snlua multicastd)
<CMD OK>
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	92.25 Kb (snlua debug_console 8888)
:0000000a	5480.97 Kb (snlua test_aoiserver)
:0000000b	53.19 Kb (snlua multicastd)
<CMD OK>
mem
:00000004	54.25 Kb (snlua cdummy)
:00000006	48.23 Kb (snlua datacenterd)
:00000007	65.66 Kb (snlua service_mgr)
:00000008	49.71 Kb (snlua rm_dbmain)
:00000009	84.53 Kb (snlua debug_console 8888)
:0000000a	5481.92 Kb (snlua test_aoiserver)

`

可以发现 debug_console  触发了gc，但是 test_aoiserver没有，它的代码也很简单

`
local function do_something()
	for i = 1, 1000 do
		local a = {}
	end
end

function test_gc()
	while true do
		skynet.sleep(100)
		do_something()
	end
end

skynet.start(function()
	test_gc()
end)

`

**Comment by kingbird2011** [comment]
内存并没有泄漏，因为gc后，内存恢复了，并且恢复到一个稳定值，只是gc会永不触发。

**Comment by kingbird2011** [comment]
有做了许多不同测试，发现出现过一次他是能自动gc的，那一次我10ms循环一次，每个函数内创建了100000个table。
但是我们开发环境曾经开了一夜内存增加了100来M，没试过更久。
所以可能是我对这个gc发生的时机理解的还有问题吧。

**Comment by cloudwu** [comment]
http://lua-users.org/lists/lua-l/2018-04/msg00087.html

lua 的自动 gc 不靠时间驱动，不靠已配分的内存驱动，也不是因为多运行了代码就一定运行。唯一驱动 gc 的是新分配的内存。

解决你的问题最简单的方法是加个定时器定期调用 collectgarbage("step", n)
