### ISSUE TITLE
Is CLOCK_THREAD_CPUTIME_ID better for skynet.hpc when used for profiling?

### ISSUE THREAD

**Issue by t0350** [cloudwu/skynet#941]
https://github.com/cloudwu/skynet/blob/master/lualib-src/lua-skynet.c#L29
在做性能分析，计时的时候发现`skynet.hpc`使用的是`CLOCK_MONOTONIC`，一方面该值会受 ntp 影响，另一方面统计的也不是 cpu 时间。是否使用`CLOCK_THREAD_CPUTIME_ID`更合适？
麻烦云风看看

ps：lua-profile.c 使用的则是`CLOCK_THREAD_CPUTIME_ID`

**Comment by cloudwu** [comment]
因为用途不同。 lua-profile.c 内部保证了计算同一个线程上的时间，这里主要是给 trace 使用，一定会有任务切换，skynet 自己做的调度，所以极有可能切到另一个线程上，所以不能使用  `CLOCK_THREAD_CPUTIME_ID` 。

避免 ntp 影响可以换成 `CLOCK_MONOTONIC_RAW` ，不过我觉得性能分析影响不大。此处 `get_time` 不仅仅是 hpc 函数调用。

**Comment by t0350** [comment]
ok，明白了。
另外看了下代码没太明白 lua-profile.c 是怎么做到保证在同一个 os 线程上？

**Comment by cloudwu** [comment]
lua-profile.c 只统计当前任务下的时长，一旦切换 coroutine 就停止计时了。

https://github.com/cloudwu/skynet/blob/master/lualib/skynet.lua#L10-L20

是通过替换 coroutine.yield  coroutine.resume 实现的。

**Comment by t0350** [comment]
明白了，谢谢~
