### ISSUE TITLE
sproto问题

### ISSUE THREAD

**Issue by kingbird2011** [cloudwu/skynet#942]
在用sproto的时候，传递的table比较特殊，数据是通过meta来访问的，本体table没有数据。
其他时候都没问题，但是在处理有主键的数组时，数据会发送不过去

经过检查发现，有主键的数组是使用lua_next来获取数据的，它不考虑meta的情况。
而无主键的数组使用lua_geti， 会触发index方法，至少我可以在lua层解决。
目前唯一的解决方法是构造一个新的无meta的纯净table，但是显然不太好。

这种差异使得功能出现了歧义，我自己觉得要么都不考虑meta，要么都考虑，能减少被坑的几率。
是否有其他因素？

**Comment by cloudwu** [comment]
增加了 __pairs 支持，看看？

**Comment by kingbird2011** [comment]
收到。。。。
几个月没更新，原来已经有了啊
我刚自己改了一版取__pairs的，也OK了。。

**Comment by kingbird2011** [comment]
收到，我自己改了一版，方法差不多。
不过我没有存iter_table, 我直接把 __pairs返回的table和iter替换了原来的array_index和iter_index
然后额外存了个iter_func的索引。
