### ISSUE TITLE
有没有自愿者帮忙写一个 ssl 库给 skynet 用？

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/skynet#943]
为了用 skynet 可以发起 https 连接，我们需要一个做一个 openssl 的 binding 。（否则就需要一个反向代理，将 http 转换为 https ）。

由于 skynet 有自己的 socket 模型，无法直接读写系统的 socket fd 。传统的 https 库，例如 libcurl 不太合适。那样会在读写时阻塞服务。

openssl 的 tls 连接是基于 BIO 抽象的，只需要利用 skynet 的 socket api 读写数据，转发到内存 BIO 上，就可以让上层完成加密通讯。

可参考： http://roxlu.com/2014/042/using-openssl-with-memory-bios  Using OpenSSL with memory BIOs

目前我暂时没有精力做这个，希望有人可以做一下。

btw， 这其实是为 lua 实现一个易用的 tls 连接库，不依赖具体 socket api 。不限于给 skynet 使用。

**Comment by kingbird2011** [comment]
之前我在网上找到一个 https://github.com/chenweiqi/lua_httpsc 这个的，但是他用的是系统的socket
我用了一个专门的服务做https的c端，这个阻塞是不是只会阻塞这个专门的服务？
如果是这样的话，那用起来还可以接受。。。

**Comment by cloudfreexiao** [comment]
是否可以参考 luasec 中 ssl 部分？
 [luasec](https://github.com/brunoos/luasec)

**Comment by lvzixun** [comment]
我找时间给完善了下， https://github.com/cloudwu/skynet/pull/949 现在是支持tls的client和server。 server那边实现的比较简单，但是感觉client应该足够用了。麻烦谁能review下？ ;)
