### ISSUE TITLE
snax服务init循环调用导致死锁的问题

### ISSUE THREAD

**Issue by najoast** [cloudwu/skynet#944]
## 问题描述
有两个snax服务`testsnax1`和`testsnax2`，服务1的`init`函数中调用`snax.uniqueservice("testsnax2")`, 而服务2的`init`函数中再调用`snax.uniqueservice("testsnax1")`, 这两个服务就死锁了，都启动不了。

## 示例
```lua
-- testsnax1.lua
function init()
    print("testsnax1 init 1")
    require("skynet.snax").uniqueservice("testsnax2")
    print("testsnax1 init 2")
end

-- testsnax2.lua
function init()
    print("testsnax2 init 1")
    require("skynet.snax").uniqueservice("testsnax1")
    print("testsnax2 init 2")
end

-- main.lua
local skynet = require "skynet"
skynet.start(function()
    local snax = require "skynet.snax"
    snax.uniqueservice("testsnax1")
    skynet.exit()
end)
```

## 原因分析
snax.uniqueservice 最终会 call 到 service_mgr.lua 里去创建服务，当1服务先创建时，会阻塞在 `request` 函数的第一行 `pcall` 那，这个`pcall`调用的是`snax.rawnewservice`, 而这里面在调用`skynet.newservice`之后会立即`skynet.call` snaxd服务的init函数，这里面再去创建snax2服务，而这里面又会调用`snax.uniqueservice("testsnax1")`，这里面最终会阻塞在 service_mgr.lua 的 `waitfor` 函数的 `skynet.wait` 那一行。

就这样服务1的初始化函数等待服务2初始化完成，而服务2又等待服务1初始化完成，死锁在这里了。

## 大致流程
```
main(main()) -> snax.uniqueservice("testsnax1") ->

service_mgr(cmd.LAUNCH) -> snax.rawnewservice("testsnax1") -> skynet.call(testsnax1, "snax", system.init) ->

testsnax1(init()) ->  snax.uniqueservice("testsnax2") ->

service_mgr(cmd.LAUNCH) -> snax.rawnewservice("testsnax2") -> skynet.call(testsnax2, "snax", system.init) ->

testsnax2(init()) -> snax.uniqueservice("testsnax1") ->

service_mgr(cmd.LAUNCH) -> waitfor -> skynet.wait
```

## 是否是业务层的错误用法？
我知道业务层写出这种循环引用的代码是不应该的，但现在积重难返，如果要改业务层可能改动量比较大。我尝试过在 snaxd 里把 initfunc 用skynet.fork包住来解决卡住的问题，但这带来了新的问题，因为init函数不阻塞了，后续对该服务任何接口的调用，在fork出来的函数执行完之前，都是错误的。

有什么好的解决办法来解决这个问题吗？任何帮助都将不胜感激:)

**Comment by cloudwu** [comment]
如果你的 A 的初始化流程依赖 B 的初始化流程完成；且 B 的初始化流程依赖 A 的初始化流程完成；那么这个问题是无解的。

我还是建议自行封装 skynet 的基础 api 再使用。snax 是一个没有持续维护的薄封装层。

其实你的本质需求是：A 和 B 两者必须都初始化完毕，A 或 B 的任何一个才可以对外提供服务。因为，A 持有 B 的地址，如果 B 没有初始化完，那么 A 的服务就是不可用的，因为 A 的服务可能间接使用 B ；反之亦然。

所以我认为从设计上，A 和 B 就应该堪称同一个服务 C 的不同地址，你让一个服务 C 分别初始化 A 和 B，然后把地址交换发放给 A B ，才结束 C 的初始化流程；使用 A 或 B 的人都应该向 C 去索取 A 的地址或 B 的地址才对。

即，使用 A 或使用 B 的人都应该先 uniqueservice "C" ，再从 C ，query "A" 或 "B" 。由 C 的初始化部分完成 A 和 B 的初始化以及 A B 之间的握手。

**Comment by najoast** [comment]
确实是无解的，我们的业务场景跟你说的还不太一样，是属于很细枝末节的一些相互依赖，写代码的人主观上没想造成这种后果。

目前的解决办法是：
1. 把所有 snax 服务的 init 函数都改为 response.init, 对 `snax.newservice/uniqueservice` 再做一层封装，创建服务时自动调一次 response.init, 这样起码不会死锁，最多就是像函数互相调用那样死循环，比较容易查问题。
2. 在业务层找到会导致循环引用的函数，在不影响代码正确性的前提下，尽量最小范围内用 `skynet.fork` 包起来，这样把 fork 造成的影响控制在一个很小的范围内。

目前问题已经得到了解决，谢谢云大的回复：）
