### ISSUE TITLE
queryservice 跨节点查询服务失败

### ISSUE THREAD

**Issue by 0x11901** [cloudwu/skynet#945]
需求是确认节点是否存活，因此我打算在每个节点开一个服务来响应心跳，再单独开一个全局服务来发送心跳包给所有注册了的服务。

看了[这篇文章](https://github.com/cloudwu/skynet/wiki/UniqueService)后得知：

> 你可以在你设计的节点上的启动脚本中调用 `skynet.uniqueservice(true, "foobar")` 将服务启动后，然后再在其它使用它的地方调用 `skynet.queryservice(true, "foobar")` 。

我觉得思路可行，就在主节点写下代码：

```lua
local function __init__()
    skynet.uniqueservice(true, "monitor")

    local harbor = skynet.newservice("harbor")
    skynet.call(harbor, "lua", "open")

    ...

end
```

其中 `monitor` 是我想全局只有一个的服务。`harbor` 服务关键代码如下：

```lua
function harbor.open(addr)
    local monitor = skynet.queryservice(true, "monitor")
    skynet.call(monitor, "lua", "register", tool.guid())
end
```

在同一个节点上代码没有发现问题，但是打开另一个节点（新开一个 shell）后，卡在了

```bash
[:0000000a] LAUNCH snlua harbor
```

猜测为 `queryservice` 阻塞。

_skynet 版本：[Version 1.2.0](https://github.com/cloudwu/skynet/releases/tag/v1.2.0)_

**Comment by cloudfreexiao** [comment]
uniqueservice 是不跨节点的

**Comment by cloudwu** [comment]
我测试是可以的。

你可以在主节点启动了  `skynet.uniqueservice(true, "monitor")`  后，用 debug console 连接上去，输入 service 指令，查看是否注册有 `@monitor` 这个服务。所有全局服务都有 @ 前缀。

然后再子节点用 `skynet.queryservice(true, "monitor")` 检查是否能拿到地址。我做了简单的测试是可以的。

**Comment by 0x11901** [comment]
> 我测试是可以的。
> 
> 你可以在主节点启动了 `skynet.uniqueservice(true, "monitor")` 后，用 debug console 连接上去，输入 service 指令，查看是否注册有 `@monitor` 这个服务。所有全局服务都有 @ 前缀。
> 
> 然后再子节点用 `skynet.queryservice(true, "monitor")` 检查是否能拿到地址。我做了简单的测试是可以的。

我有看见`@monitor` 这个全局服务。然后子节点在 `skynet.queryservice(true, "monitor")` 调用时就阻塞了。我怀疑我可能搞错了阻塞的原因，总之我打算写一个简单的例子来复现这个问题……

**Comment by cloudwu** [comment]
在子节点的 debug console 上输入 service 是否可见 `@monitor` ？如果可见，理论上就可以 query 。

**Comment by 0x11901** [comment]
> 在子节点的 debug console 上输入 service 是否可见 `@monitor` ？如果可见，理论上就可以 query 。如果不可见，说明两个节点并不在一个集群内。
> 
> btw, 如果你主节点没有启动 `@monitor` ，但在子节点查询，那么 debug console 中使用 service 可以看到有人在 Querying 。

我连上了子节点的 debug console，使用 service 出现下面的 log

```bash
Connected to localhost.
Escape character is '^]'.
Welcome to skynet console
service
@monitor	Querying:
:0000000b stack traceback:
	[C]: in function 'skynet.profile.yield'
	./server/skynet/lualib/skynet.lua:353: in upvalue 'yield_call'
	./server/skynet/lualib/skynet.lua:373: in function 'skynet.call'
	./server/skynet/lualib/skynet.lua:632: in function 'skynet.queryservice'
	././src/harbor.lua:20: in function <././src/harbor.lua:19>
	[C]: in function 'xpcall'
	././src/harbor.lua:40: in upvalue 'f'
	./server/skynet/lualib/skynet.lua:138: in function <./server/skynet/lualib/skynet.lua:110>
clusterd	:00000009
<CMD OK>
```

**Comment by 0x11901** [comment]
这里我写了个简单的 repo 复现这个问题：[issue945](https://github.com/cloudwu/skynet/issues/945)

**Comment by cloudwu** [comment]
你这个并不是 master slave 模式，而用的 cluster , 它们原本就不互通。

cluster 是去中心的，没有中心服务器做管理，需要你自己做。

**Comment by cloudwu** [comment]
简单说，你用的 cluster 模式。cluster 模式下，任何集群内服务地址都是由节点名 + 地址决定的。不可能直接用 skynet.queryservice 获得另一个节点上的服务地址，直接通讯。

**Comment by 0x11901** [comment]
> 简单说，你用的 cluster 模式。cluster 模式下，任何集群内服务地址都是由节点名 + 地址决定的。不可能直接用 skynet.queryservice 获得另一个节点上的服务地址，直接通讯。

# 十分感谢！

_随便请问一下在 cluster 模式下如何建一个全局服务（单例）或者类似的东西，可以让所有节点都访问到！_

*或者有没有什么好的建议可以让我做一个监控各个节点是否存活的机制，领导说直接查询会阻塞，他不想要阻塞……刚刚接触服务端这块快被虐哭了 (。_。)*

*也不敢直接问领导，会暴露我春节全摸鱼了根本没有学习的事实  _(:3」∠)_*

**Comment by cloudwu** [comment]
节点有名字啊，把一个具名节点当成中心节点，在上面起服务部就是全局服务了。

不想阻塞就通知。有一个检测服务阻塞，发现节点下线就通知订阅的人。

**Comment by 0x11901** [comment]
> 节点有名字啊，把一个具名节点当成中心节点，在上面起服务部就是全局服务了。
> 
> 不想阻塞就通知。有一个检测服务阻塞，发现节点下线就通知订阅的人。

我试试这个思路！今天一直在搞另一个问题……总之哭了😢再次感谢🙏
