### ISSUE TITLE
未知原因内存缓慢增长

### ISSUE THREAD

**Issue by 0x11901** [cloudwu/skynet#946]
## 问题描述

项目在 skynet 基础上增加了对 websocket 的支持，目前准备进行压测，但是有一个内存增长问题始终无法定位问题所在

目前项目中只涉及到消息的发送、转发和接收，并没有任何其他逻辑。在开启 100 个客户端 socket 连接后，skynet 占用内存呈稳定缓慢上升趋势，并且并不会释放。

我已经尝试构造了一个[测试用例: https://github.com/0x11901/issue946](https://github.com/0x11901/issue946)

推测是使用 skynet 的方法出错了。用到的 C 库已经测试过并未发现内存泄露，但为了保险起见也一并放进了 repo 中。

希望能得到帮助！

**Comment by firedtoad** [comment]
clang address santinize 值得拥有

0x11901 <notifications@github.com> 于2019年2月21日周四 下午6:28写道：

**Comment by cloudwu** [comment]
用 debug console 查看 mem 的变化，定位。

**Comment by 0x11901** [comment]
好，我今天努力定位一下！

**Comment by qq190219044** [comment]
我运行了你的代码,并用 websocket-bench -a 1000 -c 100 url 测试了下.
在代码中添加了一行: skynet.newservice("debug_console", 8800)
实际观测, 在连接断开后,用debug mem/cmem观测,并未有异常增长.
但是top观测的mem确实是会增长,虽然连接都断开了,但内存从12M->70M.
我觉得这top的mem增长可能是正常的,毕竟你虽然在lua层释放了,但程序可能并未真正释放给操作系统.
在反复测试连接断开websocket的过程中,这个内存也未见持续增长.

你这边测试有结果了再反馈下吧.

**Comment by 0x11901** [comment]
> 我运行了你的代码,并用 websocket-bench -a 1000 -c 100 url 测试了下.
> 在代码中添加了一行: skynet.newservice("debug_console", 8800)
> 实际观测, 在连接断开后,用debug mem/cmem观测,并未有异常增长.
> 但是top观测的mem确实是会增长,虽然连接都断开了,但内存从12M->70M.
> 我觉得这top的mem增长可能是正常的,毕竟你虽然在lua层释放了,但程序可能并未真正释放给操作系统.
> 在反复测试连接断开websocket的过程中,这个内存也未见持续增长.
> 
> 你这边测试有结果了再反馈下吧.

没有什么进展，下周再看看……

**Comment by qq190219044** [comment]
是找到原因了么?

**Comment by 0x11901** [comment]
> 是找到原因了么?

没有，但是换了一种思路实现了 websocket 之后内存占用可以接受了……感觉应该是 websocket 哪里写错了，和 skynet 应该是无关的。
