### ISSUE TITLE
skynet的信号处理函数SIG是否应该加个volatile更合适点？

### ISSUE THREAD

**Issue by iamjokerjun** [cloudwu/skynet#950]
static int SIG = 0;

static void
handle_hup(int signal) {
	if (signal == SIGHUP) {
		SIG = 1;
	}
}
处理信号的函数SIG。这个是否应什么为volatile sig_atomic_t更合适点呢，毕竟可能信号处理函数里修改的，优化后可能程序总读取的SIG一直在寄存器里的。信号处理函数修改的SIG是主存里的。

**Comment by cloudwu** [comment]
SIG 仅在 static 函数 `thread_timer` 里读取，没有暴露。

volatile 影响的是编译器优化行为，我确定这里编译器不可能做错误的优化。
