### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by sheldonzeng** [cloudwu/skynet#951]
建议在skynet增加一个接口等待所有挂起的co完成，停服的时候要等待所有挂起的co都完成后才可以干净的关掉服务，就像hread join一样，关服等待所有线程退出才关掉服务，关服我自己现在是这样处理的，在skynet加了个等待所有co完成的接口，但是我觉得这个应该是普遍需要的需求，可以skynet自己提供

**Comment by sheldonzeng** [comment]
还有能不能提供一个注册一个处理系统信号的lua接口，用于关服接收信号，如果用http接口接收关服信号，远程批量操作会有问题，现在我是修改了c代码注册了一个信号处理，如果可以不用修改框架代码那是最好的

**Comment by cloudwu** [comment]
我认为可以上层解决的都不必在底层实现。

**Comment by cloudwu** [comment]
目前 debug console 已经有非常丰富的手段接收运维指令，如果依旧不够用，可以自己写额外服务。
