### ISSUE TITLE
Multicast C内存泄漏。

### ISSUE THREAD

**Issue by teahouse** [cloudwu/skynet#952]
启动两个skynet进程，以master组网，a进程创建广播句柄channel=Multicast.new(), b进程从a进程中获取到广播句柄进行广播，然后debug_console查看cmem内存，发现b进程的发送广播的服务的C内存一直在涨。
a进程核心代码：
local skynet = require "skynet"
local dc = require "skynet.datacenter"
local mc = require "skynet.multicast"
skynet.start(function()
	local channel = mc.new()
	print("New channel", channel)
	dc.set("MCCHANNEL", channel.channel)	-- for multi node test
	channel:publish("Hello World")
end)
b进程核心代码：
local function onTick(mchandler)
	print("====onTick===")
	mchandler:publish("Remote message2222")
	mchandler:publish("Remote message3333")
	skynet.timeout(200, function()
		onTick(mchandler)
	end)
end
skynet.start(function()
	print("remote start")
	local channel = dc.get "MCCHANNEL"
	print("remote channel", channel or "nil")
	mchandler = mc.new {
		channel = channel ,
		dispatch = function(...) 
			print("======>", ...)
		end,
	}
	onTick(mchandler)
end)

**Comment by teahouse** [comment]
最新v1.2.0 (2018-11-6)版本

**Comment by cloudwu** [comment]
谢谢，这有个漏释放的指针。已修复。

**Comment by teahouse** [comment]
哈哈，谢谢，找了我几天了！！！
