### ISSUE TITLE
luafilesystem(lfs) 这个怎么编译到SKYNET的lua版本中

### ISSUE THREAD

**Issue by joymenu** [cloudwu/skynet#955]
现在想读取某一个目录下面的文件列表,调查发现有个lfs,但是skynet内置的LUA中没有这个.这个怎么处理比较好?

**Comment by cloudfreexiao** [comment]
自己添加 c 扩展
[例子](https://github.com/cloudfreexiao/RillServer/blob/master/lualib-src/Makefile#L31)

**Comment by joymenu** [comment]
以后skynet升级,还要和skynet做merge,担心以后的管理成本,还是说没有理解你的意思 @cloudfreexiao

**Comment by LokerLi** [comment]
直接io.popen("ls "..path) 简单

**Comment by cloudfreexiao** [comment]
这项目不就是个 例子嘛？ 把 skynet 做 submodule

**Comment by joymenu** [comment]
谢谢,搞定 @cloudfreexiao

**Comment by cloudfreexiao** [comment]
搞定了 就 关 下 issue 呗
