### ISSUE TITLE
服务器的load average值波动很大

### ISSUE THREAD

**Issue by joymenu** [cloudwu/skynet#957]
服务器是虚拟机,CPU有4核,内存4G

MMORPG游戏,压测试场景:
压力测试:400个人同时在线,1S移动一次,每次都是给所有的用户广播.通讯协议是websocket
发现load average,可以从2跳动到5.

想问下thread数量应试怎么设置?或是有其他的建议,或是有没有其他的DEBUG工具.

**Comment by cloudwu** [comment]
https://github.com/cloudwu/skynet/wiki/Config
