### ISSUE TITLE
get_time函数重名

### ISSUE THREAD

**Issue by sheldonzeng** [cloudwu/skynet#958]
get_time函数重名了，skynet.hpc实际调用的是lua-profile.c的get_time函数，结果是错误的
https://github.com/cloudwu/skynet/blob/1d4308f33af66269faf11dd29ee91315aeb599ea/lualib-src/lua-profile.c#L20

https://github.com/cloudwu/skynet/blob/1d4308f33af66269faf11dd29ee91315aeb599ea/lualib-src/lua-skynet.c#L26

https://github.com/cloudwu/skynet/blob/1d4308f33af66269faf11dd29ee91315aeb599ea/lualib-src/lua-skynet.c#L410

https://github.com/cloudwu/skynet/blob/1d4308f33af66269faf11dd29ee91315aeb599ea/lualib-src/lua-skynet.c#L508

**Comment by sheldonzeng** [comment]
https://github.com/cloudwu/skynet/blob/1d4308f33af66269faf11dd29ee91315aeb599ea/lualib-src/lua-skynet.c#L410

**Comment by ylme** [comment]
但是函数名字前面是 static ，这两个文件中的 get_time 函数对外都是不可见的，链接器到一个可执行文件中，也是不同的两个函数，没有问题的。

**Comment by sheldonzeng** [comment]
> 但是函数名字前面是 static ，这两个文件中的 get_time 函数对外都是不可见的，链接器到一个可执行文件中，也是不同的两个函数，没有问题的。

是我测试错误，clock_gettime在Red Hat 4.4.7-16版本返回的结果有误
static int64_t
get_time() {
#if !defined(__APPLE__) || defined(AVAILABLE_MAC_OS_X_VERSION_10_12_AND_LATER)
	struct timespec ti;
	clock_gettime(CLOCK_MONOTONIC, &ti);
	return (int64_t)1000000000 * ti.tv_sec + ti.tv_nsec;
#else
	struct timeval tv;
	gettimeofday(&tv, NULL);
	printf("get_time %d%d%d\n", tv.tv_sec, tv.tv_usec,(int64_t)1000000000 * tv.tv_sec + tv.tv_usec * 1000);
	return (int64_t)1000000000 * tv.tv_sec + tv.tv_usec * 1000;
#endif
}
