### ISSUE TITLE
clusterd报错

### ISSUE THREAD

**Issue by sheldonzeng** [cloudwu/skynet#962]
如果在open过程中出错了，对方关闭连接后会报错，agent是nil，因为open出错会清除agent
1、清除agent：
https://github.com/cloudwu/skynet/blob/9ffdf2dbde20934a74b0d5959249c2aaaa14c863/service/clusterd.lua#L230

2、报错地方：
https://github.com/cloudwu/skynet/blob/9ffdf2dbde20934a74b0d5959249c2aaaa14c863/service/clusterd.lua#L239

**Comment by cloudwu** [comment]
subcmd 先后收到 error 和 close ?

**Comment by cloudwu** [comment]
我觉得把 or subcmd == "error" 去掉即可。

**Comment by sheldonzeng** [comment]
> subcmd 先后收到 error 和 close ?

是的，连接过程中收到一个error，对方关闭后再收到一个close，我觉得在这里判下空好一些
https://github.com/cloudwu/skynet/blob/9ffdf2dbde20934a74b0d5959249c2aaaa14c863/service/clusterd.lua#L239
