### ISSUE TITLE
更新cluster分支的内容后,snax的post失效问题

### ISSUE THREAD

**Issue by lf723** [cloudwu/skynet#967]
2019.3.26更新到最新的master分支后，原先的snax的跨节点的rpc失效
1、查看为clusterproxy.lua中当session == 0时，默认向clusterd服务发送push请求
2、但是clusterd.lua中的common.push函数已经移除
3、在lua-skynet.c中如果是跨进程的rpc，session默认为0

具体报错如下：

[:0000000e] lua call [12f to :e : 0 msgsz = 24] error : ./3rd/skynet/lualib/skynet.lua:615: ./3rd/skynet/lualib/skynet.lua:181: ./3rd/skynet/service/clusterd.lua:212: assertion failed!
stack traceback:
	[C]: in function 'assert'
	./3rd/skynet/service/clusterd.lua:212: in upvalue 'f'
	./3rd/skynet/lualib/skynet.lua:138: in function <./3rd/skynet/lualib/skynet.lua:110>
stack traceback:
	[C]: in function 'assert'
	./3rd/skynet/lualib/skynet.lua:615: in function 'skynet.manager.dispatch_message'

是故意这样修改设计的吗？ 原先的封装需要更改？还是疏漏？

**Comment by cloudwu** [comment]
改漏了，现在应该好了。

**Comment by cloudwu** [comment]
btw， 这个 bug 原本在分支上就改过了，我们本地的 fork 是有的。不知道为什么在合并的时候丢了一个 commit 。
