### ISSUE TITLE
Redis Watch 报错

### ISSUE THREAD

**Issue by zhushaojun65** [cloudwu/skynet#970]
> 
    while true do
        local message, channel = this.watch:message()
    end

该逻辑在skynet.fork中运行, 程序放置一段时间后, 会报如下错误:

![image](https://user-images.githubusercontent.com/6133340/55052665-b5fab880-5094-11e9-85f8-e2b73d1bad32.png)

这个watch还需要自己维持一个类似于心跳一样的逻辑吗?

**Comment by cloudwu** [comment]
先检查连接为什么会出错。

如果一定会发生，那么自己处理出错后的重新连接。
