### ISSUE TITLE
需求一个可以得知 Cluster 节点是否存在的API

### ISSUE THREAD

**Issue by findix** [cloudwu/skynet#971]
Hi 云风，

我需要在登陆服务随机选择一个游戏服务后，判断这个节点是否存在，如果不存在则换一个节点。

不能通过给游戏服务发送一条不返回（ignoreret）的消息的方式来进行健康检查是因为，为了让登陆服务做到无状态，游戏服务的节点信息是存在redis里面的。如果做检查的服务异常退出，就会在redis中遗留节点信息，还是需要有办法判断节点是否存在。

参考 #803 之后我已经了解可以通过在 clustername.lua 中设置`__nowaiting = true` 来完全取消cluster.call调用的等待功能，但是有些时候可以忽略节点启动顺序还是一个很不错的特性，我只是需要有些调用可以允许我选择是否节点不存在立即失败，或者更直接的有一个API可以让我查询这个节点是否存在。

谢谢~~

**Comment by cloudwu** [comment]
你可以做自己做一个中心服务，每个 node 启动起来就去注册一下，然后向它查询。

组网是个相当复杂的工作，最好是结合自己的需求，有取舍的来做。

**Comment by findix** [comment]
了解了，确实可以向中心服务查询取代直接查询。
非常感谢~~
