### ISSUE TITLE
dns parse /etc/hosts 没有考虑注释和空行

### ISSUE THREAD

**Issue by findix** [cloudwu/skynet#975]
Hi  云风，

最新 Commit 遇到一个问题希望反馈一下~

https://github.com/cloudwu/skynet/blob/305a29d8859faab7d2d554af6f2f82e2a828bcb1/lualib/skynet/dns.lua#L115-L123

这里好像没有考虑到`/etc/hosts`文件中可能出现空行与注释（#）行，导致`match`结果为`nil`，调用`guess_name_type`时报错。

同样，
https://github.com/cloudwu/skynet/blob/305a29d8859faab7d2d554af6f2f82e2a828bcb1/lualib/skynet/dns.lua#L145-L160

`/etc/resolv.conf`文件也可能会有注释（#），按照当前的写法是即使注释了，也是会match的。

感谢~~

**Comment by cloudwu** [comment]
现在 ok 了？

**Comment by findix** [comment]
hosts 可以了。
resolv 好像还是不能忽略注释

https://github.com/cloudwu/skynet/blob/305a29d8859faab7d2d554af6f2f82e2a828bcb1/lualib/skynet/dns.lua#L156
```lua
> server = string.match("# nameserver 127.0.0.1","%s*nameserver%s+([^#;%s]+)");print(server)
127.0.0.1
> server = string.match("#nameserver 127.0.0.1","%s*nameserver%s+([^#;%s]+)");print(server)
127.0.0.1
```

**Comment by cloudwu** [comment]
@xjdrew   看看忽略注释的问题？

**Comment by xjdrew** [comment]
解析resolv.conf是继承下来的代码：https://github.com/xjdrew/skynet/commit/a9b1993686ae0cb46336352dae2493ff01e2a11a#diff-120dbda6d8edd9193017109d570ca0eaR245

确实没忽略注释，我改下。
