### ISSUE TITLE
master版本mongo driver的collection:safe_update问题与connection string问题

### ISSUE THREAD

**Issue by sabearcher** [cloudwu/skynet#978]
2. 

使用mongo driver连接副本集或分片集群的多节点时，无法使用connection string，只能直接连接一个节点，请问要如果修改？

> [https://docs.mongodb.com/manual/reference/connection-string](https://docs.mongodb.com/manual/reference/connection-string)

我们需要连接多mongos的集群，官方的连接方式是这样的：

> mongodb://mongodb1.example.com:27317,mongodb2.example.com:27017/?replicaSet=mySet&authSource=authDB

---------------

3.

在使用最新的skynet中，发现了mongo driver的一个新问题，werror函数的逻辑中，r.ok为0，但是没有writeErrors与writeConcernError属性，会引发报错
```

/root/skynet-5-28/lualib/skynet/db/mongo.lua:366: attempt to index a nil value (field 'writeConcernError')
stack traceback:
	/root/skynet-5-28/lualib/skynet/db/mongo.lua:366: in function </root/skynet-5-28/lualib/skynet/db/mongo.lua:358>
	(...tail calls...)
	../luaservices/common/data/libdatabase.lua:92: in field 'add'
	../luaservices/lgc_frame/data/pstinf.lua:61: in field '?'
	../luaservices/lgc_frame/data/pstinf.lua:102: in upvalue 'f'
	/root/skynet-5-28/lualib/skynet.lua:138: in function </root/skynet-5-28/lualib/skynet.lua:110>
stack traceback:
	[C]: in function 'assert'
	/root/skynet-5-28/lualib/skynet.lua:615: in function 'skynet.dispatch_message'

```

本地系统
> CentOS  Linux release 7.1.1503 (Core) 

lua版本
> Lua 5.1.4

------------

**Comment by cloudwu** [comment]
rawget(mongo_collection, key) 为什么为空， mongo_collection 里不是有 safe_update 方法吗？

**Comment by sabearcher** [comment]
well，是我boot.path忘了修改了，请无视问题1，直接看看后面的问题吧

**Comment by hanxi** [comment]
第3个问题可以自己调试解决的，把 r 里面的内容打印出来。好像有个 `r.errmsg`

**Comment by sabearcher** [comment]
是有的，那我就增加这个判断

**Comment by cloudwu** [comment]
不明白在说啥，所以还是自己看源码解决好了。

**Comment by sabearcher** [comment]
没问题，主要需要解决的还是第二个问题，连接多节点的connection string方案怎么做呢

**Comment by sabearcher** [comment]
云风，问题3我可以自己改源码解决，请教问题2要如何处理，我了解到官方的mongorover有支持这种连接方式

**Comment by cloudwu** [comment]
我不懂 mongo , 你可以自己实现，提个 pr

**Comment by sabearcher** [comment]
OK，那我自己这边看看吧，单可以关了
