### ISSUE TITLE
连续用相同参数调用cluster.proxy会产生多个service实例

### ISSUE THREAD

**Issue by wanliyun** [cloudwu/skynet#979]
Hi  云大
       偶然在debug_console里看到了多个参数一样的clusterproxy，并没有影响到业务层。问下是否设计初衷如此？有没有必要像cluster.sender一样处理一下（保证单例）?

感谢！

**Comment by cloudwu** [comment]
你看看这么改行么？

**Comment by wanliyun** [comment]
测试了~OK的！多谢！！
