### ISSUE TITLE
datasheet 退出异常

### ISSUE THREAD

**Issue by wushimang886** [cloudwu/skynet#981]
使用的1.20版本 skynet
我这边 有一个服务器 创建 builder.new 创建 datasheet
然后一个账号连接 一个 account 服务，里面 有调用 datasheet.query 
来获取数据。
实际在线上运行 会出现 account 服务器退出之后， datasheet 出现报错。
具体 报错信息如下：

00:00:01 : [:00007433] KILL self
00:00:01 : [:0000000b] lua call [7433 to :b : 0 msgsz = 9] error : [31m./lualib/skynet.lua:638: ./lualib/skynet.lua:196: ./lualib/skynet/datasheet/builder.lua:75: attempt to index a nil value (local 'h')
stack traceback:
	./lualib/skynet/datasheet/builder.lua:75: in upvalue 'releasehandle'
	./lualib/skynet/datasheet/builder.lua:130: in field '?'
	./lualib/skynet/datasheet/builder.lua:146: in upvalue 'f'
	./lualib/skynet.lua:154: in function <./lualib/skynet.lua:126>
stack traceback:
	[C]: in function 'assert'
	./lualib/skynet.lua:638: in function 'skynet.dispatch_message'[0m

00007433 这个服务 就是 account 服务。 当这个服务退出之后 就会出现这个报错。
而且，这个报错也不是必现。 偶尔会出。

**Comment by cloudwu** [comment]
是不是 release 那里的 handle 为 nil ?

**Comment by wushimang886** [comment]
我看代码 应该是handle 为空
但是，我不太清楚 为什么会导致这种情况发生。
我在accoun 服务里面 只有 datasheet.query 调用。

**Comment by cloudwu** [comment]
还没有等到 query 的回应时就退出，会导致 handle 为空。看一下我在分支上的修复。

**Comment by wushimang886** [comment]
好的 谢谢
