### ISSUE TITLE
socket_server.c for VC 

### ISSUE THREAD

**Issue by car520120** [cloudwu/skynet#982]
能否在执行 socket_server_create 初始化 struct socket_server *ss = MALLOC(sizeof(*ss)); 后加上
memset(ss, 0, sizeof(*ss)); //vc if no memset  ss then reserve_id is endless loop!
要不，我在VC上每次同步你的代码都是会导致 llisten 中调用  reserve_id 函数时会死循环！
注意是VC版本来的！我是新手主要是用VS来学习的！

**Comment by cloudwu** [comment]
1. 原因是什么？
2. 你可以换掉 MALLOC 这个宏。

**Comment by car520120** [comment]
目前在VS中调试中  ATOM_CAS(&s->type, SOCKET_TYPE_INVALID, SOCKET_TYPE_RESERVE)
如果前面不执行 memset ， s->type 的值就不会置位！但是我断点看到s->type 默认值 都是 0（执不执行memset结果都是一样的），所以我也不没有定到位问题，只是 memset 后就神奇的解决这个了！感觉有可能是别的地址也使用了这个引用！可能是野指针！但我读了好几次代码都没有找到！所以不太确认问题所在！我在VC中是使用SOCKET代替了管道的！不知道是不是问题出在这的！CPOLL 代替了EPOLL ！其它都是一样的了！
出现这种情况可能是平台特性吧！还是别的原因目前还不太清楚！也许是我改得遗漏了什么地方！
ATOM_CAS 宏如下
__declspec(naked) char __sync_bool_compare_and_swap(int *p, int value, int compare) {
	__asm {
		push	ebp
		mov		ebp,esp
		mov		ecx,[compare]
		mov		eax,[value]
		mov		edx,[p]
		lock	cmpxchg [edx],ecx
		sete	al
		movzx	eax,al
		pop		ebp
		ret
	}
}
你最新的是支持 mingw 了吗？socket 是  skynet 的必要模块！不知道改成如下面会有不会有BUG：
 在启动方便时间消耗上差不了多少的？可以精简一下代码！效率上应该差不了多少的！
	struct socket_server *ss = MALLOC(sizeof(*ss));
	memset(ss, 0, sizeof(*ss)); //vc if no memset  ss then reserve_id is endless loop!
	ss->time = time;
	ss->event_fd = efd;
	ss->recvctrl_fd = fd[0];
	ss->sendctrl_fd = fd[1];
	ss->checkctrl = 1;

#if 0 != SOCKET_TYPE_INVALID
	for (i=0;i<MAX_SOCKET;i++) {
		struct socket *s = &ss->slot[i];
		s->type = SOCKET_TYPE_INVALID;
		clear_wb_list(&s->high);
		clear_wb_list(&s->low);
		spinlock_init(&s->dw_lock);
	}
	ss->alloc_id = 0;
	ss->event_n = 0;
	ss->event_index = 0;
	memset(&ss->soi, 0, sizeof(ss->soi));
	FD_ZERO(&ss->rfds);
#endif
MALLOC 替换宏是最方便的！不过也不是所有地方都是需要初始化的！估计你设计之初也是想少操作一下！提高效率的...你的这个项目是有应用到生产环境上的了是吧！

**Comment by car520120** [comment]
![image](https://user-images.githubusercontent.com/36702004/55969552-94164e00-5cb0-11e9-9d59-06c3ed805681.png)
这是没有memset 执行时的结果

**Comment by G0561** [comment]
兄弟， 为何你一定要用vs 来运行skynet

**Comment by CoolDesert** [comment]
真想断点调试的话，建议使用 vscode，不需要改源码。

**Comment by hanxi** [comment]
看到有人写了vscode插件来调试skynet，在知乎上看到的，去搜搜吧。
