### ISSUE TITLE
关于SSL_read

### ISSUE THREAD

**Issue by seconemouse** [cloudwu/skynet#984]
我增加了一个 websocket+ssl的网关.需要修改socket_server.c.
之前的socket_server_poll每次调用会把收到的数据记录在result里面,
epoll使用了LT模式,当数据没有读完的时候重复执行socket_server_poll能触发读,然后每次收到的数据按2倍的容量扩大. 
但是使用了SSL_read之后,可能数据已经被读取到SSL这一层,所以缓存里没有数据了.socket_server_poll就不会再触发读事件.
目前来看可能只有一次性把数据读取完.
要么把socket_message改成链表形式存储多个,要么就在读取时,反复扩大p.size,直到大于SSL里的字节数(这里可能需要重复分配和释放内存,还要限制最大字节)
还有其他方法吗??

**Comment by cloudwu** [comment]
See https://github.com/cloudwu/skynet/pull/949

**Comment by seconemouse** [comment]
学习了,原来是BIO
