### ISSUE TITLE
怎么获取某个服务未处理请求数量？

### ISSUE THREAD

**Issue by renyankankan** [cloudwu/skynet#985]
你好，我在处理服务退出相关的工作，在退出前要确保服务的所有请求操作全部完成，请问怎么获取服务挂起的协程的数量？

**Comment by cloudwu** [comment]
不建议通过确认所有请求完成来退出，容易死锁。

如果想获取，可以调用 `skynet.task(ret_table)` 或 `skynet.call(addr, "debug", "TASK")` 。具体参考源码。

**Comment by renyankankan** [comment]
谢谢云大解答
