### ISSUE TITLE
大并发情况下，skynet基础例子main.lua的watchdog服务疑似内存泄露问题

### ISSUE THREAD

**Issue by qpxzhang** [cloudwu/skynet#995]
云风你好，最近开始使用skynet。一开始先测试了推荐的main.lua服务，该服务主要启动了
protoloader/simpledb/console/debug_console/simpledb/watchdog
由watchdog启动gate和agent。gate中调用gateserver处理消息转发问题。
主要想测试下在大并发下该框架的稳定性。讲main.lua中的max_client设置为1024.
用C写了客户端，客户端开线程连接服务器1024次后，sleep 1秒，继续循环连接。
前10个连接上发送set  echo xxxxxxxxxxxxxxxxxxxxxxx给simpledb，后面所有连接都只发送get echo指令。所有连接存活3秒后断开。 

通过控制台发现，watchdog服务的cmem一直稳定增长。clearcache和gc无法释放cmem。
程序运行一天后，watchdog的cmem增长到1.2个G。watchdog的cmem大概每10分钟增加15MB左右内存。

之前怀疑是watchdog中的connection表，删除时直接置nil不会释放，后来增加了该表的释放函数，并且用mem看，发现其lua内存非常小，保持在10MB。但cmem一直在增加。同时内存一直增加的还有3号服务：[:01000003] LAUNCH snlua launcher。但该服务增加幅度没有watchdog大。

请问会是什么原因？求教大神，已经困扰我很多天了，非常头疼。

C语言程序如下：
主函数中循环连接部分：
int i=0;
while(1)//0为连接成功
{
     i++;	    
     pthread_t thid;
     int th_flag=pthread_create(&thid, NULL, connect_func, (void*)i);	
     if(th_flag) printf("th failed, i=%d\n",i);
      if(i%1024==0)    sleep(1);
}	

connect_func如下：
char setecho[]=//set echo xxxxxxxxx 命令的打包结果，不再打包直接发送
{0x00,0x97,0x55,0x02,0x08,0x06,0x02,0x10,0x04,0x1F,0x65,0x63,0x68,0x6F,0x87,0xFF,0x10,0x49,0x20,0x61,0x6D,0x20,0x74,0x68,0x72,0x65,0x61,0x64,0x20,0x30,0x30,0x36,0x30,0x2E,0x20,0x74,0x68,0x65,0x20,0x71,0x75,0x69,0x63,0x6B,0x20,0x62,0x72,0x6F,0x77,0x6E,0x20,0x66,0x6F,0x78,0x20,0x6A,0x75,0x6D,0x70,0x65,0x64,0x20,0x74,0x68,0x65,0x20,0x6C,0x61,0x7A,0x79,0x20,0x64,0x6F,0x67,0x21,0x20,0x68,0x61,0x68,0x61,0x68,0x68,0x61,0x20,0x7A,0x68,0x61,0x6E,0x67,0x71,0x69,0x6E,0x67,0x20,0x70,0x6F,0x20,0x6C,0x69,0x20,0x63,0x68,0x75,0x6E,0x20,0x6C,0x65,0x69,0x20,0x77,0x61,0x6E,0x67,0x6C,0x69,0x79,0x65,0x20,0x6C,0x69,0x61,0x6E,0x67,0x77,0x65,0x69,0x20,0x77,0x61,0x6E,0x67,0x71,0x69,0x20,0x73,0x6B,0x79,0x6E,0x65,0x74,0x20,0x61,0x67,0x65,0x6E,0x74,0x20,0x74,0x65,0x73,0x74,0x21,0x00}; 
char getecho[]=//get echo的打包结果，直接发送
{0x00,0x0C,0x55,0x02,0x06,0x08,0x01,0xC4,0x04,0x65,0x63,0x03,0x68,0x6F};
void* connect_func(void* arg)
{
	int TID=(int)arg;
	pthread_detach(pthread_self());
	struct sockaddr_in servaddr;
	int sockfd;	
	sockfd = socket(AF_INET, SOCK_STREAM, 0);     
	bzero(&servaddr, sizeof(servaddr));
	servaddr.sin_family = AF_INET;
	inet_pton(AF_INET, "10.0.0.66", &servaddr.sin_addr);
	servaddr.sin_port = htons(SERV_PORT); 										
	if(connect(sockfd, (struct sockaddr *)&servaddr, sizeof(servaddr))!=0) 
	{    	
    	        printf("cannot connect the host);    		
	}
	else
	{
         	printf("connect  Success!\n");    	    
      	        if(TID<10 ) write(sockfd, setecho, sizeof(setecho)); 
               else         write(sockfd, getecho, sizeof(getecho)); 
    		sleep(3);
		close(sockfd);
		printf("Thread %d quit\n",TID);//sin_port是ushort类型
	}
	return (void*)0;
}

**Comment by qpxzhang** [comment]
补充，我用的是2019年3月20日左右的版本。
刚才下了新版本，今天晚上再测试一下。

**Comment by cloudwu** [comment]
上个月有一个中间版本是有问题的，试试最新版本。另外建议试试 ssm 分支。

具体最近的工作可以看我的 blog 。

**Comment by qpxzhang** [comment]
非常感谢快速的回复，新版本跑了一晚上后，发现cmem正常，没有出现内存不断增长的现象。
