### ISSUE TITLE
sharetable,运行不起来

### ISSUE THREAD

**Issue by renyankankan** [cloudwu/skynet#996]
切换到分支sharetable, make linux后，执行如下命令：

./skynet examples/config
[:01000002] LAUNCH snlua bootstrap
[:01000002] lua loader error : error loading module 'skynet.core' from file './luaclib/skynet.so':
	./luaclib/skynet.so: undefined symbol: luaL_loadfilex_
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	./lualib/skynet.lua:2: in main chunk
	[C]: in function 'require'
	./service/bootstrap.lua:1: in local 'main'
	./lualib/loader.lua:48: in main chunk
[:01000002] KILL self

**Comment by cloudwu** [comment]
去 3rd/lua 下 make clean 或根目录 make cleanall

**Comment by renyankankan** [comment]
从sharetable中获取的数据，next()返回的都是nil ??
